8293011: riscv: Duplicated stubs to interpreter for static calls
openjdk/jdk pull request #10057
Opened 2022-08-29 01:32 UTC by DingliZhang

Follow up [JDK-8280481](https://bugs.openjdk.org/browse/JDK-8280481), it provides duplicated stubs to interpreter for static calls.

## Testing:

- hotspot/jdk tier1 on unmatched board
- hotspot/jtreg/compiler/sharedstubs/SharedStubToInterpTest.java on qemu

## Results
#### Results from [Renaissance 0.14.0](https://github.com/renaissance-benchmarks/renaissance/releases/tag/v0.14.0)
Note: 'Nmethods with shared stubs' is the total number of nmethods counted during benchmark's run. 'Final # of nmethods' is a number of nmethods in CodeCache when JVM exited.

Because of the current hardware performance limitations and the fact that some cases crash in fastdebug mode (before applying this patch), I selected a few cases to test and reduced the number of iterations using `-r 10`. The data is sufficient to reflect the effect of the optimization.

- riscv64
```
+------------------+-------------+----------------------------+---------------------+
|    Benchmark     | Saved bytes | Nmethods with shared stubs | Final # of nmethods |
+------------------+-------------+----------------------------+---------------------+
| future-genetic   |       47824 |                       1278 |                1811 |
| scrabble         |       30616 |                        738 |                1605 |
| fj-kmeans        |       23320 |                        633 |                1386 |
| par-mnemonics    |        2840 |                        621 |                1398 |
| scala-kmeans     |       19544 |                        381 |                1365 |
+------------------+-------------+----------------------------+---------------------+
```

2022-08-29 02:42 UTC, feilongjiang requested changes
Changes look good, except for one copyright issue.

2022-08-29 02:42 UTC, feilongjiang commented on src/hotspot/cpu/riscv/codeBuffer_riscv.cpp
> + * Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
Missing copyright of your company for the new file.

2022-08-29 03:26 UTC, DingliZhang commented
> Changes look good, except for one copyright issue.

Thank you, @feilongjiang!  I have added the missing copyright.

2022-08-31 09:07 UTC, RealFYang approved these changes
Looks fine.

2022-08-31 09:27 UTC, DingliZhang commented
@RealFYang @feilongjiang Thank you for the reviews!
/integrate

2022-09-01 01:04 UTC, RealFYang commented
/sponsor

2022-09-01 01:07 UTC, closed without merging