8293100: riscv: Forgot to save callee-saved FloatRegisters in StubGenerator::generate_call_stub
openjdk/jdk pull request #10095
Opened 2022-08-31 08:47 UTC by zhengxiaolinX

To be filled; Tier1~4 is under testing and tests described in JDK-8293100 are cleared.

2022-09-01 07:02 UTC, VladimirKempik commented
vmTestbase/nsk/stress/jni/jnistress002.java  now passes with this patch
Running now full tier4:hotspot ( which includes vmTestbase), will report on results later

2022-09-01 07:08 UTC, yadongw approved these changes
lgtm(not a reviewer)

2022-09-01 08:54 UTC, feilongjiang requested changes
Looks good, with one comment.

2022-09-01 08:54 UTC, feilongjiang commented on src/hotspot/cpu/riscv/stubGenerator_riscv.cpp
> +  // -33 [ saved f27            ] <--- sp_after_call
I think it's better to add some comments about saving FloatRegisters at line 124.

2022-09-01 10:31 UTC, feilongjiang approved these changes

2022-09-01 11:38 UTC, shipilev approved these changes
Looks fine.

2022-09-02 02:55 UTC, zhengxiaolinX commented
> vmTestbase/nsk/stress/jni/jnistress002.java now passes with this patch Running now full tier4:hotspot ( which includes vmTestbase), will report on results later

Hi Vladimir, my hotspot tier2~4 have passed. I was wondering if all's right with your hotspot tier4?

2022-09-02 06:38 UTC, VladimirKempik commented
Hello
Tier4:hotspot is good on thead.

2022-09-02 06:39 UTC, VladimirKempik approved these changes

2022-09-02 06:45 UTC, zhengxiaolinX commented
Thanks!
And thank you all for reviewing as always. Let's move on then.

/integrate

2022-09-02 06:59 UTC, RealFYang commented
/sponsor

2022-09-02 07:01 UTC, closed without merging