JDK-8293364: IGV: Refactor Action in EditorTopComponent and fix minor bugs
openjdk/jdk pull request #10170
Opened 2022-09-05 13:38 UTC by tobiasholenstein

Refactor the Actions in EditorTopComponent (com.sun.hotspot.igv.view.actions). Move Action specific code from EditorTopComponent to the corresponding Action.

# Fixing minor Bugs

2022-09-08 13:16 UTC, robcasloz requested changes
This changeset seems to disable the keyboard shortcuts for `Extract`, `Show all nodes`, and `Hide` right after a graph is opened. Interestingly, after clicking around for a while, the keyboard shortcuts start working again. Please let me know if you need more details to reproduce the problem, hopefully it is reproducible in other platforms than my own (Ubuntu 20.04).

2022-09-15 09:26 UTC, tobiasholenstein commented
> This changeset seems to disable the keyboard shortcuts for `Extract`, `Show all nodes`, and `Hide` right after a graph is opened. Interestingly, after clicking around for a while, the keyboard shortcuts start working again. Please let me know if you need more details to reproduce the problem, hopefully it is reproducible in other platforms than my own (Ubuntu 20.04).

Thanks for spotting that @robcasloz! Defining the `Shortcuts` in `layer.xml` is not recommended anymore and cause problems with `ContextAction`. The more modern approach is to use `@ActionXXX` annotations and define the shortcuts there.

Also, `ContextAction<DiagramViewModel>` listened only to `getDiagramChangedEvent()`. I changed them to also listened to `getViewChangedEvent()`, `getViewPropertiesChangedEvent()` and `getHiddenNodesChangedEvent()`. Otherwise the context aware action missed being updated when node selection or view changed. 

 I updated to PR description accordingly

2022-09-16 13:03 UTC, robcasloz approved these changes
I have tested the changeset again and did not find any issues, keyboard shortcuts and contextual enabling/disabling of toolbar buttons works as expected. I only have a few style comments, please consider addressing them before integration.

2022-09-19 07:38 UTC, tobiasholenstein commented on src/utils/IdealGraphVisualizer/Coordinator/src/main/java/com/sun/hotspot/igv/coordinator/actions/ImportAction.java
> +import org.openide.util.actions.CallableSystemAction;
I agree, if the file is not touched, imports should not be modified. Hopefully after https://github.com/openjdk/jdk/pull/10197 this mistake shouldn't happen anymore :)

2022-09-19 07:40 UTC, tobiasholenstein commented on src/utils/IdealGraphVisualizer/View/src/main/java/com/sun/hotspot/igv/view/EditorTopComponent.java
> +    }// </editor-fold>//GEN-END:initComponents
I reverted the change. The NetBeans' Form Editor opens it, but just shows an empty plane. I don't really know why there is an `JCheckBox jCheckBox1` if we don't use it. But let's just leave it the way NetBeans generated it.

2022-09-19 07:41 UTC, tobiasholenstein commented on src/utils/IdealGraphVisualizer/View/src/main/java/com/sun/hotspot/igv/view/actions/ExportAction.java
> - */
Done

2022-09-19 10:12 UTC, chhagedorn requested changes
I only have some code style specific comments. Otherwise, good cleanup!

2022-09-19 14:26 UTC, tobiasholenstein commented on src/utils/IdealGraphVisualizer/View/src/main/java/com/sun/hotspot/igv/view/DiagramViewModel.java
> +        if (b) {
done

2022-09-19 14:26 UTC, tobiasholenstein commented on src/utils/IdealGraphVisualizer/View/src/main/java/com/sun/hotspot/igv/view/EditorTopComponent.java
> +        TopComponent topComponent = EditorTopComponent.getRegistry().getActivated();
done

2022-09-19 14:26 UTC, tobiasholenstein commented on src/utils/IdealGraphVisualizer/View/src/main/java/com/sun/hotspot/igv/view/actions/EnableBlockLayoutAction.java
> +    EditorTopComponent editor;
done

2022-09-19 14:28 UTC, tobiasholenstein commented on src/utils/IdealGraphVisualizer/View/src/main/java/com/sun/hotspot/igv/view/actions/ReduceDiffAction.java
> +    }
Unfortunately not, we need to override it because we extend `CallableSystemAction`

2022-09-20 09:02 UTC, robcasloz approved these changes

2022-09-20 11:40 UTC, tobiasholenstein commented on src/utils/IdealGraphVisualizer/View/src/main/java/com/sun/hotspot/igv/view/EditorTopComponent.java
> +        return  scene.getModel();
done

2022-09-20 11:40 UTC, tobiasholenstein commented on src/utils/IdealGraphVisualizer/View/src/main/java/com/sun/hotspot/igv/view/EditorTopComponent.java
> +    public void selectionMode(boolean b) {
done

2022-09-20 11:42 UTC, tobiasholenstein commented on src/utils/IdealGraphVisualizer/View/src/main/java/com/sun/hotspot/igv/view/actions/ReduceDiffAction.java
> +    }
Done. I added an abstract superclass `ModelAwareAction.java`

2022-09-20 12:59 UTC, tobiasholenstein commented on src/utils/IdealGraphVisualizer/View/src/main/java/com/sun/hotspot/igv/view/EditorTopComponent.java
> +    public void componentOpened() { }
I removed it

2022-09-20 13:00 UTC, tobiasholenstein commented on src/utils/IdealGraphVisualizer/View/src/main/java/com/sun/hotspot/igv/view/actions/ExpandPredecessorsAction.java
> +            Set<Figure> oldSelection = editor.getModel().getSelectedFigures();
I agree. I created a new `ExpandAdjacentAction` superclass now

2022-09-20 13:00 UTC, tobiasholenstein commented
@chhagedorn I integrated your suggestions now

2022-09-20 13:28 UTC, robcasloz approved these changes

2022-09-21 09:10 UTC, chhagedorn approved these changes
Thanks for doing the suggested updates. Apart from two small things, it looks good to me!

2022-09-21 09:33 UTC, tobiasholenstein commented on src/utils/IdealGraphVisualizer/View/src/main/java/com/sun/hotspot/igv/view/actions/EnableBlockLayoutAction.java
> +    private final EditorTopComponent editor;
done

2022-09-21 09:33 UTC, tobiasholenstein commented on src/utils/IdealGraphVisualizer/View/src/main/java/com/sun/hotspot/igv/view/actions/ExpandAdjacentAction.java
> +    protected void expandFigures(AdjacentOperator adjacentOp) {
done

2022-09-21 09:34 UTC, tobiasholenstein commented
@chhagedorn and @robcasloz thanks for the reviews!

/integrate

2022-09-21 09:37 UTC, closed without merging