8293792: runtime/Dictionary/ProtectionDomainCacheTest.java fails with FileAlreadyExistsException: /tmp
openjdk/jdk pull request #10266
Opened 2022-09-14 09:42 UTC by DamonFool

Hi all,

runtime/Dictionary/ProtectionDomainCacheTest.java fails on Linux if `/tmp` is a symbolic link directory.
The root cause is that `JarUtils.createJarFile` [1] will throw `FileAlreadyExistsException` if `parent` is a symbolic directory.
So it seems better to test the existance of `parent` before creation.

Testing:
- tier1~3 on Linux/x64 in progress, seems fine until now

Thanks.
Best regards,
Jie

[1] https://github.com/openjdk/jdk/blob/master/test/lib/jdk/test/lib/util/JarUtils.java#L72

2022-09-14 10:10 UTC, jaikiran commented
Hello Jie,

> The root cause is that `JarUtils.createJarFile` [1] will throw `FileAlreadyExistsException` if `parent` is a symbolic directory. 

The JarUtils.createJarFile on that line uses:

```
// create the target directory
        Path parent = jarfile.getParent();
        if (parent != null) {
            Files.createDirectories(parent);
        }
```
From what I can see in the javadoc of `java.nio.file.Files.createDirectories`, it doesn't state that it will throw this exception in case of symbolic links (it actually doesn't talk about symbolic links). As per the API:

```
     * @throws  FileAlreadyExistsException
     *          if {@code dir} exists but is not a directory <i>(optional specific
     *          exception)</i>
```
So if it indeed is throwing a `FileAlreadyExistsException` then perhaps this API implementation needs a look at? I am not on a Linux system right now to test this, but would you be able to get the exact OS version and other details including the output of "ls -lh /tmp" to see what it is linked to?

2022-09-14 10:47 UTC, jaikiran commented
I could reproduce the issue with `Files.createDirectories` on a macos with a trivial program. It appears to be because of the use of `NOFOLLOW_LINKS` here https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/java/nio/file/Files.java#L808. To me this appears to be something that either needs to be clarified in the the `Files.createDirectories` API or addressed/fixed there. I have asked for inputs on this from others who have more knowledge of this area.

2022-09-14 10:51 UTC, DamonFool commented
> I could reproduce the issue with `Files.createDirectories` on a macos with a trivial program. It appears to be because of the use of `NOFOLLOW_LINKS` here https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/java/nio/file/Files.java#L808. To me this appears to be something that either needs to be clarified in the the `Files.createDirectories` API or addressed/fixed there. I have asked for inputs on this from others who have more knowledge of this area.

Okay, thanks @jaikiran .

2022-09-14 11:53 UTC, coleenp commented
/label add hotspot-runtime

2022-09-14 13:53 UTC, AlanBateman commented
> I could reproduce the issue with `Files.createDirectories` on a macos with a trivial program. It appears to be because of the use of `NOFOLLOW_LINKS` here https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/java/nio/file/Files.java#L808. To me this appears to be something that either needs to be clarified in the the `Files.createDirectories` API or addressed/fixed there. I have asked for inputs on this from others who have more knowledge of this area.

The specification is that symbolic links are followed by default, with a few exceptions (like delete and move) where it would be wrong to follow links. Files.createDirectories was originally intended to be like mkdir -p. We'd need to check the history but I suspect it is a long standing bug that createAndCheckIsDirectory opts out of following links.

2022-09-21 15:18 UTC, iklam approved these changes
The fix looks reasonable to me.

There's a potential error case, if `parent` is not a directory. However, this should lead to an exception later inside `Files.newOutputStream(jarfile)`, so I think it's OK to not check for this.

2022-09-21 15:34 UTC, iklam requested changes
Withdraw my approval per Alan's comment.

2022-09-21 22:54 UTC, DamonFool commented
> Withdraw my approval per Alan's comment.

Okay.
Thanks @iklam and @AlanBateman .

2022-09-22 06:03 UTC, DamonFool commented
Close this one since it would be fixed by @jaikiran in a separate pr.
Thanks.

2022-09-22 06:03 UTC, closed without merging