8293782: Shenandoah: some tests failed on lock rank check
openjdk/jdk pull request #10264
Opened 2022-09-14 07:01 UTC by tbzhang

After [JDK-8290025](https://bugs.openjdk.org/browse/JDK-8290025), some tests using ShenandoahGC failed on the lock rank check between AdapterHandlerLibrary_lock and ShenandoahRequestedGC_lock

2022-10-04 09:34 UTC, TheRealMDoerr approved these changes
We have tested it for a couple of days and there were no new failures. LGTM.

2022-10-04 10:48 UTC, shipilev requested changes
So we can now enter this code when holding `AdapterHandlerLibrary_lock`, which has a rank of `safepoint-1`. These locks should probably match the rank of `Heap_lock`, which is `safepoint-2` now. Please update `_alloc_failure_waiters_lock` rank as well.

2022-10-09 06:40 UTC, tbzhang commented
> 

Thanks for reminding! updated the rank of `_alloc_failure_waiters_lock `

2022-10-10 12:52 UTC, shipilev approved these changes
This looks good, thank you! (I tested `hotspot:tier1` with Shenandoah, and it now passes cleanly)

2022-10-11 09:55 UTC, tbzhang commented
Thanks for reviews! @shipilev @TheRealMDoerr

2022-10-11 09:55 UTC, tbzhang commented
/integrate

2022-10-11 10:02 UTC, shipilev commented
/sponsor

2022-10-11 10:04 UTC, closed without merging