Update BasicToolBarUI.java
openjdk/jdk pull request #10309
Opened 2022-09-16 13:47 UTC by aLiEnHeAd13

Fixed Bug JDK-4305789 to support docking to any instantiated JFrame https://bugs.java.com/bugdatabase/view_bug.do?bug_id=4305789

2022-09-17 21:10 UTC, aLiEnHeAd13 commented
/signed

2022-09-27 16:11 UTC, kevinrushforth commented
This PR is premature, since it adds public API without any discussion on what adding and supporting that public API would entail. At a minimum, it needs to be discussed on the client-libs-dev mailing list, and if the idea is accepted, it will need a CSR.

2022-11-03 22:04 UTC, prrace commented
/csr

2022-11-03 22:05 UTC, prrace requested changes
Not only does this require an approved CSR but no good case has been made for this,
nor any tests provided. 
And I am sure we'd want to take a detailed look at whether we want to support this also sure this isn't how we would do it.
My take is to close the bug as "will not fix".

2022-12-30 08:37 UTC, closed without merging