8293781: RISC-V: Clarify types of calls
openjdk/jdk pull request #10311
Opened 2022-09-16 13:52 UTC by yhzhu20

RISCV64 OpenJDK uses different types of calls in generated calls. It should be clarified what they are. And the PR also cleans up some out-of-date comments.

2022-09-16 14:30 UTC, feilongjiang requested changes
Looks good, with one comment:

2022-09-16 14:30 UTC, feilongjiang commented on src/hotspot/cpu/riscv/macroAssembler_riscv.hpp
> +  //     the AArch64 address space and being patchable at runtime when the generated
s/AArch64/RISC-V

2022-09-17 02:31 UTC, yhzhu20 commented on src/hotspot/cpu/riscv/macroAssembler_riscv.hpp
> +  //     the AArch64 address space and being patchable at runtime when the generated
Done.

2022-09-20 02:59 UTC, RealFYang approved these changes
Looks good. Thanks.

2022-09-20 03:01 UTC, feilongjiang approved these changes
Change looks good.

2022-09-20 11:11 UTC, yhzhu20 commented
/integrate

2022-09-20 12:03 UTC, yadongw approved these changes
lgtm(not a reviewer)

2022-09-20 12:10 UTC, RealFYang commented
/sponsor

2022-09-20 12:12 UTC, closed without merging