8294003: Don't handle si_addr == 0 && si_code == SI_KERNEL SIGSEGVs
openjdk/jdk pull request #10340
Opened 2022-09-19 12:33 UTC by stefank

We have this code code in our signal handler:

```
#ifndef AMD64
    // Halt if SI_KERNEL before more crashes get misdiagnosed as Java bugs
    // This can happen in any running code (currently more frequently in
    // interpreter code but has been seen in compiled code)
    if (sig == SIGSEGV && info->si_addr == 0 && info->si_code == SI_KERNEL) {
      fatal("An irrecoverable SI_KERNEL SIGSEGV has occurred due "
            "to unstable signal handling in this distribution.");
    }
#endif // AMD64
```

This bug added that change:
https://bugs.openjdk.java.net/browse/JDK-8004124

In the Generational ZGC we hit the exact same condition whenever we try to (incorrectly) dereference one of our colored pointers. From the bug above:

"A segmentation violation that occurs as a result of userspace process accessing virtual memory above the TASK_SIZE limit will cause a segmentation violation with an si_code of SI_KERNEL"

That is, if we have set high-order bits (past the TASK_SIZE limit), we get these kind of SIGSEGVs.

As the signal handle code is written today, we don't "stop" this signal, and instead try to handle it as an implicit null check. This causes hard-to-debug error messages and crashes in code that incorrectly try to deoptimize the faulty code.

I propose that we short-cut the signal handling code, and let this problematic SIGSEGV get passed to VMError::report_and_die.

We've been running with this patch in the Generational ZGC repository for over a year, without any problems.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8294003](https://bugs.openjdk.org/browse/JDK-8294003): Don't handle si_addr == 0 && si_code == SI_KERNEL SIGSEGVs

### Reviewers
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**)
 * [Dean Long](https://openjdk.org/census#dlong) (@dean-long - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/10340/head:pull/10340` \
`$ git checkout pull/10340`

Update a local copy of the PR: \
`$ git checkout pull/10340` \
`$ git pull https://git.openjdk.org/jdk pull/10340/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 10340`

View PR using the GUI difftool: \
`$ git pr show -t 10340`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/10340.diff">https://git.openjdk.org/jdk/pull/10340.diff</a>

</details>

2022-09-19 12:33 UTC, stefank commented
/label add hotspot

2022-09-19 22:07 UTC, dholmes-ora approved these changes
This seems quite reasonable. We've had a few SI_KERNEL crash reports since the original 32-bit Linux issue was reported. Short-circuiting the processing makes complete sense.

Thanks.

2022-09-19 22:27 UTC, dean-long commented
Is there a way to detect this on Windows too?  https://bugs.openjdk.org/browse/JDK-8293832 looks like it could be because of high bits with ZGC.

2022-09-20 07:06 UTC, stefank commented
> Is there a way to detect this on Windows too? https://bugs.openjdk.org/browse/JDK-8293832 looks like it could be because of high bits with ZGC.

I don't know.

Single-generational ZGC places most bits in "dereferenceable" memory. We only use one bit outside of that, and that bit is specifically for dealing with finalizers.

I took a look at the linked Bug. So, on Windows we get 0xffffffff reported as the failing address. Note, that even with my patch, we still get the incorrect address reported on Linux. I don't know if that's fixable. My patch only makes sure that we don't try to continue running, and then hit one of those very misleading secondary failures.

2022-09-20 07:09 UTC, tstuefe reviewed
Only question is, does distinguishing between 32-bit and 64-bit still make sense then? Both crash, only with different error texts. In the range of possible explanations (malformed address, XEN bug, ...) there is nothing that would explain a different behavior for 32-bit.

2022-09-20 07:16 UTC, stefank commented
Oracle doesn't build and test 32-bit versions anymore, so I can't effectively try to verify if this is needed or not. I wouldn't mind if someone else takes ownership of investigating if this is still needed for 32-bits.

2022-09-20 10:40 UTC, dholmes-ora commented
The original issue we targeted on 32-bit was a kernel problem. Is it even possible to have an address past TASK_SIZE on 32-bit?

2022-09-21 13:55 UTC, shipilev commented
I think x86_32 can/should do the same, because faulting on bona fide incorrect address currently produces a misleading error, see below. From the reading of JDK-8015837, JDK-8004124 and related issues, it looks like this code was added for x86_32 to better handle a kernel bug with exec-shield emulation on hardware without NX bit. But even then "better handle" seems to be only about crashing with more precise message.

I think only the ancient hardware runs without NX, and most kernels where this bug appears otherwise are long dead. So, I think we should favor faulting with proper error instead of telling (potentially misleading) things about "unstable signal handling".

```
$ lscpu
Model name:                      Intel(R) Atom(TM) CPU Z530   @ 1.60GHz

$ cat /etc/debian_version 
11.5

$ cat Crash.java 
import java.lang.reflect.*;
import sun.misc.Unsafe;

public class Crash {
  public static void main(String... args) throws Exception {
    Field f = Unsafe.class.getDeclaredField("theUnsafe");
    f.setAccessible(true);
    Unsafe u = (Unsafe) f.get(null);
    u.getInt(-1L); // 0xF....F
  }
}

$ jdk/bin/java Crash.java
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (os_linux_x86.cpp:227), pid=1033, tid=1034
#  fatal error: An irrecoverable SI_KERNEL SIGSEGV has occurred due to unstable signal handling in this distribution.
#
```

2022-09-21 15:24 UTC, shipilev commented
> I think x86_32 can/should do the same, because faulting on bona fide incorrect address currently produces a misleading error, see below.

So I think we can just drop the entirety of `#ifndef` block:

```
diff --git a/src/hotspot/os_cpu/linux_x86/os_linux_x86.cpp b/src/hotspot/os_cpu/linux_x86/os_linux_x86.cpp
index 31afbe696a2..9cd0b9a8b58 100644
--- a/src/hotspot/os_cpu/linux_x86/os_linux_x86.cpp
+++ b/src/hotspot/os_cpu/linux_x86/os_linux_x86.cpp
@@ -220,17 +220,9 @@ bool PosixSignals::pd_hotspot_signal_handler(int sig, siginfo_t* info,
     pc = (address) os::Posix::ucontext_get_pc(uc);
 
     if (sig == SIGSEGV && info->si_addr == 0 && info->si_code == SI_KERNEL) {
-#ifndef AMD64
-    // Halt if SI_KERNEL before more crashes get misdiagnosed as Java bugs
-    // This can happen in any running code (currently more frequently in
-    // interpreter code but has been seen in compiled code)
-      fatal("An irrecoverable SI_KERNEL SIGSEGV has occurred due "
-            "to unstable signal handling in this distribution.");
-#else
       // An irrecoverable SI_KERNEL SIGSEGV has occurred.
       // It's likely caused by dereferencing an address larger than TASK_SIZE.
       return false;
-#endif
     }
 
     // Handle ALL stack overflow variations here
```

On the test above, x86_32 failure before:

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (os_linux_x86.cpp:227), pid=1007, tid=1008
#  fatal error: An irrecoverable SI_KERNEL SIGSEGV has occurred due to unstable signal handling in this distribution.
#
# JRE version: OpenJDK Runtime Environment (20.0) (build 20-testing-builds.shipilev.net-openjdk-jdk-b210-20220919)
# Java VM: OpenJDK Server VM (20-testing-builds.shipilev.net-openjdk-jdk-b210-20220919, mixed mode, sharing, tiered, serial gc, linux-x86)
# Problematic frame:
# V  [libjvm.so+0xa095be]  PosixSignals::pd_hotspot_signal_handler(int, siginfo_t*, ucontext_t*, JavaThread*)+0x40e
...
---------------  T H R E A D  ---------------

Current thread (0xb6a162d0):  JavaThread "main" [_thread_in_vm, id=1008, stack(0xb6bda000,0xb6c2b000)]

Stack: [0xb6bda000,0xb6c2b000],  sp=0xb6c29810,  free space=318k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [libjvm.so+0xa095be]  PosixSignals::pd_hotspot_signal_handler(int, siginfo_t*, ucontext_t*, JavaThread*)+0x40e  (os_linux_x86.cpp:227)
V  [libjvm.so+0xb477fa]  JVM_handle_linux_signal+0x15a  (signals_posix.cpp:655)
V  [libjvm.so+0xb47a23]  javaSignalHandler(int, siginfo_t*, void*)+0x23  (signals_posix.cpp:683)
C  [linux-gate.so.1+0x570]  __kernel_rt_sigreturn+0x0
J 860  jdk.internal.misc.Unsafe.getInt(Ljava/lang/Object;J)I java.base@20-testing (0 bytes) @ 0xaf3706e3 [0xaf370620+0x000000c3]
j  jdk.internal.misc.Unsafe.getInt(J)I+3 java.base@20-testing
j  sun.misc.Unsafe.getInt(J)I+4 jdk.unsupported@20-testing
j  Crash.main([Ljava/lang/String;)V+26
```

x86_32 failure after:

```
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0xb78f5f53, pid=710, tid=711
#
# JRE version: OpenJDK Runtime Environment (20.0) (build 20-internal-adhoc.buildbot.openjdk-jdk)
# Java VM: OpenJDK Server VM (20-internal-adhoc.buildbot.openjdk-jdk, mixed mode, sharing, tiered, serial gc, linux-x86)
# Problematic frame:
# V  [libjvm.so+0xc35f53]  Unsafe_GetInt+0xa3

Current thread (0xb6a162c0):  JavaThread "main" [_thread_in_vm, id=711, stack(0xb6b6b000,0xb6bbc000)]

Stack: [0xb6b6b000,0xb6bbc000],  sp=0xb6bbacf0,  free space=319k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [libjvm.so+0xc35f53]  Unsafe_GetInt+0xa3  (unsafe.cpp:223)
J 884  jdk.internal.misc.Unsafe.getInt(Ljava/lang/Object;J)I java.base@20-internal (0 bytes) @ 0xaf372063 [0xaf371fa0+0x000000c3]
j  jdk.internal.misc.Unsafe.getInt(J)I+3 java.base@20-internal
j  sun.misc.Unsafe.getInt(J)I+4 jdk.unsupported@20-internal
j  Crash.main([Ljava/lang/String;)V+26
```

2022-09-21 16:44 UTC, coleenp commented
Thanks @shipilev for the comment about the origin of this change.  We used to see this error a LOT randomly and it was always painful to diagnose, but I agree that this hardware/config is likely long gone and we can remove this special message.

2022-09-22 06:37 UTC, shipilev requested changes
(Putting a formal review comment)
We would be better off doing the same for x86_32, as per https://github.com/openjdk/jdk/pull/10340#issuecomment-1253868230

2022-09-22 06:39 UTC, stefank commented
Thanks for the investigations, comments, and reviews! I'll remove the 32-bit ifdefs.

2022-09-22 06:43 UTC, shipilev approved these changes
Looks fine to me!

2022-09-22 06:47 UTC, dean-long approved these changes

2022-09-22 07:51 UTC, dholmes-ora approved these changes
Ok

2022-09-22 12:32 UTC, stefank commented
/integrate

2022-09-22 12:35 UTC, closed without merging

2022-09-22 13:01 UTC, tstuefe commented
A small nit remains: why do we even need this section at all?

We get a SIGSEGV with si_addr=0. VM assumes this to be an implicit null check if signal==SIGSEGV and the PC makes sense (interpreter or code blob or vtable stub).

Would it not be cleaner to add a check at that point for info->si_code != SI_KERNEL? E.g. before calling SharedRuntime::continuation_for_implicit_exception?