8293064: Remove unused NET_xxx functions
openjdk/jdk pull request #10343
Opened 2022-09-19 14:32 UTC by DarraghClarke

No tests were affected so this is purely a removal PR apart from updating copyright headers.
I ran tests for Tier 1,2&3 and everything seems to be passing

2022-09-19 16:37 UTC, ChrisHegarty approved these changes
LGTM. Great to see that we're at a point where this kinda cleanup can now happen.

2022-09-19 17:15 UTC, djelinski requested changes

2022-09-19 17:15 UTC, djelinski commented on src/java.base/windows/native/libnet/net_util_md.h
> -JNIEXPORT int JNICALL NET_Timeout(int fd, long timeout);
also remove NET_Timeout2 and NET_BindV6

2022-09-19 18:34 UTC, AlekseiEfimov requested changes
The changes looks good to me with few additional changes needed on Linux platform: 
- `NET_SetTrafficClass`: It was discovered by invoking linker with `--print-gc-sections` option on a Linux-x64 platform. Header file: `net_util_md.h` Source file: `net_util_md.c`, both located in `src/java.base/unix/native/libnet`.
- `NET_ThrowCurrent` on Linux (as already spotted by Daniel). It needs to be removed from `src/java.base/[unix|windows]/native/libnet/net_util_md.c`

2022-09-20 07:29 UTC, AlanBateman commented
@AlekseiEfimov InetAddress.ping is not asynchronously closable so I assume there is no need for the remaining NET_* functions to do sys calls that are wrapped with startOp/endOp. Just mentioning it because a future PR could remove a lot more, including the *_close.c files.

2022-09-20 12:09 UTC, vyommani approved these changes
Looks OK to me, i build/run this patch  at my Linux env and worked as expected.

2022-09-20 14:16 UTC, Michael-Mc-Mahon commented
Have the AIX changes been verified with an AIX build?

2022-09-21 15:48 UTC, DarraghClarke commented
Thanks for the feedback everyone, I made a new commit addressing the comments, let me know if there is anything else

2022-09-21 15:49 UTC, DarraghClarke commented
> Have the AIX changes been verified with an AIX build?
Good question, I wasn't able to test those though I tested Mac/Linux/Windows,
@backwaterred Would you be able to test the AIX changes please?

2022-09-21 16:22 UTC, AlekseiEfimov approved these changes
Thanks for cleaning up additional methods, Darragh. 

The following `NET_` methods were removed and no longer referenced from the native code:
`NET_BindV6` `NET_Dup2` `NET_GetFileDescriptorID` `NET_NonBlockingRead` `NET_Read` `NET_RecvFrom` `NET_Send` `NET_SendTo` `NET_SetTrafficClass` `NET_SocketClose` `NET_ThrowCurrent` `NET_ThrowNew` `NET_Timeout` `NET_Timeout2`.

That is a great cleanup :+1:

2022-09-21 16:41 UTC, backwaterred commented
I see you ran tests in T1, T2, & T3. I can do the same on AIX. It will take some time to complete, and I'll update when the results are in.

2022-09-21 18:10 UTC, djelinski approved these changes

2022-09-27 14:56 UTC, DarraghClarke commented
> I see you ran tests in T1, T2, & T3. I can do the same on AIX. It will take some time to complete, and I'll update when the results are in.
> 
> I found some failures in T2 & T3. This is to be expected as we are less active in adding known failures to the problem lists on AIX. Running again with the master branch to compare, and will update again to let you know the result.
> 
> @DarraghClarke the test results on AIX are looking good. All failures that exist on this branch are present in master as well.

Thanks for testing that!

2022-09-27 14:57 UTC, DarraghClarke commented
/integrate

2022-09-27 15:01 UTC, closed without merging