8294752
openjdk/jdk pull request #10551
Opened 2022-10-04 09:30 UTC by albertnetymk

Simple change of removing redundant assertions.

Test: hotspot_gc

2022-10-04 18:39 UTC, tschatzl requested changes

2022-10-05 09:10 UTC, albertnetymk commented on src/hotspot/share/gc/g1/g1OopClosures.inline.hpp
> +  assert(from->is_in_reserved(p) || from->is_humongous(),
Yes, you are right. Additionally, I believe the same is true for `obj` as well, i.e. `assert(g1h->is_in(obj))`, instead of `is_in_reserved(obj)`.

2022-10-05 09:34 UTC, tschatzl approved these changes

2022-10-25 12:45 UTC, walulyai approved these changes

2022-10-26 09:14 UTC, albertnetymk commented
Thanks for the review.

/integrate

2022-10-26 09:16 UTC, closed without merging