8291443: Remove the PrintSharedDictionary flag
openjdk/jdk pull request #10596
Opened 2022-10-06 14:46 UTC by matias9927

Obsoleted the unused PrintSharedDictionary flag and removed the flag from all tests. Verified with tier1-4 tests.

2022-10-20 19:02 UTC, iklam commented
Should the issue title be "Obsolete the PrintSharedDictionary flag" instead, since we are not doing a complete removal yet?

2022-10-21 01:47 UTC, dholmes-ora requested changes
What you have looks good but the flag should also be deleted from:

./src/hotspot/share/cds/cds_globals.hpp

Thanks.

2022-10-24 04:48 UTC, dholmes-ora approved these changes
Looks good. Thanks.

2022-10-24 06:56 UTC, dholmes-ora commented
As @iklam suggested it would be more precise to change the bug title to say "Obsolete" rather than "Remove". Thanks.

2022-10-24 15:04 UTC, matias9927 commented
/integrate

2022-10-24 16:00 UTC, iklam approved these changes

2022-10-24 16:09 UTC, closed without merging