8295033: hsdis configure error when cross-compiling with --with-binutils-src
openjdk/jdk pull request #10628
Opened 2022-10-10 06:32 UTC by DingliZhang

I built hsdis with the following parameters from source code of binutils while cross-compiling:
```
--with-hsdis=binutils \
--with-binutils-src=/home/dingli/jdk-tools/binutils-2.38
```

But configure will exit with the following error:
```
checking whether we are cross compiling... configure: error: in `/home/dingli/jdk-tools/binutils-2.38-src':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
configure: Automatic building of binutils failed on configure. Try building it manually
configure: error: Cannot continue
configure exiting with result code 1
```

The reason for the error is that binutils wants to be configured with --host during cross-compilation. So we can determine if we are currently cross-compiling and add the --host parameter to binutils_target:
```diff
diff --git a/make/autoconf/lib-hsdis.m4 b/make/autoconf/lib-hsdis.m4
index d72bbf6df32..dddc1cf6a4d 100644
--- a/make/autoconf/lib-hsdis.m4
+++ b/make/autoconf/lib-hsdis.m4
@@ -175,7 +175,11 @@ AC_DEFUN([LIB_BUILD_BINUTILS],
       fi
     else
       binutils_cc="$CC $SYSROOT_CFLAGS"
- binutils_target=""
+ if test "x$host" = "x$build"; then
+ binutils_target=""
+ else
+ binutils_target="--host=$host"
+ fi
     fi
     binutils_cflags="$binutils_cflags $MACHINE_FLAG $JVM_PICFLAG $C_O_FLAG_NORM"
```

In the meantime, I removed some useless code about hsdis-demo because hsdis-demo.c was removed in [JDK-8275128](https://bugs.openjdk.org/browse/JDK-8275128) .

## Testing:

- cross compile for RISC-V on x86_64

2022-10-10 12:50 UTC, erikj79 approved these changes
Build changes look ok to me.

2022-10-10 13:34 UTC, DingliZhang commented
@erikj79 Thanks for the review!
/integrate

2022-10-11 09:53 UTC, shipilev commented
I think it requires a bit more fiddling for other arches:

```
$ CXX=aarch64-linux-gnu-g++ CC=aarch64-linux-gnu-gcc sh ./configure --with-debug-level=fastdebug --openjdk-target=aarch64-linux-gnu --with-sysroot=/chroots/arm64 --with-boot-jdk=/home/shade/Install/jdk19u-ea --with-hsdis=binutils --with-binutils-src=binutils-2.39
...
/usr/bin/bash ./../move-if-change tofiles ofiles
touch stamp-ofiles
  CCLD     libbfd.la
./libtool: line 1118: aarch64-unknown-linux-gnu-ar: command not found
gmake[3]: *** [Makefile:1429: libbfd.la] Error 127
gmake[3]: Leaving directory '/home/shade/trunks/jdk/binutils-2.39/bfd'
gmake[2]: *** [Makefile:1932: all-recursive] Error 1
gmake[2]: Leaving directory '/home/shade/trunks/jdk/binutils-2.39/bfd'
gmake[1]: *** [Makefile:1321: all] Error 2
gmake[1]: Leaving directory '/home/shade/trunks/jdk/binutils-2.39/bfd'
gmake: *** [Makefile:3057: all-bfd] Error 2
configure: Automatic building of binutils failed on make. Try building it manually
configure: error: Cannot continue
configure exiting with result code 1
```

2022-10-11 10:47 UTC, magicus approved these changes
Looks good to me.

2022-10-11 11:13 UTC, shipilev commented
> This allows building hsdis on following arches with server ports:

Also these Zero ports produce `hsdis` binaries as well (they are not as useful there, though, because no JIT compilers are done there):

```
alpha-linux-gnu
arm-linux-gnueabi
m68k-linux-gnu
mips64el-linux-gnuabi64
mipsel-linux-gnu
powerpc-linux-gnu
sh4-linux-gnu
sparc64-linux-gnu
```

2022-10-11 11:33 UTC, magicus commented
> I think checking it like this would be more robust?
> 
> ```
>       if test "x$conf_openjdk_target" != "x"; then
>         binutils_target="--host=$conf_openjdk_target"
>       else
>         binutils_target=""
>       fi
> ```
> 
> This allows me to produce AArch64 hsdis:
> 
> ```
> $ file ./build/linux-aarch64-server-fastdebug/support/hsdis/libhsdis.so
> ./build/linux-aarch64-server-fastdebug/support/hsdis/libhsdis.so: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, BuildID[sha1]=c709135f1f2ef2bee329550044fabea35e33ebb3, not stripped
> ```

Yeah, you're onto something. We should not check the autoconf variables.

I'd even recommend testing for cross compilation like this:
```
    if test "x$COMPILE_TYPE" = xcross; then
      # ...
```

We also have a `CROSS_COMPILE_ARCH` which is set to `$OPENJDK_$1_CPU_LEGACY`, but right now I can't say how it relates to `$conf_openjdk_target`. But I'd rather not use the `$conf_...` variables outside the option testing code. If we do need it, and it is not already available, we should "export" it by giving it a separate, uppercase variable name.

2022-10-11 11:34 UTC, magicus requested changes
Changing my review; we need to take this for another spin.

2022-10-11 11:38 UTC, magicus commented
Ok, we already have an exported value for `$host`, which is `$OPENJDK_TARGET_AUTOCONF_NAME`. Also, `$conf_openjdk_target` is used in the wrapper configure script. It is probably leaking into the main generated autoconf script, but it is definitely not supposed to be used there. Instead, it should only be used to setup the `--host=` option to autoconf. So looking for `$host` is fine I suppose, but we should do it using the OPENJDK_TARGET_AUTOCONF_NAME variable.

2022-10-11 12:57 UTC, shipilev commented
> Ok, we already have an exported value for `$host`, which is `$OPENJDK_TARGET_AUTOCONF_NAME`. Also, `$conf_openjdk_target` is used in the wrapper configure script. It is probably leaking into the main generated autoconf script, but it is definitely not supposed to be used there. Instead, it should only be used to setup the `--host=` option to autoconf. So looking for `$host` is fine I suppose, but we should do it using the OPENJDK_TARGET_AUTOCONF_NAME variable.

Quite!

Applying this patch over the PR:

```
diff --git a/make/autoconf/lib-hsdis.m4 b/make/autoconf/lib-hsdis.m4
index dddc1cf6a4d..72bd08c7108 100644
--- a/make/autoconf/lib-hsdis.m4
+++ b/make/autoconf/lib-hsdis.m4
@@ -175,10 +175,10 @@ AC_DEFUN([LIB_BUILD_BINUTILS],
       fi
     else
       binutils_cc="$CC $SYSROOT_CFLAGS"
-      if test "x$host" = "x$build"; then
-        binutils_target=""
+      if test "x$COMPILE_TYPE" = xcross; then
+        binutils_target="--host=$OPENJDK_TARGET_AUTOCONF_NAME"
       else
-        binutils_target="--host=$host"
+        binutils_target=""
       fi
     fi
     binutils_cflags="$binutils_cflags $MACHINE_FLAG $JVM_PICFLAG $C_O_FLAG_NORM"
```

...successfully produces the hsdis binaries on all these platforms:

```
server-release-aarch64-linux-gnu-10
server-release-arm-linux-gnueabihf-10
server-release-i686-linux-gnu-10
server-release-powerpc64le-linux-gnu-10
server-release-powerpc64-linux-gnu-10
server-release-riscv64-linux-gnu-10
server-release-s390x-linux-gnu-10
server-release-x86_64-linux-gnu-10
zero-release-aarch64-linux-gnu-10
zero-release-alpha-linux-gnu-10
zero-release-arm-linux-gnueabi-10
zero-release-arm-linux-gnueabihf-10
zero-release-i686-linux-gnu-10
zero-release-m68k-linux-gnu-10
zero-release-mips64el-linux-gnuabi64-10
zero-release-mipsel-linux-gnu-10
zero-release-powerpc64le-linux-gnu-10
zero-release-powerpc64-linux-gnu-10
zero-release-powerpc-linux-gnu-10
zero-release-riscv64-linux-gnu-10
zero-release-s390x-linux-gnu-10
zero-release-sh4-linux-gnu-10
zero-release-sparc64-linux-gnu-10
zero-release-x86_64-linux-gnu-10
```

Therefore, I believe this is what we should do and then call it a day. (Then I also need to start building all these hsdis-es at [https://builds.shipilev.net/hsdis/](https://builds.shipilev.net/hsdis/))

2022-10-11 15:56 UTC, magicus commented
Also, I think we can skip the demo Makefile changes from this PR.

In fact, I'm surprised `src/utils/hsdis/Makefile` is still there. I was sure I removed it when  I rewrote the build of hsdis to utilize the normal build system with JDK-8188073. I'd rather open a separate issue and just remove the file.

2022-10-11 16:01 UTC, magicus commented
See https://github.com/openjdk/jdk/pull/10660 ([JDK-8295163](https://bugs.openjdk.org/browse/JDK-8295163)) for the removal of the Makefile.

2022-10-12 01:26 UTC, DingliZhang commented
@shipilev @magicus Thanks for the review!
I have skipped the demo Makefile changes from this PR and applied the patch from @shipilev.

2022-10-12 06:20 UTC, magicus approved these changes
Thank you. This looks good now.

2022-10-12 06:21 UTC, DingliZhang commented
/integrate

2022-10-12 06:24 UTC, shipilev commented
Testing...

2022-10-12 07:22 UTC, shipilev approved these changes

2022-10-12 07:22 UTC, shipilev commented
/sponsor

2022-10-12 07:24 UTC, closed without merging