8282958: Rendering issues of borders, TextFields on Windows High-DPI systems
openjdk/jdk pull request #10681
Opened 2022-10-12 16:41 UTC by rajamah

This fix is based on a similar approach as described here  https://github.com/openjdk/jdk/pull/7449#issuecomment-1068218648.
We rescale the line border to render the Textfield border correctly, so that all sides of the Textfield border are of same thickness.

2022-10-12 16:42 UTC, rajamah commented
/contributor add aivanov

2022-10-27 19:45 UTC, aivanov-jdk approved these changes
Looks good to me.

2022-10-27 19:45 UTC, aivanov-jdk commented on test/jdk/javax/swing/border/LineBorder/ScaledLineBorderTest.java
> +        JFrame frame = new JFrame("Scaled Etched Border Test");
```suggestion
        JFrame frame = new JFrame("Scaled Line Border Test");
```

2022-10-28 16:37 UTC, aivanov-jdk approved these changes

2022-11-01 17:17 UTC, honkar-jdk requested changes
Checked the saved images on paint.net, the border thickness is equal and uniform on 4 sides (no. of pixels painted) for different scales.

Copyright year needs to be updated for LineBorder.

2022-11-01 17:21 UTC, honkar-jdk approved these changes

2022-11-01 17:37 UTC, azuev-java approved these changes
Looks good to me.

2022-11-01 17:38 UTC, aivanov-jdk approved these changes

2022-11-01 18:36 UTC, aivanov-jdk commented
/sponsor

2022-11-01 18:38 UTC, closed without merging