Fix build failure on MacOS 12.6 M1 with Xcode 14.0.
openjdk/jdk pull request #10768
Opened 2022-10-19 15:33 UTC by archiecobbs

Building on MacOS 12.6 M1 with Xcode 14.0 fails due to C compiler unused parameter warnings:
```
Creating support/modules_libs/java.desktop/libosx.dylib from 1 file(s)
/Users/archie/proj/jdk/src/java.desktop/share/native/liblcms/cmstypes.c:3441:132: error: parameter 'SizeOfTag' set but not used [-Werror,-Wunused-but-set-parameter]
void *Type_ProfileSequenceId_Read(struct _cms_typehandler_struct* self, cmsIOHANDLER* io, cmsUInt32Number* nItems, cmsUInt32Number SizeOfTag)
                                                                                                                                   ^
/Users/archie/proj/jdk/src/java.desktop/share/native/liblcms/cmstypes.c:5137:125: error: parameter 'SizeOfTag' set but not used [-Werror,-Wunused-but-set-parameter]
void *Type_Dictionary_Read(struct _cms_typehandler_struct* self, cmsIOHANDLER* io, cmsUInt32Number* nItems, cmsUInt32Number SizeOfTag)
                                                                                                                            ^
2 errors generated.
make[3]: *** [/Users/archie/proj/jdk/build/macosx-aarch64-server-release/support/native/java.desktop/liblcms/cmstypes.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [java.desktop-libs] Error 2
```

This patch adds `cmsUNUSED_PARAMETER()` macros to suppress the warnings and fix the build.

2022-10-21 10:08 UTC, VladimirKempik commented
Hello, a jbs bug needs to be created first, let me create one for this issue

2022-10-21 10:14 UTC, VladimirKempik commented
Here it is - https://bugs.openjdk.org/browse/JDK-8295779
So please rename this PR to  "8295779: Xcode 14.0 fails to build jdk on m1 macos"

2022-10-24 04:09 UTC, prrace requested changes
Nope. This isn't the right thing to do. This is a 3rd party library.
Go to upstream and request source code changes.
But you are too late. I submitted an upstream PR for this months ago 
https://github.com/mm2/Little-CMS/commit/9575107f11fa0f8f326c88c8f730649be728d997
The 2nd case you cite is no longer in upstream as far as I can tel.
And we will be pulling in LCMS 2.14 in a couple of weeks.
If there's any outstanding issues it will be handled in that PR anyway.
So this PR should be withdrawn.

2022-10-24 13:18 UTC, archiecobbs commented
OK thanks.

2022-10-24 13:18 UTC, closed without merging

2022-11-09 11:57 UTC, yososs commented
It is marked as a duplicate of the issue I reported and this issue.but it is a different issue. but I am very doubtful as to why such a decision was made.

https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8296654

2022-11-09 13:52 UTC, kevinrushforth commented
> It is marked as a duplicate of the issue I reported and this issue.but it is a different issue. but I am very doubtful as to why such a decision was made.
> 
> https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8296654

Yes, [JDK-8296654](https://bugs.openjdk.org/browse/JDK-8296654) is a different issue. I reopened it with a comment to that effect.

2022-11-10 16:48 UTC, RealLucy commented
As an intermediate solution until LCMS 2.14 has been pulled in, you could suppress the warning like that:
```
diff --git a/make/modules/java.desktop/lib/Awt2dLibraries.gmk b/make/modules/java.desktop/lib/Awt2dLibraries.gmk
index ce14776503f..55070197ebb 100644
--- a/make/modules/java.desktop/lib/Awt2dLibraries.gmk
+++ b/make/modules/java.desktop/lib/Awt2dLibraries.gmk
@@ -306,7 +306,7 @@ $(eval $(call SetupJdkLibrary, BUILD_LIBLCMS, \
         libawt/java2d, \
     HEADERS_FROM_SRC := $(LIBLCMS_HEADERS_FROM_SRC), \
     DISABLED_WARNINGS_gcc := format-nonliteral stringop-truncation, \
-    DISABLED_WARNINGS_clang := format-nonliteral, \
+    DISABLED_WARNINGS_clang := format-nonliteral unused-but-set-parameter, \
     LDFLAGS := $(LDFLAGS_JDKLIB) \
         $(call SET_SHARED_LIBRARY_ORIGIN), \
     LDFLAGS_unix := -L$(INSTALL_LIBRARIES_HERE), \
```
There are a few other places which need a similar fix.

2022-11-10 17:38 UTC, archiecobbs commented
FWIW here are the patches I'm currently dragging along in order to build the `master` branch:
```patch
diff --git a/make/modules/java.desktop/lib/Awt2dLibraries.gmk b/make/modules/java.desktop/lib/Awt2dLibraries.gmk
index b02c0fa6c82..b279178834e 100644
--- a/make/modules/java.desktop/lib/Awt2dLibraries.gmk
+++ b/make/modules/java.desktop/lib/Awt2dLibraries.gmk
@@ -764,6 +764,7 @@ ifeq ($(ENABLE_HEADLESS_ONLY), false)
       DISABLED_WARNINGS_gcc_splashscreen_sys.c := type-limits unused-result, \
       DISABLED_WARNINGS_clang_dgif_lib.c := sign-compare, \
       DISABLED_WARNINGS_clang_gzwrite.c := format-nonliteral, \
+      DISABLED_WARNINGS_clang_pngrutil.c := null-pointer-subtraction, \
       DISABLED_WARNINGS_clang_splashscreen_impl.c := sign-compare, \
       DISABLED_WARNINGS_clang_splashscreen_png.c := incompatible-pointer-types, \
       DISABLED_WARNINGS_clang_splashscreen_sys.m := deprecated-declarations, \
diff --git a/src/java.desktop/share/native/liblcms/cmstypes.c b/src/java.desktop/share/native/liblcms/cmstypes.c
index 006f98b084d..9a793f3efb5 100644
--- a/src/java.desktop/share/native/liblcms/cmstypes.c
+++ b/src/java.desktop/share/native/liblcms/cmstypes.c
@@ -3444,6 +3444,8 @@ void *Type_ProfileSequenceId_Read(struct _cms_typehandler_struct* self, cmsIOHAN
     cmsUInt32Number Count;
     cmsUInt32Number BaseOffset;
 
+    cmsUNUSED_PARAMETER(SizeOfTag);
+
     *nItems = 0;
 
     // Get actual position as a basis for element offsets
@@ -5144,6 +5146,8 @@ void *Type_Dictionary_Read(struct _cms_typehandler_struct* self, cmsIOHANDLER* i
    cmsMLU *DisplayNameMLU = NULL, *DisplayValueMLU=NULL;
    cmsBool rc;
 
+    cmsUNUSED_PARAMETER(SizeOfTag);
+
     *nItems = 0;
 
     // Get actual position as a basis for element offsets
```

2022-11-10 18:09 UTC, VladimirKempik commented
Well, you can just use --disable-warnings-as-errors configure argument until this fixed

2022-11-10 19:08 UTC, archiecobbs commented
> Well, you can just use `--disable-warnings-as-errors` configure argument until this fixed

Sure, but that's too blunt an instrument. It defeats the whole purpose of having warnings in the first place.

If you're hacking on the code with intent to submit it back via PR, you _want_ the warnings, at least, the valid ones.

2022-11-11 08:20 UTC, RealLucy commented
This is a moving target, and the changes depend on the build mode as well as on the Xcode version + subversion. My company forced me on Xcode 14.1 lately. That triggered "deprecated-declarations" warnings in adlc (1x), hotspot (20x), and java.desktop (1x). These are all caused by the use of sprint(). The next Xcode subversion will for sure find other code snippets to complain about. 

I'm not sure which policy to follow here. Adapt the make file (will hide the warning "forever")? Change the source code (and potentially introduce new issues)? Any advice from the build gurus?