8295711: Rename ZBarrierSetAssembler::load_at parameter name from "tmp_thread" to "tmp2"
openjdk/jdk pull request #10783
Opened 2022-10-20 08:28 UTC by RealFYang

On AArch64 and RISC-V, the last formal parameter for ZBarrierSetAssembler::load_at
is named "tmp_thread". But the callers will pass an ordinary temporary register for
this parameter which has no relation with the thread register. We should rename this
formal parameter from "tmp_thread" to "tmp2".

Testing: Fastdebug builds on linux-aarch64 & linux-riscv64.

2022-10-20 08:44 UTC, feilongjiang approved these changes

2022-10-21 01:38 UTC, shqking approved these changes
LGTM (I'm not a Reviewer).

2022-10-21 06:48 UTC, tschatzl requested changes
Please also fix the `tmp_thread` parameter for x86 while you are at it ;)

2022-10-21 07:06 UTC, RealFYang commented
> Please also fix the `tmp_thread` parameter for x86 while you are at it ;)

It looks to me that the case for x86 is different here.
For x86, this formal parameter will be used later for calling 'get_thread()' [1][2].
So I think we should keep its original name.

[1] https://github.com/openjdk/jdk/blob/master/src/hotspot/cpu/x86/gc/shenandoah/shenandoahBarrierSetAssembler_x86.cpp#L573

[2] https://github.com/openjdk/jdk/blob/master/src/hotspot/cpu/x86/gc/shenandoah/shenandoahBarrierSetAssembler_x86.cpp#L573

2022-10-26 08:15 UTC, RealFYang commented
> > Please also fix the `tmp_thread` parameter for x86 while you are at it ;)
> 
> It looks to me that the case for x86 is different here. For x86_32, this formal parameter will be used later for calling 'get_thread()' [1][2]. So I think we should keep its original name.
> 
> [1] https://github.com/openjdk/jdk/blob/master/src/hotspot/cpu/x86/gc/shenandoah/shenandoahBarrierSetAssembler_x86.cpp#L573
> 
> [2] https://github.com/openjdk/jdk/blob/master/src/hotspot/cpu/x86/gc/shenandoah/shenandoahBarrierSetAssembler_x86.cpp#L573

@tschatzl : Are you OK with this? And any further comments? Thanks.

2022-11-14 10:00 UTC, tschatzl commented
I would have changed it only for the use in x86_32 files, in the actual parameters, but others are okay as is, so go ahead pushing it.
Sorry for holding up this review for so long.

2022-11-14 10:00 UTC, tschatzl approved these changes

2022-11-14 10:19 UTC, fisk approved these changes
The tmp_thread name came from the x86 port where there are places where the tmp_thread register can't be used arbitrarily, but rather is limited to contain the thread pointer, as there is no dedicated thread register on 32 bit x86. The name was copied to the other platforms and it never made sense. I'm happy with this cleanup. Looks good.

2022-11-15 00:58 UTC, RealFYang commented
Thank you!
/integrate

2022-11-15 00:59 UTC, closed without merging