8255598: [PPC64] assert(Universe::heap()->is_in(result)) failed: object not in heap
openjdk/jdk pull request #1078
Opened 2020-11-05 16:46 UTC by TheRealMDoerr

JDK-8237363 introduced "assert(Universe::heap()->is_in..." check in CompressedOops::decode functions.
This assertion restricts the usability of the decode functions. There are periods of time (during GC) at which we can't use " Universe::heap()->is_in" because the pointer gets switched between old and new location, but "Universe::heap()->is_in" is not yet accurate.
PPC64 code has a usage of CompressedOops::decode which is affected by this problem. (It was observed with SerialGC, see JBS.)
We could also use a weaker assertion, but seems like other people value the stronger assertion more. So I suggest to use decode_raw as workaround for PPC64.

2020-11-05 17:02 UTC, TheRealMDoerr commented
/label hotspot-gc hotspot-runtime

2020-11-05 18:36 UTC, albertnetymk requested changes
Given the following naming pair, I would have guess that `decode_raw` can handle null properly, so the explicit check of null in this PR struck me as a surprise. Why so?

```
  static inline oop decode_raw_not_null(narrowOop v);
  static inline oop decode_raw(narrowOop v);
```

I think having some concise inline comments to explain why `decode_raw` is used over `decode` could improve readability.

2020-11-05 22:31 UTC, TheRealMDoerr commented
@albertnetymk: Thanks for looking at this. I've added a comment.
I was also surprised about that decode_raw doesn't handle null properly. I'd have expected decode_raw to call decode_raw_not_null, but it's implemented vice-versa. Therefore the null check before the call. Note that there's another usage with preceding null check in oopDesc::load_oop_raw.

2020-11-06 09:11 UTC, albertnetymk commented
> I've added a comment.

Thank you for that.

I believe `decode_raw` handles null well; `decode_raw_not_null` is there just to have an extra assertion when the caller *knows* that the oop is not null.

> Note that there's another usage with preceding null check in oopDesc::load_oop_raw.

Indeed, but I think that one is unnecessary as well, which could (or should) be addressed in this PR or another.

2020-11-06 09:36 UTC, TheRealMDoerr commented
Unfortunately, no.
Assume we're using "HeapBasedNarrowOop". decode_raw adds the base, so decode_raw(0) returns base which is wrong.

Also see Stefan's comment in the bug:
"I see that decode and decode_raw has different semantics w.r.t. 0, so be careful if you change this code to use decode_raw"

2020-11-06 11:10 UTC, albertnetymk commented
> Assume we're using "HeapBasedNarrowOop". decode_raw adds the base, so decode_raw(0) returns base which is wrong.

Yes, you are right. Thank you for pointing this out.

2020-11-06 11:10 UTC, albertnetymk approved these changes

2020-11-09 10:14 UTC, tschatzl approved these changes
An alternative change could be investigating whether setting `top()` earlier in the serial gc full gc. It seems to only be a problem with that collector, as the others are seemingly not affected.

I'm okay with this change too though.

2020-11-09 20:39 UTC, TheRealMDoerr commented
Thanks for the reviews!
@tschatzl: Calling `set_top` during phase 2 sounds like a nice idea, but it's currently done in `reset_after_compaction` and it may possibly break other things if I move it to an earlier phase.
So I should probably better go ahead with the current version.

2020-11-10 11:47 UTC, TheRealMDoerr commented
/integrate

2020-11-10 11:48 UTC, closed without merging