Add Thread.sleep to PollingWatchService's register method
openjdk/jdk pull request #10824
Opened 2022-10-21 21:43 UTC by backwaterred

This minor change may fix a test issue observed in internal testing. For now this PR is just a placeholder. I will close, or modify the description shortly.

2022-11-18 18:54 UTC, backwaterred commented
The Windows pre-test failure is related to `runtime/ParallelLoad/SuperWait/SuperWaitTest.java` and should not be related to this change. Windows as a native library based implementation and does not use the one provided by PollingWatchService.

2022-11-19 08:04 UTC, AlanBateman requested changes
This seems to adds a 1s sleep to Path.register. I don't think we want that. Would it be possible to start with a summary of the test failure that you are running into.

2022-11-21 18:10 UTC, backwaterred commented
Hi @AlanBateman, thanks for your interest in the PR :slightly_smiling_face: 

> Would it be possible to start with a summary of the test failure that you are running into

The WatchService test I am debugging, creates a WatchKey and expects it to notice changes that the test makes to the file system. On AIX, this test is timing out after 10s without seeing the changes. My first PR to address this issue [1] changed the delay between when the polling thread is created, and when it begins polling for changes. That fix addressed the changes on IBM's internal servers. However, the issue still occurs on Adoptium servers.

The delay proposed by this PR, ensures that the WatchKey polling thread is active before returning the WatchKey via the register method. I agree that it's not really ideal to add a delay to the registration process, so other suggestions are welcome.

One alternative idea might be to simply lower the POLLING_INIT_DELAY to 0. 

[1] https://github.com/openjdk/jdk/pull/8479

2022-11-21 19:22 UTC, AlanBateman commented
> The WatchService test I am debugging, creates a WatchKey and expects it to notice changes that the test makes to the file system. On AIX, this test is timing out after 10s without seeing the changes. 

I wonder if this is a test issue. If the test were to use a timeout of say 60s, would it pass?

2022-11-21 22:01 UTC, backwaterred commented
This is another possible solution. I wanted to err on the side of the failure being valid. Once the call to `register()` completes, I think it's fair to expect that the WatchKey is active.

2022-11-22 08:41 UTC, AlanBateman commented
> This is another possible solution. I wanted to err on the side of the failure being valid. Once the call to `register()` completes, I think it's fair to expect that the WatchKey is active.

I think you mean "valid" rather than "active". When you register a directory with a WatchService then it will valid (isValid method) until the key is cancelled or the WatchService is closed.

I think you'll need to paste in a reproducer or at least outline what the test does in other to make progress. Adding a 1s delay to Path.register to make a test pass just doesn't make sense. If the issue is AIX specific then maybe you can say something about the file system and the granularity of the file modification time. The polling WatchService works by polling the file modification time and maybe the issue is that it's not being updated on these systems?

2022-11-22 17:44 UTC, backwaterred commented
The failing test is register_and_poll in JCK17. The JCK is copyrighted, so I'm not able to post about it publicly, but I believe you should have access to it.

Currently, PollingWatchService is used only on BSD/Macos and AIX. I don't believe the issue is platform specific. I think the issue that I describe below is extant on all platforms that use PollingWatchService, but some amount of platform specificity may make it more prominent on AIX.

> I think you mean "valid" rather than "active".

I meant active, but it's probably not clear what I meant by that. What I meant to say is that there is an 'activation window' in the code without this change. The window starts when [the call](https://github.com/openjdk/jdk/blob/0ac5b55311222d0531c9cfcec8c74932661b1750/src/java.base/share/classes/sun/nio/fs/PollingWatchService.java#L317) to `scheduleAtFixedRate(POLLING_INIT_DELAY...)`, completes and ends when the first run of the [WatchKey `poll()`](https://github.com/openjdk/jdk/blob/0ac5b55311222d0531c9cfcec8c74932661b1750/src/java.base/share/classes/sun/nio/fs/PollingWatchService.java#L342) method happens.

What the delay in this change is intended to do, is eliminate this 'activation window'. It does this by forcing register to wait for POLLING_INIT_DELAY to ensure the polling thread is running when it returns. My comment was meant to suggest, that a key should be "activ[ly]" polling for changes when it is returned by `register(...)`. POLLING_INIT_DELAY is an upper bound on the length of this 'activation window'.

I agree with your sentiment that adding a delay is not the most elegant solution. If you agree that changing POLLING_INIT_DELAY to 0 and removing the proposed delay is a good option, I am happy to run the test with that change to confirm that is a viable solution, and modify this PR.

2022-11-22 19:28 UTC, AlanBateman commented
> The failing test is register_and_poll in JCK17. The JCK is copyrighted, so I'm not able to post about it publicly, but I believe you should have access to it.
> 
> Currently, PollingWatchService is used only on BSD/Macos and AIX. I don't believe the issue is platform specific. I think the issue that I describe below is extant on all platforms that use PollingWatchService, but some amount of platform specificity may make it more prominent on AIX.

I think the issue is that the test registers a directory and immediately modifies a file in that directory. To an observer using the PollingWatchService, the file last modification time has not changed so the watch key is not queued. What is the precision of the time of last modification on AIX? On macOS there is nano precision timestamps so this might explain why the issue has not been observed there. In this case, this seems like something that the test needs to deal with.

2022-11-23 19:11 UTC, backwaterred commented
> I think the issue is that the test registers a directory and immediately modifies a file in that directory. To an observer using the PollingWatchService, the file last modification time has not changed so the watch key is not queued... What is the precision of the time of last modification on AIX?

A reasonable explanation, but I disagree with the conclusion. The implementation of getLastModifiedTime comes from UnixFileSystem code which is similar between the Unixes [2]. To your question, AIX uses nanosecond information to compute the mtime as well. In addition, PollingWatchService explicitly converts the modification time to milliseconds [1].

> In passing, I would like to see POLLING_INIT_DELAY (added by JDK-8285956) be removed as it's inconsistent to start polling after 1s when the polling rate is 2s. The original code was correct.

Does this mean that you'd prefer the polling rate match always match the initial delay? I can see an argument for this. But in that case, I would advocate for the addition of a delay like the one proposed by this PR. Once the call to register a path returns, I think it's reasonable to assume that any change to the registered Watchable would be noticed by the WatchService. If the activation window that I describe is present, any changes made during that time can not be noticed because the polling thread is not running yet [3].

---

It may be worth clarifying that my changes were not intended just to make the test pass. It's  my belief that there is a real issue with the presence of this activation window, which PollingWatchService would benefit from removing. I am happy to discuss the best method for doing so.

```
Result of changing InitDelay and Interval. Changes are not reported until p_0.
scheduleAtFixedRate(thunk, InitDelay, Interval TimeUnit.SECONDS);

# Current
| InitDelay | Interval | ... | Interval |
           p_0        p_1   p_n       p_n+1
|<--------->| activation window

# Pre-8285956
| Interval | Interval | ... | Interval |
          p_0        p_1   p_n       p_n+1
|<-------->| activation window

# Proposed Change
| InitDelay | ... | Interval |
p_0        p_1   p_n       p_n+1

Legend:
InitDelay: is the POLLING_INIT_DELAY
Interval: is the DEFAULT_POLLING_INTERVAL
p_0: is the first poll run by the polling thread
p_n: is the (n+1)th poll by the polling thread
```

[1] https://github.com/openjdk/jdk/blob/2afb4c3327b6830a009ee1ab8a1eb7803ef53007/src/java.base/share/classes/sun/nio/fs/PollingWatchService.java#L367
[2] https://github.com/openjdk/jdk/blob/2afb4c3327b6830a009ee1ab8a1eb7803ef53007/src/java.base/unix/native/libjava/UnixFileSystem_md.c#L226-L247
[3] https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/concurrent/ScheduledExecutorService.html#scheduleAtFixedRate(java.lang.Runnable,long,long,java.util.concurrent.TimeUnit)

2022-11-24 08:59 UTC, AlanBateman commented
> A reasonable explanation, but I disagree with the conclusion. The implementation of getLastModifiedTime comes from UnixFileSystem code which is similar between the Unixes [2]. To your question, AIX uses nanosecond information to compute the mtime as well. In addition, PollingWatchService explicitly converts the modification time to milliseconds [1].

Would it be possible to run this on the AIX system and paste in the output? The output is just the last modified time, it wouldn't reveal anything about the system.
```
            Path file = Files.createTempFile("foo", "bin");
            try {
                FileTime t0 = Files.getLastModifiedTime(file);
                try (var ch = Files.newByteChannel(file, StandardOpenOption.APPEND)) {
                    ch.write(ByteBuffer.allocate(1000));
                }
                FileTime t1 = Files.getLastModifiedTime(file);
                System.out.format("%s%n%s%n", t0, t1);
            } finally {
                Files.delete(file);
            }
```
I think this is close to the test that is failing for you. The main thing I'd like to see is whether the time of last modification is changed or not.
 
> Does this mean that you'd prefer the polling rate match always match the initial delay? I can see an argument for this. But in that case, I would advocate for the addition of a delay like the one proposed by this PR. Once the call to register a path returns, I think it's reasonable to assume that any change to the registered Watchable would be noticed by the WatchService.

Registering a directory to watch will first scan the directory to get the names and time of last modification for all entries. This is done by the register method before before it adds the directory to the map that is scanned by the poller thread. Hopefully this makes it clearer why POLLING_INIT_DELAY doesn't really make sense. It means first the poller thread will do its first poll of all directories from 1s of first registration, then at 2s interacts thereafter.

2022-11-24 09:15 UTC, AlanBateman commented
> The implementation of getLastModifiedTime comes from UnixFileSystem code which is similar between the Unixes [2]. 

The implementation used is libnio/fs/UnixNativeDispatcher.c and there may be porting work required there to get timestamps with a precision of more than 1s. That is, it looks like AIX may use st_mtime_n rather than st_mtimespec.tv_nsec.

2022-11-28 20:52 UTC, backwaterred commented
> Would it be possible to run this on the AIX system and paste in the output?

On AIX:
```
2022-11-28T16:12:18.277871263Z
2022-11-28T16:12:18.281290513Z
```

On Linux x86_64:
```
2022-11-28T16:17:34.006071133Z
2022-11-28T16:17:34.015071329Z

```

> That is, it looks like AIX may use st_mtime_n rather than st_mtimespec.tv_nsec.

It looks to me like this is just a difference in naming, and that both refer to nanosecond resolution.

2022-11-29 11:19 UTC, AlanBateman commented
> > Would it be possible to run this on the AIX system and paste in the output?
> 
> On AIX:
> 
> ```
> 2022-11-28T16:12:18.277871263Z
> 2022-11-28T16:12:18.281290513Z
> ```

Okay, so this means you've got high precision on the last modification time. So for these values it means that registering the directory will read initial time stamp as "2022-11-28T16:12:18.277871263Z", recording it in milliseconds. The file is modified (append in the example) and a short time later the WatchService should read the time stamp as "022-11-28T16:12:18.281290513Z", see that it has changed, and queue ENTRY_MODIFY event. So now I think we are back to why this is not happening on some AIX systems. Does it always fail on specific systems or it is intermittent? Any mount options or other config that enables or disables higher precision time stamps?

2022-12-13 15:17 UTC, sxa commented
> Does it always fail on specific systems or it is intermittent?

I have an AIX system that reproduces the problem (almost) 100% of the time. running your example repeatedly showsthe following - second timestamp always later than the first, although in some cases (The final one here and the third one) it's very close:
```
bash-5.1$ while true; do jdk-19.0.1+10-jre/bin/java AlanBatemanWatchTest; echo =====; sleep 5; done
2022-12-13T15:14:40.634203242Z
2022-12-13T15:14:40.638408744Z
=====
2022-12-13T15:14:45.937219162Z
2022-12-13T15:14:45.944337962Z
=====
2022-12-13T15:14:51.23575265Z
2022-12-13T15:14:51.235752651Z
=====
2022-12-13T15:14:56.525754548Z
2022-12-13T15:14:56.53320089Z
=====
2022-12-13T15:15:01.816169292Z
2022-12-13T15:15:01.82617524Z
=====
2022-12-13T15:15:07.096153867Z
2022-12-13T15:15:07.096153868Z
=====
2022-12-13T15:15:12.366438085Z
2022-12-13T15:15:12.373201878Z
=====
2022-12-13T15:15:17.645776392Z
2022-12-13T15:15:17.645776393Z
=====
```

2022-12-13 19:27 UTC, AlanBateman commented
@sxa Would it be possible to try the following patch to record the timestamps as Instants rather than milliseconds as I suspect the issue is that milliseconds isn't precision enough for these systems. The test that is leading to the discussion here needs improving too but that's another issue. Running with this patch will help tell us if this is the issue you are running into but it's not the right change as file times can be outside of the range supported by Instant but it should be good enough for testing.

```
diff --git a/src/java.base/share/classes/sun/nio/fs/PollingWatchService.java b/src/java.base/share/classes/sun/nio/fs/PollingWatchService.java
index f86626d196a..ce0f937bb1a 100644
--- a/src/java.base/share/classes/sun/nio/fs/PollingWatchService.java
+++ b/src/java.base/share/classes/sun/nio/fs/PollingWatchService.java
@@ -41,6 +41,7 @@ import java.security.PrivilegedAction;
 import java.security.PrivilegedExceptionAction;
 import java.security.PrivilegedActionException;
 import java.io.IOException;
+import java.time.Instant;
 import java.util.HashMap;
 import java.util.HashSet;
 import java.util.Iterator;
@@ -51,6 +52,7 @@ import java.util.concurrent.ScheduledExecutorService;
 import java.util.concurrent.ScheduledFuture;
 import java.util.concurrent.ThreadFactory;
 import java.util.concurrent.TimeUnit;
+import static java.nio.file.LinkOption.NOFOLLOW_LINKS;
 
 /**
  * Simple WatchService implementation that uses periodic tasks to poll
@@ -220,10 +222,10 @@ class PollingWatchService
      * Entry in directory cache to record file last-modified-time and tick-count
      */
     private static class CacheEntry {
-        private long lastModified;
+        private Instant lastModified;
         private int lastTickCount;
 
-        CacheEntry(long lastModified, int lastTickCount) {
+        CacheEntry(Instant lastModified, int lastTickCount) {
             this.lastModified = lastModified;
             this.lastTickCount = lastTickCount;
         }
@@ -232,11 +234,11 @@ class PollingWatchService
             return lastTickCount;
         }
 
-        long lastModified() {
+        Instant lastModified() {
             return lastModified;
         }
 
-        void update(long lastModified, int tickCount) {
+        void update(Instant lastModified, int tickCount) {
             this.lastModified = lastModified;
             this.lastTickCount = tickCount;
         }
@@ -278,8 +280,7 @@ class PollingWatchService
             try (DirectoryStream<Path> stream = Files.newDirectoryStream(dir)) {
                 for (Path entry: stream) {
                     // don't follow links
-                    long lastModified =
-                        Files.getLastModifiedTime(entry, LinkOption.NOFOLLOW_LINKS).toMillis();
+                    Instant lastModified = Files.getLastModifiedTime(entry, NOFOLLOW_LINKS).toInstant();
                     entries.put(entry.getFileName(), new CacheEntry(lastModified, tickCount));
                 }
             } catch (DirectoryIteratorException e) {
@@ -356,10 +357,9 @@ class PollingWatchService
             // iterate over all entries in directory
             try {
                 for (Path entry: stream) {
-                    long lastModified = 0L;
+                    Instant lastModified;
                     try {
-                        lastModified =
-                            Files.getLastModifiedTime(entry, LinkOption.NOFOLLOW_LINKS).toMillis();
+                        lastModified = Files.getLastModifiedTime(entry, NOFOLLOW_LINKS).toInstant();
                     } catch (IOException x) {
                         // unable to get attributes of entry. If file has just
                         // been deleted then we'll report it as deleted on the
@@ -371,8 +371,7 @@ class PollingWatchService
                     CacheEntry e = entries.get(entry.getFileName());
                     if (e == null) {
                         // new file found
-                        entries.put(entry.getFileName(),
-                                     new CacheEntry(lastModified, tickCount));
+                        entries.put(entry.getFileName(), new CacheEntry(lastModified, tickCount));
 
                         // queue ENTRY_CREATE if event enabled
                         if (events.contains(StandardWatchEventKinds.ENTRY_CREATE)) {
@@ -391,7 +390,7 @@ class PollingWatchService
                     }
 
                     // check if file has changed
-                    if (e.lastModified != lastModified) {
+                    if (!e.lastModified().equals(lastModified)) {
                         if (events.contains(StandardWatchEventKinds.ENTRY_MODIFY)) {
                             signalEvent(StandardWatchEventKinds.ENTRY_MODIFY,
                                         entry.getFileName());
```

2022-12-19 15:20 UTC, sxa commented
@AlanBateman I'm building both options now, but so far 6 attempts with #11665 are looking positive! (I've had to put that fix on top of an older SHA since I'm having problems building the latest code despite @backwaterred's fix at https://github.com/openjdk/jdk/pull/11443

2022-12-20 15:35 UTC, sxa commented
@AlanBateman I've submitted a backport for 11665 to jdk17u-dev since that's looking positive: https://github.com/openjdk/jdk17u-dev/pull/957
What's the process for getting it into jdk20? Can I just PR to `jdk20` in the absence of a `-dev` branch for it?

2022-12-20 22:57 UTC, backwaterred commented
I am happy to see that #11665 fixes this issue. As such, this fix is no longer required.

2022-12-20 22:57 UTC, closed without merging