8295970: Add jdk_vector tests in GHA
openjdk/jdk pull request #10879
Opened 2022-10-27 03:53 UTC by DamonFool

Hi all,

As discussed here https://github.com/openjdk/jdk/pull/10807#pullrequestreview-1150314487 , it would be better to add the vector api tests in GHA.

Thanks.
Best regards,
Jie

2022-10-27 06:13 UTC, shipilev requested changes
Sorry, but I don't think this is a good idea. If there are tests that are important for pre-integration testing, they should just be in `tier1`.

2022-10-27 06:41 UTC, DamonFool commented
> Sorry, but I don't think this is a good idea. If there are tests that are important for pre-integration testing, they should just be in `tier1`.

Since vector api is still in incubation, I'm not sure if it's OK to go into tier1.
I'm fine to add it in tier1 if there is no objection.
Thanks.

2022-10-27 07:24 UTC, mrserb commented
Probably it will be possible to select an additional tests dynamically based on changed module? Using the same logic as the labels in the PR?

2022-10-27 09:31 UTC, DamonFool commented
> Probably it will be possible to select an additional tests dynamically based on changed module? Using the same logic as the labels in the PR?

Thanks @mrserb for your suggestion.

Dynamical testing configuration would increase the GHA complexity, which seems not worth it for jdk_vector.
This is because all 3 tier1_part* and jdk_vector took about 5 min to run according to Oracle's internal testing times.

So I think it's fine to add it in GHA directly.
Thanks.

2022-10-27 13:57 UTC, erikj79 commented
The default set of tests included in GHA is currently defined to be exactly tier1. That is the set of tests that we have collectively agreed on represents a reasonably sized set that gives the best coverage for the time spent (at least that's the intention of tier1). The time spent here is probably the most important variable, as whatever we put here, everyone runs all the time in their PRs and PFs. Adding 5 minutes may not seem like much, but multiplied with platforms and all the users and PRs it adds up to a lot. Also imagine if more components would want to add to the set, pointing to this change as a precedent ,adding another 5 minutes, and then another 5 minutes, eventually the reasonable size of the test set becomes completely unreasonable.

My point is that we can't just add more and more to GHA on a whim. The current agreement is for it to be exactly tier1. If you can't motivate that your tests should be part of tier1, then I find it pretty hard to motivate that it should be part of GHA. I don't know enough about these tests to know if they should fit in tier1/GHA or not, I'm just pointing out that we need to keep a pretty high bar to avoid bloating the set.

For this particular issue, would it be possible to define a minimal set of vector api tests that would have discovered the problem in https://github.com/openjdk/jdk/pull/10807 without taking 5 minutes? Perhaps the better solution here would be to allow a single or very few specific tests into tier1?

2022-10-27 17:01 UTC, vnkozlov commented
I think we can meet all requests by adding `jdk_vector_sanity` subset of vector tests similar to existing `jdk_svc_sanity`.
The motivation for that is to catch obvious bugs in vector code generation on 32-bit platforms and aarch64 very early.
We, in Oracle, help to test 64 bits but it is not enough I think.
Vector API is stable enough already and I think we can have some sanity checks for it in tier1.
The only issue is to find subset of tests.

2022-10-28 07:21 UTC, DamonFool commented
> I think we can meet all requests by adding `jdk_vector_sanity` subset of vector tests similar to existing `jdk_svc_sanity`. The motivation for that is to catch obvious bugs in vector code generation on 32-bit platforms and aarch64 very early. We, in Oracle, help to test 64 bits but it is not enough I think. Vector API is stable enough already and I think we can have some sanity checks for it in tier1. The only issue is to find subset of tests.

Good suggestion!
And the `jdk_vector_sanity` test group had been added.

The subset is selected as in the following picture (red in the picture).
The XMaxVector tests are selected because they will be 512 vectors on x86/AVX512 and 256 vectors on x86/AVX2.
And for most cases, people would like to use the max length vectors.
Thanks.

<img width="310" alt="image" src="https://user-images.githubusercontent.com/19923746/198526855-f1adb163-f6cf-4f38-b76b-c35c06337174.png">

2022-10-28 13:48 UTC, DamonFool commented
/label add core-libs
/label add hotspot-compiler

2022-10-28 13:53 UTC, DamonFool commented
> I think you need to add at least one other label than `build` to this now to make sure the right people can have a say in the change.

Done.
Thanks @erikj79 .

2022-10-29 07:58 UTC, AlanBateman commented
> Good suggestion!
> And the `jdk_vector_sanity` test group had been added.

In general, running a few fast sanity tests from several areas in tier1 seems a good idea. Having test lists in the TEST.group files isn't very appealing as they easily get out of the sync with the tests in the tree. I realise there are already some test lists in both the hotspot and jdk TEST.groups but it feels like it needs something better so that RunTests.gmk/jtreg can select the sanity tests to run. This is not an objection to this change proposed here, just a comment that this type of configuration is annoying to maintain.

2022-10-29 23:08 UTC, mrserb commented
What about possibility to run additional group of the test by passing somehow the name of group to the GA, via label or via /test cmd, or via parameter to the specific task in GA?

2022-10-30 12:03 UTC, DamonFool commented
> I realise there are already some test lists in both the hotspot and jdk TEST.groups but it feels like it needs something better so that RunTests.gmk/jtreg can select the sanity tests to run.

Thanks @AlanBateman for this comment.
Is there an existing example to follow?
Thanks.

2022-10-30 12:17 UTC, DamonFool commented
> What about possibility to run additional group of the test by passing somehow the name of group to the GA, via label or via /test cmd, or via parameter to the specific task in GA?

Well, it sounds good to run specific tests via label or /test cmd.
However, if the vector api tests are OK to be added in tier1 I think it's fine to run them in GHA directly.

Maybe, we can implement this feature in the future not only for vector api tests but also for other tests too.

2022-11-01 07:26 UTC, DamonFool commented
Hi all,

I changed the JBS title as `Add vector api sanity tests in tier1`.
And the added `jdk_vector_sanity` tests can be run in less than 2min on my testing box.
Any comments?

Thanks.

2022-11-01 12:45 UTC, erikj79 approved these changes
This looks good to me. The group tier1_part3 looks like it's currently the fastest of the 3, so it's the right one to add to.

2022-11-01 16:13 UTC, vnkozlov approved these changes
Good.

I think we need review from @shipilev too since he had strong opinion about this.

2022-11-02 01:24 UTC, DamonFool commented
Thanks @erikj79 and @vnkozlov for the review.
So @shipilev , are you fine with this change?
Thanks.

2022-11-02 15:11 UTC, shipilev reviewed
I think the usual style for these files is to maintain original order/sorting.

2022-11-02 15:11 UTC, shipilev commented on test/jdk/TEST.groups
>     -:jdk_svc_sanity \
```suggestion
    :jdk_svc \
   -:jdk_svc_sanity \
   -:jdk_vector_sanity \
```

2022-11-02 15:11 UTC, shipilev commented on test/jdk/TEST.groups
> +    jdk/incubator/vector/AddTest.java \
These should probably be sorted too.

2022-11-02 15:11 UTC, shipilev commented on test/jdk/TEST.groups
>      :jdk_foreign \
```suggestion
    :jdk_math \
    :jdk_svc_sanity \
    :jdk_foreign \
    :jdk_vector_sanity \
```

2022-11-03 03:30 UTC, DamonFool commented
@shipilev , all your comments had been resolved.
Thanks.

2022-11-03 08:47 UTC, shipilev approved these changes

2022-11-03 10:44 UTC, DamonFool commented
Thank you all for the review and comments.
/integrate

2022-11-03 12:14 UTC, closed without merging