8253002: Remove the unused SafePointNode::_oop_map field
openjdk/jdk pull request #109
Opened 2020-09-10 10:17 UTC by JornVernee

Hi,

I've been looking a lot at the code for generating oop maps for call nodes lately, and noticed that SafePointNode had an oopMap field that was unused (which led to some confusing as to where the oop map was actually set).

The oop map is instead generated and set in buildOopMap OopFlow::compute_reach after matching: https://github.com/openjdk/jdk/blob/master/src/hotspot/share/opto/buildOopMap.cpp#L122 So the field on the ideal node is unused.

This patch removes the field and cleans up related code. I've left a comment in SafePointNode to point people looking for the oop map at buildOopMap.cpp

Thanks,
Jorn

2020-09-10 10:22 UTC, JornVernee commented
/test

2020-09-10 20:16 UTC, kasim672 commented
05bdc4d

2020-09-14 13:19 UTC, shipilev requested changes
There is also a forward declaration of `class OopMap;` in `callnode.hpp`, do we still need it?

2020-09-14 13:19 UTC, shipilev commented on src/hotspot/share/opto/callnode.hpp
> +  // OopFlow::compute_reach on the MachSafePointNode. (See buildOopMap.cpp)
I don't think we need this comment. I think it would bitrot eventually. It seems the code to construct `OopMap` is easily discoverable already.

2020-09-15 09:26 UTC, JornVernee commented
@shipilev Thanks for the review!

> There is also a forward declaration of class OopMap; in callnode.hpp, do we still need it?

Doesn't look like it, good catch!

> I don't think we need this comment. I think it would bitrot eventually. It seems the code to construct OopMap is easily discoverable already.

Yeah, good point, I've removed it.

I've ran a build on Windows and Linux (WSL). Still builds with the new changes, I hope that's enough to test them.

2020-09-15 09:32 UTC, TobiHartmann approved these changes
Looks good.

2020-09-15 12:19 UTC, JornVernee commented
/integrate

2020-09-15 12:21 UTC, closed without merging