8296157: Rename FileMapInfo::space_at() to region_at()
openjdk/jdk pull request #10937
Opened 2022-11-01 21:39 UTC by matias9927

Most of the CDS code refers to a memory blocks inside a CDS file as "regions", represented by the type FileMapRegion. The method FileRegion* space_at() has been renamed to region_at() and all instances of its use have been replaced. Verified with tier 1-4 tests.

2022-11-02 03:30 UTC, iklam commented
Looks good. There's more to change:

- in cds.h, change `_space` to `_regions`, and increment`CURRENT_CDS_ARCHIVE_VERSION` by 1.
- in src/jdk.hotspot.agent/share/classes/sun/jvm/hotspot/memory/FileMapInfo.java:
  -  `_space[0]` -> `_regions[0]`, 
  - `spaceField` -> `regions_0Field`
  - `space_0` -> `regions_0`, etc
  - This change is tested by test/hotspot/jtreg/serviceability/sa/ClhsdbCDSCore.java
- You will also see a bunch of C++ compilation errors to tell you what else need to be changed.

2022-11-02 03:33 UTC, iklam approved these changes
Also the functions first_core_space/last_core_space in filemap.hpp need to be renamed. Please also check filemap.cpp to see if there are any other use of "space" that refers to a FileMapRegion.

2022-11-02 03:33 UTC, iklam commented on src/hotspot/share/cds/filemap.cpp
> +      region_at(region_idx)->init_bitmaps(bitmaps->at(oopmap_idx),
The next line need to be aligned.

2022-11-02 15:52 UTC, iklam requested changes

2022-11-03 18:32 UTC, calvinccheung approved these changes
Looks good.

One nit: please update copyright year 2021 to 2022 in cdsConstants.cpp.

2022-11-03 20:22 UTC, matias9927 commented
/integrate

2022-11-03 21:21 UTC, iklam approved these changes

2022-11-03 21:21 UTC, iklam commented
/sponsor

2022-11-03 21:24 UTC, closed without merging