JDK-8296360: Track native memory used by zlib via NMT
openjdk/jdk pull request #10988
Opened 2022-11-04 14:35 UTC by tstuefe

2022-12-05 10:18 UTC, AlanBateman commented
I think it's a bit premature to mark this review. The discussion thread "Extend Native Memory Tracking over the JDK ?" needs more discussion and input from others. We need to be forward looking in those discussions as it is very likely that the JNI functions and memory allocation will move to Panama in the future. Also we need to think about the maintainable and be able to manage catagories in the libs code without needing to add to allocation.hpp - I suspect this is probably something you've thought about already.

2022-12-05 13:16 UTC, magicus commented
/label -build

2022-12-11 08:07 UTC, tstuefe commented
Withdrawing for now; let's see how our discussion goes.

2023-03-22 15:01 UTC, gerard-ziemski requested changes
It's great that we are trying to keep an eye on memory in 3rd party libraries!

I like the change, however, I do have 2 items of feedback that I left as comments in the changed files...

2023-03-23 06:03 UTC, tstuefe commented
> It's great that we are trying to keep an eye on memory in 3rd party libraries!
> 
> I like the change, however, I do have 2 items of feedback that I left as comments in the changed files...

Thanks, Gerard! Unfortunately, work has stalled on this for now until we come to an overencompassing agreement.

2023-07-13 18:50 UTC, closed without merging