8296239: ISO 4217 Amendment 174 Update
openjdk/jdk pull request #10994
Opened 2022-11-04 17:21 UTC by justin-curtis-lu

Incorporated ISO 174 Amendment update: Update Croatia's currency from Kuna to Euro (to take place on 1/1/2023).

2022-11-04 18:13 UTC, naotoj requested changes

2022-11-04 18:18 UTC, justin-curtis-lu commented on src/java.base/share/data/currency/CurrencyData.properties
> +HR=HRK;2022-12-31-21-00-00;EUR
Made the change thank you

2022-11-08 16:23 UTC, naotoj approved these changes

2022-11-09 01:16 UTC, naotoj commented
/sponsor

2022-11-09 01:18 UTC, closed without merging