JDK-8296406: ChainingConstructors jtreg test reduce code duplication
openjdk/jdk pull request #11016
Opened 2022-11-07 12:49 UTC by MBaesken

The java/security/Exceptions/ChainingConstructors jdk jtreg test shows quite a lot of code duplication. The test code can be simplified e.g. by using generics. Additionally the test failure output was improved and a test for the constructors of CertPathBuilderException was added.

2022-11-07 16:00 UTC, mcpowers commented
LGTM

2022-11-08 13:37 UTC, seanjmullan commented
Add a `noreg-self` label to the JBS issue since this is a fix to the test itself. Also, I would classify this as an Enhancement, and not a Bug.

2022-11-08 13:52 UTC, MBaesken commented
> Add a `noreg-self` label to the JBS issue since this is a fix to the test itself. Also, I would classify this as an Enhancement, and not a Bug.

Thanks, this all makes sense ! I adjusted the JBS issue.

2022-11-08 14:01 UTC, seanjmullan requested changes

2022-11-08 15:15 UTC, MBaesken commented on test/jdk/java/security/Exceptions/ChainingConstructors.java
> -*/
Hi Sean,  the summary says that the test is about  "java.security Exceptions" so  javax.net.ssl.SSLException.java from another package might not fit in, maybe that's why it was commented out.
Should I still add it ? If so, the  summary comment might need a little bit adjustment, what about this "Test constructors for exception chaining of  security-related exceptions"  ?

2022-11-08 15:54 UTC, seanjmullan commented on test/jdk/java/security/Exceptions/ChainingConstructors.java
> -*/
Good point. I think it is ok to make an exception (no pun intended) for `SSLException` for this test. Changing the summary comment to your suggestion is fine with me.

2022-11-08 16:15 UTC, MBaesken commented
I added the second bug id, adjusted the summary comment and added SSLException for this test.

2022-11-08 17:33 UTC, seanjmullan approved these changes
Looks good!

2022-11-09 08:12 UTC, MBaesken commented
Mark and Sean, thanks for the reviews !
Do I need another review ?
Best regards, Matthias

2022-11-09 12:59 UTC, seanjmullan commented
> Mark and Sean, thanks for the reviews ! Do I need another review ? Best regards, Matthias

No, you can integrate now.

2022-11-09 13:47 UTC, MBaesken commented
/integrate

2022-11-09 13:50 UTC, closed without merging