remove deprecated using java.io.File.toURL() in internal classes
openjdk/jdk pull request #1108
Opened 2020-11-07 07:55 UTC by bastie

In result of Javadoc to do not use java.io.File.toURL()
Change use  java.io.File.toURL().toURI() instead.

2020-11-07 10:47 UTC, bastie commented
8066622 8066637: only for java.io.File.toURL

2020-11-08 16:58 UTC, prrace requested changes
You reference a desktop bug that discusses many, many deprecations
and skara has identified https://bugs.openjdk.java.net/browse/JDK-8066622
as the issue being fixed.
Yet you propose to fix precisely one of these.
But when this is integrated that bug will be closed out as resolved.
I think you need a new bug about JUST the changes you are making.
So I don't think you should use that bug id any where in this PR.
And I'd like to hear whether you actually *tested* splashscreen with your change ? I see no sign that you did.

2020-11-08 16:58 UTC, prrace commented
/reviewers 2

2020-11-10 11:45 UTC, bastie commented
> You reference a desktop bug that discusses many, many deprecations ...
Yep. In my opinion this is a bot problem here and need other place to discuss. 

> Yet you propose to fix precisely one of these.
@prrace:  Not really. 
The way to work with problems differ. Both bugs - maybe these are more quality change requests than bugs - are bullet lists and are created on build process. The different is, I work on single quality tests and remove deprecated code from source base. So in my clean Java build the method java.io.File.toUrl() does not(!) exist. 
Because java.io.File.toURL() doesn't exist, also two patches are needed for JDK build process (internal I use diff-patch).

> And I'd like to hear whether you actually _tested_ splashscreen with your change ? I see no sign that you did.
I'm not sure, what you want to listen. I work with a clean Java build with patch to remove java.io.File.toURL() and change the collateral damages.

2021-01-05 16:08 UTC, closed without merging