8292265: Add old gen used field at G1HeapSummary JFR event
openjdk/jdk pull request #11303
Opened 2022-11-22 23:09 UTC by sangheon

Hi all,

Can I have reviews for this change which adds 'old gen used' field at existing G1HeapSummary event?

Testing: tier1 ~ tier3

Thanks,
Sangheon

2022-11-22 23:15 UTC, sangheon commented
/label add hotspot-gc, hotspot-jfr
/label remove hotspot

2022-11-23 18:13 UTC, tschatzl requested changes

2022-11-30 09:21 UTC, tschatzl approved these changes
Lgtm.

2022-12-05 14:37 UTC, albertnetymk commented on src/hotspot/share/gc/g1/g1CollectedHeap.cpp
> +  size_t old_used_bytes = _monitoring_support->old_gen_used();
I think it's best to include `gen` in the name (across the whole PR), just to avoid the confusion of Old-region-type vs old-generation.

2022-12-08 19:07 UTC, albertnetymk approved these changes

2022-12-08 22:12 UTC, sangheon commented
Thanks @tschatzl and @albertnetymk for your reviews.

/integrate

2022-12-09 23:30 UTC, sangheon commented
/integrate

2022-12-09 23:31 UTC, closed without merging