8297389: resexhausted003 fails with assert(!thread->owns_locks()) failed: must release all locks when leaving VM
openjdk/jdk pull request #11316
Opened 2022-11-23 11:56 UTC by TobiHartmann

`Method::build_profiling_method_data` acquires the `MethodData_lock` when initializing `Method::_method_data` to prevent multiple allocations by different threads. The problem is that when metaspace allocation fails and `JvmtiExport::should_post_resource_exhausted()` is set, we assert during the `ThreadToNativeFromVM` transition in JVMTI code.

Since concurrent initialization is a rare event, I suggest to get rid of the lock and perform the initialization with a `cmpxchg`, similar to how method counters are initialized:
https://github.com/openjdk/jdk/blob/f4b5065c37e86f4b2ca26da6ce678febe4a52950/src/hotspot/share/oops/method.cpp#L644-L646

Since [current code](https://github.com/openjdk/jdk/blob/f4b5065c37e86f4b2ca26da6ce678febe4a52950/src/hotspot/share/oops/method.inline.hpp#L41-L46) in `Method::set_method_data` uses a `Atomic::release_store`, I added a `OrderAccess::release()`.

Thanks,
Tobias

2022-11-23 11:56 UTC, TobiHartmann commented
/label hotspot

2022-11-23 21:38 UTC, dholmes-ora requested changes
If `MethodData::allocate` cannot be called whilst holding a lock then perhaps we can assert that in there?

I think there is a broader problem here that metaspace allocation can occur in numerous places and any failure could post the resource-exhausted event and potentially lead to problems like this.

This fix side-steps one problematic call-site, but going lock-free has its own concerns.

2022-11-23 21:38 UTC, dholmes-ora commented on src/hotspot/share/oops/method.cpp
> +  OrderAccess::release();
A release here is not necessary as `Atomic::replace_if_null` will by default have `memory_order_conservative` which maintains the full bi-directional fence of the internal `cmpxchg`.

2022-11-23 21:38 UTC, dholmes-ora commented on src/hotspot/share/oops/method.cpp
> +  MethodData* method_data = MethodData::allocate(loader_data, method, THREAD);
So the downside of lock-free here is that we have to pre-allocate and then later free. How expensive is that? How likely are we to get multiple threads attempting this at the same time? We might trigger a resource-exhausted event unnecessarily due to the temporary use of metaspace.

2022-11-28 12:06 UTC, TobiHartmann commented
Thanks for the review, David!

I added an assert to `MethodData::allocate` and fixed the ciReplay code which only ever gets executed by a single thread by removing the lock. I also removed the `OrderAccess::release()`.

Regarding the overhead of going lock-free: I temporarily added code that counts the number of times that multiple threads attempt initialization and asserts if it's more that 50x. This triggers in 25 out of 203.772 runs (tests from tier1 to tier3). The average size of these allocations is around 88 words (704 bytes). I therefore think it's fine to avoid a lock in this case. Also, we already use a lock-free mechanism for `method::build_method_counters`.

What do you think?

2022-11-28 14:14 UTC, reinrich approved these changes
Thanks for taking care of the issue. The fix looks ok to me. Seems like you've removed all uses of `MethodData_lock` so you could remove the declaration and definition too.

Thanks, Richard.

2022-11-28 14:28 UTC, TobiHartmann commented
Thanks for the review, Richard. Good catch, I removed the `MethodData_lock`.

2022-11-29 04:08 UTC, dholmes-ora commented
> I therefore think it's fine to avoid a lock in this case. Also, we already use a lock-free mechanism for `Method::build_method_counters`.

`Method::build_method_counters` doesn't appear to be lock-free, in the sense there are no atomic operations; rather concurrency just doesn't seem to be a concern with that code. ??

But as long as the overhead is low and interference unlikely, then we can see how this works out in practice. Thanks.

2022-11-29 07:34 UTC, TobiHartmann commented
> I'm not sure if it's guaranteed that replay runs single-threaded. I haven't looked into the details, but I think ReplayInline can run in any compiler thread after startup, and then of course there is JDK-8254110.

But ReplayInline does not load ciMethodData, i.e., does not call `process_ciMethodData`, right?

The only way this code can get executed is through `JNI_CreateJavaVM_inner -> ciReplay::replay -> ciReplay::replay_impl -> process-> process_command -> process_ciMethodData` and that only ever happens single-threaded.

Of course, if we are ever going to implement [JDK-8254110](https://bugs.openjdk.org/browse/JDK-8254110), we need to revisit that code, but in that case the assert that I added will trigger.

What do you think?

> Method::build_method_counters doesn't appear to be lock-free, in the sense there are no atomic operations; rather concurrency just doesn't seem to be a concern with that code. ??

It uses the exact same mechanism that I now added to `Method::build_profiling_method_data`, including atomic operations to initialize `_method_counters`:
https://github.com/openjdk/jdk/blob/f4b5065c37e86f4b2ca26da6ce678febe4a52950/src/hotspot/share/oops/method.cpp#L651-L654

And I verified that multiple threads attempt to initialize the counters by adding verification code to:
https://github.com/openjdk/jdk/blob/f4b5065c37e86f4b2ca26da6ce678febe4a52950/src/hotspot/share/oops/method.cpp#L644-L646

2022-11-30 06:28 UTC, dholmes-ora commented
> It uses the exact same mechanism that I now added to Method::build_profiling_method_data, including atomic operations to initialize _method_counters

Sorry I somehow missed the `init_method_counters` logic. :(

2022-11-30 08:54 UTC, dean-long commented
> Of course, if we are ever going to implement [JDK-8254110](https://bugs.openjdk.org/browse/JDK-8254110), we need to revisit that code, but in that case the assert that I added will trigger.
> 
> What do you think?

OK, please add a TODO in JDK-8254110 explaining this so it doesn't get lost.

2022-11-30 10:09 UTC, TobiHartmann commented
> OK, please add a TODO in JDK-8254110 explaining this so it doesn't get lost.

Thanks, done.

2022-12-01 00:06 UTC, dholmes-ora approved these changes
Changes seem okay but I'm not that familiar with the actual code here.

Thanks.

2022-12-01 06:10 UTC, TobiHartmann commented
Thanks, David!

2022-12-01 08:14 UTC, dean-long approved these changes

2022-12-01 08:48 UTC, TobiHartmann commented
Thanks, Dean!

2022-12-01 08:48 UTC, TobiHartmann commented
/integrate

2022-12-01 08:50 UTC, closed without merging