8297138-UB leading to crash in Amalloc with optimized builds
openjdk/jdk pull request #11320
Opened 2022-11-23 12:52 UTC by afshin-zafari

2022-11-25 10:36 UTC, afshin-zafari commented
/covered

2022-11-28 01:54 UTC, dholmes-ora reviewed
Hi Afshin,

I would have expected the fix here to be making the `free` debug_only as well. It is far from clear to me we want this code in a product build.

Thanks.

2022-11-28 09:20 UTC, tstuefe commented
@afshin-zafari Good catch. This is not only UB, but most certainly breaks if any kind of malloc headers are used (e.g. if NMT is enabled). 

Could you please, just for Reviewer convenience, add a description of problem+patch in the PR text? I usually just copy the JBS issue text and, if needed, add comments describing the patch.

> I would have expected the fix here to be making the `free` debug_only as well. It is far from clear to me we want this code in a product build.

I agree with @dholmes-ora . I would prefer this to be explicitly debug-only with ifdefs. Even though in product builds UseMallocOnly is const false.

As a point of discussion, not for this RFE, I wonder whether we could get rid of `UseMallocOnly` completely. It is a constant hindrance when reworking Arenas. I'm curious about what we use it for. The only reason I can think of is to use buffer overrun detection inherent in os::malloc. But that could be added to Arena allocations as well. I attempted such a rewrite last year but stopped when the patch became too complex, and I did not know if anyone even cared for UseMallocOnly. Do people care?

2022-11-28 11:06 UTC, afshin-zafari commented
I have no idea about other possible patches. Please, let me know specifically what should I do?

2022-11-28 12:33 UTC, tstuefe commented
> I have no idea about other possible patches. Please, let me know specifically what should I do?

Guard the free with `ifdef ASSERT`. Even better, check all mentionings of UseMallocOnly and make sure those only apply for debug builds.

Cheers, Thomas

2022-11-28 13:38 UTC, coleenp commented
The UseMallocOnly flag is a develop only flag.  If #ifdef ASSERT, the code under it is optimized out.  There's no need to litter the code with debug_only() or DEBUG_ONLY() for this and that's error prone, as this bug complains.

2022-11-28 13:39 UTC, coleenp approved these changes
This looks good to me.

2022-11-28 13:39 UTC, coleenp commented on src/hotspot/share/memory/arena.cpp
> +
Nit, can you remove this blank line so that there's only one blank line?

2022-11-28 13:41 UTC, coleenp commented
@afshin-zafari Your last comment above should be in the top section (description section).  You can edit that.  You should also say what testing was performed on this patch.

2022-11-28 13:43 UTC, coleenp commented
Also, yes, I don't know why we have UseMallocOnly anymore.

2022-11-28 13:56 UTC, tstuefe commented
> The UseMallocOnly flag is a develop only flag. Even without #ifdef ASSERT, the code under it is optimized out. There's no need to litter the code with debug_only() or DEBUG_ONLY() for this and that's error prone, as this bug complains.

It is a matter of taste I guess. I don't find DEBUG_ONLY etc offensive, since I see with one glance which coding runs. Now one needs to look up the definition of the flag to know it gets inlined out for product builds.

2022-11-28 13:57 UTC, coleenp commented
I think the conditional compilation is offensive, and it caused this bug, which makes it more offensive. :)

2022-11-28 14:20 UTC, tstuefe commented
> I think the conditional compilation is offensive, and it caused this bug, which makes it more offensive. :)

See, I dislike the name more (Arena::malloc). Named *exactly* like its libc counterpart, which is asking for trouble. It relies solely on scope, and you don't get even a warning on mismatch.

2022-11-28 14:40 UTC, coleenp commented
Yeah that's a bad name.  The more I look at this the more I hate it.

2022-11-28 14:46 UTC, tstuefe commented
> Yeah that's a bad name. The more I look at this the more I hate it.

In the past I fervently wished for UseMallocOnly to go away. I even prepared a prototype that would provide buffer overrun checks in Arenas (enveloping each individual arena allocation), in the assumption that was why UseMallocOnly existed. The only problem I encountered was that we sometimes use Arena for packed data, where the data is accessed as an array and needs to be packed without interleaving canaries. I think HandleAreas are such an example.

It would be nice if we could just remove it. I assume only compiler people use it.

2022-11-28 14:55 UTC, coleenp requested changes
Ok, I've changed my mind.  UseMallocOnly is protected by #ifdef ASSERT in other places that are untouched by this change.  So the free_malloced_objects call should be under #ifdef ASSERT and the function definitions should be under #ifdef ASSERT (not PRODUCT).
It should use the capital DEBUG_ONLY though not the lower case DEBUG_ONLY.
Also Arena::malloc name should be changed to malloc_object just so it's not just malloc.

inline void Arena::free_all(char** start, char** end) {
Should be not a member of Arena, ie. should be static inline.

2022-11-28 14:58 UTC, coleenp commented
> It would be nice if we could just remove it. I assume only compiler people use it.
No idea who uses it.   I asked on our internal channels.

2022-11-29 03:45 UTC, dholmes-ora commented
I think we can close this PR in favour of a RFE that simply removes `UseMallocOnly`. It may have been useful whilst VM memory management was in its infancy (it was introduced in 1998) but now it is just a liability. I think we can simply remove it (and not worry if Arenas need better debuggability or error tracking - that would be a separate RFE).

2022-11-29 06:50 UTC, tstuefe commented
> I think we can close this PR in favour of a RFE that simply removes `UseMallocOnly`. It may have been useful whilst VM memory management was in its infancy (it was introduced in 1998) but now it is just a liability. I think we can simply remove it (and not worry if Arenas need better debuggability or error tracking - that would be a separate RFE).

I'm very much for it!

But we may need a way to detect memory stomping across arena allocations. See https://bugs.openjdk.org/browse/JDK-8007475, and hotspot/jtreg/runtime/8007475/StackMapFrameTest.java. I have used UseMallocOnly for similar purposes in the past.

As I wrote before when I did some Arena code massaging last year (8263557, 8263558, etc, see git log) I also started to add per-arena-allocation-canaries. I hit some minor road blocked and then stopped because I was not sure it was even wanted. 

Having canaries in Arenas would also have the advantage of being both faster and leaner than what we do now with C-heap allocations. So we could afford to enable them for more tests.

So if you all agree, I could bookmark some time early in the jdk20 time frame to revive my patch. We could remove UseMallocOnly now, or do it together with the proposed canary change.

2022-11-29 14:38 UTC, coleenp commented
@tstuefe is your Arena canary patch as much code as UseMallocOnly?  I'm writing the RFE now and the argument for removing UseMallocOnly is to not have this extra code to maintain that nobody really uses.  I guess we can see once you send a PR but hopefully you can share code with os::malloc or something.   Thanks for all your comments on this PR.

2022-11-29 15:21 UTC, tstuefe commented
> > @tstuefe is your Arena canary patch as much code as UseMallocOnly? I'm writing the RFE now and the argument for removing UseMallocOnly is to not have this extra code to maintain that nobody really uses. I guess we can see once you send a PR but hopefully you can share code with os::malloc or something. Thanks for all your comments on this PR.
> 
> Hi @coleenp, you may not like it: [master...tstuefe:jdk:arena-remove-usemalloc-and-guard-allocs](https://github.com/openjdk/jdk/compare/master...tstuefe:jdk:arena-remove-usemalloc-and-guard-allocs) . Note that I mixed a bunch of cleanups and comments in there, if I were to do it again I would do it in a more lightweight fashion.

Actually, a very simple way to implement arena-based canaries would be to do like Metaspace arenas and inject a pointer chain as "normal" allocation. Like this:

```
class Arena {
  struct canary_t { canary_t* next; .... };
  canary_t* _first_canary;
  canary_t* _last_canary;

  void* Amalloc(size s) {
    void* p_user_data = inner_Amalloc();
    canary_t* c = inner_Amalloc(sizeof(canary_t));
    // ... chain c together 
  }
```

then, to check for overwriters (in ~Arena or whenever you like), walk the chain. 

This piggy-backs nicely on the normal allocation paths, since the canary is allocated like any other block would be.

2023-01-24 19:10 UTC, closed without merging