Improve vector rematerialization support
openjdk/jdk pull request #1136
Opened 2020-11-09 21:46 UTC by iwanowww

2020-11-09 21:49 UTC, iwanowww commented
/label add hotspot-compiler
/label remove hotspot

2020-11-19 11:03 UTC, TobiHartmann approved these changes
Looks reasonable to me.

2020-11-19 18:10 UTC, vnkozlov requested changes

2020-11-19 18:10 UTC, vnkozlov commented on src/hotspot/share/prims/vectorSupport.cpp
> +      case T_DOUBLE: arr->bool_at_put(index,  (*(jlong*)addr) != 0); break;
Why you push `bool` value for everything?!!!

2020-11-19 18:16 UTC, vnkozlov requested changes

2020-11-19 18:16 UTC, vnkozlov commented on src/hotspot/share/prims/vectorSupport.cpp
> +      case T_DOUBLE: arr->bool_at_put(index,  (*(jlong*)addr) != 0); break;
Okay. After reading code more I understand that array is boolean type for case when `is_mask` is `true`. So changes are correct.

2020-11-19 18:16 UTC, vnkozlov commented on src/hotspot/share/prims/vectorSupport.cpp
> +      case T_DOUBLE: arr->bool_at_put(index,  (*(jlong*)addr) != 0); break;
May be you need separate method to avoid this confusion. The code is separate anyway.

2020-11-20 15:24 UTC, vnkozlov commented
After thinking more on this a separate method could complicate changes. At least add a comment.

2020-11-20 16:24 UTC, iwanowww commented on src/hotspot/share/prims/vectorSupport.cpp
> +      default: assert(false, "unsupported: %s", type2name(elem_bt));
Fixed.

2020-11-20 16:26 UTC, iwanowww commented
> After thinking more on this a separate method could complicate changes. At least add a comment.

Added. Frankly speaking, I was on a fence when touching that code, but found it cleaner to have masks and vectors initialized in the same place.

2020-11-20 18:40 UTC, vnkozlov approved these changes

2020-11-20 18:40 UTC, vnkozlov commented on src/hotspot/share/prims/vectorSupport.cpp
> +    // TODO: revisit when predicate registers are fully supported.
Good and thanks.

2020-11-20 20:01 UTC, iwanowww commented
Thanks for the reviews, Tobias and Vladimir.

2020-11-20 21:15 UTC, iwanowww commented
/integrate

2020-11-20 21:17 UTC, closed without merging