8297740
openjdk/jdk pull request #11409
Opened 2022-11-29 09:28 UTC by albertnetymk

Fix the failure in `-Xcomp` mode. Thanks to David's analysis that a local variable is not enough to keep the object live; using a global variable now.

2022-11-29 10:43 UTC, stefank commented
Could an alternative be to print the object after the liveness check, but before the triggering of the class unloading? I think that's the approach @kstefanj is going for with #11300. Maybe you should sync up and discuss a common solution?

2022-11-29 19:23 UTC, dcubed-ojdk approved these changes
Thumbs up. This is a trivial fix.

I'm fine with this current fix. This bug is generating 2 failures per Tier4 job set
so it's a bit on the noisy side. Further refinements can be done with an RFE.

2022-11-30 00:22 UTC, dholmes-ora requested changes
Making the reference static should fix the issue but you no longer need the local reference. You could just keep the 'o' name on the global and avoid any other changes.

Thanks.

2022-11-30 00:22 UTC, dholmes-ora commented on test/hotspot/jtreg/runtime/ClassUnload/UnloadTest.java
> +    // JDK-8297740: using a global static field to keep the object live in -Xcomp mode.
No need to reference the bug in the comment - we don't generally do that. You could add it to `@bug` list.

2022-11-30 00:22 UTC, dholmes-ora commented on test/hotspot/jtreg/runtime/ClassUnload/UnloadTest.java
> +        global_o = o;
You don't need the local 'o' any more.

2022-11-30 08:57 UTC, albertnetymk commented
> Could an alternative be to print the object after the liveness check, but before the triggering of the class unloading?

That probably works as well. Actually both approaches (static-field and use-in-print) can be seen in existing tests:

```
test/hotspot/jtreg/runtime/ClassUnload/KeepAliveObject.java
test/hotspot/jtreg/runtime/ClassUnload/ConstantPoolDependsTest.java
```

I will keep the current approach because the intent is more explicit this way.

2022-11-30 08:57 UTC, albertnetymk commented
> You could just keep the 'o' name on the global and avoid any other changes.

Revised as suggested.

2022-11-30 12:59 UTC, albertnetymk commented
Tier4 passes with the PR; merging now to keep the CI clean.

2022-11-30 13:01 UTC, closed without merging

2022-12-01 00:42 UTC, dholmes-ora commented
I don't know why I didn't think about this sooner but the right way to deal with liveness issues is to use `Reference.reachabilityFence`.

2022-12-01 10:33 UTC, albertnetymk commented
Filed at https://bugs.openjdk.org/browse/JDK-8297936