JDK-8298138: Shenandoah: HdrSeq asserts "sub-bucket index (512) overflow for value ( 1.00)"
openjdk/jdk pull request #11524
Opened 2022-12-06 03:46 UTC by ysramakrishna

- Fixed a boundary condition that was triggering an assert.
- Added a simple-minded gtest for HdrSeq, which allows one to exercise the asserting code in a debug build.

2022-12-06 11:35 UTC, rkennke requested changes
Hi Ramki,
The change looks good. I have a few minor comments.

2022-12-06 11:35 UTC, rkennke commented on test/hotspot/gtest/gc/shenandoah/test_shenandoahNumberSeq.cpp
> + * Copyright (c) 2016, 2017, Oracle and/or its affiliates. All rights reserved.
The copyright should be 2022.

2022-12-06 18:19 UTC, ysramakrishna commented on src/hotspot/share/gc/shenandoah/shenandoahNumberSeq.hpp
> +class BinaryMagnitudeSeq : public CHeapObj<mtInternal> {
Wanted a spec for allocation for correct accounting.

Changed to mtGC; thanks!

2022-12-06 18:19 UTC, ysramakrishna commented on test/hotspot/gtest/gc/shenandoah/test_shenandoahNumberSeq.cpp
> + * Copyright (c) 2016, 2017, Oracle and/or its affiliates. All rights reserved.
Fixed; thanks for the catch!

2022-12-07 18:56 UTC, ysramakrishna commented
@rkennke & @shipilev : could you folks please review and approve? I made the changes requested by Roman.

Thanks!
-- Ramki

2022-12-08 10:03 UTC, shipilev approved these changes
So the failure is: we want the bucket to cover `[a; a+n)`, but current code makes it cover `[a; a+n]`, which means the right-most value would overflow its assignment for sub-bucket? If so, the fix looks good.

2022-12-08 14:13 UTC, rkennke approved these changes
Looks good, thank you!

2022-12-08 21:53 UTC, ysramakrishna commented
Thanks for the reviews, Roman and Alexey!

2022-12-08 21:53 UTC, ysramakrishna commented
/integrate

2022-12-08 21:54 UTC, closed without merging