7030853: JDK 7 Serializable Swing classes not compatible with JDK 6
openjdk/jdk pull request #11565
Opened 2022-12-07 16:35 UTC by prsadhuk

The serialized form of the following classes in JDK 7 builds are not compatible with prior versions of Java:
    javax.swing.text.html.parser.ParserDelegator
    javax.swing.LayoutComparator
They need to be declared as not compatible between releases in the API documentation, as is the case for some other serializable Swing classes.

Since It is widely known that serialized Swing classes are not comptible between major releases, we just didn't add the warning at that couple classes.
Added the warning..

2022-12-07 21:55 UTC, mrserb commented
I think we will need a CSR for this change.  What people think about adding this note to the documentation of the swing package?

2022-12-07 22:11 UTC, prrace commented
Is this something that should be handled like the threading policy where the javax.swing package doc spells it out for the entire API ?

2022-12-08 03:31 UTC, prsadhuk commented
OK. Added the same in javax.swing package..
Retained individual class too as the warnings are present in other classes too

2022-12-08 20:24 UTC, mrserb commented
/csr

2022-12-09 03:30 UTC, prsadhuk commented
CSR https://bugs.openjdk.org/browse/JDK-8298431
Please review

2022-12-09 03:52 UTC, prrace commented on src/java.desktop/share/classes/javax/swing/package-info.java
> + * Serialized objects of any swing class will not be compatible with
capitalise swing

2022-12-11 00:48 UTC, mrserb commented on src/java.desktop/share/classes/javax/swing/text/html/parser/ParserDelegator.java
> + *  has been added to the <code>java.beans</code> package
Looks like it has an unnecessary space after `*`

2022-12-16 12:01 UTC, aivanov-jdk requested changes

2022-12-16 12:01 UTC, aivanov-jdk commented on src/java.desktop/share/classes/javax/swing/text/html/parser/ParserDelegator.java
> + * <strong>Warning:</strong>
Missing `<p>`.

2023-01-03 20:42 UTC, aivanov-jdk approved these changes

2023-01-03 20:44 UTC, aivanov-jdk commented
Does this change require updating the CSR?

2023-01-04 03:26 UTC, closed without merging