8298281
openjdk/jdk pull request #11562
Opened 2022-12-07 15:20 UTC by albertnetymk

Simple change of removing some redundant code in oop-iteration.

Test: hotspot_gc

2022-12-07 17:00 UTC, stefank requested changes

2022-12-07 17:00 UTC, stefank commented on src/hotspot/share/gc/serial/markSweep.hpp
> +  MarkAndPushClosure(int claim) : ClaimMetadataVisitingOopIterateClosure(claim) {}
We always pass in the same value for `claim`. An alternative would be to remove this parameter and pass it to ClaimMetadataVisitingOopIterateClosure here. But maybe you liked having all the claim values together in one location in markSweep.cpp?

2022-12-08 11:29 UTC, stefank approved these changes
Thanks!

2022-12-09 08:03 UTC, kstefanj approved these changes
Looks good.

2022-12-09 13:24 UTC, albertnetymk commented
Thanks for the review.

/integrate

2022-12-09 13:26 UTC, closed without merging