JDK-8299470: sun/jvm/hotspot/SALauncher.java handling of negative rmiport args
openjdk/jdk pull request #11811
Opened 2023-01-02 14:31 UTC by MBaesken

The test serviceability/sa/sadebugd/SADebugDTest.java can pass under some circumstances a negative rmiport (--rmiport -1) to SALauncher.java.
This leads to a somewhat misleading message 
`[debugd] Argument is expected for 'rmiport' `
(we set an argument [-1] but probably this is not what is really expected) and additionally the real exception is not shown.
Probably also a warning in case of negative rmiport values should be printed because they seem to lead to errors.

2023-01-04 12:06 UTC, MBaesken commented
I adjusted the exception message a bit to show what is wrong (-1 as an argument is not expected/supported).
Removed one warning output because it seems we do not get there.

Any reviews ?

2023-01-04 12:42 UTC, RealCLanger requested changes
I've got one suggestion, plus, the copyright year now is 2023 😉

2023-01-04 12:42 UTC, RealCLanger commented on src/jdk.hotspot.agent/share/classes/sun/jvm/hotspot/SALauncher.java
> +            System.err.println("SA agent option related exception occured");
Maybe you could do here:
`System.err.println("SA agent option exception occured: " + e.getMessage);`
and remove the `System.err.println(e.getMessage());` in line 505.

2023-01-04 13:04 UTC, RealCLanger approved these changes

2023-01-04 14:19 UTC, kevinjwalls commented
The changes here to log a better error are I think good (maybe adding the stacktrace printing is not needed now the error is more understandable!), but aborting the launch attempt in the caller, if it gets -1 when trying to find a free port, should be even clearer?

In
test/hotspot/jtreg/serviceability/sa/sadebugd/SADebugDTest.java

the method testWithPid() finds an rmiPort:

  final int rmiPort = useRmiPort ? Utils.findUnreservedFreePort(REGISTRY_DEFAULT_PORT, registryPort) : -1;

...but can proceed to launch even if it gets that -1 value?   That looks like a mistake.

In the "if (useRmiPort) {" block, we should be failing the test if rmiPort is -1, saying something like
"cannot find an rmiPort, findUnreservedFreePort returns -1"

A similar abort if setting registryPort gets -1 might also be good?

2023-01-04 14:24 UTC, MBaesken commented
> In the "if (useRmiPort) {" block, we should be failing the test if rmiPort is -1, saying something like "cannot find an rmiPort, findUnreservedFreePort returns -1"
> 
> A similar abort if setting registryPort gets -1 might also be good?

Hi Kevin,  I think you are correct, adjusting the  test test/hotspot/jtreg/serviceability/sa/sadebugd/SADebugDTest.java  in those two cases (rmiPort / registryPort  -1)  probably makes sense.  Should we do it in another JBS issue or here ?
Additionally , should we fail the test in these cases , or pass with some warning - message ?

2023-01-04 14:39 UTC, kevinjwalls commented
SADebugDTest is only one test, so seems OK to have it fail as soon as we realise we need a port, and it has a value of -1.

I would do it in this change as they are so connected, but really whichever works best for you.  (I don't see other uses of findUnreservedFreePort() in the same test hierarchy, so this task should not keep on growing... 8-) )

2023-01-04 15:14 UTC, kevinjwalls commented
Looks good!

Rereading the change, occured should be "occurred" (we do have a lot of "occured" in the JDK, but many more "occurred")
On the line after that, I don't think we should introduce the stacktrace.  The user is getting a more readable error message already...
In SAGetopt.java you single-quote the 'opt' value, but could we do the same to the  _argv[_optind] value.

Then can you could make it "a registryPort" rather than "an", and I think I'm done with comments.

Thanks!

2023-01-04 23:39 UTC, sspitsyn approved these changes
Looks good.
Thanks,
Serguei

2023-01-05 07:50 UTC, kevinjwalls commented
Thanks for updating. 
I do think we should remove the e.printStackTrace() that was added in src/jdk.hotspot.agent/share/classes/sun/jvm/hotspot/SALauncher.java
as this is a message for the user.
In the test, those new exceptions will produce a stacktrace for when we look at the failing test.

2023-01-05 07:50 UTC, kevinjwalls approved these changes

2023-01-05 07:57 UTC, MBaesken commented
/integrate

2023-01-05 08:00 UTC, closed without merging

2023-01-05 21:44 UTC, dholmes-ora commented
This change has introduced a test failure in our tier 5 CI testing:

https://bugs.openjdk.org/browse/JDK-8299700

2023-01-05 21:45 UTC, dholmes-ora commented
I missed an issue had already been filed for the failure.