JDK-8299672: Enhance HeapDump JFR event
openjdk/jdk pull request #11864
Opened 2023-01-05 14:54 UTC by MBaesken

Enhance the JFR Event HeapDump  with the additional interesting fields, compression and overwrite.
Add some UL logging in case the heap dump writing failed .

2023-01-09 10:02 UTC, schmelter-sap approved these changes
Looks good.

2023-01-09 13:37 UTC, egahlin commented
What's the rationale for adding compression level and overwrite?

2023-01-10 08:19 UTC, MBaesken commented
The support for gzipped heap dumps was added recently with "8237354: Add option to jcmd to write a gzipped heap dump" but not reflected in JFR so I wanted to add it here too to get a full picture of the heap dump creation.
The overwrite field was just added  for completion, no specific reason.

2023-01-11 11:17 UTC, MBaesken commented on test/jdk/jdk/jfr/event/diagnostics/TestHeapDump.java
> +            Events.assertField(e, "compression").equal(-1);
Hi Ralf, thanks for the review. 
I adjusted the test as suggested.

2023-01-11 11:24 UTC, RealCLanger requested changes
Some spelling issues, for consistency.

2023-01-11 11:24 UTC, RealCLanger commented on src/hotspot/share/jfr/metadata/metadata.xml
> +  <Event name="HeapDump" category="Java Virtual Machine, Diagnostics" label="Heap Dump" description="Information about a successfully written Java Heap dump"
spelling: "Java heap dump" in description (small heap)

2023-01-11 11:24 UTC, RealCLanger commented on src/hotspot/share/jfr/metadata/metadata.xml
> +    <Field type="string" name="destination" label="Destination path of the dump" />
Spelling: In the label we'd write Path and Dump in capitals

2023-01-11 11:24 UTC, RealCLanger commented on src/hotspot/share/jfr/metadata/metadata.xml
> +    <Field type="boolean" name="onOutOfMemoryError" label="Heap dump on Out of Memory Error" />
Also here: "Dump" in capitals in the label

2023-01-11 11:24 UTC, RealCLanger commented on src/hotspot/share/jfr/metadata/metadata.xml
> +    <Field type="int" name="compression" label="Compression Level" description="Compression level of the Dump, if larger than 0 we use gzip compressoion with this level" />
Here, in description, use small letter for "dump"

2023-01-11 11:44 UTC, MBaesken commented
Hi Christoph, I did some adjustments (also compressoion  -> compression).

2023-01-11 11:56 UTC, RealCLanger approved these changes
Looks good to me now.

PS: The metadata.xml also has a copyright year to update which you should do before integrating.

2023-01-11 12:48 UTC, egahlin commented
> The support for gzipped heap dumps was added recently with "8237354: Add option to jcmd to write a gzipped heap dump" but not reflected in JFR so I wanted to add it here too to get a full picture of the heap dump creation.
> The overwrite field was just added for completion, no specific reason.

Not sure what the user is going to do with the information, but OK.

2023-01-12 08:01 UTC, MBaesken commented
/integrate

2023-01-12 08:05 UTC, closed without merging