8256267: Relax compiler/floatingpoint/NaNTest.java for x86_32 and lower -XX:+UseSSE
openjdk/jdk pull request #1187
Opened 2020-11-12 13:06 UTC by shipilev

Reproduces like this:

```
$ CONF=linux-x86-server-fastdebug make images run-test TEST=compiler/floatingpoint/NaNTest.java TEST_VM_OPTS="-XX:UseSSE=1"

STDOUT:
### NanTest started
Written and read back float values match
0x7F800001 0x7F800001
STDERR:
java.lang.RuntimeException: Original and read back double values mismatch
0xFFF0000000000001 0xFFF8000000000001

at compiler.floatingpoint.NaNTest.testDouble(NaNTest.java:56)
at compiler.floatingpoint.NaNTest.main(NaNTest.java:69)
```

After reading through [JDK-8076373](https://bugs.openjdk.java.net/browse/JDK-8076373), I think the test cannot be expected to pass without SSE >= 2 for doubles, and SSE >= 1 for floats on x86_32. This change adds the platform and UseSSE sensing to test.

Additional testing:
 - [x] Affected test on Linux x86_32 with `-XX:UseSSE={0,1,2}`
 - [x] Affected test on Linux x86_64 with `-XX:UseSSE={0,1,2}`
 - [x] Affected test on Linux AArch64

2020-11-16 08:17 UTC, shipilev commented
Anyone? :)

2020-11-17 00:42 UTC, vnkozlov requested changes
Why to run test code if you know the result will not match? Why not just skip testing?
I thought about using `@requires vm.cpu.features` checks but your check in main() is simpler and more clear.

2020-11-17 07:09 UTC, shipilev commented
> Why to run test code if you know the result will not match? Why not just skip testing?
> I thought about using `@requires vm.cpu.features` checks but your check in main() is simpler and more clear.

Yes, I thought about just skipping the test initially. But then I realized I would like to know how exactly the results do not match for the excluded cases.

2020-11-18 17:25 UTC, shipilev commented
Do you still want me to make changes, @vnkozlov? I can throw `SkippedException` instead.

2020-11-23 07:39 UTC, shipilev commented
Which way you'd like me to move with this, @vnkozlov? :) I am fine with either way, leaning towards what we already have.

2020-11-23 16:01 UTC, vnkozlov commented
What I meant is to run tests only if SSE is used:
```
if (expectStableFloats) {
    testFloat();
}
if (expectStableDoubles) {
    testDouble();
}
```

2020-11-24 09:32 UTC, shipilev commented
> What I meant is to run tests only if SSE is used:
> 
> ```
> if (expectStableFloats) {
>     testFloat();
> }
> if (expectStableDoubles) {
>     testDouble();
> }
> ```

Sure, if you want. See the update. x86_32 is currently broken by Foreign Linker integration, so I have not rebased to current master. New commit still fixes x86_32 failure on this test.

2020-11-24 17:14 UTC, vnkozlov approved these changes
Good.

2020-11-24 17:33 UTC, iignatev commented
if  `expectStableFloats` is false, we basically don't do any testing, so I'd prefer us to throw `SkippedException` to have more realistic test results. and for a case `expectStableFloats` being false, it would be nice to at least print a message saying we didn't do that part.

2020-11-24 18:02 UTC, shipilev commented
> if `expectStableFloats` is false, we basically don't do any testing, so I'd prefer us to throw `SkippedException` to have more realistic test results. and for a case `expectStableFloats` being false, it would be nice to at least print a message saying we didn't do that part.

Well, my previous version used to print out the results even when skipped. `expectStableDoubles` implies `expectStableFloats` due to implementation specifics, so we better not rely on that. See new patch: prints messages when skipping either test, and throws `SkippedException` if no test cases were run.

2020-11-24 18:11 UTC, iignatev approved these changes

2020-11-24 18:27 UTC, vnkozlov approved these changes

2020-11-25 20:00 UTC, shipilev commented
/integrate

2020-11-25 20:01 UTC, closed without merging