JDK-8299915: Remove ArrayAllocatorMallocLimit
openjdk/jdk pull request #11931
Opened 2023-01-10 20:55 UTC by jcking

Remove abstraction that is a holdover from Solaris. Direct usages of `MmapArrayAllocator` have been switched to normal `malloc`. The justification is that none of the code paths are called from signal handlers, so using `mmap` directly does not make sense and is potentially slower than going through `malloc` which can potentially re-use memory without making any system calls. The remaining usages of `ArrayAllocator` and `MallocArrayAllocator` are equivalent.

2023-01-11 10:05 UTC, stefank commented
I'm happy to see this flag getting removed. I'm less happy about seeing usages of the array allocators being replaced by macros. I'd rather see an effort towards getting rid of these macros. Could we limit this patch to only remove the ArrayAllocatorMallocLimit flag and ArrayAllocator class, and defer the discussion around what API to use for array allocations?

2023-01-11 14:27 UTC, jcking commented
> I'm happy to see this flag getting removed. I'm less happy about seeing usages of the array allocators being replaced by macros. I'd rather see an effort towards getting rid of these macros. Could we limit this patch to only remove the ArrayAllocatorMallocLimit flag and ArrayAllocator class, and defer the discussion around what API to use for array allocations?

`ArrayAllocator` with `ArrayAllocatorMallocLimit` removed is effectively `MallocArrayAllocator`. Are you suggesting leaving `MallocArrayAllocator` and `MmapArrayAllocator` thus update references to `ArrayAllocator` to be `MallocArrayAllocator`?

As far as APIs, the majority of the codebase uses the macros. IMO consistency would be better and having two ways of doing things doesn't help. But if you feel strongly about it, we can punt and just surgically remove the bare minimum, assuming you clarify your expectation (see above).

2023-01-11 14:49 UTC, tstuefe commented
Curious, I always thought we do ArrayAllocator - using mmap for larger allocations - to prevent memory retention for libc variants whose allocators are "grabby", i.e. which don't promptly return memory to the OS on free(). E.g. because they only use sbrk (Solaris, AIX), or are just cautious about returning memory (glibc).

Glibc's retention problem is only relevant for fine-grained allocations, so for glibc this is probably fine. This leaves at least AIX as a potential problem. @backwaterred, does the AIX libc still exclusively use sbrk ? Does free'd memory still stick to the process?

(While writing this, I remember that we at SAP even rewrote Arena allocation to use mmap for AIX, because large compile arenas caused lasting RSS increase, so it has definitely been a problem in the past)

2023-01-11 17:58 UTC, jcking commented
> > ArrayAllocator with ArrayAllocatorMallocLimit removed is effectively MallocArrayAllocator. Are you suggesting leaving MallocArrayAllocator and MmapArrayAllocator thus update references to ArrayAllocator to be MallocArrayAllocator?
> 
> Yes, that was what I wanted.
> 
> > As far as APIs, the majority of the codebase uses the macros. IMO consistency would be better and having two ways of doing things doesn't help. But if you feel strongly about it, we can punt and just surgically remove the bare minimum, assuming you clarify your expectation (see above).
> 
> I agree about the argument about consistency, so I retract my objection. We can deal with these macros as a separate RFE (if we ever get to it).
> 
> I would like to retain the usage of mmapped memory for ZGC to minimize the risk of any surprises for us. ZGC code also tend to initialize as much as possible in the initialization list, so the extra memset that comes after initialization lists sticks out a bit. Could you create a private `ZGranuleMap::allocate_array` function that uses os::reserve_memory/commmit_memory and change the code to be:
> 
> ```
> inline ZGranuleMap<T>::ZGranuleMap(size_t max_offset) :
>     _size(max_offset >> ZGranuleSizeShift),
>     _map(allocate_array(_size)) {
> ```
> 
> Or if you like, I can provide a patch on top of your branch to do that.

The extra memset is due to `malloc` not handing out zero initialized memory, it looks like `zGranuleMap` is sensitive to that.

Done. Restored mmap as suggested for zGranuleMap.

2023-01-11 18:10 UTC, jcking commented
> Curious, I always thought we do ArrayAllocator - using mmap for larger allocations - to prevent memory retention for libc variants whose allocators are "grabby", i.e. which don't promptly return memory to the OS on free(). E.g. because they only use sbrk (Solaris, AIX), or are just cautious about returning memory (glibc).
> 
> Glibc's retention problem is only relevant for fine-grained allocations, so for glibc this is probably fine. This leaves at least AIX as a potential problem. @backwaterred, does the AIX libc malloc() still exclusively use the data segment ? Does free'd memory still stick to the process?
> 
> (While writing this, I remember that we at SAP even rewrote Arena allocation to use mmap for AIX, because large compile arenas caused lasting RSS increase, so it has definitely been a problem in the past)

Correct, glibc always mmap's allocations above a certain limit and always unmaps them on free. I believe most implementations do that, either immediately unmapping or using madvise. AIX still uses sbrk, based on their documentation that I could find. Though AIX does have something called [malloc disclaim](https://www.ibm.com/docs/en/aix/7.2?topic=subsystem-malloc-disclaim).

2023-01-11 18:52 UTC, coleenp commented
To follow up on @tstuefe comment - and the one that I tried to say in the bug was that we added this MmapArrayAllocate feature for some G1 marking bits that used so much memory that hit the Solaris _sbrk issue.  Maybe @stefank and @tschatzl remember this issue.  Maybe it's ok for AIX, then removing this code is a good change.  Maybe the G1 usages need a mmap implementation though.

2023-01-11 20:56 UTC, jcking commented
> To follow up on @tstuefe comment - and the one that I tried to say in the bug was that we added this MmapArrayAllocate feature for some G1 marking bits that used so much memory that hit the Solaris _sbrk issue. Maybe @stefank and @tschatzl remember this issue. Maybe it's ok for AIX, then removing this code is a good change. Maybe the G1 usages need a mmap implementation though.

The padding.inline.hpp usage seems to have one caller which is called once. The other mmap usage in G1 we can convert to mmap using a similar approach to zGranuleMap if that is preferred. That would then be equivalent behavior, it looks like the G1 code uses the page allocation granularity anyway so maybe keeping it mmap is the better way to go here anyway?

2023-01-12 07:32 UTC, stefank requested changes
Thanks for the ZGC update. I have a request to slightly modify the style a bit. Would you mind taking this patch:
https://github.com/stefank/jdk/tree/pr_11931

There's a FIXME about that allocation.inline.hpp file is now empty. Will you remove it in this patch? I'd prefer if you did. Alternatively, remove the FIXME from this patch and then immediately clean this up as a separate patch.

2023-01-12 16:52 UTC, tstuefe commented
> > To follow up on @tstuefe comment - and the one that I tried to say in the bug was that we added this MmapArrayAllocate feature for some G1 marking bits that used so much memory that hit the Solaris _sbrk issue. Maybe @stefank and @tschatzl remember this issue. Maybe it's ok for AIX, then removing this code is a good change. Maybe the G1 usages need a mmap implementation though.
> 
> The padding.inline.hpp usage seems to have one caller which is called once. The other mmap usage in G1 we can convert to mmap using a similar approach to zGranuleMap if that is preferred. That would then be equivalent behavior, it looks like the G1 code uses the page allocation granularity anyway so maybe keeping it mmap is the better way to go here anyway?

My uninformed opinion (I'm not the G1 code owner) is that it would be fine to use explicit mmap. I'd love the complexity reduction this patch brings.

2023-01-13 17:32 UTC, jcking commented
/contributor add @stefank

2023-01-13 17:33 UTC, jcking commented
Applied your patch @stefank

2023-01-13 17:46 UTC, jcking commented
Restored `mmap` for G1, though in the future it might make sense to switch to just using malloc.

2023-01-19 17:41 UTC, jcking commented
> There's a FIXME about that allocation.inline.hpp file is now empty. Will you remove it in this patch? I'd prefer if you did. Alternatively, remove the FIXME from this patch and then immediately clean this up as a separate patch.

Yeah, separate patch immediately after is probably best. Trying to avoid having to mass update includes and enter merge conflict hell for this patch. After is easier.

2023-01-20 23:13 UTC, backwaterred commented
> This leaves at least AIX as a potential problem. @backwaterred, does the AIX libc malloc() still exclusively use the data segment? Does free'd memory still stick to the process?

I agree with @coleenp that AIX seems to still use the data segment and sbrk for dynamic memory allocation. I am not sure about memory sticking to the process.

With these changes I see several of the gtests failing on AIX.

```
[==========] 58 tests from 6 test cases ran. (3718 ms total)
[  PASSED  ] 53 tests.
[  FAILED  ] 5 tests, listed below:
[  FAILED  ] os.safefetchN_negative_vm
[  FAILED  ] os.safefetch32_negative_vm
[  FAILED  ] os.safefetchN_negative_current_null_vm
[  FAILED  ] os.safefetch32_negative_current_null_vm
[  FAILED  ] os.safefetch_negative_at_safepoint_vm
```

I can experiment with the disclaim option as well.

2023-04-15 01:45 UTC, closed without merging

2023-05-22 16:45 UTC, iklam commented
@tstuefe @backwaterred I'd like to see this RFE revived. Do we know if anyone is using the `ArrayAllocatorMallocLimit` flag in any production environment today?

It seems unlikely to me, as you'd need to explicitly specify `-XX:+UnlockExperimentalVMOptions` in the command-line.

And, if this option had been useful (for the AIX port, for example), it would have been changed to a non-experimental (with proper `_pd` support) option over the past 10 years.

2023-05-22 17:59 UTC, tstuefe commented on src/hotspot/share/memory/padded.inline.hpp
> +
Old code, when doing the malloc path, did not initialize. Why here?

2023-05-22 18:01 UTC, tstuefe commented
> @tstuefe @backwaterred I'd like to see this RFE revived. Do we know if anyone is using the `ArrayAllocatorMallocLimit` flag in any production environment today?
> 
> It seems unlikely to me, as you'd need to explicitly specify `-XX:+UnlockExperimentalVMOptions` in the command-line.
> 
> And, if this option had been useful (for the AIX port, for example), it would have been changed to a non-experimental (with proper `_pd` support) option over the past 10 years.

@iklam I'm fine with removing the ArrayAllocator.

2023-05-22 19:00 UTC, stefank reviewed
Could we create a simpler version of this PR? One that only removes ArrayAllocator and ArrayAllocatorMallocLimit, but keeps MallocArrayAllocator and MmapArrayAllocator? That way we can figure out later, in a separate RFE, if we want to remove MmapArrayAllocator.