8299960: Speed up test/hotspot/jtreg/compiler/c2/irTests/TestVectorizeURShiftSubword.java
openjdk/jdk pull request #11942
Opened 2023-01-11 11:55 UTC by eme64

This is one of the most time-consuming compiler tests.
On my machine, I was able to reduce it from `20 sec` to `3 sec`.

This is an irTest, so we basically only want to see if certain IR-nodes are present.
By default we do lots of warmup iterations, this is not required in these examples, so I set `@Warmup(1)`.

2023-01-11 12:10 UTC, TobiHartmann requested changes
Please use`testFrameworkobject.setDefaultWarmup`, see [README.md](https://github.com/openjdk/jdk/blob/master/test/hotspot/jtreg/compiler/lib/ir_framework/README.md).

2023-01-11 12:38 UTC, TobiHartmann approved these changes
Looks good!

2023-01-11 13:16 UTC, chhagedorn approved these changes
Looks good!

2023-01-12 04:01 UTC, fg1417 reviewed
Nice work! Please also help update Arm Limited copyright notice to 2023. Thanks.

2023-01-12 04:04 UTC, fg1417 approved these changes

2023-01-12 08:07 UTC, eme64 commented
@fg1417 Thanks for the review!
I am not sure that I am allowed to alter the Arm copyright. I'm looking into that.

2023-01-12 08:30 UTC, fg1417 approved these changes
LGTM

2023-01-12 22:46 UTC, vnkozlov commented
> I am not sure that I am allowed to alter the Arm copyright. I'm looking into that.

You did right by adding new Oracle's copyright line.

2023-01-16 09:16 UTC, eme64 commented
Thanks @vnkozlov for the clarification.
Thanks @chhagedorn for the suggestion for the solution.
Thanks @chhagedorn @TobiHartmann @fg1417 for the reviews!

/integrate

2023-01-16 09:17 UTC, closed without merging