JDK-8300042: Improve CPU related JFR events descriptions
openjdk/jdk pull request #11969
Opened 2023-01-12 15:42 UTC by MBaesken

There are a number of JFR events dealing with CPU related information. Those sometimes miss descriptions or have very limited descriptions, this can be improved.

2023-01-17 09:29 UTC, RealCLanger requested changes

2023-01-17 09:29 UTC, RealCLanger commented on src/hotspot/share/jfr/metadata/metadata.xml
> +         description="OS CPU Load values of the process, contains information about the recent cpu usage of the JVM process"
CPU should be written in capitals here, too.

2023-01-17 11:11 UTC, thegreystone commented
The inoffical rule has been to not add descriptions that do not add to the understanding of the event type. Like not adding comments when the code is self explanatory. I would argue that, at least, everything before the comma can be removed.

2023-01-17 12:45 UTC, MBaesken commented
Hi Christoph and Marcus, I shortened and adjusted the CPULoad description,

2023-01-18 22:07 UTC, RealCLanger requested changes
I've got 3 further comments to shorten the description texts.

2023-01-18 22:07 UTC, RealCLanger commented on src/hotspot/share/jfr/metadata/metadata.xml
> +         description="Various characteristics and descriptions of the processor(s) the JVM is running on"
I would leave out the word "Various" here

2023-01-18 22:07 UTC, RealCLanger commented on src/hotspot/share/jfr/metadata/metadata.xml
> +         description="Various information about the CPU time stamp mechanism / (RD)TSC"
Same here, drop the "Various"

2023-01-18 22:07 UTC, RealCLanger commented on src/hotspot/share/jfr/metadata/metadata.xml
> +         description="Contains information about the recent CPU usage of the JVM process"
Here only say "Information about...", leave out the "Contains"

2023-01-19 09:03 UTC, MBaesken commented
Hi Christoph, I adjusted the descriptions.

2023-01-19 09:11 UTC, RealCLanger approved these changes
Looks good to me now

2023-01-19 10:11 UTC, RealLucy approved these changes
Looks good to me.

2023-01-19 11:59 UTC, MBaesken commented
Hi Lutz and Christoph, thanks for the reviews !

/integrate

2023-01-19 12:02 UTC, closed without merging