Replace NULL with nullptr in share/ci/
openjdk/jdk pull request #12029
Opened 2023-01-17 11:07 UTC by jdksjolen

Do the conversion in the share/ci/ sub-directory and all of its files.

2023-01-19 20:11 UTC, jdksjolen reviewed
Manual fixes to be done.

2023-01-19 20:11 UTC, jdksjolen commented on src/hotspot/share/ci/ciEnv.cpp
> +// Returns nullptr if no location is found.
fix

2023-01-19 20:11 UTC, jdksjolen commented on src/hotspot/share/ci/ciEnv.hpp
> +  // If require_local, result must be defined in that class loader, or nullptr.
fix

2023-01-19 20:11 UTC, jdksjolen commented on src/hotspot/share/ci/ciEnv.hpp
> +  // or return nullptr if not.
fix

2023-01-19 20:11 UTC, jdksjolen commented on src/hotspot/share/ci/ciField.cpp
> +// To avoid vicious circularities, we initialize ciField::_type to nullptr
fix

2023-01-19 20:11 UTC, jdksjolen commented on src/hotspot/share/ci/ciInstance.cpp
> +  // Return nullptr if it is not java.lang.Class.
fix

2023-01-19 20:11 UTC, jdksjolen commented on src/hotspot/share/ci/ciInstanceKlass.hpp
> +  //   nullptr: no implementor.
fix

2023-01-19 20:11 UTC, jdksjolen commented on src/hotspot/share/ci/ciMethod.cpp
> +// for the call.  Return nullptr if the call is not monomorphic in
fix

2023-01-19 20:11 UTC, jdksjolen commented on src/hotspot/share/ci/ciMethod.cpp
> +    // to return nullptr, even if the CHA encountered irrelevant
fix

2023-01-19 20:11 UTC, jdksjolen commented on src/hotspot/share/ci/ciMethod.cpp
> +    // Return nullptr only if there was a problem with lookup (uninitialized class, etc.)
fix

2023-01-19 20:11 UTC, jdksjolen commented on src/hotspot/share/ci/ciMethod.hpp
> +  // for the call.  Return nullptr if the call is not monomorphic in
fix

2023-01-19 20:11 UTC, jdksjolen commented on src/hotspot/share/ci/ciMethod.hpp
> +  // Return nullptr if the call has no target or is abstract.
fix

2023-01-19 20:11 UTC, jdksjolen commented on src/hotspot/share/ci/ciMethodData.hpp
> +  // Area dedicated to parameters. nullptr if no parameter profiling for this method.
fix

2023-01-19 20:11 UTC, jdksjolen commented on src/hotspot/share/ci/ciMethodData.hpp
> +  // Get the data at an arbitrary bci, or nullptr if there is none. If m
fix

2023-01-19 20:11 UTC, jdksjolen commented on src/hotspot/share/ci/ciNullObject.hpp
> +#ifndef SHARE_CI_CInullptrOBJECT_HPP
fix

2023-01-19 20:11 UTC, jdksjolen commented on src/hotspot/share/ci/ciObjArrayKlass.cpp
> +    assert(dimension() > 1, "_element_klass should not be nullptr");
fix

2023-01-19 20:11 UTC, jdksjolen commented on src/hotspot/share/ci/ciObject.cpp
> +// nullptr variant.  Used only by ciNullObject.
fix

2023-01-19 20:11 UTC, jdksjolen commented on src/hotspot/share/ci/ciObject.cpp
> +      // When both _klass and _handle are nullptr, we are dealing
fix

2023-01-19 20:11 UTC, jdksjolen commented on src/hotspot/share/ci/ciObject.hpp
> +  // handle may, in a small set of cases, correctly be nullptr.
fix

2023-01-19 20:11 UTC, jdksjolen commented on src/hotspot/share/ci/ciTypeFlow.cpp
> +    // VM's interpreter will not load 'klass' if object is nullptr.
fix

2023-01-19 20:11 UTC, jdksjolen commented on src/hotspot/share/ci/ciTypeFlow.hpp
> +      T_nullptr    = T_BYTE       // for now.
fix

2023-01-19 20:11 UTC, jdksjolen commented on src/hotspot/share/ci/ciTypeFlow.hpp
> +    static ciType* null_type()   { return ciType::make((BasicType)T_nullptr); }
fix

2023-01-19 20:11 UTC, jdksjolen commented on src/hotspot/share/ci/ciTypeFlow.hpp
> +    // null is popped from the stack, we return nullptr.  Caller beware.
fix

2023-01-19 20:11 UTC, jdksjolen commented on src/hotspot/share/ci/ciTypeFlow.hpp
> +  // with jsrs, or nullptr if there is none.
fix

2023-01-19 20:23 UTC, jdksjolen commented
All of the issues I found are now fixed and this is open for review.

2023-01-19 21:03 UTC, vnkozlov commented on src/hotspot/share/ci/ciInstance.cpp
> +    return nullptr;
I am confused. Did I miss some previous reviews which asked to keep `null` in comments?
These lines are confusing: comment says `null` but method returns `nullptr`. Why not use `nullptr` in comment?

2023-01-19 21:03 UTC, vnkozlov commented on src/hotspot/share/ci/ciInstance.hpp
> +  // Otherwise, return nullptr.
And here we have `nullptr` in comment.

2023-01-19 21:08 UTC, vnkozlov commented on src/hotspot/share/ci/ciMethodData.hpp
> +  ciProfileData* bci_to_data(int bci, ciMethod* m = nullptr);
Again mixture of `null` and `nullptr` in comment. Even so the comment for `ciMethodData::bci_to_data()` in .cpp file says `nullptr`

2023-01-19 21:09 UTC, vnkozlov commented on src/hotspot/share/ci/ciNullObject.hpp
> + * Copyright (c) 1999, 2023, Oracle and/or its affiliates. All rights reserved.
No change in file

2023-01-20 10:25 UTC, jdksjolen commented
Hi @vnkozlov.

Regarding the confusion regarding `null` and `nullptr` in comments :). Yes, the idea is that we use `null` in comments as it reads better. In *some* situations I've chosen to keep `nullptr` in comments, this is specifically when there are code expressions (such as `nullptr == x`) in the comments. Sometimes I simply miss fixing them, because my script cannot deal with comments correctly and I need to alter them manually. This fact makes it a bit confusing to review, I agree.

This was discussed in a previous review, as you suspected.

Thank you for your comments!

2023-01-20 19:37 UTC, vnkozlov commented
> Regarding the confusion regarding `null` and `nullptr` in comments :). Yes, the idea is that we use `null` in comments as it reads better. In _some_ situations I've chosen to keep `nullptr` in comments, this is specifically when there are code

As owner of the code I prefer to match comments and code.

> This was discussed in a previous review, as you suspected.

Please, point me to that discussion.

2023-01-23 18:28 UTC, vnkozlov requested changes
Okay. After second look through I agree to use `null` in comments as it indeed sounds better.
I found several cases with `nullptr` in comments you missed. We should be consistent.
And one file which has copyright year update but no changes.

2023-01-23 18:28 UTC, vnkozlov commented on src/hotspot/share/ci/ciInstance.hpp
> +  // Otherwise, return nullptr.
Use `null` here.

2023-01-23 18:28 UTC, vnkozlov commented on src/hotspot/share/ci/ciMethod.cpp
> +// Return nullptr if the call has no target or the target is abstract.
Use `null`

2023-01-23 18:28 UTC, vnkozlov commented on src/hotspot/share/ci/ciMethod.cpp
> +// nullptr otherwise.
Use `null`

2023-01-23 18:28 UTC, vnkozlov commented on src/hotspot/share/ci/ciMethodData.hpp
> +  // is not nullptr look for a SpeculativeTrapData if any first.
Use `null`

2023-01-23 18:28 UTC, vnkozlov commented on src/hotspot/share/ci/ciNullObject.hpp
> + * Copyright (c) 1999, 2023, Oracle and/or its affiliates. All rights reserved.
Undo this. No changes in file.

2023-01-24 22:30 UTC, vnkozlov approved these changes
Looks good.

2023-01-25 14:44 UTC, jdksjolen commented
Passes tier1.

2023-01-27 14:03 UTC, coleenp approved these changes

2023-01-27 15:41 UTC, jdksjolen commented
Still passes tier1!

/integrate

2023-01-27 15:43 UTC, closed without merging