JDK-8300531: Update MSVC optimization flags to match GCC/Clang
openjdk/jdk pull request #12073
Opened 2023-01-18 14:32 UTC by jcking

Update MSVC CFlags to be more consistent with other compilers. Also disables RTTI in a simliar manner to GCC/Clang for the JVM.

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8300531](https://bugs.openjdk.org/browse/JDK-8300531): Update MSVC optimization flags to match GCC/Clang

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/12073/head:pull/12073` \
`$ git checkout pull/12073`

Update a local copy of the PR: \
`$ git checkout pull/12073` \
`$ git pull https://git.openjdk.org/jdk.git pull/12073/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12073`

View PR using the GUI difftool: \
`$ git pr show -t 12073`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12073.diff">https://git.openjdk.org/jdk/pull/12073.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/12073#issuecomment-1387179830)

2023-01-18 14:34 UTC, jcking commented
Not sure why `-Oy-` was used. GCC/Clang omit frame pointers by default these days, IIRC. So forcing MSVC to preserve frame pointers at the highest optimization level seems odd.

2023-01-19 19:23 UTC, erikj79 commented
Changing the global optimization flags is a pretty big and potentially intrusive change. It's quite possible that the current flags need a re-evaluation, since they were chosen a long time ago, for a much older version of Visual Studio. But, doing that evaluation is going to take some work. What is the impact on footprint and performance? How thoroughly have you tested that the increased optimization level isn't triggering something in Hotspot? We have quite a bit of history of compiler optimizations not working well with certain things that are done in the JVM.

My expectation for a change like this is that it would come with a pretty extensive report on gains, losses and tradeoffs to motivate it. Then other OpenJDK participants would likely want to replicate those findings and verify with their own benchmarks and requirements. I don't think making the number after the O in the flags match what we use for other compilers is motivation enough to warrant a change like this. Different compilers are sure to have their optimization levels mean different things.

2023-01-19 19:43 UTC, erikj79 commented
> I don't think making the number after the O in the flags match what we use for other compilers is motivation enough to warrant a change like this. Different compilers are sure to have their optimization levels mean different things.

I take this last part back. I see now that you did reference the documentation in the bug, which would make a case for evaluating changing these values. My other points remain however.

2023-01-19 20:47 UTC, jcking commented
> Changing the global optimization flags is a pretty big and potentially intrusive change. It's quite possible that the current flags need a re-evaluation, since they were chosen a long time ago, for a much older version of Visual Studio. But, doing that evaluation is going to take some work. What is the impact on footprint and performance? How thoroughly have you tested that the increased optimization level isn't triggering something in Hotspot? We have quite a bit of history of compiler optimizations not working well with certain things that are done in the JVM.

Yes, I need to get my personal box back together so I can see the results on Windows. The main drawback of the changes is going to be binary size, the question is out much. I'll move this back to draft until I can see for myself. Based on compiler explorer -O2 is much more optimal than -O1 for certain things.

2023-02-14 18:59 UTC, jcking commented
The main difference between `/O1` and `/O2`, besides speed vs. size, is that the latter adds `/Oi` which tells the compiler to try and inline intrinsics rather than making function calls. This can lead to improved speed. GCC/Clang do the same thing by treating certain functions like memcpy/memset/memmove and special.

Additionally I added `/Oy-` which preserves frame pointers. This makes MSVC match the GCC/Clang configuration with pass `-fno-omit-frame-pointer`.

Additionally we have disabled RTTI now by passing `/GR-`, this again matches GCC/Clang. The resulting size of the JVM binary drops by ~1MB.

2023-02-15 21:17 UTC, jcking commented
Looks like serviceability might rely on RTTI on Windows. Removed the addition of `/GR-`, which is unfortunate but necessary if serviceability relies on it.

2023-02-16 02:03 UTC, dholmes-ora commented
> Looks like serviceability might rely on RTTI on Windows.

Can you point to the code please? We should not be using RTTI.

2023-02-16 03:01 UTC, jcking commented
> > Looks like serviceability might rely on RTTI on Windows.
> 
> Can you point to the code please? We should not be using RTTI.

Removing /GR- makes the tests pass. I think somewhere we are indirectly relying on RTTI for Windows. Maybe related to DbgEng or DbgHelp on Windows. I'll have to look more to find it. It's only some of the tests.

2023-02-16 04:00 UTC, dholmes-ora commented
I grepp'd the tests and couldn't find anything that appears to be RTTI usage: no dynamic_cast, typeid or type_info. That said use of RTTI in tests is a different matter - tests can use whatever language facilities they need.

2023-02-16 04:20 UTC, jcking commented
Disabling RTTI seems to prevent serviceability from locating threads on Windows. As the test that failed isn't printing threads at all. My current hypothesis is MSVC isn't exporting some symbols now that RTTI is disabled, and either DbgHelp or DbgEng needs it.  I'll see if I can track it down.

2023-02-16 06:33 UTC, iklam requested changes
As a general comment, the bug title should be to the point. "Look suspicious" contains no information. It looks like you are changing the optimization level, so the bug title should reflect that.

2023-02-17 11:55 UTC, magicus commented
> As a general comment, the bug title should be to the point. "Look suspicious" contains no information. It looks like you are changing the optimization level, so the bug title should reflect that.

I agree. But let me expand the point a bit: It is fully okay for an *issue in JBS* to have a title like "flags look sus". Bug reports can be vague and be as much about further research. But once the research is done, the bug should either be closed (if the research ended in "it's ok, no change needed"), or it should be retitled to describe the actual changes needed.

So the requirement to match PR and bug title is a good one, but we should be liberal with updating bug titles in JBS, when more knowledge about the problem has appeared.

And, as another general rule, if some code is still in the "research" phase, but you still want to open a PR, it should be opened as a draft. That way you clearly signal that you do not intend to integrate the changes as-is, but are looking for feedback on an incomplete fix.

So, an alternative to renaming the PR/JBS issue, is to move this PR to draft. And perhaps make it even clearer by renaming it "WIP: ....". That makes the bug impossible to integrate, and will give folks peace of mind of knowing that this won't suddenly be integrated without further discussion.

2023-02-18 18:16 UTC, jcking commented
Okay I updated this change title to be more specific, sorry about that. Just optimization-related flags. I punted on disabling RTTI to [JDK-8302817](https://bugs.openjdk.org/browse/JDK-8302817) as I cannot pinpoint the failure, it seems related to DbgHelp or DbgEng.

2023-02-18 18:23 UTC, jcking commented
This change ensures MSVC is similar to GCC/Clang in terms of optimization flags, at least in spirit. It also applies the equivalent of `-fno-omit-frame-pointer` to MSVC (`-Oy-`). Binary size is not significantly affected. The main difference is MSVC will prefer speed over size when generating code, and will try to prefer intrinsic versions of builtins rather than emitting function calls.

2023-02-18 21:36 UTC, magicus commented
The new title is showing much clearer what you want to achieve, thanks for that. But I'd like to re-iterate what Erik said early on:

> Changing the global optimization flags is a pretty big and potentially intrusive change. [...] I don't think making the number after the O in the flags match what we use for other compilers is motivation enough to warrant a change like this. 

That is, just making the flags "match" is not motivation enough to accept such a change. This needs to be thoroughly tested, and then communicated and discussed with the wider JDK community, including but not limited to, engineers specifically involved in performance testing, evaluation and improvements.

2023-05-15 04:22 UTC, closed without merging