JDK-8300651: Replace NULL with nullptr in share/runtime/
openjdk/jdk pull request #12094
Opened 2023-01-19 12:27 UTC by jdksjolen

Do the conversion in the share/runtime/ sub-directory and all of its files.

2023-01-19 18:08 UTC, jdksjolen commented
Seems like uploading the GHA results are failing.

2023-01-20 11:33 UTC, robehn approved these changes
Thank you!

2023-01-23 01:22 UTC, dholmes-ora requested changes
Looks good but a few cases where nullptr should be null in comments for consistency with surrounding changes if nothing else.

Thanks.

2023-01-23 01:22 UTC, dholmes-ora commented on src/hotspot/share/runtime/threadSMR.hpp
> +    assert(list != nullptr, "ThreadsList must not be nullptr.");
null

2023-01-23 01:22 UTC, dholmes-ora commented on src/hotspot/share/runtime/vmStructs.hpp
> +  // the fact that it has a nullptr typeName
null for consistency

2023-01-23 01:22 UTC, dholmes-ora commented on src/hotspot/share/runtime/mutexLocker.cpp
> +  assert(lock != nullptr, "Need non-nullptr lock");
null for consistency

2023-01-23 08:42 UTC, robehn commented
> Looks good but a few cases where nullptr should be null in comments for consistency with surrounding changes if nothing else.

Yes, good. The terminology used by posix is: "null pointer", so using lower case null I think is good.

2023-01-25 01:49 UTC, dholmes-ora approved these changes
Looks good! Thanks.

2023-01-25 10:28 UTC, jdksjolen commented
Passes tier1.

/integrate

2023-01-25 10:30 UTC, closed without merging