8295944: Move the Http2TestServer and related classes into a package of its own
openjdk/jdk pull request #12160
Opened 2023-01-24 06:05 UTC by jaikiran

Can I please get a review of this change which addresses https://bugs.openjdk.org/browse/JDK-8295944?

As noted in the issue, the HttpClient testing helper infrastructure code resides in a default packages within the test hierarchy. The commit in this PR moves those classes into a specific package. The tests have been updated to refer to them correctly with proper package name references.
Additionally as noted in the issue, the `@modules` declaration used in the httpclient tests, were all the same and were repeated in all these tests. The commit in this  PR moves those module references into the `TEST.properties` to centralize such reference. Any test which needs additional modules can then use specific `@modules` declaration in the test definition.

No functional changes have been done in this PR.

tier1, tier2 and tier3 testing passed after these changes.

2023-01-24 12:36 UTC, dfuch requested changes
Very nice refactoring overall. Thanks for taking that on! There are a few places where some lines should have been removed but were not. I made some suggestions. Also there are 9 classes that have kept their custom `@modules` clause because they want to access 
```
 *          java.base/sun.net.www
 *          java.base/sun.net 
 ```
 I wonder if we should just add these two in TEST.properties - and then remove the `@modules` from these nine classes as well?

2023-01-24 12:36 UTC, dfuch commented on test/jdk/java/net/httpclient/FlowAdapterSubscriberTest.java
>   *          jdk.httpserver
```suggestion
```

2023-01-24 12:36 UTC, dfuch commented on test/jdk/java/net/httpclient/ExecutorShutdown.java
>   *          jdk.httpserver
```suggestion
```

2023-01-24 12:36 UTC, dfuch commented on test/jdk/java/net/httpclient/CookieHeaderTest.java
>   *          jdk.httpserver
```suggestion
```

2023-01-24 12:36 UTC, dfuch commented on test/jdk/java/net/httpclient/HeadTest.java
>   *          jdk.httpserver
```suggestion
```

2023-01-24 12:36 UTC, dfuch commented on test/jdk/java/net/httpclient/PathSubscriber/BodySubscriberOfFileTest.java
>   *          jdk.httpserver
```suggestion
```

2023-01-24 12:36 UTC, dfuch commented on test/jdk/java/net/httpclient/RedirectWithCookie.java
>   *          jdk.httpserver
```suggestion
```

2023-01-24 12:36 UTC, dfuch commented on test/jdk/java/net/httpclient/Response1xxTest.java
>   *          jdk.httpserver
```suggestion
```

2023-01-24 12:36 UTC, dfuch commented on test/jdk/java/net/httpclient/RetryWithCookie.java
>   *          jdk.httpserver
```suggestion
```

2023-01-24 12:36 UTC, dfuch commented on test/jdk/java/net/httpclient/StreamingBody.java
>   *          jdk.httpserver
```suggestion
```

2023-01-24 12:36 UTC, dfuch commented on test/jdk/java/net/httpclient/UnauthorizedTest.java
>   *          jdk.httpserver
```suggestion
```

2023-01-24 12:36 UTC, dfuch commented on test/jdk/java/net/httpclient/UserCookieTest.java
>   *          jdk.httpserver
```suggestion
```

2023-01-24 12:36 UTC, dfuch commented on test/jdk/java/net/httpclient/BasicRedirectTest.java
>   *          jdk.httpserver
```suggestion
```

2023-01-24 12:36 UTC, dfuch commented on test/jdk/java/net/httpclient/FilePublisher/FilePublisherPermsTest.java
>   *          jdk.httpserver
```suggestion
```

2023-01-24 12:36 UTC, dfuch commented on test/jdk/java/net/httpclient/FilePublisher/FilePublisherTest.java
>   *          jdk.httpserver
```suggestion
```

2023-01-24 12:36 UTC, dfuch commented on test/jdk/java/net/httpclient/MaxStreams.java
>   *          jdk.httpserver
```suggestion
```

2023-01-24 12:36 UTC, dfuch commented on test/jdk/java/net/httpclient/PathSubscriber/BodyHandlerOfFileDownloadTest.java
>   *          jdk.httpserver
```suggestion
```

2023-01-24 12:36 UTC, dfuch commented on test/jdk/java/net/httpclient/PathSubscriber/BodyHandlerOfFileTest.java
>   *          jdk.httpserver
```suggestion
```

2023-01-25 06:31 UTC, jaikiran commented
Hello Daniel,

> There are a few places where some lines should have been removed but were not. I made some suggestions.

Thank you for catching these. These were genuine issues and were a leftover from my `@modules` removal. I've fixed these now in the updated PR. I went through all the files again and did a search (with a different search term this time) and I think have now covered all these leftovers.

2023-01-25 07:05 UTC, jaikiran commented
> Also there are 9 classes that have kept their custom @modules clause because they want to access
>
>           java.base/sun.net.www
>           java.base/sun.net 
>
> I wonder if we should just add these two in TEST.properties - and then remove the @modules from these nine classes as well?

I think that's reasonable. When I changed most of these tests to remove `@modules` from their test definition, my selection of "common" declarations missed out these two declarations. I've now updated the `TEST.properties` to include these and also updated the relevant tests to remove the `@modules` declaration.

After this change, there remains few tests which use only a limited subset of the modules delcared in `TEST.properties`. I have left those tests as-is (for example `CancelledResponse.java`), since it didn't look necessary to remove those `@modules`. Let me know if you prefer otherwise and I'll update them as well.

Local testing with the latest state of the PR passed. I've now triggered a broader testing with these changes.

2023-01-25 11:54 UTC, dfuch approved these changes

2023-01-25 13:35 UTC, jaikiran commented
Thank you Daniel for the review. tier1, tier2, tier3 testing came back successful.

2023-01-25 13:36 UTC, jaikiran commented
/integrate

2023-01-25 13:38 UTC, closed without merging