JDK-8301076: Replace NULL with nullptr in share/prims/
openjdk/jdk pull request #12188
Opened 2023-01-25 11:47 UTC by jdksjolen

Do the conversion in the share/prims/ sub-directory and all of its files.

2023-01-26 16:22 UTC, jdksjolen commented on src/hotspot/share/prims/jni.cpp
> +    /* JNI Specification states return nullptr on OOM */
null

2023-01-26 16:22 UTC, jdksjolen commented on src/hotspot/share/prims/jni.cpp
> +    /* Empty array: legal but useless, can't return nullptr. \
null

2023-01-26 16:22 UTC, jdksjolen commented on src/hotspot/share/prims/jni.cpp
> +    /* JNI Specification states return nullptr on OOM */                    \
null

2023-01-26 16:22 UTC, jdksjolen commented on src/hotspot/share/prims/jni.cpp
> +    /* JNI Specification states return nullptr on OOM */
null

2023-01-26 16:22 UTC, jdksjolen commented on src/hotspot/share/prims/jniCheck.cpp
> +    if (cur == nullptr || !cur->is_Java_thread()) {                         \
align

2023-01-26 16:22 UTC, jdksjolen commented on src/hotspot/share/prims/jniCheck.cpp
> +      jniCheck::validate_call(thr, nullptr, methodID, obj); \
align

2023-01-26 16:22 UTC, jdksjolen commented on src/hotspot/share/prims/jniCheck.cpp
> +      jniCheck::validate_call(thr, nullptr, methodID, obj); \
align

2023-01-26 16:22 UTC, jdksjolen commented on src/hotspot/share/prims/jniCheck.cpp
> +      jniCheck::validate_call(thr, nullptr, methodID, obj); \
align

2023-01-26 16:24 UTC, jdksjolen commented on src/hotspot/share/prims/jniCheck.cpp
> +      jniCheck::validate_call(thr, nullptr, methodID, obj); \
Not aligned from start, not fixing.

2023-01-26 16:25 UTC, jdksjolen commented on src/hotspot/share/prims/jniCheck.cpp
> +      jniCheck::validate_call(thr, nullptr, methodID, obj); \
Not aligned from start, not fixing.

2023-01-26 16:25 UTC, jdksjolen commented on src/hotspot/share/prims/jniCheck.cpp
> +      jniCheck::validate_call(thr, nullptr, methodID, obj); \
Not aligned from start, not fixing.

2023-01-26 16:25 UTC, jdksjolen commented
Passes tier1.

2023-01-27 20:43 UTC, alexmenkov commented on src/hotspot/share/prims/jvmtiImpl.hpp
> +#NULL nullptr_CHECK(X, Y) if ((X) == nullptr) { return (Y); }
causes compilation error

2023-01-29 00:07 UTC, kimbarrett requested changes

2023-01-29 00:07 UTC, kimbarrett commented on src/hotspot/share/prims/methodHandles.cpp
> +#undef STRING_nullptr
Should not be changed.

2023-01-29 00:07 UTC, kimbarrett commented on src/hotspot/share/prims/methodHandles.cpp
> +#define STRING_nullptr(scope,value) #value "\0"
Should not be changed.

2023-01-29 00:07 UTC, kimbarrett commented on src/hotspot/share/prims/methodHandles.cpp
> +static const char con_names[] = { EACH_NAMED_CON(STRING_nullptr, IGNORE_REQ) };
Should not be changed.

2023-01-29 00:07 UTC, kimbarrett commented on src/hotspot/share/prims/upcallLinker.cpp
> +  // legal state. We have no last Java frame if last_Java_sp == null so
s/null/nullptr/ ?

2023-01-30 09:26 UTC, jdksjolen commented
Thanks for these review comments, I've fixed your suggestions. I must've accidentally submitted a different branch for tier1 testing, as this doesn't compile.

2023-01-31 02:23 UTC, dholmes-ora approved these changes
A few adjustments but overall looks good. Thanks.

2023-01-31 09:30 UTC, jdksjolen commented
All tests passing in GHA. @alexmenkov , would you mind approving :)?

2023-01-31 14:21 UTC, jdksjolen commented
Tier1 is passing and this has 2 approvals, I'm integrating. Thank you for the reviews.

/integrate

2023-01-31 14:22 UTC, closed without merging