JDK-8301072: Replace NULL with nullptr in share/oops/
openjdk/jdk pull request #12186
Opened 2023-01-25 11:46 UTC by jdksjolen

Do the conversion in the share/oops/ sub-directory and all of its files.

2023-01-26 15:27 UTC, jdksjolen reviewed
Found some manual fixes

2023-01-26 15:27 UTC, jdksjolen commented on src/hotspot/share/oops/annotations.cpp
> +  it->push(&_fields_type_annotations); // FIXME: need a test case where _fields_type_annotations != null
nullptr

2023-01-26 15:27 UTC, jdksjolen commented on src/hotspot/share/oops/instanceKlass.cpp
> +    char* data = nullptr;                                           \
align

2023-01-26 15:27 UTC, jdksjolen commented on src/hotspot/share/oops/method.cpp
> +  // if loader is not the default loader (i.e., != null), we can't know the intrinsics
non-null

2023-01-26 16:25 UTC, jdksjolen commented
Passes tier1.

2023-01-27 11:33 UTC, stefank requested changes

2023-01-27 11:33 UTC, stefank commented on src/hotspot/share/oops/compressedOops.inline.hpp
> +  return is_null(v) ? (oop)nullptr : decode_not_null(v);
Seems like we should be able to remove the `(oop)` cast after this change.

2023-01-27 11:33 UTC, stefank commented on src/hotspot/share/oops/compressedOops.inline.hpp
> +  return is_null(v) ? (Klass*)nullptr : decode_not_null(v);
Seems like we should be able to remove the `(Klass*)` cast after this change.

2023-01-27 11:33 UTC, stefank commented on src/hotspot/share/oops/constantPool.hpp
> +      (Symbol*)nullptr : symbol_at(_generic_signature_index);
Remove cast?

2023-01-27 11:33 UTC, stefank commented on src/hotspot/share/oops/constantPool.hpp
> +      (Symbol*)nullptr : symbol_at(_source_file_name_index);
Remove cast?

2023-01-27 11:33 UTC, stefank commented on src/hotspot/share/oops/generateOopMap.cpp
> +  if (var == nullptr) {                                              \
Could you fix the alignment of the backslashes?

2023-01-27 11:33 UTC, stefank commented on src/hotspot/share/oops/instanceKlass.cpp
> +      id == nullptr) {       // cache doesn't contain entry
Comments seems to be misaligned now.

2023-01-27 11:33 UTC, stefank commented on src/hotspot/share/oops/instanceKlass.cpp
>        (length = (size_t)jmeths[0]) <= idnum) {  // cache is too short
Alignment of comments

2023-01-27 11:33 UTC, stefank commented on src/hotspot/share/oops/instanceKlass.cpp
> -    id = jmeths[idnum+1];                       // Look up the id (may be NULL)
Alignment of comments

2023-01-27 11:33 UTC, stefank commented on src/hotspot/share/oops/klass.cpp
> -          && (super->superklass() == NULL || !is_interface())),
Alignment of comments

2023-01-27 11:33 UTC, stefank commented on src/hotspot/share/oops/method.hpp
> +  Symbol* generic_signature() const              { int idx = generic_signature_index(); return ((idx != 0) ? constants()->symbol_at(idx) : (Symbol*)nullptr); }
Remove cast?

2023-01-27 11:33 UTC, stefank commented on src/hotspot/share/oops/oopHandle.inline.hpp
> +  return (_obj == nullptr) ? (oop)nullptr : NativeAccess<>::oop_load(_obj);
Remove cast?

2023-01-27 11:33 UTC, stefank commented on src/hotspot/share/oops/oopHandle.inline.hpp
> +  return (_obj == nullptr) ? (oop)nullptr : NativeAccess<AS_NO_KEEPALIVE>::oop_load(_obj);
Remove cast?

2023-01-27 11:33 UTC, stefank commented on src/hotspot/share/oops/oopHandle.inline.hpp
> +    NativeAccess<>::oop_store(_obj, (oop)nullptr);
Remove cast?

2023-01-27 11:33 UTC, stefank commented on src/hotspot/share/oops/weakHandle.cpp
> +    NativeAccess<ON_PHANTOM_OOP_REF>::oop_store(_obj, (oop)nullptr);
Remove cast?

2023-01-27 13:38 UTC, jdksjolen commented
Thanks Stefan, added your fixes.

2023-01-27 14:09 UTC, coleenp approved these changes
Besides the casts that you may or may not be able to remove, this looks fine.

2023-01-27 14:26 UTC, stefank approved these changes

2023-01-29 23:04 UTC, dholmes-ora approved these changes
Looks good. Thanks!

2023-01-29 23:04 UTC, dholmes-ora commented on src/hotspot/share/oops/oop.hpp
> +  // this call returns "null" for that thread; any other thread has the
Nit: null should not be in quotes

2023-01-30 18:41 UTC, jdksjolen commented
@stefank , we do need to those `oop` casts. The `NativeAccess<>::oop_store` calls makes sense, `oop_store` is templated so we need to provide the type. We also need the casts in `CompressedOops`, and I don't know why that is.

2023-01-31 01:10 UTC, dholmes-ora approved these changes

2023-01-31 09:53 UTC, stefank commented
> @stefank , we do need to those `oop` casts. The `NativeAccess<>::oop_store` calls makes sense, `oop_store` is templated so we need to provide the type. We also need the casts in `CompressedOops`, and I don't know why that is.

I took a look at this. And as far as I can see, there's no obvious problem with the oop_store ore CompressedOops changes, but with the NativeAccess<>::oop_load changes.

NativeAccess<>::oop_load returns an OopLoadProxy object instead of oop, which causes the following code:
```
inline oop OopHandle::resolve() const {
  return (_obj == nullptr) ? nullptr : NativeAccess<>::oop_load(_obj);
}
```
To use the raw `nullptr` and create an OopLoadProxy, which then crashes because the passed in value is null.

We might want to reconsider removing OopLoadProxy, since it isn't the first time it is causing problems for us. I'll think about that in a context of a separate RFE.

2023-01-31 14:37 UTC, jdksjolen commented
> > @stefank , we do need to those `oop` casts. The `NativeAccess<>::oop_store` calls makes sense, `oop_store` is templated so we need to provide the type. We also need the casts in `CompressedOops`, and I don't know why that is.
> 
> I took a look at this. And as far as I can see, there's no obvious problem with the oop_store ore CompressedOops changes, but with the NativeAccess<>::oop_load changes.
> 
> NativeAccess<>::oop_load returns an OopLoadProxy object instead of oop, which causes the following code:
> 
> ```
> inline oop OopHandle::resolve() const {
>   return (_obj == nullptr) ? nullptr : NativeAccess<>::oop_load(_obj);
> }
> ```
> 
> To use the raw `nullptr` and create an OopLoadProxy, which then crashes because the passed in value is null.
> 
> We might want to reconsider removing OopLoadProxy, since it isn't the first time it is causing problems for us. I'll think about that in a context of a separate RFE.

Thanks for looking at these. I'm removing the unnecessary casts and keeping the remaining ones.

2023-02-10 09:57 UTC, jdksjolen commented
Last GHA passed, integrating this as the merge conflict was trivial.

/integrate

2023-02-10 09:58 UTC, closed without merging