JDK-8301077: Replace NULL with nullptr in share/services/
openjdk/jdk pull request #12189
Opened 2023-01-25 11:47 UTC by jdksjolen

Do the conversion in the share/services/ sub-directory and all of its files.

2023-01-25 14:56 UTC, jdksjolen reviewed
Found some things to manually fix.

2023-01-25 14:56 UTC, jdksjolen commented on src/hotspot/share/services/attachListener.cpp
> +  { nullptr,               nullptr }
Align

2023-01-25 14:56 UTC, jdksjolen commented on src/hotspot/share/services/classLoadingService.cpp
> +    if (name != nullptr) {                             \
Align

2023-01-25 14:56 UTC, jdksjolen commented on src/hotspot/share/services/heapDumper.cpp
> +    assert(_buffer == nullptr && _buffer_base == nullptr, "current buffer must be nullptr before allocate");
String

2023-01-25 14:56 UTC, jdksjolen commented on src/hotspot/share/services/heapDumper.cpp
> +  InstanceKlass* ik = nullptr; // bottom class for object arrays, null for primitive type arrays
string

2023-01-25 16:16 UTC, jdksjolen commented
Passes tier1.

2023-01-25 18:30 UTC, plummercj requested changes

2023-01-25 18:30 UTC, plummercj commented on src/hotspot/share/services/heapDumper.cpp
> +    assert (_dumper_controller == nullptr, "dumper controller must be nullptr");
The string should say "null", not "nullptr".

2023-01-25 18:30 UTC, plummercj commented on src/hotspot/share/services/mallocTracker.hpp
> +    assert(memblock != nullptr, "nullptr pointer");
String should say "null", not "nullptr"

2023-01-25 18:30 UTC, plummercj commented on src/hotspot/share/services/mallocTracker.hpp
> +    assert(memblock != nullptr, "nullptr pointer");
String should say "null", not "nullptr"

2023-01-25 18:30 UTC, plummercj commented on src/hotspot/share/services/management.cpp
> +  assert(times() != nullptr, "times was nullptr");
String should say "null", not "nullptr"

2023-01-25 18:30 UTC, plummercj commented on src/hotspot/share/services/management.cpp
> +  assert(thread != nullptr, "thread was nullptr");
String should say "null", not "nullptr"

2023-01-25 18:30 UTC, plummercj commented on src/hotspot/share/services/threadService.cpp
> +  assert(thread != nullptr, "should be non-nullptr");
String should say "null", not "nullptr"

2023-01-26 14:58 UTC, jdksjolen commented
Thanks @plummercj , I've pushed your fixes.

2023-01-27 01:46 UTC, plummercj approved these changes

2023-01-27 15:41 UTC, jdksjolen commented
Still passes tier1!

/integrate

2023-01-27 15:43 UTC, closed without merging