JDK-8301223: Replace NULL with nullptr in share/gc/g1/
openjdk/jdk pull request #12248
Opened 2023-01-27 10:06 UTC by jdksjolen

Hi, this PR changes all occurrences of NULL to nullptr for the subdirectory share/gc/g1/. Unfortunately the script that does the change isn't perfect, and so we
need to comb through these manually to make sure nothing has gone wrong. I also review these changes but things slip past my eyes sometimes.

Here are some typical things to look out for:

1. No changes but copyright header changed (probably because I reverted some changes but forgot the copyright).
2. Macros having their NULL changed to nullptr, these are added to the script when I find them. They should be NULL.
3. nullptr in comments and logs. We try to use lower case "null" in these cases as it reads better. An exception is made when code expressions are in a comment.

An example of this:

```c++
// This function returns null
void* ret_null();
// This function returns true if *x == nullptr
bool is_nullptr(void** x);
```

Note how `nullptr` participates in a code expression here, we really are talking about the specific value `nullptr`.

Thanks!

2023-01-30 09:23 UTC, tschatzl requested changes

2023-01-30 09:23 UTC, tschatzl commented on src/hotspot/share/gc/g1/c2/g1BarrierSetC2.cpp
> + * References that are nullptr are filtered during runtime by the barrier
```suggestion
 * If the previous value is null there is no need to save the old value.
 * References that are null are filtered during runtime by the barrier
```

2023-01-30 09:23 UTC, tschatzl commented on src/hotspot/share/gc/g1/c2/g1BarrierSetC2.cpp
> + * prove that the reference about to be overwritten is nullptr during compile
```suggestion
 * prove that the reference about to be overwritten is null during compile
```

2023-01-30 09:23 UTC, tschatzl commented on src/hotspot/share/gc/g1/c2/g1BarrierSetC2.cpp
> +    // if (pre_val != null)
```suggestion
    // if (pre_val != nullptr)
```
This is converted wrongly in a comment

2023-01-30 09:23 UTC, tschatzl commented on src/hotspot/share/gc/g1/c2/g1BarrierSetC2.cpp
> +      Node* buffer  = __ load(__ ctrl(), buffer_adr, TypeRawPtr::NOTnullptr, T_ADDRESS, Compile::AliasIdxRaw);
```suggestion
      Node* buffer  = __ load(__ ctrl(), buffer_adr, TypeRawPtr::NOTNULL, T_ADDRESS, Compile::AliasIdxRaw);
```

2023-01-30 09:23 UTC, tschatzl commented on src/hotspot/share/gc/g1/c2/g1BarrierSetC2.cpp
> +    } __ end_if();  // (pre_val != null)
```suggestion
    } __ end_if();  // (pre_val != nullptr)
```

2023-01-30 09:23 UTC, tschatzl commented on src/hotspot/share/gc/g1/c2/g1BarrierSetC2.cpp
> +  fields[TypeFunc::Parms+1] = TypeRawPtr::NOTnullptr; // thread
```suggestion
  fields[TypeFunc::Parms+0] = TypeInstPtr::NOTNULL; // original field value
  fields[TypeFunc::Parms+1] = TypeRawPtr::NOTNULL; // thread
```

2023-01-30 09:23 UTC, tschatzl commented on src/hotspot/share/gc/g1/c2/g1BarrierSetC2.cpp
> +  fields[TypeFunc::Parms+1] = TypeRawPtr::NOTnullptr;  // thread
```suggestion
  fields[TypeFunc::Parms+0] = TypeRawPtr::NOTNULL;  // Card addr
  fields[TypeFunc::Parms+1] = TypeRawPtr::NOTNULL;  // thread
```

2023-01-30 09:23 UTC, tschatzl commented on src/hotspot/share/gc/g1/c2/g1BarrierSetC2.cpp
> + * the same region as the reference, when the nullptr is being written or
```suggestion
 * the same region as the reference, when null is being written or
```

2023-01-30 09:23 UTC, tschatzl commented on src/hotspot/share/gc/g1/c2/g1BarrierSetC2.cpp
> +  if (val != nullptr && val->is_Con() && val->bottom_type() == TypePtr::nullptr_PTR) {
```suggestion
  if (val != nullptr && val->is_Con() && val->bottom_type() == TypePtr::NULL_PTR) {
```

2023-01-30 09:23 UTC, tschatzl commented on src/hotspot/share/gc/g1/c2/g1BarrierSetC2.cpp
> +    assert(t == Type::TOP || t == TypePtr::nullptr_PTR, "must be null");
```suggestion
    assert(t == Type::TOP || t == TypePtr::NULL_PTR, "must be null");
```

2023-01-30 09:23 UTC, tschatzl commented on src/hotspot/share/gc/g1/c2/g1BarrierSetC2.cpp
> +    // No post barrier if writing nullx
```suggestion
    // No post barrier if writing null.
```

2023-01-30 09:23 UTC, tschatzl commented on src/hotspot/share/gc/g1/c2/g1BarrierSetC2.cpp
> +  Node* buffer = __ load(__ ctrl(), buffer_adr, TypeRawPtr::NOTnullptr, T_ADDRESS, Compile::AliasIdxRaw);
```suggestion
  Node* buffer = __ load(__ ctrl(), buffer_adr, TypeRawPtr::NOTNULL, T_ADDRESS, Compile::AliasIdxRaw);
```

2023-01-30 09:23 UTC, tschatzl commented on src/hotspot/share/gc/g1/c2/g1BarrierSetC2.cpp
> +      // No barrier if we are storing a null
```suggestion
      // No barrier if we are storing a null.
```

2023-01-30 09:23 UTC, tschatzl commented on src/hotspot/share/gc/g1/g1CollectedHeap.hpp
> +    assert(Thread::current_or_null() != nullptr, "no current thread");           \
```suggestion
    assert(Thread::current_or_null() != nullptr, "no current thread");        \
```

2023-01-30 09:23 UTC, tschatzl commented on src/hotspot/share/gc/g1/g1CollectedHeap.hpp
> +  // allocated block, or else "null".
```suggestion
  // allocated block, or else null.
```

2023-01-30 09:23 UTC, tschatzl commented on src/hotspot/share/gc/g1/g1ConcurrentMark.cpp
> +        // we return null and the caller should try calling
```suggestion
        // We return null and the caller should try calling
```

2023-01-30 09:23 UTC, tschatzl commented on src/hotspot/share/gc/g1/g1FreeIdSet.cpp
> +  _next(nullptr),         // array of "next" indices
```suggestion
  _next(nullptr),      // array of "next" indices
```

2023-01-30 09:23 UTC, tschatzl commented on src/hotspot/share/gc/g1/g1RemSet.cpp
> +  // We cannot load the card value before the "r == null" check, because G1
```suggestion
  // We cannot load the card value before the "r == nullptr" check above, because G1
```

2023-04-18 14:49 UTC, jdksjolen commented
Hm, got some funny errors:

```

=== Output from failing command(s) repeated here ===
* For target hotspot_variant-server_libjvm_objs_filemap.o:
/home/runner/work/jdk/jdk/src/hotspot/share/cds/filemap.cpp: In member function 'void FileMapInfo::seek_to_position(size_t)':
/home/runner/work/jdk/jdk/src/hotspot/share/cds/filemap.cpp:1429:50: error: format '%ld' expects argument of type 'long int', but argument 2 has type 'size_t' {aka 'unsigned int'} [-Werror=format=]
 1429 |     log_error(cds)("Unable to seek to position %ld", pos);
      |                                                ~~^   ~~~
      |                                                  |   |
      |                                                  |   size_t {aka unsigned int}
      |                                                  long int
      |                                                %d
cc1plus: all warnings being treated as errors
```

I'll have to look into the merge and see if I messed that up. Worst case, I'll re-apply the nullptr conversion to origin/master.

2023-04-18 19:31 UTC, kimbarrett commented
> Hm, got some funny errors:
> 
> ```
> 
> === Output from failing command(s) repeated here ===
> * For target hotspot_variant-server_libjvm_objs_filemap.o:
> /home/runner/work/jdk/jdk/src/hotspot/share/cds/filemap.cpp: In member function 'void FileMapInfo::seek_to_position(size_t)':
> /home/runner/work/jdk/jdk/src/hotspot/share/cds/filemap.cpp:1429:50: error: format '%ld' expects argument of type 'long int', but argument 2 has type 'size_t' {aka 'unsigned int'} [-Werror=format=]
>  1429 |     log_error(cds)("Unable to seek to position %ld", pos);
>       |                                                ~~^   ~~~
>       |                                                  |   |
>       |                                                  |   size_t {aka unsigned int}
>       |                                                  long int
>       |                                                %d
> cc1plus: all warnings being treated as errors
> ```
> 
> I'll have to look into the merge and see if I messed that up. Worst case, I'll re-apply the nullptr conversion to origin/master.

That seems to be  https://bugs.openjdk.org/browse/JDK-8306289, which has been fixed.

2023-04-18 19:53 UTC, kimbarrett approved these changes
Looks good.

2023-04-19 09:46 UTC, tschatzl approved these changes
There is one more `NULL` in
```

HeapWord*
G1CollectedHeap::humongous_obj_allocate_initialize_regions(HeapRegion* first_hr,
                                                           uint num_regions,
                                                           size_t word_size) {
  assert(first_hr != NULL, "pre-condition");
```
line 281. I do not seem to be able to anchor this suggestion in the github UI.

Looks good otherwise.

2023-05-02 13:03 UTC, jdksjolen commented
Fixed the remaining nullptr conversion that tschatzl pointed out and Mach5 passes tier1.

/integrate

2023-05-02 13:04 UTC, closed without merging