JDK-8301480: Replace NULL with nullptr in os/posix
openjdk/jdk pull request #12316
Opened 2023-01-31 10:16 UTC by jdksjolen

Hi, this PR changes all occurrences of NULL to nullptr for the subdirectory os/posix. Unfortunately the script that does the change isn't perfect, and so we
need to comb through these manually to make sure nothing has gone wrong. I also review these changes but things slip past my eyes sometimes.

Here are some typical things to look out for:

1. No changes but copyright header changed (probably because I reverted some changes but forgot the copyright).
2. Macros having their NULL changed to nullptr, these are added to the script when I find them. They should be NULL.
3. nullptr in comments and logs. We try to use lower case "null" in these cases as it reads better. An exception is made when code expressions are in a comment.

An example of this:

```c++
// This function returns null
void* ret_null();
// This function returns true if *x == nullptr
bool is_nullptr(void** x);
```

Note how `nullptr` participates in a code expression here, we really are talking about the specific value `nullptr`.

Thanks!

2023-01-31 10:39 UTC, jdksjolen reviewed
Found 1issue

2023-01-31 10:39 UTC, jdksjolen commented on src/hotspot/os/posix/perfMemory_posix.cpp
> +        // indicating success, but has p == null. This was observed when
nullptr

2023-01-31 14:05 UTC, coleenp approved these changes
trivially fine.

2023-02-01 22:07 UTC, dholmes-ora requested changes
Generally good but one bug. Thanks

2023-02-01 22:07 UTC, dholmes-ora commented on src/hotspot/os/posix/signals_posix.cpp
> +                                MACH_PORT_nullptr,
This is wrong. Needs reverting. (How did this build on macOS?)

2023-02-06 23:26 UTC, dholmes-ora approved these changes
Update looks good. Thanks.

2023-02-10 13:59 UTC, jdksjolen commented
Passes tier1, integrating.

/integrate

2023-02-10 14:02 UTC, closed without merging