JDK-8301495: Replace NULL with nullptr in cpu/ppc
openjdk/jdk pull request #12323
Opened 2023-01-31 11:39 UTC by jdksjolen

Hi, this PR changes all occurrences of NULL to nullptr for the subdirectory cpu/ppc. Unfortunately the script that does the change isn't perfect, and so we
need to comb through these manually to make sure nothing has gone wrong. I also review these changes but things slip past my eyes sometimes.

Here are some typical things to look out for:

1. No changes but copyright header changed (probably because I reverted some changes but forgot the copyright).
2. Macros having their NULL changed to nullptr, these are added to the script when I find them. They should be NULL.
3. nullptr in comments and logs. We try to use lower case "null" in these cases as it reads better. An exception is made when code expressions are in a comment.

An example of this:

```c++
// This function returns null
void* ret_null();
// This function returns true if *x == nullptr
bool is_nullptr(void** x);
```

Note how `nullptr` participates in a code expression here, we really are talking about the specific value `nullptr`.

Thanks!

2023-02-01 08:37 UTC, reinrich requested changes
Looks good, just a few changes I'd like to suggest.

Thanks, Richard.

2023-02-01 08:37 UTC, reinrich commented on src/hotspot/cpu/ppc/abstractInterpreter_ppc.cpp
> +// interpreter_frame != null:
```suggestion
// interpreter_frame != nullptr:
```

2023-02-01 08:37 UTC, reinrich commented on src/hotspot/cpu/ppc/frame_ppc.cpp
> +    // In particular, (fp == null) might be true. So let's check and
```suggestion
    // In particular, (fp == nullptr) might be true. So let's check and
```

2023-02-01 08:37 UTC, reinrich commented on src/hotspot/cpu/ppc/interp_masm_ppc_64.cpp
> +    //   monitor->lock()->set_displaced_header(null);
```suggestion
    //   monitor->lock()->set_displaced_header(nullptr);
```

2023-02-01 08:37 UTC, reinrich commented on src/hotspot/cpu/ppc/interp_masm_ppc_64.cpp
> +    //   monitor->lock()->set_displaced_header(null);
```suggestion
    //   monitor->lock()->set_displaced_header(nullptr);
```

2023-02-01 08:37 UTC, reinrich commented on src/hotspot/cpu/ppc/interp_masm_ppc_64.cpp
> +    // if ((displaced_header = monitor->displaced_header()) == null) {
```suggestion
    // if ((displaced_header = monitor->displaced_header()) == nullptr) {
```

2023-02-01 08:37 UTC, reinrich commented on src/hotspot/cpu/ppc/interp_masm_ppc_64.cpp
> +    //   monitor->set_obj(null);
```suggestion
    //   monitor->set_obj(nullptr);
```

2023-02-01 08:37 UTC, reinrich commented on src/hotspot/cpu/ppc/interp_masm_ppc_64.cpp
> +    //   monitor->set_obj(null);
```suggestion
    //   monitor->set_obj(nullptr);
```

2023-02-01 08:37 UTC, reinrich commented on src/hotspot/cpu/ppc/interp_masm_ppc_64.cpp
> +    //   monitor->set_obj(null);
```suggestion
    //   monitor->set_obj(nullptr);
```

2023-02-01 08:37 UTC, reinrich commented on src/hotspot/cpu/ppc/interp_masm_ppc_64.cpp
> +    // Exchange worked, do monitor->set_obj(null);
```suggestion
    // Exchange worked, do monitor->set_obj(nullptr);
```

2023-02-01 08:37 UTC, reinrich commented on src/hotspot/cpu/ppc/interpreterRT_ppc.cpp
> +  bool do_nullptr_check = offset() != 0 || is_static();
```suggestion
  bool do_null_check = offset() != 0 || is_static();
```

2023-02-01 08:37 UTC, reinrich commented on src/hotspot/cpu/ppc/interpreterRT_ppc.cpp
> +  if (do_nullptr_check) {
```suggestion
  if (do_null_check) {
```

2023-02-01 08:37 UTC, reinrich commented on src/hotspot/cpu/ppc/stubGenerator_ppc.cpp
> +    __ cmpdi(CCR1, src, 0);      // if (src == null) return -1;
```suggestion
    __ cmpdi(CCR1, src, 0);      // if (src == nullptr) return -1;
```

2023-02-01 08:37 UTC, reinrich commented on src/hotspot/cpu/ppc/stubGenerator_ppc.cpp
> +    __ cmpdi(CCR5, dst, 0);      // if (dst == null) return -1;
```suggestion
    __ cmpdi(CCR5, dst, 0);      // if (dst == nullptr) return -1;
```

2023-02-01 08:37 UTC, reinrich commented on src/hotspot/cpu/ppc/templateInterpreterGenerator_ppc.cpp
> +  // Check if receiver == null and go the slow path.
```suggestion
  // Check if receiver == nullptr and go the slow path.
```

2023-03-15 13:02 UTC, jdksjolen reviewed
Found a few minor issues.

2023-03-15 13:02 UTC, jdksjolen commented on src/hotspot/os/posix/os_posix.cpp
> +             : NativeCallStack(NativeCallStack ::FakeMarker ::its_fake)));
Accidentally committed this, will revert to original.

2023-03-15 13:07 UTC, jdksjolen commented
Thanks @reinrich for your review. I've fixed the issues you found and fixed some that I found also, we will see what GHA says about this commit.

2023-04-11 12:36 UTC, jdksjolen commented
@backwaterred , would you like to check that this builds and tests for PPC :)?

2023-04-11 20:49 UTC, reinrich approved these changes
I've built fastdebug and release on ppc64le successfully.
Hotspot tier1 tests succeeded also.
Thanks, Richard.

2023-04-13 10:58 UTC, TheRealMDoerr approved these changes
LGTM.

2023-04-13 17:37 UTC, backwaterred approved these changes
Thanks for reaching out. This looks good to me, and builds on AIX. Testing is strange on AIX atm (there are some unrelated failures), so I'm having trouble getting a good clean run. I'm happy to fix any issues that come up later.

2023-04-14 08:53 UTC, jdksjolen commented
Thanks for all of the help with this PR.

/integrate

2023-04-14 08:55 UTC, closed without merging