8298293: NMT: should os::realloc() API take flags as arguments?
openjdk/jdk pull request #12422
Opened 2023-02-03 23:02 UTC by gerard-ziemski

2023-02-06 05:10 UTC, dholmes-ora approved these changes
Took me a little bit to get my head around the control flow here but this seems quite reasonable.

Thanks.

2023-02-06 05:11 UTC, dholmes-ora commented
P.S is it worth changing the bug synopsis now to reflect the actual changes?

2023-02-06 06:33 UTC, tstuefe approved these changes
LGTM. Maybe this would have been better before 8297718, but it's good now too.

Which buffer was this? How many buffers are there (malloced before VM init, grown afterward)?

If we really go down that route, we should benefit from it and remove some of the complexities:
- remove MEMFLAGS from os::realloc() and NMTPreInit::handle_realloc() - why should caller have to specify this the only allowed value is the one in the malloc header
- optionally: add MEMFLAGS to NMTPreInit::handle_malloc() and carry it around in the *preinit* malloc header too (see struct NMTPreInitAllocation); so that NMTPreInit::handle_realloc() can use this MEMFLAGS to call os::malloc() in case of buffer-grow-after-VMinit. But to keep things simple we could skip that part. The only penalty is that these kind of buffers are accounted with NMT default category; if we only have one of these buffers, or two, maybe its fine.
- Part of the complexity added by 8297718 is not needed anymore; some of it may be simplified

Cheers, Thomas

2023-02-06 06:56 UTC, iklam requested changes
The bug synopsis needs to be changed, since this PR does not change the `os::realloc()` API at all.

2023-02-06 06:59 UTC, dholmes-ora commented
> - remove MEMFLAGS from os::realloc() and NMTPreInit::handle_realloc() - why should caller have to specify this if the only allowed value is the one in the malloc header

@tstuefe  that was the original question this issue was asking but the determined answer was "yes it should take the flags" - the reason being that when `realloc(null,size)` is used as an alias for `malloc(size)` then we need the flags

2023-02-06 09:01 UTC, tstuefe commented
> > * remove MEMFLAGS from os::realloc() and NMTPreInit::handle_realloc() - why should caller have to specify this if the only allowed value is the one in the malloc header
> 
> @tstuefe that was the original question this issue was asking but the determined answer was "yes it should take the flags" - the reason being that when `realloc(null,size)` is used as an alias for `malloc(size)` then we need the flags

Ah, you are right, I forgot about that case.

2023-02-06 14:40 UTC, gerard-ziemski commented
Thank you for the reviews everyone!

When David, Ioi ask to change the bug synopsis, you mean the bug title, correct?

2023-02-06 16:11 UTC, iklam commented
> Thank you for the reviews everyone!
> 
> When David, Ioi ask to change the bug synopsis, you mean the bug title, correct?

Both the JBS bug title and description should be updated to reflect what this changeset is about.

2023-02-13 15:49 UTC, gerard-ziemski commented
> > Thank you for the reviews everyone!
> > When David, Ioi ask to change the bug synopsis, you mean the bug title, correct?
> 
> Both the JBS bug title and description should be updated to reflect what this changeset is about.

I wish I filed a new bug here, something to learn for the future...

2023-02-13 16:22 UTC, gerard-ziemski commented
@iklam Hopefully, I got this back on-track. Can you please approve?

2023-02-13 17:40 UTC, iklam approved these changes
LGTM

2023-02-13 18:13 UTC, gerard-ziemski commented
/integrate

2023-02-13 18:14 UTC, closed without merging