8301820: C4819 warnings were reported on Windows
openjdk/jdk pull request #12427
Opened 2023-02-04 09:42 UTC by YaSuenag

C4819 warnings were reported when I tried to build JDK on Windows with VS2022.
This PR contains changes both HotSpot and client libraries. Let me know if they should be separated.

* HotSpot
    * stubGenerator_x86_64_poly.cpp
    * elfFile.hpp
* libfontmanager
    * hb.hh
* libfreetype
    * afblue.c

I added C4819 to `DISABLED_WARNINGS_microsoft` for libfontmanager and for libfreetype because they are 3rd-party libraries.

2023-02-04 23:08 UTC, vidmik commented
Out of curiosity, which version of VS 2022 is this?

2023-02-05 00:40 UTC, YaSuenag commented
I uses 17.3.6 (VS Community) on Windows 11 Pro (Japanese locale (CP932))

I saw following message on the console (It is Japanese, sorry...)

```
d:\github-forked\jdk\src\hotspot\cpu\x86\stubGenerator_x86_64_poly.cpp(1): error C2220: 次の警告はエラーとして処理されます
d:\github-forked\jdk\src\hotspot\cpu\x86\stubGenerator_x86_64_poly.cpp(1): warning C4819: ファイルは、現在のコード ページ (932) で表示できない文字を含んでいます。データの損失を防ぐために、ファイルを Unicode 形式で保存してください。
```

In case of stubGenerator_x86_64_poly.cpp , `×` in comments cannot be handled in cl.exe. I confirmed that this character cannot be handled `iconv -f CP932 -t UTF8`, so I replaced it to `x` (alphabet).

2023-02-06 01:06 UTC, dholmes-ora requested changes
Sorry Yasumasa, but I'd much prefer to see this split into three sub-tasks (or issues) just so we can keep the issues more clearly separated.

IIUC for stubGenerator_x86_64_poly.cpp we have a multiplication symbol instead of an ascii 'x' (likely pasted from a word processing document).

For elfFile.hpp there are smart-quotes instead of ascii "

Thanks.

2023-02-06 12:37 UTC, YaSuenag commented
@dholmes-ora I splitted this in three sub tasks as #12435, #12436, #12437.  
I hope they are reviewed and merged.

So I close this PR (but I do not close this issue on JBS until all subtasks are resolved).

2023-02-06 12:37 UTC, closed without merging