8296158: Refactor the verification of CDS region checksum
openjdk/jdk pull request #12424
Opened 2023-02-04 01:22 UTC by iklam

Consolidate the two old functions

- `FileMapInfo::region_crc_check(char* buf, size_t size, int expected_crc)`
- `FileMapInfo::verify_region_checksum(int i)`

Into a single function `FileMapRegion::check_region_crc()`.

Also performed some minor renaming and removed a useless API.

2023-02-04 02:24 UTC, calvinccheung approved these changes
Code refactoring looks good.

2023-02-14 21:28 UTC, matias9927 requested changes

2023-02-14 22:02 UTC, iklam commented on src/hotspot/share/cds/filemap.cpp
> +  if (!VerifySharedSpaces) {
Thanks for the comment. I fixed the code as you suggested.

2023-02-14 22:06 UTC, matias9927 approved these changes
LGTM!

2023-02-17 07:20 UTC, iklam commented
Thanks @matias9927 and @calvinccheung for the review
/integrate

2023-02-17 07:21 UTC, closed without merging