8301854: C4819 warnings were reported in libfreetype on Windows
openjdk/jdk pull request #12436
Opened 2023-02-06 12:34 UTC by YaSuenag

This is subtask of https://github.com/openjdk/jdk/pull/12427 .

I have seen C4819 warning in libfreetype files on Windows (CP932: Japanese locale)

```
d:\github-forked\jdk\src\java.desktop\share\native\libfreetype\src\autofit\afscript.h(1): warning C4819: ファイルは、現在のコード ページ (932) で表示できない文字を含んでいます。データの損失を防ぐために、ファイルを Unicode 形式で保存してください。
```

I added C4819 to DISABLED_WARNINGS_microsoft for libfontmanager and for libfreetype because they are 3rd-party libraries.

2023-02-06 13:49 UTC, magicus commented
So to add some context to this and the related PRs.  **C4819** has this official description:

`The file contains a character that cannot be represented in the current code page (number). Save the file in Unicode format to prevent data loss.`

So, this is not so much a compilation error per se, but a problem with the encoding of our source code files.

Some time ago, there were a discussion that we should make sure our code base where in utf-8, instead of the current unspecified state of "mostly ascii, but some additional characters but we won't tell you which encoding, hopefully it's latin-1". 

I'm thinking the correct choice is maybe not to silence the warning, but to actually put down our collective feet, say "enough is enough of this nonsense!", declare the source to be utf-8, turn on all flags needed to get our tools to recognize this fact, and then go on with our lives.

2023-02-06 17:14 UTC, prrace commented
Fix rejected for the same reasons as described in https://github.com/openjdk/jdk/pull/12437

" declare the source to be utf-8, "

you can't do that if you don't own the code, can you ?
Regardless this fix isn't right.

2023-02-07 00:01 UTC, YaSuenag commented
I grep'ed (with `-i`) in `doc` directory with `LANG`, `utf`, `locale`, but I could not find out them. I guess locale of build environment is not mentioned clearly. Is it correct?

I agree with you to use English locale (e.g. `LANG=C`) is prefered, but I guess may difficult when we use WSL because `LANG` is not propergate to Windows environment.

I confirmed that it is succeeded to build with `--with-extra-cflags=/utf-8 --with-extra-cxxflags=/utf-8`, so I think it is better to add them to build option for Windows by default, but I'm not sure it is correct because no documents mention to the locale. What do you think?

2023-02-07 01:12 UTC, prrace commented
> I grep'ed (with `-i`) in `doc` directory with `LANG`, `utf`, `locale`, but I could not find out them. I guess locale of build environment is not mentioned clearly. Is it correct?
> 
> I agree with you to use English locale (e.g. `LANG=C`) is prefered, but I guess may difficult when we use WSL because `LANG` is not propergate to Windows environment.
> 
> I confirmed that it is succeeded to build with `--with-extra-cflags=/utf-8 --with-extra-cxxflags=/utf-8`, so I think it is better to add them to build option for Windows by default, but I'm not sure it is correct because no documents mention to the locale. What do you think?

I don't know if it is documented but it has been discussed multiple times over the years.
Which encodings are *supposed* to work would be a good thing to document, LANG=C isn't strictly "English" and LC_* vars over-ride it
but "en_US-iso-8859-1" (eg) definitely should work, because that or some close equivalent (windows cp1252 or maybe 1250) are what we've considered as "must work" (SFAIK) 

If the build team want to make utf-8 the default encoding and it can be done  without having to worry unduly about 3rd party code and what might be in the repo today then that would be a good thing I expect.
But it is a bigger conversation than this PR

2023-02-07 02:46 UTC, YaSuenag commented
> but "en_US-iso-8859-1" (eg) definitely should work, because that or some close equivalent (windows cp1252 or maybe 1250) are what we've considered as "must work" (SFAIK)

According to Wikipedia article of [CP1250](https://en.wikipedia.org/wiki/Windows-1250) and [CP1252](https://en.wikipedia.org/wiki/Windows-1252), characters in 9x is not available in [8859-1](https://en.wikipedia.org/wiki/ISO/IEC_8859-1), and  I saw this error in `“` (0x93) and `”` (0x94).

So I think to use UTF-8 should be documented, and it is better to add `/utf-8` to `CFLAGS` / `CXXFLAGS` for Windows if we can.

2023-02-07 03:55 UTC, prrace commented
> > but "en_US-iso-8859-1" (eg) definitely should work, because that or some close equivalent (windows cp1252 or maybe 1250) are what we've considered as "must work" (SFAIK)
> 
> According to Wikipedia article of [CP1250](https://en.wikipedia.org/wiki/Windows-1250) and [CP1252](https://en.wikipedia.org/wiki/Windows-1252), characters in 9x is not available in [8859-1](https://en.wikipedia.org/wiki/ISO/IEC_8859-1), and I saw this error in `“` (0x93) and `”` (0x94).
> 
> So I think to use UTF-8 should be documented, and it is better to add `/utf-8` to `CFLAGS` / `CXXFLAGS` for Windows if we can.

So let's say it is the compatible subset.

Regardless, take this to the build team as a separate PR to find a JDK-wide
solution. No disabling warnings in random libraries

2023-02-07 11:50 UTC, magicus commented
> I grep'ed (with `-i`) in `doc` directory with `LANG`, `utf`, `locale`, but I could not find out them. I guess locale of build environment is not mentioned clearly. Is it correct?

Yes, it is unfortunately not documented. :-( There is an open bug about this ([JDK-8264425](https://bugs.openjdk.org/browse/JDK-8264425)) but it has repeatedly been pushed down on my todo list due to low priority. :(

2023-02-07 11:57 UTC, magicus requested changes
I agree with Phil here. This is not the proper solution. As a workaround, you can use the configure arguments to add additional flags to the compiler. Or you can change your locale.

The proper solution is getting the source code base to a consistent UTF-8 format. This is a much larger undertaking, however.

2023-02-07 12:08 UTC, magicus commented
I have opened https://bugs.openjdk.org/browse/JDK-8301971 for converting the entire code base to UTF-8.

2023-02-09 06:48 UTC, YaSuenag commented
This issue will be treated in [JDK-8301971](https://bugs.openjdk.org/browse/JDK-8301971)

2023-02-09 06:48 UTC, closed without merging