8301853: C4819 warnings were reported in HotSpot on Windows
openjdk/jdk pull request #12435
Opened 2023-02-06 12:33 UTC by YaSuenag

This is subtask of #12427 .

I have seen C4819 warning in stubGenerator_x86_64_poly.cpp and elfFile.hpp in HotSpot on Windows (CP932: Japanese locale)

```
d:\github-forked\jdk\src\hotspot\cpu\x86\stubGenerator_x86_64_poly.cpp(1): error C2220: 次の警告はエラーとして処理されます
d:\github-forked\jdk\src\hotspot\cpu\x86\stubGenerator_x86_64_poly.cpp(1): warning C4819: ファイルは、現在のコード ページ (932) で表示できない文字を含んでいます。データの損失を防ぐために、ファイルを Unicode 形式で保存してください。
```

2023-02-06 22:10 UTC, dholmes-ora approved these changes
Looks good and trivial. Thanks for fixing.

2023-02-07 02:30 UTC, dholmes-ora commented
I note from the related PRs that they are not being fixed due to "building with the 'wrong' locale", but I would still want to see this change integrated for hotspot because the problematic characters in src/hotspot/cpu/x86/stubGenerator_x86_64_poly.cpp do not display correctly in text editors (the multiplication sign displays for me as a capital A with a tilde over it).

2023-02-07 02:48 UTC, YaSuenag commented
We continue to discuss for the encoding of source files in #12436, but I want to merge this to master branch because this PR changes comments only.

2023-02-07 11:45 UTC, magicus requested changes
Please hold on and do not merge this PR.

The problem here is that the encoding of the file is not properly conveyed. This is code written by Intel where the original author clearly put in the time to use a separate mathematical sign to clarify the discussion. I think this should not just be trivially removed. Let's fix this properly instead.

2023-02-08 00:52 UTC, dholmes-ora commented
> Isn't it better to replace the multiplication sign with an asterisk (*) instead of the letter 'x'?

No. Asterisk is already used to mean something else
```
//    * used for poly1305_multiply_scalar
//    x used for poly1305_multiply8_avx512
```

> The problem here is that the encoding of the file is not properly conveyed.

@magicus That may be the problem with the warning, but I'm more concerned that the special characters won't display properly in typical editing environments. So as a change to hotspot code I am more than happy to see this go in.

2023-02-08 01:11 UTC, dholmes-ora commented
Visually the difference between × and x is minimal.  Whereas seeing Ã in place of x is very disruptive. Sure you could argue this is an environment issue and the multiplication symbol should display properly with the right settings, but it is trivial fix, with zero harm, to just replace it with plain x.

2023-02-08 13:15 UTC, magicus approved these changes
Ok, it's your code, so if you want an `x` instead, go ahead. I fully agree that some special non-ASCII character has no need in the source code, like typographic quotes, and should be replaced by normal ASCII character. I would not have counted this multiplication symbol as unnecessary, but I understand and respect that you think otherwise.

2023-02-09 06:48 UTC, YaSuenag commented
/integrate

2023-02-09 06:50 UTC, closed without merging