8300255: Introduce interface for GC oop verification in the assembler
openjdk/jdk pull request #12443
Opened 2023-02-06 15:32 UTC by fisk

In the assembly code, there is some generic oop verification code. Said verification may or may not fit a particular GC. In particular, it has not worked well for ZGC for a while, and there is an if (UseZGC). This enhancement aims at generalizing this code, such that a collector can have its own oop verification policy.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8300255](https://bugs.openjdk.org/browse/JDK-8300255): Introduce interface for GC oop verification in the assembler

### Reviewers
 * [Fei Yang](https://openjdk.org/census#fyang) (@RealFYang - **Reviewer**)
 * [Axel Boldt-Christmas](https://openjdk.org/census#aboldtch) (@xmas92 - Committer)
 * [Coleen Phillimore](https://openjdk.org/census#coleenp) (@coleenp - **Reviewer**)

### Contributors
 * Martin Doerr `<mdoerr@openjdk.org>`
 * Axel Boldt-Christmas `<aboldtch@openjdk.org>`
 * Yadong Wang `<yadongwang@openjdk.org>`

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/12443/head:pull/12443` \
`$ git checkout pull/12443`

Update a local copy of the PR: \
`$ git checkout pull/12443` \
`$ git pull https://git.openjdk.org/jdk pull/12443/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12443`

View PR using the GUI difftool: \
`$ git pr show -t 12443`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12443.diff">https://git.openjdk.org/jdk/pull/12443.diff</a>

</details>

2023-02-06 15:33 UTC, fisk commented
/contributor add @TheRealMDoerr

2023-02-06 15:34 UTC, fisk commented
/contributor add @xmas92

2023-02-06 15:35 UTC, fisk commented
/contributor add @yadongw

2023-02-06 15:36 UTC, fisk commented
PPC code contributed by @TheRealMDoerr and RISC-V code contributed by @yadongw. Could you please check that it works on your machines?

2023-02-07 05:14 UTC, TheRealMDoerr commented
> PPC code contributed by @TheRealMDoerr and RISC-V code contributed by @yadongw. Could you please check that it works on your machines?

The default version of check_oop doesn't work for ZGC. I suggest to exclude the PPC64 parts here and ship them with the generational ZGC PR. That will reduce effort. Does that make sense?

2023-02-07 09:57 UTC, fisk commented
> > PPC code contributed by @TheRealMDoerr and RISC-V code contributed by @yadongw. Could you please check that it works on your machines?
> 
> The default version of check_oop doesn't work for ZGC. I suggest to exclude the PPC64 parts here and ship them with the generational ZGC PR. That will reduce effort. Does that make sense?

Hmm. Looking at the changes of this patch, we used to call __ verify_oop, but now we call check_oop on the barrier set assembler, which in turn has a single implementation which calls __ verify_oop. It seems like this patch currently does not change the behaviour at all to what happened before? While I am perfectly fine removing the PPC changes, I don't think I understand what behaviour this patch changes for PPC.

2023-02-07 10:34 UTC, RealFYang requested changes
Hi, seems we need two extra small changes to build on linux-riscv. Thanks.

2023-02-07 10:34 UTC, RealFYang commented on src/hotspot/cpu/riscv/gc/z/zBarrierSetAssembler_riscv.hpp
> +  virtual void check_oop(MacroAssembler* masm, Register obj, Register tmp1, Register tmp2, Label& error);
Need to remove 'virtual' here.

2023-02-07 10:34 UTC, RealFYang commented on src/hotspot/cpu/riscv/gc/z/zBarrierSetAssembler_riscv.cpp
> +void BarrierSetAssembler::check_oop(MacroAssembler* masm, Register obj, Register tmp1, Register tmp2, Label& error) {
Should be 'ZBarrierSetAssembler::check_oop' here.

2023-02-07 11:52 UTC, TheRealMDoerr commented
> > > PPC code contributed by @TheRealMDoerr and RISC-V code contributed by @yadongw. Could you please check that it works on your machines?
> > 
> > 
> > The default version of check_oop doesn't work for ZGC. I suggest to exclude the PPC64 parts here and ship them with the generational ZGC PR. That will reduce effort. Does that make sense?
> 
> Hmm. Looking at the changes of this patch, we used to call __ verify_oop, but now we call check_oop on the barrier set assembler, which in turn has a single implementation which calls __ verify_oop. It seems like this patch currently does not change the behaviour at all to what happened before? While I am perfectly fine removing the PPC changes, I don't think I understand what behaviour this patch changes for PPC.

You're right. VerifyOops is already broken with ZGC on PPC64. You can keep the PPC64 parts as they are. The generational ZGC code will fix the problem. So, I'm fine with this PR.

2023-02-07 15:08 UTC, fisk commented
> > > > PPC code contributed by @TheRealMDoerr and RISC-V code contributed by @yadongw. Could you please check that it works on your machines?
> > > 
> > > 
> > > The default version of check_oop doesn't work for ZGC. I suggest to exclude the PPC64 parts here and ship them with the generational ZGC PR. That will reduce effort. Does that make sense?
> > 
> > 
> > Hmm. Looking at the changes of this patch, we used to call __ verify_oop, but now we call check_oop on the barrier set assembler, which in turn has a single implementation which calls __ verify_oop. It seems like this patch currently does not change the behaviour at all to what happened before? While I am perfectly fine removing the PPC changes, I don't think I understand what behaviour this patch changes for PPC.
> 
> You're right. VerifyOops is already broken with ZGC on PPC64. You can keep the PPC64 parts as they are. The generational ZGC code will fix the problem. So, I'm fine with this PR.

Okay great - thanks for checking!

2023-02-07 15:08 UTC, fisk commented
> Hi, seems we need two extra small changes to build on linux-riscv. Thanks.

Thanks for having a look! Hopefully fixed in the latest commit.

2023-02-08 09:02 UTC, RealFYang commented
@fisk : Hi, I think we should also add following changes for riscv:
```
diff --git a/src/hotspot/cpu/riscv/gc/shared/barrierSetAssembler_riscv.cpp b/src/hotspot/cpu/riscv/gc/shared/barrierSetAssembler_riscv.cpp
index ed53fbf22c8..662de44de29 100644
--- a/src/hotspot/cpu/riscv/gc/shared/barrierSetAssembler_riscv.cpp
+++ b/src/hotspot/cpu/riscv/gc/shared/barrierSetAssembler_riscv.cpp
@@ -316,8 +316,7 @@ void BarrierSetAssembler::check_oop(MacroAssembler* masm, Register obj, Register
   __ mv(tmp2, (intptr_t) Universe::verify_oop_bits());

   // Compare tmp1 and tmp2.
-  __ xorr(tmp1, tmp1, tmp2);
-  __ bnez(tmp1, error);
+  __ bne(tmp1, tmp2, error);

   // Make sure klass is 'reasonable', which is not zero.
   __ load_klass(obj, obj, tmp1); // get klass
diff --git a/src/hotspot/cpu/riscv/gc/z/zBarrierSetAssembler_riscv.cpp b/src/hotspot/cpu/riscv/gc/z/zBarrierSetAssembler_riscv.cpp
index 0741869ddaf..1ebfb8f9e23 100644
--- a/src/hotspot/cpu/riscv/gc/z/zBarrierSetAssembler_riscv.cpp
+++ b/src/hotspot/cpu/riscv/gc/z/zBarrierSetAssembler_riscv.cpp
@@ -449,10 +449,10 @@ void ZBarrierSetAssembler::generate_c1_load_barrier_runtime_stub(StubAssembler*

 void ZBarrierSetAssembler::check_oop(MacroAssembler* masm, Register obj, Register tmp1, Register tmp2, Label& error) {
   // Check if mask is good.
-  // verifies that ZAddressBadMask & x10 == 0
-  __ ld(c_rarg3, Address(xthread, ZThreadLocalData::address_bad_mask_offset()));
-  __ andr(c_rarg2, x10, c_rarg3);
-  __ bnez(c_rarg2, error);
+  // verifies that ZAddressBadMask & obj == 0
+  __ ld(tmp2, Address(xthread, ZThreadLocalData::address_bad_mask_offset()));
+  __ andr(tmp1, obj, tmp2);
+  __ bnez(tmp1, error);

   BarrierSetAssembler::check_oop(masm, obj, tmp1, tmp2, error);
 }
```

2023-02-08 10:42 UTC, fisk commented
> @fisk : Hi, I think we should also add following changes for riscv to make it work:
> 
> ```
> diff --git a/src/hotspot/cpu/riscv/gc/shared/barrierSetAssembler_riscv.cpp b/src/hotspot/cpu/riscv/gc/shared/barrierSetAssembler_riscv.cpp
> index ed53fbf22c8..662de44de29 100644
> --- a/src/hotspot/cpu/riscv/gc/shared/barrierSetAssembler_riscv.cpp
> +++ b/src/hotspot/cpu/riscv/gc/shared/barrierSetAssembler_riscv.cpp
> @@ -316,8 +316,7 @@ void BarrierSetAssembler::check_oop(MacroAssembler* masm, Register obj, Register
>    __ mv(tmp2, (intptr_t) Universe::verify_oop_bits());
> 
>    // Compare tmp1 and tmp2.
> -  __ xorr(tmp1, tmp1, tmp2);
> -  __ bnez(tmp1, error);
> +  __ bne(tmp1, tmp2, error);
> 
>    // Make sure klass is 'reasonable', which is not zero.
>    __ load_klass(obj, obj, tmp1); // get klass
> diff --git a/src/hotspot/cpu/riscv/gc/z/zBarrierSetAssembler_riscv.cpp b/src/hotspot/cpu/riscv/gc/z/zBarrierSetAssembler_riscv.cpp
> index 0741869ddaf..1ebfb8f9e23 100644
> --- a/src/hotspot/cpu/riscv/gc/z/zBarrierSetAssembler_riscv.cpp
> +++ b/src/hotspot/cpu/riscv/gc/z/zBarrierSetAssembler_riscv.cpp
> @@ -449,10 +449,10 @@ void ZBarrierSetAssembler::generate_c1_load_barrier_runtime_stub(StubAssembler*
> 
>  void ZBarrierSetAssembler::check_oop(MacroAssembler* masm, Register obj, Register tmp1, Register tmp2, Label& error) {
>    // Check if mask is good.
> -  // verifies that ZAddressBadMask & x10 == 0
> -  __ ld(c_rarg3, Address(xthread, ZThreadLocalData::address_bad_mask_offset()));
> -  __ andr(c_rarg2, x10, c_rarg3);
> -  __ bnez(c_rarg2, error);
> +  // verifies that ZAddressBadMask & obj == 0
> +  __ ld(tmp2, Address(xthread, ZThreadLocalData::address_bad_mask_offset()));
> +  __ andr(tmp1, obj, tmp2);
> +  __ bnez(tmp1, error);
> 
>    BarrierSetAssembler::check_oop(masm, obj, tmp1, tmp2, error);
>  }
> ```

Fixed!

2023-02-09 13:10 UTC, xmas92 approved these changes
lgtm.

2023-02-09 13:10 UTC, xmas92 commented on src/hotspot/cpu/aarch64/gc/z/zBarrierSetAssembler_aarch64.cpp
> +  // verifies that ZAddressBadMask & r0 == 0
Update comment `s/r0/obj`

2023-02-09 15:32 UTC, coleenp approved these changes
This change looks nice.  Did you run tier8 or tier1 tests with -XX:+VerifyOops? I thought we ran some general testing in tier3 with -XX:+VerifyOops but we don't seem to be doing that.  Thanks.

2023-02-10 07:38 UTC, RealFYang approved these changes
Updated RISC-V part looks good. Thanks.

2023-02-10 14:49 UTC, fisk commented
> Updated RISC-V part looks good. Thanks.

Thanks!

2023-02-10 14:52 UTC, fisk commented
> This change looks nice. Did you run tier8 or tier1 tests with -XX:+VerifyOops? I thought we ran some general testing in tier3 with -XX:+VerifyOops but we don't seem to be doing that. Thanks.

Thanks for the review! I have run gc-test-suite locally on both an AArch64 machine and x86_64 machine, with -XX:+VerifyOops with ZGC and G1, and it looks fine. I think it exercises verify oops pretty well. Do you want me to run tier8 as well? Personally, I hesitate a bit to run off a tier8 job for this change if gc-test-suite is happy with -XX:+VerifyOops.

2023-02-10 15:40 UTC, coleenp commented
Tier8 is unnecessary as you've done general testing with it.

2023-02-10 16:30 UTC, fisk commented
> Tier8 is unnecessary as you've done general testing with it.

Okay, thanks!

2023-02-13 15:49 UTC, fisk commented
/integrate

2023-02-13 15:51 UTC, closed without merging