8301753: AppendFile needs to add a new line to be compatible with old make
openjdk/jdk pull request #12461
Opened 2023-02-07 20:56 UTC by lmesnik

The newline is added to be compatible with old make 3.81 which is still used on MacOSX

2023-02-07 20:59 UTC, lmesnik commented
/contributor add dnsimon

2023-02-07 21:08 UTC, erikj79 approved these changes

2023-02-07 21:40 UTC, dougxc approved these changes

2023-02-08 13:53 UTC, magicus commented
Possible solutions include:
* Stripping any potential newline from the end of the input, and keep unconditionally adding one in the printf statement like in the current patch.
* Checking if the input ends with a newline, and print the additional `\n` only if it doesn't.
* Change the requirements for both the make 4+ and printf version to never have input ending in a newline. This would likely have to be verified by an assert.

My personal recommendation would be to pick the first solution on this list, I think it is easiest to implement in Make.

2023-02-08 14:17 UTC, erikj79 requested changes
It looks like you are correct Magnus, I didn't think about that. I will see what I can do about solving this properly.

2023-02-08 14:22 UTC, magicus commented
@lmesnik If you want, I can take over the issue and solve it correctly. Let me know.

2023-04-18 00:58 UTC, closed without merging