8302155: [AIX] NUM_LCPU is not required variable
openjdk/jdk pull request #12494
Opened 2023-02-09 15:21 UTC by offamitkumar

We don't need NUM_LCPU, it's just a small code change which removes this variable. I've tested it on AIX and cores are detected successfully with changes. 
@backwaterred please take look at it. 
 Suggestions are welcomed :)

2023-02-10 16:59 UTC, backwaterred approved these changes
I wanted to point out these changes are semantically different in the error case. If we don't get the output we expect from lparstat we potentially overwrite the NUM_CORES var with the empty string. Previously, the code protected against this by testing if the result stored in the temp variable was non-empty before committing to them.

Checking the [documentation](https://www.ibm.com/docs/en/aix/7.2?topic=l-lparstat-command) for AIX 7.1-7.3, it seems like the syntax is stable, so removing this check seems reasonable to me.

2023-02-13 14:22 UTC, magicus commented on make/autoconf/build-performance.m4
> +    NUM_CORES=`lparstat -m 2> /dev/null | $GREP -o "lcpu=[[0-9]]*" | $CUT -d "=" -f 2`
The assignment of `NUM_CORES=0` on line 29 was to cover the case that `lparstat` failed. If you are certain that it works, fine, make this change. But please also remove the unnecessary initialization of `NUM_CORES` then.

2023-02-13 14:23 UTC, magicus requested changes
(github needs me to repeat the comment here)

2023-02-13 16:15 UTC, magicus approved these changes
The merge warning from the bots sounded a bit scary; I don't understand what git move you did there, but the end result seems to look fine anyway.

2023-02-13 16:17 UTC, magicus commented
I can sponsor this change, unless you have some other sponsor already.

2023-02-13 16:25 UTC, offamitkumar commented
Sure @magicus , 
/integrate

2023-02-13 18:59 UTC, magicus commented
/sponsor

2023-02-13 19:01 UTC, closed without merging