JDK-8302335: IGV: Bytecode not showing
openjdk/jdk pull request #12537
Opened 2023-02-13 15:09 UTC by tobiasholenstein

Currently, IGV does not show the bytecode of a graph in the "Bytecode" window although the bytecode is present in the XML file.

# Solution
<img width="283" alt="bytecode" src="https://user-images.githubusercontent.com/71546117/218495199-2b02a79c-3065-404c-af57-3f8a603ac499.png">

2023-02-15 09:49 UTC, robcasloz requested changes
Good catch! The issue with the more liberal matching of bytecodes proposed in this PR is that bytecode attributes are now also matched and treated as bytecodes, see e.g. the second last line in this screenshot:

![bytecodes](https://user-images.githubusercontent.com/8792647/218989785-79d53c60-7e34-4680-ba51-536b7eead232.png)

Somewhere between JDK 20 b17 and JDK 20 b25 (most likely with the integration of [JDK-8292699](https://bugs.openjdk.org/browse/JDK-8292699)), the indentation in bytecode dumps produced by `BytecodeTracer::print_method_codes()` changed. The change introduced indentation for the bytecodes but did not update the indentation of their attributes, which I guess was unintended. Here is an example:

Before:

```
0 nofast_aload_0
1 invokevirtual 478 <java/lang/String.isLatin1()Z> 
  0   bci: 1    VirtualCallData     count(5119) nonprofiled_count(0) entries(0)

```

After:

```
   0 nofast_aload_0
   1 invokevirtual 478 <java/lang/String.isLatin1()Z> 
  0   bci: 1    VirtualCallData     count(5119) nonprofiled_count(0) entries(0)

```

I am not sure about what is the best solution to this, but ideally we would want to support the old and current indentation, and probably also fix and support the proper indentation of bytecode attributes in `BytecodeTracer::print_method_codes()`.

A possible solution from IGV side is to rule out attribute lines, e.g. likes starting with  a number then the `bci` keyword such as 
`  56  bci: 4    BranchData          taken(0) displacement(48)`
or lines starting with non-digits such as
`                                    not taken(5119)`
And so on. Another possible solution is to actually parse these attributes and display them somehow (e.g. as bytecode sub-items), since they actually convey useful information. What do you think?

2023-02-15 15:35 UTC, tobiasholenstein commented
> Good catch! The issue with the more liberal matching of bytecodes proposed in this PR is that bytecode attributes are now also matched and treated as bytecodes, see e.g. the second last line in this screenshot:
> 
> ![bytecodes](https://user-images.githubusercontent.com/8792647/218989785-79d53c60-7e34-4680-ba51-536b7eead232.png)
> 
> Somewhere between JDK 20 b17 and JDK 20 b25 (most likely with the integration of [JDK-8292699](https://bugs.openjdk.org/browse/JDK-8292699)), the indentation in bytecode dumps produced by `BytecodeTracer::print_method_codes()` changed. The change introduced indentation for the bytecodes but did not update the indentation of their attributes, which I guess was unintended. Here is an example:
> 
> Before:
> 
> ```
> 0 nofast_aload_0
> 1 invokevirtual 478 <java/lang/String.isLatin1()Z> 
>   0   bci: 1    VirtualCallData     count(5119) nonprofiled_count(0) entries(0)
> ```
> 
> After:
> 
> ```
>    0 nofast_aload_0
>    1 invokevirtual 478 <java/lang/String.isLatin1()Z> 
>   0   bci: 1    VirtualCallData     count(5119) nonprofiled_count(0) entries(0)
> ```
> 
> I am not sure about what is the best solution to this, but ideally we would want to support the old and current indentation, and probably also fix and support the proper indentation of bytecode attributes in `BytecodeTracer::print_method_codes()`.
> 
> A possible solution from IGV side is to rule out attribute lines, e.g. likes starting with a number then the `bci` keyword such as ` 56 bci: 4 BranchData taken(0) displacement(48)` or lines starting with non-digits such as ` not taken(5119)` And so on. Another possible solution is to actually parse these attributes and display them somehow (e.g. as bytecode sub-items), since they actually convey useful information. What do you think?

You are right. I changed it such that we now support the old and new format. Now we just skip lines with the `bci:` keyword.
Regarding parsing and displaying bci information - I think this should be done in a different RFE

2023-02-15 18:12 UTC, navyxliu commented
>   0   bci: 1    VirtualCallData     count(5119) nonprofiled_count(0) entries(0)

Those are methoddata.  Should we add a leading character such as '#' to distinct them from real bytecode?  I believe that would simplify matching logic in IGV.

2023-02-16 12:09 UTC, tobiasholenstein commented
> methoddata

This would require a VM change for a printing flag. E.g. `-XX:+CIPrintMethodCodes` uses that code as well - I think we should leave it as it is because the main use is intended to be human-readable and it could break parsing of other uses (that we are not aware of)

2023-02-16 12:09 UTC, tobiasholenstein commented
> > 0   bci: 1    VirtualCallData     count(5119) nonprofiled_count(0) entries(0)
> 
> Those are methoddata. Should we add a leading character such as '#' to distinct them from real bytecode? I believe that would simplify matching logic in IGV.

This would require a VM change for a printing flag. E.g. `-XX:+CIPrintMethodCodes` uses that code as well - I think we should leave it as it is because the main use is intended to be human-readable and it could break parsing of other uses (that we are not aware of)

2023-02-16 12:37 UTC, robcasloz approved these changes
Looks good otherwise!

2023-02-16 12:37 UTC, robcasloz commented on src/utils/IdealGraphVisualizer/Data/src/main/java/com/sun/hotspot/igv/data/InputMethod.java
>                  // indented lines are extra textual information
Maybe update this comment?

2023-02-16 12:41 UTC, TobiHartmann commented
The method data still shows up for me:

![Screenshot from 2023-02-16 13-39-18](https://user-images.githubusercontent.com/5312595/219367453-aed3f86d-de6c-4a54-9df5-bb5095e26026.png)

2023-02-16 13:03 UTC, tobiasholenstein commented
> The method data still shows up for me:
> 
> ![Screenshot from 2023-02-16 13-39-18](https://user-images.githubusercontent.com/5312595/219367453-aed3f86d-de6c-4a54-9df5-bb5095e26026.png)



> The method data still shows up for me:
> 
> ![Screenshot from 2023-02-16 13-39-18](https://user-images.githubusercontent.com/5312595/219367453-aed3f86d-de6c-4a54-9df5-bb5095e26026.png)

Thanks for catching that! 
This is actually a bug in printing the bytecodes on the VM side: [JDK-8302656](https://bugs.openjdk.org/browse/JDK-8302656)
I adjusted the PR to work even in the presents of the bug (and still work when it is fixed)

2023-02-16 13:11 UTC, robcasloz approved these changes

2023-02-16 22:38 UTC, navyxliu approved these changes
LGTM. I am not a reviewer.

2023-02-17 14:25 UTC, tobiasholenstein commented
thanks @robcasloz , @TobiHartmann and @navyxliu for the reviews! 

/integrate

2023-02-17 14:26 UTC, closed without merging