JDK-8302129: Make MetaspaceReclaimPolicy a diagnostic switch
openjdk/jdk pull request #12540
Opened 2023-02-13 17:11 UTC by tstuefe

See associated CSR for background and motivation: https://bugs.openjdk.org/browse/JDK-8302130 .

This patch is technically trivial. CSR is approved.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change requires CSR request [JDK-8302130](https://bugs.openjdk.org/browse/JDK-8302130) to be approved

### Issues
 * [JDK-8302129](https://bugs.openjdk.org/browse/JDK-8302129): Make MetaspaceReclaimPolicy a diagnostic switch
 * [JDK-8302130](https://bugs.openjdk.org/browse/JDK-8302130): Make MetaspaceReclaimPolicy a diagnostic switch (**CSR**)

### Reviewers
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Coleen Phillimore](https://openjdk.org/census#coleenp) (@coleenp - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/12540/head:pull/12540` \
`$ git checkout pull/12540`

Update a local copy of the PR: \
`$ git checkout pull/12540` \
`$ git pull https://git.openjdk.org/jdk pull/12540/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12540`

View PR using the GUI difftool: \
`$ git pr show -t 12540`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/12540.diff">https://git.openjdk.org/jdk/pull/12540.diff</a>

</details>

2023-02-13 17:11 UTC, tstuefe commented
/csr needed

2023-02-14 07:00 UTC, dholmes-ora requested changes
There seem to be tests using this flag which do not unlock diagnostic options. IIRC debug VMs unlock by default but for product you will need to unlock explicitly.

Thanks.

2023-02-14 07:08 UTC, tstuefe commented
> There seem to be tests using this flag which do not unlock diagnostic options. IIRC debug VMs unlock by default but for product you will need to unlock explicitly.
> 
> Thanks.

Oh, good catch. I only tested debug locally, should have tested release too.

2023-02-14 16:40 UTC, coleenp approved these changes
Looks good!

2023-02-15 05:06 UTC, dholmes-ora approved these changes
Looks good. Thanks

2023-02-15 06:34 UTC, tstuefe commented
Thanks @coleenp and @dholmes-ora.

/integrate

2023-02-15 06:36 UTC, closed without merging