8297936: Use reachabilityFence to manage liveness in ClassUnload tests
openjdk/jdk pull request #12552
Opened 2023-02-14 09:02 UTC by afshin-zafari

### Description
Instead of using static instances or using an object in print to keep it alive, `java.lang.ref.Reference.reachabilityFence(Object)` is used to keep an object alive and avoid class unloading.

### Tests
linux-x64-debug, macosx-aarch64-debug, mach5 tier1-5

2023-02-14 16:42 UTC, coleenp requested changes
I know -Xcomp shows the problem but I don't really want these tests to be run by default with -Xcomp.  Can you remove Xcomp?

2023-02-15 06:17 UTC, dholmes-ora requested changes

2023-02-15 06:17 UTC, dholmes-ora commented on test/hotspot/jtreg/runtime/ClassUnload/KeepAliveObject.java
> +    Reference.reachabilityFence(o);
Please add comment:
```
// Don't let `o` get prematurely reclaimed by the GC.
```

2023-02-15 06:17 UTC, dholmes-ora commented on test/hotspot/jtreg/runtime/ClassUnload/UnloadTest.java
>      // Using a global static field to keep the object live in -Xcomp mode.
This comment needs deleting now.

2023-02-15 06:17 UTC, dholmes-ora commented on test/hotspot/jtreg/runtime/ClassUnload/UnloadTest.java
> +        Reference.reachabilityFence(o);
Again add a comment please.

2023-02-15 06:17 UTC, dholmes-ora commented on test/hotspot/jtreg/runtime/ClassUnload/UnloadTest.java
> +        Reference.reachabilityFence(o);
Again please add comment.

2023-02-15 06:17 UTC, dholmes-ora commented on test/hotspot/jtreg/runtime/ClassUnload/ConstantPoolDependsTest.java
> + * @run main/othervm -Xbootclasspath/a:. -Xmn8m -XX:+UnlockDiagnosticVMOptions -Xlog:class+unload -Xcomp -XX:+WhiteBoxAPI ConstantPoolDependsTest
As Coleen states, do not force the tests to run in Xcomp mode.

2023-02-16 09:22 UTC, afshin-zafari commented
> I know -Xcomp shows the problem but I don't really want these tests to be run by default with -Xcomp. Can you remove Xcomp?

done.

2023-02-17 02:22 UTC, dholmes-ora approved these changes
Updates look good. Thanks.

2023-03-02 09:19 UTC, afshin-zafari commented
/integrate

2023-03-03 16:42 UTC, JesperIRL commented
/sponsor

2023-03-03 16:44 UTC, calvinccheung commented
/sponsor

2023-03-03 16:44 UTC, closed without merging