8256424: Move ciSymbol::symbol_name() to ciSymbols::symbol_name()
openjdk/jdk pull request #1256
Opened 2020-11-17 12:53 UTC by cl4es

This moves ciSymbols mirrored from vmSymbols.hpp to a separate file, ciSymbols.hpp, to reduce includes throughout hotspot.

2020-12-07 20:28 UTC, vnkozlov approved these changes

2020-12-08 03:52 UTC, iklam requested changes

2020-12-08 03:52 UTC, iklam commented on src/hotspot/share/ci/bcEscapeAnalyzer.hpp
> +  void compute_escape_for_intrinsic(vmIntrinsicID iid);
I think the use of vmIntrinsics::ID in bcEscapeAnalyzer.cpp should also be changed to vmIntrinsicID for consistency, even though they are the same type. (The same for other hpp files such as ciMethod.hpp)

2020-12-08 03:52 UTC, iklam commented on src/hotspot/share/opto/library_call.cpp
> +#include "ci/ciSymbols.hpp"
This file doesn't seem to use the exports from ciSymbols.hpp.

2020-12-08 17:20 UTC, iklam approved these changes

2020-12-10 17:22 UTC, cl4es commented
/integrate

2020-12-10 17:22 UTC, closed without merging