Optimize DateTimeFormatterBuilder.ZoneTextPrinterParser.getTreee()
openjdk/jdk pull request #12612
Opened 2023-02-17 09:50 UTC by stsypanov

1) When `DateTimeFormatter` is reused we don't need to make a copy of `availableZoneIds` and allocate `nonRegionIds` as PrefixTree can be taken from cache. In the related benchmark allocation of `HashSet` takes ~93% of all time, so avoiding it should bring some improvement for cases when we reuse `DateTimeFormatter` to parse a string into `ZoneDateTime`
![image](https://user-images.githubusercontent.com/10835776/219609028-af48eae4-d326-4719-8366-c215baa85835.png)

2) `DateTimeFormatter` is mostly used with one locale, so `cachedTree` and `cachedTreeCI` can have predefined size.

2023-03-25 18:42 UTC, stsypanov commented
Benchmarking
```
make test TEST="micro:time.format.ZonedDateTimeFormatterBenchmark" MICRO="OPTIONS=-prof gc"

master

Benchmark                                                              Mode  Cnt      Score     Error   Units
ZonedDateTimeFormatterBenchmark.parse                                  avgt   20  13545.737 ± 451.164   ns/op
ZonedDateTimeFormatterBenchmark.parse:·gc.alloc.rate                   avgt   20   1713.579 ±  56.517  MB/sec
ZonedDateTimeFormatterBenchmark.parse:·gc.alloc.rate.norm              avgt   20  24320.006 ±   0.001    B/op
ZonedDateTimeFormatterBenchmark.parse:·gc.count                        avgt   20    110.000            counts
ZonedDateTimeFormatterBenchmark.parse:·gc.time                         avgt   20    514.000                ms


patch

Benchmark                                                              Mode  Cnt     Score    Error   Units
ZonedDateTimeFormatterBenchmark.parse                                  avgt   20  1276.063 ± 52.543   ns/op
ZonedDateTimeFormatterBenchmark.parse:·gc.alloc.rate                   avgt   20   622.223 ± 26.456  MB/sec
ZonedDateTimeFormatterBenchmark.parse:·gc.alloc.rate.norm              avgt   20   832.001 ±  0.001    B/op
ZonedDateTimeFormatterBenchmark.parse:·gc.count                        avgt   20    58.000           counts
ZonedDateTimeFormatterBenchmark.parse:·gc.time                         avgt   20   475.000               ms
```

2023-03-28 16:41 UTC, naotoj requested changes
Looks like a nice fix to me.

2023-03-28 16:41 UTC, naotoj commented on test/micro/org/openjdk/bench/java/time/format/ZonedDateTimeFormatterBenchmark.java
> +package time.format;
package should be `org.openjdk.bench.java.time.format`?

2023-03-29 16:22 UTC, naotoj approved these changes
LGTM

2023-03-29 18:29 UTC, naotoj commented
/sponsor

2023-03-29 18:32 UTC, closed without merging

2023-05-31 15:55 UTC, olivergillespie commented
/backport jdk17u-dev