8302870: More information needed from failures in vmTestbase ThreadUtils.waitThreadState
openjdk/jdk pull request #12661
Opened 2023-02-20 12:54 UTC by kevinjwalls

Test update to make failures such as JDK-8076494 more informative.

Waiting for a thread to change state: give more time (to distinguish a real deadlock from some other delay), and log the thread stackframes when the expected state change is not observed.

2023-02-20 22:36 UTC, dholmes-ora requested changes
Approach is fine in principle but a few minor nits.

Thanks.

2023-02-20 22:36 UTC, dholmes-ora commented on test/hotspot/jtreg/vmTestbase/nsk/monitoring/share/thread/ThreadUtils.java
> +        // Sleep time increased to help avoid spurious failures.
"increased" doesn't mean anything outside this PR as you can't tell the value has changed.

2023-02-20 22:36 UTC, dholmes-ora commented on test/hotspot/jtreg/vmTestbase/nsk/monitoring/share/thread/ThreadUtils.java
> +        // Sleep time increased to help avoid spurious failures.
Also any comment on sleep time belongs after line 233.

2023-02-20 22:36 UTC, dholmes-ora commented on test/hotspot/jtreg/vmTestbase/nsk/monitoring/share/thread/ThreadUtils.java
> +                long ctime2 = 0;
So ctime -> startTime; ctime2 -> elapsedTime ?

2023-02-20 22:36 UTC, dholmes-ora commented on test/hotspot/jtreg/vmTestbase/nsk/monitoring/share/thread/ThreadUtils.java
> +                            Thread.sleep(waitThreadStateSleepTime);
This file is using an indent of 8

2023-02-20 22:36 UTC, dholmes-ora commented on test/hotspot/jtreg/vmTestbase/nsk/monitoring/share/thread/ThreadUtils.java
> +                            // Failed to see desired state, give info to help diagnose the isuse.
This file is using an indent of 8. Looks odd to use 4 for the modified code only. Maybe you could fix all the indents before integration?

2023-02-21 09:14 UTC, kevinjwalls commented
OK thanks David, nits taken care of I think.  (I'm not falling for the trap of changing all the indenting so nobody can see from the diff what I'm changing here, so I suppressed my instincts and used 8 spaces.)

2023-02-21 23:52 UTC, dholmes-ora approved these changes
Update looks good - thanks.

I have no issue if you change the file indents after the PR is approved and then integrate - as it is only whitespace change. :)

2023-02-22 08:08 UTC, sspitsyn approved these changes
Looks good.
Thanks,
Serguei

2023-02-22 09:25 UTC, kevinjwalls commented
Thanks David and Serguei!
(leaving whitespace unification alone for now... 8-) )

2023-02-22 09:28 UTC, kevinjwalls commented
/integrate

2023-02-22 09:30 UTC, closed without merging