8300792: Refactor examples in java.net.http to use @snippet
openjdk/jdk pull request #12692
Opened 2023-02-21 15:53 UTC by DarraghClarke

Refactored instances of `@code` to instead use `@snippet`.

I also spent some time looking into using external snippets to reference the existing files `JavadocExamples` and `WebSocketExample` though ultimately thought it was better to keep the docs pretty much as they had been with only a few small changes to formatting.

2023-02-21 16:08 UTC, dfuch requested changes
Other places in the JDK are using:

```
{@snippet lang=java :
```

Since all our snippets are java code we may want to do that too.

2023-02-21 16:33 UTC, DarraghClarke commented
> Other places in the JDK are using:
> 
> ```
> {@snippet lang=java :
> ```
> 
> Since all our snippets are java code we may want to do that too.

I wouldn't mind changing it to specify, though I do think if no value is set it defaults to java, at least from reading the JEP thats what I thought

2023-02-21 16:44 UTC, dfuch commented
> I wouldn't mind changing it to specify, though I do think if no value is set it defaults to java, at least from reading the JEP thats what I thought

Good point. From [JEP 413](https://openjdk.org/jeps/413):

> Code fragments are typically Java source code, but they may also be fragments of properties files, source code in other languages, or plain text. A snippet may specify a lang attribute, which identifies the kind of content in the snippet. For an inline snippet, the default value is java.

2023-02-21 17:03 UTC, dfuch commented
Have you tried to `make docs`? I get compilation errors when I try...

2023-02-22 15:58 UTC, DarraghClarke commented
I checked this over vs the existing docs and made some small formatting changes while fixing those build errors from the last commit.

2023-02-22 18:21 UTC, dfuch commented on src/java.net.http/share/classes/java/net/http/HttpRequest.java
> +     *   // Request body from a String
Since this snippet contains three different individual example it would be better to have each example in its own snippet.

2023-02-22 18:22 UTC, dfuch commented on src/java.net.http/share/classes/java/net/http/HttpResponse.java
> +     * {@snippet :
Same remark here. It would make more sense to have each example in its own snippet.

2023-02-23 14:21 UTC, DarraghClarke commented
Thanks for pointing that out, I pushed that change there

2023-02-23 14:50 UTC, dfuch commented on src/java.net.http/share/classes/java/net/http/HttpResponse.java
> +     *   // Streams the response body to a File
Did you miss this one @DarraghClarke ?

2023-02-23 15:07 UTC, DarraghClarke commented on src/java.net.http/share/classes/java/net/http/HttpResponse.java
> +     *   // Streams the response body to a File
Sorry I did miss it, pushing that now

2023-02-23 16:16 UTC, dfuch approved these changes
LGTM. The API documentation with each example in its own snippet also looks better IMO.

2023-02-24 13:47 UTC, DarraghClarke commented
> LGTM. The API documentation with each example in its own snippet also looks better IMO.

I agree, thanks for suggesting that

2023-02-24 13:48 UTC, DarraghClarke commented
/integrate

2023-02-27 09:11 UTC, jaikiran approved these changes
Changes look good to me.

2023-02-27 09:16 UTC, jaikiran commented
/sponsor

2023-02-27 09:19 UTC, closed without merging