8303089: [jittester] Add time limit to IRTree generation
openjdk/jdk pull request #12722
Opened 2023-02-22 19:54 UTC by lepestock

Sometimes, the generation could take more than an hour and probably never stop. This PR adds a time limit (defaults to 10 minutes) to the generation of a single test.

2023-02-22 22:04 UTC, veresov approved these changes
Looks reasonable.

2023-02-23 09:53 UTC, lepestock commented
/integrate

2023-02-23 15:40 UTC, lmesnik requested changes

2023-02-23 19:34 UTC, lepestock commented on test/hotspot/jtreg/testlibrary/jittester/src/jdk/test/lib/jittester/Automatic.java
> +                    generatorThread.interrupt();
I didn't changed that code, and it is kind of misleading, yes. The limit I added concerns L124, the `generateIRTree` call. On the contrary, the InterruptedException you're looking for is captured in the `TestsGenerator`, methods `generateGoldenOut` and `compilePrinter` as well as in the `JavaCodeGenerator.compileJavaFile`.

2023-02-23 19:47 UTC, lmesnik approved these changes

2023-02-23 19:48 UTC, lmesnik commented
/sponsor

2023-02-23 19:51 UTC, closed without merging