8301684: Fix test code to not get finalizer deprecation warnings
openjdk/jdk pull request #12968
Opened 2023-03-10 08:23 UTC by afshin-zafari

To replace the finalizer use in the code, the `Cleaner` approach is used as stated in [Oracle doc on deprecated finalize() method](https://docs.oracle.com/javase/10/docs/api/java/lang/Object.html#finalize()).
Briefly:
1.  An instance of `Cleaner` (`java.lang.ref`) is created.
2. Using the `Cleaner`, an object is registered with a `Runnable` callback that is notified when the object is no longer reachable (GC'ed).
3. Write code in the callback to do other cleanings.
4. Or, use the `Cleanable` object which is returned from registration above and call its `clean` method to explicitly clean the object.

```java
Cleaner c = new Cleaner();
Cleanable cleanable = c.register(an_obj, a_runnable);
...
  //JVM notifies by calling the 
    a_runnable.run() {...}
... 
// possible to explicit cleaning 
cleanable.clean(an_obj); 
```

2023-03-10 12:49 UTC, coleenp reviewed
I don't know how cleaners work so here are some superficial comments.

2023-03-10 12:49 UTC, coleenp commented on test/hotspot/jtreg/vmTestbase/nsk/share/ClassUnloader.java
> +        // objbects to let them be created when new customClassLoader is created.
typo: objbects

2023-03-10 12:49 UTC, coleenp commented on test/hotspot/jtreg/vmTestbase/nsk/share/ClassUnloader.java
> +    private static class CustomClassLoaderCleaner implements Runnable{
nit: can you add a space before open { in these lines?
Also use // comments ?

2023-03-11 07:46 UTC, turbanoff commented on test/hotspot/jtreg/vmTestbase/nsk/share/ClassUnloader.java
> +            if(class_unloader != null){
```suggestion
            if (class_unloader != null){
```

2023-03-13 03:03 UTC, dholmes-ora requested changes
This does not look quite right me - see comments below. You need to know that the Custom loader has become unreachable and only then check the unloaded classes.

There are numerous references to finalization still in the code that should be updated to a more suitable form.

I think things can be simplified/streamlined somewhat.

Thanks

2023-03-15 05:16 UTC, dholmes-ora requested changes
This looks much simpler/cleaner - thanks!

Just a few nits with comments. Nice try with replacing "finalize" by "reclaim" but it doesn't quite work grammatically in the comments.

2023-03-15 05:16 UTC, dholmes-ora commented on test/hotspot/jtreg/vmTestbase/nsk/share/ClassUnloader.java
> + * <code>unloadClass()</code> method returns <i>false</i>.
All of the existing commentary in this test is somewhat lacking in terms of grammatical correctness, but we can at least make improvements to the new text. I suggest the following:
```
 * A class is eligible for unloading if its class loader has been reclaimed.
 * A Cleaner is used to inform the main test code when the class loader
 * becomes unreachable and is reclaimed.
 * If, after setting the class loader to null, no notification that it has become
 * reclaimed is received within the timeout interval, then the class is considered
 * to still be loaded and <code>unloadClass()</code> returns <i>false</i>.
```

2023-03-15 05:16 UTC, dholmes-ora commented on test/hotspot/jtreg/vmTestbase/nsk/share/ClassUnloader.java
> +     * Whole amount of time in milliseconds to wait for class loader reclaim.
s/reclaim/to be reclaimed/

2023-03-15 05:16 UTC, dholmes-ora commented on test/hotspot/jtreg/vmTestbase/nsk/share/ClassUnloader.java
> +     * Piece of time in milliseconds to wait in a loop for class loader reclaim.
Suggestion:
```
* Sleep time in milliseconds for the loop waiting for the class loader to be reclaimed.
* ```

2023-03-15 05:16 UTC, dholmes-ora commented on test/hotspot/jtreg/vmTestbase/nsk/share/ClassUnloader.java
> +     * Has class loader been is_reclaimed or not.
s/is_reclaimed/reclaimed/

2023-03-15 05:16 UTC, dholmes-ora commented on test/hotspot/jtreg/vmTestbase/nsk/share/ClassUnloader.java
> +        // When customClassLoader becomes unreachable, the lambda is called by JVM/GC.
Suggestion:
```
// Register a Cleaner to inform us when the class loader has been reclaimed.
```

2023-03-15 05:16 UTC, dholmes-ora commented on test/hotspot/jtreg/vmTestbase/nsk/share/ClassUnloader.java
> +        // When customClassLoader becomes unreachable, the lambda is called by JVM/GC.
Suggestion:
```
// Register a Cleaner to inform us when the class loader has been reclaimed.
```

2023-03-15 05:16 UTC, dholmes-ora commented on test/hotspot/jtreg/vmTestbase/nsk/share/ClassUnloader.java
> +        // class loader has not been is_reclaimed
s/is_reclaimed/reclaimed/

2023-03-15 10:15 UTC, afshin-zafari commented
> This looks much simpler/cleaner - thanks!
> 
> Just a few nits with comments. Nice try with replacing "finalize" by "reclaim" but it doesn't quite work grammatically in the comments.

Thanks for your comments, and thank you also for being patient with my naive mistakes.

2023-03-15 16:07 UTC, coleenp approved these changes
This looks great.

2023-03-16 06:05 UTC, dholmes-ora approved these changes
Looks good. Thanks for fixing this.

2023-03-17 08:50 UTC, afshin-zafari commented
Thanks for reviewing this PR.
/integrate

2023-03-17 13:19 UTC, coleenp commented
/sponsor

2023-03-17 13:22 UTC, closed without merging