8304144: G1: Remove unnecessary is_survivor check in G1ClearCardTableTask
openjdk/jdk pull request #13023
Opened 2023-03-14 15:02 UTC by albertnetymk

Simple removing redundant check.

Test: tier1-6

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8304144](https://bugs.openjdk.org/browse/JDK-8304144): G1: Remove unnecessary is_survivor check in G1ClearCardTableTask

### Reviewers
 * [Thomas Schatzl](https://openjdk.org/census#tschatzl) (@tschatzl - **Reviewer**)
 * [Y. Srinivas Ramakrishna](https://openjdk.org/census#ysr) (@ysramakrishna - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13023/head:pull/13023` \
`$ git checkout pull/13023`

Update a local copy of the PR: \
`$ git checkout pull/13023` \
`$ git pull https://git.openjdk.org/jdk.git pull/13023/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13023`

View PR using the GUI difftool: \
`$ git pr show -t 13023`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13023.diff">https://git.openjdk.org/jdk/pull/13023.diff</a>

</details>

2023-03-14 16:32 UTC, tschatzl approved these changes
Lgtm.

2023-03-15 16:41 UTC, tschatzl requested changes
Actually, after some re-reading of code this check is an optimization that should be kept.

The checks make sure to leave the `young` marks on the card table that were written when allocating a PLAB in survivor region (see `G1Allocator::survivor_attempt_allocation`).

I would request to either add a comment here or do not add survivor regions to the `_all_dirty_regions` somewhere else.

2023-03-15 18:09 UTC, tschatzl approved these changes
Actually, I am revising my review again; survivor regions should not be in the `all_dirty_regions` list at all. Survivor regions are completely new regions allocated during gc.
I can't find code that would add them either.

2023-03-15 21:36 UTC, ysramakrishna requested changes
@tschatzl & @albertnetymk : 

I'd suggest adding an assert that the region for which cards are being cleared is not a survivor region, with a comment to that effect. That would safely take care of both of your intentions/comments here.

Otherwise looks good.

2023-03-18 06:03 UTC, ysramakrishna commented
@albertnetymk : 

I am not sure if this is stil relevant today or is a fragment of code that has outlived its usefulness (I must confess I have not looked closely at or kept up with G1's evolution, especially wrt concurrent refinement, over the last few years, but note that @tschatzl must have been thinking of the allocation in survivor regions that dirties the backing cards using the following API):

```
  // It dirties the cards that cover the block so that the post
  // write barrier never queues anything when updating objects on this
  // block. It is assumed (and in fact we assert) that the block
  // belongs to a young region.
  inline void dirty_young_block(HeapWord* start, size_t word_size);
```

You should check what the post-write barrier does today before it enqueues dirty pointers. Hence the comment about not clearing cards for survivor (or young) regions.

2023-03-20 11:14 UTC, albertnetymk commented
"dirty" in "dirty_young_block" can be misleading. It's like "annotation" as it essentially calls `g1_mark_as_young`, which ensures writes to young-gen doesn't trigger the barrier slow path (e.g. `G1BarrierSet::write_ref_field_post`).

In other places, "dirty" has a reserved meaning that the heap mem range for a dirty card potentially contains an old-to-young pointer that must be scanned.

It's probably better to rename this method to sth less misleading in another PR.

2023-03-20 23:55 UTC, ysramakrishna commented
> "dirty" in "dirty_young_block" can be misleading. It's like "annotation" as it essentially calls `g1_mark_as_young`, which ensures writes to young-gen doesn't trigger the barrier slow path (e.g. `G1BarrierSet::write_ref_field_post`).
> 
> In other places, "dirty" has a reserved meaning that the heap mem range for a dirty card potentially contains an old-to-young pointer that must be scanned.
> 
> It's probably better to rename this method to sth less misleading in another PR.

I don't know about renaming, but `clean` / `clear` seems to be unequivocal in its intentions and actions:

```
void HeapRegion::clear_cardtable() {
  G1CardTable* ct = G1CollectedHeap::heap()->card_table();
  ct->clear(MemRegion(bottom(), end()));
}
```
and which seems to eventually bottom out in:
```
void CardTable::clear_MemRegion(MemRegion mr) {
  // Be conservative: only clean cards entirely contained within the
  // region.
  CardValue* cur;
  if (mr.start() == _whole_heap.start()) {
    cur = byte_for(mr.start());
  } else {
    assert(mr.start() > _whole_heap.start(), "mr is not covered.");
    cur = byte_after(mr.start() - 1);
  }
  CardValue* last = byte_after(mr.last());
  memset(cur, clean_card, pointer_delta(last, cur, sizeof(CardValue)));
}
```

But clearing (i.e. marking card clean) today, from my cursory reading of the code, over-writes the `g1_young_gen` value, because:

```
    g1_young_gen = CT_MR_BS_last_reserved << 1,
```
(etc.)

(i.e. the value `0x10` see below)
while:

```
  enum CardValues {
    clean_card                  = (CardValue)-1,

    dirty_card                  =  0,
    CT_MR_BS_last_reserved      =  1
  };
```

I didn't check the pointer update enqueueing code to see if what it was doing though. And don't know if this materially affects performance, but may be @tschatzl or someone more familiar with G1's recent evolution might know.

2023-03-21 00:18 UTC, ysramakrishna approved these changes
Reviewed modulo comment above about why I think the assert still makes sense.

2023-03-21 08:12 UTC, albertnetymk commented
> But clearing (i.e. marking card clean) today, from my cursory reading of the code, over-writes the `g1_young_gen` value,

That's correct. Nevertheless, lacking further context, it's impossible to determine whether the mentioned overwrite is appropriate or not. For example in this PR, one doesn't know why the current region can or cannot be a survior-region in the local context.

The class in which this occurs goes by the name of "G1ClearCardTableTask", so it's logical to utilize a method named "clear_cardtable", without requiring broader knowledge.

However, having said that, when considering global knowledge, we do know that regions in cset will arrive at this point, and if a freed region later becomes an eden-region, cards are annotated with `g1_young_gen` as allocation grows inside that region -- rendering the clearing in `G1ClearCardTableTask` redundant. Possibly, this redundancy (and potentially other factors) can use some refactoring here, which probably uncovers a more reasonable location for a region-type related assertion.

2023-03-21 10:57 UTC, tschatzl commented
> > But clearing (i.e. marking card clean) today, from my cursory reading of the code, over-writes the `g1_young_gen` value,
> 
> That's correct. Nevertheless, lacking further context, it's impossible to determine whether the mentioned overwrite is appropriate or not. For example in this PR, one doesn't know why the current region can or cannot be a survior-region in the local context.
> 
> The class in which this occurs goes by the name of "G1ClearCardTableTask", so it's logical to utilize a method named "clear_cardtable", without requiring broader knowledge.

Not sure whether an `assert`, which is what we are discussing, needs broader knowledge to be justified. But we've already confirmed that survivor regions can't show up here, so I am fine as is.

> 
> However, having said that, when considering global knowledge, we do know that regions in cset will arrive at this point, and if a freed region later becomes an eden-region, cards are annotated with `g1_young_gen` as allocation grows inside that region -- rendering the clearing in `G1ClearCardTableTask` redundant. Possibly, this redundancy (and potentially other factors) can use some refactoring here, which probably uncovers a more reasonable location for a region-type related assertion.

One option could be checking that the region type is appropriate when adding to that list.

There have been prototypes to lazily clear these values [JDK-8227174](https://bugs.openjdk.org/browse/JDK-8227174), but temporarily abandoned. The memory ordering concerns mentioned there may not be an issue with currently supported architectures any more. I can see if I can dig up the patch from somewhere if wanted.

Orthogonal from that we want to get rid of the `g1_young_card_val` value completely which is just an optimization [JDK-8226731](https://bugs.openjdk.org/browse/JDK-8226731).

2023-03-21 22:35 UTC, ysramakrishna commented
I agree, some refactoring/cleanups etc. along with the changes you pointed out above might be worthwhile in the fullness of time, or would be moot if/when `g1_younger_gen_val` and surrounding code were to go away. Thanks for the extra background and the discussion and, yes, this looks fine to me in any case with or without the assert, just to bring the review/discussion to a conclusion from my end :-)

2023-03-22 10:10 UTC, albertnetymk commented
Thanks for the review.

/integrate

2023-03-22 10:12 UTC, closed without merging