8256585: Remove in-place conversion vector operators from Vector API
openjdk/jdk pull request #1305
Opened 2020-11-19 03:26 UTC by sviswa7

Remove partially implemented in-place conversion vector operators from Vector API:
   ofNarrowing, ofWidening, INPLACE_XXX

2020-11-19 03:28 UTC, sviswa7 commented
/label core-libs

2020-11-19 03:29 UTC, sviswa7 commented
/label hotspot

2020-11-19 06:23 UTC, jddarcy commented
/csr needed

2020-11-19 17:18 UTC, PaulSandoz requested changes
The documentation `Vector.convert` and `Vector.convertShape` needs to be updated to remove specification of in-place conversions, as does the class documentation on `Vector`. A search for the term `in-place` should find the relevant locations.

2020-11-19 19:47 UTC, sviswa7 commented
Updated documentation to reflect removal of widening and contracting in-place conversions.

2020-11-19 21:22 UTC, PaulSandoz approved these changes

2020-11-23 18:47 UTC, sviswa7 commented
/integrate

2020-11-23 18:48 UTC, closed without merging