8304412
openjdk/jdk pull request #13076
Opened 2023-03-17 13:51 UTC by albertnetymk

Simple refactoring to use more informative names/comments.

Test: tier1-6

2023-03-23 13:13 UTC, tschatzl requested changes

2023-03-24 12:34 UTC, tschatzl approved these changes
lgtm. Please consider moving the comment.

2023-03-24 12:34 UTC, tschatzl commented on src/hotspot/share/gc/serial/genMarkSweep.cpp
> +  // conservatively not loose any old-to-young pointer.
I was actually thinking of putting this into the hpp file at the declaration of the method.

2023-03-27 08:18 UTC, tschatzl approved these changes
Thanks!

2023-03-28 06:04 UTC, kimbarrett approved these changes
Looks good.

2023-03-28 07:22 UTC, albertnetymk commented
Thanks for the review.

/integrate

2023-03-28 07:24 UTC, closed without merging