JDK-8304028: Port fdlibm IEEEremainder to Java
openjdk/jdk pull request #13113
Opened 2023-03-21 06:11 UTC by jddarcy

Last but not least, a port of fdlibm IEEEremainder from C to Java. I plan to write some more implementation-specific tests around decision points in the FDLIBM algorithm, but I wanted to get the bulk of the changes out for review first.

Note that since IEEEremainder was the last native method in StrictMath.java, the StrictMath.c file needed to be deleted (or modified) since StrictMath.h was no longer generated as part of the build. (StrictMath.c was one of the file deleted as part of JDK-8302801).

For testing, Mach 5 tier 1 through 3 were successful (other than an unrelated test failure that was problem listed) and the exhaustive test was locally run and passed with "16, 16" to increase the testing density.

2023-03-21 06:13 UTC, jddarcy commented
Diffs to aid review:

```
$ diff -w Remainder.c Remainder.translit.java 
1,25c1,6
< /* __ieee754_remainder(x,p)
<  * Return :
<  *      returns  x REM p  =  x - [x/p]*p as if in infinite
<  *      precise arithmetic, where [x/p] is the (infinite bit)
<  *      integer nearest x/p (in half way case choose the even one).
<  * Method :
<  *      Based on fmod() return x-[x/p]chopped*p exactlp.
<  */
< 
< #include "fdlibm.h"
< 
< #ifdef __STDC__
< static const double zero = 0.0;
< #else
< static double zero = 0.0;
< #endif
< 
< 
< #ifdef __STDC__
<         double __ieee754_remainder(double x, double p)
< #else
<         double __ieee754_remainder(x,p)
<         double x,p;
< #endif
< {
---
>     private static final class IEEEremainder {
>         private static final double zero = 0.0;
>         private static double one = 1.0;
>         private static double[] Zero = {0.0, -0.0,};
> 
>         static double compute(double x, double p) {
27c8
<         unsigned sx,lx,lp;
---
>             /*unsigned*/ int sx,lx,lp;
48,49c29,30
<         x  = fabs(x);
<         p  = fabs(p);
---
>             x  = Math.abs(x);
>             p  = Math.abs(p);
62c43,44
<         __HI(x) ^= sx;
---
>             // __HI(x) ^= sx;
>             x = __HI(x, __HI(x)^sx);
65,85c47,48
< /*
<  * __ieee754_fmod(x,y)
<  * Return x mod y in exact arithmetic
<  * Method: shift and subtract
<  */
< 
< #include "fdlibm.h"
< 
< #ifdef __STDC__
< static const double one = 1.0, Zero[] = {0.0, -0.0,};
< #else
< static double one = 1.0, Zero[] = {0.0, -0.0,};
< #endif
< 
< #ifdef __STDC__
<         double __ieee754_fmod(double x, double y)
< #else
<         double __ieee754_fmod(x,y)
<         double x,y ;
< #endif
< {
---
> 
>         private static double __ieee754_fmod(double x, double y) {
87c50
<         unsigned lx,ly,lz;
---
>             /*unsigned*/ int lx,ly,lz;
102c65,66
<             if((hx<hy)||(lx<ly)) return x;      /* |x|<|y| return x */
---
>                 // if((hx<hy)||(lx<ly)) return x;      /* |x|<|y| return x */
>                 if((hx<hy)||(Integer.compareUnsigned(lx,ly) < 0))  return x;  /* |x|<|y| return x */
104c68
<                 return Zero[(unsigned)sx>>31];  /* |x|=|y| return x*0*/
---
>                     return Zero[/*(unsigned)*/sx>>>31];  /* |x|=|y| return x*0*/ // unsigned shift
131c95
<                 hx = (hx<<n)|(lx>>(32-n));
---
>                     hx = (hx<<n)|(lx >>> (32-n)); // unsigned shift
143c107
<                 hy = (hy<<n)|(ly>>(32-n));
---
>                     hy = (hy<<n)|(ly >>> (32-n)); // unsigned shift
153,155c117,121
<         while(n--) {
<             hz=hx-hy;lz=lx-ly; if(lx<ly) hz -= 1;
<             if(hz<0){hx = hx+hx+(lx>>31); lx = lx+lx;}
---
>             while(n-- != 0) {
>                 hz=hx-hy;lz=lx-ly;
>                 // if(lx<ly) hz -= 1;
>                 if(Integer.compareUnsigned(lx, ly) < 0) hz -= 1;
>                 if(hz<0){hx = hx+hx+(lx >>> 31); lx = lx+lx;} // unsigned shift
158,159c124,126
<                     return Zero[(unsigned)sx>>31];
<                 hx = hz+hz+(lz>>31); lx = lz+lz;
---
>                         return Zero[/*(unsigned)*/sx>>>31]; // unsigned shift
>                     hx = hz+hz+(lz >>> 31); // unsigned shift
>                     lx = lz+lz;
162c129,131
<         hz=hx-hy;lz=lx-ly; if(lx<ly) hz -= 1;
---
>             hz=hx-hy;lz=lx-ly;
>             // if(lx<ly) hz -= 1;
>             if(Integer.compareUnsigned(lx, ly) < 0) hz -= 1;
167c136
<             return Zero[(unsigned)sx>>31];
---
>                 return Zero[/*(unsigned)*/sx >>> 31]; // unsigned shift
169c138
<             hx = hx+hx+(lx>>31); lx = lx+lx;
---
>                 hx = hx+hx+(lx >>> 31); lx = lx+lx; // unsigned shift
174,175c143,146
<             __HI(x) = hx|sx;
<             __LO(x) = lx;
---
>                 // __HI(x) = hx|sx;
>                 x = __HI(x, hx|sx);
>                 // __LO(x) = lx;
>                 x = __LO(x, lx);
179c150
<                 lx = (lx>>n)|((unsigned)hx<<(32-n));
---
>                     lx = (lx >>> n)|(/*(unsigned)*/hx<<(32-n)); // unsigned shift
182c153,154
<                 lx = (hx<<(32-n))|(lx>>n); hx = sx;
---
>                     lx = (hx<<(32-n))|(lx >>> n); // unsigned shift
>                     hx = sx;
186,187c158,161
<             __HI(x) = hx|sx;
<             __LO(x) = lx;
---
>                 // __HI(x) = hx|sx;
>                 x = __HI(x, hx|sx);
>                 // __LO(x) = lx;
>                 x = __LO(x, lx);
191a166
>     }
```

$```
 diff -w Remainder.translit.java  Remainder.fdlibm.java 
1,4c1,2
<     private static final class IEEEremainder {
<         private static final double zero = 0.0;
<         private static double one = 1.0;
<         private static double[] Zero = {0.0, -0.0,};
---
>     static final class IEEEremainder {
>         private IEEEremainder() {throw new UnsupportedOperationException();}
11,24c9,15
<             hx = __HI(x);           /* high word of x */
<             lx = __LO(x);           /* low  word of x */
<             hp = __HI(p);           /* high word of p */
<             lp = __LO(p);           /* low  word of p */
<             sx = hx&0x80000000;
<             hp &= 0x7fffffff;
<             hx &= 0x7fffffff;
< 
<             /* purge off exception values */
<             if((hp|lp)==0) return (x*p)/(x*p);      /* p = 0 */
<             if((hx>=0x7ff00000)||                   /* x not finite */
<                ((hp>=0x7ff00000)&&                   /* p is NaN */
<                 (((hp-0x7ff00000)|lp)!=0)))
<                 return (x*p)/(x*p);
---
>             hx = __HI(x);           // high word of x
>             lx = __LO(x);           // low  word of x
>             hp = __HI(p);           // high word of p
>             lp = __LO(p);           // low  word of p
>             sx = hx & 0x8000_0000;
>             hp &= 0x7fff_ffff;
>             hx &= 0x7fff_ffff;
25a17,24
>             // purge off exception values
>             if ((hp | lp) == 0) {// p = 0
>                 return (x*p)/(x*p);
>             }
>             if ((hx >= 0x7ff0_0000) ||                   // not finite
>                 ((hp >= 0x7ff0_0000) &&                   // p is NaN
>                  (((hp - 0x7ff0_0000) | lp) != 0)))
>                 return (x*p)/(x*p);
27,28c26,31
<             if (hp<=0x7fdfffff) x = __ieee754_fmod(x,p+p);  /* now x < 2p */
<             if (((hx-hp)|(lx-lp))==0) return zero*x;
---
>             if (hp <= 0x7fdf_ffff) {  // now x < 2p
>                 x = __ieee754_fmod(x, p + p);
>             }
>             if (((hx - hp) | (lx - lp)) == 0) {
>                 return 0.0*x;
>             }
31c34
<             if (hp<0x00200000) {
---
>             if (hp < 0x0020_0000) {
34c37,39
<                     if(x+x>=p) x -= p;
---
>                     if (x + x >= p) {
>                         x -= p;
>                     }
40c45,47
<                     if(x>=p_half) x -= p;
---
>                     if (x >= p_half) {
>                         x -= p;
>                     }
43d49
<             // __HI(x) ^= sx;
49c55
<             int n,hx,hy,hz,ix,iy,sx,i;
---
>             int n, hx, hy, hz, ix, iy, sx;
52,62c58,68
<             hx = __HI(x);           /* high word of x */
<             lx = __LO(x);           /* low  word of x */
<             hy = __HI(y);           /* high word of y */
<             ly = __LO(y);           /* low  word of y */
<             sx = hx&0x80000000;             /* sign of x */
<             hx ^=sx;                /* |x| */
<             hy &= 0x7fffffff;       /* |y| */
< 
<             /* purge off exception values */
<             if((hy|ly)==0||(hx>=0x7ff00000)||       /* y=0,or x not finite */
<                ((hy|((ly|-ly)>>31))>0x7ff00000))     /* or y is NaN */
---
>             hx = __HI(x);           // high word of x
>             lx = __LO(x);           // low  word of x
>             hy = __HI(y);           // high word [...]

2023-03-21 11:41 UTC, turbanoff commented on src/java.base/share/classes/java/lang/FdLibm.java
> +            if(iy >= -1022)
```suggestion
            if (iy >= -1022)
```

2023-03-21 11:42 UTC, turbanoff commented on src/java.base/share/classes/java/lang/FdLibm.java
> +            while(n-- != 0) {
```suggestion
            while (n-- != 0) {
```

2023-03-22 09:07 UTC, turbanoff requested changes

2023-03-29 04:10 UTC, jddarcy commented on test/jdk/java/lang/StrictMath/FdlibmTranslit.java
> +               ((hy|((ly|-ly)>>31))>0x7ff00000))     /* or y is NaN */
Updated to latest push in both FdlibmTranslit and Fdlibm; thanks,

2023-03-31 16:13 UTC, rgiulietti commented
Last commit LGTM

2023-03-31 18:58 UTC, bplb approved these changes
LGTM2

2023-03-31 19:24 UTC, bplb approved these changes

2023-03-31 19:46 UTC, jddarcy commented
/integrate

2023-03-31 19:48 UTC, closed without merging