8297539: Use PrimitiveConversions::cast for local uses of the int<->float union conversion trick
openjdk/jdk pull request #13136
Opened 2023-03-22 10:59 UTC by afshin-zafari

**Only** the instances of using `union` for converting `int` to `float` are replaced with call to `PrimitiveConversions::cast<To>(From)` method. The instances where the union contains other types of fields than `int` and `float` are left unchanged.

2023-03-27 14:17 UTC, coleenp approved these changes
Looks good.  There are a couple of minor include file ordering things to fix.

2023-03-27 14:17 UTC, coleenp commented on src/hotspot/cpu/aarch64/assembler_aarch64.cpp
> +#include "metaprogramming/primitiveConversions.hpp"
This needs to be after immediate_aarch64.hpp (alphabetical order).

2023-03-27 14:17 UTC, coleenp commented on src/hotspot/cpu/aarch64/immediate_aarch64.cpp
> +#include "metaprogramming/primitiveConversions.hpp"
pre-existing, immediate_aarch64.hpp should be above this include.

2023-03-27 21:43 UTC, kimbarrett requested changes
Overall this looks good.  Just a few minor nits and naming issues.

2023-03-27 21:43 UTC, kimbarrett commented on src/hotspot/cpu/aarch64/assembler_aarch64.cpp
> +  unsigned ival;
I'd like this to be initialized rather than assigned on the next line.

2023-03-27 21:43 UTC, kimbarrett commented on src/hotspot/cpu/arm/assembler_arm.hpp
> +    virtual unsigned int s() const { return _num_bits >> 31; }
These should be override rather than virtual.  Similarly for double_num.

2023-03-27 21:43 UTC, kimbarrett commented on src/hotspot/cpu/arm/assembler_arm.hpp
> +    unsigned int _num_bits;
The name _num_bits is confusing; I spent a few moments trying to figure out what it was the number
of bits of.  I think just _bits or _raw_bits or something like that would be better.  Similarly in double_num.
I also think the class names would be better with "num" => "bits", but that likely has fannout, so maybe
later (if at all).

2023-03-27 21:43 UTC, kimbarrett commented on src/hotspot/cpu/arm/macroAssembler_arm.cpp
> +  jint accessor_i = PrimitiveConversions::cast<jint>(c);
I don't think the "accessor_" prefix has any meaning with this change, and just seems odd.
Just call the variable "bits" or "float_bits" or something like that?

2023-03-27 21:43 UTC, kimbarrett commented on src/hotspot/share/runtime/sharedRuntime.cpp
> +  juint ybits_i = PrimitiveConversions::cast<juint>(y);
The "_i" suffix here doesn't have any meaning anymore.  Just "xbits" and "ybits" would be better.
Similarly in below in "drem".

2023-03-28 15:27 UTC, kimbarrett requested changes

2023-03-31 05:11 UTC, dholmes-ora reviewed
Seems okay other than the override issue.

Thanks.

2023-03-31 14:13 UTC, afshin-zafari commented on src/hotspot/cpu/arm/assembler_arm.hpp
> +    override unsigned int s() const { return _bits >> 31; }
I fixed it.

2023-03-31 16:21 UTC, kimbarrett approved these changes
Looks good.

2023-04-01 01:00 UTC, dholmes-ora approved these changes

2023-04-01 01:00 UTC, dholmes-ora commented
/sponsor

2023-04-01 01:02 UTC, closed without merging