8304069: ClassFileParser has ad-hoc hashtables
openjdk/jdk pull request #13141
Opened 2023-03-22 14:56 UTC by matias9927

The ClassFileParser has ad-hoc hash tables for checking for duplicate names for fields, methods and interfaces. ResourceHashtable will now be used instead. Verified with tier1-4 tests.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8304069](https://bugs.openjdk.org/browse/JDK-8304069): ClassFileParser has ad-hoc hashtables

### Reviewers
 * [Coleen Phillimore](https://openjdk.org/census#coleenp) (@coleenp - **Reviewer**)
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13141/head:pull/13141` \
`$ git checkout pull/13141`

Update a local copy of the PR: \
`$ git checkout pull/13141` \
`$ git pull https://git.openjdk.org/jdk.git pull/13141/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13141`

View PR using the GUI difftool: \
`$ git pr show -t 13141`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13141.diff">https://git.openjdk.org/jdk/pull/13141.diff</a>

</details>

2023-03-22 18:02 UTC, coleenp requested changes
I have some suggestions for improving this.

2023-03-22 18:02 UTC, coleenp commented on src/hotspot/share/classfile/classFileParser.cpp
> +        interface_name = new NameSigHash();
You could use a local NameSigHash and copy for the values like:
  name_sig_hash = NameSigHash(k->name(), nullptr);
Then the hashtable key could be a non-pointer, saving a pointer per entry and may be more efficient.

2023-03-22 21:31 UTC, coleenp approved these changes
This looks great.

2023-03-23 06:29 UTC, dholmes-ora reviewed
This conversion looks good but I was confused by the way the original code was doing things. Once we have this conversion I think we could clean things up further:

1. Interfaces don't need `NameSigHash`, all we need is a map of names, so we should be able to directly have a RHT of `Symbol*` for the `interface_name_table`.
2. `NameSigHash` is the wrong terminology - we are checking names and descriptors [JVMS 4.3], not names and signatures [JVMS4.7.9.1]! (And a Java Language "signature" is something different again [JLS 8.4.2]!

Unfortunately I think we misuse "signature" throughout the VM, so maybe fixing it here will serve little purpose.

2023-03-23 18:50 UTC, coleenp requested changes
Every cleanup suggests more cleanups.

2023-03-23 21:46 UTC, coleenp approved these changes
Looks good to me!

2023-03-23 22:11 UTC, dholmes-ora approved these changes
Looks good! Thanks for the additional cleanups/simplifications.

2023-03-24 15:42 UTC, coleenp commented
/sponsor

2023-03-24 15:45 UTC, closed without merging