8304912
openjdk/jdk pull request #13213
Opened 2023-03-28 17:59 UTC by RogerRiggs

Update classes in the java.desktop module to use the jdk.internal.util.OperatingSystem enum instead of the `os.name` system property to select OS specific behaviors.

2023-03-28 19:44 UTC, turbanoff commented
sun.awt.OSInfo could be cleanup up:
1. sun.awt.OSInfo#getOSTypeAction - is unused now
2. sun.awt.OSInfo#getOSType could use `OperatingSystem` method instead of relying of sun.awt.OSInfo#OS_NAME property

2023-03-28 20:04 UTC, RogerRiggs commented
> * sun.awt.OSInfo#getOSTypeAction - is unused now
> 
> * sun.awt.OSInfo#getOSType could use `OperatingSystem` method instead of relying of sun.awt.OSInfo#OS_NAME property. It seems it's used only in one place - sun.awt.X11.MotifColorUtilities#loadSystemColorsForCDE

OSInfo.getOSType() is used by some tests; those references will need to be remediated.

2023-03-31 06:44 UTC, turbanoff commented
Let's at least update `sun.awt.X11.MotifColorUtilities#loadSystemColorsForCDE`
https://github.com/openjdk/jdk/blob/master/src/java.desktop/unix/classes/sun/awt/X11/MotifColorUtilities.java#L440

2023-04-04 17:04 UTC, bplb approved these changes
Looks fine modulo any cleanup to be performed subsequently.

2023-04-04 19:37 UTC, RogerRiggs commented
> Looks fine modulo any cleanup to be performed subsequently.

Tracked with [JDK-8305606](https://bugs.openjdk.org/browse/JDK-8305606)

2023-04-04 21:46 UTC, turbanoff commented on src/java.desktop/share/classes/sun/font/FontUtilities.java
> +                isMacOSX = OperatingSystem.isMacOS(); // TODO: MacOSX
I think this `TODO` is not actual anymore

2023-04-04 21:55 UTC, turbanoff commented
Found another couple of places:

https://github.com/openjdk/jdk/blob/7cf24d1c06142a3bab9cce5cd0ba34b8bbccf00f/src/java.desktop/unix/classes/sun/awt/X11/MotifColorUtilities.java#L641
https://github.com/openjdk/jdk/blob/7cf24d1c06142a3bab9cce5cd0ba34b8bbccf00f/src/java.desktop/unix/classes/sun/awt/X11/XScrollbarPeer.java#L78

2023-04-07 01:45 UTC, prrace commented
So if we want to get rid of all the getProperty (etc) calls and unify it then  the way I'd prefer to do this is via a single channel inside the desktop module.
So change everything to use that pre-existing sun.awt.OSInfo class.
Modifying that as necessary. Then that class can be the SINGLE place that has a direct dependency on this java.base internal and we can more easily drop it if required.
Meanwhile I also think there's a better than 50:50 chance someone will add new uses of System.getProperty .. whatever the solution is. So whack-a-mole-away.

2023-04-08 03:51 UTC, prrace requested changes

2023-04-08 03:51 UTC, prrace commented on src/java.desktop/share/classes/sun/awt/shell/ShellFolder.java
> + * Copyright (c) 2000, 2023, Oracle and/or its affiliates. All rights reserved.
no changes so revert (c) year

2023-04-08 03:51 UTC, prrace commented on src/java.desktop/share/classes/sun/swing/WindowsPlacesBar.java
> + * Copyright (c) 2003, 2023, Oracle and/or its affiliates. All rights reserved.
no changes so revert (c) year

2023-04-08 03:51 UTC, prrace commented on src/java.desktop/unix/classes/sun/font/FcFontConfiguration.java
> + * Copyright (c) 2008, 2023, Oracle and/or its affiliates. All rights reserved.
no changes so revert (c) year

2023-04-08 03:51 UTC, prrace commented on src/java.desktop/windows/classes/com/sun/java/swing/plaf/windows/WindowsLookAndFeel.java
> + * Copyright (c) 1997, 2023, Oracle and/or its affiliates. All rights reserved.
no changes so revert (c) year

2023-04-08 08:24 UTC, turbanoff commented on src/java.desktop/share/classes/sun/awt/OSInfo.java
`sun.awt.OSInfo#OS_NAME` is now unused

2023-04-08 20:25 UTC, prrace commented on src/java.desktop/share/classes/sun/awt/OSInfo.java
>      public static final WindowsVersion WINDOWS_7 = new WindowsVersion(6, 1);
The  windows version map looks like it hasn't had any love in a long time.
Updating it is VERY out of scope for this fix as it needs some thought in whether to remove old entries
and what to do about replacing them so I filed https://bugs.openjdk.org/browse/JDK-8305777

2023-04-10 16:08 UTC, turbanoff commented on src/java.desktop/windows/classes/com/sun/java/swing/plaf/windows/WindowsLookAndFeel.java
> + * Copyright (c) 1997, 2023, Oracle and/or its affiliates. All rights reserved.
@RogerRiggs missed this one

2023-04-11 06:54 UTC, turbanoff commented on src/java.desktop/share/classes/sun/awt/OSInfo.java
>      private static final PrivilegedAction<OSType> osTypeAction = new PrivilegedAction<OSType>() {
As this field is not used in production code anymore, I think it makes sense to inline it (allocate directly in `sun.awt.OSInfo#getOSTypeAction`)

2023-04-11 17:05 UTC, turbanoff approved these changes

2023-04-13 20:16 UTC, RogerRiggs commented
@prrace Please review

2023-04-13 20:35 UTC, prrace approved these changes

2023-04-13 20:38 UTC, Glavo commented on src/java.desktop/share/classes/sun/awt/OSInfo.java
>  import java.security.PrivilegedAction;
These imports are no longer used.

2023-04-14 15:29 UTC, Glavo approved these changes
It looks great.

2023-04-14 16:41 UTC, RogerRiggs commented
/integrate

2023-04-14 16:42 UTC, closed without merging