8305084: Remove finalize() from test/hotspot/jtreg/serviceability/dcmd/gc/ that are used in serviceability/dcmd/gc/
openjdk/jdk pull request #13423
Opened 2023-04-11 10:20 UTC by afshin-zafari

The `removal` warnings are suppressed out.
Test:
`FinalizerInfoTest` and `RunFinalizationTest` are executed locally.

2023-04-11 10:57 UTC, dholmes-ora requested changes
Suppression of warning is fine but the bug synopsis (and so PR title) needs to be updated to reflect what is actually happening here. And the bug title doesn't really make sense anyway - why is the test location given twice ??

Thanks

2023-04-11 10:57 UTC, dholmes-ora commented on test/hotspot/jtreg/serviceability/dcmd/gc/FinalizationRunner.java
> + * Copyright (c) 2023, Oracle and/or its affiliates. All rights reserved.
Copyright change is wrong - should be "2015, 2023,"

2023-04-11 12:06 UTC, afshin-zafari commented
> Suppression of warning is fine but the bug synopsis (and so PR title) needs to be updated to reflect what is actually happening here. And the bug title doesn't really make sense anyway - why is the test location given twice ??

Bug and PR titles are changed.

2023-04-12 02:36 UTC, dholmes-ora approved these changes
Looks good. Thanks.

2023-04-12 07:53 UTC, afshin-zafari commented
Thank you David and Chris for your reviews.
/integrate

2023-05-05 13:22 UTC, closed without merging