8306006: strace001.java fails due to unknown methods on stack
openjdk/jdk pull request #13476
Opened 2023-04-14 13:27 UTC by fbredber

Added the missing java.lang.Thread.beforeSleep and java.lang.afterSleep to expectedSystemTrace.
Tested on my local machine.

2023-04-14 13:29 UTC, robehn commented
Looks good to me!

2023-04-14 13:30 UTC, robehn approved these changes

2023-04-14 13:54 UTC, AlanBateman approved these changes
Looks good. Apologies we missed this test when updating j.l.Thread, I'm quite sure I didn't see this test failing.

2023-04-15 02:38 UTC, dholmes-ora requested changes
This change is not sufficient. You also have:
```
# ERROR: Length of the stack trace is 206, but expected to be not greater than 205
```
and if you look at the log:
```
Snapshot of thread: 0
	 0: jdk.internal.event.ThreadSleepEvent.isEnabled(ThreadSleepEvent.java:-1)
	 1: jdk.internal.event.ThreadSleepEvent.isTurnedOn(ThreadSleepEvent.java:39)
	 2: java.lang.Thread.beforeSleep(Thread.java:456)
```
so you need to increase the allowance on the expected depth by 2 and add the two SleepEvent methods to the expected list.

I don't think you want to add `afterSleep` as that means the thread woke too soon and we may need to adjust the sleep time. - so we would want that to fail.

Thanks.

2023-04-15 02:39 UTC, dholmes-ora commented
P.S. The comment block at line 209 discussing the extra allowance on stack depth needs updating - it was already inaccurate before these latest Thread changes. Thanks.

2023-04-16 08:06 UTC, AlanBateman commented
> I don't think you want to add `afterSleep` as that means the thread woke too soon and we may need to adjust the sleep time. - so we would want that to fail.

If I read the test correctly, "RunningThread" does recursive calls and eventually calls waitForSign where it spins calling Thread.sleep(1). The observer calling java.lang.management.ThreadInfo::getStackTrace could sample the thread in Thread.sleep at any time so I think it may see afterSleep in the stack. I don't know if there is any value doing this, would it loose anything to ignore any frames deeper than Thread.sleep(long)?

2023-04-16 08:06 UTC, AlanBateman reviewed
David seems to be right, this test needs further work.

2023-04-16 08:08 UTC, AlanBateman requested changes
David seems to be right, this test needs further work.

2023-04-17 01:34 UTC, dholmes-ora commented
> The observer calling java.lang.management.ThreadInfo::getStackTrace could sample the thread in Thread.sleep at any time so I think it may see afterSleep in the stack.

Thanks @AlanBateman  -Yes, sorry, the test doesn't do what I expected - the sleep is actually incidental so it copuld be sampled anywhere.

> and add the two SleepEvent methods to the expected list.

I see now those two methods are already present, so just the stack depth check needs updating.

Of course if this test were ever run with these events enabled then it could fail for a variety of reasons.

BTW the comments in TestDescription.java for strace00* are all inaccurate  with regards to this:
```
 2. The length of a trace must not be greater than (depth + 3).
```

2023-04-18 20:20 UTC, dcubed-ojdk commented
We current have a total of 20 sightings of this failure in both CI and Adhoc
jobs and it's happening in quite a few tests. Here's the current distribution:

   2 vmTestbase/nsk/monitoring/stress/thread/strace001/TestDescription.java
   3 vmTestbase/nsk/monitoring/stress/thread/strace003/TestDescription.java
   8 vmTestbase/nsk/monitoring/stress/thread/strace004/TestDescription.java
   2 vmTestbase/nsk/monitoring/stress/thread/strace006/TestDescription.java
   2 vmTestbase/nsk/monitoring/stress/thread/strace007/TestDescription.java
   2 vmTestbase/nsk/monitoring/stress/thread/strace008/TestDescription.java
   1 vmTestbase/nsk/monitoring/stress/thread/strace009/TestDescription.java

I would prefer not to ProblemList these 7 tests. What's the current status of
this PR and what's the estimate for integration?

2023-04-19 07:36 UTC, fbredber commented
Hi @dcubed-ojdk,
Don't ProblemList the 7 tests. I'm currently updating the tests after the review.
Running the tests looks good (no issues). Will integrate as soon as all reviewers are happy. Hoping for today or tomorrow.

2023-04-19 12:40 UTC, dholmes-ora approved these changes
Final version looks good - thanks!

A follow up would be to check what each of these test variants are supposed to do, because AFAICS the `-testMode` argument is never used.

2023-04-19 14:38 UTC, fbredber commented
/integrate

2023-04-19 15:02 UTC, AlanBateman commented
/sponsor

2023-04-19 15:04 UTC, closed without merging