8306455: Wrong majorVersion for multiple attributes in Classfile API
openjdk/jdk pull request #13536
Opened 2023-04-19 14:31 UTC by liach

Spotted the typo for BootstrapMethods, and another review over the API exposed the typo on PermittedSubclasses.

2023-05-01 08:50 UTC, liach commented
@asotona Would you mind reviewing this?

2023-05-02 10:57 UTC, asotona requested changes
BootstrapMethods is a good catch, however I would rather recommend to remove the `AttributeMapper::validSince` from the API completely. 

Classfile API has no use of it and it does not perform any checks based on this value. Also the value itself is related to the major version only, so it does not allow to model preview features.

PermittedSubclasses attribute is a preview part of JDK 15, see: https://openjdk.org/jeps/360

Real model of attributes and features versioning would have to be more complex and linked with some form of validation.

2023-05-02 11:57 UTC, liach commented
Agree; we should remove this validsince. I change PermittedSubclasses for Record uses its release major version than its preview major version.

2023-05-09 15:32 UTC, liach commented
Withdrawing this patch in favor of removing `validSince` completely in another patch.

2023-05-09 15:32 UTC, closed without merging