8305566: ZGC: gc/stringdedup/TestStringDeduplicationFullGC.java#Z failed with SIGSEGV in ZBarrier::weak_load_barrier_on_phantom_oop_slow_path
openjdk/jdk pull request #13607
Opened 2023-04-24 08:24 UTC by kimbarrett

Please review this change to the string deduplication thread to make it a kind
of JavaThread rather than a ConcurrentGCThread.  There are several pieces to
this change:

(1) New class StringDedupThread (derived from JavaThread), separate from
StringDedup::Processor (which is now just a CHeapObj instead of deriving from
ConcurrentGCThread).  The thread no longer needs to or supports being stopped,
like other similar threads.  It also needs to be started later, once Java
threads are supported.  Also don't need an explicit visitor, since it will be
in the normal Java threads list.  This separation made the changeover a little
cleaner to develop, and made the servicability support a little cleaner too.

(2) The Processor now uses the ThreadBlockInVM idiom to be safepoint polite,
instead of using the SuspendibleThreadSet facility.

(3) Because we're using ThreadBlockInVM, which has a different usage style
from STS, the tracking of time spent by the processor blocked for safepoints
doesn't really work.  It's not very important anyway, since normal thread
descheduling can also affect the normal processing times being gathered and
reported.  So we just drop the so-called "blocked" time and associated
infrastructure, simplifying Stat tracking a bit.  Also renamed the
"concurrent" stat to be "active", since it's all in a JavaThread now.

(4) To avoid #include problems, moved the definition of
JavaThread::is_active_Java_thread from the .hpp file to the .inline.hpp file,
where one of the functions it calls also is defined.

(5) Added servicability support for the new thread.

Testing:
mach5 tier1-3 with -XX:+UseStringDeduplication.
The test runtime/cds/DeterministicDump.java fails intermittently with that
option, which is not surprising - see JDK-8306712.

I was never able to reproduce the failure; it's likely quite timing sensitive.
The fix of changing the type is based on StefanK's comment that ZResurrection
doesn't expect a non-Java thread to perform load-barriers.

2023-04-24 09:07 UTC, stefank approved these changes
I think this looks sensible to me, though I'm not very familiar with the current StringDedup code, so consider this a partial review only.

2023-04-24 09:07 UTC, stefank commented on src/hotspot/share/gc/shared/stringdedup/stringDedupProcessor.hpp
>  #include "gc/shared/stringdedup/stringDedup.hpp"
sort order

2023-04-24 09:19 UTC, kimbarrett commented on src/hotspot/share/gc/shared/stringdedup/stringDedupProcessor.hpp
>  #include "gc/shared/stringdedup/stringDedup.hpp"
oops.  fixed.

2023-04-24 09:22 UTC, shipilev commented
Could we please change the synopsis to something more relevant? This PR does not only fix the ZGC test failure, but does a more fundamental change: switching string dedup thread from being `ConcurrentGCThread` to `JavaThread`, and so it affects more than one GC. The synopsis should reflect that, I think. (This would also be cleaner for potential backports, if any).

2023-04-24 09:39 UTC, shipilev approved these changes
I like this simplification a lot, thanks! I am running some Shenandoah string-dedup tests now.

2023-04-24 09:39 UTC, shipilev requested changes
(Formally requesting the change of synopsis)

2023-04-24 11:55 UTC, shipilev commented
> I like this simplification a lot, thanks! I am running some Shenandoah string-dedup tests now.

Ran `gc/shenandoah/TestStringDedup*` on x86_64 and AArch64 for 100 times without a problem. These tests usually fail when there are bugs in string dedup. So I think we are clear there!

2023-04-24 20:23 UTC, plummercj approved these changes
SA changes look good

2023-04-26 14:39 UTC, tschatzl approved these changes
Please improve the bug name as suggested by @shipilev before pushing.

Looks good otherwise.

2023-04-28 02:48 UTC, kimbarrett commented
Thanks all for reviews.  I've changed the bug and PR summaries as requested.

2023-04-28 03:08 UTC, kimbarrett commented
/integrate

2023-04-28 03:11 UTC, closed without merging