8306933: C2: "assert(false) failed: infinite loop" failure
openjdk/jdk pull request #13672
Opened 2023-04-26 15:36 UTC by rwestrel

The assert fires because an infinite loop appears in the graph after
loop opts are over.

After loop opts, the `for(;;)` loop contains a null check and a range
check for `array[i]`. So it's not considered an infinite loop (it has
exits to uncommon traps). The null check and range check is redundant
with the one right before the loop: `int v = array2[k];` IGVN can
optimize it but it doesn't happen until after loop opts when a
`ConvI2L` for the `array[i]` access is processed as part of post loop
opts IGVN. The `for(;;)` loop is then emptied and only contains a
`Loop` and a `Safepoint` nodes.

I propose removing the assert (at least for now) as I don't see a way
to guarantee no infinite loop can appear after loop opts.

2023-04-27 10:29 UTC, chhagedorn requested changes
That looks reasonable!

2023-04-27 10:29 UTC, chhagedorn commented on test/hotspot/jtreg/compiler/c2/TestInfiniteLoopCompilationFailure.java
> + *                   -XX:+StressIGVN TestInfiniteLoopCompilationFailure
Since `StressIGVN` is diagnostic, you need to add `-XX:+UnlockDiagnosticVMOptions` here.

2023-05-03 07:19 UTC, TobiHartmann approved these changes
Looks good to me too (besides the missing `-XX:+UnlockDiagnosticVMOptions`).

2023-05-03 11:08 UTC, chhagedorn approved these changes
Update looks good!

2023-05-03 11:14 UTC, rwestrel commented
@TobiHartmann @chhagedorn thanks for the reviews

2023-05-03 11:14 UTC, rwestrel commented
/integrate

2023-05-03 11:15 UTC, closed without merging