JDK-8306672: support offset in dll_address_to_library_name on AIX
openjdk/jdk pull request #13692
Opened 2023-04-27 14:30 UTC by JoKern65

So far the offset return reference parameter was not supported on AIX, but always set to -1. This could be improved, it was already supported on other OS platforms like Linux.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8306672](https://bugs.openjdk.org/browse/JDK-8306672): support offset in dll_address_to_library_name on AIX

### Reviewers
 * [Thomas Stuefe](https://openjdk.org/census#stuefe) (@tstuefe - **Reviewer**) ⚠️ Review applies to [20e9f552](https://git.openjdk.org/jdk/pull/13692/files/20e9f5527131145b90000e156309eca97141c49f)
 * [Christoph Langer](https://openjdk.org/census#clanger) (@RealCLanger - **Reviewer**)
 * [Matthias Baesken](https://openjdk.org/census#mbaesken) (@MBaesken - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13692/head:pull/13692` \
`$ git checkout pull/13692`

Update a local copy of the PR: \
`$ git checkout pull/13692` \
`$ git pull https://git.openjdk.org/jdk.git pull/13692/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13692`

View PR using the GUI difftool: \
`$ git pr show -t 13692`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13692.diff">https://git.openjdk.org/jdk/pull/13692.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/13692#issuecomment-1525833400)

2023-04-27 15:51 UTC, tstuefe requested changes
Hi Joachim,

nice to see you here :-)

Change is mostly good, small nits remain. You may want to adjust copyright years in the file headers. The rule we follow is
- adjust Oracle's copyright year always if needed (changing the last year to 2023)
- adjust SAPs (or whatever company you work for) copyright too
- leave other copyrights alone.
Note: porting_aix has no Oracle copyrights since nothing in that codebase hat been derived from the OpenJDK.

Cheers, Thomas

2023-04-27 15:51 UTC, tstuefe commented on src/hotspot/os/aix/os_aix.cpp
> +    *offset = addr - base;
Maybe add a sanity check that addr >= base and <= (base + INT_MAX). If it never should happen, an assert is fine, otherwise handled at runtime.

2023-04-27 15:51 UTC, tstuefe commented on src/hotspot/os/aix/porting_aix.hpp
> +    address* p_base                  // [out] module name
comment copy paste error?

2023-04-27 16:15 UTC, RealCLanger commented
Please also enable GHA (it's not so important for this PR as AIX is not tested and the code is AIX only. But for future PRs that touch shared code it could be helpful). You have to enable it here: https://github.com/JoKern65/jdk/actions.

2023-04-28 07:15 UTC, MBaesken commented
Yes please enable the github actions, they will bring you some additional builds/tests after every push - helps not to break other platforms in case your change would touch other platforms (which is not the case here).

2023-04-28 09:11 UTC, tstuefe approved these changes
Okay

2023-04-28 09:14 UTC, JoKern65 commented
Hi Thomas,

thank you for your advice. I adjusted the copyright years, made the cosmetic changes and added the assert.

Greetings
Joachim

2023-04-28 09:43 UTC, RealCLanger approved these changes
Looks good.

2023-04-28 10:40 UTC, MBaesken approved these changes
Looks good to me now, thanks for fixing the comments(copyright years and for the small adjustments.

2023-04-28 13:03 UTC, JoKern65 commented
/integrate

2023-04-28 13:08 UTC, closed without merging