JDK-8282797: CompileCommand parsing errors should exit VM
openjdk/jdk pull request #13753
Opened 2023-05-02 11:35 UTC by tobiasholenstein

Currently, errors during compile command parsing just print an error but don't exit the VM. As a result, issues go unnoticed. 

With this PR the behavior is changed to exit the VM when an error occurs.

E.g. `java -XX:CompileCommand=compileonly,HashMap:: -version` will exit the VM after a parsing occurred.  
```
CompileCommand: An error occurred during parsing
Error: Could not parse method pattern
Line: 'compileonly,HashMap::'

Usage: '-XX:CompileCommand=<option>,<method pattern>' - to set boolean option to true
Usage: '-XX:CompileCommand=<option>,<method pattern>,<value>'
Use:   '-XX:CompileCommand=help' for more information and to list all option.

Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

### Updated Tests
Updated all tests to now expect an error code `1` for wrong `CompileCommand`

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change requires CSR request [JDK-8308679](https://bugs.openjdk.org/browse/JDK-8308679) to be approved

### Issues
 * [JDK-8282797](https://bugs.openjdk.org/browse/JDK-8282797): CompileCommand parsing errors should exit VM (**Enhancement** - P4)
 * [JDK-8308679](https://bugs.openjdk.org/browse/JDK-8308679): Exit VM for CompileCommand parsing errors (**CSR**)

### Reviewers
 * [Vladimir Kozlov](https://openjdk.org/census#kvn) (@vnkozlov - **Reviewer**)
 * [Christian Hagedorn](https://openjdk.org/census#chagedorn) (@chhagedorn - **Reviewer**)
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - **Reviewer**) ⚠️ Review applies to [6de71f77](https://git.openjdk.org/jdk/pull/13753/files/6de71f7760c8464203ceca1e922496e8863286da)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/13753/head:pull/13753` \
`$ git checkout pull/13753`

Update a local copy of the PR: \
`$ git checkout pull/13753` \
`$ git pull https://git.openjdk.org/jdk.git pull/13753/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13753`

View PR using the GUI difftool: \
`$ git pr show -t 13753`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/13753.diff">https://git.openjdk.org/jdk/pull/13753.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/13753#issuecomment-1559714697)

2023-05-23 16:19 UTC, vnkozlov approved these changes
Looks good.

2023-05-24 09:32 UTC, chhagedorn requested changes
That's a nice feature to avoid accidental compile command typos in tests!

I have some comments.

2023-05-24 09:32 UTC, chhagedorn commented on test/hotspot/jtreg/compiler/compilercontrol/share/IntrinsicCommand.java
> +        System.out.println("XXXXXXXXXXXXXXXX compileCommand.isValid " + compileCommand.isValid());
Leftover from debugging?

2023-05-24 09:32 UTC, chhagedorn commented on test/hotspot/jtreg/compiler/compilercontrol/share/scenario/Scenario.java
> +            //if (isJcmdValid) {
Intentionally commented out? Then it can be removed.

2023-05-24 09:32 UTC, chhagedorn commented on test/hotspot/jtreg/compiler/compilercontrol/share/scenario/Scenario.java
> +            for(OutputAnalyzer out : outputList) {
```suggestion
            for (OutputAnalyzer out : outputList) {
```

2023-05-24 09:32 UTC, chhagedorn requested changes
That's a nice feature to avoid accidental compile command typos in tests!

I have some comments.

2023-05-24 09:32 UTC, TobiHartmann approved these changes
Looks good to me otherwise.

2023-05-24 09:32 UTC, TobiHartmann commented on test/hotspot/jtreg/compiler/compilercontrol/share/scenario/Scenario.java
> +            //if (isJcmdValid) {
Should be removed.

2023-05-24 10:49 UTC, tobiasholenstein commented on test/hotspot/jtreg/compiler/compilercontrol/share/IntrinsicCommand.java
> +        System.out.println("XXXXXXXXXXXXXXXX compileCommand.isValid " + compileCommand.isValid());
right. I removed it now

2023-05-24 10:50 UTC, tobiasholenstein commented on test/hotspot/jtreg/compiler/compilercontrol/share/IntrinsicCommand.java
> +        System.out.println("XXXXXXXXXXXXXXXX compileCommand.isValid " + compileCommand.isValid());
yes. I removed it

2023-05-24 10:58 UTC, tobiasholenstein commented on src/hotspot/share/compiler/compilerOracle.cpp
> +        return true;
right. I changed it

2023-05-24 11:00 UTC, tobiasholenstein commented on test/hotspot/jtreg/compiler/compilercontrol/share/scenario/Scenario.java
> +            //if (isJcmdValid) {
done

2023-05-31 10:50 UTC, chhagedorn approved these changes
Thanks for doing the updates, looks good!

2023-06-01 13:53 UTC, AlanBateman commented
/label remove core-libs

2023-06-09 12:14 UTC, tobiasholenstein commented
Thanks @vnkozlov , @TobiHartmann and @chhagedorn for the reviews!

/integrate

2023-06-09 12:18 UTC, tobiasholenstein commented
Thanks @vnkozlov , @TobiHartmann and @chhagedorn for the reviews!

/integrate

2023-06-09 12:59 UTC, tobiasholenstein commented
Thanks @vnkozlov , @TobiHartmann and @chhagedorn for the reviews!

/integrate

2023-06-09 13:01 UTC, closed without merging