8303153: Native interpreter frame missing mirror
openjdk/jdk pull request #13794
Opened 2023-05-04 08:00 UTC by fbredber

The mirror needs to be stored in the frame for native calls also on AArch64 and RISC-V (as it is on other platforms).
See JDK-8303153 for more info.
Passes tier1-5 tests on AArch64. Done basic tests on RISC-V using QEmu.

2023-05-04 08:09 UTC, fbredber commented
I'd appreciate if @theRealAph and @RealFYang can have a look at this.

2023-05-04 16:52 UTC, coleenp approved these changes
This looks good to me.

2023-05-05 12:18 UTC, RealFYang requested changes
Hi,
Thanks for taking care of RISC-V at the same time. 
I think it would be cleaner if we do following for the RISC-V part:
```
diff --git a/src/hotspot/cpu/riscv/templateInterpreterGenerator_riscv.cpp b/src/hotspot/cpu/riscv/templateInterpreterGenerator_riscv.cpp
index 3e0e94515fc..f8ce528634f 100644
--- a/src/hotspot/cpu/riscv/templateInterpreterGenerator_riscv.cpp
+++ b/src/hotspot/cpu/riscv/templateInterpreterGenerator_riscv.cpp
@@ -770,8 +770,10 @@ void TemplateInterpreterGenerator::generate_fixed_frame(bool native_call) {
   __ sd(x19_sender_sp, Address(sp, 9 * wordSize));
   __ sd(zr, Address(sp, 8 * wordSize));

-  // Get mirror
+  // Get mirror and store it in the frame as GC root for this Method*
   __ load_mirror(t2, xmethod, x15, t1);
+  __ sd(t2, Address(sp, 4 * wordSize));
+
   if (!native_call) {
     __ ld(t0, Address(xmethod, Method::const_offset()));
     __ lhu(t0, Address(t0, ConstMethod::max_stack_offset()));
@@ -779,9 +781,8 @@ void TemplateInterpreterGenerator::generate_fixed_frame(bool native_call) {
     __ slli(t0, t0, 3);
     __ sub(t0, sp, t0);
     __ andi(t0, t0, -16);
-    // Store extended SP and mirror
+    // Store extended SP
     __ sd(t0, Address(sp, 5 * wordSize));
-    __ sd(t2, Address(sp, 4 * wordSize));
     // Move SP out of the way
     __ mv(sp, t0);
   } else {
@@ -789,7 +790,6 @@ void TemplateInterpreterGenerator::generate_fixed_frame(bool native_call) {
     // an exception (see TemplateInterpreterGenerator::generate_throw_exception())
     __ sub(t0, sp, 2 * wordSize);
     __ sd(t0, Address(sp, 5 * wordSize));
-    __ sd(zr, Address(sp, 4 * wordSize));
     __ mv(sp, t0);
   }
 }
```

2023-05-08 01:26 UTC, RealFYang approved these changes
Looks reasonable to me. Thanks for the update. 
FYI: I have performed tier1-3 tests on linux-riscv64 board, result looks good.

2023-05-08 08:45 UTC, fbredber commented
Thanks for the review @coleenp and @RealFYang.
If no one else has anything to add, I'll integrate (as soon as I can get a sponsor).

2023-05-08 08:45 UTC, fbredber commented
/integrate

2023-05-08 14:45 UTC, closed without merging