8256754: Deoptimization::revoke_for_object_deoptimization: stack processing start call is redundant
openjdk/jdk pull request #1381
Opened 2020-11-23 11:40 UTC by reinrich

This is a XS clean-up of Deoptimization::revoke_for_object_deoptimization() which removes the StackWatermarkSet::start_processing() call.

This is correct because all paths leading to revoke_for_object_deoptimization() are equipt with a KeepStackGCProcessedMark.

Call Tree:

```
StackWatermarkSet::start_processing(JavaThread *, enum StackWatermarkKind) : void
    Deoptimization::revoke_for_object_deoptimization(JavaThread *, frame, RegisterMap *, JavaThread *) : void
        Deoptimization::deoptimize_objects_internal(JavaThread *, GrowableArray<compiledVFrame *> *, bool &) : bool
            EscapeBarrier::deoptimize_objects_internal(JavaThread *, intptr_t *) : bool
                EscapeBarrier::deoptimize_objects_all_threads() : bool                     // has KeepStackGCProcessedMark
                EscapeBarrier::deoptimize_objects(intptr_t *) : bool
                    EscapeBarrier::deoptimize_objects(int, int) : bool                     // has KeepStackGCProcessedMark 
```

Testing: hotspot_serviceability, jdk_svc, jdk_jdi, vmTestbase_nsk_jdi, vmTestbase_nsk_jvmti, vmTestbase_nsk_jdwp with -XX:+UseZGC.

2020-11-23 22:41 UTC, dean-long requested changes
The justification for removing this code is that all callers use KeepStackGCProcessedMark.  Is there an assert you can add in place of the removed code that checks this invariant?

2020-11-24 08:43 UTC, fisk approved these changes
Looks good.

2020-11-24 11:28 UTC, reinrich commented
Thanks for having a look @dean-long 
> 
> 
> The justification for removing this code is that all callers use KeepStackGCProcessedMark. Is there an assert you can add in place of the removed code that checks this invariant?

I don't think there is an assert I could use. I added code that allows for asserting this.  Let me know which version you prefer.

2020-11-24 11:31 UTC, reinrich commented
> 
> 
> Looks good.

Thank you @fisk 
Note that I added code to assert that the remote stack is kept gc processed. Just in case you have comments on that.

2020-11-24 23:15 UTC, dean-long approved these changes

2020-11-24 23:15 UTC, dean-long commented
I like the version with the assert.

2020-11-25 08:59 UTC, reinrich commented
> 
> 
> I like the version with the assert.

Good. Thanks for reviewing!

2020-11-30 08:36 UTC, reinrich commented
/integrate

2020-11-30 08:37 UTC, closed without merging