8256858: C2: Devirtualize PhaseIterGVN-specific methods
openjdk/jdk pull request #1385
Opened 2020-11-23 13:48 UTC by cl4es

PhaseValues define the virtual method is_IterGVN, which is trivially returning 0(!) for all types except those derived from PhaseIterGVN. Similarly there's igvn_rehash_node_delayed which is virtual and a no-op in base types, but implemented to call rehash_node_delayed in PhaseIterGVN.

By devirtualizing we allow for more aggressive inlining and slightly better code generation in a few places. 

This increases sizeof(PhaseValues) from 2480 to 2488 on x64. Since we only go through a limited number of phases per compilation this seems acceptable.

2020-11-23 19:52 UTC, vnkozlov approved these changes
Good.

2020-11-24 07:15 UTC, TobiHartmann requested changes

2020-11-24 07:15 UTC, TobiHartmann commented on src/hotspot/share/opto/addnode.cpp
> +      if (add2->outcnt() == 0 && phase->is_IterGVN()) {
Why did you remove the local variable `igvn`? Performance wise it shouldn't make a difference, right?

2020-11-24 07:15 UTC, TobiHartmann commented on src/hotspot/share/opto/addnode.cpp
> +      if (add->outcnt() == 0 && phase->is_IterGVN()) {
Again, I think replacing `igvn` by `phase->is_IterGVN()` makes the code less readable.

2020-11-24 07:15 UTC, TobiHartmann commented on src/hotspot/share/opto/memnode.cpp
> +  if (result != this && igvn != NULL) {
Here you did the reverse (replaced `phase->is_IterGVN()` by `igvn` local).

2020-11-24 07:15 UTC, TobiHartmann commented on src/hotspot/share/opto/phaseX.hpp
> +  PhaseIterGVN *is_IterGVN() { return (_iterGVN) ? (PhaseIterGVN*)this : NULL; }
`PhaseIterGVN *is_IterGVN` -> `PhaseIterGVN* is_IterGVN`

2020-11-24 07:15 UTC, TobiHartmann commented on src/hotspot/share/opto/phaseX.hpp
> +  const Type* saturate(const Type* new_type, const Type* old_type,
Indentation should be fixed.

2020-11-24 14:20 UTC, TobiHartmann approved these changes

2020-11-24 14:33 UTC, cl4es commented
@vnkozlov @TobiHartmann - thank you for reviewing!

/integrate

2020-11-24 14:33 UTC, closed without merging