8256883: C2: Add a RegMask iterator
openjdk/jdk pull request #1397
Opened 2020-11-23 18:01 UTC by cl4es

By implementing a simple RegMaskIterator we can speed this up and possibly make the code a bit clearer by doing so.

2020-11-23 20:03 UTC, vnkozlov requested changes
There are 2 places in ZGC code (x86 and aarch64) which could use new iterator too:
https://github.com/openjdk/jdk/blob/master/src/hotspot/cpu/x86/gc/z/zBarrierSetAssembler_x86.cpp#L482

2020-11-23 23:30 UTC, cl4es commented
/label remove hotspot
/label add hotspot-gc
/label add hotspot-compiler

2020-11-24 00:07 UTC, vnkozlov approved these changes
Good.

2020-11-24 00:16 UTC, pliden approved these changes
ZGC changes look good.

2020-11-24 11:22 UTC, fisk approved these changes
Looks good.

2020-11-24 14:34 UTC, cl4es commented
@vnkozlov @pliden @fisk - thank you for reviewing!

I ran ZGC tier1-7 testing on linux-x64 and linux-aarch64 overnight, all passed.

/integrate

2020-11-24 14:35 UTC, closed without merging