8308088: Improve klass check in CollectedHeap::is_oop
openjdk/jdk pull request #13982
Opened 2023-05-15 10:25 UTC by shipilev

See the bug for more details.

2023-05-15 19:33 UTC, zhengyu123 approved these changes
LGTM

2023-05-16 00:37 UTC, zhengyu123 approved these changes
LGTM

2023-05-16 07:44 UTC, tschatzl approved these changes

2023-05-16 08:11 UTC, albertnetymk approved these changes

2023-05-16 08:11 UTC, albertnetymk commented on src/hotspot/share/gc/shared/collectedHeap.cpp
> +  Klass* k = object->klass_raw();
Introducing a local-var doesn't seem needed.

2023-05-16 12:26 UTC, tstuefe requested changes
This can be improved:

- klass_raw() will, eventually, end up doing some asserts. We don't want that. So narrow Klass extraction needs to be done separately. 
- then, we could weed out obvious bogus Klass values (not aligned or null)
- then, Metaspace::contains checks class space and non-class metaspace. The latter would be a false positive, and its also more expensive, since it walks the (usually short) list of metaspace regions. class space otoh is just one region. A correct check for Klass would be to check if its in CDS or in class space.

Proposal:
https://github.com/openjdk/jdk/commit/b8868dac39e43c8bea6ccd34d8e5b186506415fe

2023-05-16 13:28 UTC, tstuefe commented
> This can be improved:
> 
>     * klass_raw() will, eventually, end up doing some asserts. We don't want that. So narrow Klass extraction needs to be done separately.
> 
>     * then, we could weed out obvious bogus Klass values (not aligned or null)
> 
>     * then, Metaspace::contains checks class space and non-class metaspace. The latter would be a false positive, and its also more expensive, since it walks the (usually short) list of metaspace regions. class space otoh is just one region. A correct check for Klass would be to check if its in CDS or in class space.
> 
> 
> Proposal sketch: [b8868da](https://github.com/openjdk/jdk/commit/b8868dac39e43c8bea6ccd34d8e5b186506415fe)

Update: looks like I was mistaken about the first point. The rest is probably not worth optimizing. Never mind then, this looks good as it is.

2023-05-16 13:29 UTC, tstuefe approved these changes
include memory/metaspace.hpp is missing.

Otherwise LGTM

2023-05-17 09:17 UTC, shipilev commented
Thanks for reviews! I am integrating now.

/integrate

2023-05-17 09:19 UTC, closed without merging