8308403
openjdk/jdk pull request #14055
Opened 2023-05-19 08:27 UTC by offamitkumar

This PR split `z_abi_160` into `z_abi_160_base` and `z_abi_160`. `z_abi_160_base` will represent the minimal structure and overflowing args will be taken care by `remaining_cargs` field present in `z_abi_160`.  We're separating this field because it's causing issue in calculating the correct frame size for Vthreads.

2023-05-19 17:31 UTC, TheRealMDoerr approved these changes
I'm ok with it.

2023-05-19 17:31 UTC, TheRealMDoerr commented on src/hotspot/cpu/s390/frame_s390.hpp
> +  // layout. There is an field in the z_abi_160
Should be "a field".

2023-05-19 18:57 UTC, offamitkumar commented on src/hotspot/cpu/s390/frame_s390.hpp
> +  // layout. There is an field in the z_abi_160
Fixed, Thanks for the Review.

2023-05-22 15:44 UTC, RealLucy requested changes
I would like to have the comment updated.
Otherwise LGTM.

2023-05-22 15:44 UTC, RealLucy commented on src/hotspot/cpu/s390/frame_s390.hpp
>    // sizeof(...).
I would better like a wording like
Therefore, please use `sizeof(z_abi_160_base)` or the `enum` value `z_abi_160_size` to find out the size of the `ABI` structure.

2023-05-22 16:17 UTC, offamitkumar commented
Thanks, Martin and Lutz, for Review. I'm executing integrate command, but feel free to suggest more changes :-) 

/integrate

2023-05-23 08:30 UTC, RealLucy approved these changes
LGTM.
Thanks for adapting the comment.
It is believed to be good practice to have the requested changes implemented and approved before issuing the integrate command.

2023-05-23 08:32 UTC, closed without merging