8309346: Extend hs_err logging for all VM operations deriving from VM_GC_Operation
openjdk/jdk pull request #14287
Opened 2023-06-02 15:13 UTC by quadhier

This patch implements `cause()` for `VM_GC_Operation` and its derived classes. It follows [JDK-8309210](https://bugs.openjdk.org/browse/JDK-8309210) to provide more detailed info for `VM_GC_Operation`s in hs_err log file.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issue
 * [JDK-8309346](https://bugs.openjdk.org/browse/JDK-8309346): Extend hs_err logging for all VM operations deriving from VM_GC_Operation

### Reviewers
 * [Thomas Schatzl](https://openjdk.org/census#tschatzl) (@tschatzl - **Reviewer**)
 * [Stefan Karlsson](https://openjdk.org/census#stefank) (@stefank - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/14287/head:pull/14287` \
`$ git checkout pull/14287`

Update a local copy of the PR: \
`$ git checkout pull/14287` \
`$ git pull https://git.openjdk.org/jdk.git pull/14287/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 14287`

View PR using the GUI difftool: \
`$ git pr show -t 14287`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/14287.diff">https://git.openjdk.org/jdk/pull/14287.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/14287#issuecomment-1573909276)

2023-06-05 12:18 UTC, lkorinth commented
(this is not a review) How about using `override` instead of `virtual`? I think it better shows how the method is used, and also create compile time errors if we miss to rename the method during refactoring.

2023-06-05 14:54 UTC, tschatzl approved these changes
Lgtm.

Would it be possible to also add some description string for `VM_Verify` and `VM_PopulateDynamicDumpSharedSpace` (separately)? I'll file an RFE which you could pick up if you want.

2023-06-05 16:39 UTC, stefank requested changes
Could you move the implementation over to the .cpp file? We should strive to not add non-trivial implementation in .hpp files.

2023-06-05 19:14 UTC, stefank approved these changes
Looks good.

2023-06-06 07:27 UTC, tschatzl commented
/sponsor

2023-06-06 07:29 UTC, closed without merging