JDK-8309404
openjdk/jdk pull request #14297
Opened 2023-06-03 09:57 UTC by lgxbslgx

Hi all,

This patch parallelizes the process of the class loader data graph in young gc.

The class `ClassLoaderData` has a field `_claim` to avoid applying oop closure more than once 
and the method `ClassLoaderData::oops_do` can check if the CLD had been claimed.
The parallel full gc has already used them in `MarkFromRootsTask::work` and `PSAdjustTask::work`.

But I don't have experience to test the performance improvement of the GC.
If this patch needs such test data before integrating, please guide and help me here.

Thanks for the review and guidance.

Best Regards,
-- Guoxiong

2023-06-06 09:03 UTC, tschatzl requested changes
The reason why this is not parallelized in stw pauses is because the CLD data structure is not amenable to parallelization at all. This is basically a linked list, and when parallelizing it this way, 
* every thread visits every CLD anyway (doing the pointer chasing)
* threads are massively choking themselves on obtaining the claim value
* the code adds another pass through the CLD linked list clearing the claim marks
In my experience you *will* get significant negative scaling (i.e. that phase taking significant multiples of the original time) with this simple approach.

I.e. this has been analyzed before, see https://bugs.openjdk.org/browse/JDK-8030144; only Shenandoah does a parallel walk, but with limited number of threads (e.g. https://bugs.openjdk.org/browse/JDK-8246097)

The latter CR also provides some applications with apparently many CLDG entries (Spring Boot and CLion), which may be used for this investigation.
Fwiw, it may be easier to start this investigation with G1 as it has the timing logging already implmented (but it is no problem to add this to Parallel temporarily(?)).

2023-06-06 16:06 UTC, lgxbslgx commented
> The reason why this is not parallelized in stw pauses is because the CLD data structure is not amenable to parallelization at all. This is basically a linked list, and when parallelizing it this way,
> 
> * every thread visits every CLD anyway (doing the pointer chasing)
> * threads are massively choking themselves on obtaining the claim value
> * the code adds another pass through the CLD linked list clearing the claim marks
>   In my experience you _will_ get significant negative scaling (i.e. that phase taking significant multiples of the original time) with this simple approach.
> 
> I.e. this has been analyzed before, see https://bugs.openjdk.org/browse/JDK-8030144; only Shenandoah does a parallel walk, but with limited number of threads (e.g. https://bugs.openjdk.org/browse/JDK-8246097)
> 
> The latter CR also provides some applications with apparently many CLDG entries (Spring Boot and CLion), which may be used for this investigation. Fwiw, it may be easier to start this investigation with G1 as it has the timing logging already implmented (but it is no problem to add this to Parallel temporarily(?)).

Thanks for the guidance. The full GC in `Parallel` had parallelized it, so previously, I thought it is good to do the same thing in young GC. One of young GC or full GC should be adjusted. I will investigate more information in related issues (mainly test the performance).

2023-06-07 09:08 UTC, lgxbslgx commented
@tschatzl I have a problem. During searching the roots in parallel, the claim values of the threads also need to be changed atomically by all the worker threads. Does it also have the same problem? Do you know/do any research related to it?

```java
// file threads.cpp
void Threads::possibly_parallel_threads_do(bool is_par, ThreadClosure* tc) {
  assert_at_safepoint();

  uintx claim_token = Threads::thread_claim_token();
  ALL_JAVA_THREADS(p) {
    if (p->claim_threads_do(is_par, claim_token)) {
      tc->do_thread(p);
    }
  }
  for (NonJavaThread::Iterator njti; !njti.end(); njti.step()) {
    Thread* current = njti.current();
    if (current->claim_threads_do(is_par, claim_token)) {
      tc->do_thread(current);
    }
  }
}

// file thread.cpp
bool Thread::claim_par_threads_do(uintx claim_token) {
  uintx token = _threads_do_token;
  if (token != claim_token) {
    uintx res = Atomic::cmpxchg(&_threads_do_token, token, claim_token);
    if (res == token) {
      return true;
    }
    guarantee(res == claim_token, "invariant");
  }
  return false;
}
```

2023-06-07 10:25 UTC, tschatzl commented
> @tschatzl I have a question. During searching the roots in parallel, the claim values of the threads also need to be changed atomically by all the worker threads. Does it also have the same problem? Do you know/do any research related to it?
> 

It generally has the same problem, but is mitigated because the work per Thread is much larger (a Thread has typically many stacks levels to look through), so the relative impact smaller. The amount of contention on that is much lower too as the probability that multiple threads try to claim the same claim value is lower due to longer and more variable time to process the task.

There is also a newer API available that allows less contention claiming, see e.g. `G1JavaThreadsListClaimer` and the use in `G1PreEvacuateCollectionSetBatchTask`, however at this point it is only used in a few places. Replacement work isn't trivial.

2023-08-02 14:12 UTC, closed without merging