8309502: RISC-V: String.indexOf intrinsic may produce misaligned memory loads
openjdk/jdk pull request #14320
Opened 2023-06-05 20:52 UTC by VladimirKempik

Please review this attempt to remove misaligned loads in String.indexOf intrinsic on RISC-V

Initialy found these misaligned loads when profiling finagle-http test from renaissance suite.
The majority of trp_lam events (about 66k per finagle-http round) came at line 706 (https://github.com/openjdk/jdk/pull/14320/files#diff-35eb1d2f1e2f0514dd46bd7fbad49ff2c87703d5a3041a6433956df00a3fe6e6L706)
The other two produced about 100 events combined.
Later I've found this can partially be reproduced with StringIndexOf.advancedWithMediumSub.
Numbers on hifive before and after applying the patch:

```
Benchmark                                                  Mode  Cnt       Score      Error  Units
StringIndexOf.advancedWithMediumSub                        avgt   25   47031.406 ±  144.005  ns/op
```

After:
```
Benchmark                                                 Mode  Cnt       Score     Error  Units
StringIndexOf.advancedWithMediumSub                       avgt   25    4256.830 ±  23.075  ns/op
```

Testing: tier1/tier2 is clean on hifive.

/cc hotspot-compiler

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8309502](https://bugs.openjdk.org/browse/JDK-8309502): RISC-V: String.indexOf intrinsic may produce misaligned memory loads (**Enhancement** - P4)

### Reviewers
 * [Ludovic Henry](https://openjdk.org/census#luhenry) (@luhenry - Committer) ⚠️ Review applies to [a0880518](https://git.openjdk.org/jdk/pull/14320/files/a08805183cf980601423fda0877a06fe7b56de38)
 * [Feilong Jiang](https://openjdk.org/census#fjiang) (@feilongjiang - Author) ⚠️ Review applies to [185a811d](https://git.openjdk.org/jdk/pull/14320/files/185a811deb702555b605575e53fa621240a066e4)
 * [Fei Yang](https://openjdk.org/census#fyang) (@RealFYang - **Reviewer**) ⚠️ Review applies to [185a811d](https://git.openjdk.org/jdk/pull/14320/files/185a811deb702555b605575e53fa621240a066e4)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/14320/head:pull/14320` \
`$ git checkout pull/14320`

Update a local copy of the PR: \
`$ git checkout pull/14320` \
`$ git pull https://git.openjdk.org/jdk.git pull/14320/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 14320`

View PR using the GUI difftool: \
`$ git pr show -t 14320`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/14320.diff">https://git.openjdk.org/jdk/pull/14320.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/14320#issuecomment-1577466073)

2023-06-06 06:29 UTC, luhenry approved these changes
Looks good!

2023-06-06 11:41 UTC, feilongjiang commented
Looks good, I see some `load_4chr` at [1], could it also produce misaligned loads?

1. https://github.com/openjdk/jdk/blob/01455a07a7e1f15aed43cd47222047810c826abd/src/hotspot/cpu/riscv/c2_MacroAssembler_riscv.cpp#L675-L690

2023-06-06 15:49 UTC, VladimirKempik commented
> Looks good, I see some `load_4chr` at [1], could it also produce misaligned loads?
> 
> 1. https://github.com/openjdk/jdk/blob/01455a07a7e1f15aed43cd47222047810c826abd/src/hotspot/cpu/riscv/c2_MacroAssembler_riscv.cpp#L675-L690

That's hard to say, I just run some tests with perf and check result for trp_lam events. Such analysis is a lot easier.

2023-06-07 06:20 UTC, RealFYang commented
Hi, I searched and found that we have four callers of `C2_MacroAssembler::string_indexof_linearscan`: three in file riscv.ad and one by `C2_MacroAssembler::string_indexof`. Did you checked which one is triggering these unaligned accesses? I am not sure but it looks to me that the three callers in file riscv.ad are less likely to have such an issue. If that is true, we might need some distinugish among those callers for better performance. Also, it would be better to have some numbers on other venders like T-head.

2023-06-07 07:10 UTC, VladimirKempik commented
I'll test on thead

as for the first part of the patch, at line 494,
on this [line](https://github.com/openjdk/jdk/pull/14320/files#diff-35eb1d2f1e2f0514dd46bd7fbad49ff2c87703d5a3041a6433956df00a3fe6e6L482), we do nlen_tmp -= 7;
then we add nlen_tmp to result and read long word from it, obviously this causes misaligned load

2023-06-07 07:41 UTC, VladimirKempik commented
> Hi, I searched and found that we have four direct callers of `C2_MacroAssembler::string_indexof_linearscan`: three in file riscv.ad (by string_indexof_conUU, string_indexof_conLL and string_indexof_conUL) and one by `C2_MacroAssembler::string_indexof`. Did you check which one is triggering these unaligned accesses? I am not sure but it looks to me that the three direct callers in file riscv.ad are less likely to have such an issue. If that is true, we might need some distinugish among those callers for better performance.

Originally, when I found this misaligned load, this code `(this->*load_2chr)(ch2, Address(tmp3), noreg);` was corresponding to `lhu t1, 0(t4)`. So I can say the isLL variable was true.

2023-06-07 07:49 UTC, RealFYang commented
> > Hi, I searched and found that we have four direct callers of `C2_MacroAssembler::string_indexof_linearscan`: three in file riscv.ad (by string_indexof_conUU, string_indexof_conLL and string_indexof_conUL) and one by `C2_MacroAssembler::string_indexof`. Did you check which one is triggering these unaligned accesses? I am not sure but it looks to me that the three direct callers in file riscv.ad are less likely to have such an issue. If that is true, we might need some distinugish among those callers for better performance.
> 
> Originally, when I found this misaligned load, this code `(this->*load_2chr)(ch2, Address(tmp3), noreg);` was corresponding to `lhu t1, 0(t4)`. So I can say the isLL variable was true.

Can we simply change condition `if (AvoidUnalignedAccesses) {` added in `C2_MacroAssembler::string_indexof_linearscan` into something like `if (needle_con_cnt == -1 && AvoidUnalignedAccesses) {` and re-run and see this could also resolve the problem?

2023-06-07 07:54 UTC, VladimirKempik commented
See, this part of algo is misaligned
```
 bind(CH1_LOOP);
    add(tmp3, haystack, hlen_neg);
    (this->*load_2chr)(ch2, Address(tmp3), noreg);
    beq(ch1, ch2, MATCH);
    add(hlen_neg, hlen_neg, haystack_chr_size);
    blez(hlen_neg, CH1_LOOP);
```
this becomes:
```
CH1_LOOP: add t4, a1, a2
lhu t1, 0(t4)
beg t0, t1, 0xMATCH
addi a2, a2, 1
blez a2, CH1_LOOP
```

so we load halfword on each iteration from address (a1+a2), and while a1 is constant, a2 is incrementing by 1 each step, so every other load is misaligned.

2023-06-07 08:27 UTC, RealFYang commented
> See, this part of algo is misaligned
> 
> ```
>  bind(CH1_LOOP);
>     add(tmp3, haystack, hlen_neg);
>     (this->*load_2chr)(ch2, Address(tmp3), noreg);
>     beq(ch1, ch2, MATCH);
>     add(hlen_neg, hlen_neg, haystack_chr_size);
>     blez(hlen_neg, CH1_LOOP);
> ```
> 
> this becomes:
> 
> ```
> CH1_LOOP: add t4, a1, a2
> lhu t1, 0(t4)
> beg t0, t1, 0xMATCH
> addi a2, a2, 1
> blez a2, CH1_LOOP
> ```
> 
> so we load halfword on each iteration from address (a1+a2), and while a1 is constant, a2 is incrementing by 1 each step, so every other load is misaligned.

I see it now. Thanks. Then I am expecting that we could also have similar issue for the `if (needle_con_cnt == 4)` case in the same function where we do `load_4chr` incrementally with 1 byte step when `isLL` variable is true, right?

2023-06-07 13:05 UTC, VladimirKempik commented
> > > Hi, I searched and found that we have four direct callers of `C2_MacroAssembler::string_indexof_linearscan`: three in file riscv.ad (by string_indexof_conUU, string_indexof_conLL and string_indexof_conUL) and one by `C2_MacroAssembler::string_indexof`. Did you check which one is triggering these unaligned accesses? I am not sure but it looks to me that the three direct callers in file riscv.ad are less likely to have such an issue. If that is true, we might need some distinugish among those callers for better performance.
> > 
> > 
> > Originally, when I found this misaligned load, this code `(this->*load_2chr)(ch2, Address(tmp3), noreg);` was corresponding to `lhu t1, 0(t4)`. So I can say the isLL variable was true.
> 
> Can we simply change the two conditions `if (AvoidUnalignedAccesses) {` added in `C2_MacroAssembler::string_indexof_linearscan` into something like `if (needle_con_cnt == -1 && AvoidUnalignedAccesses) {` and see if this could also resolve the problem?

I can't put whole section ( https://github.com/openjdk/jdk/pull/14320/files#diff-35eb1d2f1e2f0514dd46bd7fbad49ff2c87703d5a3041a6433956df00a3fe6e6L714 ) under AvoidUnalignedAccesses  as it defines label DO3 which is used earlier

2023-06-07 16:59 UTC, VladimirKempik commented
I have made a microtest to test specifically DO2 part of string_indexof_linear
```
diff --git a/test/micro/org/openjdk/bench/java/lang/StringIndexOf.java b/test/micro/org/openjdk/bench/java/lang/StringIndexOf.java
index 57ced6d8e13..33c8d998d8d 100644
--- a/test/micro/org/openjdk/bench/java/lang/StringIndexOf.java
+++ b/test/micro/org/openjdk/bench/java/lang/StringIndexOf.java
@@ -46,6 +46,8 @@ public class StringIndexOf {
     private String shortSub1;
     private String data2;
     private String shortSub2;
+
+    private String shortSub3;
     private String string16Short;
     private String string16Medium;
     private String string16Long;
@@ -64,6 +66,7 @@ public class StringIndexOf {
         shortSub1 = "1";
         data2 = "00001001010100a10110101010010101110101001110110101010010101010010000010111010101010101010a100010010101110111010101101010100010010a100a0010101111111000010101010010101000010101010010101010101110a10010101010101010101010101010";
         shortSub2 = "a";
+        shortSub3 = "a1";
         searchChar = 's';
 
         string16Short = "scar\u01fe1";
@@ -246,6 +249,20 @@ public class StringIndexOf {
         return dummy;
     }
 
+    /**
+     * Benchmarks String.indexOf with a rather big String. Search repeatedly for a matched that is 2 chars but only with
+     * a few matches.
+     */
+    @Benchmark
+    public int advancedWithShortSub3() {
+        int dummy = 0;
+        int index = 0;
+        while ((index = data2.indexOf(shortSub3, index)) > -1) {
+            index++;
+            dummy += index;
+        }
+        return dummy;
+    }
     @Benchmark
     public void constantPattern() {
         String tmp = "simple-hash:SHA-1/UTF-8";
```

Results, v1 - original patch in this PR, v2 - latest update to DO2
```
hifive
Benchmark                            Mode  Cnt     Score    Error  Units
Before
StringIndexOf.advancedWithShortSub3  avgt   25  37302.933 ± 80.306  ns/op
V1
StringIndexOf.advancedWithShortSub3  avgt   25  1362.159 ± 37.021  ns/op
V2
StringIndexOf.advancedWithShortSub3  avgt   25  1248.750 ± 40.432  ns/op


thead
Benchmark                            Mode  Cnt     Score    Error  Units
Before
StringIndexOf.advancedWithShortSub3  avgt   25  632.976 ? 42.601  ns/op
V1
StringIndexOf.advancedWithShortSub3  avgt   25  916.040 ? 45.086  ns/op
V2
StringIndexOf.advancedWithShortSub3  avgt   25  919.363 ? 21.977  ns/op
```

while hifive benefits the update, thead doesn't care and like misaligned way the most

2023-06-07 18:09 UTC, VladimirKempik commented
Numbers on DO4 ( comparing 4 characters at once)
DO4:
```
hifive
Benchmark                                 Mode  Cnt     Score    Error  Units
before
StringIndexOf.advancedWithShortSub4Chars  avgt   25  69514.891 ± 128.730  ns/op
after
StringIndexOf.advancedWithShortSub4Chars  avgt   25  2481.448 ± 13.481  ns/op

thead

Benchmark                                 Mode  Cnt     Score    Error  Units
before
StringIndexOf.advancedWithShortSub4Chars  avgt   25  753.125 ? 2.859  ns/op
after
StringIndexOf.advancedWithShortSub4Chars  avgt   25  741.031 ? 9.075  ns/op
```

2023-06-08 01:01 UTC, feilongjiang requested changes

2023-06-08 01:01 UTC, feilongjiang commented on src/hotspot/cpu/riscv/c2_MacroAssembler_riscv.cpp
> +        //need to erase 1 most significant byte in 32-bit value of ch2
```suggestion
        // need to erase 1 most significant byte in 32-bit value of ch2
```

2023-06-08 01:01 UTC, feilongjiang commented on src/hotspot/cpu/riscv/c2_MacroAssembler_riscv.cpp
> +        slli(ch2, ch2, 16); //2 most significant bytes will be erased by this operation
```suggestion
        slli(ch2, ch2, 16); // 2 most significant bytes will be erased by this operation
```

2023-06-08 02:39 UTC, RealFYang requested changes
Thanks for the update. Would you mind one more tweak? Since needle_chr_shift and haystack_chr_shift could be 0 for the L case, I think we should guard the shift instructions at https://github.com/openjdk/jdk/blob/master/src/hotspot/cpu/riscv/c2_MacroAssembler_riscv.cpp#L634, https://github.com/openjdk/jdk/blob/master/src/hotspot/cpu/riscv/c2_MacroAssembler_riscv.cpp#L637, https://github.com/openjdk/jdk/blob/master/src/hotspot/cpu/riscv/c2_MacroAssembler_riscv.cpp#L679, https://github.com/openjdk/jdk/blob/master/src/hotspot/cpu/riscv/c2_MacroAssembler_riscv.cpp#L700, https://github.com/openjdk/jdk/blob/master/src/hotspot/cpu/riscv/c2_MacroAssembler_riscv.cpp#L724 and https://github.com/openjdk/jdk/blob/master/src/hotspot/cpu/riscv/c2_MacroAssembler_riscv.cpp#L775 with `if (needle_chr_shift)` or `if (haystack_chr_shift)`.

2023-06-08 02:39 UTC, RealFYang commented on src/hotspot/cpu/riscv/c2_MacroAssembler_riscv.cpp
> +  load_long_misaligned(ch2, Address(result), ch1); // can use ch1 as tmpreg here as it will be trashed on next mv command anyway
Suggestion for comment: // can use ch1 as temp register here as it will be trashed by next mv anyway

2023-06-08 02:39 UTC, RealFYang commented on src/hotspot/cpu/riscv/c2_MacroAssembler_riscv.cpp
> +      {
Suggestion for coding style: `if (isLL) {`

2023-06-08 02:51 UTC, RealFYang commented
> @VladimirKempik : Thanks for the update. Would you mind one more tweak? Since `needle_chr_shift` and `haystack_chr_shift` could be 0 for the L case, I think we should guard the shift instructions at https://github.com/openjdk/jdk/blob/master/src/hotspot/cpu/riscv/c2_MacroAssembler_riscv.cpp#L634, https://github.com/openjdk/jdk/blob/master/src/hotspot/cpu/riscv/c2_MacroAssembler_riscv.cpp#L637, https://github.com/openjdk/jdk/blob/master/src/hotspot/cpu/riscv/c2_MacroAssembler_riscv.cpp#L679, https://github.com/openjdk/jdk/blob/master/src/hotspot/cpu/riscv/c2_MacroAssembler_riscv.cpp#L700, https://github.com/openjdk/jdk/blob/master/src/hotspot/cpu/riscv/c2_MacroAssembler_riscv.cpp#L724, https://github.com/openjdk/jdk/blob/master/src/hotspot/cpu/riscv/c2_MacroAssembler_riscv.cpp#L775 with conditions `if (needle_chr_shift)` or `if (haystack_chr_shift)`.

Ah, this won't save us any instructions. Let's change this code snippet: https://github.com/openjdk/jdk/blob/master/src/hotspot/cpu/riscv/c2_MacroAssembler_riscv.cpp#LL754-L757
 into a single line: `slli(tmp3, result_tmp, haystack_chr_shift);`

2023-06-08 05:42 UTC, VladimirKempik commented
> @VladimirKempik : Thanks for the update. Would you mind one more tweak? Since `needle_chr_shift` and `haystack_chr_shift` could be 0 for the L case, I think we should guard the shift instructions at https://github.com/openjdk/jdk/blob/master/src/hotspot/cpu/riscv/c2_MacroAssembler_riscv.cpp#L634, https://github.com/openjdk/jdk/blob/master/src/hotspot/cpu/riscv/c2_MacroAssembler_riscv.cpp#L637, https://github.com/openjdk/jdk/blob/master/src/hotspot/cpu/riscv/c2_MacroAssembler_riscv.cpp#L679, https://github.com/openjdk/jdk/blob/master/src/hotspot/cpu/riscv/c2_MacroAssembler_riscv.cpp#L700, https://github.com/openjdk/jdk/blob/master/src/hotspot/cpu/riscv/c2_MacroAssembler_riscv.cpp#L724, https://github.com/openjdk/jdk/blob/master/src/hotspot/cpu/riscv/c2_MacroAssembler_riscv.cpp#L775 with conditions `if (needle_chr_shift)` or `if (haystack_chr_shift)`.

It's questionable, mv(Xd, Xs) becomes addi(Xd, Xs, 0).
and what is chearper - addi(Xd, Xs,0) or slli(Xd, Xs,0) is an open question.

2023-06-08 06:14 UTC, RealFYang approved these changes
Looks good. Thanks.

2023-06-08 06:17 UTC, VladimirKempik commented
I have asked our HW team, addi sometimes can be cheaper than slli:  addi Xd, Xs, 0 can be resolved by register renaming ( not on every uarch tho), without using ALU. and slli always uses ALU
So it may be worth it to add umbrella for slli in macroassembler, if shift amount is zero - use addi instead.

2023-06-08 06:51 UTC, feilongjiang approved these changes

2023-06-08 08:32 UTC, theRealAph commented
I am very concerned about the increased complexity and maintenance burden caused by these unaligned access patches. While RISC-V is not a mainstream arch at this time, it may become one, and it that happens we'll need something reasonably maintainable.
Sprinkling '`if (AvoidUnalignedAccesses)`' all over the back end is disastrous for readability. I urge you to find a more abstract solution, for example by creating a memory access assembler class and subclassing it as appropriate with aligned and unaligned versions.

2023-06-08 13:27 UTC, VladimirKempik commented
First change, at [Line496](https://github.com/openjdk/jdk/pull/14320/files#diff-35eb1d2f1e2f0514dd46bd7fbad49ff2c87703d5a3041a6433956df00a3fe6e6R496) regresses performance of indexOf based on Boyer-Moore-Horspool algo on thead :
Before:
```
org.openjdk.bench.java.lang.StringIndexOf.advancedWithMediumSub   2790.160 ±  56.442  ns/op
```
After:
```
org.openjdk.bench.java.lang.StringIndexOf.advancedWithMediumSub  3377.943 ± 42.496 ns/op
```

I think this could be improved

Currently, when we compare a needle and a region of haystack, we first read last 8 bytes from both regions then compare them, then if they match, compare rest byte per byte.
Reading 8 bytes from haystack is not always aligned or misaligned, we can read 4 or 2 bytes for first comparision, reducing wasted reads from haystack

2023-06-08 20:46 UTC, theRealAph commented
> > I am very concerned about the increased complexity and maintenance burden caused by these unaligned access patches. While RISC-V is not a mainstream arch at this time, it may become one, and it that happens we'll need something reasonably maintainable. Sprinkling '`if (AvoidUnalignedAccesses)`' all over the back end is disastrous for readability. I urge you to find a more abstract solution, for example by creating a memory access assembler class and subclassing it as appropriate with aligned and unaligned versions.
> 
> Hello, do you mean things like load_XXXX_misaligned ( e.g. https://github.com/openjdk/jdk/blob/master/src/hotspot/cpu/riscv/macroAssembler_riscv.cpp#L1735 ) or more complicated things ?

That's certainly a good start, although I believe its implementation could be much improved. But everywhere you see `if (AvoidUnalignedAccesses)` is potentially a candidate for factoring out the parts and moving them into a misaligned memory access class.

2023-06-13 21:29 UTC, VladimirKempik commented
jmh results, StringIndexOf
advancedWithShortSubXChars - three new tests which test speed of linear search with needs of size X

before:
```
Benchmark                                                 (loops)  (pathCnt)  (rngSeed)  Mode  Cnt       Score     Error  Units
StringIndexOf.advancedWithMediumSub                           N/A        N/A        N/A  avgt   25   47184.829 ± 227.340  ns/op
StringIndexOf.advancedWithShortSub1                           N/A        N/A        N/A  avgt   25    4121.931 ± 194.659  ns/op
StringIndexOf.advancedWithShortSub2                           N/A        N/A        N/A  avgt   25     992.714 ±  24.638  ns/op
StringIndexOf.advancedWithShortSub2Chars                      N/A        N/A        N/A  avgt   25   37315.528 ±  61.079  ns/op
StringIndexOf.advancedWithShortSub3Chars                      N/A        N/A        N/A  avgt   25   37316.547 ±  26.079  ns/op
StringIndexOf.advancedWithShortSub4Chars                      N/A        N/A        N/A  avgt   25   69367.409 ± 117.164  ns/op
StringIndexOf.constantPattern                                 N/A        N/A        N/A  avgt   25      73.671 ±   3.551  ns/op
StringIndexOf.searchChar16LongSuccess                         N/A        N/A        N/A  avgt   25     251.513 ±   3.103  ns/op
StringIndexOf.searchChar16LongWithOffsetSuccess               N/A        N/A        N/A  avgt   25     258.523 ±   2.925  ns/op
StringIndexOf.searchChar16MediumSuccess                       N/A        N/A        N/A  avgt   25     134.067 ±   3.635  ns/op
StringIndexOf.searchChar16MediumWithOffsetSuccess             N/A        N/A        N/A  avgt   25     146.327 ±   3.257  ns/op
StringIndexOf.searchChar16ShortSuccess                        N/A        N/A        N/A  avgt   25      35.564 ±   2.468  ns/op
StringIndexOf.searchChar16ShortWithOffsetSuccess              N/A        N/A        N/A  avgt   25      40.607 ±   3.270  ns/op
StringIndexOf.searchCharLongSuccess                           N/A        N/A        N/A  avgt   25     122.948 ±   4.485  ns/op
StringIndexOf.searchCharMediumSuccess                         N/A        N/A        N/A  avgt   25      63.505 ±   2.645  ns/op
StringIndexOf.searchCharShortSuccess                          N/A        N/A        N/A  avgt   25      33.107 ±   2.404  ns/op
StringIndexOf.searchString16LongLatinSuccess                  N/A        N/A        N/A  avgt   25     504.675 ±   6.297  ns/op
StringIndexOf.searchString16LongSuccess                       N/A        N/A        N/A  avgt   25     628.733 ±   3.652  ns/op
StringIndexOf.searchString16LongWithOffsetLatinSuccess        N/A        N/A        N/A  avgt   25     325.615 ±   3.355  ns/op
StringIndexOf.searchString16LongWithOffsetSuccess             N/A        N/A        N/A  avgt   25     343.145 ±   3.068  ns/op
StringIndexOf.searchString16MediumLatinSuccess                N/A        N/A        N/A  avgt   25     226.349 ±   3.635  ns/op
StringIndexOf.searchString16MediumSuccess                     N/A        N/A        N/A  avgt   25     279.963 ±   3.536  ns/op
StringIndexOf.searchString16MediumWithOffsetLatinSuccess      N/A        N/A        N/A  avgt   25     161.672 ±   3.024  ns/op
StringIndexOf.searchString16MediumWithOffsetSuccess           N/A        N/A        N/A  avgt   25     162.722 ±   3.598  ns/op
StringIndexOf.searchString16ShortLatinSuccess                 N/A        N/A        N/A  avgt   25     322.307 ±   3.027  ns/op
StringIndexOf.searchString16ShortSuccess                      N/A        N/A        N/A  avgt   25      55.243 ±   3.518  ns/op
StringIndexOf.searchString16ShortWithOffsetLatinSuccess       N/A        N/A        N/A  avgt   25      55.825 ±   2.582  ns/op
StringIndexOf.searchString16ShortWithOffsetSuccess            N/A        N/A        N/A  avgt   25      54.268 ±   3.709  ns/op
StringIndexOf.success                                         N/A        N/A        N/A  avgt   25      80.776 ±   2.500  ns/op
StringIndexOf.successBig                                      N/A        N/A        N/A  avgt   25    6283.167 ±  11.876  ns/op
StringIndexOfChar.latin1_AVX2_String                       100000       1000       1999  avgt   25  206802.394 ± 598.649  ns/op
StringIndexOfChar.latin1_AVX2_char                         100000       1000       1999  avgt   25  103587.559 ± 214.802  ns/op
StringIndexOfChar.latin1_SSE4_String                       100000       1000       1999  avgt   25  121714.481 ± 118.594  ns/op
StringIndexOfChar.latin1_SSE4_char                         100000       1000       1999  avgt   25   75014.737 ± 178.044  ns/op
StringIndexOfChar.latin1_Short_String                      100000       1000       1999  avgt   25  116975.364 ±  90.326  ns/op
StringIndexOfChar.latin1_Short_char                        100000       1000       1999  avgt   25   81844.387 ± 230.281  ns/op
StringIndexOfChar.latin1_mixed_String                      100000       1000       1999  avgt   25  210860.343 ± 159.635  ns/op
StringIndexOfChar.latin1_mixed_char                        100000       1000       1999  avgt   25  117095.518 ± 204.476  ns/op
StringIndexOfChar.utf16_AVX2_String                        100000       1000       1999  avgt   25  100868.093 ± 136.887  ns/op
StringIndexOfChar.utf16_AVX2_char                          100000       1000       1999  avgt   25   80257.944 ± 208.123  ns/op
StringIndexOfChar.utf16_SSE4_String                        100000       1000       1999  avgt   25   74831.080 ± 284.069  ns/op
StringIndexOfChar.utf16_SSE4_char                          100000       1000       1999  avgt   25   64963.525 ± 113.680  ns/op
StringIndexOfChar.utf16_Short_String                       100000       1000       1999  avgt   25   72531.734 ± 209.899  ns/op
StringIndexOfChar.utf16_Short_char                         100000       1000       1999  avgt   25   70835.907 ± 202.187  ns/op
StringIndexOfChar.utf16_mixed_String                       100000       1000       1999  avgt   25  162457.612 ± 178.987  ns/op
StringIndexOfChar.utf16_mixed_char                         100000       1000       1999  avgt   25  149974.738 ± 320.802  ns/op
```

Hifive, after:
```
Benchmark                                                 (loops)  (pathCnt)  (rngSeed)  Mode  Cnt       Score     Error  Units
StringIndexOf.advancedWithMediumSub                           N/A        N/A        N/A  avgt   25    4276.564 ±  39.149  ns/op
StringIndexOf.advancedWithShortSub1                           N/A        N/A        N/A  avgt   25    4149.350 ± 209.233  ns/op
StringIndexOf.advancedWithShortSub2                           N/A        N/A        N/A  avgt   25    1128.838 ±  20.157  ns/op
StringIndexOf.advancedWithShortSub2Chars                      N/A        N/A        N/A  avgt   25    1277.692 ±  13.031  ns/op
StringIndexOf.advancedWithShortSub3Chars                      N/A        N/A        N/A  avgt   25    1313.186 ±   9.654  ns/op
StringIndexOf.advancedWithShortSub4Chars                      N/A        N/A        N/A  avgt   25    2488.046 ±   8.964  ns/op
StringIndexOf.constantPattern                                 N/A        N/A        N/A  avgt   25      79.567 ±   5.082  ns/op
StringIndexOf.searchChar16LongSuccess                         N/A        N/A        N/A  avgt   25     251.484 ±   3.302  ns/op
StringIndexOf.searchChar16LongWithOffsetSuccess               N/A        N/A        N/A  avgt   25     256.214 ±   3.778  ns/op
StringIndexOf.searchChar16MediumSuccess                       N/A        N/A        N/A  avgt   25     133.622 ±   3.497  ns/op
StringIndexOf.searchChar16MediumWithOffsetSuccess             N/A        N/A        N/A  avgt   25     139.377 ±   3.008  ns/op
StringIndexOf.searchChar16ShortSuccess                        N/A        N/A        N/A  avgt   25      35.788 ±   2.936  ns/op
StringIndexOf.searchChar16ShortWithOffsetSuccess              N/A        N/A        N/A  avgt   25      37.000 ±   2.983  ns/op
StringIndexOf.searchCharLong [...]

2023-06-15 06:21 UTC, VladimirKempik commented
tier1/2 clean, so
/integrate

2023-06-15 06:22 UTC, closed without merging