8309890: TestStringDeduplicationInterned.java waits for the wrong condition
openjdk/jdk pull request #14437
Opened 2023-06-13 05:48 UTC by stefank

There's a section in the test that waits up to 10 seconds for a string to be deduplicated and then does a final verification that the string was correctly deduplicated. However, the initial waiting gets passed the wrong comparison string, which has the effect that this test always waits for 10 seconds before proceeding.

The problem is here:
```
            if (!waitForDeduplication(dupString3, baseString)) {
                if (getValue(dupString3) != getValue(internedString)) {
```
where the first line should say:
```
            if (!waitForDeduplication(dupString3, internedString)) { 
```

2023-06-13 06:27 UTC, xmas92 approved these changes

2023-06-13 07:20 UTC, kimbarrett requested changes

2023-06-13 09:12 UTC, stefank commented on test/hotspot/jtreg/gc/stringdedup/TestStringDeduplicationTools.java
>                  if (getValue(dupString3) != getValue(internedString)) {
I've updated the test.

2023-06-13 13:34 UTC, kimbarrett approved these changes
Looks good.

2023-06-14 05:57 UTC, xmas92 approved these changes

2023-06-14 06:29 UTC, stefank commented
Thanks for the reviews!
/integrate

2023-06-14 06:30 UTC, closed without merging