8309632: JDK 21 RDP1 L10n resource files update
openjdk/jdk pull request #14430
Opened 2023-06-12 22:00 UTC by justin-curtis-lu

Please review this PR which updates the JDK's localized resources since the previous L10n translation drop (1/26).

To help with reviewing the changes, @jonathan-gibbons created a tool which displays the localized changes next to the original file's changes in UTF-8 native. Those files can be viewed [here](https://cr.openjdk.org/~jlu/output/) 

For example,

<img width="1081" alt="image" src="https://github.com/openjdk/jdk21/assets/67398801/e68a48a8-916e-4860-afb0-526924c6a3d3">

Please note that the HTML files only apply to .properties, and not .java resources.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8309632](https://bugs.openjdk.org/browse/JDK-8309632): JDK 21 RDP1 L10n resource files update (**Bug** - P3)

### Reviewers
 * [Naoto Sato](https://openjdk.org/census#naoto) (@naotoj - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/14430/head:pull/14430` \
`$ git checkout pull/14430`

Update a local copy of the PR: \
`$ git checkout pull/14430` \
`$ git pull https://git.openjdk.org/jdk.git pull/14430/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 14430`

View PR using the GUI difftool: \
`$ git pr show -t 14430`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/14430.diff">https://git.openjdk.org/jdk/pull/14430.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/14430#issuecomment-1588172394)

2023-06-12 22:13 UTC, justin-curtis-lu commented
@naotoj @wangweij @sormuras could you please review the changes that affect the languages you are familiar with when you have the chance. Please use the HTML files for this, as they will be in UTF-8 native and not unicode escaped sequences.

@prrace @jonathan-gibbons @pavelrappo @lahodaj @wangweij @igraves @AlanBateman @eirbjo could you please review the modules / changes you are familiar with, thank you.

2023-06-12 22:17 UTC, eirbjo commented on src/jdk.jartool/share/classes/sun/tools/jar/resources/jar_de.properties
> +main.help.opt.any.file=\  -f, --file=FILE            Der Name der Archivdatei. Wenn Sie dies lauslassen, wird entweder stdin oder\n                             stdout verwendet, je nach Vorgang\n
This change looks suspicious to me. The English word used is “omitted”. “Auslassen” is to “Leave out”, while “lauslassen” is to “let go”. A native German speaker should confirm, I have only high school level German..

2023-06-13 18:38 UTC, naotoj reviewed
Left some comments on the translations mainly in Japanese. It is now very easy to look at the l10n changes in the generated HTML. One small comment to the tool is that it would be nice if the order in HTML (alphabetically sorted currently) aligns with the order in the actual resource file. It is a great improvement anyways.

2023-06-13 18:38 UTC, naotoj commented on src/jdk.compiler/share/classes/com/sun/tools/javac/resources/compiler_ja.properties
> +
The translation of "well-formed" is incorrect. It is not 整数式

2023-06-13 18:38 UTC, naotoj commented on src/java.desktop/macosx/classes/com/apple/laf/resources/aqua_ja.properties
> +FileChooser.chooseButtonToolTip.textAndMnemonic=\u9078\u629E\u3057\u305F\u30D5\u30A1\u30A4\u30EB\u3092\u8FFD\u52A0\u3057\u307E\u3059
The translation seems wrong. It means to *add* the selected file, which is not the same meaning as in English file

2023-06-13 18:38 UTC, naotoj commented on src/jdk.compiler/share/classes/com/sun/tools/javac/resources/compiler_ja.properties
> +
These translations are very cryptic. Cannot understand it at first hand.

2023-06-13 18:50 UTC, justin-curtis-lu commented on src/jdk.compiler/share/classes/com/sun/tools/javac/resources/compiler_de.properties
> +compiler.err.annotation.unrecognized.attribute.name=Annotation @{0} weist das unbekannte Attribut "{1}" auf
I will consult the language specialist on this. I remember in previous discussions that certain languages would format punctuation differently, but let ask about this specific instance.

2023-06-13 18:53 UTC, justin-curtis-lu commented on src/jdk.compiler/share/classes/com/sun/tools/javac/resources/compiler_ja.properties
> +
For translations that are incorrect, I can file a bug against the tool. Such a fix would probably not happen soon, can you suggest an alternative for now?

2023-06-13 20:21 UTC, naotoj requested changes
Left some suggestions. Should be looked at by translators later.

2023-06-13 20:21 UTC, naotoj commented on src/jdk.compiler/share/classes/com/sun/tools/javac/resources/compiler_ja.properties
> +compiler.warn.possible.this.escape=\u30B5\u30D6\u30AF\u30E9\u30B9\u524D\u306B\u6307\u5B9A\u53EF\u80FD\u306A''this''\u30A8\u30B9\u30B1\u30FC\u30D7\u306F\u5B8C\u5168\u306B\u521D\u671F\u5316\u3055\u308C
```suggestion
compiler.warn.possible.this.escape=\u30b5\u30d6\u30af\u30e9\u30b9\u304c\u521d\u671f\u5316\u3055\u308c\u308b\u524d\u306e''this''\u30a8\u30b9\u30b1\u30fc\u30d7\u306e\u53ef\u80fd\u6027\u304c\u3042\u308a\u307e\u3059
```

2023-06-13 20:21 UTC, naotoj commented on src/jdk.compiler/share/classes/com/sun/tools/javac/resources/compiler_ja.properties
> +compiler.warn.possible.this.escape.location=\u4E8B\u524D\u306B\u6307\u5B9A\u53EF\u80FD\u306A''this''\u30A8\u30B9\u30B1\u30FC\u30D7\u306F\u547C\u51FA\u3057\u3092\u4ECB\u3057\u3066\u3053\u3053\u306B\u5
```suggestion
compiler.warn.possible.this.escape.location=\u4e8b\u524d\u306e''this''\u30a8\u30b9\u30b1\u30fc\u30d7\u306f\u3053\u306e\u547c\u3073\u51fa\u3057\u3067\u51fa\u73fe\u3057\u307e\u3059
```

2023-06-13 20:21 UTC, naotoj commented on src/jdk.compiler/share/classes/com/sun/tools/javac/resources/compiler_ja.properties
> +compiler.err.string.template.is.not.well.formed=\u6587\u5B57\u5217\u30C6\u30F3\u30D7\u30EC\u30FC\u30C8\u304C\u6574\u5F62\u5F0F\u3067\u306F\u3042\u308A\u307E\u305B\u3093
```suggestion
compiler.err.string.template.is.not.well.formed=\u6587\u5b57\u5217\u30c6\u30f3\u30d7\u30ec\u30fc\u30c8\u304c\u9069\u683c\u3067\u306f\u3042\u308a\u307e\u305b\u3093
```

2023-06-13 20:21 UTC, naotoj commented on src/jdk.compiler/share/classes/com/sun/tools/javac/resources/compiler_ja.properties
> +compiler.err.text.block.template.is.not.well.formed=\u30C6\u30AD\u30B9\u30C8\u30FB\u30D6\u30ED\u30C3\u30AF\u30FB\u30C6\u30F3\u30D7\u30EC\u30FC\u30C8\u304C\u6574\u5F62\u5F0F\u3067\u306F\u3042\u308A\u3
```suggestion
compiler.err.text.block.template.is.not.well.formed=\u30c6\u30ad\u30b9\u30c8\u30fb\u30d6\u30ed\u30c3\u30af\u30fb\u30c6\u30f3\u30d7\u30ec\u30fc\u30c8\u304c\u9069\u683c\u3067\u306f\u3042\u308a\u307e\u305b\u3093
```

2023-06-13 21:00 UTC, justin-curtis-lu commented on src/java.desktop/macosx/classes/com/apple/laf/resources/aqua_ja.properties
> +FileChooser.chooseButtonToolTip.textAndMnemonic=\u9078\u629E\u3057\u305F\u30D5\u30A1\u30A4\u30EB\u3092\u8FFD\u52A0\u3057\u307E\u3059
Thank you Naoto, all your recommended translations have been updated. The HTML diffs have also been updated as well.

2023-06-13 22:04 UTC, justin-curtis-lu commented
Thank you for the review @wangweij,

I have addressed these recommendations

>     * `src/jdk.compiler/share/classes/com/sun/tools/javac/resources/javac`:
> 
> 
> `javac.opt.Xlint.desc.output-file-clash`: "native header files" is translated into "本机标头文件". The "本机" is strange, I'd rather just say "头文件" as there is no non-native header file.
> 
>     * `src/jdk.jdeps/share/classes/com/sun/tools/javap/resources/javap`
> 
> 
> I don't think the new translation is better than the old one.

For the other comments, I will bring them to the language specialist for updated translations. Ideally we can get those in for this translation drop, but if not, they can go in during the second translation drop during RDP2. 

I am also hesitant to make too many manual changes, as they will just get overwritten by the tool in the future, so it's best to get it fixed in the tool first.

2023-06-14 00:06 UTC, naotoj approved these changes
Looks good, Justin

2023-06-14 16:21 UTC, justin-curtis-lu commented on src/jdk.compiler/share/classes/com/sun/tools/javac/resources/compiler_de.properties
> +compiler.err.annotation.unrecognized.attribute.name=Annotation @{0} weist das unbekannte Attribut "{1}" auf
The language specialist confirmed the double quotes are locale specific for de.

2023-06-15 19:42 UTC, justin-curtis-lu commented
/integrate

2023-06-15 19:43 UTC, closed without merging

2023-06-16 15:06 UTC, jonathan-gibbons commented
> Left some comments on the translations mainly in Japanese. It is now very easy to look at the l10n changes in the generated HTML. One small comment to the tool is that it would be nice if the order in HTML (alphabetically sorted currently) aligns with the order in the actual resource file. It is a great improvement anyways.

1. It is not easy to recover the order in the actual resource file: the contents are read into a `Properties` object which uses a `Hashtable` to store the data. 
2. There is no guarantee that the order is the same in all the resource files, so we would have to choose one, presumably the default one, to determine the presentation order.

2023-06-16 17:12 UTC, naotoj commented
Makes sense. Thanks for the explanation @jonathan-gibbons