8308499
openjdk/jdk pull request #14480
Opened 2023-06-14 21:24 UTC by plummercj

The test gets overloaded with MethodExitEvents, causing them to queue up (in the JDI queue) and continue to be processed by the test after the debuggee exits. This results in a VMDisconnectedException when the test tries to do the following after getting an event:

`    String str = ((MethodExitEvent)event).location().declaringType().name(); `

The test is suppose to add filters to execlude events for all non-test classes, but it is only filtering `java.*` and `sun.*`. There are also a very large number of `jdk.*` events coming in, and this is what is causing the event backlog and the processing of events after disconnect. Filtering out `jdk.*` events reduces the total number of events to a few dozen, and the test passes.

More details can be found in the CR.

Testing in progress: tier5 svc testing, and also running the failing test on all platforms (both debug and product).

2023-06-14 21:54 UTC, lmesnik requested changes

2023-06-14 21:54 UTC, lmesnik commented on test/hotspot/jtreg/vmTestbase/nsk/jdi/MethodExitRequest/addClassExclusionFilter/filter001.java
> +    private String classExclName3 = "jdk";
The fix is reasonable. However,
I think it would be better to use List<String> with List.of(...) and list.contains() to filter exclusions.

2023-06-15 03:18 UTC, lmesnik commented on test/hotspot/jtreg/vmTestbase/nsk/jdi/MethodExitRequest/addClassExclusionFilter/filter001.java
> +    private String classExclName3 = "jdk";
If you think it is easier, then fine.

2023-06-15 03:18 UTC, lmesnik approved these changes

2023-06-15 08:28 UTC, kevinjwalls approved these changes

2023-06-15 18:04 UTC, plummercj commented
Thanks for the reviews Leonid and Kevin!

/integrate

2023-06-15 19:12 UTC, closed without merging