8301489: ShortLoopOptimizer might lift instructions before their inputs
openjdk/jdk pull request #14492
Opened 2023-06-15 11:13 UTC by danielogh

ShortLoopOptimizer might lift instructions before their inputs on some graph shapes. We propose adding a check that the insertion point for an instruction that is a candidate for hoisting should not be higher up the dominator tree than any inputs to the instruction.

Testing: tier1-tier3.

Additional testing: observed that `(cur_invariant && !v.is_valid())` never occurs on tier1-tier3 before the added test case.
Also verified that the depth check is equivalent to `(*vp->block() == _insert->block()) || dominates(*vp, _insert)` on all of tier1-tier3.

Failure case: in the attached image the `arraylength` instruction from B10 is lifted to B0, as the dominator of B10 is calculated as B0. This is based on the logic in [`ComputeLinearScanOrder::compute_dominator_impl`](https://github.com/openjdk/jdk/blob/master/src/hotspot/share/c1/c1_IR.cpp#L801).  But the array input is in Block 3. This is later spotted in `c1_LIRAssembler.cpp` with `Error: ShouldNotReachHere()`. We can reproduce the error on other instructions too -- the reader may refer to the test case provided.

![image](https://github.com/openjdk/jdk/assets/111436254/9130516c-073d-45d1-a38a-af776e5e6672)

2023-06-19 06:30 UTC, TobiHartmann reviewed
Great work investigating this, Daniel! 

From your comments in JBS, it seems that the underlying issue is additional exception edges in the graph that affect dominator computation. Could you elaborate a bit more on that with respect to the example that you provided in the PR description?

I'm not an expert in C1 though (paging @veresov and @rwestrel as the author of JDK-7153771).

Thanks,
Tobias

2023-06-19 08:54 UTC, robcasloz requested changes
Good catch, analysis, and regression test Daniel. Great that you could generalize the fix to cover all other LICM cases. Just a couple of comments/suggestions.

2023-06-19 08:54 UTC, robcasloz commented on src/hotspot/share/c1/c1_ValueMap.cpp
> +class CheckInsertionPoint: public ValueVisitor {
For consistency with other similar cases in `c1_ValueMap.cpp`: 
```suggestion
class CheckInsertionPoint : public ValueVisitor {
```

2023-06-19 08:54 UTC, robcasloz commented on src/hotspot/share/c1/c1_ValueMap.cpp
> +    cur->input_values_do(&v);
For compilation efficiency, would it be possible to perform this computation only when `cur_invariant` holds? You could for example encapsulate the creation of `v`, call to `cur->input_values_do(&v)`, and `v.is_valid()` check into an auxiliary function `is_dominated_by_inputs(_insertion_point, cur)` or similar and call that function below (`if (cur_invariant && is_dominated_by_inputs(_insertion_point, cur)) {`).

2023-06-20 08:32 UTC, danielogh commented on src/hotspot/share/c1/c1_ValueMap.cpp
> +  void visit(Value* vp) {
I am not sure if this is possible without changing the ValueVisitor ([ref](https://java.se.oracle.com/source/xref/jdk-jdk/jdk-open/src/hotspot/share/c1/c1_Instruction.hpp#123)) itself

2023-06-20 08:38 UTC, danielogh commented
> Great work investigating this, Daniel!
> 
> From your comments in JBS, it seems that the underlying issue is additional exception edges in the graph that affect dominator computation. Could you elaborate a bit more on that with respect to the example that you provided in the PR description?
> 
> I'm not an expert in C1 though (paging @veresov and @rwestrel as the author of JDK-7153771).
> 
> Thanks, Tobias

Thank you very much for review! 

My understanding is, this might have been introduced in JDK-7153771, where we have extra edges to the exception handler of all successors during dominator calculation -- `Additional edge to xhandler of all our successors`. The client RangeCheckElimination optimization needed this additional information, but the short loop optimization was not updated accordingly. In this specific case, I observed using print debugging and -XX:TraceLinearScanLevel=4, that the dominator of B10 is being calculated as common_dominator(B7, B1). But B1 has dominator B0 because of the extra edge from B14 to B1 (the exception handler of B3). The short loop optimization lifts loop invariant instructions to the dominator of the loop header, which in this case becomes B0.

2023-06-21 11:57 UTC, robcasloz approved these changes
Thanks for addressing the suggestions and for the additional explanation, looks good!

2023-06-23 07:06 UTC, TobiHartmann commented on src/hotspot/share/c1/c1_ValueMap.cpp
> +  void visit(Value* vp) {
Right, makes sense.

2023-06-23 07:13 UTC, TobiHartmann approved these changes
Looks good to me.

2023-06-27 06:41 UTC, danielogh commented
/integrate

2023-06-27 06:53 UTC, danielogh commented
Thanks Roberto and Tobias for review. Thanks Roberto for additional help with PR.

2023-06-27 07:04 UTC, TobiHartmann commented
/sponsor

2023-06-27 07:05 UTC, closed without merging