8251358: Clean up Access configuration after Shenandoah barrier change
openjdk/jdk pull request #146
Opened 2020-09-14 05:16 UTC by adityamandaleeka

This change removes a bunch of code that is no longer necessary after the Shenandoah barrier changes, including the `SUPPORT` macros in barrierSetConfig.hpp and code using them. `Access::resolve` and associated code have also been removed, and callers have been modified.

Testing done:
tier1
hotspot_gc_shenandoah

2020-09-14 05:20 UTC, adityamandaleeka commented
/label remove serviceability

2020-09-14 05:20 UTC, adityamandaleeka commented
/label add gc

2020-09-14 05:21 UTC, adityamandaleeka commented
/label remove hotspot

2020-09-14 05:21 UTC, adityamandaleeka commented
/label add hotspot-gc

2020-09-14 13:20 UTC, shipilev commented
/label add shenandoah

2020-09-14 21:40 UTC, adityamandaleeka commented
@kimbarrett Can you please take a look when you have time?

2020-09-15 09:37 UTC, fisk requested changes
Thanks for fixing this. It's nice to see build-time decorators go. Naturally, when removing the resolve() function, we can also remove a bunch of "_raw" functions in the runtime. Like there is no longer a need to distinguish between field_addr and field_addr_raw. Or between base and base_raw. They were all introduced so that one of them could apply the resolve barrier. The same goes for mark vs mark_raw and the other related mark accessor functions on oopDesc. I think we want to get rid of that too, right?

2020-09-16 06:32 UTC, adityamandaleeka commented
@fisk Good point. It's clear that the field_addr and base ones can be changed, and I'll do that in the next update I send. I'll take a closer look at the marking functions you mentioned as well. I want to understand the decorators they're using and see whether they still do anything meaningful before I get rid of them.

2020-09-16 06:38 UTC, fisk commented
The only supported decorators for primitives is memory ordering decorators. These functions use MO_RELAXED. Specifying MO_RELAXED is equivalent to using Atomic::load/store.

2020-09-23 01:10 UTC, adityamandaleeka commented
@fisk Thanks again for the feedback, and sorry for the delay (it's been a very busy week!). I've pushed an update that cleans up a bunch of the `_raw` stuff.

2020-09-23 11:53 UTC, rkennke approved these changes
Looks good to me! Good to see those unused code paths go! Thanks!

2020-09-24 00:57 UTC, adityamandaleeka commented
Thanks @rkennke . I will also need a sponsor for this change. Can you or @fisk please do that?

2020-09-24 06:03 UTC, shipilev requested changes
No, wait a second. I agree with some `_raw` removals, but not the other. The point of many `_raw` calls is using them from internal GC code when we *know* barriers are not required (because GC already knows in which state the object is in) or even correct to perform (for example, setting marks on incomplete objects). Changing e.g. `set_mark_raw` to `set_mark` on those paths exposes objects to GC barriers.

2020-09-24 06:03 UTC, shipilev commented on src/hotspot/share/gc/g1/g1FullGCCompactTask.cpp
> +  oop(destination)->init_mark();
For example, here.

2020-09-24 06:03 UTC, shipilev commented on src/hotspot/share/gc/g1/g1FullGCCompactTask.cpp
> +          obj->init_mark();
For example, here.

2020-09-24 06:03 UTC, shipilev commented on src/hotspot/share/gc/parallel/psPromotionLAB.cpp
> +  filler_oop->set_mark(markWord::prototype());
...or here.

2020-09-24 06:27 UTC, fisk commented
> No, wait a second. I agree with some `_raw` removals, but not the other. The point of many `_raw` calls is using them from internal GC code when we *know* barriers are not required (because GC already knows in which state the object is in) or even correct to perform (for example, setting marks on incomplete objects). Changing e.g. `set_mark_raw` to `set_mark` on those paths exposes objects to GC barriers.

We did not have said raw functions before Shenandoah. They were added to distinguish between barriers vs no barriers. And people would have to figure out which one to call. Now we never use barriers, so there is no difference. Sure the GC code knows there are no barriers. Agreed. But so does everybody else. Because we are removing barriers for primitives support. And mark words are simply primitives. Or do you have any other need for actually having barriers on mark word reads and writes?

2020-09-24 06:35 UTC, shipilev commented
> We did not have said raw functions before Shenandoah. 

Right. I misremembered the history here. JDK-8199735 added these `_raw` methods and this effectively reverts it.

2020-09-24 06:35 UTC, shipilev approved these changes

2020-09-24 06:39 UTC, shipilev commented
Speaking of JDK-8199735, `cas_set_mark_raw` is also unnecessary now?

2020-09-24 06:41 UTC, fisk commented
> Speaking of JDK-8199735, `cas_set_mark_raw` is also unnecessary now? 

Yes, good catch. I found 2 more mark word accessors that I commented on.

2020-09-24 06:58 UTC, adityamandaleeka commented
Thanks @shipilev and @fisk . I had left `cas_set_mark_raw` alone since there's a caller that specifies `memory_order_release` and I didn't want to change any behavior with the cleanup: https://github.com/openjdk/jdk/blob/master/src/hotspot/share/gc/parallel/psPromotionManager.inline.hpp#L242

That said, I haven't looked into how necessary that is; perhaps it's okay to change it to relaxed order.

@fisk Thanks for taking another look. I don't see the new comments you added yet. Have you submitted them?

2020-09-24 07:25 UTC, fisk requested changes
Oops seems like I didn't publish the comments somehow.

2020-09-24 07:27 UTC, fisk commented
> Thanks @shipilev and @fisk . I had left `cas_set_mark_raw` alone since there's a caller that specifies `memory_order_release` and I didn't want to change any behavior with the cleanup: https://github.com/openjdk/jdk/blob/master/src/hotspot/share/gc/parallel/psPromotionManager.inline.hpp#L242
> 
> 
> 
> That said, I haven't looked into how necessary that is; perhaps it's okay to change it to relaxed order.
> 
> 
> 
> @fisk Thanks for taking another look. I don't see the new comments you added yet. Have you submitted them?
> 
> 
> 
> I'll follow up on this PR tomorrow since it's quite late here 😄 
> 
> 

A lot of thought has gone into the memory ordering flags. This change should definitely not change any of that. Having said that, I can't see why we can not rename raw functions to not raw functions, while maintaining the same memory ordering.

2020-09-25 04:10 UTC, adityamandaleeka commented
That makes sense, and I just pushed an update that renames those functions. `cas_set_mark_raw` had a default argument for the memory order which I've turned into a required argument in order to disambiguate after the rename. The only caller that was relying on the default argument was in the Shenandoah forwarding code, and I've updated it to pass in the memory order.

2020-09-28 20:31 UTC, adityamandaleeka commented
@fisk Can you please take another look at this when you get a chance?

2020-09-28 20:33 UTC, fisk approved these changes
Looks good.

2020-09-28 20:42 UTC, adityamandaleeka commented
Thank you!

2020-09-28 20:42 UTC, adityamandaleeka commented
/integrate

2020-09-28 21:39 UTC, adityamandaleeka commented
Can one of the reviewers please sponsor the change?

2020-09-29 07:24 UTC, shipilev commented
/sponsor

2020-09-29 07:25 UTC, closed without merging