8309140: ResourceHashtable failed "assert(~(_allocation_t[0] | allocation_mask) == (uintptr_t)this) failed: lost resource object"
openjdk/jdk pull request #14601
Opened 2023-06-21 17:49 UTC by gujustin1

Please review the change to ResourceHashtables from statically allocated to CHeap allocated at initialization time. Ran Mach5 testing tiers 1-4 that all passed. See CR for more details.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8309140](https://bugs.openjdk.org/browse/JDK-8309140): ResourceHashtable failed "assert(~(_allocation_t[0] | allocation_mask) == (uintptr_t)this) failed: lost resource object" (**Bug** - P3)

### Reviewers
 * [Coleen Phillimore](https://openjdk.org/census#coleenp) (@coleenp - **Reviewer**) ⚠️ Review applies to [958c6048](https://git.openjdk.org/jdk/pull/14601/files/958c604811f6fc07e9e930407bdf0ed3548cb43b)
 * [Matias Saavedra Silva](https://openjdk.org/census#matsaave) (@matias9927 - Committer) ⚠️ Review applies to [958c6048](https://git.openjdk.org/jdk/pull/14601/files/958c604811f6fc07e9e930407bdf0ed3548cb43b)
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/14601/head:pull/14601` \
`$ git checkout pull/14601`

Update a local copy of the PR: \
`$ git checkout pull/14601` \
`$ git pull https://git.openjdk.org/jdk.git pull/14601/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 14601`

View PR using the GUI difftool: \
`$ git pr show -t 14601`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/14601.diff">https://git.openjdk.org/jdk/pull/14601.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/14601#issuecomment-1602979165)

2023-06-22 17:01 UTC, coleenp requested changes
This looks good! I have a couple of comments to fix.

2023-06-22 17:01 UTC, coleenp commented on src/hotspot/share/runtime/sharedRuntime.cpp
> +    _adapter_handler_table = new (mtClass) AHTable();
This should be mtCode not mtClass since the adapter_handler_table belongs to the mtCode (NMT code tracking category).

2023-06-26 13:55 UTC, coleenp commented on src/hotspot/share/classfile/verifier.cpp
> -
Sorry I mean the line should be added back.

2023-06-26 14:01 UTC, coleenp approved these changes
These changes look really good - thank you for working on these hashtables!

2023-06-26 15:02 UTC, matias9927 reviewed
Overall, this looks good! I just have one comment

2023-06-26 18:30 UTC, coleenp approved these changes
The name changes look good.

2023-06-27 07:03 UTC, dholmes-ora requested changes
Looks good - thanks for fixing this. One typo in a type-name that must be fixed first.

2023-06-28 07:53 UTC, dholmes-ora approved these changes
Looks good. Thanks.

2023-06-28 17:08 UTC, gujustin1 commented
Thanks @coleenp @dholmes-ora @matias9927 for reviewing my change!
/integrate

2023-06-28 17:10 UTC, closed without merging

2023-07-05 19:14 UTC, coleenp commented
/backport 21

2023-07-05 19:17 UTC, coleenp commented
/backport openjdk/jdk21