6594730: UUID.getVersion() is only meaningful for Leach-Salz variant
openjdk/jdk pull request #1467
Opened 2020-11-26 18:51 UTC by Fleshgrinder

2020-11-26 19:03 UTC, dfuch commented
/csr

2020-12-14 19:36 UTC, RogerRiggs requested changes
The `version` method is described in the javadoc as only being applicable to variant = 2 UUIDs.
Changing the behavior to throw a `UnsupportedOperationException` is not a compatible change.
There is very little value in adding the exception doing so might prevent existing applications from continuing to function. 

Repeating the limitation to version 2 to the javadoc of the version method as far as this request can go.

Otherwise, please close the PR without integrating.

2020-12-17 17:18 UTC, LanceAndersen commented
> > There is very little value in adding the exception doing so might prevent existing applications from continuing to function.
> 
> I disagree on the value and am with the author of the original issue. All these existing applications are functioning but factually invalid, adding the exception like we have it in all other methods of the class would surface the issue in exactly those applications.

While I can appreciate that the current behavior might be less than ideal, changing it to throw an UnsupportedOperationException could break existing applications.    Have you had a chance to research the number of uses of version() in the java eco-system to determine that  the risk to existing applications will minimal?

If you feel that the change in functionality  is important for users of UUID,  then please propose a replacement method for version and propose to deprecate the existing method ?  

If you decide to move forward with proposing a replacement method for version, then please socialize the proposal on corelibs-dev prior to creating a new PR.   

 Please note that a CSR will also be required to move forward.

2020-12-17 22:07 UTC, Fleshgrinder commented
I cannot create CRSs, only members can. Deprecating and switching to another function results in much more work for users overall because it affects all those who use it correctly as well. In other words: 100%

I'm in favor of rejection if that's the way forward.

What's wrong with creating PRs for existing issues?

2020-12-17 22:16 UTC, RogerRiggs commented
Often an enhancement is created when there's an idea of an improvement but no resources to do the research and develop a justification. That work has to be done when someone has time.  Usually ideas are discussed on one of the many OpenJDK email aliases to validate the idea and the approach before developing the code. See the list of OpenJDK Mail lists for details.
https://mail.openjdk.java.net/mailman/listinfo
As for moving to GitHub,  it was in part to make it easier to collaborate on the development but also to move from Mercurial to Git.
But GitHub does not replace the need for discussion on the Email Lists.

2021-01-15 07:14 UTC, Fleshgrinder commented
Active

2021-02-12 19:13 UTC, Fleshgrinder commented
Active

2021-04-21 14:52 UTC, Fleshgrinder commented
Active

2021-05-19 18:24 UTC, Fleshgrinder commented
@bridgekeeper I guess it will stay open for a little longer. 😜

2021-06-17 06:13 UTC, closed without merging