8311030: ResourceBundle.handleKeySet() is racy
openjdk/jdk pull request #14692
Opened 2023-06-28 11:05 UTC by stsypanov

Double-checked locking should rely on local variable to avoid racy reads from volatile field.

2023-06-28 14:13 UTC, pavelrappo commented
It seems like a benign race, so that the whole PR qualifies as performance improvement, not a bug fix. Do I understand it correctly?

2023-06-28 14:20 UTC, pavelrappo commented
To put this into perspective, the race you are trying to fix seems benign, so the PR qualifies as a performance improvement, not a bug fix. Is my understanding correct?

2023-06-28 18:50 UTC, stsypanov commented
It'd be a benign race in case all members of `HashSet` are `final`, but they aren't, so there are no safe publication guarantees.

2023-06-28 20:02 UTC, RogerRiggs approved these changes
Looks ok; was this a tool detected race?

2023-06-28 20:21 UTC, naotoj approved these changes
+1

2023-06-29 10:08 UTC, stsypanov commented
@RogerRiggs no tool, just fell into the sources while debugging my application

2023-06-29 10:08 UTC, stsypanov commented
/integrate

2023-06-29 12:18 UTC, dholmes-ora commented
I don't see any race here. The addition of the local serves no purpose AFAICS - we don't even save any volatile reads.

2023-06-29 12:23 UTC, rgiulietti commented
The role of the local `keySet` seems pretty useless. It doesn't save neither volatile reads nor writes.

2023-06-29 12:24 UTC, viktorklang-ora commented
@stsypanov I don't see that there's any issue with the existing code as the volatile field is only written at most once as guarded by the synchronized-block. Best case this patch avoids an extra volatile read (presuming it isn't optimized away).

2023-06-29 13:15 UTC, dfuch commented
The new code makes it more visible that 1. keySet is expected to be volatile and 2. that there is no path were code could be ordered leading to the 'wrong' value of keySet being returned. So maybe there's no race, but the new code make it more obvious.

2023-06-29 13:55 UTC, RogerRiggs requested changes
Given all the comments, I don't think this is ready to integrate.

2023-06-29 14:40 UTC, shipilev commented
Yeah, current code looks like a correct volatile-bearing-DCL. `keySet` is safely published already. Introducing local variable gains us nothing here performance-wise. Arguably, readability is worse. So I would avoid doing this change.

We could have explored if we could drop `volatile` from `keySet`, but it does not look safe, given `HashMap` is not safely constructed.

2023-06-29 16:09 UTC, naotoj requested changes
Retrieving the approval, per the discussion.

2023-06-29 20:59 UTC, stsypanov commented
@rgiulietti `keySet` is volatile, so providing it has already been initialized, in original code we read from it twice when doing null-check and returning the value. With local variable we read from the field only once, don't we?

2023-06-30 08:30 UTC, rgiulietti commented
True. I was mislead because the return statement does not appear in the changeset (the line is textually the same, although it has a different semantics: `keySet` now refers to a local), so I didn't count for it.

In the end, this PR is not about fixing a race, as the title seems to suggest (the original code is correct), but to avoid a volatile read, right?

2023-06-30 10:25 UTC, stsypanov commented
> In the end, this PR is not about fixing a race, as the title seems to suggest (the original code is correct), but to avoid a volatile read, right?

Yeah, probably I was wrong in my conclusion. Should I rename the ticket?

2023-07-03 00:34 UTC, dholmes-ora commented
I don't think saving one volatile read is a reasonable trade-off for the loss of readability of this code change.

2023-07-03 08:32 UTC, closed without merging