8257146: C2: extend the scope of StressGCM
openjdk/jdk pull request #1469
Opened 2020-11-26 20:36 UTC by robcasloz

Extend the scope of StressGCM by allowing it to move instructions into basic blocks with worse frequency. This should improve StressGCM's ability to expose bugs where C2 relies on GCM heuristics for correctness.

Tested with StressGCM enabled on `hs-tier1-3` and a single repetition, the following test cases fail on `linux-aarch64-debug` and require further investigation:
- `serviceability/sa/ClhsdbJstackXcompStress.java`
- `compiler/c2/cr6663848/Tester.java`

Also tested with StressGCM disabled (default)  on `hs-tier1-3`, all tests pass.

2020-11-26 20:37 UTC, robcasloz commented
/summary
Extend the scope of StressGCM by allowing it to move instructions into basic
blocks with worse frequency.

2020-11-27 13:18 UTC, shipilev commented
From the archives, the original discussion about StressGCM:
 https://mail.openjdk.java.net/pipermail/hotspot-compiler-dev/2013-February/009777.html 

It was explicitly putting the loads in lower frequency block only, because as Vladimir says:
 > There is an other old bug which you may hit if you randomize placement
 > in gcm: 6831314. I still did not find a solution which does not
 > introduce performance regression. What saves us is placing loads into
 > "cheaper" low frequency block (which is most nested block where load's
 > result is used).

Is that not a problem anymore?

2020-11-30 08:57 UTC, robcasloz commented
> From the archives, the original discussion about StressGCM:
> https://mail.openjdk.java.net/pipermail/hotspot-compiler-dev/2013-February/009777.html
> 
> It was explicitly putting the loads in lower frequency block only, because as Vladimir says:
> 
> > There is an other old bug which you may hit if you randomize placement
> > in gcm: 6831314. I still did not find a solution which does not
> > introduce performance regression. What saves us is placing loads into
> > "cheaper" low frequency block (which is most nested block where load's
> > result is used).
> 
> Is that not a problem anymore?

Thanks for the pointer, Aleksey!

The [JIRA bug report for 6831314](https://bugs.openjdk.java.net/browse/JDK-6831314?focusedCommentId=14128897) was closed in 2017 with Vladimir's comment _"Will not fix. As evaluation said it is only observed with modified C2 code"_, so this particular case does not seem to be a problem anymore. In any case, my reasoning is that it is good to know if there are other cases where C2 relies on GCM heuristics for correctness, regardless of what we do about it.

@vnkozlov, what do you think?

2020-11-30 18:02 UTC, vnkozlov commented
First, StressGCM is not used in production only for testing - it should not affect released JDK.
Second,  I think  it would be nice to try reproduce 6831314 issue again with latest JDK. We did several changes with nodes types casting which may fixed it. And it should not prevent us from widening the scope of testing with StressGCM to find other issues now.
When @shipilev implemented this flag first, my concern was that we would have to spend a lot of resources to clean up found issues. Now we have more engineers and we should do the clean up.

@robcasloz  I suggest additionally to run hs-precheckin-comp with StressGCM ON.

2020-12-01 07:47 UTC, TobiHartmann requested changes
Looks good to me but the test failures that you've found when running lower tiers should be investigated and fixed before integrating this to avoid frequent failures in the CI runs. I would suggest to defer this to JDK 17.

Also, as Vladimir already said, more testing should be executed. Please run the higher tiers as well.

2020-12-01 11:35 UTC, robcasloz commented
> First, StressGCM is not used in production only for testing - it should not affect released JDK.
> Second, I think it would be nice to try reproduce 6831314 issue again with latest JDK. We did several changes with nodes types casting which may fixed it. And it should not prevent us from widening the scope of testing with StressGCM to find other issues now.
> When @shipilev implemented this flag first, my concern was that we would have to spend a lot of resources to clean up found issues. Now we have more engineers and we should do the clean up.
> 
> @robcasloz I suggest additionally to run hs-precheckin-comp with StressGCM ON.

Thanks for the clarification, Vladimir. I did a single run of hs-precheckin-comp with StressGCM enabled, the following test cases fail on macosx-x64-debug:
- `runtime/handshake/HandshakeWalkStackTest.java`
- `compiler/c2/cr6663848/Tester.java` (same as before)

2020-12-01 11:57 UTC, robcasloz commented
> Looks good to me but the test failures that you've found when running lower tiers should be investigated and fixed before integrating this to avoid frequent failures in the CI runs. I would suggest to defer this to JDK 17.

Fair point. My only concern with postponing the integration is that it could reduce the incentive to investigate the failures, as these will not be as visible.

> Also, as Vladimir already said, more testing should be executed. Please run the higher tiers as well.

Will do!

2020-12-01 21:52 UTC, vnkozlov commented
I agree with deferring it to JDK 17.  Meanwhile I suggest to investigate failing cases and file separate bug for them (which can be fixed in JDK 16).

2020-12-02 08:14 UTC, robcasloz commented
> I agree with deferring it to JDK 17. Meanwhile I suggest to investigate failing cases and file separate bug for them (which can be fixed in JDK 16).

OK, thanks for the feedback Aleksey, Vladimir, and Tobias! I will put this PR on hold.

2021-01-07 08:32 UTC, robcasloz commented
This is a comment just to prevent the bot from closing the PR.

2021-03-04 11:20 UTC, closed without merging