8311645: Memory leak in jspawnhelper spawnChild after JDK-8307990
openjdk/jdk pull request #14809
Opened 2023-07-08 02:05 UTC by kspeeyu

Free-ing 'buf' before two conditional return statements introduced by JDK-8307990

2023-07-10 11:14 UTC, shipilev requested changes
Looks okay, but need to fix two whitespace errors for jcheck to be happy.
Also, attention @simonis, whose patch introduced this little problem, I think.

2023-07-10 11:14 UTC, shipilev commented on src/java.base/unix/native/libjava/ProcessImpl_md.c
> +	return -1;
See jcheck warnings: there is `TAB` on this line, which should be replaced by 4-space indents.

2023-07-10 11:14 UTC, shipilev commented on src/java.base/unix/native/libjava/ProcessImpl_md.c
> +	return -1;
Same here.

2023-07-10 16:13 UTC, kspeeyu commented on src/java.base/unix/native/libjava/ProcessImpl_md.c
> +	return -1;
Thanks for that. Will do

2023-07-10 16:38 UTC, simonis commented
Hi @kspeeyu ,

Thanks for fixing this issue. The fix looks good except the whitespace issue already mentioned before.

Notice that we don't use TABs for code indentation in OpenJDK. For the native Hotspot sources (i.e. the ones under `src/hotspot/`) we use an indentation of two spaces whereas for Java code and the native part of the class library (i.e. the native code outside `src/hotspot`) we use four spaces. We don't change the indentation of imported libraries like HarfBuzz or zlib at all.

You can find more details on the coding style under https://github.com/openjdk/jdk/tree/master/doc. Just in case you haven't seen it yet, the [OpenJDK Developers’ Guide](https://openjdk.org/guide/) also contains a lot of useful information.

2023-07-10 18:27 UTC, shipilev approved these changes
Looks good!

2023-07-10 18:28 UTC, kspeeyu commented
@simonis, thanks for your response. Fixed the whitespace, will follow the coding style guidelines.

2023-07-10 18:33 UTC, simonis approved these changes
Thanks, looks good now.

I can sponsor your change once you `/integrate`.

2023-07-10 18:52 UTC, simonis commented
> Hold on a sec, let's make sure the GitHub Actions complete with all green. We can techinically wait after `/integrate` is said for sponsored changeset, but it is cleaner process-wise to wait for GHA all-clear/all-green.

Sure thing :)

2023-07-11 05:40 UTC, AlanBateman approved these changes

2023-07-11 07:38 UTC, shipilev commented
GHA reports one test failure, but it looks infrastructural. Feel free to say `/integrate`, @kspeeyu.

2023-07-11 14:03 UTC, RogerRiggs approved these changes

2023-07-11 16:52 UTC, kspeeyu commented
/integrate

2023-07-11 16:54 UTC, shipilev commented
/sponsor

2023-07-11 16:55 UTC, closed without merging