8309603: Deallocate hashtables in ClassLoaderData::unload
openjdk/jdk pull request #14820
Opened 2023-07-11 00:01 UTC by chadrako

[JDK-8309603](https://bugs.openjdk.org/browse/JDK-8309603)

Memory is released in `ClassLoaderdata::~ClassLoaderData` for the dictionary and module hashtables but they could be deleted earlier in `ClassLoaderdata::unload`. Since we're unloading the class loader is no longer being used for lookup.

Additional testing:
- [ ] Linux x86_64 fastdebug `tier2`
- [ ] Linux x86_64 release `tier2`
- [ ] Linux x86_64 fastdebug `gtest:all`
- [ ] Linux x86_64 release `gtest:all`

2023-07-11 21:15 UTC, coleenp requested changes

2023-07-11 21:15 UTC, coleenp commented on src/hotspot/share/classfile/classLoaderData.cpp
>    }
Can you do packages too?

2023-07-11 21:15 UTC, coleenp commented on src/hotspot/share/classfile/classLoaderData.cpp
>    if (_unnamed_module != nullptr) {
And maybe unnamed module?

2023-07-14 01:26 UTC, dholmes-ora commented
When do we delete the ClassLoaderData? Does moving this to unload time help with a specific problem? It seems odd to split the deallocation operations between unload and the destructor - why does unload not just call the destructor?

2023-07-14 19:31 UTC, coleenp commented
Unload cannot just call the destructor because it's not safe to release the metaspace chunk yet, until the next handshake operation.  Since ZGenerational may take a while to request a handshake, this might be able to release some memory beforehand.  @fisk asked for this.
Did releasing the package table not work?

2023-07-14 23:09 UTC, chadrako commented
Started failing a handful of tier1/tier2 tests after moving packages and unnamed module to unload. Running a couple more tests to see what the issue is

2023-07-25 00:43 UTC, chadrako commented
> Started failing a handful of tier1/tier2 tests after moving packages and unnamed module to unload. Running a couple more tests to see what the issue is

Failed tests passed when ran again. They do not appear to be related

2023-07-27 19:25 UTC, coleenp approved these changes
This looks good.  While it's nicer to remove these in the destructor, this releases memory more eagerly for class unloading without waiting for a safepoint.

2023-07-28 12:56 UTC, fisk commented
The design for concurrent class unloading was to essentially do this:
1. Unlink unloading data
2. Handshake all threads potentially accessing unloading data
3. Delete unloading data
The reason for this order, is that it provides safe memory reclamation. We want to do this consistently, so we don't get races where the code works 99.999999% of the time, except when you get a nasty race that crashes the JVM.
So unfortunately, this patch goes in the wrong direction, I think. I don't think we should do this.

2023-07-28 16:04 UTC, closed without merging