8308903: Print detailed info for Java objects in -Xlog:cds+map
openjdk/jdk pull request #14841
Opened 2023-07-12 00:39 UTC by iklam

This PR adds detailed printing of oop information with `-Xlog:cds+map+oop=trace`, or simply `-Xlog:cds+map*=trace`. The information is useful for debugging contents of the CDS archived heap objects.

The output looks like `oopDesc::print_on(tty)`, but we need to print the pointers using the locations of the objects at runtime. The examples below show how a `String` references its `value` array.

Example with `-XX:-UseCompressedOops`:

```
0x00000000100001f0: @@ Object java.lang.String
0x00000000100001f0: 0000006ff6ab8d01 88d47c5b00010290 0000000000010000 0000000010000210
 - klass: 'java/lang/String' 0x0000000800010290
 - ---- fields (total size 4 words):
 - private 'hash' 'I' @12 -1999340453 (0x88d47c5b)
 - private final 'coder' 'B' @16 0 (0x00)
 - private 'hashIsZero' 'Z' @17 false (0x00)
 - injected 'flags' 'B' @18 1 (0x01)
 - private final 'value' '[B' @24 0x0000000010000210 [B length: 6
0x0000000010000210: @@ Object [B length: 6
0x0000000010000210: 000000693b708001 00000006000024c8 0000574f5252414e
 - klass: {type array byte} 0x00000008000024c8
 - 0: 4e N
 - 1: 41 A
 - 2: 52 R
 - 3: 52 R
 - 4: 4f O
 - 5: 57 W
```

Example with `-XX:+UseCompressedOops`. Note that the narrorOop is also printed:

```
0x00000007ffc001b8: @@ Object (0xfff80037) java.lang.String
0x00000007ffc001b8: f6ab8d01 0000006f 00010290 88d47c5b 00010000 fff8003a
 - klass: 'java/lang/String' 0x0000000800010290
 - ---- fields (total size 3 words):
 - private 'hash' 'I' @12 -1999340453 (0x88d47c5b)
 - private final 'coder' 'B' @16 0 (0x00)
 - private 'hashIsZero' 'Z' @17 false (0x00)
 - injected 'flags' 'B' @18 1 (0x01)
 - private final 'value' '[B' @20 0x00000007ffc001d0 (0xfff8003a) [B length: 6
0x00000007ffc001d0: @@ Object (0xfff8003a) [B length: 6
0x00000007ffc001d0: 3b708001 00000069 000024c8 00000006 5252414e 0000574f
 - klass: {type array byte} 0x00000008000024c8
 - 0: 4e N
 - 1: 41 A
 - 2: 52 R
 - 3: 52 R
 - 4: 4f O
 - 5: 57 W
```

2023-07-12 05:51 UTC, tstuefe commented
> The output looks like oopDesc::print_on(tty), but we need to print the pointers using the locations of the objects at runtime. 

I don't understand. Are you not experimenting with a new allocation mode that would basically make the runtime address unpredictable? Or is this still for the old way of things where the heap archive is mapped as-is ?

Other than that, this looks very useful.

2023-07-12 16:39 UTC, iklam commented
> > The output looks like oopDesc::print_on(tty), but we need to print the pointers using the locations of the objects at runtime. 
> 
> 
> 
> I don't understand. Are you not experimenting with a new allocation mode that would basically make the runtime address unpredictable? Or is this still for the old way of things where the heap archive is mapped as-is ?
> 
> 
> 
> Other than that, this looks very useful.

This map file is useful for both the existing and experimental loading code.

My experimental loading code uses the same format for input. I partially wrote this PR to test the new loading code, which assumes contiguous objects in the input stream. So at runtime, I just need to look at the lower 3 digits, which would be the same as in the map file.

The map file also shows how the objects are grouped. For example, I am reordering the objects so that the first 50% of them don't need relocation. That can be verified with the map file.

Also, even with the new loading approach, we could have a future optimization where the GC knows that we are still in the archive loading stage, and can return contiguous objects that start with the requested address. This way, we can avoid relocation.

2023-07-14 21:12 UTC, matias9927 requested changes
I have two style suggestions but otherwise this looks good!

2023-07-14 21:12 UTC, matias9927 commented on src/hotspot/share/cds/archiveBuilder.cpp
> +      default:
The if block inside the default case leads to a lot of indentation. Maybe this could be it's own method?

2023-07-14 21:12 UTC, matias9927 commented on src/hotspot/share/cds/archiveHeapWriter.cpp
> +  return idx < heap_info->ptrmap()->size() && heap_info->ptrmap()->at(idx);
I believe this should be something like
`return (idx < heap_info->ptrmap()->size()) && (heap_info->ptrmap()->at(idx) != nullptr);`

2023-07-15 06:36 UTC, tstuefe reviewed
Looks useful. Found nothing to note but a small style nit. But a more extensive test would be nice, e.g. matching the output of this log against a known object layout.

2023-07-15 06:36 UTC, tstuefe commented on src/hotspot/share/cds/archiveBuilder.cpp
> +        st.print_cr(" - ---- fields (total size " SIZE_FORMAT " words):", source_oop->size());
Nit, proposal: "fields (xx words):" (no leading dashes, no "total size") for more density

2023-07-22 06:59 UTC, tstuefe approved these changes
This looks good to me. Nice addition!

2023-07-24 16:03 UTC, calvinccheung approved these changes
Just couple of nits. Looks good.

2023-07-24 16:17 UTC, iklam commented on src/hotspot/share/cds/archiveBuilder.cpp
> +
I added this blank line to separate the following lines from the previous loop, to make the code easier to read.

2023-07-24 16:19 UTC, calvinccheung commented on src/hotspot/share/cds/archiveBuilder.cpp
> +
Ok

2023-07-24 16:19 UTC, calvinccheung commented on src/hotspot/share/cds/archiveHeapWriter.cpp
> +  return (idx < heap_info->ptrmap()->size()) && (heap_info->ptrmap()->at(idx) == true);
I see.

2023-07-24 17:56 UTC, closed without merging