8311986: runtime/os/TestTracePageSizes.java fails for ShenandoahGC
openjdk/jdk pull request #14858
Opened 2023-07-13 02:16 UTC by xiangzhai

Hi,

runtime/os/TestTracePageSizes.java fails for ShenandoahGC on linux-x86_64:

```
ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.AssertionError: Page sizes mismatch: 4 != 2048
REASON: User specified action: run main/othervm -XX:+AlwaysPreTouch -Xmx128m -Xlog:pagesize:ps-%p.log -XX:-SegmentedCodeCache -XX:+UseTransparentHugePages TestTracePageSizes 
TIME:   0.353 seconds
messages:
command: main -XX:+AlwaysPreTouch -Xmx128m -Xlog:pagesize:ps-%p.log -XX:-SegmentedCodeCache -XX:+UseTransparentHugePages TestTracePageSizes
reason: User specified action: run main/othervm -XX:+AlwaysPreTouch -Xmx128m -Xlog:pagesize:ps-%p.log -XX:-SegmentedCodeCache -XX:+UseTransparentHugePages TestTracePageSizes 
started: Thu Jul 13 09:57:18 CST 2023
Mode: othervm [/othervm specified]
finished: Thu Jul 13 09:57:19 CST 2023
elapsed time (seconds): 0.353
configuration:
STDOUT:
STDERR:
java.lang.AssertionError: Page sizes mismatch: 4 != 2048
	at TestTracePageSizes.main(TestTracePageSizes.java:294)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
	at java.base/java.lang.Thread.run(Thread.java:1570)

JavaTest Message: Test threw exception: java.lang.AssertionError: Page sizes mismatch: 4 != 2048
JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: java.lang.AssertionError: Page sizes mismatch: 4 != 2048
rerun:
cd /mnt/repo/openjdk/jdk/build/linux-x86_64-server-fastdebug/test-support/jtreg_test_hotspot_jtreg_runtime_os_TestTracePageSizes_java/scratch/0 && \
HOME=/home/loongson \
LANG=zh_CN.UTF-8 \
LC_ALL=C \
PATH=/bin:/usr/bin:/usr/sbin \
TEST_IMAGE_DIR=/mnt/repo/openjdk/jdk/build/linux-x86_64-server-fastdebug/images/test \
_JVM_DWARF_PATH=/mnt/repo/openjdk/jdk/build/linux-x86_64-server-fastdebug/images/symbols \
CLASSPATH=/mnt/repo/openjdk/jdk/build/linux-x86_64-server-fastdebug/test-support/jtreg_test_hotspot_jtreg_runtime_os_TestTracePageSizes_java/classes/0/runtime/os/TestTracePageSizes_compiler-options.d:/mnt/repo/openjdk/jdk/test/hotspot/jtreg/runtime/os:/mnt/repo/openjdk/jdk/build/linux-x86_64-server-fastdebug/test-support/jtreg_test_hotspot_jtreg_runtime_os_TestTracePageSizes_java/classes/0/test/lib:/mnt/repo/openjdk/jdk/test/lib:/mnt/download/jtreg/lib/javatest.jar:/mnt/download/jtreg/lib/jtreg.jar \
    /mnt/repo/openjdk/jdk/build/linux-x86_64-server-fastdebug/images/jdk/bin/java \
        -Dtest.vm.opts='-XX:MaxRAMPercentage=4.16667 -Dtest.boot.jdk=/mnt/download/jdk-20.0.1 -Djava.io.tmpdir=/mnt/repo/openjdk/jdk/build/linux-x86_64-server-fastdebug/test-support/jtreg_test_hotspot_jtreg_runtime_os_TestTracePageSizes_java/tmp -XX:+UseShenandoahGC' \
        -Dtest.tool.vm.opts='-J-XX:MaxRAMPercentage=4.16667 -J-Dtest.boot.jdk=/mnt/download/jdk-20.0.1 -J-Djava.io.tmpdir=/mnt/repo/openjdk/jdk/build/linux-x86_64-server-fastdebug/test-support/jtreg_test_hotspot_jtreg_runtime_os_TestTracePageSizes_java/tmp -J-XX:+UseShenandoahGC' \
        -Dtest.compiler.opts= \
        -Dtest.java.opts= \
        -Dtest.jdk=/mnt/repo/openjdk/jdk/build/linux-x86_64-server-fastdebug/images/jdk \
        -Dcompile.jdk=/mnt/repo/openjdk/jdk/build/linux-x86_64-server-fastdebug/images/jdk \
        -Dtest.timeout.factor=4.0 \
        -Dtest.nativepath=/mnt/repo/openjdk/jdk/build/linux-x86_64-server-fastdebug/images/test/hotspot/jtreg/native \
        -Dtest.root=/mnt/repo/openjdk/jdk/test/hotspot/jtreg \
        -Dtest.name=runtime/os/TestTracePageSizes.java#compiler-options \
        -Dtest.file=/mnt/repo/openjdk/jdk/test/hotspot/jtreg/runtime/os/TestTracePageSizes.java \
        -Dtest.src=/mnt/repo/openjdk/jdk/test/hotspot/jtreg/runtime/os \
        -Dtest.src.path=/mnt/repo/openjdk/jdk/test/hotspot/jtreg/runtime/os:/mnt/repo/openjdk/jdk/test/lib \
        -Dtest.classes=/mnt/repo/openjdk/jdk/build/linux-x86_64-server-fastdebug/test-support/jtreg_test_hotspot_jtreg_runtime_os_TestTracePageSizes_java/classes/0/runtime/os/TestTracePageSizes_compiler-options.d \
        -Dtest.class.path=/mnt/repo/openjdk/jdk/build/linux-x86_64-server-fastdebug/test-support/jtreg_test_hotspot_jtreg_runtime_os_TestTracePageSizes_java/classes/0/runtime/os/TestTracePageSizes_compiler-options.d:/mnt/repo/openjdk/jdk/build/linux-x86_64-server-fastdebug/test-support/jtreg_test_hotspot_jtreg_runtime_os_TestTracePageSizes_java/classes/0/test/lib \
        -Dtest.class.path.prefix=/mnt/repo/openjdk/jdk/build/linux-x86_64-server-fastdebug/test-support/jtreg_test_hotspot_jtreg_runtime_os_TestTracePageSizes_java/classes/0/runtime/os/TestTracePageSizes_compiler-options.d:/mnt/repo/openjdk/jdk/test/hotspot/jtreg/runtime/os:/mnt/repo/openjdk/jdk/build/linux-x86_64-server-fastdebug/test-support/jtreg_test_hotspot_jtreg_runtime_os_TestTracePageSizes_java/classes/0/test/lib \
        -XX:MaxRAMPercentage=4.16667 \
        -Dtest.boot.jdk=/mnt/download/jdk-20.0.1 \
        -Djava.io.tmpdir=/mnt/repo/openjdk/jdk/build/linux-x86_64-server-fastdebug/test-support/jtreg_test_hotspot_jtreg_runtime_os_TestTracePageSizes_java/tmp \
        -XX:+UseShenandoahGC \
        -Djava.library.path=/mnt/repo/openjdk/jdk/build/linux-x86_64-server-fastdebug/images/test/hotspot/jtreg/native \
        -XX:+AlwaysPreTouch \
        -Xmx128m \
        -Xlog:pagesize:ps-%p.log \
        -XX:-SegmentedCodeCache \
        -XX:+UseTransparentHugePages \
        com.sun.javatest.regtest.agent.MainWrapper /mnt/repo/openjdk/jdk/build/linux-x86_64-server-fastdebug/test-support/jtreg_test_hotspot_jtreg_runtime_os_TestTracePageSizes_java/runtime/os/TestTracePageSizes_compiler-options.d/main.2.jta

TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.AssertionError: Page sizes mismatch: 4 != 2048
```

Also fails on linux-loongarch64:

```
ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.AssertionError: Page sizes mismatch: 16 != 32768
REASON: User specified action: run main/othervm -XX:+AlwaysPreTouch -Xmx128m -Xlog:pagesize:ps-%p.log -XX:-SegmentedCodeCache -XX:+UseTransparentHugePages TestTracePageSizes 
TIME:   1.162 seconds
messages:
command: main -XX:+AlwaysPreTouch -Xmx128m -Xlog:pagesize:ps-%p.log -XX:-SegmentedCodeCache -XX:+UseTransparentHugePages TestTracePageSizes
reason: User specified action: run main/othervm -XX:+AlwaysPreTouch -Xmx128m -Xlog:pagesize:ps-%p.log -XX:-SegmentedCodeCache -XX:+UseTransparentHugePages TestTracePageSizes 
started: Thu Jul 13 09:15:46 CST 2023
Mode: othervm [/othervm specified]
finished: Thu Jul 13 09:15:47 CST 2023
elapsed time (seconds): 1.162
configuration:
STDOUT:
STDERR:
OpenJDK 64-Bit Server VM warning: Large pages size (32768K) is too large to afford page-sized regions, disabling uncommit
java.lang.AssertionError: Page sizes mismatch: 16 != 32768
	at TestTracePageSizes.main(TestTracePageSizes.java:300)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
	at java.base/java.lang.Thread.run(Thread.java:1570)

JavaTest Message: Test threw exception: java.lang.AssertionError: Page sizes mismatch: 16 != 32768
JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: java.lang.AssertionError: Page sizes mismatch: 16 != 32768
rerun:
cd /mnt/repo/private/jdk-ls/build/linux-loongarch64-server-fastdebug/test-support/jtreg_test_hotspot_jtreg_runtime_os_TestTracePageSizes_java/scratch/1 && \
HOME=/home/zhaixiang \
LANG=zh_CN.UTF-8 \
LC_ALL=C \
PATH=/bin:/usr/bin:/usr/sbin \
TEST_IMAGE_DIR=/mnt/repo/private/jdk-ls/build/linux-loongarch64-server-fastdebug/images/test \
_JVM_DWARF_PATH=/mnt/repo/private/jdk-ls/build/linux-loongarch64-server-fastdebug/images/symbols \
CLASSPATH=/mnt/repo/private/jdk-ls/build/linux-loongarch6 [...]

2023-07-13 02:42 UTC, DamonFool approved these changes
LGTM

2023-07-14 00:59 UTC, xiangzhai commented
/integrate

2023-07-14 03:13 UTC, dholmes-ora commented
It would be nice to understand why the test fails with ShenandoahGC (and ZGC for that matter).

2023-07-14 03:52 UTC, xiangzhai commented
Hi @dholmes-ora 

(single generation) ZGC and Generational ZGC are not able to reproduce the issue now:

```
-XX:+UseZGC
```

or

```
-XX:+UseZGC -XX:+ZGenerational
```

I am investigating why only (single generation) ShenandoahGC is able to reproduce the issue.

@shipilev @rkennke Could you give some hint?

Thanks,
Leslie Zhai

2023-07-14 08:22 UTC, xiangzhai commented
Hi @dholmes-ora 

It might be `VmFlags` issue.

> "VmFlags" field deserves a separate description. This member represents the kernel flags associated with the particular virtual memory area in two letter encoded manner https://github.com/torvalds/linux/blob/master/Documentation/filesystems/proc.rst

[DEBUG](https://github.com/xiangzhai/jdk/commits/DEBUG-8311986) on purpose to add two bitmaps: `lzhai_bitmap` and `rzhai_bitmap` and `UseShenandoahGC` to rerun the testcase:

```
DEBUG: size: 4194304 preferred_page_size: 2097152
DEBUG: size: 4194304 preferred_page_size: 4096
DEBUG: size: 4194304 preferred_page_size: 2097152
DEBUG: size: 4194304 preferred_page_size: 2097152
DEBUG: size: 2097152 preferred_page_size: 2097152
DEBUG: smapsFileToParse: null
DEBUG: smapsCopy: smaps-copy-38346-0.txt
DEBUG: line: [0.001s][info][pagesize] Using the default large page size: 2M
DEBUG: line: [0.001s][info][pagesize] Usable page sizes: 4k, 2M
DEBUG: line: [0.002s][info][pagesize] CodeCache:  min=4M max=240M base=0x00007f1584800000 size=240M page_size=2M
DEBUG: pageSize: 2M
DEBUG: pageSizeFromSmaps: 4
DEBUG: pageSizeFromTrace: 2048
DEBUG: VmFlags: rd wr ex mr mw me ac sd hg 
DEBUG: line: [0.003s][info][pagesize] Heap: req_size=128M req_page_size=2M base=0x00000000f8000000 size=128M page_size=2M
DEBUG: pageSize: 2M
DEBUG: pageSizeFromSmaps: 4
DEBUG: pageSizeFromTrace: 2048
DEBUG: VmFlags: rd wr mr mw me ac sd hg 
DEBUG: line: [0.003s][info][pagesize] Mark Bitmap: req_size=4M req_page_size=2M base=0x00007f15a2a00000 size=4M page_size=2M
DEBUG: pageSize: 2M
DEBUG: pageSizeFromSmaps: 4
DEBUG: pageSizeFromTrace: 2048
DEBUG: VmFlags: rd wr mr mw me ac sd hg 
DEBUG: line: [0.004s][info][pagesize] DEBUG: Leslie Zhai Bitmap: req_size=4M req_page_size=4K base=0x00007f15a1ffa000 size=4M page_size=4K
DEBUG: pageSize: 4K
DEBUG: pageSizeFromSmaps: 4
DEBUG: pageSizeFromTrace: 4
=> DEBUG: line: [0.004s][info][pagesize] DEBUG: Ray Zhai Bitmap: req_size=4M req_page_size=2M base=0x00007f15a1a00000 size=4M page_size=2M
DEBUG: pageSize: 2M
DEBUG: pageSizeFromSmaps: 4
DEBUG: pageSizeFromTrace: 2048
=> DEBUG: VmFlags: mr mw me nr sd 
java.lang.AssertionError: Page sizes mismatch: 4 != 2048
	at TestTracePageSizes.main(TestTracePageSizes.java:301)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
	at java.base/java.lang.Thread.run(Thread.java:1570)

JavaTest Message: Test threw exception: java.lang.AssertionError: Page sizes mismatch: 4 != 2048
JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: java.lang.AssertionError: Page sizes mismatch: 4 != 2048
```

[smaps-copy-38346-0.txt](https://github.com/openjdk/jdk/files/12047810/smaps-copy-38346-0.txt)


The `VmFlags` of virtual memory area `Ray Zhai Bitmap` is lack of `hg`. So *not* hit the condition `range.isTransparentHuge()`.

Compared with Generational ZGC `UseZGC` and `ZGenerational` to rerun the testcase:

```
DEBUG: smapsFileToParse: null
DEBUG: smapsCopy: smaps-copy-38376-0.txt
DEBUG: line: [0.001s][info][pagesize] Using the default large page size: 2M
DEBUG: line: [0.001s][info][pagesize] Usable page sizes: 4k, 2M
=> DEBUG: line: [0.002s][info][pagesize] CodeCache:  min=4M max=240M base=0x00007f024c800000 size=240M page_size=2M
DEBUG: pageSize: 2M
DEBUG: pageSizeFromSmaps: 4
DEBUG: pageSizeFromTrace: 2048
=> DEBUG: VmFlags: rd wr ex mr mw me ac sd hg 
STATUS:Passed.
```

There is `hg` in the `VmFlags` of vma `CodeCache` even if the `os::vm_page_size` (4KB for linux-x86_64) is not equals to `bitmap_page_size` when `UseLargePages`.

linux-x86_64 and linux-loongarch64 confirmed enabled THP:

```
$ cat /sys/kernel/mm/transparent_hugepage/enabled
[always] madvise never
```

Thanks,
Leslie Zhai

2023-07-14 09:02 UTC, rkennke commented
I believe @tstuefe might know more about this.

2023-07-14 09:05 UTC, tstuefe commented
> I believe @tstuefe might know more about this.

Possibly caused by defect THP detection. Possibly fixed by upcoming https://github.com/openjdk/jdk/pull/14739.

I remember knowing more, e.g. why this affects Shenandoah only, but the details slipped my mind for a moment. But I know that is why we explicitly don't test for Shenandoah. Therefore this patch is fine.

2023-07-14 09:06 UTC, tstuefe approved these changes
Can you please change issue subject and PR subject to something like "Disable xxx for Shenandoah", since this does not fix the issue, it just disables the test.

Otherwise okay.

2023-07-14 09:07 UTC, shipilev commented
I think it has to do with https://bugs.openjdk.org/browse/JDK-8310110 -- the test passes before that commit, and fails after it.

2023-07-14 09:32 UTC, tstuefe commented
> I think it has to do with https://bugs.openjdk.org/browse/JDK-8310110 -- the test passes before that commit, and fails after it.

Yes, before https://bugs.openjdk.org/browse/JDK-8310110 we did not output anything for Shenandoah, so this test just is a noop since the Matcher does not match anything to check.

I now remember again. Underlying cause is that AUX bitmap is madviced incorrectly for Shenandoah. 

See https://github.com/openjdk/jdk/pull/14486#issuecomment-1598871634 . 

I have a line of patches upcoming, starting with https://github.com/openjdk/jdk/pull/14739, then https://github.com/openjdk/jdk/pull/14559, and the AUX bitmap issue will probably be fixed as a side effect of the latter. Then, finally, this test can be enabled properly for Shenandoah.

Its all sideline stuff though, since my main focus is Lilliput and native heap trimming. Its also Reviewer-bound - the THP detection fix alone is already open since > 2 weeks.

2023-07-14 09:38 UTC, shipilev approved these changes
OK, so let's disable this test for Shenandoah until the auxbitmap fix is here.

2023-07-14 09:42 UTC, xiangzhai commented
Hi @tstuefe 

> I now remember again. Underlying cause is that AUX bitmap is madviced incorrectly for Shenandoah.

Added `Leslie Zhai Bitmap` and `Ray Zhai Bitmap` before `Aux Bitmap` on purpose for [DEBUG](https://github.com/xiangzhai/jdk/commit/b3a092ea6e461309012869c043243ef014278054) :)

Thanks,
Leslie Zhai

2023-07-14 09:51 UTC, xiangzhai commented
> Can you please change issue subject and PR subject to something like "Disable xxx for Shenandoah", since this does not fix the issue, it just disables the test.

Done.

2023-07-14 09:53 UTC, shipilev requested changes

2023-07-14 09:53 UTC, shipilev commented on test/hotspot/jtreg/runtime/os/TestTracePageSizes.java
> + * @requires vm.gc != "Shenandoah"
No, wait, don't drop "Z" from here. This patch should only affect Shenandoah.

2023-07-14 09:56 UTC, shipilev approved these changes

2023-07-14 13:02 UTC, DamonFool commented
/sponsor

2023-07-14 13:51 UTC, xiangzhai commented
/integrate

2023-07-14 13:53 UTC, DamonFool commented
/sponsor

2023-07-14 13:54 UTC, closed without merging