JDK-8312512: sspi.cpp gss_export_name avoid delete on NULL fullname
openjdk/jdk pull request #14989
Opened 2023-07-24 07:50 UTC by MBaesken

sspi.cpp contains the gss_export_name function, where at the end some cleanup is done by calling delete. However this should be done more careful, because the function get_full_name which is called in gss_export_name might return NULL, so we better avoid calling delete in this case.

2023-07-24 11:01 UTC, djelinski requested changes
`free`, `delete` and `delete[]` are all safe to call on a NULL pointer.

I noticed that we are checking for NULL in other places in this file; could you remove these checks?

2023-07-24 11:25 UTC, MBaesken commented
> `free`, `delete` and `delete[]` are all safe to call on a NULL pointer.
> 
> I noticed that we are checking for NULL in other places in this file; could you remove these checks?

Hi, I found and adjusted a number of places where the pointer ws checked for NULL before calling free/delete in this file.

2023-07-24 11:35 UTC, djelinski approved these changes
LGTM

2023-07-24 12:02 UTC, MBaesken commented
Hi Daniel , thanks for the review !
I adjusted the JBS issue short description text to better reflect what the change now does.

2023-07-25 10:55 UTC, MBaesken commented
/integrate

2023-07-25 10:56 UTC, closed without merging