5032471: JFormattedTextField does not use editformatter on initial focus with setText()
openjdk/jdk pull request #14993
Opened 2023-07-24 09:20 UTC by prsadhuk

When a JFormattedTextField field value is set by setText, then when the field initially gains focus it seems to not use the edit formatter, but rather use display formatter, which is wrong. 
Native "Date and Time setting" in windows changes the date field to edit mode in initial focus itself.
Fix is made to treat setText as in edit mode and commit the changes made to it.

2023-07-25 09:06 UTC, kumarabhi006 commented on src/java.desktop/share/classes/javax/swing/JFormattedTextField.java
> +    public void setText(String text){
```suggestion
    public void setText(String text) {
```

2023-07-25 09:06 UTC, kumarabhi006 commented on src/java.desktop/share/classes/javax/swing/JFormattedTextField.java
> +        if(isEdited() && isEditValid()){
```suggestion
        if (isEdited() && isEditValid()) {
```

2023-07-25 09:06 UTC, kumarabhi006 commented on src/java.desktop/share/classes/javax/swing/JFormattedTextField.java
> +            try{
```suggestion
            try {
```

2023-07-25 09:06 UTC, kumarabhi006 commented on src/java.desktop/share/classes/javax/swing/JFormattedTextField.java
> +            } catch(ParseException pe){}//do nothing, we assume this will never happen.
```suggestion
            } catch (ParseException pe){} //do nothing, we assume this will never happen.
```

2023-07-25 11:17 UTC, aivanov-jdk reviewed
The bug report mentions using `setDocument()` to change the value of the formatted text field. Also, it's possible to call `getDocument().setText()`, which may still have the original bug.

2023-07-25 11:17 UTC, aivanov-jdk commented on src/java.desktop/share/classes/javax/swing/JFormattedTextField.java
> +    public void setText(String text){
Shall the explicit `{@inheritDoc}` be added? Or rather the javadoc should be modified to reflect *the updated behaviour*. There are cases where the text isn't set, right?

2023-07-25 11:17 UTC, aivanov-jdk commented on test/jdk/javax/swing/JFormattedTextField/JFormattedTextProblem.java
> +            JFormattedTextProblem test = new JFormattedTextProblem();
The constructor should be called on EDT because it creates lots of Swing components and Swing components are not thread-safe.

2023-07-25 11:17 UTC, aivanov-jdk commented on test/jdk/javax/swing/JFormattedTextField/JFormattedTextProblem.java
> +            if (!expected) {
Isn't `robot.waitForIdle()` required here to allow the EDT to handle all the events?

2023-07-26 03:26 UTC, prsadhuk commented
> The bug report mentions using `setDocument()` to change the value of the formatted text field. Also, it's possible to call `getDocument().setText()`, which may still have the original bug.

Fixed setDocument but I couldn't find Document.setText that can be called...

2023-07-28 19:40 UTC, aivanov-jdk requested changes
I wonder what happens if `setText` is called with a value that cannot be interpreted by the current formatter and how it plays with different policies on focus lost as outlined in [the javadoc](https://docs.oracle.com/en/java/javase/17/docs/api/java.desktop/javax/swing/JFormattedTextField.html).

2023-07-28 19:40 UTC, aivanov-jdk commented on test/jdk/javax/swing/JFormattedTextField/JFormattedTextProblem.java
> +        SimpleDateFormat editTime = new SimpleDateFormat("HH:mm");
These two variables are unused, should we remove them?

2023-07-28 19:40 UTC, aivanov-jdk commented on test/jdk/javax/swing/JFormattedTextField/JFormattedTextProblem.java
> +import java.beans.PropertyChangeListener;
Could you sort the imports and remove the unused ones?

2023-07-28 19:40 UTC, aivanov-jdk commented on test/jdk/javax/swing/JFormattedTextField/JFormattedTextProblem.java
> +public class JFormattedTextProblem {
Should we use a more descriptive name for the test class?

2023-07-28 19:47 UTC, aivanov-jdk commented
> > The bug report mentions using `setDocument()` to change the value of the formatted text field. Also, it's possible to call `getDocument().setText()`, which may still have the original bug.
> 
> Fixed setDocument but I couldn't find Document.setText that can be called...

Sorry about it, `Document` uses `insertString` method. Perhaps, we shouldn't care about it, if you modify the text using the `Document` interface directly, you could lose the invariants that `JFormattedTextField` provides. The [javadoc](https://docs.oracle.com/en/java/javase/17/docs/api/java.desktop/javax/swing/JFormattedTextField.html) also mentions, that you should not install your own `DocumentFilter` and `NavigationFilter`.

2023-08-04 20:05 UTC, aivanov-jdk commented
> I wonder what happens if `setText` is called with a value that cannot be interpreted by the current formatter and how it plays with different policies on focus lost as outlined in [the javadoc](https://docs.oracle.com/en/java/javase/17/docs/api/java.desktop/javax/swing/JFormattedTextField.html).

~~It should be safe because `commitEdit` is guarded by `isEditValid`.~~

I was about to write the above but I looked deeper in the code, and my opinion has changed dramatically.

Let's see what's happening when `setText` is called. The first thing that's done is `super.setText` is called. So far, so good.

The call `super.setText` mutates the text model, `Document`; as the result, the `edited` flag is set to `true` by `DocumentHandler` and its `insertUpdate` and/or `removeUpdate` methods.

When is the text validated? When is `isEditValid` set to `true` or `false`? The comment for the `setEditValid` method says, “This will invoked by `AbstractFormatter` as the user edits the value.” I can't see where and when `AbstractFormatter` gets called in this case.

Things aren't as clear now…

The documentation for [`JFormattedTextField`](https://docs.oracle.com/en/java/javase/17/docs/api/java.desktop/javax/swing/JFormattedTextField.html#) suggests the `setValue` method should be used to set the value.

When you edit the value, the `setText` method is used to change the displayed text as the `JFormattedTextField` switches into editing mode and back. As such, changing the implementation of `setText` (and `setDocument`) adds an overhead.

It looks as if `setText` and `setDocument` as well as methods of `Document` may mutate the text bypassing the formatter, thus breaking the invariants provided by the `JFormattedTextField` class. Perhaps, if it were possible, the direct access to `setText`, `setDocument` and `getDocument` should be restricted.

---

Taking into account everything I said above, I strongly believe the fix is not necessary and the bug should be closed as either *Not an Issue* or *Won't Fix*.

**The correct fix** to the sample provided is to *use the `setValue` method instead of `setText`*.

In `JFormattedTextProblem.java`, replace the lines 
```java
    dateField.setText(displayDate.format(new Date()));
    timeField.setText(displayTime.format(new Date()));
```
with
```java
    dateField.setValue(new Date());
    timeField.setValue(new Date());
```
and both formatted text fields, `dateField` and `timeField`, behave as expected.

2023-08-30 05:27 UTC, prsadhuk commented
> > I wonder what happens if `setText` is called with a value that cannot be interpreted by the current formatter and how it plays with different policies on focus lost as outlined in [the javadoc](https://docs.oracle.com/en/java/javase/17/docs/api/java.desktop/javax/swing/JFormattedTextField.html).
> 
> ~It should be safe because `commitEdit` is guarded by `isEditValid`.~
> 
> I was about to write the above but I looked deeper in the code, and my opinion has changed dramatically.
> 
> Let's see what's happening when `setText` is called. The first thing that's done is `super.setText` is called. So far, so good.
> 
> The call `super.setText` mutates the text model, `Document`; as the result, the `edited` flag is set to `true` by `DocumentHandler` and its `insertUpdate` and/or `removeUpdate` methods.
> 
> When is the text validated? When is `isEditValid` set to `true` or `false`? The comment for the `setEditValid` method says, “This will invoked by `AbstractFormatter` as the user edits the value.” I can't see where and when `AbstractFormatter` gets called in this case.
> 
> Things aren't as clear now…
> 
> The documentation for [`JFormattedTextField`](https://docs.oracle.com/en/java/javase/17/docs/api/java.desktop/javax/swing/JFormattedTextField.html#) suggests the `setValue` method should be used to set the value.
> 
> When you edit the value, the `setText` method is used to change the displayed text as the `JFormattedTextField` switches into editing mode and back. As such, changing the implementation of `setText` (and `setDocument`) adds an overhead.
> 
> It looks as if `setText` and `setDocument` as well as methods of `Document` may mutate the text bypassing the formatter, thus breaking the invariants provided by the `JFormattedTextField` class. Perhaps, if it were possible, the direct access to `setText`, `setDocument` and `getDocument` should be restricted.
> 
> Taking into account everything I said above, I strongly believe the fix is not necessary and the bug should be closed as either _Not an Issue_ or _Won't Fix_.
> 
> **The correct fix** to the sample provided is to _use the `setValue` method instead of `setText`_.
> 
> In `JFormattedTextProblem.java`, replace the lines
> 
> ```java
>     dateField.setText(displayDate.format(new Date()));
>     timeField.setText(displayTime.format(new Date()));
> ```
> 
> with
> 
> ```java
>     dateField.setValue(new Date());
>     timeField.setValue(new Date());
> ```
> 
> and both formatted text fields, `dateField` and `timeField`, behave as expected.

I tend to agree..Besides the fix is also causing couple of JCK test to fail as setText->commitEdit->setValue->setFormatter->format.install->setText causing StackOverflowError
so seems like setValue, as you told, should be used instead..

Closing this as Not an Issue

2023-08-30 05:29 UTC, closed without merging