JDK-8312467: relax the builddir check in make/autoconf/basic.m4
openjdk/jdk pull request #15017
Opened 2023-07-25 12:00 UTC by MBaesken

In case of issues in the configure step, we run into error messages like this :

configure: Current directory is /openjdk/jdk_4/build_mymachine.
configure: Since this is not the source root, configure will output the configuration here
configure: (as opposed to creating a configuration in <src_root>/build/<conf-name>).
configure: However, this directory is not empty. This is not allowed, since it could
configure: seriously mess up just about everything.
configure: Try 'cd /mysrcdir/jdk' and restart configure
configure: (or create a new empty directory and cd to it).
configure: error: Will not continue creating configuration in /openjdk/jdk_4/build_mymachine
configure exiting with result code 1

Probably the check could be relaxed; it tests for 'if test ! -e "$OUTPUTDIR/spec.gmk"; then ...'
but the non-existance of spec.gmk does not mean we are not in a build directory.
We could additionally check for e.g. $OUTPUTDIR/configure-support/config.log or something related to check if it is a build directory .

2023-07-26 06:53 UTC, RealCLanger requested changes
Looks sensible. However, could you please stick to only one if condition?

`if test ! -e "$OUTPUTDIR/spec.gmk" && test ! -e "$OUTPUTDIR/configure-support/generated-configure.sh"; then`

This will help avoid unnecessary indentation and also keeps the change smaller.

2023-07-26 07:15 UTC, MBaesken commented
Hi Christoph, I adjusted the check.
Additionally I adjusted the output in the failure case, the 'bad' files causing the check to fail are printed now .

2023-07-26 07:41 UTC, RealCLanger approved these changes
This looks good to me but someone from build group needs to review this, too.

2023-07-27 07:25 UTC, MBaesken commented
Hi Christoph, thanks for the review !

May I have a second review ?

2023-08-01 13:45 UTC, MBaesken commented
Any other reviewers ?

2023-08-08 18:34 UTC, erikj79 approved these changes

2023-08-09 07:08 UTC, closed without merging