8314091: Set native thread name for Java main thread
openjdk/jdk pull request #15224
Opened 2023-08-10 12:42 UTC by y1yang0

cat /proc/<java_process>/task/<main thread>/comm shows "java"

User wants it to be "main", just like any other JVM threads, which can be achieved by explicitly calling pthread_setname_np when spawning main thread at VM startup.

2023-08-10 21:08 UTC, dholmes-ora requested changes
I do not agree with this change.

It is a policy decision that the native thread names of attached native threads are not changed by the VM - this includes the initial/starting thread that loads the VM - as those threads belong to the application loading the VM. If it were  desirable to make this kind of change then it would have to happen in the launcher as then we know that we "own" the initial thread.

<deleted incorrect comment about name of primordial thread>

2023-08-10 21:19 UTC, dholmes-ora commented
> this kind of change then it would have to happen in the launcher

Or perhaps if we detect that the launcher type is SUN_STANDARD then we can do it in the VM. That said this will add to startup cost and even if it is very small it is not obvious that such a change should be imposed on all users.

2023-08-11 01:26 UTC, YaSuenag commented
FYI: I proposed same enhancement in [JDK-8152690](https://bugs.openjdk.org/browse/JDK-8152690) 7 years ago, and it closed as "won't fix". We have to consider several cases to be created JVM instance - e.g. created by JNI.

2023-08-11 02:02 UTC, dholmes-ora commented
Thanks for that reminder @YaSuenag I had forgotten about the additional issues that can arise.

2023-08-21 05:58 UTC, closed without merging