JDK-8294090 : Aligns the CSS <rgb()> and <rgba()> function behaviours
openjdk/jdk pull request #15262
Opened 2023-08-13 18:17 UTC by scientificware

This is referenced in Java Bug Database as
- [JDK-8294090 : Aligns the CSS `<rgb()>` and `<rgba()>` function behaviours](https://bugs.java.com/bugdatabase/view_bug?bug_id=8294090)

This is tracked in JBS as 
- [JDK-8294090 : Aligns the CSS `<rgb()>` and `<rgba()>` function behaviours](https://bugs.openjdk.java.net/browse/JDK-8294090)

Aligns the `<rgb()>` and `<rgba()>`  function behaviours in CSS.java, as described in :
CSS Color Module Level 4
W3C Candidate Recommendation Snapshot, 5 July 2022
[4.1 The `<Color>` syntax](https://www.w3.org/TR/css-color-4/#color-syntax)
[6.1. The RGB functions: rgb() and rgba()](https://www.w3.org/TR/css-color-4/#funcdef-rgb)

Designed from : [ScientificWare JDK-8294090 : Aligns the CSS <rgb()> and <rgba()> function behaviours](https://github.com/scientificware/jdk/issues/16)

2023-10-07 23:44 UTC, prrace commented
Read the comment in https://github.com/openjdk/jdk/pull/9825.
This PR needs to be merged into that PR and this PR withdrawn.
Bugs should be closed as dups.

2023-10-07 23:45 UTC, prrace requested changes

2023-10-07 23:46 UTC, prrace commented
I don't intend to do a detailed review of this PR until the content is merged into the other one.

2023-10-09 14:24 UTC, scientificware commented
I close the PR JDK-8294090 and I'll merge its content in #9825.

2023-10-09 14:25 UTC, scientificware commented
I close the PR JDK-8294090 and I'll merge its content in #9825.

2023-10-09 14:25 UTC, closed without merging

2023-10-12 22:07 UTC, scientificware commented on src/java.desktop/share/classes/javax/swing/text/html/CSS.java
> +     * <code>rgb(rc,gc,bc)</code>, <code>rgb(rc gc bc / ac)</code>,
Done.