8314274
openjdk/jdk pull request #15289
Opened 2023-08-15 13:26 UTC by albertnetymk

Add value-range check and explicit type conversion. The second write has its check at the beginning of the method, so doesn't require an assertion.

2023-08-15 18:26 UTC, kimbarrett requested changes

2023-08-15 18:26 UTC, kimbarrett commented on src/hotspot/share/gc/g1/g1CardSetContainers.inline.hpp
> +  _data[0] = static_cast<EntryDataType>(card_in_region);
Shouldn't this be checked_cast rather than static_cast?

2023-08-15 18:26 UTC, kimbarrett commented on src/hotspot/share/gc/g1/g1CardSetContainers.inline.hpp
> +  _data[num_entries] = static_cast<EntryDataType>(card_idx);
Shouldn't this be checked_cast rather than static_cast?

2023-08-16 13:49 UTC, tschatzl approved these changes

2023-08-22 16:10 UTC, kimbarrett approved these changes
Change looks good.

One of us is going to need to deal with the interaction between this and https://git.openjdk.org/jdk/pull/15377

2023-08-22 17:21 UTC, closed without merging