8314651: G1: Fix -Wconversion warnings in static fields of HeapRegion
openjdk/jdk pull request #15360
Opened 2023-08-21 12:25 UTC by albertnetymk

Use unsigned type for heap-region-size related shifts in HeapRegion.
 
Test: tier1-3

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8314651](https://bugs.openjdk.org/browse/JDK-8314651): G1: Fix -Wconversion warnings in static fields of HeapRegion (**Enhancement** - P4)

### Reviewers
 * [Thomas Schatzl](https://openjdk.org/census#tschatzl) (@tschatzl - **Reviewer**)
 * [Ivan Walulya](https://openjdk.org/census#iwalulya) (@walulyai - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15360/head:pull/15360` \
`$ git checkout pull/15360`

Update a local copy of the PR: \
`$ git checkout pull/15360` \
`$ git pull https://git.openjdk.org/jdk.git pull/15360/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15360`

View PR using the GUI difftool: \
`$ git pr show -t 15360`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15360.diff">https://git.openjdk.org/jdk/pull/15360.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15360#issuecomment-1686242519)

2023-08-25 12:12 UTC, albertnetymk commented
/label hotspot-gc

2023-08-29 09:07 UTC, tschatzl requested changes

2023-08-29 09:07 UTC, tschatzl commented on src/hotspot/share/gc/g1/c1/g1BarrierSetC1.cpp
> +                            LIR_OprFact::intConst(static_cast<jint>(HeapRegion::LogOfHRGrainBytes)),
One could maybe argue that this should be a `checked_cast`, but given that the value bounds are known there is no point...

2023-08-29 09:20 UTC, albertnetymk commented on src/hotspot/share/jvmci/vmStructs_jvmci.cpp
> +  static_field(HeapRegion, LogOfHRGrainBytes, uint32_t)
That was my original attempt, but JVMCI related tests failed with `uint`.

2023-08-29 14:35 UTC, tschatzl reviewed
Lgtm.

2023-08-29 14:35 UTC, tschatzl approved these changes

2023-08-29 16:06 UTC, walulyai approved these changes

2023-08-30 09:35 UTC, albertnetymk commented
Thanks for the review.

/integrate

2023-08-30 09:36 UTC, closed without merging