8315020: The macro definition for LoongArch64 zero build is not accurate.
openjdk/jdk pull request #15428
Opened 2023-08-25 10:17 UTC by theaoqi

The `LOONGARCH` is not a macro that must be defined. It is not a C/C++ pre-defined macro and is also not pre-defined in libraries such as libffi. We'd better use a macro defined in jdk.

2023-08-25 20:07 UTC, erikj79 approved these changes

2023-08-26 17:08 UTC, theaoqi commented
I am not sure if this need a second review. If yes, may I have it?

2023-08-27 03:49 UTC, RealFYang requested changes
Two minor nits.

2023-08-27 03:49 UTC, RealFYang commented on src/hotspot/os/linux/os_linux.cpp
> +#elif  (defined LOONGARCH64)
Maybe we should also rename the `LOONGARCH` macro here at this line?https://github.com/openjdk/jdk/blob/master/src/hotspot/os/linux/os_linux.cpp#L1735

2023-08-27 03:49 UTC, RealFYang commented on make/autoconf/platform.m4
> +    HOTSPOT_$1_CPU_DEFINE=LOONGARCH64
Would you mind moving the preceding two lines for RISCV32 to after PPC32? https://github.com/openjdk/jdk/blob/master/make/autoconf/platform.m4#L570C1-L571C34
We only have Zero support for RISCV32 for now. Thanks.

2023-08-27 09:01 UTC, theaoqi commented
Thanks for your advice, @RealFYang. I have updated the patch.

2023-08-27 12:50 UTC, RealFYang approved these changes

2023-08-27 12:53 UTC, theaoqi commented
Thanks @erikj79 and @RealFYang for your review.
/integrate

2023-08-28 11:10 UTC, closed without merging

2023-08-28 11:19 UTC, theaoqi commented
Thank you, @RealFYang.