JDK-8314121: test tools/jpackage/share/RuntimePackageTest.java#id0 fails on RHEL8
openjdk/jdk pull request #15528
Opened 2023-09-01 07:22 UTC by MBaesken

on some RHEL Linux 8.X machines , we run into errors in test tools/jpackage/share/RuntimePackageTest.java#id0 , error can be seen below.
It looks like these errors occur when running the jtreg tests with higher concurrency, I did not see them when running just the single test.

When adding some test output , we see the 2 top install dirs below (1 is expected, not 2) :
./test/unpacked-rpm/opt
./test/unpacked-rpm/usr

error output :

java.lang.AssertionError: Expected [1]. Actual [2]: Check the package has 1 top installation directories
       at jdk.jpackage.test.TKit.error(TKit.java:273)
       at jdk.jpackage.test.TKit.assertEquals(TKit.java:576)
       at jdk.jpackage.test.PackageTest$Handler.verifyRootCountInUnpackedPackage(PackageTest.java:705)
       at jdk.jpackage.test.PackageTest$Handler.lambda$verifyPackageInstalled$3(PackageTest.java:635)
       at java.base/java.util.Optional.ifPresent(Optional.java:178)
       at jdk.jpackage.test.PackageTest$Handler.verifyPackageInstalled(PackageTest.java:633)
       at jdk.jpackage.test.PackageTest$Handler.accept(PackageTest.java:592)
       at jdk.jpackage.test.PackageTest$2.accept(PackageTest.java:504)
       at jdk.jpackage.test.PackageTest$2.accept(PackageTest.java:411)
       at jdk.jpackage.test.Functional$ThrowingConsumer.lambda$toConsumer$0(Functional.java:41)
       at java.base/java.lang.Iterable.forEach(Iterable.java:75)
       at jdk.jpackage.test.PackageTest.lambda$runActions$24(PackageTest.java:381)
       at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
       at jdk.jpackage.test.PackageTest.lambda$runActions$25(PackageTest.java:380)
       at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
       at jdk.jpackage.test.PackageTest.runActions(PackageTest.java:379)
       at jdk.jpackage.test.RunnablePackageTest.run(RunnablePackageTest.java:58)
       at RuntimePackageTest.test(RuntimePackageTest.java:83)
       at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
       at java.base/java.lang.reflect.Method.invoke(Method.java:580)
       at jdk.jpackage.test.MethodCall.accept(MethodCall.java:145)
       at jdk.jpackage.test.TestInstance.run(TestInstance.java:230)
       at jdk.jpackage.test.TKit.lambda$ignoreExceptions$5(TKit.java:141)
       at jdk.jpackage.test.TKit.lambda$runTests$3(TKit.java:126)
       at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
       at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
       at jdk.jpackage.test.TKit.lambda$runTests$4(TKit.java:123)
       at jdk.jpackage.test.Functional$ThrowingRunnable.lambda$toRunnable$0(Functional.java:105)
       at jdk.jpackage.test.TKit.withExtraLogStream(TKit.java:109)
       at jdk.jpackage.test.TKit.runTests(TKit.java:122)
       at jdk.jpackage.test.Main.runTests(Main.java:79)
       at jdk.jpackage.test.Main.lambda$main$2(Main.java:75)
       at jdk.jpackage.test.Functional$ThrowingRunnable.lambda$toRunnable$0(Functional.java:105)
       at jdk.jpackage.test.TKit.withExtraLogStream(TKit.java:109)
       at jdk.jpackage.test.Main.main(Main.java:75)
       at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
       at java.base/java.lang.reflect.Method.invoke(Method.java:580)
       at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
       at java.base/java.lang.Thread.run(Thread.java:1570)

Looks like the additional dir /usr/lib/.build-id  is coming from automatically adding /usr/lib/.build-id to package; this seems to be a feature of the rpmbuild according to https://bugzilla.redhat.com/show_bug.cgi?id=1724153   and must be configured in template.spec if it is unwanted.

2023-09-05 08:19 UTC, RealLucy approved these changes
LGTM.
Thanks for fixing. The add'l output doesn't fix anything, but may be helpful in the future.

2023-09-05 08:48 UTC, MBaesken commented
Hi Lutz, thanks for the review !
I'll wait a little more maybe Alexey has still something to comment.

2023-09-05 20:49 UTC, alexeysemenyukoracle requested changes

2023-09-06 07:22 UTC, MBaesken commented on test/jdk/tools/jpackage/helpers/jdk/jpackage/test/PackageTest.java
> +
Hi Alexey, I removed the output from the test .

2023-09-06 23:07 UTC, alexeysemenyukoracle approved these changes

2023-09-07 07:29 UTC, MBaesken commented
Hi Alexey,  thanks for the review !

/integrate

2023-09-07 07:30 UTC, closed without merging