8315652: RISC-V: Features string uses wrong separator for jtreg
openjdk/jdk pull request #15579
Opened 2023-09-06 06:14 UTC by robehn

Hi, please consider.

As described in jbs, this handles both cases with a rough solution by having two strings.
Meaning we get e.g. 'v' as a separate feature from CPUInfo, but we still get the pretty string in e.g. hs_err.

Tested tier1 on rv.

2023-09-07 07:56 UTC, RealFYang requested changes
Hi, I have a small question about the JBS description. Where does the comma in the string we are regexping comes from if we use plain space here?
I am wondering if we could do the separation for the original `_features_string`. This would help elimnate changes to the shared code. I guess it might not be a big issue for other places.

2023-09-07 08:36 UTC, robehn commented on src/hotspot/os_cpu/linux_riscv/vm_version_linux_riscv.cpp
> +  _parsable_features_string = os::strdup(buf);
Yes, this looks wrong. I'll investigate way this was working in testing. It seem like it should not have....

2023-09-07 08:50 UTC, robehn commented
> Hi, I have a small question about the JBS description. Where does the comma in the string we are regexping comes from if we use plain space here? I am also wondering if we could do the separation for the original `_features_string`. This would help elimnate changes to the shared code. I guess it might not be a big issue for other places.

CPUInfo.java splits the feature string into a List<String>, so the string supplied to jtreg required annotation is Arrays.toString().
So e.g. "rv64 i g c v zicbop z..." is in a List with strings: "rv64", "i", "g", "c", "v", "zicbop,"....
toString() returns:
"[rv64, i, g, c, v, zicbop, z...]"

Yes, we could do the separation from the original string but adding a method to parse out everything didn't seem better.
I think it actually easier to do the other way around having the feature flags with separator and then remove them for 'pretty' print string. But not clear to me that it would be an improvement, i.e. having more code dealing with strings.

2023-09-07 12:24 UTC, robehn commented on src/hotspot/os_cpu/linux_riscv/vm_version_linux_riscv.cpp
> +  _parsable_features_string = os::strdup(buf);
Yes, this was not working at all. I found the issue in my testing. Good catch! Thanks alot!

2023-09-07 14:19 UTC, RealFYang commented
> > Hi, I have a small question about the JBS description. Where does the comma in the string we are regexping comes from if we use plain space here? I am also wondering if we could do the separation for the original `_features_string`. This would help elimnate changes to the shared code. I guess it might not be a big issue for other places.
> 
> CPUInfo.java splits the feature string into a List, so the string supplied to jtreg required annotation is Arrays.toString(). So e.g. "rv64 i g c v zicbop z..." is in a List with strings: "rv64", "i", "g", "c", "v", "zicbop,".... toString() returns: "[rv64, i, g, c, v, zicbop, z...]"

Thanks for the explaination.

> Yes, we could do the separation from the original string but adding a method to parse out everything didn't seem better. I think it actually easier to do the other way around having the feature flags with separator and then remove them for 'pretty' print string. But not clear to me that it would be an improvement, i.e. having more code dealing with strings.

In fact, I mean simply keeping the feature flags with space separators in `_features_string` without removing them for 'pretty' print string. As you mentioned on JBS, then we would have CPU info/desc like: 
"CPU: total 16 (initial active 16) rv64 i m a f d c v zicbom zicboz zicbop zba zbb zbs zicsr zifencei zic64b zihintpause"
This seems acceptable to me. Please consider.

2023-09-08 04:53 UTC, robehn commented
> In fact, I mean simply keeping the feature flags with space separators in `_features_string` without removing them for 'pretty' print string. As you mentioned on JBS, then we would have CPU info/desc like: "CPU: total 16 (initial active 16) rv64 i m a f d c v zicbom zicboz zicbop zba zbb zbs zicsr zifencei zic64b zihintpause" This seems acceptable to me. Please consider.

Yes, sure I'll change!

2023-09-08 10:55 UTC, RealFYang approved these changes
LGTM. Thanks.

2023-09-12 12:08 UTC, luhenry approved these changes

2023-09-13 04:58 UTC, robehn commented
/integrate

2023-09-13 04:59 UTC, closed without merging