8257436: [aarch64] Regressions in ArrayCopyUnalignedDst.testByte/testChar for 65-78 bytes when UseSIMDForMemoryOps is on
openjdk/jdk pull request #1558
Opened 2020-12-02 10:12 UTC by eastig

Copying data in range 65 - 80 bytes with
```
ldpq
ldpq 
ldp
stpq
stpq
stp
```
is faster than with
```
ldpq
ldpq
ldpq
stpq
stpq
stpq
```
This fixes regressions of ArrayCopyUnalignedDst.testByte/testChar when UseSIMDForMemoryOps is on.
See the attached results for performance data
[test_byte_results.txt](https://github.com/openjdk/jdk/files/5628447/test_byte_results.txt)
[test_char_results.txt](https://github.com/openjdk/jdk/files/5628451/test_char_results.txt)
[test_int_results.txt](https://github.com/openjdk/jdk/files/5628462/test_int_results.txt)
[test_long_results.txt](https://github.com/openjdk/jdk/files/5628468/test_long_results.txt)

2020-12-02 10:46 UTC, eastig commented
@theRealAph could please check if it causes any issues on ThunderX 2?

Thanks,
Evgeny

2020-12-02 10:56 UTC, theRealAph commented
> @theRealAph could please check if it causes any issues on ThunderX 2?

Is there some script you use that generates the comparison? Otherwise it'll take some time.

2020-12-02 11:12 UTC, eastig commented
> > @theRealAph could please check if it causes any issues on ThunderX 2?
> 
> Is there some script you use that generates the comparison? Otherwise it'll take some time.

Unfortunately, no. I have scripts that do runs. Then I pull all results in Excel.
BTW, I attached data comparing SIMD_OFF vs SIMD_ON(patch). JDK-8257436 has data showing regressions with SIMD three ldpq instructions. I'll attach data comparing SIMD_no_fix vs SIMD_fix later.

2020-12-02 14:04 UTC, eastig commented
I updated the attached data. It now includes the following:
- UseSIMDForMemoryOps is off.
- UseSIMDForMemoryOps is on.
- UseSIMDForMemoryOps + fix is on.

The fix is narrowed to be used for byte and char arraycopies. They have the most problems with unaligned accesses. Int arraycopies are at least 4 byte aligned. Long arraycopies are always 8 byte aligned.

2020-12-02 18:26 UTC, eastig commented
I am attaching performance data for int arraycopy to show the impact of the patch on it:
[test_int_results.txt](https://github.com/openjdk/jdk/files/5631318/test_int_results.txt)

2020-12-03 10:02 UTC, simonis requested changes
Hi Evegeny,

thanks for fixing this. Your change looks good to me. Thanks especially for measuring all the different cases.

I only have two minor request regarding the comments. Once fixed I'll sponsor this change.

Best regards,
Volker

2020-12-03 13:54 UTC, eastig commented on src/hotspot/cpu/aarch64/stubGenerator_aarch64.cpp
> +      // This have more chances to happen when granularity of data is
Done

2020-12-03 13:54 UTC, eastig commented on src/hotspot/cpu/aarch64/stubGenerator_aarch64.cpp
>      // <= 96 bytes do inline. Direction doesn't matter because we always
Done.

2020-12-03 14:03 UTC, simonis approved these changes
Looks good now. Thanks!

2020-12-03 14:04 UTC, eastig commented
/integrate

2020-12-03 15:55 UTC, simonis commented
/sponsor

2020-12-03 15:55 UTC, closed without merging