8315794: RISC-V: build fails with GCC 12.3
openjdk/jdk pull request #15593
Opened 2023-09-06 14:29 UTC by gctony

The build failure happens when building on RISC-V with GCC 12.3. Is there a better way to address this than disabling the stringop-overflow warnings for the two files in question?

2023-09-07 01:38 UTC, RealFYang commented
Hi, I once created a similar JBS issue and provided a workaround for this problem: https://bugs.openjdk.org/browse/JDK-8299580. As discussed on PR: https://github.com/openjdk/jdk/pull/11858, the mentioned HotSpot code looks fine and this looks like a GCC-12 suprious warning. And we intend to think that it should be a GCC bug. 

But I think it's better to disabling the stringop-overflow warnings for the affected files like you do in this PR.

2023-09-07 01:42 UTC, RealFYang approved these changes

2023-09-07 07:01 UTC, robehn approved these changes
Thanks!

I don't see any other non-trivial work around, the issue is in gcc 13 also.

2023-09-07 11:08 UTC, theRealAph commented
Just for the record, this is very likely https://gcc.gnu.org/bugzilla/show_bug.cgi?id=104475 .

2023-09-07 18:32 UTC, kimbarrett commented
The fix for [JDK-8294031](https://bugs.openjdk.org/browse/JDK-8294031) was to make various error reporting functions `[[noreturn]]`. Is there perhaps a missing `[[noreturn]]` in the RISC-V code? Or is there some other statically apparent but never actually taken code path? Also, does the failure happen in release builds, or only (fast)debug builds? More details about the failure would be helpful.

2023-09-07 18:35 UTC, kimbarrett commented
I'd like to not disable the warnings without a better understanding of the problem.  I agree with @theRealAph that gcc
bug 104475 is likely where the warning is coming from.  But it may be that giving gcc better control flow information
via appropriate `[[noreturn]]` or (something like) `std::unreachable()` might be better.

2023-09-07 20:56 UTC, gctony commented
> Just for the record, this is very likely https://gcc.gnu.org/bugzilla/show_bug.cgi?id=104475 .

Thanks for the heads up!

2023-09-07 21:03 UTC, gctony commented
> Hi, I once created a similar JBS issue and provided a workaround for this problem: https://bugs.openjdk.org/browse/JDK-8299580. As discussed on PR: #11858, the mentioned HotSpot code looks fine and this looks like a GCC-12 suprious warning. So we intend to think that it should be a GCC bug.
> 
> I think it's better to disabling the stringop-overflow warnings for the affected files like you do in this PR.

@RealFYang Thanks for mentioning this! I did try to find other similar issues but I somehow missed it. Yeah, I also looked at the code and I didn't see anything obvious. Also, in the case I'm looking at, I don't think there's anything RISC-V-specific?

2023-09-07 21:19 UTC, gctony commented
@kimbarrett @erikj79 Thanks for taking a look.

> Generally when we disable warnings, we document in the bug why the warning is benign or incorrect in this case, or file a followup bug to address it properly.

> I'd like to not disable the warnings without a better understanding of the problem.

I understand. I just can't figure out what's causing this. The call is a few nested templates and I don't understand why the type passed to the outermost one ends up as `void*` in the innermost one.

> The fix for [JDK-8294031](https://bugs.openjdk.org/browse/JDK-8294031) was to make various error reporting functions `[[noreturn]]`. Is there perhaps a missing `[[noreturn]]` in the RISC-V code?

I don't think the issue is RISC-V-specific. It's in two shared files (`xPageAllocator.cpp` and `zPageAllocator.cpp`).

> Also, does the failure happen in release builds, or only (fast)debug builds? 

Both.

2023-09-07 21:24 UTC, gctony commented
I should have included the full error messages (my bad):

```
In file included from /home/tony/dev/ws/git/jdk-devel/src/hotspot/share/runtime/atomic.hpp:814,
                 from /home/tony/dev/ws/git/jdk-devel/src/hotspot/share/oops/oop.hpp:34,
                 from /home/tony/dev/ws/git/jdk-devel/src/hotspot/share/oops/weakHandle.hpp:28,
                 from /home/tony/dev/ws/git/jdk-devel/src/hotspot/share/classfile/classLoaderData.hpp:30,
                 from /home/tony/dev/ws/git/jdk-devel/src/hotspot/share/precompiled/precompiled.hpp:34:
In member function 'D Atomic::PlatformAdd<byte_size>::add_then_fetch(volatile D*, I, atomic_memory_order) const [with D = long unsigned int; I = long unsigned int; long unsigned int byte_size = 8]',
    inlined from 'static D Atomic::AddImpl<D, I, typename std::enable_if<(((std::is_integral<From>::value && std::is_integral<_Tp>::value) && (sizeof (I) <= sizeof (D))) && (std::is_signed<I>::value == std::is_signed<_Tp>::value)), void>::type>::add_then_fetch(volatile D*, I, atomic_memory_order) [with D = long unsigned int; I = long unsigned int]' at /home/tony/dev/ws/git/jdk-devel/src/hotspot/share/runtime/atomic.hpp:888:51,
    inlined from 'static D Atomic::add(volatile D*, I, atomic_memory_order) [with D = long unsigned int; I = long unsigned int]' at /home/tony/dev/ws/git/jdk-devel/src/hotspot/share/runtime/atomic.hpp:869:39,
    inlined from 'size_t XPageAllocator::uncommit(uint64_t*)' at /home/tony/dev/ws/git/jdk-devel/src/hotspot/share/gc/x/xPageAllocator.cpp:789:16:
/home/tony/dev/ws/git/jdk-devel/src/hotspot/os_cpu/linux_riscv/atomic_linux_riscv.hpp:44:31: error: 'long unsigned int __atomic_add_fetch_8(volatile void*, long unsigned int, int)' writing 8 bytes into a region of size 0 overflows the destination [-Werror=stringop-overflow=]
   44 |     D res = __atomic_add_fetch(dest, add_value, __ATOMIC_RELAXED);
      |             ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/tony/dev/ws/git/jdk-devel/src/hotspot/share/runtime/atomic.hpp:814,
                 from /home/tony/dev/ws/git/jdk-devel/src/hotspot/share/oops/oop.hpp:34,
                 from /home/tony/dev/ws/git/jdk-devel/src/hotspot/share/oops/weakHandle.hpp:28,
                 from /home/tony/dev/ws/git/jdk-devel/src/hotspot/share/classfile/classLoaderData.hpp:30,
                 from /home/tony/dev/ws/git/jdk-devel/src/hotspot/share/precompiled/precompiled.hpp:34:
In member function 'D Atomic::PlatformAdd<byte_size>::add_then_fetch(volatile D*, I, atomic_memory_order) const [with D = long unsigned int; I = long unsigned int; long unsigned int byte_size = 8]',
    inlined from 'static D Atomic::AddImpl<D, I, typename std::enable_if<(((std::is_integral<From>::value && std::is_integral<_Tp>::value) && (sizeof (I) <= sizeof (D))) && (std::is_signed<I>::value == std::is_signed<_Tp>::value)), void>::type>::add_then_fetch(volatile D*, I, atomic_memory_order) [with D = long unsigned int; I = long unsigned int]' at /home/tony/dev/ws/git/jdk-devel/src/hotspot/share/runtime/atomic.hpp:888:51,
    inlined from 'static D Atomic::add(volatile D*, I, atomic_memory_order) [with D = long unsigned int; I = long unsigned int]' at /home/tony/dev/ws/git/jdk-devel/src/hotspot/share/runtime/atomic.hpp:869:39,
    inlined from 'size_t ZPageAllocator::uncommit(uint64_t*)' at /home/tony/dev/ws/git/jdk-devel/src/hotspot/share/gc/z/zPageAllocator.cpp:887:16:
/home/tony/dev/ws/git/jdk-devel/src/hotspot/os_cpu/linux_riscv/atomic_linux_riscv.hpp:44:31: error: 'long unsigned int __atomic_add_fetch_8(volatile void*, long unsigned int, int)' writing 8 bytes into a region of size 0 overflows the destination [-Werror=stringop-overflow=]
   44 |     D res = __atomic_add_fetch(dest, add_value, __ATOMIC_RELAXED);
      |             ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
```

Looks the same as [JDK-8299580](https://bugs.openjdk.org/browse/JDK-8299580) that @RealFYang had reported?

2023-09-13 18:18 UTC, kimbarrett commented
It seems to be complaining about atomic increment of a data member,
which is really weird.

```
Atomic::add(&_claimed, flushed);
```

When we saw this warning in other places it was because we were
passing a pointer that was known to be null on some (not supposed to
be reachable) code paths. I don't see how that can be what's going on
here though.

There's an Atomic::sub on the same data member a few lines later. Does
that get warned about?  And why these?  I'm pretty sure there are
other places where we do the same thing.  (I'm assuming this warning
isn't showing up elsewhere.)

Disabling the warning for this file feels a bit too much like voodoo,
though might be all we've got right now.

2023-09-14 08:00 UTC, robehn commented
> It seems to be complaining about atomic increment of a data member, which is really weird.
> 
> ```
> Atomic::add(&_claimed, flushed);
> ```
> 
> When we saw this warning in other places it was because we were passing a pointer that was known to be null on some (not supposed to be reachable) code paths. I don't see how that can be what's going on here though.
> 
> There's an Atomic::sub on the same data member a few lines later. Does that get warned about? And why these? I'm pretty sure there are other places where we do the same thing. (I'm assuming this warning isn't showing up elsewhere.)
> 
> Disabling the warning for this file feels a bit too much like voodoo, though might be all we've got right now.

Yes, I also saw that inconsistency with _claimed, only add.

2023-09-15 17:29 UTC, gctony commented
> When we saw this warning in other places it was because we were
> passing a pointer that was known to be null on some (not supposed to
> be reachable) code paths. I don't see how that can be what's going on
> here though.

Yeah, I've been perplexed too.

> There's an Atomic::sub on the same data member a few lines later. Does that get warned about? And why these?

Very interesting. If I comment out the calls to `Atomic::add()` that trigger the compilation failure (in `xPageAllocator.cpp` and `zPageAllocator.cpp`), the build succeeds. If I replace them with `Atomic::sub()`, I get the same failure. Interesting that the compiler doesn't complain about the call to `Atomic::sub()` a bit further down (with the same args!), as you pointed out.

> Disabling the warning for this file feels a bit too much like voodoo,
> though might be all we've got right now.

I'll spend a bit more time to see if there's a better way to fix this. But, is there a way to disable the warning only for RISC-V builds, instead of all builds?

2023-09-16 13:49 UTC, gctony commented
Looks as if adding the pragma in the two .cpp files also seems to work:

```
     // Record flushed pages as claimed
+    PRAGMA_STRINGOP_OVERFLOW_IGNORED
     Atomic::add(&_claimed, flushed);
```

Not sure why it doesn't work when I put the pragma in `PlatformAdd::add_then_fetch` in `atomic_linux_riscv.hpp`.

2023-09-18 19:29 UTC, gctony commented
How about something like this in `zPageAllocator.cpp` / `xPageAllocator.cpp` as a compromise?

```
+    PRAGMA_DIAG_PUSH
+    PRAGMA_STRINGOP_OVERFLOW_IGNORED
     // Record flushed pages as claimed
     Atomic::add(&_claimed, flushed);
+    PRAGMA_DIAG_POP
```

This should only disable the warning for the two uses of `Atomic::add()` that exhibit the issue.

@kimbarrett @erikj79 I know you two had concerns about disabling the warning for the entire files. Does this look reasonable?

2023-09-18 22:29 UTC, erikj79 commented
> @erikj79 I know you two had concerns about disabling the warning for the entire files. Does this look reasonable?

If you disable it the warning with a pragma, I don't have any opinion as it doesn't affect the build.

2023-09-18 23:41 UTC, kimbarrett commented
> How about something like this in `zPageAllocator.cpp` / `xPageAllocator.cpp` as a compromise?
> 
> ```
> +    PRAGMA_DIAG_PUSH
> +    PRAGMA_STRINGOP_OVERFLOW_IGNORED
>      // Record flushed pages as claimed
>      Atomic::add(&_claimed, flushed);
> +    PRAGMA_DIAG_POP
> ```
> 
> This should only disable the warning for the two uses of `Atomic::add()` that exhibit the issue.

I think I'd prefer
```
RISCV_ONLY(PRAGMA_STRINGOP_OVERFLOW_IGNORED)
```
unless and until we encounter the problem for some other platform.

2023-09-19 14:08 UTC, gctony commented
> I think I'd prefer
> 
> ```
> RISCV_ONLY(PRAGMA_STRINGOP_OVERFLOW_IGNORED)
> ```
> 
> unless and until we encounter the problem for some other platform.

Fair. See updated patch.

2023-09-19 14:37 UTC, robehn approved these changes

2023-09-20 20:51 UTC, gctony commented
Hey, I'll integrate this tomorrow if there are no more concerns. Thank you.

2023-09-21 03:46 UTC, kimbarrett approved these changes

2023-09-21 09:36 UTC, magicus commented
/label -build
/label hotspot-gc

2023-09-21 10:14 UTC, luhenry approved these changes

2023-09-21 12:33 UTC, stefank requested changes
I find it a bit unfortunate if we have to add this to the ZGC code. Could we instead handle this by turning off the warning in these files when you compile with gcc + riscv? Maybe something like this:
```
diff --git a/make/common/NativeCompilation.gmk b/make/common/NativeCompilation.gmk
index 6056f4632a5..b0d3c158ffe 100644
--- a/make/common/NativeCompilation.gmk
+++ b/make/common/NativeCompilation.gmk
@@ -363,7 +363,8 @@ define SetupCompileNativeFileBody
     ifneq ($(DISABLE_WARNING_PREFIX), )
       $1_WARNINGS_FLAGS := $$(addprefix $(DISABLE_WARNING_PREFIX), \
         $$($$($1_BASE)_DISABLED_WARNINGS_$(TOOLCHAIN_TYPE)_$$($1_FILENAME)) \
-        $$($$($1_BASE)_DISABLED_WARNINGS_$(TOOLCHAIN_TYPE)_$(OPENJDK_TARGET_OS)_$$($1_FILENAME)))
+        $$($$($1_BASE)_DISABLED_WARNINGS_$(TOOLCHAIN_TYPE)_$(OPENJDK_TARGET_OS)_$$($1_FILENAME)) \
+        $$($$($1_BASE)_DISABLED_WARNINGS_$(TOOLCHAIN_TYPE)_$(OPENJDK_TARGET_OS)_$(OPENJDK_TARGET_CPU)_$$($1_FILENAME)) )
     endif
 
     $1_BASE_CFLAGS :=  $$($$($1_BASE)_CFLAGS) $$($$($1_BASE)_EXTRA_CFLAGS) \
diff --git a/make/hotspot/lib/CompileJvm.gmk b/make/hotspot/lib/CompileJvm.gmk
index 0123829afee..9ef82905dbb 100644
--- a/make/hotspot/lib/CompileJvm.gmk
+++ b/make/hotspot/lib/CompileJvm.gmk
@@ -166,6 +166,8 @@ $(eval $(call SetupJdkLibrary, BUILD_LIBJVM, \
     DISABLED_WARNINGS_gcc_cgroupV2Subsystem_linux.cpp := address, \
     DISABLED_WARNINGS_gcc_interp_masm_x86.cpp := uninitialized, \
     DISABLED_WARNINGS_gcc_postaloc.cpp := address, \
+    DISABLED_WARNINGS_gcc_linux_riscv64_xPageAllocator.cpp := stringop-overflow, \
+    DISABLED_WARNINGS_gcc_linux_riscv64_zPageAllocator.cpp := stringop-overflow, \
     DISABLED_WARNINGS_clang := $(DISABLED_WARNINGS_clang), \
     DISABLED_WARNINGS_clang_arguments.cpp := missing-field-initializers, \
     DISABLED_WARNINGS_clang_codeBuffer.cpp := tautological-undefined-compare, \
```

2023-09-21 13:48 UTC, magicus commented
That seems like a reasonable extension to the functionality in NativeCompilation.gmk.

2023-10-23 22:40 UTC, gctony commented
I'm actually going to close this. The issue seems to have disappeared. I did review some of the changes that went in and I'm not sure which one is responsible for fixing it. But I can build the current HEAD on both a RISC-V vm and my VisionFive 2 board with GCC 12.3 and with no failures.

If it re-occurs, the fix suggested by @stefank is probably the best trade-off.

2023-10-23 22:40 UTC, closed without merging