8315683: Parallelize java/util/concurrent/tck/JSR166TestCase.java
openjdk/jdk pull request #15619
Opened 2023-09-07 13:55 UTC by roy-soumadipta

This test is running in tier1, and takes about 400 seconds to complete. Thus, it drags the execution time of tier1 on large machines. The commit includes changing the sequential run of test cases in java/util/concurrent/tck/JSR166TestCase.java to the best possible combination of parallelization to reduce the total runtime of the overall test and causing least possible change to user and system times. The below comparison shows existing and newer combinations of parallelizations:
before                 : make test CONF=macosx-aarch64-server-fastdebug   200.64s user 20.94s system 204% cpu 1:48.47 total
fully parallel         : make test CONF=macosx-aarch64-server-fastdebug   308.84s user 23.75s system 479% cpu 1:09.42 total
default-details-tck    : make test CONF=macosx-aarch64-server-fastdebug   244.69s user 22.03s system 314% cpu 1:24.94 total
default-fjp_details-tck : make test CONF=macosx-aarch64-server-fastdebug   260.12s user 24.47s system 404% cpu 1:10.31 total

Based on the comparison above, the fourth combination has a result very close to full parallelization and at the same time having the least deviation of system and user times among the newer combinations. Hence the commit includes the changes corresponding to the fourth combination.

2023-09-07 15:56 UTC, Martin-Buchholz commented on test/jdk/java/util/concurrent/tck/JSR166TestCase.java
>   * @summary JSR-166 tck tests, in a number of variations.
The @summary is stale - it describes the state when there was only one @test

2023-09-07 15:58 UTC, Martin-Buchholz commented on test/jdk/java/util/concurrent/tck/JSR166TestCase.java
>   * @run junit/othervm/timeout=1000 -Djava.security.manager=allow JSR166TestCase
security manager testing is relatively less important.   I would move this to a lower tier, while moving a test with -Djsr166.testImplementationDetails=true into tier1

2023-09-07 16:08 UTC, Martin-Buchholz requested changes
Hello Soumadipta - pleased to "meet" you.

If the intent is to split the tests into relatively more and less important variants for placing into separate tiers, that should be clear from the @summary's in the tests.

2023-09-13 12:24 UTC, roy-soumadipta commented
> Hello Soumadipta - pleased to "meet" you.
> 
> If the intent is to split the tests into relatively more and less important variants for placing into separate tiers, that should be clear from the @summary's in the tests.

Hi @Martin-Buchholz the latest commit addresses the comment regarding missing summary for each section of tests. Also from the JBS bug, I can see it has been agreed to have a separate PR for improvements to the test itself and segregation into appropriate tiers.

2023-09-14 04:29 UTC, Martin-Buchholz approved these changes

2023-09-14 04:29 UTC, Martin-Buchholz commented on test/jdk/java/util/concurrent/tck/JSR166TestCase.java
>   * @run junit/othervm/timeout=1000 -Djava.security.manager=allow JSR166TestCase
I still think the test with -Djava.security.manager=allow is relatively low value, so would also move it into its own @test id=security-manager

2023-09-14 08:02 UTC, roy-soumadipta commented
Hi @Martin-Buchholz I have created a separate test case for security manager as you requested. The deviations of user and system times are very less from the initial comment and with total running time improvement: **285.76s user 23.37s system 492% cpu 1:02.76 total**.
Request your re-approval on the latest changes.

2023-09-14 14:05 UTC, Martin-Buchholz approved these changes
Thanks!

2023-09-14 14:13 UTC, shipilev approved these changes

2023-09-14 14:20 UTC, roy-soumadipta commented
/integrate

2023-09-14 15:22 UTC, roy-soumadipta commented
Hi @Martin-Buchholz can you please sponsor the PR

2023-09-14 19:21 UTC, Martin-Buchholz commented
/sponsor

2023-09-14 19:22 UTC, closed without merging