8314832: Few runtime/os tests ignore vm flags
openjdk/jdk pull request #15647
Opened 2023-09-08 22:31 UTC by mseledts

2023-09-11 07:41 UTC, dholmes-ora requested changes

2023-09-11 07:41 UTC, dholmes-ora commented on test/hotspot/jtreg/runtime/os/THPsInThreadStackPreventionTest.java
I think this test should also be marked vm.flagless. Running with additional flags, especially something like -Xcomp, could have an effect on the RSS usage that the test is trying to measure. Other flags really have no bearing on what is being tested here.

2023-09-11 16:38 UTC, mseledts commented on test/hotspot/jtreg/runtime/os/THPsInThreadStackPreventionTest.java
David, thank you for advice. I will update the test to make it "flagless".

2023-09-12 00:34 UTC, dholmes-ora approved these changes
I don't think we need to add flagless to the manual tests, but I'm not sure. I will leave it to you.

Thanks

2023-09-12 00:34 UTC, dholmes-ora commented on test/hotspot/jtreg/runtime/os/THPsInThreadStackPreventionTest.java
> + * @requires vm.flagless
Not sure this is needed here as this is a manual test

2023-09-12 00:34 UTC, dholmes-ora commented on test/hotspot/jtreg/runtime/os/TestTrimNative.java
> + * @requires vm.flagless
Ditto perhaps not needed for a manual test

2023-09-12 00:34 UTC, dholmes-ora commented on test/hotspot/jtreg/runtime/os/TestTrimNative.java
> + * @requires vm.flagless
Ditto manual test

2023-09-12 01:30 UTC, lmesnik approved these changes

2023-09-12 14:37 UTC, mseledts commented
Thank you David, Leonid.

/integrate

2023-09-12 14:40 UTC, closed without merging