8315726: Open source several AWT applet tests
openjdk/jdk pull request #15671
Opened 2023-09-11 22:18 UTC by azvegint

Some closed AWT test are open sourced.

2023-09-12 08:38 UTC, prsadhuk approved these changes

2023-09-12 08:38 UTC, prsadhuk commented on test/jdk/java/awt/Component/Displayable.java
> +            f.dispose();
GUess it will be better to do dispose in try-finally block

2023-09-12 08:44 UTC, turbanoff commented on test/jdk/java/awt/Focus/TestWindowsLFFocus.java
> +                location.y +=  bar.getHeight() / 2 + item.getHeight() / 2;
```suggestion
                location.y += bar.getHeight() / 2 + item.getHeight() / 2;
```

2023-09-12 12:20 UTC, azvegint commented on test/jdk/java/awt/Focus/TestWindowsLFFocus.java
> +                location.y +=  bar.getHeight() / 2 + item.getHeight() / 2;
Fixed

2023-09-12 21:04 UTC, aivanov-jdk requested changes

2023-09-12 21:40 UTC, azvegint commented on test/jdk/java/awt/Choice/ChoiceSelectTest.java
> +    Choice c;
Sure.

2023-09-12 21:40 UTC, azvegint commented on test/jdk/java/awt/Choice/ChoiceSelectTest.java
> +    }
No, it can't, Choice is heavyweight component: https://github.com/openjdk/jdk/blob/master/src/java.desktop/share/classes/java/awt/Choice.java#L116

2023-09-12 21:40 UTC, azvegint commented on test/jdk/java/awt/geom/HitTest/PathHitTestManual.java
> +                /* contains?  point in?  intersects? */
Fixed.

2023-09-13 19:15 UTC, aivanov-jdk commented on test/jdk/java/awt/Choice/ChoiceSelectTest.java
> +    }
Right, heavyweight can't even be created in headless mode.

2023-09-13 22:23 UTC, azvegint commented
/integrate

2023-09-13 22:23 UTC, closed without merging