8316115
openjdk/jdk pull request #15682
Opened 2023-09-12 11:48 UTC by albertnetymk

Essentially same as https://github.com/openjdk/jdk/pull/15541, but for Parallel.

2023-09-12 12:43 UTC, shipilev requested changes
See multiple failures in GHA :)

2023-09-13 12:14 UTC, tschatzl approved these changes
Looks good. Please fix the indentation issue before pushing.

2023-09-13 12:14 UTC, tschatzl commented on src/hotspot/share/gc/parallel/mutableNUMASpace.hpp
> +    uint lgrp_id() const                             { return _lgrp_id;             }
Indentation

2023-09-14 11:37 UTC, albertnetymk commented
@shipilev GHA builds are green now. The current test failures are unrelated to this PR.

2023-09-14 12:09 UTC, shipilev approved these changes

2023-09-14 14:47 UTC, albertnetymk commented
Thanks for the review.

/integrate

2023-09-14 14:49 UTC, closed without merging