JDK-8315951: Open source several Swing HTMLEditorKit related tests
openjdk/jdk pull request #15751
Opened 2023-09-14 18:45 UTC by honkar-jdk

Following tests are open sourced as part of this PR.

1. java/awt/event/PaintEvent/RepaintTest/RepaintTest.java
2. javax/swing/text/html/HTMLEditorKit/4214848/bug4214848.java
3. javax/swing/text/html/HTMLEditorKit/4230197/bug4230197.java
4. javax/swing/text/html/HTMLEditorKit/4238223/bug4238223.java

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8315951](https://bugs.openjdk.org/browse/JDK-8315951): Open source several Swing HTMLEditorKit related tests (**Bug** - P4)

### Reviewers
 * [Damon Nguyen](https://openjdk.org/census#dnguyen) (@DamonGuy - Committer) ⚠️ Review applies to [a8984390](https://git.openjdk.org/jdk/pull/15751/files/a898439070dcad61beef31fae50be3c25b12a255)
 * [Alexey Ivanov](https://openjdk.org/census#aivanov) (@aivanov-jdk - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15751/head:pull/15751` \
`$ git checkout pull/15751`

Update a local copy of the PR: \
`$ git checkout pull/15751` \
`$ git pull https://git.openjdk.org/jdk.git pull/15751/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15751`

View PR using the GUI difftool: \
`$ git pr show -t 15751`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15751.diff">https://git.openjdk.org/jdk/pull/15751.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15751#issuecomment-1719975580)

2023-09-15 22:12 UTC, DamonGuy approved these changes
Looks fine to me.

2023-09-18 11:07 UTC, aivanov-jdk requested changes

2023-09-18 11:07 UTC, aivanov-jdk commented on test/jdk/javax/swing/text/html/HTMLEditorKit/bug4230197.java
> +                || (!au.contains("<i>0</i>"))) {
I'd put each condition on its own line for easier parsing:
```suggestion
        if ((!au.contains("<sub>0</sub>"))
                || (!au.contains("<sup>0</sup>"))
                || (!au.contains("<code>0</code>"))
                || (!au.contains("<b>0</b>"))
                || (!au.contains("<i>0</i>"))) {
```

2023-09-18 11:07 UTC, aivanov-jdk commented on test/jdk/javax/swing/text/html/HTMLEditorKit/bug4238223.java
> +                    pos != commentIndex) {
```suggestion
            if (!(new String(data)).equals(commentData)
                    || pos != commentIndex) {
```
There are no spaces after the `!` operator in the following `if` statements. I would also suggest wrapping before the operator.

2023-09-18 11:07 UTC, aivanov-jdk commented on test/jdk/javax/swing/text/html/HTMLEditorKit/bug4238223.java
> +                    pos != endTagPositions[endTagIndex]) {
```suggestion
            if (!tag.equals(endTags[endTagIndex])
                    || pos != endTagPositions[endTagIndex]) {
```
No space after `!`, wrap before the operator.

2023-09-18 21:47 UTC, honkar-jdk commented on test/jdk/java/awt/event/PaintEvent/RepaintTest.java
> +            }
Updated

2023-09-18 21:47 UTC, honkar-jdk commented on test/jdk/java/awt/event/PaintEvent/RepaintTest.java
> +            robot.delay(300);
Delay removed.

2023-09-18 21:47 UTC, honkar-jdk commented on test/jdk/java/awt/event/PaintEvent/RepaintTest.java
> +// that increments everytime paint is invoked on it.
Removed comment

2023-09-18 21:50 UTC, honkar-jdk commented
Review changes updated. PR ready for re-review.

2023-09-19 17:34 UTC, aivanov-jdk approved these changes

2023-09-19 18:42 UTC, honkar-jdk commented
/integrate

2023-09-19 18:43 UTC, closed without merging