8316053: Open some swing tests 3
openjdk/jdk pull request #15851
Opened 2023-09-20 22:30 UTC by alisenchung

Moving tests from closed to open
8 javax/swing/SwingGraphics/VolatileBackBuffer/MultimonVImage.java
9 javax/swing/SwingUtilities/4859570/bug4859570.java
10 javax/swing/SwingUtilities/4936652/bug4936652.java
11 javax/swing/ToolTipManager/4768127/bug4768127.java

2023-09-21 16:49 UTC, DamonGuy requested changes

2023-09-21 16:49 UTC, DamonGuy commented on test/jdk/javax/swing/JDialog/bug4859570.java
> +    public static void main(String args[]) throws Exception {
```suggestion
    public static void main(String[] args) throws Exception {
```
Probably better to standardize this throughout all the tests here

2023-09-21 16:49 UTC, DamonGuy commented on test/jdk/javax/swing/JDialog/bug4859570.java
> +        r.waitForIdle();
waitForIdle before delays typically

2023-09-21 16:49 UTC, DamonGuy commented on test/jdk/javax/swing/JDialog/bug4859570.java
> +            }
Since you already create a Robot, can't you avoid using notifyAll, synchronized, and dialogIsClosed altogether and use delays/waitForIdle?

2023-09-21 16:49 UTC, DamonGuy commented on test/jdk/javax/swing/JDialog/bug4859570.java
> +/* @test
```suggestion
/*
 * @test
```

Minor nit pick here. Standardize throughout the tests as well

2023-09-21 16:49 UTC, DamonGuy commented on test/jdk/javax/swing/JDialog/bug4936652.java
> +/* @test
```suggestion
/*
 * @test
```

2023-09-21 16:49 UTC, DamonGuy commented on test/jdk/javax/swing/JDialog/bug4936652.java
> +    public static void main(String[] argv) throws Exception {
```suggestion
    public static void main(String[] args) throws Exception {
```

2023-09-21 16:49 UTC, DamonGuy commented on test/jdk/javax/swing/JLabel/bug4768127.java
> +    static volatile Robot robot;
I think robot can be local instead of static

2023-09-21 16:49 UTC, DamonGuy commented on test/jdk/javax/swing/JLabel/bug4768127.java
> +        robot.mouseRelease(InputEvent.BUTTON1_MASK);
Is this deprecated? I think BUTTON1_DOWN_MASK is the replacement

2023-09-21 16:49 UTC, DamonGuy commented on test/jdk/javax/swing/JLabel/bug4768127.java
> +        final Point p = label[i].getLocationOnScreen();
I think this line should be on EDT

2023-09-21 16:49 UTC, DamonGuy commented on test/jdk/javax/swing/JLabel/bug4768127.java
> +    public static void main(String args[]) throws Exception {
```suggestion
    public static void main(String[] args) throws Exception {
```

2023-09-21 16:49 UTC, DamonGuy commented on test/jdk/javax/swing/JLabel/bug4768127.java
> +/* @test
```suggestion
/* 
 * @test
```

2023-09-21 19:55 UTC, DamonGuy commented on test/jdk/javax/swing/JDialog/bug4859570.java
> +        }
Do you know if dialogIsClosed is needed? It seems to only add a delay. I suppose this makes more sense when there was `synchronized`, but not sure if it's still needed.

2023-09-21 19:55 UTC, DamonGuy commented on test/jdk/javax/swing/JDialog/bug4859570.java
> +    static Robot r;
Pretty sure robot can be local.

2023-09-21 21:58 UTC, DamonGuy approved these changes

2023-09-21 22:46 UTC, prrace approved these changes

2023-09-23 05:41 UTC, alisenchung commented
/integrate

2023-09-23 05:42 UTC, closed without merging