8315031
openjdk/jdk pull request #15901
Opened 2023-09-25 12:26 UTC by albertnetymk

Simple fix around unaligned PLAB size. Due to a circular dependency between the heap and PLAB initialization in G1, `_default_plab_size` picks up unaligned PLAB sizes, hence the additional alignment there.

2023-09-28 08:04 UTC, tschatzl requested changes

2023-09-28 11:54 UTC, tschatzl approved these changes
lgtm.

2023-09-28 13:35 UTC, walulyai approved these changes

2023-09-28 17:12 UTC, albertnetymk commented
Thanks for the review.

/integrate

2023-09-28 17:13 UTC, closed without merging

2024-06-03 02:32 UTC, mmyxym commented
/backport jdk22u

2024-06-03 02:33 UTC, mmyxym commented
/backport jdk21u-dev