8280120: [IR Framework] Add attribute to @IR to enable/disable IR matching based on the architecture
openjdk/jdk pull request #15938
Opened 2023-09-27 06:12 UTC by danielogh

This PR adds support for platform features in IR Framework preconditions. This allows us to write platform-specific IR checks in the same .java test file.

Platforms considered in this PR are: operating system, arch, and data model (32 or 64-bit VM). Supported field values correspond to vm.simpleArch, os.family, and vm.bits, as used in jtreg `@requires` fields. We use the Platform library methods to accomplish this. Otherwise, the new preconditions work similar to the corresponding CPUFeature preconditions.

Testing: T1-T3, GHA.

Additional testing: Tweaked SW test succeeds with removed `@requires` field and added IR platform precondition, but fails with just removed `@requires` field on 32-bit Linux. Performed a few spot tests with incorrectly formatted preconditions, and with valid platform checks but invalid counts.

2023-09-27 07:09 UTC, chhagedorn requested changes
That's a useful addition, thanks for working on this!

I have a couple of comments but otherwise, it looks good!

2023-09-27 07:09 UTC, chhagedorn commented on test/hotspot/jtreg/compiler/lib/ir_framework/IR.java
> +    String[] applyIfPlatformFeature() default {};
Maybe we can just use the name `applyIfPlatform`?

2023-09-27 07:09 UTC, chhagedorn commented on test/hotspot/jtreg/compiler/loopopts/superword/SumRed_Long.java
> - * @requires vm.bits == "64"
Maybe we should file a follow-up RFE to check all IR tests that have such a `@requires` limitation and see if we could just change some specific rules to use these new constraints in order to let the test pass for all platforms.

2023-09-27 07:09 UTC, chhagedorn commented on test/hotspot/jtreg/compiler/lib/ir_framework/README.md
> +#### Disable/Enable IR Rules based on available Platform Features
Should we just say "platform"?
```suggestion
#### Disable/Enable IR Rules based on Platform
```

2023-09-27 12:00 UTC, robcasloz reviewed
Looks good to me, modulo issues/comments raised by Christian and a few additional minor comments and suggestions.

It seems the IR test framework's annotation-based precondition language is slowly converging towards jtreg's @requires expressions. In the long run, it would be interesting to investigate whether we could simply reuse the jtreg @requires expression support (as suggested in [JDK-8294279](https://bugs.openjdk.org/browse/JDK-8294279)).

2023-09-29 07:43 UTC, danielogh commented
Thanks @chhagedorn for the suggestion. The preconditions read better after renaming. Going over IR tests and removing @requires fields sounds good in order to run tests on all platforms and to consolidate tests.

Appreciate the review @robcasloz. I rewrote parts of the documentation and added more tests. Since we are implementing functionality that is similar to jtreg `@requires` reusing that implementation could be favorable.

This PR might be ready for another round of reviews.

2023-09-29 11:50 UTC, robcasloz commented
> Appreciate the review @robcasloz. I rewrote parts of the documentation and added more tests.

The new version looks good. Maybe I missed something, but does any of the newly added tests address my suggestion (https://github.com/openjdk/jdk/pull/15938/files#r1338489724) to check that platform preconditions take precedence over VM flags, i.e. VM flags are not even validated if platform preconditions do not hold?

2023-09-29 12:00 UTC, danielogh commented
> > Appreciate the review @robcasloz. I rewrote parts of the documentation and added more tests.
> 
> The new version looks good. Maybe I missed something, but does any of the newly added tests address my suggestion (https://github.com/openjdk/jdk/pull/15938/files#r1338489724) to check that platform preconditions take precedence over VM flags, i.e. VM flags are not even validated if platform preconditions do not hold?

Thanks for the review. The intention is that the last four tests in `TestPreconditions.java` test precedence through platform-specific VM flags. As an example `testApplyPlatformSVE` will fail with `Could not find VM flag "UseSVE"` if we remove the `applyIfPlatform` precondition on x64.

2023-09-29 12:11 UTC, robcasloz commented
> > > Appreciate the review @robcasloz. I rewrote parts of the documentation and added more tests.
> > 
> > 
> > The new version looks good. Maybe I missed something, but does any of the newly added tests address my suggestion (https://github.com/openjdk/jdk/pull/15938/files#r1338489724) to check that platform preconditions take precedence over VM flags, i.e. VM flags are not even validated if platform preconditions do not hold?
> 
> Thanks for the review. The intention is that the last four tests in `TestPreconditions.java` test precedence through platform-specific VM flags. As an example `testApplyPlatformSVE` will fail with `Could not find VM flag "UseSVE"` if we remove the `applyIfPlatform` precondition on x64.

Right, thanks for the clarification!

2023-09-29 12:11 UTC, robcasloz approved these changes

2023-10-02 08:59 UTC, eme64 commented on test/hotspot/jtreg/testlibrary_tests/ir_framework/tests/TestPreconditions.java
>  }
Good idea! We got something similar wrong recently, so this is a must.

2023-10-02 09:02 UTC, eme64 commented
Thanks for doing this, @danielogh !
I thinks this patch is good. But please add the rules requested here https://github.com/openjdk/jdk/pull/15938#discussion_r1338489724.
And make sure to file the follow-up RFE and link it to this issue here https://github.com/openjdk/jdk/pull/15938#discussion_r1338137686.

2023-10-02 09:20 UTC, eme64 commented on test/hotspot/jtreg/testlibrary_tests/ir_framework/tests/TestPreconditions.java
>  }
Update: Not necessary

2023-10-02 09:27 UTC, eme64 approved these changes
Thanks for the work, looks good to me :)

2023-10-04 11:41 UTC, TobiHartmann approved these changes
Nice enhancement! Looks good to me.

2023-10-04 11:48 UTC, danielogh commented
Thanks @eme64 and @TobiHartmann for reviews

2023-10-04 11:49 UTC, danielogh commented
/integrate

2023-10-04 11:56 UTC, eme64 commented
Thanks for all the work on this, we wanted this for a while!
/sponsor

2023-10-04 11:58 UTC, closed without merging