8316947: Write a test to check textArea triggers MouseEntered/MouseExited events properly
openjdk/jdk pull request #15961
Opened 2023-09-28 11:18 UTC by ravigupta30

Write a test to check textArea triggers MouseEntered/MouseExited events properly

MouseEntered should be triggered only when the mouse enters the component and MouseExited should be triggered when the mouse goes out of the component.

In TextArea, when we moved the mouse inside the component MouseMoved events are triggered properly. But when we slowly took the mouse outside the component that is towards the scrollbars, we could see a MouseEntered event being triggered followed by MouseExited.(before actually mouse enters the scrollbar)

Testing:
Tested using Mach5(20 times per platform) in macos,linux and windows and got all pass.

2023-10-03 10:48 UTC, ravigupta30 commented
Any volunteers for a review?

2023-10-04 06:22 UTC, TejeshR13 approved these changes
Looks good.

2023-10-04 17:23 UTC, honkar-jdk requested changes
Is there source code fix or PR related to this test. Since the PR description mentions "MouseEntered/Exited" events does not occur properly.

2023-10-04 17:23 UTC, honkar-jdk commented on test/jdk/java/awt/event/MouseEvent/MouseEnterExitTest.java
> +                .println("MouseEntered " + e.getSource().getClass().getName());
It is a bit odd to have a line break after sys.out. It looks better this way.

```
 System.out.println("MouseEntered "
                    + e.getSource().getClass().getName());
```

2023-10-04 17:23 UTC, honkar-jdk commented on test/jdk/java/awt/event/MouseEvent/MouseEnterExitTest.java
> +                .println("MouseExited " + e.getSource().getClass().getName());
Same here. Line break.

2023-10-04 17:23 UTC, honkar-jdk commented on test/jdk/java/awt/event/MouseEvent/MouseEnterExitTest.java
> +            frame = null;
After frame.dispose() assigning the var back to null is unnecessary.

2023-10-04 17:23 UTC, honkar-jdk commented on test/jdk/java/awt/event/MouseEvent/MouseEnterExitTest.java
> +        textArea = new TextArea("TextArea");
Rows and columns can be specified for the TextArea to reduce scan time.

```suggestion
        textArea = new TextArea("TextArea", 10, 10);
```

2023-10-04 17:23 UTC, honkar-jdk commented on test/jdk/java/awt/event/MouseEvent/MouseEnterExitTest.java
> +    private volatile static List list;
Since TextArea and List are accessed only within invokeAndWait they need not be volatile.

2023-10-06 17:02 UTC, honkar-jdk commented on test/jdk/java/awt/event/MouseEvent/MouseEnterExitTest.java
> +                .println("MouseEntered " + e.getSource().getClass().getName());
I would add the line break after "MouseEntered/Exited" as above, looks cleaner and preserves line lengths.

2023-10-06 17:06 UTC, honkar-jdk approved these changes
Updated changes look good.

2023-10-06 18:27 UTC, aivanov-jdk requested changes

2023-10-06 18:27 UTC, aivanov-jdk commented on test/jdk/java/awt/event/MouseEvent/MouseEnterExitTest.java
> +            robot.setAutoWaitForIdle(true);
```suggestion
            robot = new Robot();
            robot.setAutoDelay(100);
            robot.setAutoWaitForIdle(true);

            EventQueue.invokeAndWait(MouseEnterExitTest::initializeGUI);
            robot.waitForIdle();
```
Before continuing to get the coordinates of the frame, you want to ensure it's completely shown.

2023-10-06 18:27 UTC, aivanov-jdk commented on test/jdk/java/awt/event/MouseEvent/MouseEnterExitTest.java
> +    private static MouseListener mListener = new MouseAdapter() {
```suggestion
    private static final MouseListener mouseListener = new MouseAdapter() {
```
Why not make the field `mouseListener`?

2023-10-06 18:27 UTC, aivanov-jdk commented on test/jdk/java/awt/event/MouseEvent/MouseEnterExitTest.java
> +    private static Robot robot;
Robot can be a local variable in the `main` method.

2023-10-06 18:27 UTC, aivanov-jdk commented on test/jdk/java/awt/event/MouseEvent/MouseEnterExitTest.java
> +    private static List list;
Both `list` and `textArea` can be local variables in the `initializeGUI` method.

2023-10-06 18:27 UTC, aivanov-jdk commented on test/jdk/java/awt/event/MouseEvent/MouseEnterExitTest.java
> + * @summary On Solaris,TextArea triggers MouseEntered when the mouse is inside the component
```suggestion
 * @summary On Solaris, TextArea triggers MouseEntered when the mouse is inside the component
```

2023-10-06 18:44 UTC, aivanov-jdk commented
> Is there source code fix or PR associated with this test.

I couldn't see the answer to this question. I guess the fix was done long time ago in JDK-4454304. Now, the test gets open-sourced.

2023-10-06 19:08 UTC, honkar-jdk commented
> > Is there source code fix or PR associated with this test.
> 
> I couldn't see the answer to this question. I guess the fix was done long time ago in JDK-4454304. Now, the test gets open-sourced.

Correct, and saw @ravigupta30 comments in JBS after this post.

2023-10-09 15:11 UTC, aivanov-jdk requested changes

2023-10-09 15:11 UTC, aivanov-jdk commented on test/jdk/java/awt/event/MouseEvent/MouseEnterExitTest.java
> +    private volatile static Dimension compSize;
To my personal taste, I'd add blank line to visually separate groups of fields:
```suggestion
    private static Frame frame;

    private volatile static boolean entered = false;
    private volatile static boolean exited = false;
    private volatile static boolean passed = true;

    private volatile static Point compAt;
    private volatile static Dimension compSize;
```

2023-10-09 15:11 UTC, aivanov-jdk commented on test/jdk/java/awt/event/MouseEvent/MouseEnterExitTest.java
> +        public void mouseEntered(MouseEvent e) {
```suggestion
    private static final MouseListener mouseListener = new MouseAdapter() {
        @Override
        public void mouseEntered(MouseEvent e) {
```
Let's add `@Override` annotations, it's basically a new code, so it's better to add them.

2023-10-09 15:11 UTC, aivanov-jdk commented on test/jdk/java/awt/event/MouseEvent/MouseEnterExitTest.java
> +        public void mouseExited(MouseEvent e) {
```suggestion
        @Override
        public void mouseExited(MouseEvent e) {
```

2023-10-09 15:11 UTC, aivanov-jdk commented on test/jdk/java/awt/event/MouseEvent/MouseEnterExitTest.java
> +            EventQueue.invokeAndWait(() -> {
```suggestion
            robot.waitForIdle();

            EventQueue.invokeAndWait(() -> {
```

2023-10-09 15:11 UTC, aivanov-jdk commented on test/jdk/java/awt/event/MouseEvent/MouseEnterExitTest.java
> +            if (!passed || entered || !exited) {
```suggestion

            if (!passed || entered || !exited) {
```
A couple of blank lines in the `main` method.

2023-10-09 15:11 UTC, aivanov-jdk commented on test/jdk/java/awt/event/MouseEvent/MouseEnterExitTest.java
> +    public static void disposeFrame() {
```suggestion
    private static void disposeFrame() {
```
It should be private.

2023-10-10 11:36 UTC, aivanov-jdk approved these changes

2023-10-11 10:44 UTC, ravigupta30 commented
/integrate

2023-10-12 09:38 UTC, aivanov-jdk commented
/sponsor

2023-10-12 09:40 UTC, closed without merging