8317971: RISC-V: implement copySignF/D and signumF/D intrinsics
openjdk/jdk pull request #16186
Opened 2023-10-13 15:36 UTC by Ilyagavrilin

Hi all, please review this changes into risc-v floating point copysign and signum intrinsics.
CopySign - returns first argument with the sign of second. On risc-v we have `fsgnj.x` instruction, which can implement this intrinsic.
Signum - returns input value if it is +/- 0.0 or NaN, otherwise 1.0 with the sign of input value returned.  On risc-v we can use `fclass.x` to specify type of input value and return appropriate value.

Tests:
Performance tests on t-head board:
With intrinsics:
```
Benchmark                 (seed)   Mode  Cnt      Score      Error   Units
MathBench.copySignDouble       0  thrpt    8  34156.580 ±   76.272  ops/ms
MathBench.copySignFloat        0  thrpt    8  34181.731 ±   38.182  ops/ms
MathBench.signumDouble         0  thrpt    8  31977.258 ± 1122.327  ops/ms
MathBench.signumFloat          0  thrpt    8  31836.852 ±   56.013  ops/ms
```
Intrinsics turned off (`-XX:+UnlockDiagnosticVMOptions -XX:-UseCopySignIntrinsic -XX:-UseSignumIntrinsic`):
```
Benchmark                 (seed)   Mode  Cnt      Score      Error   Units
MathBench.copySignDouble       0  thrpt    8  31000.996 ±  943.094  ops/ms
MathBench.copySignFloat        0  thrpt    8  30678.016 ±   28.087  ops/ms
MathBench.signumDouble         0  thrpt    8  25435.010 ± 2047.085  ops/ms
MathBench.signumFloat          0  thrpt    8  25257.058 ±   79.175  ops/ms
```
Regression tests: tier1, hotspot:tier2 on risc-v board.

Also, changed name of one micro test: before we had: `sigNumDouble` and `signumFloat` tests, they does not matches to `signum` or `sigNum`. Now we have similar part: `signum`.
Performance tests has been changed a bit, to check intrinsics result better, diff to modify tests:
```
diff --git a/test/micro/org/openjdk/bench/java/lang/MathBench.java b/test/micro/org/openjdk/bench/java/lang/MathBench.java
index 6cd1353907e..0bee25366bf 100644
--- a/test/micro/org/openjdk/bench/java/lang/MathBench.java
+++ b/test/micro/org/openjdk/bench/java/lang/MathBench.java
@@ -143,12 +143,12 @@ public double  ceilDouble() {
 
     @Benchmark
     public double  copySignDouble() {
-        return  Math.copySign(double81, doubleNegative12);
+        return  Math.copySign(double81, doubleNegative12) + Math.copySign(double81, double2) + Math.copySign(double4Dot1, doubleNegative12);
     }
 
     @Benchmark
     public float  copySignFloat() {
-        return  Math.copySign(floatNegative99, float1);
+        return  Math.copySign(floatNegative99, float1) + Math.copySign(eFloat, float1) + Math.copySign(eFloat, floatNegative99);
     }
 
     @Benchmark
@@ -472,12 +472,12 @@ public float  scalbFloatInt() {
 
     @Benchmark
     public double  sigNumDouble() {
-        return  Math.signum(double4Dot1);
+        return  Math.signum(double4Dot1) + Math.signum(doubleNegative12) + Math.signum(double81);
     }
 
     @Benchmark
     public double  signumFloat() {
-        return  Math.signum(floatNegative99);
+        return  Math.signum(floatNegative99) + Math.signum(float2) + Math.signum(float7);
     }
 
     @Benchmark
```

2023-10-13 16:08 UTC, Ilyagavrilin commented
/cc hotspot-compiler

2023-10-16 07:34 UTC, RealFYang reviewed
Some comments after a brief look.

2023-10-16 07:34 UTC, RealFYang commented on src/hotspot/cpu/riscv/c2_MacroAssembler_riscv.cpp
> +// bool single_precision - specififes single or double precision operations will be used.
Suggestion: s/bool single_precision - specififes/bool is_double - specifies/

2023-10-16 07:34 UTC, RealFYang commented on src/hotspot/cpu/riscv/c2_MacroAssembler_riscv.cpp
> +// tmp1 - used to store result of fclass operation,
Seems to me that scratch register `t0` could be used in this function in order to save use of `tmp1`.

2023-10-16 07:34 UTC, RealFYang commented on src/hotspot/cpu/riscv/c2_MacroAssembler_riscv.cpp
> +  assert_different_registers(dst, src, one);
This constraint could be relaxed if we use scratch register `t0` here instead of `tmp`.

2023-10-16 07:34 UTC, RealFYang commented on src/hotspot/cpu/riscv/riscv.ad
> +instruct copySignD_reg(fRegD dst, fRegD src1, fRegD src2, immD0 zero) %{
A more simpler `immD zero` will do here which is similar with the x86 counterpart.

2023-10-16 07:34 UTC, RealFYang commented on src/hotspot/cpu/riscv/riscv.ad
> +instruct signumD_reg(fRegD dst, fRegD src, fRegD zero, fRegD one, iRegINoSp tmp1) %{
Use `immD zero` instread, which will help avoid reserving one FP register here.

2023-10-16 07:34 UTC, RealFYang commented on src/hotspot/cpu/riscv/riscv.ad
> +instruct signumF_reg(fRegF dst, fRegF src, fRegF zero, fRegF one, iRegINoSp tmp1) %{
Use `immF zero` instread, which will help avoid reserving one FP register here.

2023-10-16 07:34 UTC, RealFYang commented on src/hotspot/cpu/riscv/riscv.ad
> +  effect(TEMP_DEF dst, USE src1, USE src2);
Unnecessary effect.

2023-10-16 07:34 UTC, RealFYang commented on src/hotspot/cpu/riscv/riscv.ad
> +  effect(TEMP_DEF dst, USE src1, USE src2);
Unnecessary effect.

2023-10-16 07:34 UTC, RealFYang commented on src/hotspot/cpu/riscv/riscv.ad
> +  effect(TEMP_DEF dst, USE src, USE one, TEMP tmp1);
Unnecessary effect if changed to use `t0` instead of `tmp1` in `signum_fp`.

2023-10-16 07:34 UTC, RealFYang commented on src/hotspot/cpu/riscv/riscv.ad
> +  effect(TEMP_DEF dst, USE src, USE one, TEMP tmp1);
Unnecessary effect if changed to use `t0` instead of `tmp1` in `signum_fp`.

2023-10-17 06:49 UTC, robehn commented
Hey, I went ahead and create https://bugs.openjdk.org/browse/JDK-8318216.
So we can track these and not do double work.

2023-10-17 09:18 UTC, RealFYang requested changes

2023-10-17 09:18 UTC, RealFYang commented on src/hotspot/cpu/riscv/riscv.ad
> +  effect(TEMP_DEF dst, USE src, USE one);
Any reason to keep this effect?

2023-10-17 09:52 UTC, Ilyagavrilin commented on src/hotspot/cpu/riscv/c2_MacroAssembler_riscv.cpp
> +            : fsgnj_s(dst, one, src);
According to IEEE754, we can get positive or negative zero in the `src` register (also positive zero can be named as zero) , and these cases included to mask for the tmp1 (L1671-1676) and `src` value returned.

2023-10-18 08:10 UTC, RealFYang commented on src/hotspot/cpu/riscv/c2_MacroAssembler_riscv.cpp
> +            : fsgnj_s(dst, one, src);
I see. Thanks for the answer. I can approve this once my other comments are resolved.

2023-10-19 00:37 UTC, RealFYang approved these changes
Updated change looks good. Thanks.
JMH data on hifive unmatched for reference:
```
Before:
Benchmark                 (seed)   Mode  Cnt      Score       Error   Units
MathBench.copySignDouble       0  thrpt    8  79728.042 ?  8211.438  ops/ms
MathBench.copySignFloat        0  thrpt    8  79516.930 ? 13163.477  ops/ms
MathBench.sigNumDouble         0  thrpt    8  58204.403 ?  6795.238  ops/ms
MathBench.signumFloat          0  thrpt    8  57882.056 ?  3635.354  ops/ms

After:
Benchmark                 (seed)   Mode  Cnt       Score       Error   Units
MathBench.copySignDouble       0  thrpt    8  104301.832 ?  7170.917  ops/ms
MathBench.copySignFloat        0  thrpt    8  103008.851 ? 11722.187  ops/ms
MathBench.signumDouble         0  thrpt    8   64465.030 ?  6849.148  ops/ms
MathBench.signumFloat          0  thrpt    8   63987.290 ?  4298.311  ops/m
```

2023-10-19 12:15 UTC, Ilyagavrilin commented
Change branch inside `signum`, now `dst` always moves to `src`, so we can remove `j(done); `
Performance results:
Without intrinsic:
```
Benchmark               (seed)   Mode  Cnt      Score    Error   Units
MathBench.signumDouble       0  thrpt    8  35666.674 ±  6.317  ops/ms
MathBench.signumFloat        0  thrpt    8  34040.220 ± 13.783  ops/ms
```
With old version:
```
Benchmark               (seed)   Mode  Cnt      Score    Error   Units
MathBench.signumDouble       0  thrpt    8  41601.513 ± 16.570  ops/ms
MathBench.signumFloat        0  thrpt    8  39414.511 ± 28.290  ops/ms
```
With new version:
```
Benchmark               (seed)   Mode  Cnt      Score    Error   Units
MathBench.signumDouble       0  thrpt    8  44060.456 ± 12.483  ops/ms
MathBench.signumFloat        0  thrpt    8  40481.776 ± 28.512  ops/ms
```

2023-10-19 12:17 UTC, VladimirKempik approved these changes
Looks good, last change is pretty similar to what was done here https://github.com/openjdk/jdk/pull/13800/commits/00e16a6726c258ad1409c7c671b9742bf8448a55

2023-10-19 12:22 UTC, RealFYang approved these changes
Still good. You might want correct the remaining typo.

2023-10-19 12:22 UTC, RealFYang commented on src/hotspot/cpu/riscv/c2_MacroAssembler_riscv.cpp
> +// bool is_double - specififes single or double precision operations will be used.
Suggestion: s/specififes/specifies/

2023-10-19 12:29 UTC, Ilyagavrilin commented
> Still good. You might want to correct the remaining typo.

Thanks for review!

2023-10-20 14:15 UTC, Ilyagavrilin commented
/integrate

2023-10-20 14:31 UTC, closed without merging