String::newStringNoRepl and String::getBytesNoRepl does not throw CharacterCodingException
openjdk/jdk pull request #16209
Opened 2023-10-16 22:27 UTC by wenshao

When calling String::newStringNoRepl and String::getBytesNoRepl, we need to use try...catch to handle CharacterCodingException and throw IllegalArgumentException instead of CharacterCodingException to make the calling code cleaner.

2023-10-17 03:09 UTC, liach requested changes
The thrown CCE was intended for `Files.readString` and `Files.writeString`, and is in reality, only used by those 2 sites. However, you missed updating those sites, so they now throw IAE instead of CCE, which should be fixed.

2023-10-17 09:31 UTC, cl4es commented
I agree with @liach that `Files.readString / writeString` should continue to throw `CCE`, not `IAE`.

2023-10-17 10:13 UTC, AlanBateman commented
> The thrown CCE was intended for `Files.readString` and `Files.writeString`, and is in reality, only used by those 2 sites. However, you missed updating those sites, so they now throw IAE instead of CCE, which should be fixed.

Right, these APIs are specified to throw an IOException "If an I/O error occurs reading from the file or a malformed or unmappable byte sequence is read". Changing this to throw an unexpected IAE would be a breaking change. So good to spot this. Need to make sure that tier2 tests are run with this change.

2023-10-17 10:35 UTC, AlanBateman commented
/reviewers 2 reviewer

2023-10-17 10:42 UTC, cl4es commented on test/jdk/java/lang/String/NoReplTest.java
> -        } catch (CharacterCodingException cce) {
Shouldn't these test changes be completely reverted now?

2023-10-17 11:13 UTC, AlanBateman commented on src/java.base/share/classes/java/nio/file/Files.java
> +            throw e;
This is wrong, if IAE is thrown for any other reason than CharacterCodingException then it means the JDK is broken.

2023-10-17 11:16 UTC, AlanBateman commented
I've set this PR to require two Reviewers as there is obvious breakage here and no evidence that the tier2 tests have been run.

2023-10-17 14:09 UTC, rgiulietti commented
@wenshao The proposal changes the exception types for seemingly no reason.
What concrete problem does this enhancement PR address?

2023-10-17 14:30 UTC, wenshao commented
> @wenshao The proposal changes the exception types for seemingly no reason. What concrete problem does this enhancement PR address?

@lianch 's suggestion in PR #14812 : 
"Make the NoRepl methods throw IllegalArgument (like NoRepl1 do) by default; move the exception handling logic into Files implementation, the only place where it's actually needed. "

We used noRepl in UUID/HexFormat to handle CCE. We felt that the code was not clean enough, so we submitted this PR.

After the discussion above, I found that things are not that simple. Should I continue this PR?

2023-10-17 18:07 UTC, RogerRiggs requested changes
Hacking around the exception types isn't a good fix.
If the exception is thrown, it is because of a charset conversion error.
IllegalArgumentException is for cases where the arguments are incorrect.

2023-10-18 16:39 UTC, AlanBateman commented
> The new usages that are driving this change would be better served by a method dedicated to creating latin1 strings from a caller provided byte array. The JavaLangAccess shared secret interface is already overused, but it is cleaner, more maintainable, and fit for purpose to add a method than to contort the exception handling as proposed.

We have to be very careful with proposals like this as it means code outside of java.lang having access to the underlying bytes. I think other alternatives needs to be explored to avoid this and related concerns.

2023-10-18 17:36 UTC, RogerRiggs commented
> We have to be very careful with proposals like this as it means code outside of java.lang having access to the underlying bytes. I think other alternatives needs to be explored to avoid this and related concerns.

Yes, adding another method in the "NoRepl" family needs to be done with care and be narrowly focused.
JLA already exposes several methods that allow the contents of strings to be read from the underlying value or created from caller provided buffers. All to avoid extra allocations and copying.

2023-10-18 18:14 UTC, Glavo commented
Should we revisit https://github.com/openjdk/jdk/pull/14655?

2023-10-20 11:35 UTC, closed without merging