8318049: C2: assert(!failure) failed: Missed optimization opportunity in PhaseIterGVN
openjdk/jdk pull request #16214
Opened 2023-10-17 09:52 UTC by jaskarth

This patch fixes [JDK-8318049](https://bugs.openjdk.org/browse/JDK-8318049) by informing XorI and XorL nodes in addition to sub and phi nodes when Cast nodes are updated during IGVN. 

The bug manifests when loop optimizations change the IR:
![image](https://github.com/openjdk/jdk/assets/25208576/5274f2cc-a6fb-4ce6-89f4-4a638577901c)

To the following form:
![image](https://github.com/openjdk/jdk/assets/25208576/07bcbec3-f0bb-4d6a-b312-6a459e6b8c0c)

XorI nodes check for that form in their `Value` call, to do the `x ^ x => 0` transformation, checking through casts. As the cast node didn't inform the Xor when it changes, the transformation doesn't have a chance to run.
https://github.com/openjdk/jdk/blob/5bd10521eb5e51e76b20e955addd45f76abba6f7/src/hotspot/share/opto/addnode.cpp#L947-L950

I've attached a reduced version of the test found in the bug. Reviews would be appreciated!

2023-10-19 09:53 UTC, eme64 requested changes
Thanks for the work @jaskarth . A few small suggestions below.

2023-10-19 09:53 UTC, eme64 commented on src/hotspot/share/opto/phaseX.cpp
>        auto push_phi_or_sub_uses_to_worklist = [&](Node* n){
```suggestion
      auto push_the_uses_to_worklist = [&](Node* n){
```

2023-10-19 09:53 UTC, eme64 commented on src/hotspot/share/opto/phaseX.cpp
>        auto push_phi_or_sub_uses_to_worklist = [&](Node* n){
Change the name now. Maybe something more generic is good, since we do not know how many more of these examples we will eventually add to this.

2023-10-19 09:53 UTC, eme64 commented on test/hotspot/jtreg/compiler/c2/TestNotifyCastToXor.java
> + * @run main/othervm -Xbatch -Xcomp -XX:-TieredCompilation -XX:CompileOnly=compiler.c2.TestNotifyCastToXor::test -XX:VerifyIterativeGVN=10 compiler.c2.TestNotifyCastToXor
The line is a bit long, use multiple lines.
`-Xbatch` is redundant, `-Xcomp` already makes sure things run in the "blocking" mode.

2023-10-19 10:45 UTC, eme64 commented on test/hotspot/jtreg/compiler/c2/TestNotifyCastToXor.java
> + * @run main/othervm -Xbatch -Xcomp -XX:-TieredCompilation -XX:CompileOnly=compiler.c2.TestNotifyCastToXor::test -XX:VerifyIterativeGVN=10 compiler.c2.TestNotifyCastToXor
I'm also getting this when running the testing:
```
Error: VM option 'VerifyIterativeGVN' is develop and is available only in debug version of VM.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```
You need to prepend `-XX:+IgnoreUnrecognizedVMOptions`.

2023-10-19 12:02 UTC, jaskarth commented
Hi, thank you for the review and testing! I've pushed a commit that should resolve the issues.

2023-10-19 12:57 UTC, eme64 commented
@jaskarth thanks for the updates. Looks good now.
I also confirmed by hand that the regression test fails before, and succeeds after your patch.

Testing for v01 running...

2023-10-20 07:26 UTC, TobiHartmann approved these changes
Looks good to me.

2023-10-20 07:29 UTC, eme64 approved these changes
All tests passed, ship it :ship: 
And thanks again!

2023-10-20 10:32 UTC, jaskarth commented
Awesome, thank you for the reviews @eme64 @TobiHartmann!

/integrate

2023-10-20 10:43 UTC, eme64 commented
/sponsor

2023-10-20 10:45 UTC, closed without merging

2025-03-05 10:49 UTC, linade commented
/backport jdk21u-dev

2025-03-06 06:27 UTC, linade commented
/backport jdk21u-dev