Add Ideal transformation: (~a) | (~b) => ~(a & b)
openjdk/jdk pull request #16334
Opened 2023-10-24 05:02 UTC by CptGit

Hello,

(~a) | (~b) => ~(a & b) is a widely seen pattern, for example it is implemented for LLVM [here](https://github.com/llvm/llvm-project/blob/397f1ce9efb4eea1ee10fe4833f733b8c7abd878/llvm/lib/Transforms/InstCombine/InstCombineAndOrXor.cpp#L1617C28-L1617C28); however it is missing in current implementation of hotspot. This pull request adds this transformation and associated tests.

Thanks.

2023-11-21 15:43 UTC, CptGit commented
Hi, can I get a review?

2023-12-14 08:36 UTC, TobiHartmann commented
A JBS issue has been created for this: [JDK-8322077](https://bugs.openjdk.org/browse/JDK-8322077). Please update the PR accordingly.

2023-12-14 17:44 UTC, CptGit commented
> A JBS issue has been created for this: [JDK-8322077](https://bugs.openjdk.org/browse/JDK-8322077). Please update the PR accordingly.

Thanks. Updated.

2023-12-14 18:06 UTC, merykitty commented
LGTM, but may you consider having dedicated functions to check and create `Not` patterns? Thanks a lot.

2023-12-15 20:44 UTC, CptGit commented
> LGTM, but may you consider having dedicated functions to check and create `Not` patterns? Thanks a lot.

Thanks. I updated. Please let me know if there are more comments.

2024-01-05 11:00 UTC, TobiHartmann reviewed
Looks good to me. Please update the copyright dates.

I submitted testing and will report back once it passed.

2024-01-05 16:22 UTC, eme64 requested changes
Looks like a good idea. Left a few comments.

I would have merged this with https://github.com/openjdk/jdk/pull/16333, since it is essentially the symmetric case. But leave it separate now.

It would be nice to have some shared tests, where both optimizations need to be combined. Like:
`(~a | ~b) & (~c | ~d)` -> `~(a & b) & ~(c & d)` -> `~((a & b) | (c & d))`

2024-01-05 16:22 UTC, eme64 commented on src/hotspot/share/opto/addnode.cpp
> +                    T_INT);
I'd put the `AndI` node on a separate line. Call it `add_a_b` or similar.
Then you can transform on the next line.
And then on a third line the `make_not`.

2024-01-05 16:22 UTC, eme64 commented on src/hotspot/share/opto/addnode.cpp
> +}
If you are going to use this also for your changes in https://github.com/openjdk/jdk/pull/16333, then you probably want this to go into a shared file.

2024-01-06 00:44 UTC, CptGit commented
@eme64 @TobiHartmann Thanks for the comments. All addressed.

I rebased this PR onto #16333 so I was able to add these tests for using both optimizations. (the history was messed up).

2024-01-08 07:48 UTC, eme64 commented
Nice, looks much better, thanks for the updates!

2024-01-08 08:37 UTC, TobiHartmann approved these changes
Looks good to me otherwise.

/reviewers 2

2024-01-08 08:37 UTC, TobiHartmann commented on test/hotspot/jtreg/compiler/c2/irTests/DeMorganLawIntTests.java
> + * @summary Test that Ideal transformations on the De Morgan's Law performe
```suggestion
 * @summary Test that Ideal transformations on the De Morgan's Law perform
```

2024-01-09 08:48 UTC, TobiHartmann approved these changes

2024-01-09 14:02 UTC, eme64 approved these changes
LGTM, and thanks for the work!

Please only integrate this once your other change is integrated, and merged into this one. Then wait for GHA to complete, and run your own testing.

2024-01-10 07:30 UTC, TobiHartmann approved these changes

2024-01-10 07:47 UTC, eme64 commented
@CptGit can you merge from master again, please? It looks now like you are pushing both the changes here and the ones from your previous PR. Once you did that, I'd like to run some testing before we push this.

2024-01-10 20:29 UTC, CptGit commented
@eme64 Yes I merged. Looks clean now.

2024-01-11 08:23 UTC, eme64 commented
Testing running for commit 34...

2024-01-12 14:42 UTC, TobiHartmann commented
All tests passed, this is good to go.

2024-01-12 16:40 UTC, CptGit commented
/integrate

2024-01-12 16:44 UTC, CptGit commented
@eme64 @TobiHartmann Thanks for testing! Can you sponsor it when you get a chance thank you!

2024-01-15 06:46 UTC, TobiHartmann commented
/sponsor

2024-01-15 06:48 UTC, closed without merging