8315890: Attempts to load from nullptr in instanceKlass.cpp and unsafe.cpp
openjdk/jdk pull request #16405
Opened 2023-10-27 15:40 UTC by matias9927

Calls in instanceKlass.cpp and unsafe.cpp try to call an atomic load on method calls that could return nullptr. This patch ensures that nullptr is not passed into the load.

2023-10-27 18:15 UTC, coleenp approved these changes
Looks good.

2023-10-28 06:22 UTC, calvinccheung approved these changes
LGTM

2023-10-30 07:40 UTC, dholmes-ora requested changes

2023-10-30 07:40 UTC, dholmes-ora commented on src/hotspot/share/oops/instanceKlass.cpp
> +      InstanceKlass* impl = (iklass != nullptr) ? Atomic::load_acquire(iklass) : nullptr;
This looks very klunky as we do a raw read, check it for null then re-read with acquire semantics. Cleaner IMO to do a raw read followed by a raw `OrderAccess::acquire()` and no need for a null check.

2023-10-30 07:40 UTC, dholmes-ora commented on src/hotspot/share/prims/unsafe.cpp
> +    assert(addr() != nullptr, "Attempting to load from null pointer");
I don't see how `addr()` can be null unless `_obj` was null - which would be a usage error. So asserting `_obj != nullptr` in the constructor would seem better to me. I mean no point checking `addr()` here but not in other functions where we dereference it!

2023-10-30 20:26 UTC, coleenp approved these changes
Yes, this looks better.  This was the source of the nullptr.

2023-10-30 22:09 UTC, calvinccheung approved these changes
Updated changes look good.

2023-10-30 22:46 UTC, dholmes-ora reviewed
Not sure why it needed to be lifted out of Unsafe. The issue description should be updated now.

2023-10-31 14:59 UTC, matias9927 commented
> Not sure why it needed to be lifted out of Unsafe. The issue description should be updated now.

Sorry, I meant to explain this change in response to your comments. I'll explain here:

The call stack that results in the issue shown in `get_volatile()` starts near where the new assert is placed. When discussing with @coleenp, we decided that placing the assert at the source of the nullptr would be a better indicate the problem should it arise in the code. The description has been updated with more detail.

2023-11-01 02:01 UTC, dholmes-ora approved these changes
Okay. Thanks

2023-11-02 14:28 UTC, matias9927 commented
Thanks for the reviews @coleenp , @calvinccheung , and @dholmes-ora!
/integrate

2023-11-02 14:30 UTC, closed without merging