8313710: jcmd: typo in the documentation of JFR.start and JFR.dump
openjdk/jdk pull request #16413
Opened 2023-10-30 08:46 UTC by kurashige23

Hi,

I fixed the typos for JFR.start and JFR.dump.
Acconding to issue's description, there is some typo in JFR.stop documentation, but I couldn't find that. I confirmed that there is no such typo in this repository. So I thought there was no need to fix JFR.stop documentation.

I confirmed that the fixes are reflected and that all of the jdk_jfr tests pass.

Could someone please review it?

2023-10-30 16:09 UTC, egahlin commented
Looks like the added character and shift to the right will make the description exceed 80 characters in some lines, for example "included" for the begin option.

2023-10-30 22:39 UTC, dholmes-ora requested changes

2023-10-30 22:39 UTC, dholmes-ora commented on src/jdk.jcmd/share/man/jcmd.1
This file is generated from markdown sources that Oracle has to maintain. Please work with an Oracle engineer to get the changes applied to that source and then regenerate the `jcmd.1` nroff file. You can split this into a separate sub-task if needed.

2023-11-28 07:37 UTC, kurashige23 commented
@egahlin 
> Looks like the added character and shift to the right will make the description exceed 80 characters in some lines, for example "included" for the begin option.

I'm sorry, I don't know from which letter to which letter is more than 80 characters, for example in line of begin option. Can you tell me that?
Also, I didn't know the rule that the number of characters per line should not exceed 80. If possible, could you please tell me where such a rule is stated?

2023-11-28 07:38 UTC, kurashige23 commented on src/jdk.jcmd/share/man/jcmd.1
Thank you for telling me about how to jcmd.1 nroff file is managed.
I will split this change into separate subtasks. Then if one of the Oracle engineers finds that subtask, will he/she work on it like any other bug?

2023-11-28 07:44 UTC, dholmes-ora commented on src/jdk.jcmd/share/man/jcmd.1
Yes it will be assigned and addressed. Thanks

2023-11-30 11:37 UTC, egahlin commented
> @egahlin
> 
> > Looks like the added character and shift to the right will make the description exceed 80 characters in some lines, for example "included" for the begin option.
> 
> I'm sorry, I don't know from which letter to which letter is more than 80 characters, for example in line of begin option. Can you tell me that? Also, I didn't know the rule that the number of characters per line should not exceed 80. If possible, could you please tell me where such a rule is stated?

You could look at line 319 in DCmdStart.java and 198 in DcmdDump.java. Make sure characters don't exceed. "...1234567890"

2023-12-26 14:09 UTC, kurashige23 commented
> > @egahlin
> > > Looks like the added character and shift to the right will make the description exceed 80 characters in some lines, for example "included" for the begin option.
> > 
> > 
> > I'm sorry, I don't know from which letter to which letter is more than 80 characters, for example in line of begin option. Can you tell me that? Also, I didn't know the rule that the number of characters per line should not exceed 80. If possible, could you please tell me where such a rule is stated?
> 
> You could look at line 319 in DCmdStart.java and 198 in DcmdDump.java. Make sure characters don't exceed. "...1234567890"

Thanks, I understand that characters should not exceed "... 1234567890" (88 characters) .  
I fixed line 204 in DcmdDump.java.  
In addition, the starting position of "...1234567890" in DcmdStart.java does not match the beginning of "Syntax :..", and it is hard to see visually whether characters exceed "...1234567890". So I fixed it.

2023-12-26 14:11 UTC, kurashige23 commented on src/jdk.jcmd/share/man/jcmd.1
Sorry for the late response.

I will ask my colleague to make it, so please wait a moment.

2024-01-18 08:26 UTC, kurashige23 commented on src/jdk.jcmd/share/man/jcmd.1
@dholmes-ora 
Sorry for the late response again.  
I issued sub-task.  
https://bugs.openjdk.org/browse/JDK-8324089

2024-01-31 06:41 UTC, kurashige23 commented
@dholmes-ora @egahlin 

I'm sorry that my slow response has prolonged this issue. I created a subtask and modified the source. If possible, please review them.

2024-02-01 05:07 UTC, dholmes-ora commented
Thanks @kurashige23 , the manpage subtask will be handled by someone from Oracle. I'll leave it to JFR folk to do the review here.

2024-02-07 05:56 UTC, kurashige23 commented
Thanks @dholmes-ora , I understood that the subtask will be handled by someone from Oracle.

> I'll leave it to JFR folk to do the review here.

Does it mean that this pull request will not be merged until the subtask is resolved?

2024-02-27 02:06 UTC, kurashige23 commented
Could someone please review this PR?  
(Or will the review be done after https://bugs.openjdk.org/browse/JDK-8324089 is resolved?)

2024-02-27 05:37 UTC, dholmes-ora approved these changes
These changes seem fine to me.

Hopefully @egahlin can also approve.

2024-02-27 05:38 UTC, dholmes-ora commented
BTW please merge your branch with master so that it is up to date. Thanks

2024-02-27 08:07 UTC, kurashige23 commented
I merged my branch with master. Thanks.

2024-02-27 09:45 UTC, egahlin approved these changes
Looks good. Thanks for fixing this. I can sponsor the change.

2024-02-27 10:33 UTC, kurashige23 commented
Thanks for review.

/integrate

2024-02-27 10:39 UTC, egahlin commented
/sponsor

2024-02-27 10:39 UTC, closed without merging