JDK-8319195: Move tier 1 vector API regression tests to tier 2
openjdk/jdk pull request #16437
Opened 2023-10-31 20:14 UTC by jddarcy

Due to their longer-than-typical running time and because the vector API is not (yet) in the base module, move the vector API tests in tier 1 to tier 2.

2023-10-31 20:16 UTC, jddarcy commented
> Due to their longer-than-typical running time and because the vector API is not (yet) in the base module, move the vector API tests in tier 1 to tier 2.

As a check on the semantics of the change, `jtreg -l ...` output for tier 1 and tier 2 before and after the patch:

```
$ diff tier1.txt tier1-patched.txt 
108,133d107
< jdk/incubator/vector/AddTest.java
< jdk/incubator/vector/ByteMaxVectorLoadStoreTests.java
< jdk/incubator/vector/ByteMaxVectorTests.java
< jdk/incubator/vector/CovarOverrideTest.java
< jdk/incubator/vector/DoubleMaxVectorLoadStoreTests.java
< jdk/incubator/vector/DoubleMaxVectorTests.java
< jdk/incubator/vector/FloatMaxVectorLoadStoreTests.java
< jdk/incubator/vector/FloatMaxVectorTests.java
< jdk/incubator/vector/ImageTest.java
< jdk/incubator/vector/IntMaxVectorLoadStoreTests.java
< jdk/incubator/vector/IntMaxVectorTests.java
< jdk/incubator/vector/LoadJsvmlTest.java
< jdk/incubator/vector/LongMaxVectorLoadStoreTests.java
< jdk/incubator/vector/LongMaxVectorTests.java
< jdk/incubator/vector/MethodOverideTest.java
< jdk/incubator/vector/MismatchTest.java
< jdk/incubator/vector/PreferredSpeciesTest.java#id0
< jdk/incubator/vector/PreferredSpeciesTest.java#id1
< jdk/incubator/vector/ShortMaxVectorLoadStoreTests.java
< jdk/incubator/vector/ShortMaxVectorTests.java
< jdk/incubator/vector/VectorHash.java
< jdk/incubator/vector/VectorMaxConversionTests.java#id0
< jdk/incubator/vector/VectorMaxConversionTests.java#ZGenerational
< jdk/incubator/vector/VectorMaxConversionTests.java#ZSinglegen
< jdk/incubator/vector/VectorReshapeTests.java
< jdk/incubator/vector/VectorRuns.java
2410c2384
< Tests found: 2,408
---
> Tests found: 2,382

$ diff tier1.txt tier1-patched.txt 
108,133d107
< jdk/incubator/vector/AddTest.java
< jdk/incubator/vector/ByteMaxVectorLoadStoreTests.java
< jdk/incubator/vector/ByteMaxVectorTests.java
< jdk/incubator/vector/CovarOverrideTest.java
< jdk/incubator/vector/DoubleMaxVectorLoadStoreTests.java
< jdk/incubator/vector/DoubleMaxVectorTests.java
< jdk/incubator/vector/FloatMaxVectorLoadStoreTests.java
< jdk/incubator/vector/FloatMaxVectorTests.java
< jdk/incubator/vector/ImageTest.java
< jdk/incubator/vector/IntMaxVectorLoadStoreTests.java
< jdk/incubator/vector/IntMaxVectorTests.java
< jdk/incubator/vector/LoadJsvmlTest.java
< jdk/incubator/vector/LongMaxVectorLoadStoreTests.java
< jdk/incubator/vector/LongMaxVectorTests.java
< jdk/incubator/vector/MethodOverideTest.java
< jdk/incubator/vector/MismatchTest.java
< jdk/incubator/vector/PreferredSpeciesTest.java#id0
< jdk/incubator/vector/PreferredSpeciesTest.java#id1
< jdk/incubator/vector/ShortMaxVectorLoadStoreTests.java
< jdk/incubator/vector/ShortMaxVectorTests.java
< jdk/incubator/vector/VectorHash.java
< jdk/incubator/vector/VectorMaxConversionTests.java#id0
< jdk/incubator/vector/VectorMaxConversionTests.java#ZGenerational
< jdk/incubator/vector/VectorMaxConversionTests.java#ZSinglegen
< jdk/incubator/vector/VectorReshapeTests.java
< jdk/incubator/vector/VectorRuns.java
2410c2384
< Tests found: 2,408
---
> Tests found: 2,382

```

2023-10-31 20:28 UTC, AlanBateman commented
jdk_vector_sanity was added by JDK-8295970 to get some coverage in tier1. That motivation should probably be re-examined. One thing that I don't like is that it maps to a list of specific tests so it's not very maintainable. I wonder if it could be removed and change jdk_vector to run in tier2.

2023-11-01 01:34 UTC, DamonFool commented
May I ask how long it will take to run jdk_vector_sanity?

My testing in JDK-8295970 was less than 2min. See https://github.com/openjdk/jdk/pull/10879#issuecomment-1298126965

2023-11-01 02:34 UTC, jddarcy commented
> May I ask how long it will take to run jdk_vector_sanity?
> 
> My testing in JDK-8295970 was less than 2min. See [#10879 (comment)](https://github.com/openjdk/jdk/pull/10879#issuecomment-1298126965)

The time taken is going to vary of course. That set of tests took about 2 minutes when run with 4 way concurrency on the configuration I use for development, 3 minutes 21 seconds when run serially. About 10 of the individual tests took more than 25 seconds latency to run on that config.

I don't think it would be hard to find, say 30 different API areas in the JDK outside of the base module, that might want "just 2 minutes of testing in tier1," which would cause tier 1 to take another hour to run.

Until the vector API is in the base module, I think a total tier 1 time budget of at most 10 seconds _total_, but being only in tier 2 and later tiers would be fine too IMO.

2023-11-01 03:03 UTC, DamonFool commented
Okay.

If 2min testing time is not acceptable in tier1 for vector api, I agree with @AlanBateman that `jdk_vector_sanity` should be removed.
Also, it would be better to hear from @vnkozlov .

2023-11-01 18:39 UTC, vnkozlov requested changes
jdk_vector_sanity was added to tier1 to catch issues early in GHA.
See #10879 and discussion [#10807-review](https://github.com/openjdk/jdk/pull/10807#pullrequestreview-1150314487)

If some tests run for long time they could be excluded from jdk_vector_sanity list.

2023-11-01 19:11 UTC, vnkozlov commented
I would suggest to determine the set of tests which run "at most 10 seconds total" and run only them in tier1.
Also taking into account API coverage.

2023-11-01 20:36 UTC, jddarcy commented
> I would suggest to determine the set of tests which run "at most 10 seconds total" and run only them in tier1. Also taking into account API coverage.

Okay; I think preserving a handful of tests to check for a dead-on-arrival vector change is acceptable. Here are the sorted running times from my machine, times in milliseconds:

VectorHash.jtr:2190
PreferredSpeciesTest_id0.jtr:2545
VectorRuns.jtr:2790
PreferredSpeciesTest_id1.jtr:3228
MethodOverideTest.jtr:3864
CovarOverrideTest.jtr:3993
MismatchTest.jtr:4013
LoadJsvmlTest.jtr:4112
ImageTest.jtr:6074
LongMaxVectorLoadStoreTests.jtr:6197
DoubleMaxVectorLoadStoreTests.jtr:6445
ShortMaxVectorLoadStoreTests.jtr:6692
IntMaxVectorLoadStoreTests.jtr:6868
FloatMaxVectorLoadStoreTests.jtr:6952
ByteMaxVectorLoadStoreTests.jtr:7098
AddTest.jtr:7303
-=-=-=-=-=-=-=-=-=-
VectorMaxConversionTests_ZSinglegen.jtr:24001
LongMaxVectorTests.jtr:27290
IntMaxVectorTests.jtr:27349
VectorMaxConversionTests_id0.jtr:27588
VectorMaxConversionTests_ZGenerational.jtr:29138
ShortMaxVectorTests.jtr:29220
FloatMaxVectorTests.jtr:30849
ByteMaxVectorTests.jtr:31206
DoubleMaxVectorTests.jtr:32384
VectorReshapeTests.jtr:39873

The tests below the line take 24 or more seconds to run so would be out of consideration.

@vnkozlov , which subset of the above the line regressions tests would be most helpful to preserve?

2023-11-01 22:00 UTC, vnkozlov commented
@jddarcy  I think next 3 tests are good for sanity check in tier1:

VectorHash.java
VectorRuns.java
PreferredSpeciesTest.java

2023-11-02 01:58 UTC, jddarcy commented
> @jddarcy I think next 3 tests are good for sanity check in tier1:
> 
> VectorHash.java VectorRuns.java PreferredSpeciesTest.java

Changeset implementing that pushed.

Double-check on tier1:

```
$ diff tier1.txt tier1-patched.txt 
108,123d107
< jdk/incubator/vector/AddTest.java
< jdk/incubator/vector/ByteMaxVectorLoadStoreTests.java
< jdk/incubator/vector/ByteMaxVectorTests.java
< jdk/incubator/vector/CovarOverrideTest.java
< jdk/incubator/vector/DoubleMaxVectorLoadStoreTests.java
< jdk/incubator/vector/DoubleMaxVectorTests.java
< jdk/incubator/vector/FloatMaxVectorLoadStoreTests.java
< jdk/incubator/vector/FloatMaxVectorTests.java
< jdk/incubator/vector/ImageTest.java
< jdk/incubator/vector/IntMaxVectorLoadStoreTests.java
< jdk/incubator/vector/IntMaxVectorTests.java
< jdk/incubator/vector/LoadJsvmlTest.java
< jdk/incubator/vector/LongMaxVectorLoadStoreTests.java
< jdk/incubator/vector/LongMaxVectorTests.java
< jdk/incubator/vector/MethodOverideTest.java
< jdk/incubator/vector/MismatchTest.java
126,127d109
< jdk/incubator/vector/ShortMaxVectorLoadStoreTests.java
< jdk/incubator/vector/ShortMaxVectorTests.java
129,132d110
< jdk/incubator/vector/VectorMaxConversionTests.java#id0
< jdk/incubator/vector/VectorMaxConversionTests.java#ZGenerational
< jdk/incubator/vector/VectorMaxConversionTests.java#ZSinglegen
< jdk/incubator/vector/VectorReshapeTests.java
2410c2388
< Tests found: 2,408
---
> Tests found: 2,386

Tier 2 is unchanged from before the PR.
```

2023-11-02 02:11 UTC, DamonFool approved these changes
LGTM

If tier2 is unchanged after this patch, it would be good to change the JBS title.
Thanks.

2023-11-02 03:49 UTC, jddarcy commented
> LGTM
> 
> If tier2 is unchanged after this patch, it would be good to change the JBS title. Thanks.

Good point; bug and PR titles updated accordingly. Thanks.

2023-11-02 05:14 UTC, vnkozlov approved these changes
Good

2023-11-02 18:58 UTC, jddarcy commented
/integrate

2023-11-02 18:59 UTC, closed without merging