8319200: Don't use test thread factory in ProcessTools.createLimitedTestJavaProcessBuilder()
openjdk/jdk pull request #16442
Opened 2023-11-01 00:06 UTC by lmesnik

Test thread factory is a mode similar to VM flags and should not be used in ProcessTools.createLimitedTestJavaProcessBuilder(). Only createTestJavaProcessBuilder() should use it like jtreg VM options.
Testing tier1-5.

2023-11-01 02:58 UTC, dholmes-ora reviewed
> Test thread factory is a mode similar to VM flags and should not be used in ProcessTools.createLimitedTestJavaProcessBuilder(). 

I'm not sure I agree with that. I think the test factory is a separate testing dimension, independent of JVM flags.

2023-11-01 02:58 UTC, dholmes-ora commented on test/lib/jdk/test/lib/process/ProcessTools.java
> +     * @param isLimited Defines if jtreg options and test thread factory should be added
Suggestion:
```
@param isLimited If true, prevents the addition of jtreg options to the command, and ignores any available test thread factory
```

2023-11-01 05:17 UTC, lmesnik commented
/cc hotspot

2023-11-01 07:00 UTC, stefank requested changes
It seems like the code would be cleaner if you moved the threadFactory injection to `createTestJavaProcessBuilder`.

2023-11-03 21:58 UTC, msheppar commented on test/lib/jdk/test/lib/process/ProcessTools.java
> +    private static ProcessBuilder createJavaProcessBuilder(boolean isLimited, String... command) {
addThreadFactory might be a more appropriate name
However, Stefan has a more SOLID suggestion

2023-11-08 05:33 UTC, lmesnik commented
Moved the threadFactory injection to createTestJavaProcessBuilder. I think that it is more logical to don't set it for limited version of process builder.

2023-11-08 19:10 UTC, lmesnik commented on test/lib/jdk/test/lib/process/ProcessTools.java
> +    private static String[] addTestThreadFactoryArgs(String testThreadFactoryName, String[] command) {
done

2023-11-09 04:57 UTC, dholmes-ora commented on test/lib/jdk/test/lib/process/ProcessTools.java
> +        for (String cmd : commandArgs) {
So `cmd` should really be `arg` right?

2023-11-09 05:01 UTC, dholmes-ora commented
I remain concerned that this means that a whole swag of tests will never be run with virtual threads, which reduces our virtual thread test coverage. Hard to quantify. Do you have any stats on how many tests this will affect and which ones?

2023-11-09 10:47 UTC, msheppar commented
> I remain concerned that this means that a whole swag of tests will never be run with virtual threads, which reduces our virtual thread test coverage. Hard to quantify. Do you have any stats on how many tests this will affect and which ones?

I thought the purpose of the createLimitedTestJavaProcessBuilder is for use where vm option are NOT  being propagated to the ProcessBuilder,  as such the thread factory property wont come into consideration ? the Java doc notes that test using createLimitedTestJavaProcessBuilder would be marked as vm.flagless which would suugest thread factory is not being used.
createTestJavaProcessBuilder is for use when vm args are being propagated and as such thread factory can be "injected" via this method. So this change is streamlining these use cases.
Is this a correct interpretation?

2023-11-10 02:17 UTC, lmesnik commented
The createLimitedTestJavaProcessBuilder is used in 410 tests (hotspot and jdk).
233 of them are flagless and not supposed to be executed with any additional VM flags. (They should be reviewed by it is a separate issue).
177 are not marked as flagless and should be updated to be flagless or use createTestJavaProcessBuilder.
The 'createLimitedTestJavaProcessBuilder' method should be used only when the process not accept any flags and it is logical to assume that thread factory shouldn't be used either.  I think it just makes consistent the createLimitedTestJavaProcessBuilder and createTestJavaProcessBuilder methods.
It was not my original goal to add test thread factory part of createLimitedTestJavaProcessBuilder, I just missed that original createJavaProcessBuilder is applied to all processes.

2023-11-10 04:30 UTC, dholmes-ora commented
Okay, sorry, I've misunderstood the nature of this issue. This change has no affect on whether jtreg runs a specific test (or set of tests) using the virtual thread wrapper to launch the test. This only affects code that uses ProcessTools and where the launched JVM would examine the `test.thread.factory` property. How many tests actually look at this property directly in code that is run via ProcessTools? The only tests that appear to look at this property are JDB and JDI tests, where we have a test framework that selects use of virtual threads based on this property. I couldn't find any test that would actually be affected by this. Sorry for the noise.

2023-11-10 04:42 UTC, dholmes-ora commented
Uggghhh no I've still misunderstood what this is doing. `addTestThreadFactoryArgs` will create a wrapper to run the specified main class in a virtual thread. So if the test using `createLimitedTestJavaProcessBuilder` was being run in a virtual thread, then the exec'd "app" would be too. Plus it would have the property set. So this is potentially reducing virtual thread test coverage.

That said I'm bowing out of this discussion.

2023-11-16 07:10 UTC, lmesnik commented
It is expected from `createLimitedTestJavaProcessBuilder` to execute the process exactly as specified in the test, without any additional changes from jtreg. It is very likely that the test might fail if the process is executed in other modes. I agree that usage of this method is always a potential loss of coverage for vm flags being tested and for virtual threads. So this method should be used only when it is necessary. As well as we should minimize the number of flagless testing.

2024-01-11 10:57 UTC, closed without merging