JDK-8319314: NMT detail report slow or hangs for large number of mappings
openjdk/jdk pull request #16480
Opened 2023-11-02 16:42 UTC by tstuefe

If a lot of mappings have been registered with NMT, NMT detail report may get so slow as to hang seemingly. 

100 k mappings will take > 1 minute
1 million mappings never returns (I canceled the test after 90 minutes)

We burn all the time doing a sorted insert into the target array of the MemBaseline object. That sorted insert is pointless since the source array is already sorted by region base address.

Omitting the pointless sort makes the command complete, for 1 million mappings, in 48 seconds.

2023-11-03 09:26 UTC, jdksjolen approved these changes
Hi,

Thanks for this, one small thing to be fixed.

2023-11-03 09:26 UTC, jdksjolen commented on src/hotspot/share/nmt/memBaseline.cpp
> +    assert(rgn->base() >= _last_base, "region unordered?");
It seems like we don't assign to `_last_base`?

2023-11-03 10:14 UTC, tstuefe commented
/label add hotspot-runtime

2023-11-05 06:20 UTC, tstuefe commented
Ping @gerard-ziemski ?

2023-11-08 07:05 UTC, tstuefe commented
Ping anyone?

2023-11-08 15:23 UTC, gerard-ziemski commented
Taking a look...

2023-11-08 15:54 UTC, gerard-ziemski requested changes
I have a couple small questions/feedback.

Also, you said:

```
100 k mappings will take > 1 minute
1 million mappings never returns (I canceled the test after 90 minutes)
```

What are those times now with this change?

2023-11-09 06:31 UTC, tstuefe commented
Hi Gerard,

thanks for looking into this. Answers below.

> I have a couple small questions/feedback - see below.
> 
> Also, you said:
> 
> ```
> 100 k mappings will take > 1 minute
> 1 million mappings never returns (I canceled the test after 90 minutes)
> ```
> 
> What are those times now with this change?

1 million mappings finished with my patch in 48 seconds.
100k mappings finished in 19 seconds I believe? The growth was exponential before my patch, now it seems linear.

2023-11-09 09:42 UTC, tstuefe commented on src/hotspot/share/nmt/memBaseline.cpp
> +#endif
I think that won't compile. I don't remember the exact reason, but DEBUG_ONLY does not work for initializer lists.

2023-11-09 09:44 UTC, tstuefe commented on src/hotspot/share/nmt/memBaseline.cpp
> +  size_t    _count;
No idea. I guess this is a remnant, and could probably be removed, but ideally in another cleanup PR.

2023-11-10 08:30 UTC, tstuefe commented
@gerard-ziemski Do you want me to make any other changes? About the _count, I don't really want to touch that since I would like to keep this change small minimal and focused, since it needs to be backported to at least 21 and 17, possibly further down.

2023-11-11 00:03 UTC, gerard-ziemski approved these changes

2023-11-11 06:54 UTC, tstuefe commented
Thanks @gerard-ziemski and @jdksjolen !

/integrate

2023-11-11 06:55 UTC, closed without merging