8256641: CDS VM operations do not lock the heap
openjdk/jdk pull request #1661
Opened 2020-12-07 11:23 UTC by tschatzl

Hi all,

  can I get reviews for this change that adds missing synchronization of CDS related VM operations with other heap operations?

`VM_PopulateDumpSharedSpace`, `VM_PopulateDynamicDumpSharedSpace` and `VM_Verify` are used during CDS operation, one for creating the CDS archive, one for mapping in the CDS archive into the heap, and the last one for verification.

They all in one way or the other need to synchronize with garbage collection as they may either do a GC or just do verification, as actual (STW-)gc returns an uninitialized block of memory that is not parseable; and before that block of memory can be initialized, another VM operation could be started otherwise seeing that uninitialized memory.

The existing mechanism to prevent this kind of interference is taking the `Heap_lock`, so the suggested solution is based on having all these VM operations descend from a new `VM_GC_Sync_Operation` `VM_Operation` which does that (and only that).

There some points I would like to discuss in this change though:
- each VM Operation handles `Heap_lock` by itself, which I considered to be too error-prone.
- the need for `VM_Verify` to coordinate with garbage collections is "new" and has been introduced with [JDK-8253081](https://bugs.openjdk.java.net/browse/JDK-8253081). That could be undone (removed), but I kind of believe that with more expected changes to the CDS mechanism in the future the additional full-heap verification after loading the archive is worth the additional effort.
One drawback is that since ZGC also uses `VM_Verify`, that operation now gets the `Heap_lock` too, and is kind of also using some part of the "set of operations related to GC" in general but did not so before, keeping almost completely separate. Testing did not show an issue, and I tried to look at the code carefully to see whether there could be issues to no result. (I.e. I couldn't find an issue)
- this changes adds a new VM Operation class called `VM_GC_Sync_Operation` that splits off the handling of `Heap_lock` (i.e. the actual synchronization` from `VM_GC_Operation`. The reason is that I do not think skipping logic for the gc VM operation if there already has been a GC between the `doit_prolouge()` (outside of the safepoint) and the `doit()` (inside the safepoint) is a good fit for all the `VM_Populate*` or even `VM_Verify`.
Other existing VM operations (`VM_HeapDump` and `VM_HeapInspection`) that are not interested in that mechanism use dummy variables and override some methods, but that's not very nice. Since this is a simple change I added this to this change too, but I can separate it.

2020-12-09 10:49 UTC, tschatzl commented
/label add hotspot-gc
/label add hotspot-runtime
/label remove hotspot

2020-12-09 12:24 UTC, kimbarrett requested changes

2020-12-09 12:24 UTC, kimbarrett commented on src/hotspot/share/gc/shared/gcVMOperations.cpp
> +}
This invocation checking doesn't seem right at this level.  That is, skip_operation and prologue_succeeded all seem to me to have nothing to do with syncing, instead belonging to the VM_GC_Operation level and should remain there.

2020-12-09 12:24 UTC, kimbarrett commented on src/hotspot/share/gc/shared/gcVMOperations.hpp
> +  // Do notifyAll (if needed) and release held lock
s/notifyAll/notify_all/

2020-12-09 12:29 UTC, tschatzl commented on src/hotspot/share/gc/shared/gcVMOperations.cpp
> +  if (Universe::has_reference_pending_list()) {
Also answering the next question: these two items (i.e. including the `prologue_succeeded` stuff) have mostly been kept there to allow simple reuse in `VM_GC_Operation`. I'll remove those and (maybe) just break the inheritance chain.

2020-12-09 15:55 UTC, kimbarrett approved these changes
Code changes look good.  A couple of places where comments could use some improvement.

2020-12-09 15:55 UTC, kimbarrett commented on src/hotspot/share/gc/shared/gcVMOperations.hpp
>    virtual bool doit_prologue();
This does a lot more than just acquiring the lock.  It also handles the prevention of multiple gc requests.

2020-12-09 15:55 UTC, kimbarrett commented on src/hotspot/share/gc/shared/gcVMOperations.hpp
>    uint           _full_gc_count_before;    // full gc count before acquiring PLL
[pre-existing] "PLL" ?  I think that might be obsolete terminology, referring to the "pending list lock"?  I think should be Heap_lock now.

2020-12-09 18:13 UTC, iklam reviewed
The CDS part looks good to me.

I also scanned the GC code and it looks reasonable to me, but I don't understand all the details to give an official review.

2020-12-09 23:02 UTC, iklam approved these changes

2020-12-10 10:48 UTC, tschatzl commented
I fixed the mentioned comments but would like to defer further cleanup of the classes, particularly those `VM_GC_Operation`s that do not actually participate in the skipping protocol to [JDK-8258029](https://bugs.openjdk.java.net/browse/JDK-8258029) I filed just now.

2020-12-10 11:41 UTC, kimbarrett approved these changes

2020-12-11 09:58 UTC, tschatzl commented
This is a change originally meant for JDK16, but the fork has occurred before integration. So re-requesting a pull [there](https://github.com/openjdk/jdk16/pull/8)

2020-12-11 09:58 UTC, closed without merging