8320530: has_resolved_ref_index flag not restored after resetting entry
openjdk/jdk pull request #16769
Opened 2023-11-21 16:38 UTC by matias9927

ResolvedMethodEntry::reset_entry() clears the fields in the structure and then restores the constant pool index and the resolved references index if it has one. Currently, the resolved references index is restored without restoring the has_resolved_reference flag used by the structure. 

This patch restored the flag with the resolved references index.

2023-11-22 16:55 UTC, adinn approved these changes
Nice catch!

2023-11-23 05:46 UTC, dholmes-ora approved these changes
Change seems fine but what was the effect of not restoring the flag? Does this cause failures or just unnecessary re-resolution, or?

Thanks

2023-11-27 04:48 UTC, iklam commented
> Change seems fine but what was the effect of not restoring the flag? Does this cause failures or just unnecessary re-resolution, or?
> 
> Thanks

The code works somehow, but in an unsafe manner. We are reading from `resolved_references_index()` even when the `has_resolved_ref_shift` bit has been (improperly) cleared. Adding the following assert makes it impossible to start jtreg:

```
diff --git a/src/hotspot/share/oops/cpCache.cpp b/src/hotspot/share/oops/cpCache.cpp
index daa094baa7e..760c5268c88 100644
--- a/src/hotspot/share/oops/cpCache.cpp
+++ b/src/hotspot/share/oops/cpCache.cpp
@@ -310,6 +310,9 @@ ResolvedMethodEntry* ConstantPoolCache::set_method_handle(int method_index, cons
   // Store appendix, if any.
   if (has_appendix) {
+    assert(method_entry->has_resolved_ref_index(), "huh");
     const int appendix_index = method_entry->resolved_references_index();
     objArrayOop resolved_references = constant_pool()->resolved_references();
```

I think we should take this as a chance to tighten up the code in resolvedMethodEntry.hpp:

- `resolved_references_index()` should assert that `has_resolved_ref_index()`.
- The following three functions should assert for mutual exclusivity. I.e., you can't call set_klass() and then call  set_resolved_references_index(). Probably the easiest is to add two more bits: `_has_klass_shift` and `_has_table_index_shift`. At entry of these three setters, we should assert that all three klass/table_index/resolved_references_index bits are cleared.

```
  void set_klass(InstanceKlass* klass) {
    _entry_specific._interface_klass = klass;
  }
  void set_resolved_references_index(u2 ref_index) {
    set_flags(1 << has_resolved_ref_shift);
    _entry_specific._resolved_references_index = ref_index;
  }
  void set_table_index(u2 table_index) {
    _entry_specific._table_index = table_index;
  }
```

Also, `has_resolved_ref_index` should be renamed to `has_resolved_reference_index`; otherwise it's difficult to search for all code related to `resolved_refenece_index`.

2023-11-27 09:03 UTC, adinn commented
> . . . Probably the easiest is to add two more bits: _has_klass_shift and _has_table_index_shift. . . .
Maybe so, but only in debug builds?

2023-11-29 00:12 UTC, iklam approved these changes
LGTM. Just a small nit.

2023-11-29 00:12 UTC, iklam commented on src/hotspot/share/oops/cpCache.cpp
> +    assert(method_entry->has_resolved_references_index(), "sanity");
The assert is not necessary here, as resolved_references_index() already has the same assert.

2023-11-29 06:35 UTC, dholmes-ora requested changes
A few nits with the `DEBUG_ONLY` code.

2023-11-30 06:23 UTC, dholmes-ora approved these changes
Thanks for the updates.

One indentation nit to fix before integration please.

2023-11-30 06:23 UTC, dholmes-ora commented on src/hotspot/share/oops/resolvedMethodEntry.hpp
> +#endif
Indent appears to be 1 instead of 2

2023-11-30 09:54 UTC, adinn approved these changes
Still good

2023-11-30 13:36 UTC, coleenp requested changes
I have a couple of minor requests before you push.  Hopefully not delaying.

2023-11-30 13:37 UTC, coleenp commented on src/hotspot/share/oops/resolvedMethodEntry.hpp
> +  DEBUG_ONLY(
I see, I said the opposite.  I don't like the #ifdef ASSERT blocks.  3 lines vs 1.

2023-11-30 13:39 UTC, coleenp commented on src/hotspot/share/oops/resolvedMethodEntry.hpp
> +  DEBUG_ONLY(
I think each variable should have DEBUG_ONLY() around it, not grouped though.

2023-11-30 21:20 UTC, closed without merging