8296787: Unify debug printing format of X.509 cert serial numbers
openjdk/jdk pull request #16834
Opened 2023-11-27 21:45 UTC by blperez01

Updated `X509CertSelector.java` and `SerialNumber.java` to use same debug printing format for X.509 serial numbers. The format in `SSLLogger.java` is slightly different but now uses the `toString` method in `SerialNumber.java` for better readability.

2023-11-28 10:53 UTC, coffeys commented
for clarity - can you include before and after examples of the serial numbers printed from each change ?

2023-11-28 13:51 UTC, seanjmullan commented
I would like us to use a consistent hex format where each byte is separated by a ":", so for example:

08:3B:E0:56:90:42:46:B1:A1:75:6A:C9:59:91:C7:4A

This is easier to visually parse and is a common format used by other X.509 certificate display tools.

2023-11-29 17:36 UTC, seanjmullan commented
> for clarity - can you include before and after examples of the serial numbers printed from each change ?

Yes, I think that would be useful. Also you will need to add a `noreg` label to the bug since you are not including a test (which I think is ok).

2023-11-29 17:41 UTC, seanjmullan requested changes

2023-11-29 17:41 UTC, seanjmullan commented on src/java.base/share/classes/sun/security/x509/SerialNumber.java
> +        serialNum.toString(16).toUpperCase().replaceAll("(?<=..)(..)", ":$1"); }
I am not sure that `replaceAll` expression is correct. When I tried it for `BigInteger("74984748")`, it emitted "47:82:d2c" when I think it should be "04:78:2D:2C". I would use the HexFormat class here (and in `X509CertSelector`), ex:

`HexFormat.ofDelimiter(":").withUpperCase().formatHex(xcert.getSerialNumber().toByteArray())`

2023-11-29 20:51 UTC, seanjmullan commented on src/java.base/share/classes/sun/security/x509/SerialNumber.java
> +    public String toString() { return "Serial number: " +
Here I would keep "Serial number" as "SerialNumber" to maintain consistency with other X.509 `toString` methods which generally emit the name of the field using camel case format.

My only other comment is to whether it makes sense to move this into a utility method. I see `sun.security.util.Debug.toString` already does the same thing and uses HexFormat but in lower case. I think using lower case or upper case is not a big deal. So maybe just change all of these code instances to call `Debug.toString` to keep things consistent and reuse existing code.

2023-12-05 10:43 UTC, coffeys commented
Edits are heading in the right direction. 

How about refactoring the Debug utility methods ? `toString(byte[]) `might be better as `toHexString(byte[])`

you could also introduce a `toHexString(BigInteger)` method in Debug. That will save you the extra `toByteArray()` call you're making in the various call sites.

It should be possible to extend code coverage in an existing x509 test also to ensure the serial number `toString `output is as expected and to ensure we don't regress in this area in the future etc.

2023-12-08 20:11 UTC, seanjmullan approved these changes
One comment on the test, but looks good otherwise.

2023-12-11 15:46 UTC, coffeys approved these changes
Looks good to me. 

Please ensure you run a wide selection of tests before integration. It should include JFR testing to exercise the X509 JFR event testing we have there.

2023-12-12 19:20 UTC, blperez01 commented
/integrate

2023-12-14 17:56 UTC, seanjmullan commented
/sponsor

2023-12-14 17:57 UTC, closed without merging