8317831: compiler/codecache/CheckLargePages.java fails on OL 8.8 with unexpected memory string
openjdk/jdk pull request #16962
Opened 2023-12-05 01:08 UTC by yftsai

Test CheckLargePages was broken by the previous changes:

[JDK-8261894](https://bugs.openjdk.org/browse/JDK-8261894) removes `UseHugeTLBFS`. It was also removed from `os::can_execute_large_page_memory`, and `CodeCache::page_size` cannot  use huge pages anymore.

[JDK-8310233](https://bugs.openjdk.org/browse/JDK-8310233) changes the pagesize logs from
```
Usable page sizes: 4k, 1G
```
to
```
Large page support enabled. Usable page sizes: 4k, 1G. Default large page size: 1G.
```

This change includes:
- `os::can_execute_large_page_memory` uses `UseLargePages`, which could be implicitly enabled by `UseTransparentHugePages` as well.
- The regular expression in CheckLargePages is updated to capture only the page sizes.
- Test CheckLargePages is still kept in ProblemList.txt until [JDK-8319795](https://bugs.openjdk.org/browse/JDK-8319795)) is resolved.

2023-12-05 13:48 UTC, eastig requested changes

2023-12-05 13:48 UTC, eastig commented on src/hotspot/os/linux/os_linux.cpp
> +  return UseLargePages;
Could you please exclude this change from the PR? The function will be removed by my PR.

In `test/hotspot/jtreg/ProblemList.txt` could you please change
```
compiler/codecache/CheckLargePages.java 8317831 linux-x64
```

to
```
compiler/codecache/CheckLargePages.java 8319795 linux-x64
```

2023-12-05 14:57 UTC, eastig commented
I tested my PR #16582 with the fixed test. The test passed as expected.

2023-12-05 20:55 UTC, eastig approved these changes
lgtm

2023-12-06 01:11 UTC, dholmes-ora approved these changes
I'm going to approve this test fix as the change to the regex itself seems reasonable, even though because the test remains excluded by [JDK-8319795](https://bugs.openjdk.org/browse/JDK-8319795) we won't actually be testing it. If any issues arise when the test is removed from the ProblemList it is expected that [JDK-8319795](https://bugs.openjdk.org/browse/JDK-8319795) will deal with that.

Thanks

2023-12-06 01:47 UTC, yftsai commented
/integrate

2023-12-06 02:33 UTC, dholmes-ora commented
/sponsor

2023-12-06 02:34 UTC, closed without merging