8321683: Tests fail with AssertionError in RangeWithPageSize
openjdk/jdk pull request #17064
Opened 2023-12-11 18:18 UTC by stefank

The test was recently changed to check the THPeligible value in the smaps file, instead of checking the hg flag. This was done because hg isn't set if the THP policy is set to 'always'. With that change I added an assert that if the "hg" flag is set, then THPeligible should also be set. This turns out to not be true, and the assert fails.

My proposal is to check both properties and set isTHP to true if either is set. The isTHP property is later only used to make the page size checks more lenient in the presence of transparent huge pages.

2023-12-19 13:17 UTC, tstuefe requested changes
As Arno mentioned, we need a workaround for older kernels. "THPeligible" has been introduced with linux 5.0. Older kernels won't have that thing.

Also, there has been a back and forth of patches that change the alignment of the output. So, make sure we work with both "THPeligible: 1" and "THPeligible:      1".

Other than that, this is good. Scanning for both hg and THPeligible covers almost all cases. 

I don't know why we used !HT. Does not seem to make much sense.

2023-12-22 12:35 UTC, stefank commented
Thanks @tstuefe and @ArnoZeller for the feedback around older kernels.

> As Arno mentioned, we need a workaround for older kernels. "THPeligible" has been introduced with linux 5.0. Older kernels won't have that thing.

I've added a null check, but I don't have a < 5.0 kernel readily available so it would be good if you could test this (if you have such a set up available).

> 
> Also, there has been a back and forth of patches that change the alignment of the output. So, make sure we work with `THPeligible: <any number of spaces> 1`.

I think the `\\s+` should handle those cases.

> 
> Other than that, this is good. Scanning for both hg and THPeligible covers almost all cases.
> 
> I don't know why we used !HT. Does not seem to make much sense.

Hopefully these changes covers enough for our testing.

2023-12-22 12:38 UTC, tstuefe approved these changes
Looks good. Small typo.

2023-12-22 12:38 UTC, tstuefe commented on test/hotspot/jtreg/runtime/os/TestTracePageSizes.java
> +        // therefore also check thpEligible. If this is still cauing problems in the future,
typo cauing

2023-12-22 13:00 UTC, MBaesken approved these changes

2023-12-22 13:24 UTC, stefank commented
Thanks for the reviews! I'm integrating this now. Feel free to open a new PR if this test needs further tweaking.

2023-12-22 13:25 UTC, stefank commented
/integrate

2023-12-22 13:25 UTC, closed without merging

2023-12-22 22:14 UTC, dcubed-ojdk commented
@stefank - do you plan to backport this fix to JDK22?