8274051
openjdk/jdk pull request #17125
Opened 2023-12-15 15:34 UTC by LizBing

2023-12-16 03:51 UTC, dholmes-ora reviewed
Hi @LizBing ,

This issue was already assigned to @fbredber - did you discuss taking it over with them?

2023-12-16 03:51 UTC, dholmes-ora commented on src/hotspot/share/runtime/os.hpp
> -  static bool supports_vtime();
You need to update the comment appropriately too.

2023-12-16 04:04 UTC, LizBing commented
> Hi @LizBing ,
> 
> This issue was already assigned to @fbredber - did you discuss taking it over with them?

I didn't. However, I saw this issue hadn't been solved for a long time, so I tried handling it.

2023-12-17 22:14 UTC, dholmes-ora approved these changes

2023-12-17 22:15 UTC, dholmes-ora commented
Reminder: hotspot changes require 2 reviews

2023-12-18 09:20 UTC, kimbarrett requested changes
I don't think this change should be made, for reasons discussed in JBS and in
email back when the JBS issues was first opened.

2024-02-12 15:10 UTC, closed without merging