JDK-8322255
openjdk/jdk pull request #17137
Opened 2023-12-17 15:37 UTC by lgxbslgx

Hi all,

This patch fixes several issues about heuristics.

1. Move `ZHeuristics::set_medium_page_size` to `ZArguments::initialize` so that the setting of `MaxTenuringThreshold` can use `ZPageSizeMedium` correctly.
2. Fix `ZHeuristics::use_per_cpu_shared_small_pages` to meet its comment.
3. Fix `ZHeuristics::significant_heap_overhead` and `ZHeuristics::significant_young_overhead` to use `ZFragmentationLimit` and `ZYoungCompactionLimit` as percentages instead of multiples.

Thanks for the review.

Best Regards,
-- Guoxiong

2023-12-18 09:17 UTC, tschatzl requested changes
Would it be possible to split these different issues into separate PRs?

They look like different bugs.

2023-12-18 09:56 UTC, lgxbslgx commented
> Would it be possible to split these different issues into separate PRs?
> 
> They look like different bugs.

I thought about splitting them before. But all of them only change one line or two in the same file. So I put them together by using a common title. If you insist on splitting them, I am OK too.

2023-12-18 10:18 UTC, tschatzl commented
That is the point - put unrelated changes into different PRs so that new, unexpected behavior can be (if necessary) easily traced back to that particular issue (e.g. when bisecting).

2023-12-18 11:22 UTC, lgxbslgx commented
Filed [JDK-8322278](https://bugs.openjdk.org/browse/JDK-8322278) and [JDK-8322279](https://bugs.openjdk.org/browse/JDK-8322279) to split the other issues. Now this patch only sets the ZPageSizeMedium before MaxTenuringThreshold.

2023-12-18 13:03 UTC, fisk approved these changes
Looks good.

2023-12-18 13:30 UTC, tschatzl approved these changes

2023-12-19 10:38 UTC, lgxbslgx commented
@fisk @tschatzl Thanks for your reviews. Integrating.

/integrate

2023-12-19 10:39 UTC, closed without merging

2024-01-23 09:32 UTC, mmyxym commented
/backport jdk21u-dev