8257910: [JVMCI] Set exception_seen accordingly in the runtime.
openjdk/jdk pull request #1713
Opened 2020-12-09 10:03 UTC by mur47x111

Update exception_seen flag in the MDO when no exception handler is found for caller during deoptimization, or when exception is thrown in the runtime.

Plus, `-Xlog:exceptions=info` code and `AbortVMOnException` are adjusted in C1 runtime and jvmci runtime to be consistent with C2, i.e., before `JvmtiExport::can_post_on_exceptions` deoptimization and fast continuation when compiled handler is found.

2020-12-09 18:31 UTC, vnkozlov requested changes

2020-12-09 18:31 UTC, vnkozlov commented on src/hotspot/share/runtime/sharedRuntime.cpp
> +  if (EnableJVMCI) {
I think this should also check `&& UseJVMCICompiler`

2020-12-10 00:07 UTC, vnkozlov commented on src/hotspot/share/jvmci/jvmciRuntime.cpp
> +  NOT_PRODUCT(Exceptions::debug_check_abort(exception));
All other places calls debug_check_abort() in product too. It seems 8136577 changes missed JVMCI:
https://github.com/openjdk/jdk/commit/a25ce80e782a73390ae1109250dfa6fe6a48fcbe
Please, update to call it in product for JVMCI too. Note, AbortVMOnException is diagnostic flag now.

2020-12-10 00:10 UTC, vnkozlov commented on src/hotspot/share/c1/c1_Runtime1.cpp
> +    tempst.print("compiled method <%s>\n"
Can you change message:
"C1 compiled method <%s>\n"

2020-12-10 00:12 UTC, vnkozlov requested changes

2020-12-10 00:12 UTC, vnkozlov commented on src/hotspot/share/jvmci/jvmciRuntime.cpp
> +    tempst.print("compiled method <%s>\n"
Can you change message to?:
"JVMCI compiled method <%s>\n"

2020-12-10 17:03 UTC, vnkozlov requested changes
Looks good. Unfortunately it missed JDK16 fork but because it is P3 bug it can be fixed there without approval for now (RDP1 phase).
Please, create PR based on https://github.com/openjdk/jdk16 (create your fork for it) and I will approve it. After push the fix will be auto-forwarded into JDK 17 (current  https://github.com/openjdk/jdk)

2020-12-10 17:57 UTC, mur47x111 commented
Thanks @vnkozlov ! Created https://github.com/openjdk/jdk16/pull/2 and took the opportunity to squash commits.

2020-12-14 13:04 UTC, closed without merging