8322298
openjdk/jdk pull request #17145
Opened 2023-12-18 14:33 UTC by albertnetymk

Trivial removing dead code.

2023-12-18 16:10 UTC, tschatzl approved these changes
Lgtm and trivial.

2023-12-19 08:45 UTC, kstefanj approved these changes

2023-12-19 11:36 UTC, kimbarrett requested changes
Looks good.

2023-12-19 11:36 UTC, kimbarrett approved these changes

2023-12-28 13:00 UTC, lgxbslgx approved these changes
LGTM

2024-01-04 08:30 UTC, albertnetymk commented
Thanks for the review.

/integrate

2024-01-04 08:31 UTC, closed without merging