8322321: Add man page doc for -XX:+VerifySharedSpaces
openjdk/jdk pull request #17152
Opened 2023-12-19 06:19 UTC by iklam

`VerifySharedSpaces` was disabled in [JDK-8221478](https://bugs.openjdk.org/browse/JDK-8221478) by default. We should add an entry in the "java" man page about the intended use for this flag.

2023-12-19 07:56 UTC, iklam commented
/label hotspot

2023-12-19 22:19 UTC, dholmes-ora requested changes
Text is generally fine. A couple of typos need fixing.

2023-12-19 22:19 UTC, dholmes-ora commented on src/java.base/share/man/java.1
> +if it passes an integrity check based on CRC32 checkums.
typo: checkums

2023-12-19 22:19 UTC, dholmes-ora commented on src/java.base/share/man/java.1
> +The purpose of this flag is to check for unintentional damages of CDS
s/damages of/damage to/

2023-12-19 23:34 UTC, dholmes-ora commented on src/java.base/share/man/java.1
> +The purpose of this flag is to check for unintentional damages to CDS
s/damages/damage/

2023-12-20 00:52 UTC, dholmes-ora approved these changes
Looks good.

Only one review needed for this doc change.

Thanks.

2023-12-20 01:04 UTC, calvinccheung approved these changes

2023-12-20 05:49 UTC, iklam commented
Thanks @dholmes-ora @calvinccheung for the review
/integrate

2023-12-20 05:50 UTC, closed without merging