8322781: C1: Debug build crash in GraphBuilder::vmap() when print stats
openjdk/jdk pull request #17205
Opened 2023-12-29 15:02 UTC by D-D-H

Hi,

Could I have a review of this fix patch that fixes a crash problem in the debug build when -XX:+PrintValueNumbering -XX:+Verbose -XX:-UseLocalValueNumbering

Thanks

2024-01-02 20:16 UTC, vnkozlov approved these changes
Looks good.

2024-01-03 06:38 UTC, TobiHartmann requested changes
Please add a test case to `test/hotspot/jtreg/compiler/arguments/TestC1Globals.java`. Thanks!

2024-01-03 07:50 UTC, D-D-H commented
> Please add a test case to `test/hotspot/jtreg/compiler/arguments/TestC1Globals.java`. Thanks!

Added and verified in my Linux env.

2024-01-03 12:00 UTC, shipilev approved these changes
Looks fine.

2024-01-04 13:06 UTC, TobiHartmann approved these changes
Thanks, looks good to me.

2024-01-04 13:11 UTC, D-D-H commented
/integrate

Thanks for the review.

2024-01-04 13:11 UTC, closed without merging