8322859
openjdk/jdk pull request #17227
Opened 2024-01-02 16:44 UTC by albertnetymk

Simple moving the `transform_stack_chunk` call to match its counterpart in G1.

2024-01-02 17:15 UTC, stefank requested changes
Shouldn't the transform_stack_chunk be called before push_contents?

2024-01-09 12:42 UTC, tschatzl requested changes
Needs more background. Note that quick analysis indicates that this is okay ("make code appear like g1" isn't such a proof or attempt to prove), and the CAS can be relaxed (as suggested in #4751) but just in case I expect more analysis and testing before doing that.

2024-06-26 07:57 UTC, stefank approved these changes
Looks good.

2024-06-26 08:38 UTC, tschatzl approved these changes

2024-06-27 10:23 UTC, albertnetymk commented
Thanks for review.

/integrate

2024-06-27 10:23 UTC, closed without merging