8323660
openjdk/jdk pull request #17398
Opened 2024-01-12 14:31 UTC by LizBing

follow up 8234502.

2024-01-12 14:45 UTC, albertnetymk commented
Some indentations of arg list are broken, e.g. `SerialHeap::collect_generation`.

2024-01-12 15:19 UTC, albertnetymk commented on src/hotspot/share/gc/serial/serialHeap.cpp
> +#include "services/memoryManager.hpp"
This order seems wrong.

2024-01-12 15:27 UTC, albertnetymk approved these changes

2024-01-12 20:49 UTC, plummercj approved these changes
SA change looks good. But...

It looks like all the copyright updates to 2024 are missing from this PR and the previous PR. We may need another PR for that. Also, the two new files in that PR should have a copyright that just says 2024, since that is the year it was added. Instead they say "Copyright (c) 2000, 2023"

2024-01-13 01:57 UTC, LizBing commented
> SA change looks good. But...
> 
> It looks like all the copyright updates to 2024 are missing from this PR and the previous PR. We may need another PR for that. Also, the two new files in that PR should have a copyright that just says 2024, since that is the year it was added. Instead they say "Copyright (c) 2000, 2023"

reported.
https://bugs.openjdk.org/browse/JDK-8323693

2024-01-13 02:23 UTC, LizBing commented
thanks for the review.
/integrate

2024-01-13 20:11 UTC, kimbarrett requested changes

2024-01-13 20:11 UTC, kimbarrett commented on src/hotspot/share/gc/serial/serialHeap.cpp
> +  _old_pool(nullptr) {
Don't make this change to the indentation of the mem-initializer-list.  The existing indentation is one of
several styles used in GC code, including throughtout Z.  The proposed new indentation is one which is
also probably still used in older code.  But some time ago there was discussion amongst the Oracle GC
team about constructor formatting and which of several we might prefer.  We didn't reach a consensus
at the time, but this one was unanimously, and strongly, disliked.  The problem is that with the indentation
of the mem-initializer-list being the same as the body, and the opening brace of the body cuddled with
the end of the mem-initializer-list, it is hard to spot where the mem-initializer-list ends and the body
begins.

2024-01-14 05:26 UTC, kimbarrett approved these changes

2024-01-14 06:47 UTC, LizBing commented
/integrate

2024-01-15 09:11 UTC, albertnetymk commented
/sponsor

2024-01-15 09:13 UTC, closed without merging