8323715
openjdk/jdk pull request #17418
Opened 2024-01-15 09:37 UTC by albertnetymk

Simple moving files from shared to serial folder.

2024-01-15 09:53 UTC, stefank requested changes
Could the files be renamed from genMemoryPools.* to serialMemoryPools.*?

2024-01-15 09:53 UTC, stefank commented on src/hotspot/share/gc/serial/genMemoryPools.cpp
>  #include "gc/serial/defNewGeneration.hpp"
The defNewGeneration.hpp line needs to move up.

2024-01-15 10:49 UTC, stefank requested changes

2024-01-15 10:49 UTC, stefank commented on src/hotspot/share/gc/serial/serialMemoryPools.hpp
> +#define SHARE_GC_SERIAL_GENMEMORYPOOLS_HPP
The include guards need to be updated as well.

2024-01-15 10:53 UTC, tschatzl approved these changes
Lgtm.

Please also update copyright year at your discretion before pushing.

2024-01-15 12:05 UTC, stefank approved these changes

2024-01-16 08:37 UTC, albertnetymk commented
Thanks for the review.

/integrate

2024-01-16 08:39 UTC, closed without merging