8323794: Remove unused jimage compressor plugin configuration
openjdk/jdk pull request #17443
Opened 2024-01-16 10:55 UTC by cl4es

There's an unused concept of a pluginConfig that is passed into the jlink compress plugins, however we always pass null here and the code seems broken (the pluginConfig wouldn't have been stored properly). This seem to be a left-over from a more generic plugin design that never came to fruition.

This PR cleans out this code from the plugins and decompressors, while keeping the compressed header format intact for backwards compatibility (and in case we want to revisit this in the future)

2024-01-16 16:04 UTC, JimLaskey requested changes

2024-01-16 16:04 UTC, JimLaskey commented on src/java.base/share/classes/jdk/internal/jimage/decompressor/CompressedResourceHeader.java
> +        int magic = buffer.getInt(0);
Named constant for offsets?

2024-01-16 16:04 UTC, JimLaskey commented on src/java.base/share/classes/jdk/internal/jimage/decompressor/CompressedResourceHeader.java
> +        long size = buffer.getLong(4);
Named constant for offsets?

2024-01-16 18:05 UTC, JimLaskey approved these changes
LGTM

2024-01-16 18:16 UTC, mlchung approved these changes
Looks good.

2024-01-16 20:51 UTC, mlchung approved these changes

2024-01-17 10:51 UTC, cl4es commented
Thanks for reviewing and re-reviewing! I caught and fixed a few issues in testing (tier1-4), extending pre-integration testing to tier5 and taking another manual pass over all related tests before integrating.

2024-01-17 15:40 UTC, cl4es commented
/integrate

2024-01-17 15:41 UTC, closed without merging