8324210
openjdk/jdk pull request #17497
Opened 2024-01-19 13:33 UTC by albertnetymk

Trivial removing dead code.

2024-01-22 14:45 UTC, tschatzl requested changes

2024-01-22 14:45 UTC, tschatzl commented on src/hotspot/share/gc/serial/generation.hpp
> -  virtual Generation::Name kind() { return Generation::Other; }
`Generation::Other` should be removed as well.

2024-01-23 09:37 UTC, tschatzl approved these changes

2024-01-23 09:38 UTC, albertnetymk commented
Thanks for review.

/integrate

2024-01-23 09:38 UTC, closed without merging