8324126: Error message for mistyping -XX:+Unlock...Options is not helpful
openjdk/jdk pull request #17575
Opened 2024-01-25 19:01 UTC by SoniaZaldana

If we run the VM option to unlock experimental vm options without the preceding ‘+’, the error message is not very helpful: 

```Error: VM option 'UnlockExperimentalVMOptions' is experimental and must be enabled via -XX:+UnlockExperimentalVMOptions.```

With the proposed change, we should see a more descriptive error message, namely the lack of a +/- sign. 

```Missing +/- setting for VM option 'UnlockExperimentalVMOptions'```

Testing: runtime/commandLine regression tests pass. Also added a regression test to verify expected behaviour.

2024-01-26 05:59 UTC, tstuefe commented
Mechanically, the fix looks okay. But we now will always, when missing +- for a locked option, print "missing +-":

Example:

"-XX:UseCompactObjectHeaders"
-> "missing +-"
User corrects:
"-XX:+UseCompactObjectHeaders"
-> "needs to be unlocked"

I think this is fine, and a minor concern, but let's ask @dholmes-ora.

The alternative would be to not make "UseDiagnosticVMOptions" option itself diagnostic, and vice versa with UseExperimentalVMOptions. Wonder what the reason for that was, @dholmes-ora ?

2024-01-29 02:59 UTC, dholmes-ora commented
> I think this is fine, and a minor concern, but let's ask @dholmes-ora.

So existing logic gives preference to whether the flag is unlocked, and then examines whether it is well-formed. The new code gives preference to whether it is well-formed and then whether it is unlocked. Can't you do both together?

> The alternative would be to not make "UseDiagnosticVMOptions" option itself diagnostic, and vice versa with UseExperimentalVMOptions. Wonder what the reason for that was, @dholmes-ora ?

I expect because it was considered appropriate. If those flags were themselves product flags then they would be subject to product flag rules.

2024-01-29 02:59 UTC, dholmes-ora requested changes

2024-01-29 02:59 UTC, dholmes-ora commented on src/hotspot/share/runtime/arguments.cpp
> + * Copyright (c) 1997, 2023, 2024, Oracle and/or its affiliates. All rights reserved.
This copyright change is incorrect. Oracle copyrights only use 2 years: first and last, so 2023 simply becomes 2024.

2024-01-29 02:59 UTC, dholmes-ora commented on test/hotspot/jtreg/runtime/CommandLine/TestVMOptions.java
> + * Copyright (c) 2014, 2023, 2024, Oracle and/or its affiliates. All rights reserved.
Ditto re copyright.

2024-01-30 06:26 UTC, dholmes-ora commented
So now we will print the unlock message followed by any formatting error message? Can you provide sample output please. Thanks

2024-01-31 06:18 UTC, dholmes-ora approved these changes
Thanks. Looks good.

2024-01-31 06:39 UTC, tstuefe approved these changes
Small nits wrt indentation, otherwise good. If you fix them, I don't need another review - feel free to integrate.

> I expect because it was considered appropriate. If those flags were themselves product flags then they would be subject to product flag rules.

The more I think about this, the less sense this makes. UseExperimentalVMOptions is used to enable experimental VM options. That implies that it is a product flag itself, since you must be able to use in for a product VM that is not yet in ExperimentalVMOptions-allowed-state.

2024-01-31 06:39 UTC, tstuefe commented on src/hotspot/share/runtime/arguments.cpp
> +      #endif
Please revert the indentation (above too) - we don't usually indent preprocessor directives .

2024-01-31 06:39 UTC, tstuefe commented on src/hotspot/share/runtime/arguments.cpp
> +          "Missing +/- setting for VM option '%s'\n", argname);
Fix indentation (2 spaces)

2024-01-31 15:02 UTC, SoniaZaldana commented
/integrate

2024-02-06 07:03 UTC, tstuefe commented
/sponsor

2024-02-06 07:03 UTC, closed without merging