8324933: ConcurrentHashTable::statistics_calculate synchronization is expensive
openjdk/jdk pull request #17629
Opened 2024-01-30 10:48 UTC by fisk

In the ConcurrentHashTable::statistics_calculate function, we enter and exit a ScopedCS with the global counter for every single bucket. This has showed up to be pretty intense on some machines. We should make the synchronization a bit less intense here. This patch adds simple batching so we synchronize once per 128 buckets instead of every single one.

2024-01-31 11:12 UTC, tschatzl requested changes

2024-01-31 11:12 UTC, tschatzl commented on src/hotspot/share/utilities/concurrentHashTable.inline.hpp
> +      batch_end = batch_start + batch_size;
Something like (untested):
```suggestion
  for (size_t start_batch = 0; start_batch <= _table->_size; start_batch += batch_size {
    size_t batch_end = MIN2(start_batch + batch_size, _table->_size);
```

seems to be much much easier to follow (and corresponds to "usual" code for such loops) than the suggested one.
For extra performance `_table->_size` could be hoisted as well, but the compiler may alread do that anyway.

2024-02-13 15:06 UTC, fisk commented
Thanks for the review @tschatzl! I liked your suggested change. It looks simpler now.

2024-02-13 15:52 UTC, coleenp approved these changes
This seems reasonable, as long as the critical section is held throughout a bucket iteration.

2024-02-14 12:20 UTC, tschatzl approved these changes
lgtm. A comment why we need to do the batched iteration (without looking at versioning system logs) would be nice.

2024-02-14 14:59 UTC, fisk commented
Thanks for the reviews, @coleenp and @tschatzl! I will add a comment before integrating.

2024-02-15 09:26 UTC, fisk commented
/integrate

2024-02-15 09:26 UTC, closed without merging