8324893: Rename JVMDITools.h
openjdk/jdk pull request #17636
Opened 2024-01-30 18:34 UTC by kimbarrett

8324893: Rename JVMDITools.h

Please review this trivial change that renames the file
test/hotspot/jtreg/vmTestbase/nsk/share/JVMDITools.h to JVMDITools.hpp.  There
are no uses of NULL in this file to be fixed.

Testing: mach5 tier1

2024-01-30 19:09 UTC, kimbarrett commented
/label hotspot-runtime

2024-01-30 19:38 UTC, coleenp approved these changes
Are these actually used ?  @dcubed-ojdk  I thought JVMDI was removed years ago.

2024-01-30 21:10 UTC, dcubed-ojdk commented
JVM/DI and JVM/PI were removed years ago. This file came in when the NSK test suite
was imported into the code base. JVMDITools.h is mentioned in two other files:

test/hotspot/jtreg/vmTestbase/nsk/share/JVMDITools.cpp:#include "JVMDITools.h"
test/hotspot/jtreg/vmTestbase/nsk/share/README:        JVMDITools.h, JVMDITools.c

I have no idea whether there's still some very old code that still uses stuff in JVMDITools.cpp.

2024-01-30 22:01 UTC, coleenp requested changes
I can't find these used anywhere.  You should remove these.

2024-01-31 08:57 UTC, kimbarrett commented
You are right. While looking into JDK-8324799 I found a couple of headers that
were only included by an associated .cpp that wasn't built, but the .cpp was
instead included by other files that were built. I mis-remembered this was one
of those, but apparently not. I'll delete the files, update the bug, and make a new PR.

2024-01-31 08:57 UTC, closed without merging