JDK-8324950: IGV: save the state opened graphs to a file
openjdk/jdk pull request #17630
Opened 2024-01-30 14:13 UTC by tobiasholenstein

The current workflow in IGV is the following:
1) import an XML file with graphs or send via network
2) open open or more graphs in a tab
3) extract a set of nodes to be displayed in the tab
4) close IGV and start from 1) again

The idea of this RFE is to save the important states of IGV:
- imported graphs
- opened graphs (tabs)
- for each tab the extracted nodes

2024-01-31 12:50 UTC, TobiHartmann reviewed
Very nice. I gave this a first try and it works well on my machine (Ubuntu, x64).

2024-02-16 13:18 UTC, robcasloz commented on src/utils/IdealGraphVisualizer/igv.sh
> +echo "The IGV workspace in which the imported graphs are saved saved can be set as follows :"
```suggestion
echo "The IGV workspace in which the imported graphs are saved can be set as follows :"
```

2024-02-16 13:34 UTC, robcasloz requested changes
Nice idea!
When I start IGV with `sh igv.sh` (no arguments), I get:
```
The IGV workspace in which the imported graphs are saved saved can be set as follows :
  1) export IGV_WORKSPACE=path/to/workspace
  2) ./igv.sh path/to/workspace
  3) default is ./workspace

IGV workspace : /home/rocastan/git/views/JDK-8324950/open/src/utils/IdealGraphVisualizer/workspace
```
However, the actual workspace directory seems to be:
`/home/rocastan/git/views/JDK-8324950/open/src/utils/IdealGraphVisualizer/application/target/userdir`

![Screenshot from 2024-02-16 14-32-29](https://github.com/openjdk/jdk/assets/8792647/6b1fc50d-5209-4963-88da-4fc9e005ad09)

2024-02-17 13:17 UTC, tobiasholenstein commented
> igv.sh

You are right. There was a small mistake in the `igv.sh` script. It should work now

2024-02-17 13:17 UTC, tobiasholenstein commented
> Nice idea! When I start IGV with `sh igv.sh` (no arguments), I get:
> 
> ```
> The IGV workspace in which the imported graphs are saved saved can be set as follows :
>   1) export IGV_WORKSPACE=path/to/workspace
>   2) ./igv.sh path/to/workspace
>   3) default is ./workspace
> 
> IGV workspace : /home/rocastan/git/views/JDK-8324950/open/src/utils/IdealGraphVisualizer/workspace
> ```
> 
> However, the actual workspace directory seems to be: `/home/rocastan/git/views/JDK-8324950/open/src/utils/IdealGraphVisualizer/application/target/userdir`
> 
> ![Screenshot from 2024-02-16 14-32-29](https://private-user-images.githubusercontent.com/8792647/305428820-6b1fc50d-5209-4963-88da-4fc9e005ad09.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxNzYwNjEsIm5iZiI6MTcwODE3NTc2MSwicGF0aCI6Ii84NzkyNjQ3LzMwNTQyODgyMC02YjFmYzUwZC01MjA5LTQ5NjMtODhkYS00ZmM5ZTAwNWFkMDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTdUMTMxNjAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTM2NzEwYWNkZjY5NWNkODkyYzdmNDA5NWM2YzQxOWY1NDg0ODg4ZGZkNzE3NTY1MjllMTc2MTIzODM3YzM5OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.gf5xWDeW858Ea0BLNOwvazfUcTvMbwdTgP6uPZ2UUzc)

You are right. There was a small mistake in the igv.sh script. It should work now

2024-02-26 09:21 UTC, turbanoff commented on src/utils/IdealGraphVisualizer/Coordinator/src/main/java/com/sun/hotspot/igv/coordinator/OutlineTopComponent.java
> +    static public String WORKSPACE_STATE_FILE = "state.igv";
Let's use blessed modifiers order
```suggestion
    public static String WORKSPACE_XML_FILE = "graphs.xml";
    public static String WORKSPACE_STATE_FILE = "state.igv";
```

2024-04-10 08:51 UTC, robcasloz commented
Hi Toby, this feature seems very useful, thanks for developing it! I very much prefer the current model that saves the state into the graph XML file compared to the original proposal. A few comments (this is not a full review yet):

- The export/import icons I see differ from those shown in the PR description:

![outline](https://github.com/openjdk/jdk/assets/8792647/946952d4-4ddc-495f-b5cd-22adf9721839)

- I find the distinction between 'Save' and 'Export' a bit unclear from a user perspective. My suggestion would be to either remove 'Export' (one can achieve the same result by removing the unnecessary graphs and then saving all remaining ones) or rename 'Save', 'Save as...', and 'Export' with 'Save all', 'Save all as...', and 'Save selected as...' (and using similar icons for the three), if that is the only difference between saving and exporting.

- It would be nice to make more tab-specific state persistent, for example which view is displayed (sea of nodes, CFG, etc.) or whether neighboring nodes of extracted nodes are shown. This could be done here or in a future RFE.

2024-04-10 10:38 UTC, tobiasholenstein commented
> Hi Toby, this feature seems very useful, thanks for developing it! I very much prefer the current model that saves the state into the graph XML file compared to the original proposal. A few comments (this is not a full review yet):
Thanks for the comments!
> * The export/import icons I see differ from those shown in the PR description:
> 
> ![outline](https://private-user-images.githubusercontent.com/8792647/321167807-946952d4-4ddc-495f-b5cd-22adf9721839.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NDQ3MjYsIm5iZiI6MTcxMjc0NDQyNiwicGF0aCI6Ii84NzkyNjQ3LzMyMTE2NzgwNy05NDY5NTJkNC00ZGRjLTQ5NWYtYjVjZC0yMmFkZjk3MjE4MzkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTBUMTAyMDI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTUyMzA4NWQ3NzljNGM3NDJhY2I0OGQzYTJmOGY1Zjg5MmVlODcwN2I5YmI3ODNmYWE5NzI2NzZkYzY0NDE0MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.x5VxRqOAxE-ZWBjP9GlmvJacfQBMgrY4tAMTvvUtSuE)

Strange. How did you checkout the PR? Seems like the newly added files `export.png` and `open.png` can not be found. (E.g. when applying as a patch like `git apply --index 8324950.diff` binary (png) files are not added) - Can you try:

_Checkout this PR locally:_
`$ git fetch https://git.openjdk.org/jdk.git pull/17630/head:pull/17630`
`$ git checkout pull/17630`

> * I find the distinction between 'Save' and 'Export' a bit unclear from a user perspective. My suggestion would be to either remove 'Export' (one can achieve the same result by removing the unnecessary graphs and then saving all remaining ones) or rename 'Save', 'Save as...', and 'Export' with 'Save all', 'Save all as...', and 'Save selected as...' (and using similar icons for the three), if that is the only difference between saving and exporting.
Right, I understand that it can be a bit unclear. I would suggest to drop the `Export` option and move `Import` next after `Open`:
<img width="200" alt="bar" src="https://github.com/openjdk/jdk/assets/71546117/3721ec57-cdad-4051-aefc-ec2cb41bebcc">

> * It would be nice to make more tab-specific state persistent, for example which view is displayed (sea of nodes, CFG, etc.) or whether neighboring nodes of extracted nodes are shown. This could be done here or in a future RFE.
Yes, this would be nice. Also IGV could reopen the last opened XML at startup. But I suggest a future RFE for this.

2024-04-10 11:38 UTC, robcasloz commented
> Strange. How did you checkout the PR? Seems like the newly added files export.png and open.png can not be found. (E.g. when applying as a patch like git apply --index 8324950.diff binary (png) files are not added) - Can you try:

My bad, I did check the PR out via a plain-text diff file.

> I would suggest to drop the Export option and move Import next after

Sounds good to me.

> Yes, this would be nice. Also IGV could reopen the last opened XML at startup. But I suggest a future RFE for this.

Fair enough :)

2024-04-10 13:22 UTC, robcasloz reviewed
Looks better, thanks! A couple of suggestions, for consistency between the File menu and the Outline icons.

2024-04-10 13:22 UTC, robcasloz commented on src/utils/IdealGraphVisualizer/Coordinator/src/main/java/com/sun/hotspot/igv/coordinator/actions/RemoveAllAction.java
> +        putValue(Action.SHORT_DESCRIPTION, "clear workspace");
```suggestion
        putValue(Action.SHORT_DESCRIPTION, "Clear workspace");
```

2024-04-10 13:22 UTC, robcasloz commented on src/utils/IdealGraphVisualizer/Coordinator/src/main/resources/com/sun/hotspot/igv/coordinator/actions/Bundle.properties
>  CTL_RemoveAllAction=Remove all graphs and groups
```suggestion
CTL_RemoveAllAction=Clear workspace
```

2024-04-10 13:41 UTC, robcasloz reviewed
When a graph file with several graphs is opened (e.g. [three-graphs.zip](https://github.com/openjdk/jdk/files/14932810/three-graphs.zip)), clicking on the tabs of the opened graphs does not highlight the corresponding entries in the Outline tree (as done when the graphs are freshly imported). Would it be possible to have the same behavior regardless of whether the displayed graphs are opened or imported?

2024-04-11 07:31 UTC, tobiasholenstein commented
> When a graph file with several graphs is opened (e.g. [three-graphs.zip](https://github.com/openjdk/jdk/files/14932810/three-graphs.zip)), clicking on the tabs of the opened graphs does not highlight the corresponding entries in the Outline tree (as done when the graphs are freshly imported). Would it be possible to have the same behavior regardless of whether the displayed graphs are opened or imported?

It should be fixed now. The entries in the Outline tree are computed lazily. So they don't exist until the folder is extended

2024-04-11 07:33 UTC, tobiasholenstein commented
I updated the PR: save the visibleNodes instead of the hiddenNodes. This is way more memory efficient. Especially for large graphs. 

PR is ready for review again!

2024-04-11 08:33 UTC, robcasloz commented
> It should be fixed now. The entries in the Outline tree are computed lazily. So they don't exist until the folder is extended

Thanks, that works for me now!

> I updated the PR: save the visibleNodes instead of the hiddenNodes. This is way more memory efficient. Especially for large graphs.

One issue with that is that now graphs are opened with a fixed set of visible nodes rather than "all nodes are visible". This works for the graph that is directly shown when the file is open, but if you step into the next graph in the group, new nodes will be hidden. To reproduce this, you can open [one-graph.zip](https://github.com/openjdk/jdk/files/14943396/one-graph.zip) and click on "Show next graph of current group". In the next graph, nodes 5, 7, 25, 26, and 27 are hidden unexpectedly.

One (hopefully simple) fix would be to show all nodes if `visibleNodes` is absent from the XML file or introduce an attribute to indicate that all nodes should be visible, something like:
```
<visibleNodes all="true">
</visibleNodes>
```
This would also lead to more compact XML files for graphs without hidden nodes.

Another solution would be to express the graph state as a chain of actions (e.g. `<showNode id="2"/>`, `<hideNode id="5"/>`, etc.). Then one could determine which chain of actions is more compact for a given graph state. This would also open for sending "commands" to IGV in the future, e.g. via gdb. But this is probably best left for future work.

2024-04-11 13:37 UTC, tobiasholenstein commented
> One issue with that is that now graphs are opened with a fixed set of visible nodes rather than "all nodes are visible". This works for the graph that is directly shown when the file is open, but if you step into the next graph in the group, new nodes will be hidden. To reproduce this, you can open [one-graph.zip](https://github.com/openjdk/jdk/files/14943396/one-graph.zip) and click on "Show next graph of current group". In the next graph, nodes 5, 7, 25, 26, and 27 are hidden unexpectedly.

I opted for your proposal introducing an attribute that indicates if all nodes should be visible:

- Show all nodes an ignore nodes in <visibleNodes> (should be empty anyways)
```xml
<visibleNodes all="true">
</visibleNodes>
```

- Show no nodes
```xml
<visibleNodes all="false">
</visibleNodes>
```

- Show only nodes "0"
```xml
<visibleNodes all="false">
<node id="0"/>
</visibleNodes>
```

2024-04-12 08:57 UTC, robcasloz commented
Thanks for addressing my questions and comments so far, Toby!

One more high-level question: currently, it seems the graph state is restored only for graphs from opened graph files, but not for graphs that are imported (e.g. from other graph files or from the network). Would it be hard to restore also the state from imported graphs? This is probably not a high-priority use case, but would be nice to e.g. enable sending graphs from gdb that are opened directly and where e.g. one node is highlighted.

2024-04-12 13:36 UTC, tobiasholenstein commented
> Thanks for addressing my questions and comments so far, Toby!
> 
> One more high-level question: currently, it seems the graph state is restored only for graphs from opened graph files, but not for graphs that are imported (e.g. from other graph files or from the network). Would it be hard to restore also the state from imported graphs? This is probably not a high-priority use case, but would be nice to e.g. enable sending graphs from gdb that are opened directly and where e.g. one node is highlighted.

If graphs are sent over the network with `<graphStates>` they are automatically opened. But this feature is currently not available in C2. Regarding manually importing a graph I prefer to not automatically open the Tabs.

2024-04-15 07:08 UTC, robcasloz commented
> If graphs are sent over the network with <graphStates> they are automatically opened. But this feature is currently not available in C2. Regarding manually importing a graph I prefer to not automatically open the Tabs.

I see, thanks for the clarification. I am fine with this decision, the main use case I see is for when graphs are imported over the network.

2024-04-15 09:01 UTC, robcasloz requested changes
There is an issue with saved difference graph states. If I open [diff.zip](https://github.com/openjdk/jdk/files/14976481/diff.zip) (which I just created by importing some graphs, opening one of them, and diffing it against another one), I get the following assertion error:
```
[INFO] java.lang.AssertionError
[INFO] 	at com.sun.hotspot.igv.util.RangeSliderModel.setPositions(RangeSliderModel.java:101)
[INFO] 	at com.sun.hotspot.igv.coordinator.OutlineTopComponent.lambda$loadContext$2(OutlineTopComponent.java:481)
[INFO] 	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
[INFO] 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
[INFO] 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
[INFO] 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
[INFO] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
[INFO] 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
[INFO] 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
[INFO] 	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
[INFO] [catch] at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
[INFO] 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
[INFO] 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
[INFO] 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
[INFO] 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
[INFO] 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
I imagine fully supporting saving and restoring the diff state would require quite a lot of additional complexity, both in IGV and in the XML files. Maybe this is not a very important use case, and we could just not support it?

2024-04-16 15:33 UTC, tobiasholenstein commented
> There is an issue with saved difference graph states. If I open [diff.zip](https://github.com/openjdk/jdk/files/14976481/diff.zip) (which I just created by importing some graphs, opening one of them, and diffing it against another one), I get the following assertion error:
> 
> ```
> [INFO] java.lang.AssertionError
> [INFO] 	at com.sun.hotspot.igv.util.RangeSliderModel.setPositions(RangeSliderModel.java:101)
> [INFO] 	at com.sun.hotspot.igv.coordinator.OutlineTopComponent.lambda$loadContext$2(OutlineTopComponent.java:481)
> [INFO] 	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
> [INFO] 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
> [INFO] 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
> [INFO] 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
> [INFO] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
> [INFO] 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
> [INFO] 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
> [INFO] 	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
> [INFO] [catch] at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
> [INFO] 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
> [INFO] 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
> [INFO] 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
> [INFO] 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> [INFO] 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
> ```
> 
> I imagine fully supporting saving and restoring the diff state would require quite a lot of additional complexity, both in IGV and in the XML files. Maybe this is not a very important use case, and we could just not support it?

Thanks for catching that! I fixed it. Difference graph are supported as long as they are in the same group. A difference graph from two different groups is just not saved to the xml.

2024-04-17 07:04 UTC, robcasloz commented
> Thanks for catching that! I fixed it. Difference graph are supported as long as they are in the same group. A difference graph from two different groups is just not saved to the xml.

Great, that works fine now, as far as I can see. A minor related issue is that difference graphs from two different groups are not closed when the workspace is cleared. Is this expected? I would intuitively expect them to be closed as well, but I guess one can also argue that they do not belong to the workspace.

2024-04-17 07:32 UTC, tobiasholenstein commented
> > Thanks for catching that! I fixed it. Difference graph are supported as long as they are in the same group. A difference graph from two different groups is just not saved to the xml.
> 
> Great, that works fine now, as far as I can see. A minor related issue is that difference graphs from two different groups are not closed when the workspace is cleared. Is this expected? I would intuitively expect them to be closed as well, but I guess one can also argue that they do not belong to the workspace.

Right. Implementation wise difference graphs from two groups are kind of a special case. But I agree the user would expect all tabs to be closed. Since we only ever have one workspace at the time, we can simply close all tabs when the workspace is closed - that's what I added in the latest commit. I think this is a good enough solution

2024-04-17 08:02 UTC, robcasloz approved these changes
Looks good!

2024-04-17 09:11 UTC, robcasloz approved these changes

2024-04-18 06:20 UTC, chhagedorn commented
That is a nice feature! I've tried the following out which does not seem to be working as expected:

1) Open graphs.xml -> opens with extracted nodes as shown in PR description
2) Click "Clear workspace"
3) Open graphs.xml again -> this time, it opens the entire graph without selection.

Same result when I completely restart IGV in step 2) instead.

2024-04-18 10:49 UTC, chhagedorn approved these changes
As discussed offline, the confusion was due to opening the tabs in a random order each time a file is opened. The fix now looks good.

Only a few minor comments - I'm not familiar with the code. I've dong some testing with IGV and the features seem to work. Great job!

2024-04-18 10:49 UTC, chhagedorn commented on src/utils/IdealGraphVisualizer/Coordinator/src/main/java/com/sun/hotspot/igv/coordinator/OutlineTopComponent.java
> +            this.requestActive();
`this` can probably be removed
```suggestion
            clearWorkspace();
            open(); // Reopen the OutlineTopComponent
            requestActive();
```

2024-04-18 10:49 UTC, chhagedorn commented on src/utils/IdealGraphVisualizer/Coordinator/src/main/java/com/sun/hotspot/igv/coordinator/OutlineTopComponent.java
> +        return false;
Could be simplified to:
```
frame.dispose();
return result == JOptionPane.YES_OPTION;
```

2024-04-18 10:49 UTC, chhagedorn commented on src/utils/IdealGraphVisualizer/Coordinator/src/main/java/com/sun/hotspot/igv/coordinator/OutlineTopComponent.java
> +        }
Can `path` really be `null` here?

2024-04-18 10:49 UTC, chhagedorn commented on src/utils/IdealGraphVisualizer/Data/src/main/java/com/sun/hotspot/igv/data/serialization/Parser.java
> +                    //  artificial "no block" block
```suggestion
                    // artificial "no block" block
```

2024-04-18 12:49 UTC, chhagedorn approved these changes
Looks good, thanks for the update!

2024-04-18 12:53 UTC, tobiasholenstein commented
Thanks for the reviews @robcasloz and @chhagedorn

/integrate

2024-04-18 12:53 UTC, closed without merging