JDK-8325037: x86: enable and fix hotspot/jtreg/compiler/vectorization/TestRoundVectFloat.java
openjdk/jdk pull request #17649
Opened 2024-01-31 10:09 UTC by Hamlin-Li

Hi,
Can you help to review this simple patch to fix test TestRoundVectFloat.java?
Thanks!

FYI: This test is not actually tested, need to fix the test applying filter and IR matching rule.

2024-01-31 11:37 UTC, TobiHartmann requested changes

2024-01-31 12:54 UTC, TobiHartmann approved these changes

2024-01-31 16:47 UTC, vnkozlov approved these changes
Good.

2024-02-01 10:37 UTC, jatin-bhateja commented on test/hotspot/jtreg/compiler/vectorization/TestRoundVectFloat.java
> +  @IR(applyIf = {"UseAVX", " > 1"}, counts = {IRNode.ROUND_VF , " > 0 "})
FTR, backend implementation of rounding first adds a broadcasted 0.5 value to incoming floating point vector lanes, register only flavor of broadcast operation is only supported by AVX2 targets. We can broadcast 0.5 into constant table emitted prior to method body to lift this limitation. Another concern is around different max vector size for floating point and integral vectors on AVX1 targets, 256 bit float vector vs 128 bit integral vector. Thus, a sharper check in match_rule_supported_vector (size_in_bits  > 128 && UseAVX < 2) should be added to support this for AVX1 targets as we are emitting an integral compare in special case handling for NaN and -/+0.0 / Inf.

2024-02-01 10:39 UTC, jatin-bhateja approved these changes

2024-02-01 11:00 UTC, Hamlin-Li commented
> I'll run this through our testing and report back once it passed.

Thanks for testing, I'll wait for your feedback.

2024-02-04 09:45 UTC, Hamlin-Li commented
@TobiHartmann @vnkozlov @jatin-bhateja Thanks for your revewiing!

/integrate

2024-02-04 09:46 UTC, closed without merging