8325134: Serial: Remove Generation::used_region
openjdk/jdk pull request #17673
Opened 2024-02-01 15:44 UTC by albertnetymk

Trivial removing dead code. The change of moving the definition to `tenuredGeneration.hpp` is needed to work around linking failure.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8325134](https://bugs.openjdk.org/browse/JDK-8325134): Serial: Remove Generation::used_region (**Enhancement** - P4)

### Reviewers
 * [Thomas Schatzl](https://openjdk.org/census#tschatzl) (@tschatzl - **Reviewer**)
 * [Ivan Walulya](https://openjdk.org/census#iwalulya) (@walulyai - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/17673/head:pull/17673` \
`$ git checkout pull/17673`

Update a local copy of the PR: \
`$ git checkout pull/17673` \
`$ git pull https://git.openjdk.org/jdk.git pull/17673/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17673`

View PR using the GUI difftool: \
`$ git pr show -t 17673`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/17673.diff">https://git.openjdk.org/jdk/pull/17673.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/17673#issuecomment-1921632344)

2024-02-01 16:12 UTC, tschatzl requested changes

2024-02-01 16:12 UTC, tschatzl commented on src/hotspot/share/gc/serial/tenuredGeneration.hpp
> +  MemRegion used_region() const { return space()->used_region(); }
This move requires inclusion of `space.hpp`.

Maybe it is better to move `save_used_region()` into the `.inline.hpp` file as well and include the `.inline.hpp` file where needed.

2024-02-03 08:28 UTC, tschatzl approved these changes

2024-02-05 10:31 UTC, walulyai approved these changes

2024-02-05 10:53 UTC, albertnetymk commented
Thanks for review.

/integrate

2024-02-05 10:54 UTC, closed without merging