8325168: JShell should support Markdown comments
openjdk/jdk pull request #17686
Opened 2024-02-02 14:02 UTC by lahodaj

2024-02-05 19:02 UTC, jonathan-gibbons commented
Compared to the previous PR, which was reasonably simple and quite elegant,
this one seems unduly complicated and somewhat invasive. It is also using
the transformer mechanism in a way that is not as intended. 

The `jdk.internal.md` module is intended to be for JDK support for Markdown.
As such, it has an imported copy of `commonmark-java` and now the new transformer
support, which is just intended to be used to support any JDK extensions to Markdown,
such as the new support for reference links for program elements. (There are 
suggestions for other future features in the JEP.) As such, I would 
expect all JDK clients to use the existing "standard" transformer, and to not 
substitute their own.  Ideally, the "standard" transformer would be used
by default, but I wanted to avoid an unconditional dependency from `jdk.compiler`
to `jdk.internal.md` -- so hence the use of the service provider mechanism.
(I guess I could update `jdk.compiler` to use `requires static` to establish
a compile-time dependency on the `jdk.internal.md` module, and then try
and install the standard transformer, which would always be available if we
put a hard dependency in modules like `jdk.javadoc` and `jdk.jshell`.)

Your previous PR was pretty good (although I accept we did not get as far as
a full review and approval.)  The recent changes the overall Markdown work
were made with that PR in mind.  As such, the intention was that only two
fairly small changes would be required.

1. Change the means to detect Markdown comments, from looking for `/**md`
   to using the new `CommentKind` support in `DocTrees`.
2. Install the 'standard' transformer, to enable the JDK extensions to
   Markdown

With those two changes, you can use the previous technique to parse and 
render a Markdown doc comment as before.

2024-02-05 20:23 UTC, jonathan-gibbons requested changes

2024-02-06 07:13 UTC, lahodaj commented
Thanks for the comments! I've dropped the `ToHTML` transformer, and made the transformations easier. Sadly, the standard transformer seems to break raw text tree positions, so it is not currently possible to properly replace the Markdown text with the Javadoc text when the transformer is installed. Please see:
https://github.com/openjdk/jdk/pull/16388#discussion_r1479306878
for more details. Once that is solved, it should be possible to merge the newest changes in the Markdown branch.

2024-05-31 20:36 UTC, jonathan-gibbons approved these changes
I'll approve it for what it is.

There are some minor comments about imports and tests; these can either be fixed here in this PR, or in cleanup tasks before RDP2.

It is disappointing but not surprising to see duplication of somewhat similar code in the `jdk.javadoc` module, especially the handling of Markdown code. This just adds to the duplication of effort interpreting other aspects of doc comments. I understand how we got to this point, but down the road, we should look to share more code, translating doc comments into some intermediate representation (such as the HTML classes currently in  `jdk.javadoc.internal.doclets.formats.html.markup`) such that we only need minimal subsequent conversion to a near-text form., like ANSI-styled text. That would be a good layer of abstraction to have in the `jdk.javadoc` module anyway, and if we can expose it (internally?) to other JDK modules, to support their use and display of doc comments, so much the better: we all win.

2024-05-31 20:36 UTC, jonathan-gibbons commented on src/jdk.jshell/share/classes/jdk/internal/shellsupport/doc/JavadocHelper.java
> +                        //this links is a synthetic rewritten link, replace
spelling `this link`

2024-06-04 11:54 UTC, lahodaj commented
/integrate

2024-06-04 11:54 UTC, closed without merging