8325081
openjdk/jdk pull request #17693
Opened 2024-02-03 07:54 UTC by LizBing

trivial

2024-02-03 14:32 UTC, kimbarrett requested changes
In the constructor for CollectedHeap, I'd like the newly added `_soft_ref_policy` to
be explicitly initialized, rather than relying on implicit member initialization.  That is,
add a mem-initializer to the mem-initializer-list of that constructor.

2024-02-05 15:56 UTC, kimbarrett approved these changes
Looks good (and agree with @tschatzl about not trivial, but that doesn't matter now).

Also, for future reference, I think the PR description ought to provide more
information than was provided here.

2024-02-05 17:48 UTC, LizBing commented
thanks for the review.
/integrate

2024-02-06 01:05 UTC, kimbarrett commented
/sponsor

2024-02-06 01:06 UTC, closed without merging