8321192 : j.a.PrintJob/ImageTest/ImageTest.java: Fail or skip the test if there's no printer
openjdk/jdk pull request #17790
Opened 2024-02-09 14:59 UTC by Renjithkannath

Hi Reviewers,
I have updated the test with 'PassFailJFrame' with programmatically generating image and print , please review and let me know your suggestions.

2024-02-09 15:19 UTC, aivanov-jdk approved these changes
Should we mark `paint` and `imageUpdate` with `@Override` annotation?

Overall, looks good to me.

2024-02-09 15:19 UTC, aivanov-jdk commented on test/jdk/java/awt/PrintJob/ImageTest/ImageTest.java
> +import java.awt.Button;
Usually, `javax.*` packages are below `java.*` packages.

2024-02-09 15:19 UTC, aivanov-jdk commented on test/jdk/java/awt/PrintJob/ImageTest/ImageTest.java
> +        public void setPrintJob(PrintJob pj) {
Can be make `private`.

2024-02-09 15:19 UTC, aivanov-jdk commented on test/jdk/java/awt/PrintJob/ImageTest/ImageTest.java
> +        f.setBounds(0, 50, 700, 350);
```suggestion
        f.setSize(700, 350);
```
The position is determined by `PassFailJFrame`.

2024-02-09 16:05 UTC, aivanov-jdk commented on test/jdk/java/awt/PrintJob/ImageTest/ImageTest.java
> +                    + " Test cannot continue.");
```suggestion
            throw new SkippedException("Printer not configured or available.");
```
We decided to shorten the message. Let's keep it consistent.

2024-02-09 19:11 UTC, prrace commented
I thought SkippedException looks like a "pass" too ?
What is effectively different by using it here ?
If the @printer keyword is there, then let's educate people that there MUST be a printer by making the test fail or if possible report a jtreg "error".  Not sure if that is possible, error is usually timeout and things like that.

2024-02-09 19:27 UTC, aivanov-jdk commented
> I thought SkippedException looks like a "pass" too ?  
> What is effectively different by using it here ?

No, it's not. If a test throws `jtreg.SkippedException`, then it's reported as **skipped**. It is neither a failure nor a success — it indicates the prerequisites aren't met.

> If the @printer keyword is there, then let's educate people that there MUST be a printer by making the test fail or if possible report a jtreg "error". Not sure if that is possible, error is usually timeout and things like that.

That's exactly what `jtreg.SkippedException` does: it's a configuration / environment error.

Most printer tests already have such a condition. Previously, each test behaved as if the test passed even though it wasn't even run.

The `jtreg.SkippedException` changes the status which comes out as a distinct one from either *pass* or *fail*.

Do you think this check should be removed completely? Yes, it is somewhat redundant: the test with `@key printer` should not be started in an environment where there's no printer.

2024-02-09 19:38 UTC, aivanov-jdk commented
> > I thought SkippedException looks like a "pass" too ?
> > What is effectively different by using it here ?
> 
> No, it's not. If a test throws `jtreg.SkippedException`, then it's reported as **skipped**. It is neither a failure nor a success — it indicates the prerequisites aren't met.

**jtreg FAQ: [What if a test does not apply in a given situation?](https://openjdk.org/jtreg/faq.html#what-if-a-test-does-not-apply-in-a-given-situation)**

“While `@modules` and `@requires` will cover many cases, there may be cases where the determination of whether the test is applicable needs to be determined by the test itself. For example, a test may want to check the presence of a shared library containing compiled native code, and to skip the main body of the test if the library is not available. <em>In such cases, a test may throw an exception named `jtreg.SkippedException`. […] This exception will be treated specially: unlike for any other exception, the test will be deemed to have passed, but the reason will be set to a message saying that the test was skipped instead of executing normally.</em>”

@prrace Does it explain `jtreg.SkippedException`?

However, `@key printer` also covers the condition in this case.

2024-02-09 20:01 UTC, prrace commented
> > > I thought SkippedException looks like a "pass" too ?
> > > What is effectively different by using it here ?
> > 
> > 
> > No, it's not. If a test throws `jtreg.SkippedException`, then it's reported as **skipped**. It is neither a failure nor a success — it indicates the prerequisites aren't met.
> 
> **jtreg FAQ: [What if a test does not apply in a given situation?](https://openjdk.org/jtreg/faq.html#what-if-a-test-does-not-apply-in-a-given-situation)**
> 
> “While `@modules` and `@requires` will cover many cases, there may be cases where the determination of whether the test is applicable needs to be determined by the test itself. For example, a test may want to check the presence of a shared library containing compiled native code, and to skip the main body of the test if the library is not available. _In such cases, a test may throw an exception named `jtreg.SkippedException`. […] This exception will be treated specially: unlike for any other exception, the test will be deemed to have passed, but the reason will be set to a message saying that the test was skipped instead of executing normally._”
> 
> @prrace Does it explain `jtreg.SkippedException`?
> 
> However, `@key printer` also covers the condition in this case.

"the test will be deemed to have passed" is not what we want.
We want it to fail. So don't run these tests unless you have a printer. Otherwise we might as well leave the test as it is.

I see no point in using SkippedException in any of the printer tests unless there's some test-specific circumstance I can't think of.

2024-02-09 20:04 UTC, prrace commented
> However, @key printer also covers the condition in this case.

Yes, if we didn't have a keyword, then it would be less reasonable to fail the test.
Like if a test requires multimon, and we don't have a keyword to support filtering such tests, THEN SkippedException might be reasonable.

Also adding that exception means you can't run without the jtreg framework, unless you provide the class as part of the test itself. I mean something has to provide that class.

2024-02-11 19:38 UTC, prrace commented
I had a slack chat with Jon Gibbons (maintainer of jtreg) and he thinks FAIL would be better here.
I think we should be consistent and now that all tests that need a printer specify @key printer - 
should FAIL if there's no printer. Not saying we have to rush off and change them all immediately,
but if we are updating it anyway for some reason then do it.

2024-02-12 19:31 UTC, aivanov-jdk commented
@prrace You're right. I was under impression that `jtreg.SkippedException` gives the test a distinct status from either *Pass* or *Fail*. Eventually, it's not the case.

In verbose mode, I can see the exception:

```text
runner starting test: java/awt/PrintJob/test/FailedTest.java
runner finished test: java/awt/PrintJob/test/FailedTest.java
Failed. Execution failed: `main' threw exception: java.lang.Error: Fail the test
runner starting test: java/awt/PrintJob/test/PassedTest.java
runner finished test: java/awt/PrintJob/test/PassedTest.java
Passed. Execution successful
runner starting test: java/awt/PrintJob/test/SkippedTest.java
runner finished test: java/awt/PrintJob/test/SkippedTest.java
Passed. Skipped: jtreg.SkippedException: Skip the test
Test results: passed: 2; failed: 1
```
This is why I thought it was recorded as a different status.

At the same time, the report looks like this:
```text
==============================
Test summary
==============================
   TEST                                              TOTAL  PASS  FAIL ERROR   
>> jtreg:open/test/jdk/java/awt/PrintJob/test            3     2     1     0 <<
==============================
TEST FAILURE
```

If `jtreg.SkippedException` resulted in a status distinct from *Pass* or *Fail*, it would be more useful.

2024-02-12 19:35 UTC, aivanov-jdk commented
What would be the best option to handle a missing printer?

1. Throw a `RuntimeException` or `Error` indicating there's no printer available?
2. Let the test fail with whatever error it may fail when there's no printer?

I'm inclined towards the first option — it gives a clear indication of the error.

2024-02-12 19:46 UTC, aivanov-jdk requested changes

2024-02-12 19:46 UTC, aivanov-jdk commented on test/jdk/java/awt/PrintJob/ImageTest/ImageTest.java
> +                    + " Test cannot continue.");
As per the above discussion, fail the test if there's no printer.

```suggestion
        if (PrinterJob.lookupPrintServices().length == 0) {
            throw new RuntimeException("Printer not configured or available.");
```

2024-02-15 15:45 UTC, aivanov-jdk approved these changes
Looks good except for minor comment: remove `/test/lib` from the libraries.

2024-02-15 15:45 UTC, aivanov-jdk commented on test/jdk/java/awt/PrintJob/ImageTest/ImageTest.java
> + * @library /java/awt/regtesthelpers /test/lib
```suggestion
 * @library /java/awt/regtesthelpers
```
The `/test/lib` library isn't used any more.

2024-02-19 06:33 UTC, TejeshR13 approved these changes
Looks good to me.

2024-02-22 06:48 UTC, Renjithkannath commented
/integrate

2024-02-22 10:44 UTC, aivanov-jdk commented on test/jdk/java/awt/PrintJob/ImageTest/ImageTest.java
> + * @library /java/awt/regtesthelpers /test/lib
@Renjithkannath Please remove `/test/lib` from the list of libraries before integrating.

2024-02-22 13:48 UTC, Renjithkannath commented
/integrate

2024-02-22 14:03 UTC, aivanov-jdk approved these changes

2024-02-22 14:04 UTC, aivanov-jdk commented
/sponsor

2024-02-22 14:05 UTC, closed without merging