8325635
openjdk/jdk pull request #17807
Opened 2024-02-12 12:57 UTC by albertnetymk

Trivial signature update.

2024-02-12 13:16 UTC, stefank approved these changes
Looks good.

Though it is not clear to me that it is worth having a separate function for this instead of just inlining this code into scan_old_to_young_ref. I was wondering what the name `verify_used_region_at_save_marks` meant and why it was taking a TenuredSpace. It made more sense when I read the code in conjuncture with the caller.

2024-02-12 14:07 UTC, stefank requested changes

2024-02-12 14:07 UTC, stefank commented on src/hotspot/share/gc/serial/cardTableRS.cpp
> +#endif
Having the ASSERT blocks makes this code messier than it have to be, IMHO. I would prefer if this was changed to:
```
void CardTableRS::scan_old_to_young_refs(TenuredSpace* sp) {
  const MemRegion ur    = sp->used_region();
  const MemRegion urasm = sp->used_region_at_save_marks();

  assert(ur.contains(urasm),
         "Did you forget to call save_marks()? "
         "[" PTR_FORMAT ", " PTR_FORMAT ") is not contained in "
         "[" PTR_FORMAT ", " PTR_FORMAT ")",
         p2i(urasm.start()), p2i(urasm.end()), p2i(ur.start()), p2i(ur.end()));

  if (!urasm.is_empty()) {
    OldGenScanClosure cl(SerialHeap::heap()->young_gen());
    non_clean_card_iterate(sp, urasm, &cl);
  }
}
```

2024-02-12 14:47 UTC, stefank approved these changes

2024-02-13 08:45 UTC, albertnetymk commented
Thanks for review.

/integrate

2024-02-13 08:47 UTC, closed without merging