8325860
openjdk/jdk pull request #17844
Opened 2024-02-14 13:15 UTC by albertnetymk

Relocate `Generation.java` to mirror the structure in hotspot. Also, specialize the logic to two concrete generations.

Test: tier1-3

2024-02-14 20:01 UTC, plummercj requested changes
TestUniverse.java needs a copyright update.

2024-02-14 20:32 UTC, plummercj approved these changes
Looks good. Thanks for the cleanup.

2024-02-15 09:21 UTC, tschatzl approved these changes

2024-02-15 10:19 UTC, albertnetymk commented
Thanks for review.

/integrate

2024-02-15 10:20 UTC, closed without merging