8324849: Uniform use of synchronizations in NMT
openjdk/jdk pull request #18000
Opened 2024-02-26 07:41 UTC by afshin-zafari

In NMT, both `ThreadCritical` and `Tracker` objects are used to do synchronizations. `Tracker` class uses `ThreadCritical` internally and used only for uncommit and release memory operations.  In this change, `Tracker` class is replaced with explicit use of `ThreadCritical` to be the same as the other instances of sync'ing NMT operations.

tiers1-5 tests passed.

2024-02-26 11:22 UTC, tstuefe approved these changes
+1. Yes, please.

2024-02-26 14:38 UTC, tstuefe commented
BTW, since you are here, and if @jdksjolen agrees:

Could we rename VirtualMemoryTracker::remove_uncommitted_region to something else (e.g. VirtualMemoryTracker::remove_committed_region or VirtualMemoryTracker::uncommit_region)? I always start wondering when reading this function name, since we don't remove an uncommitted region, we uncommit a region resp. remove a committed region.

2024-02-26 17:55 UTC, vnkozlov requested changes
@afshin-zafari  Please, set correct RFE id number!!!!  See "Integration blockers" and "Issue".

2024-02-26 18:40 UTC, tstuefe commented
> @afshin-zafari  Please, set correct RFE id number!!!!  See "Integration blockers" and "Issue".

ow. But Skara bot did not catch this? How strange.

2024-02-26 19:30 UTC, vnkozlov commented
> > @afshin-zafari  Please, set correct RFE id number!!!!  See "Integration blockers" and "Issue".
> 
> ow. But Skara bot did not catch this? How strange.

It catch - It will not allow you to integrate until you resolve "Integration blockers".

Yes, it would be better if Skara does not allow to create such PR but I am not sure Skara does these checks at that time.

2024-02-26 19:37 UTC, kevinrushforth commented
FWIW, the correct bug ID is "8324829"

2024-02-27 05:48 UTC, tstuefe commented
> > > @afshin-zafari  Please, set correct RFE id number!!!!  See "Integration blockers" and "Issue".
> > 
> > 
> > ow. But Skara bot did not catch this? How strange.
> 
> It catch - It will not allow you to integrate until you resolve "Integration blockers".
> 
> Yes, it would be better if Skara does not allow to create such PR but I am not sure Skara does these checks at that time.

Ah, okay. It would be cool for jcheck to pick this up and show an error in GHAs though. That way you notice it immediately.

2024-02-27 09:12 UTC, afshin-zafari commented
> Could we rename VirtualMemoryTracker::remove_uncommitted_region to something else (e.g. VirtualMemoryTracker::remove_committed_region or VirtualMemoryTracker::uncommit_region)? I always start wondering when reading this function name, since we don't remove an uncommitted region, we uncommit a region resp. remove a committed region.

The `VirtualMemoryTracker` (VMT) API is used internally by the NMT itself. The `MemTracker` API are the ones used by other hotspot code. The *remove* in `VirtualMemoryTracking::remove_uncommitted_region` refers to editing of the linked list and not referring to the memory operations. When we uncommit a region we call `MemTracker::record_virtual_memory_uncommit` for recording that in NMT which is meaningful and correct. VMT APIs are not called/used by non-NMT hotspot code.

2024-02-29 08:38 UTC, afshin-zafari commented
@tstuefe and @jdksjolen, if you agree on keeping the method name as it is, then I can integrate this PR.

2024-02-29 09:41 UTC, jdksjolen approved these changes
I'm fine with this being merged either way, @afshin-zafari

2024-03-01 14:56 UTC, tstuefe commented
Sure. Ship it.

2024-03-04 08:17 UTC, afshin-zafari commented
Thank you @tstuefe and @jdksjolen for your comments.
Thank you @kevinrushforth and @vnkozlov for your catch and help on fixing the issue number.
/integrate

2024-03-04 08:18 UTC, closed without merging