8326763
openjdk/jdk pull request #18022
Opened 2024-02-27 09:46 UTC by albertnetymk

Trivial inlining and removing some unused methods.

2024-02-27 09:59 UTC, stefank requested changes

2024-02-27 09:59 UTC, stefank commented on src/hotspot/share/gc/shared/space.cpp
> -void ContiguousSpace::print() const { print_on(tty); }
It is a common pattern in HotSpot to have a `print()` function that delegates to `print_on(tty)`. I think this function should be kept.

2024-02-28 13:23 UTC, lgxbslgx approved these changes
Looks good.

2024-02-28 15:04 UTC, stefank approved these changes

2024-02-28 15:07 UTC, albertnetymk commented on src/hotspot/share/gc/shared/space.cpp
> +  st->print_cr(" space %zuK, %3d%% used [" PTR_FORMAT ", " PTR_FORMAT ", " PTR_FORMAT ")",
`%zu` is shorter and easier to read, and it's widely used in new code; `SIZE_FORMAT` is used in old code when we didn't have `%zu`.

2024-02-28 15:08 UTC, lgxbslgx commented on src/hotspot/share/gc/shared/space.cpp
> +  st->print_cr(" space %zuK, %3d%% used [" PTR_FORMAT ", " PTR_FORMAT ", " PTR_FORMAT ")",
Got it. Thanks for your explanation.

2024-02-28 15:14 UTC, albertnetymk commented
Thanks for review.

/integrate

2024-02-28 15:14 UTC, closed without merging