8327057
openjdk/jdk pull request #18065
Opened 2024-02-29 15:00 UTC by albertnetymk

Simplifying bitmap iterate logic in full-gc compaction to reduce possible outcomes callers must handle.

Test: tier1-6

2024-03-01 10:46 UTC, tschatzl requested changes

2024-03-01 10:46 UTC, tschatzl commented on src/hotspot/share/gc/parallel/parMarkBitMap.cpp
> -      live_closure->set_source(bit_to_addr(cur_beg));
The caller of `iterate` expects `live_closure->source()` to be set at exit. It is in used.

This is not the case for the `iterate` taking two closures afaict, but nevertheless it seems part of the contract so it is surprising if some methods do and some do not.

The other changes seem to be okay.

2024-03-01 11:04 UTC, tschatzl commented on src/hotspot/share/gc/parallel/parMarkBitMap.cpp
> -      live_closure->set_source(bit_to_addr(cur_beg));
@albertnetymk mentioned that `do_addr` of `MarkAndUpdateClosure` properly updates the `source` of the closure.

2024-03-01 11:04 UTC, tschatzl approved these changes

2024-03-04 15:30 UTC, walulyai approved these changes

2024-03-04 18:50 UTC, albertnetymk commented
Thanks for review.

/integrate

2024-03-04 18:50 UTC, closed without merging