8327046: (fs) Files.walk should be clear that depth-first traversal is pre-order
openjdk/jdk pull request #18063
Opened 2024-02-29 12:56 UTC by pavelrappo

Please review this clarification to the specification of the two overloads of `java.nio.file.Files.walk`. No tests are added, as I believe the existing `StreamTest.testWalk*` methods already test the order sufficiently. I also took this opportunity to fix a few minor typos.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8327046](https://bugs.openjdk.org/browse/JDK-8327046): (fs) Files.walk should be clear that depth-first traversal is pre-order (**Bug** - P4)

### Reviewers
 * [Alan Bateman](https://openjdk.org/census#alanb) (@AlanBateman - **Reviewer**) ⚠️ Review applies to [5ffccf38](https://git.openjdk.org/jdk/pull/18063/files/5ffccf3867827ea606cdd90048c639f4a231a1a2)
 * [Guoxiong Li](https://openjdk.org/census#gli) (@lgxbslgx - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18063/head:pull/18063` \
`$ git checkout pull/18063`

Update a local copy of the PR: \
`$ git checkout pull/18063` \
`$ git pull https://git.openjdk.org/jdk.git pull/18063/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18063`

View PR using the GUI difftool: \
`$ git pr show -t 18063`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18063.diff">https://git.openjdk.org/jdk/pull/18063.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18063#issuecomment-1971093834)

2024-02-29 13:46 UTC, AlanBateman commented
Your proposed wording is okay but it makes me wonder if we now need to define "pre-order" as it is new term here. An alternative is something like this:

"The file tree traversal is depth-first with a directory visited before the entries in the directory."

which will align it closely to the existing wording in walkFileTree and FileVisitor.

2024-02-29 15:20 UTC, AlanBateman approved these changes

2024-03-01 07:52 UTC, lgxbslgx requested changes
A trivial issue about the name.

2024-03-01 07:52 UTC, lgxbslgx commented on test/jdk/java/nio/file/Files/StreamTest.java
> +    static Path[] all_followLinks;
The name `all_followLinks`, which contains the underline and the lower camel case, is strange. What about `allFollowLinks`?

2024-03-01 10:27 UTC, lgxbslgx approved these changes
Looks good.

2024-03-01 13:48 UTC, pavelrappo commented
/integrate

2024-03-01 13:48 UTC, closed without merging