8327176: UnreferencedExecutor.java can fail on libgraal with -Xcomp
openjdk/jdk pull request #18098
Opened 2024-03-03 17:01 UTC by dougxc

The `java/util/concurrent/Executors/UnreferencedExecutor.java` test can fail when run on libgraal and `-Xcomp` is specified. The problem appears to be that libgraal temporarily causes some objects that the test expects to be weakly referenced to have strong roots for a short amount of time (i.e. while a libgraal referencing these objects is in progress).

Installing a global `Thread.UncaughtExceptionHandler` that ignores `OutOfMemoryError`s resolves the problem.

2024-03-03 17:03 UTC, dougxc commented
I confirmed that `java/util/concurrent/Executors/UnreferencedExecutor.java` still fails if the [fix applied to ThreadContainers.java](https://github.com/openjdk/jdk/commit/ada416e66cbff6c8e631bf352acc0744c248740b#diff-1e347b9a95cc4fe81a01ca70e4122a73a65d99a69668c7567abb2a6067f8cc6dL68) is reverted.

2024-03-21 05:38 UTC, dholmes-ora requested changes

2024-03-21 05:38 UTC, dholmes-ora commented on test/jdk/java/util/concurrent/Executors/UnreferencedExecutor.java
> +        }
I'm not clear exactly what you are trying to achieve with this - is it just to not print the stacktrace when OOME occurs?

A UEH should not rethrow exceptions as they are effectively ignored as we are already at the final level of handling exceptions (the VM will print a one line warning if a UEH itself throws). If I understand what you want then I think the following would be more correct:
```
// Ignore OOME but do default handling for any other uncaught exception.
public void uncaughtException(Thread t, Throwable e) {
    if ( ! e instanceof OutOfMemoryError) {
        System.err.print("Exception in thread \"" + t.getName() + "\" ");
        e.printStackTrace(System.err);
    }
}
```

This doesn't stop the thread from terminating of course - the OOME already caused it to unwind its stack if we get this far.

2024-03-21 07:41 UTC, AlanBateman commented
@dougxc I added this test when fixing JDK-8308235. The point of the test is that OOME is not thrown so adding a default UEH to ignore OOME is changing the test. I wonder if this is a test that just needed to be skipped with libgraal.

2024-03-21 09:11 UTC, dougxc commented
> @dougxc I added this test when fixing JDK-8308235. The point of the test is that OOME is not thrown so adding a default UEH to ignore OOME is changing the test. I wonder if this is a test that just needed to be skipped with libgraal.

I understood the point of that test to be that an OOME does not cause the VM to exit. As i mentioned (https://github.com/openjdk/jdk/pull/18098#issuecomment-1975231258), the test still detects the memory leak plugged by JDK-8308235.

That said, I have tried to reproduce the failure on a more recent libgraal and JDK build and am having no luck. I'll close this PR and come up with alternative solutions if the failure starts reappearing.

2024-03-21 09:11 UTC, closed without merging