8327361: Update some comments after JDK-8139457
openjdk/jdk pull request #18120
Opened 2024-03-05 11:06 UTC by rkennke

A follow-up to [8139457: Relax alignment of array elements](https://bugs.openjdk.org/browse/JDK-8139457) ([PR](https://git.openjdk.org/jdk/pull/11044)), some comments need an update.

2024-03-05 11:08 UTC, rkennke commented
/reviewers 1 galderz

2024-03-05 11:33 UTC, galderz requested changes
I think the changes look fine, but looking closer to the original PR, src/hotspot/cpu/riscv/c1_MacroAssembler_riscv.hpp might also need adjusting. s390 and ppc are probably just fine.

2024-03-07 14:37 UTC, rkennke commented
@galderz is it ok now? I assume it counts as trivial, too?

2024-03-12 05:32 UTC, galderz approved these changes

2024-03-12 05:32 UTC, galderz commented
@rkennke Yeah, ok now. Trivial too.

2024-03-12 12:00 UTC, shipilev approved these changes

2024-03-12 12:05 UTC, rkennke commented
Thanks!
/integrate

2024-03-12 12:08 UTC, closed without merging