8327365
openjdk/jdk pull request #18122
Opened 2024-03-05 11:47 UTC by albertnetymk

Simple refactoring to move a field from superclass to subclass.

2024-03-05 15:14 UTC, lgxbslgx requested changes
Looks good.

2024-03-05 15:14 UTC, lgxbslgx commented on src/hotspot/share/gc/serial/generation.hpp
>    virtual void update_gc_stats(Generation* current_generation, bool full) {}
The method `update_gc_stats` here can be removed and the method `update_gc_stats` in `tenuredGeneration.hpp` can be non-virtual.

2024-03-05 15:27 UTC, lgxbslgx approved these changes
Looks good.

2024-03-06 08:04 UTC, tschatzl commented
There is no more `GCStats` use in serial gc, all references to it in `generation.hpp` and `tenuredGeneration.hpp` can be removed (forward decl, include).
Also `GCStats` files can be moved to the `parallel` directory.

Tbh, similar to serial gc, `GCStats` could be replaced by the `AdaptivePaddedNoZeroDevAverage` class in Parallel GC too and completely removed. I.e. imo either both or none of these replacements should be done.

2024-03-06 09:26 UTC, albertnetymk commented
I think `GCStats` can be inlined in Parallel as well. That is independent of this PR (Serial-only), so I left it out here.

2024-03-06 10:50 UTC, lgxbslgx approved these changes

2024-03-06 10:51 UTC, albertnetymk commented
Included both Serial and Parallel in the latest revision.

2024-03-06 12:07 UTC, tschatzl approved these changes
Lgtm.

`_avg_promoted` does not need to be a reference I think, but that can be changed separately potentially together with the other statistics.

2024-03-06 13:03 UTC, albertnetymk commented
Thanks for review.

/integrate

2024-03-06 13:04 UTC, closed without merging