8326333: jshell <TAB> completion on arrays is incomplete
openjdk/jdk pull request #18163
Opened 2024-03-08 08:40 UTC by lahodaj

Inside jshell, arrays don't show `Object` method in array code completion, i.e.:
```
jshell> String[] arr = null;
arr ==> null

jshell> arr.<code-completion-here>
```

will only show `length`. This patch adds `j.l.Object` methods to the suggestions for arrays.

2024-03-09 04:54 UTC, lgxbslgx requested changes
The copyright of `SourceCodeAnalysisImpl.java` needs to be adjusted too. Thanks.

2024-03-09 04:54 UTC, lgxbslgx commented on test/langtools/jdk/jshell/CompletionSuggestionTest.java
> +    //JDK-8326333
Such simple bug-id seems unnecessary or uncomplete.  It is better to privode some description content.

2024-03-14 13:28 UTC, vicente-romero-oracle approved these changes
lgtm

2024-03-18 08:24 UTC, lahodaj commented
/integrate

2024-03-18 08:25 UTC, closed without merging