8258584: java/util/HexFormat/HexFormatTest.java fails on x86_32
openjdk/jdk pull request #1817
Opened 2020-12-17 12:11 UTC by DamonFool

Hi all,

java/util/HexFormat/HexFormatTest.java fails on x86_32 due to '-Xmx4G'.
The reason is that -Xmx4G is invalid maximum heap size for 32-bit platforms.
The current implementation only supports maximum 3800M on 32-bit systems [1].

I've tried to reduce the -Xmx size, but it still fails even with -Xmx2G.
So this test seems to be brittle on 32-bit platforms since 2G is already larger than 3800M/2=1900M.
The fix just skips the test for 32-bit systems.

Thanks.
Best regards,
Jie

[1] https://github.com/openjdk/jdk/blob/master/src/hotspot/os/posix/os_posix.cpp#L567

2020-12-17 12:11 UTC, DamonFool commented
/issue add JDK-8258584
/test
/label add core-libs
/cc core-libs

2020-12-17 16:14 UTC, RogerRiggs requested changes
Disabling all of the tests on 32 bit is not a good idea.

Instead the HexFormatTest.testOOME test should be skipped or the OOME should be ignored.
Checking Runtime.getRuntime().maxMemory() should provide enough info to skip it.

2020-12-19 09:44 UTC, DamonFool commented
> Disabling all of the tests on 32 bit is not a good idea.
> 
> Instead the HexFormatTest.testOOME test should be skipped or the OOME should be ignored.
> Checking Runtime.getRuntime().maxMemory() should provide enough info to skip it.

Thanks @RogerRiggs for your review and comments.
Let's ignore the OOME for testOOME.
What do you think of the updated change?
Thanks.

2020-12-21 15:34 UTC, RogerRiggs requested changes
Completely ignoring the exception will leave no trace that the test was skipped or why.
Please retain the printing of the memory limits and instead of rethrowing the oome add:
```throw new SkipException("Insufficient Memory to test OOME");```
(It will need an import of org.testng.SkipException).
Throwing SkipException will flag the test as being skipped in the Jtreg summary.

2020-12-21 23:36 UTC, DamonFool commented
> Completely ignoring the exception will leave no trace that the test was skipped or why.
> Please retain the printing of the memory limits and instead of rethrowing the oome add:
> `throw new SkipException("Insufficient Memory to test OOME");`
> (It will need an import of org.testng.SkipException).
> Throwing SkipException will flag the test as being skipped in the Jtreg summary.

Updated.
Thanks for your help.

2020-12-21 23:38 UTC, RogerRiggs approved these changes
Looks fine.  Thanks

2020-12-22 02:07 UTC, DamonFool commented
/integrate

2020-12-22 02:07 UTC, closed without merging