8327946: containers/docker/TestJFREvents.java fails when host kernel config vm.swappiness=0 after 8325139
openjdk/jdk pull request #18225
Opened 2024-03-12 09:06 UTC by sendaoYan

According to the docker document(https://docs.docker.com/config/containers/resource_constraints/#--memory-swappiness-details), the default value of --memory-swappiness is inherited from the host machine. So, when the the kervel config vm.swappiness=0 on the host machine, this testcase will fail, because of docker container can not use swap memory, the deafult value of --memory-swappiness is 0.

2024-03-14 02:04 UTC, sendaoYan commented
Fix the testcase bug, the risk is low. Can anyone reivew this PR, thanks.

2024-04-11 06:23 UTC, sendaoYan commented
Fix the testcase bug, the risk is low. Can anyone reivew this PR, thanks.

2024-04-11 09:51 UTC, jerboaa requested changes
`--memory-swappiness` is cgv1 specific and needs to be handled for the cgv2 case.

2024-04-11 15:36 UTC, sendaoYan commented on test/hotspot/jtreg/containers/docker/TestJFREvents.java
> +                                      .addDockerOpts("--memory-swappiness=60")
Thanks for your review. The space after `//` has been added.

I can't reproduce the "OCI runtime error" failure on mine ubuntu22 environment.
It seems that ubuntu22 use cgroups v2 by default.
![image](https://github.com/openjdk/jdk/assets/24123821/d41934fe-afb4-45a7-abd4-df4070123bb2)

Can you show your host machine enviroment information, so I can reproduce the same failure. After that I will try to find a solution with cgroupv2.

2024-04-11 15:49 UTC, jerboaa commented on test/hotspot/jtreg/containers/docker/TestJFREvents.java
> +                                      .addDockerOpts("--memory-swappiness=60")
It seems to be podman runtime specific. `crun` fails, `runc` doesn't seem to be. Either way, the corresponding interface file, `memory.swappiness` doesn't exist for cgroup v2. Try `podman run --runtime /usr/bin/crun --rm -ti --memory-swappiness=60 fedora:39`  provided the `crun` runtime is installed in `/usr/bin`.

2024-04-12 09:06 UTC, jerboaa reviewed
I don't think we need `Whitebox`. A simpler check would be to use the `Metrics` class. See for example `test/hotspot/jtreg/containers/docker/TestMemoryWithCgroupV1.java`.

2024-04-12 09:50 UTC, sendaoYan commented
> I don't think we need `Whitebox`. A simpler check would be to use the `Metrics` class. See for example `test/hotspot/jtreg/containers/docker/TestMemoryWithCgroupV1.java`.

Thanks your advice. The `Whitebox` has been removed, and Use `Metrics`class to get the cgroup version information.

2024-04-12 10:14 UTC, jerboaa reviewed
Better. I don't think we need to duplicate that much of the test. All we'd need to do is to add the `--memory-swappiness` option only if we are on cg v1:

```
                                          opts.addDockerOpts("--memory=" + memValueToSet)
                                                  .addDockerOpts("--memory-swap=" + swapValueToSet)
                                                  .addClassOptions("jdk.SwapSpace"));
                                          if (isCgroupV1) {
                                              // With Cgroupv1, The default memory-swappiness vaule is inherited from the host machine, which maybe 0
                                              opts.addDockerOpts("--memory-swappiness=60");
                                          }
                                          out = DockerTestUtils.dockerRunJava(opts);
                                          ...
```

2024-04-12 15:30 UTC, sendaoYan commented
> Better. I don't think we need to duplicate that much of the test. All we'd need to do is to add the `--memory-swappiness` option only if we are on cg v1:
> 
> ```
>                                           opts.addDockerOpts("--memory=" + memValueToSet)
>                                                   .addDockerOpts("--memory-swap=" + swapValueToSet)
>                                                   .addClassOptions("jdk.SwapSpace"));
>                                           if (isCgroupV1) {
>                                               // With Cgroupv1, The default memory-swappiness vaule is inherited from the host machine, which maybe 0
>                                               opts.addDockerOpts("--memory-swappiness=60");
>                                           }
>                                           out = DockerTestUtils.dockerRunJava(opts);
>                                           ...
> ```

Thank you very much for your very professional opinions. The modification of the review opinions has been completed. In addition, an extra space at the beginning of the line was deleted.

2024-04-12 16:28 UTC, jerboaa approved these changes
Looks OK to me.

2024-04-12 16:30 UTC, jerboaa commented
If you merge latest master, GHA should be clean too.

2024-04-13 02:55 UTC, sendaoYan commented
> If you merge latest master, GHA should be clean too.



> If you merge latest master, GHA should be clean too.

The GHA show java/lang/String/StringRepeat.java#id1 fails on linux x86. It's a testcase bug which has been fixed in [8328524](https://github.com/openjdk/jdk/pull/18380)

2024-04-17 02:10 UTC, sendaoYan commented
> Looks OK to me.

Thanks for the review.

2024-04-17 02:10 UTC, sendaoYan commented
/integrate

2024-04-17 08:38 UTC, jerboaa commented
/sponsor

2024-04-17 08:39 UTC, closed without merging

2024-04-17 16:19 UTC, sendaoYan commented
> /sponsor

Thanks.