8327969: Convert javax/swing/border/Test6910490.java applet test to main
openjdk/jdk pull request #18229
Opened 2024-03-12 11:15 UTC by TejeshR13

Convert javax/swing/border/Test6910490.java applet test to main based test using PassFailJFrame.

2024-03-13 01:10 UTC, DamonGuy approved these changes
Changes look straightforward and good to me.

2024-03-13 01:11 UTC, DamonGuy requested changes

2024-03-13 01:11 UTC, DamonGuy commented on test/jdk/javax/swing/border/Test6910490.java
> +        JFrame frame = new JFrame("Matte border test");
```suggestion
        JFrame frame = new JFrame("Matte Border Test");
```

2024-03-13 01:11 UTC, DamonGuy commented on test/jdk/javax/swing/border/Test6910490.java
> +        JFrame frame = new JFrame("Matte border test");
Title case

2024-03-13 01:17 UTC, honkar-jdk approved these changes

2024-03-14 15:28 UTC, DamonGuy approved these changes

2024-03-14 15:39 UTC, TejeshR13 commented
/integrate

2024-03-14 15:40 UTC, closed without merging