8328087: Automate javax/swing/JTable/TAB/TAB.java applet test
openjdk/jdk pull request #18274
Opened 2024-03-13 13:26 UTC by kumarabhi006

Conversion of manual applet test to automated test. CI testing is green. Link attached to JBS.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8328087](https://bugs.openjdk.org/browse/JDK-8328087): Automate javax/swing/JTable/TAB/TAB.java applet test (**Bug** - P4)

### Reviewers
 * [Harshitha Onkar](https://openjdk.org/census#honkar) (@honkar-jdk - **Reviewer**) ⚠️ Review applies to [0a6e5acb](https://git.openjdk.org/jdk/pull/18274/files/0a6e5acb3299ea84ee273647048f95072633bde1)
 * [Tejesh R](https://openjdk.org/census#tr) (@TejeshR13 - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/18274/head:pull/18274` \
`$ git checkout pull/18274`

Update a local copy of the PR: \
`$ git checkout pull/18274` \
`$ git pull https://git.openjdk.org/jdk.git pull/18274/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18274`

View PR using the GUI difftool: \
`$ git pr show -t 18274`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/18274.diff">https://git.openjdk.org/jdk/pull/18274.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/18274#issuecomment-1994414354)

2024-03-14 01:01 UTC, honkar-jdk requested changes

2024-03-14 01:01 UTC, honkar-jdk commented on test/jdk/javax/swing/JTable/TAB.java
> +public class TAB
Class name is in all-caps, `Tab` would be more appropriate.

2024-03-14 16:07 UTC, kumarabhi006 commented
@honkar-jdk Updated as per last review. Please take a look.

2024-03-14 17:19 UTC, honkar-jdk commented on test/jdk/javax/swing/JTable/Tab.java
>  {
Minor nit: Opening brace placement

2024-03-14 17:23 UTC, honkar-jdk approved these changes

2024-03-15 07:16 UTC, TejeshR13 reviewed
Looks good to me. Does this work fine in other L&F (Like Aqua), because you have explicitly mentioned as Metal right?

2024-03-15 07:43 UTC, kumarabhi006 commented
> Looks good to me. Does this work fine in other L&F (Like Aqua), because you have explicitly mentioned as Metal right?

The older version of applet test also checks for MetalLookAndFeel. Since the test is just converted to main manual, didn't check explicitly on Aqua or other LAFs.

2024-03-15 09:37 UTC, TejeshR13 approved these changes

2024-03-15 10:48 UTC, kumarabhi006 commented
/integrate

2024-03-15 10:49 UTC, closed without merging