8327180: Failed: java/io/ObjectStreamClass/ObjectStreamClassCaching.java#G1
openjdk/jdk pull request #18284
Opened 2024-03-13 18:01 UTC by RogerRiggs

The intermittent failure of ObjectStreamClassCaching is due to an incorrect assumption about GC behavior and a race condition.

Removed test based on incorrect assumptions about simultaneous clearing of WeakReferences.
Added a run of the test using ZGC, (previously omitted)

2024-03-13 19:49 UTC, stefank requested changes

2024-03-13 20:29 UTC, stefank approved these changes
Looks good. Make sure that the test has run after the -XX:+ZGenerational flag was added.

2024-03-13 20:49 UTC, irisclark approved these changes

2024-03-18 16:06 UTC, RogerRiggs commented
CI Tier1-3 successful

2024-03-18 16:06 UTC, RogerRiggs commented
/integrate

2024-03-18 16:07 UTC, closed without merging