8328228: Missing comma in copyright year for a few JColorChooser tests
openjdk/jdk pull request #18317
Opened 2024-03-14 23:36 UTC by alisenchung

Adding comma to copyright years

2024-03-14 23:39 UTC, dholmes-ora requested changes

2024-03-14 23:39 UTC, dholmes-ora commented on test/jdk/javax/swing/JColorChooser/Test4759306.java
> + * Copyright (c) 2002, 2008, 2024, Oracle and/or its affiliates. All rights reserved.
This line is wrong, we only use the first and last years. Please delete "2008, "

2024-03-14 23:39 UTC, dholmes-ora commented on test/jdk/javax/swing/JColorChooser/Test4759934.java
> + * Copyright (c) 2003, 2008, 2024, Oracle and/or its affiliates. All rights reserved.
Same here - please delete 2008.

2024-03-15 00:28 UTC, jaikiran approved these changes
Trivial copyright year update. This looks good to me.

2024-03-15 00:34 UTC, alisenchung commented
/integrate

2024-03-15 00:34 UTC, closed without merging

2024-03-15 03:48 UTC, dholmes-ora commented
@alisenchung  sorry I became unavailable to follow this through. Thanks for fixing.