8328648: Remove applet usage from JFileChooser tests bug4150029
openjdk/jdk pull request #18415
Opened 2024-03-20 22:48 UTC by alisenchung

Removing applet usage from manual JFileChooser tests

2024-03-21 11:47 UTC, kumarabhi006 commented
This test can be converted to automated. Similar issue was resolved for GTK LAF. You can refer https://github.com/openjdk/jdk/pull/11291.

2024-03-26 15:40 UTC, kumarabhi006 commented on test/jdk/javax/swing/JFileChooser/4150029/bug4150029.java
> + * @run main/manual bug4150029
Not a manual test anymore, please remove manual test related tags and library.

2024-03-26 15:40 UTC, kumarabhi006 commented on test/jdk/javax/swing/JFileChooser/4150029/bug4150029.java
> +//            fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
Not required to keep commented code.

2024-03-26 15:40 UTC, kumarabhi006 commented on test/jdk/javax/swing/JFileChooser/4150029/bug4150029.java
> +                frame = new JFrame("Backspace Shortcut for Directory Navigation Test");
Block of code can be moved to separate method to create and show UI elements.

2024-03-26 15:40 UTC, kumarabhi006 commented on test/jdk/javax/swing/JFileChooser/4150029/bug4150029.java
> +        Point p = frame.getLocationOnScreen();
should be on EDT.

2024-03-26 15:40 UTC, kumarabhi006 commented on test/jdk/javax/swing/JFileChooser/4150029/bug4150029.java
> +        robot.mousePress(InputEvent.BUTTON1_MASK);
```suggestion
        robot.mousePress(InputEvent.BUTTON1_DOWN_MASK);
```

should we add `robot.mouseRelease(InputEvent.BUTTON1_DOWN_MASK);` too ?

2024-03-26 15:40 UTC, kumarabhi006 commented on test/jdk/javax/swing/JFileChooser/4150029/bug4150029.java
> +        if (passed_1 && passed_2) {
I think no need to print "Test Passed", can check for not passed and throw the runtime exception inside if block.

2024-03-26 18:59 UTC, DamonGuy commented on test/jdk/javax/swing/JFileChooser/4150029/bug4150029.java
> +                frame.getContentPane().add(fileChooser, BorderLayout.CENTER);
```suggestion
                frame.add(fileChooser, BorderLayout.CENTER);
```

It was brought to my attention in one of my PRs that `getContentPane()` is obsolete as of JDK 1.5. They referenced  https://github.com/openjdk/jdk/pull/18390#discussion_r1533017080.

2024-03-26 23:40 UTC, DamonGuy requested changes

2024-03-26 23:40 UTC, DamonGuy commented on test/jdk/javax/swing/JFileChooser/4150029/bug4150029.java
> +        robot.mouseRelease(InputEvent.BUTTON1_DOWN_MASK);
`p.x` and `p.y` isn't in scope I believe. You can move `Point p` outside the method, make it static and volatile, then it should be fine. Maybe remove the extra newline in this `SwingUtilities.invokeAndWait()` block as well.

2024-03-27 05:10 UTC, kumarabhi006 commented on test/jdk/javax/swing/JFileChooser/4150029/bug4150029.java
> +                passed_2 = true;
This condition is not satisfied and hence the test failed in win11 machine. In linux machine, once the current directory is at `root` then pressing the backspace key doesn't have any effect.
But looks like it is different in windows and mac. Checked in windows native explorer, once it reached to `home` folder, it toggles between `home` and `Desktop` on backspace key press. The condition checked here will never satisfy and `passed_2` variable remains false.

So, either you can check the condition differently or may remove this check for windows and mac.

2024-03-29 04:50 UTC, DamonGuy reviewed
Looks like the test needs a headful tag as well. Was this ran via CI?

2024-03-29 05:33 UTC, kumarabhi006 commented on test/jdk/javax/swing/JFileChooser/4150029/bug4150029.java
> +            passed = true;
`passed` variable looks redundant now. You can directly evaluate compare the `prevDir` and `crntDir`, if they are same then test should fail.

2024-03-29 08:10 UTC, kumarabhi006 commented on test/jdk/javax/swing/JFileChooser/4150029/bug4150029.java
> +    private static File subDir;
`testDir` can be declared as local variable.
Probably `subDir` also can be moved as local variable provided you create JFileChooser instance with default directory and then set current directory inside main method after createAndShowUI method call.

something like this..

`SwingUtilities.invokeAndWait(() -> {
                createAndShowUI();
                fileChooser.setCurrentDirectory(subDir);
            });`

2024-03-29 08:10 UTC, kumarabhi006 commented on test/jdk/javax/swing/JFileChooser/4150029/bug4150029.java
> +        if (!(prevDir != crntDir)) {
simplified condition - 
```suggestion
        if (prevDir == crntDir) {
```

2024-03-29 08:10 UTC, kumarabhi006 commented on test/jdk/javax/swing/JFileChooser/4150029/bug4150029.java
May remove extra blank line.

2024-03-29 16:43 UTC, kumarabhi006 approved these changes
Looks good now. Only point is "should we move this test outside folder as html file is deleted now?".
Hope you have tested in CI for all platform.

2024-04-01 06:21 UTC, alisenchung commented
> Looks good now. Only point is "should we move this test outside folder as html file is deleted now?". Hope you have tested in CI for all platform.

Clientlibs is green, also I'll keep this inside the folder for bookkeeping

2024-04-01 06:21 UTC, alisenchung commented
/integrate

2024-04-01 07:16 UTC, kumarabhi006 commented
> /integrate

You need a "Reviewer" approval to integrate.

2024-04-01 19:30 UTC, DamonGuy approved these changes
Agreed. Looks good now, especially if CI is green. Still need "R"eviewer approval.

2024-04-01 20:57 UTC, honkar-jdk requested changes

2024-04-01 20:57 UTC, honkar-jdk commented on test/jdk/javax/swing/JFileChooser/4150029/bug4150029.java
> +        if (prevDir == crntDir) {
Wrong comparison operator should be .equals(). 
You might want to run the CI testing again with the updated changes just to make sure it works the same on all platforms.

```suggestion
        if (prevDir.equals(crntDir)) {
```

2024-04-02 23:33 UTC, honkar-jdk approved these changes
LGTM

2024-04-02 23:35 UTC, alisenchung commented
/integrate

2024-04-02 23:36 UTC, closed without merging