8328819: Remove applet usage from JFileChooser tests bug6698013
openjdk/jdk pull request #18456
Opened 2024-03-22 15:40 UTC by alisenchung

Removing applet usage from manual JFileChooser tests
The original test is failing (nothing shows up in the JFileChooser), but this change does replace the applet usage with PassFailJFrame

2024-03-22 21:00 UTC, honkar-jdk reviewed
> The original test is failing (nothing shows up in the JFileChooser), but this change does replace the applet usage with PassFailJFrame

@alisenchung The original test works on Windows. Is it on macOS that nothing is shown ?

2024-03-22 21:33 UTC, honkar-jdk reviewed
Ideally the Instruction window and Test window appear side-by-side. In this case, the JFileChooser completely covers the Instruction window even when set using .testUI(). Not sure why the window manager doesn't honor the position set by PassFailJFrame, for now you can increase the number rows to increase the size of instruction window, so that the user running the manual test is aware that there are 2 windows.

2024-03-26 07:53 UTC, TejeshR13 reviewed
`rootFile`, `subdir `and `subdirFile` can be moved inside `VirtualFileSystemView` class ?

2024-03-26 07:53 UTC, TejeshR13 commented on test/jdk/javax/swing/JFileChooser/6698013/bug6698013.java
> +                3. Go into 'subdir' folder: select 'subdir' folder and press the 'Open' button""";
Mentioning about Test Pass and Fail criteria would be beneficial, the instruction only says how to test, doesn't specify about Test PASS/FAIL criteria....?

2024-03-26 18:49 UTC, DamonGuy requested changes

2024-03-26 18:49 UTC, DamonGuy commented on test/jdk/javax/swing/JFileChooser/6698013/bug6698013.java
> +                .rows(25)
```suggestion
                .rows((int) INSTRUCTIONS.lines().count() + 2)
```

Your instructions frame has a lot of white space. Maybe worth incorporating this so you don't have to worry about adjusting the row count for each test.

2024-03-26 23:01 UTC, honkar-jdk approved these changes
LGTM.

Suggestion:
Since this test is problem-listed on macOS, mentioning it in PR description is helpful for reviewers as well as for future reference.

2024-03-26 23:31 UTC, DamonGuy approved these changes

2024-03-27 03:41 UTC, TejeshR13 approved these changes

2024-03-27 19:19 UTC, alisenchung commented
/integrate

2024-03-27 19:19 UTC, closed without merging