8329766
openjdk/jdk pull request #18651
Opened 2024-04-05 11:23 UTC by albertnetymk

Simple refactoring towards unifying BOT API between Serial and Parallel.

2024-04-05 12:08 UTC, lgxbslgx approved these changes
Looks good.

2024-04-08 15:37 UTC, walulyai requested changes

2024-04-08 15:37 UTC, walulyai commented on src/hotspot/share/gc/serial/serialBlockOffsetTable.cpp
> +  // + 1 for inclusive
```suggestion
  // + 1 for inclusive.
```

2024-04-08 15:37 UTC, walulyai commented on src/hotspot/share/gc/serial/serialBlockOffsetTable.hpp
> +  // Mapping from address to object start array entry
```suggestion
  // Mapping from address to object start array entry.
```

2024-04-08 15:37 UTC, walulyai commented on src/hotspot/share/gc/serial/serialBlockOffsetTable.hpp
> +  // Mapping from object start array entry to address of first word
```suggestion
  // Mapping from object start array entry to address of first word.
```

2024-04-08 15:37 UTC, walulyai commented on src/hotspot/share/gc/serial/serialBlockOffsetTable.cpp
> +static void fill_range(uint8_t* start, uint8_t* end, uint8_t v) {
I suggest we write out the `v` as `value`, I don't see what we save by the abbreviation.

2024-04-08 15:45 UTC, lgxbslgx approved these changes

2024-04-08 15:47 UTC, walulyai approved these changes

2024-04-08 18:32 UTC, albertnetymk commented
Thanks for review.

/integrate

2024-04-08 18:34 UTC, closed without merging