8330670
openjdk/jdk pull request #18861
Opened 2024-04-19 11:53 UTC by albertnetymk

Obsolete a gc product flag.

Test: tier1-3

2024-04-19 11:53 UTC, albertnetymk commented
/label add hotspot-gc

2024-04-19 12:09 UTC, stefank requested changes

2024-04-19 12:09 UTC, stefank commented on src/hotspot/share/gc/z/zDriver.cpp
> +  return false;
I'm not sure if this is correct. We previously returned true here if the user didn't set ScavengeBeforeFullGC, right? Maybe we need a ZGC-specific flag to allow this "precleaning" to be turned off?

2024-04-19 12:26 UTC, stefank commented on src/hotspot/share/gc/z/zDriver.cpp
> +  return false;
Ahh, I missed that. Nowadays we typically put that kind of code in the GC-specific places and not in the shared code.

2024-04-23 08:07 UTC, stefank approved these changes

2024-04-23 09:40 UTC, tschatzl approved these changes

2024-04-24 09:42 UTC, albertnetymk commented
Thanks for review.

/integrate

2024-04-24 09:44 UTC, closed without merging