8032218: Emit single post-constructor barrier for chain of superclass constructors
openjdk/jdk pull request #18870
Opened 2024-04-19 22:31 UTC by caojoshua

Opening this PR on top of https://github.com/openjdk/jdk/pull/18505. This PR is only valid if we agree it is sufficient to use `StoreStore` barriers at the end of constructors instead of `Release` barriers.

Currently on master, [C2 emits a Release barrier for each constructor call](https://github.com/openjdk/jdk/blob/32946e1882e9b22c983cbba3c6bda3cc7295946a/src/hotspot/share/opto/parse1.cpp#L1019) in a chain of superclass constructor calls. After https://github.com/openjdk/jdk/pull/18505 is merged, it is the same except that the barrier is a `StoreStore`. It is unnecessary. We only need to emit a single barrier for each object allocation / each pair of `Allocation/InitializeNode`. 

[Macro expansion emits a trailing StoreStore after an InitializeNode](https://github.com/openjdk/jdk/blob/32946e1882e9b22c983cbba3c6bda3cc7295946a/src/hotspot/share/opto/macro.cpp#L1610-L1628). This `StoreStore` is sufficient as the post-constructor barrier. From the [InitializeNode definition](https://github.com/openjdk/jdk/blob/32946e1882e9b22c983cbba3c6bda3cc7295946a/src/hotspot/share/opto/memnode.cpp#L3639-L3642):

> // An InitializeNode collects and isolates object initialization after
// an AllocateNode and before the next possible safepoint.  As a
// memory barrier (MemBarNode), it keeps critical stores from drifting
// down past any safepoint or any publication of the allocation.

All the writes that occur in the constructor will come before the `InitializeNode/StoreStore`. This PR subsumes https://github.com/openjdk/jdk/pull/18505.

Passes hotspot tier1 locally on x86 linux machine. New tests make sure that there is a single `StoreStore` for chained constructors.

2024-04-19 22:49 UTC, caojoshua commented
I originally had a [different approach](https://github.com/caojoshua/jdk/commit/eb48719f75279721bcce48d00ed262ebbf3691e0) where we detect superclass constructors and do not emit barriers for them. We can tell if a constructor is a superclass constructor if:

1. the current and parent method have the same receiver
2. the current and parent method are both initializers

I didn't complete it. It fails a case where the superclass constructor does not write a final, and the child constructor does write a final. The patch would not emit a barrier in that case because the outermost constructor did not write a final. The child `Parse` would need to propagate `wrote_final` and other `wrote_*` flags to the parent `Parse`. `Parse` instances don't have any information on each other, and the code would need a fair amount of restructuring to support it.

Despite the bug, it passed all the test cases I created anyway. Thats when I looked into the macro expansion for `InitializeNode` and thought that by itself was sufficient in emitting post-constructor barriers, arriving to this patch.

Sharing this in case I have some wrong assumptions in this PR. We could revert to working o

2024-04-19 23:28 UTC, dean-long commented
Doesn't this only work if the allocation and call to ctor are compiled together?  Where is the StoreStore added if we compile a <init> method by itself?  The allocation could be in the interpreter but the when calling <init> we call compiled code.

2024-04-22 22:17 UTC, caojoshua commented
> Doesn't this only work if the allocation and call to ctor are compiled together? Where is the StoreStore added if we compile a method by itself? The allocation could be in the interpreter but the when calling we call compiled code.

Yes, I think you're right. We should probably still emit the barrier when it is the outermost method. Unfortunately, I don't think we can directly IR test on a constructor.

2024-04-24 01:38 UTC, dean-long requested changes
If the subclass ctor inlines the super ctor, it might be safe to omit the barrier from the super ctor.  However, the current approach seem to remove barriers that are needed when the `<init>` is called from the interpter or another compiled method.

2024-06-17 19:06 UTC, caojoshua commented
Had to step away for a while but still plan on working on this. Comment to keep alive.

2024-06-23 07:17 UTC, caojoshua commented
Re-worked this patch. See updated description. Now we avoid emitting a barrier if we can find the object's `InitializeNode`. We don't need to emit a barrier if we find the `InitializeNode` because  macro expansion will expand it and emit the trailing StoreStore barrier

2024-07-10 23:26 UTC, dean-long commented on src/hotspot/share/opto/parse1.cpp
> +        Op_MemBarRelease, alloc_with_final());
FYI, JDK-8333791 proposes changes here also.

2024-08-18 07:35 UTC, caojoshua commented
Had some merge conflicts with https://bugs.openjdk.org/browse/JDK-8333791. As I understand it, when it comes to post-constructor barriers, we can treat stable and final fields the same. Fixed the merge conflict and added tests to reflect those changes.

2024-08-26 06:25 UTC, TobiHartmann commented
`compiler/stringopts/TestStringObjectInitialization.java` fails on Linux AArch64 with `-XX:-TieredCompilation -XX:+AlwaysIncrementalInline`:

```
java.lang.NullPointerException: Cannot read the array length because "this.value" is null
	at java.base/java.lang.String.length(String.java:1593)
	at java.base/java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:590)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:179)
	at compiler.stringopts.TestStringObjectInitialization.add(TestStringObjectInitialization.java:62)
	at compiler.stringopts.TestStringObjectInitialization.run(TestStringObjectInitialization.java:67)
	at compiler.stringopts.TestStringObjectInitialization$Runner.run(TestStringObjectInitialization.java:85)
	at java.base/java.lang.Thread.run(Thread.java:1575)
STATUS:Failed.`main' threw exception: java.lang.NullPointerException: Cannot read the array length because "this.value" is null
java.lang.NullPointerException: Cannot read the array length because "this.value" is null
	at java.base/java.lang.String.length(String.java:1593)
	at java.base/java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:590)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:179)
	at compiler.stringopts.TestStringObjectInitialization.add(TestStringObjectInitialization.java:62)
	at compiler.stringopts.TestStringObjectInitialization.run(TestStringObjectInitialization.java:67)
	at compiler.stringopts.TestStringObjectInitialization$Runner.run(TestStringObjectInitialization.java:85)
	at java.base/java.lang.Thread.run(Thread.java:1575)
STATUS:Failed.`main' threw exception: java.lang.NullPointerException: Cannot read the array length because "this.value" is null
java.lang.NullPointerException: Cannot read the array length because "this.value" is null
	at java.base/java.lang.String.length(String.java:1593)
	at java.base/java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:590)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:179)
	at compiler.stringopts.TestStringObjectInitialization.add(TestStringObjectInitialization.java:62)
	at compiler.stringopts.TestStringObjectInitialization.run(TestStringObjectInitialization.java:67)
	at compiler.stringopts.TestStringObjectInitialization$Runner.run(TestStringObjectInitialization.java:85)
	at java.base/java.lang.Thread.run(Thread.java:1575)
```

I also see this with an internal stress test:

```
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (/workspace/open/src/hotspot/share/opto/escape.cpp:4674), pid=22930, tid=42355
#  assert(n->is_Mem()) failed: memory node required.
#
# JRE version: Java(TM) SE Runtime Environment (24.0) (fastdebug build 24-internal-2024-08-26-0524112.tobias.hartmann.jdk3)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (fastdebug 24-internal-2024-08-26-0524112.tobias.hartmann.jdk3, mixed mode, tiered, compressed class ptrs, z gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0xbcc316]  ConnectionGraph::split_unique_types(GrowableArray<Node*>&, GrowableArray<ArrayCopyNode*>&, GrowableArray<MergeMemNode*>&, Unique_Node_List&)+0x3796
#


Current CompileTask:
C2:617119 124774       4       sun.util.locale.LocaleExtensions::toID (136 bytes)

Stack: [0x00007fd262f9b000,0x00007fd26309b000],  sp=0x00007fd263095a70,  free space=1002k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [libjvm.so+0xbcc316]  ConnectionGraph::split_unique_types(GrowableArray<Node*>&, GrowableArray<ArrayCopyNode*>&, GrowableArray<MergeMemNode*>&, Unique_Node_List&)+0x3796  (escape.cpp:4674)
V  [libjvm.so+0xbd46b9]  ConnectionGraph::compute_escape()+0x20e9  (escape.cpp:397)
V  [libjvm.so+0xbd4f11]  ConnectionGraph::do_analysis(Compile*, PhaseIterGVN*)+0xf1  (escape.cpp:119)
V  [libjvm.so+0x9fbeaa]  Compile::Optimize()+0x63a  (compile.cpp:2324)
V  [libjvm.so+0x9ffe13]  Compile::Compile(ciEnv*, ciMethod*, int, Options, DirectiveSet*)+0x1b43  (compile.cpp:852)
V  [libjvm.so+0x84f2c5]  C2Compiler::compile_method(ciEnv*, ciMethod*, int, bool, DirectiveSet*)+0x1d5  (c2compiler.cpp:142)
V  [libjvm.so+0xa0bad8]  CompileBroker::invoke_compiler_on_method(CompileTask*)+0x928  (compileBroker.cpp:2303)
V  [libjvm.so+0xa0c768]  CompileBroker::compiler_thread_loop()+0x478  (compileBroker.cpp:1961)
V  [libjvm.so+0xeb67bc]  JavaThread::thread_main_inner()+0xcc  (javaThread.cpp:758)
V  [libjvm.so+0x17e2ab6]  Thread::call_run()+0xb6  (thread.cpp:225)
V  [libjvm.so+0x14cc747]  thread_native_entry(Thread*)+0x127  (os_linux.cpp:858)
```

2024-10-21 12:24 UTC, closed without merging