JDK-8330989: unify os::create_binary_file across Posix platforms
openjdk/jdk pull request #18918
Opened 2024-04-23 14:41 UTC by MBaesken

Seems os::create_binary_file can be unified across Posix platforms.

2024-04-24 06:11 UTC, dholmes-ora requested changes
I think we can fold in the Windows version too and put it in os.cpp with one `WINDOWS_ONLY(xxx)` part

2024-04-24 07:59 UTC, MBaesken commented
> I think we can fold in the Windows version too and put it in os.cpp with one `WINDOWS_ONLY(xxx)` part

There is only a small difference, so why not  !

2024-04-24 10:42 UTC, dholmes-ora requested changes
Sorry @MBaesken I led you astray - I missed the fact that on Windows all the flag constants also start with `_` so `_O_CREAT` instead of `O_CREAT`. etc. If the non-underscore versions exist they will likely generate a compiler warning.

2024-04-24 11:58 UTC, MBaesken commented
> Sorry @MBaesken I led you astray - I missed the fact that on Windows all the flag constants also start with `_` so `_O_CREAT` instead of `O_CREAT`. etc. If the non-underscore versions exist they will likely generate a compiler warning.

I see no errors in the windows GHAs.
On the other hand,  the MS documentation recommends _open instead of ::open / open  
https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/open?view=msvc-170

We already use the  '::open' with non-underscore string flags for example here  osSupport_windows.cpp , seems both work.

2024-04-25 13:46 UTC, MBaesken commented
Hi David, no compile or test errors have been observed in GHA or in our internal testing.
So should we keep what we have?  Or go for the '_'  prefixed flags and _open on Windows ?

2024-04-26 06:48 UTC, dholmes-ora commented
> Hi David, no compile or test errors have been observed in GHA or in our internal testing. So should we keep what we have? Or go for the '_' prefixed flags and _open on Windows ?

Okay. Based on this:

https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/open?view=msvc-170
https://learn.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-3-c4996?view=msvc-170#posix-function-names

I expected to see compiler deprecation warnings AFAICS we don't disable them??

If this works then I guess it is okay.

2024-04-26 07:36 UTC, MBaesken commented
> > Hi David, no compile or test errors have been observed in GHA or in our internal testing. So should we keep what we have? Or go for the '_' prefixed flags and _open on Windows ?
> 
> Okay. Based on this:
> 
> https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/open?view=msvc-170 https://learn.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-3-c4996?view=msvc-170#posix-function-names
> 
> I expected to see compiler deprecation warningsm as AFAICS we don't disable them. ??
> 
> If this works then I guess it is okay.

Hi David, this is indeed a little strange.   The MS document you mentioned says 

> The Microsoft-implemented POSIX function name open is a deprecated alias for the [_open](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/open-wopen?view=msvc-170) function. By default, it generates [Compiler warning (level 3) C4996](https://learn.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-3-c4996?view=msvc-170).

We disable the mentioned warning 4996 for quite a few compilation units (grep for 4996 in make/modules), but not for all.
I do not see it disabled for os.cpp. But still no compilation errors in GHA or our builds/tests.  Maybe for some strange reason 'open'  is bad but '::open' is okay for MSVC (it is used anyway in os_windows.cpp see `os::dll_load`)?

2024-04-26 07:43 UTC, MBaesken commented
> Maybe for some strange reason 'open' is bad but '::open' is okay for MSVC

btw. should we maybe better use `os::open`  instead or was there a special reason not to do it here ?
The Windows os::open already adds  O_BINARY, see https://github.com/openjdk/jdk/blob/a407dc9cbb48c4f66af51433067925605d3bc39d/src/hotspot/os/windows/os_windows.cpp#L4816
 so there would be no need for this Win-only special handling any more.

2024-04-28 21:52 UTC, dholmes-ora commented
> was there a special reason not to do it here ?

We often use platform specific code in this file rather than "jumping" back out to shared code like`os::xxx`.

> The Windows os::open already adds O_BINARY

And the non-windows `os::open` does a lot of other hacking around close-on-exec. I would rather not change any functionality in this PR as it meant to be a simple refactoring.

It isn't clear to me why `os::create_binary_file` even needed to be introduced but it is day one code for the heapDumper. I suspect it was a wrapper purely to add the O_BINARY flag on Windows. But we have CDS code, for example, the also creates binary files but doesn't use this API. Seems like a candidate for removal to me, but not this PR.

2024-04-29 11:25 UTC, MBaesken commented
okay the let's NOT use `os::open` .
Regarding recommended  `_open` vs,  `::open`  on Windows, we used `::open`  before in `create_binary_file`   , so this should be fine and is just the same code moved to os.cpp . 
Regarding the flags, they exist on Windows with and without leading ` _`  - any reason to go to the versions with leading ` _`  ?
I can do so if you want but it would only add ifdefs to the code .

2024-04-30 04:45 UTC, dholmes-ora commented
Drop the underscores on the flag names so we have shared code. Thanks.

2024-05-01 08:54 UTC, dholmes-ora commented
Thanks @kimbarrett , I had forgotten about that: https://bugs.openjdk.org/browse/JDK-6991482

2024-05-01 21:57 UTC, kimbarrett approved these changes
Looks good.

2024-05-02 07:05 UTC, MBaesken commented
Hi David and Kim, thanks for the reviews !

/integrate

2024-05-02 07:06 UTC, closed without merging