8330275: Crash in XMark::follow_array
openjdk/jdk pull request #18941
Opened 2024-04-24 20:22 UTC by ashu-mehra

This PR addresses the issue in ZGC where the number of address offset bits can go beyond the limit imposed by the encoding scheme in mark stack, thereby causing the encoding to fail.
Encoding of partial array offset in mark stack requires that the address offset be no more than 44 bits. But the current mechanism to probe maximum address offset bits on aarch64 and riscv platforms can return value larger that 44 bits.

I have updated the generational mode to avoid subtracting 3 bits from the maximum address offset bit probed by the system, as the generational mode does not use multi-mapping.

I have also updated the code to set MarkPartialArrayMinSizeShift dynamically depending on the number of address offset bits used. This would avoid running into such problem again if in future maximum address offset bits is increased beyond 44.

Testing: test/hotspot/jtreg/gc/z and test/hotspot/jtreg/gc/x

2024-04-25 01:17 UTC, ashu-mehra commented
I am currently trying to get access to aarch64 system and run the tests test/hotspot/jtreg/gc/z and test/hotspot/jtreg/gc/x.
I would appreciate if some one can also test the ppc and riscv changes as I don't have access to such systems.

2024-04-25 01:17 UTC, ashu-mehra commented
/label add hotspot-gc

2024-04-25 06:54 UTC, stefank requested changes
Hi @ashu-mehra,

Thanks for fixing this issue.

There's a number of changes style changes I would like to make to make sure that the code looks more inline with what the rest of the ZGC code looks like. But before we start with that I would like to request that we skip making the changes to marking stack code and limit the changes to only the probing code. Doing so will make it easier to get this fix reviewed and delivered.

2024-04-25 14:29 UTC, ashu-mehra commented
@stefank I am trying to understand the reason behind your suggestion to remove the changes in marking stack code. Are they not correct or is it that they don't belong to this PR?
Anyway I have removed them from this PR.

2024-04-26 06:54 UTC, tstuefe commented
> > @stefank I am trying to understand the reason behind your suggestion to remove the changes in marking stack code. Are they not correct or is it that they don't belong to this PR? Anyway I have removed them from this PR.
> 
> To me, it was not bleeding obvious that they were the right thing to do, and given other changes that doesn't follow the grown ZGC coding style, I wanted suggest a way forward for you to get this bug fixed, with less resistance from us ZGC developers/maintainers. That was the reasoning.

I agree with Stefan. I would keep the patch as minimal as possible to make it easier to follow the actual error that has been fixed, and to make it easier for backporters to decide what to downport. 

Code cleanups can happen in a separate RFE.

Ashu, are the other platforms actually broken? If yes, which ones? If a platform is not broken, I would defer touching it up to a separate cleanup RFE. Again because of patch clarity.

2024-04-26 14:20 UTC, ashu-mehra commented
I agree from the point of view of backporting, point-fix is all we need in this PR.

@tstuefe  As for the other platforms (riscv and ppc), looking at their code they seem to be broken in the same way as aarch64 but then the problem only happens if the user runs with > 1TB heap size with more than 48 addressable bits.
Again, in the spirit of "do not touch if it is not broken", I am fine if we restrict the change to just aarch64.

@tstuefe @stefank please let me know if you agree with just doing the point-fix to aarch64.

2024-04-27 05:07 UTC, tstuefe commented
> I agree from the point of view of backporting, point-fix is all we need in this PR.
> 
> @tstuefe As for the other platforms (riscv and ppc), looking at their code they seem to be broken in the same way as aarch64 but then the problem only happens if the user runs with > 1TB heap size with more than 48 addressable bits. Again, in the spirit of "do not touch if it is not broken", I am fine if we restrict the change to just aarch64.
> 
> @tstuefe @stefank please let me know if you agree with just doing the point-fix to aarch64.

Absolutely. We can do any platform testing on other platforms and cleanups in subsequent RFEs.

2024-05-08 13:27 UTC, ashu-mehra commented
Sorry for the long absence on this PR. I have updated the PR to just do a point fix for aarch64. I have also done tier1, tier2 and tier3 tests on aarch64.

2024-05-08 13:36 UTC, stefank approved these changes
Looks good.

FWIW, the 128TB and 64GB numbers are just confusing when we are talking about a bit position. If the 46th bit succeeds the usable address range is 128TB, and the 46th bit will account for 64TB out of those 128TB. I wouldn't mind at all if we just ripped out the mentions of 64TB and  64GB here.

2024-05-08 14:13 UTC, ashu-mehra commented
> I wouldn't mind at all if we just ripped out the mentions of 64TB and 64GB here.

Done

2024-05-08 14:37 UTC, ashu-mehra commented
@tstuefe does this look ok?

2024-05-08 15:43 UTC, tstuefe approved these changes
Looks good, question inline.

2024-05-08 15:43 UTC, tstuefe commented on src/hotspot/cpu/aarch64/gc/x/xGlobals_aarch64.cpp
> -// Minimum value returned, if probing fails: 64GB
any reason you removed the comment for MINIMUM_MAX_ADDRESS_BIT?

2024-05-08 20:25 UTC, ashu-mehra commented
As the last commit is a trivial change to add the comments back, I am not requesting new review and integrating it as is.

2024-05-08 20:25 UTC, ashu-mehra commented
/integrate

2024-05-08 20:26 UTC, closed without merging

2024-05-13 10:03 UTC, stefank commented on src/hotspot/cpu/aarch64/gc/z/zAddress_aarch64.cpp
> +// the bit layout of XForwardingEntry or Partial array entry (see XMarkStackEntry) in mark stack
This comment was copy-n-pasted without updating the names to ZForwardingEntry and ZMarkStackEntry.

2024-05-28 14:32 UTC, ashu-mehra commented
/backport jdk21u-dev

2024-05-28 15:25 UTC, ashu-mehra commented
/backport jdk22u