8331159: VM build without C2 fails after JDK-8180450
openjdk/jdk pull request #18962
Opened 2024-04-25 20:54 UTC by lewurm

x86 bits are fine.

2024-04-26 08:04 UTC, lewurm commented
/integrate

2024-04-26 15:45 UTC, vnkozlov requested changes
I would like author of this code to review this. @theRealAph please look.

There is difference between x64 and aarch64 how this stub is generated. For x64 it is generated as part of compiler stubs under `#ifdef COMPILER2`. For aarch64 it is in final stubs. Why is difference?

If it is really C2 specific stub then why `UseSecondarySupersTable` flag is global?

`MacroAssembler::lookup_secondary_supers_table*()` methods could be also in `c2_MacroAssembler*` files.

2024-05-29 16:55 UTC, lewurm commented
@theRealAph could you have a look at this?  Thanks!

2024-05-30 08:38 UTC, theRealAph approved these changes
Sure, it's fine. I have the same change in [8331658](https://github.com/openjdk/jdk/pull/19426/files#diff-9112056f732229b18fec48fb0b20a3fe824de49d0abd41fbdb4202cfe70ad114), but you can push this if you like and I'll take that change out.

2024-05-30 18:30 UTC, vnkozlov approved these changes
Okay since Andrew agreed.

2024-05-31 07:59 UTC, lewurm commented
/integrate

2024-05-31 08:00 UTC, lewurm commented
Thanks!  Can someone sponsor it please?

2024-05-31 18:17 UTC, vnkozlov commented
/sponsor

2024-05-31 18:18 UTC, closed without merging