8331285
openjdk/jdk pull request #18994
Opened 2024-04-29 10:06 UTC by albertnetymk

Simple deprecating a jvm flag.

2024-04-29 10:11 UTC, albertnetymk commented
/cc hotspot-gc

2024-04-30 06:17 UTC, dholmes-ora requested changes

2024-04-30 06:17 UTC, dholmes-ora commented on src/hotspot/share/runtime/arguments.cpp
> +  { "OldSize",                      JDK_Version::jdk(23), JDK_Version::jdk(24), JDK_Version::jdk(25) },
This should be at line 504 before PreserveAllAnnotations to keep ordering within release.

2024-05-01 09:28 UTC, dholmes-ora approved these changes
Looks good. Thanks.

2024-05-06 09:35 UTC, fisk approved these changes
Looks good.

2024-05-06 09:40 UTC, albertnetymk commented
Thanks for review.

/integrate

2024-05-06 09:41 UTC, closed without merging