8331077 : nroff man page update for jar tool
openjdk/jdk pull request #19039
Opened 2024-05-01 17:52 UTC by weibxiao

nroff man page update for jar tool. <br>
This update is caused by the change of https://bugs.openjdk.org/browse/JDK-8318971. While the .md man pages got updated in other repos, the corresponding nroff man page was never updated in OpenJDK repos

2024-05-01 18:06 UTC, jonathan-gibbons requested changes

2024-05-01 18:06 UTC, jonathan-gibbons commented on src/jdk.jartool/share/man/jar.1
> +.TH "JAR" "1" "2024" "JDK 23-internal" "JDK Commands"
should remain as `ea` -- not `internal`

2024-05-01 18:38 UTC, weibxiao commented
reverted to "JDK 23-ea"

2024-05-01 18:46 UTC, coffeys approved these changes
Looks ok to me

2024-05-01 20:02 UTC, jonathan-gibbons approved these changes
Approved, as corresponding to the upstream Markdown file.

That being said, the descriptions about arg files in lines 334-343 look somewhat clunky, and could benefit from some improvements in a later update.

2024-05-02 11:47 UTC, coffeys commented
/sponsor

2024-05-02 11:48 UTC, closed without merging