8331723: Serial: Remove the unused parameter of the method SerialHeap::gc_prologue
openjdk/jdk pull request #19165
Opened 2024-05-10 01:00 UTC by xiaotaonan

Serial: Remove the unused parameter of the method SerialHeap::gc_prologue

2024-05-10 01:24 UTC, xiaotaonan commented
@lgxbslgx

2024-05-10 07:28 UTC, lgxbslgx commented
Please enable the GitHub Action; See https://wiki.openjdk.org/display/SKARA/Testing for more information.

2024-05-11 00:48 UTC, xiaotaonan commented
> Please enable the GitHub Action; See https://wiki.openjdk.org/display/SKARA/Testing for more information.

I have enabled the GitHub Action.

2024-05-11 00:48 UTC, xiaotaonan commented
@lgxbslgx

2024-05-12 04:42 UTC, lgxbslgx requested changes
The usages of the `SerialHeap::gc_prologue` needs to be revised too, such as `SerialHeap::do_collection`.

I build this patch locally but it fails. It is better for you to build the code and run some test cases locally before submitting the PR (in the future).

2024-05-12 09:05 UTC, closed without merging

2024-05-12 10:08 UTC, lgxbslgx commented
Why did you close this PR and file https://github.com/openjdk/jdk/pull/19207?