8332448
openjdk/jdk pull request #19279
Opened 2024-05-17 09:29 UTC by albertnetymk

Extract the state for `top` out of `SpaceMangler`. Users (Serial and Parallel GC) already tracks the top before/after GC. The "real" change in this PR are only two places: `serialFullGC.cpp` and `PSParallelCompact::post_compact`.

Test: tier1-5

2024-05-20 20:55 UTC, kimbarrett requested changes

2024-05-20 20:55 UTC, kimbarrett commented on src/hotspot/share/gc/serial/serialFullGC.cpp
> +      space->set_top(new_top);
I'd rather the new_top variable declaration was after the comment rather than before.

2024-05-20 20:55 UTC, kimbarrett commented on src/hotspot/share/gc/shared/spaceDecorator.cpp
>  void SpaceMangler::mangle_region(MemRegion mr) {
SpaceMangler::mangle_region should be debug-only rather than not-product, both conceptually, and
because it has no effect in non-debug builds.

2024-05-20 21:17 UTC, kimbarrett approved these changes
Looks good.

2024-05-21 07:43 UTC, albertnetymk commented
Thanks for review.

/integrate

2024-05-21 07:43 UTC, closed without merging