8332402: [IR Framework] Add tests for applyIfCPUFeature* and applyIfPlatform* in TestBadFormat
openjdk/jdk pull request #19302
Opened 2024-05-20 08:27 UTC by Hamlin-Li

Hi,
Can you help to review this patch to add some test for IR test framework?
As discussed https://github.com/openjdk/jdk/pull/19270#pullrequestreview-2060974799, it's worth to add some tests for for applyIfCPUFeature* and applyIfPlatform* in TestBadFormat.

Thanks

2024-05-21 07:54 UTC, luhenry approved these changes

2024-05-21 07:56 UTC, luhenry commented
@chhagedorn @eme64 could you please review as you did the most recent changes on this file? Not sure who else to ping on this. Thank you!

2024-05-21 08:18 UTC, eme64 requested changes
Thanks for the work! Generally looks good. I have a few comments.
We should also wait a week, @chhagedorn is out of the office. He generally has more context on the IR framework.

2024-05-21 08:18 UTC, eme64 commented on test/hotspot/jtreg/testlibrary_tests/ir_framework/tests/TestBadFormat.java
> +    @FailCount(3)
Why are there 3 failures?

2024-05-21 08:18 UTC, eme64 commented on test/hotspot/jtreg/testlibrary_tests/ir_framework/tests/TestBadFormat.java
> +    @FailCount(3)
Generally, the count is not always as I would expect. Can we fix that? You should at least comment what fails, and why.

I would expect there to be a single failure per rule. But that seems not to be the case.

2024-05-21 08:18 UTC, eme64 commented on test/hotspot/jtreg/testlibrary_tests/ir_framework/tests/TestBadFormat.java
> -    @IR(failOn = IRNode.CALL, applyIfAnd = {"TLABRefillWasteFraction", "50", "UseTLAB", "true"},
Not sure why you changed the format here. You seem to have one-liners everywhere else? Plus it just creates noise when reviewing.

2024-05-27 08:08 UTC, chhagedorn reviewed
Thanks for adding all these new tests! I have some comments.

2024-05-27 08:37 UTC, chhagedorn commented
/label add hotspot-compiler

2024-07-22 13:30 UTC, closed without merging