8332610: Remove unused nWakeups in ObjectMonitor
openjdk/jdk pull request #19326
Opened 2024-05-21 13:14 UTC by jdksjolen

Hi,

This comment only serves to confuse people, as `nWakeups` is not shared between threads and never read. It is probably meant for debugging (not sure). Let's delete the comment.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8332610](https://bugs.openjdk.org/browse/JDK-8332610): Remove unused nWakeups in ObjectMonitor (**Enhancement** - P4)

### Reviewers
 * [Coleen Phillimore](https://openjdk.org/census#coleenp) (@coleenp - **Reviewer**)
 * [Daniel D. Daugherty](https://openjdk.org/census#dcubed) (@dcubed-ojdk - **Reviewer**) ⚠️ Review applies to [f0de0bf1](https://git.openjdk.org/jdk/pull/19326/files/f0de0bf1986186a22d4119ac47a6fe7847393fe5)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19326/head:pull/19326` \
`$ git checkout pull/19326`

Update a local copy of the PR: \
`$ git checkout pull/19326` \
`$ git pull https://git.openjdk.org/jdk.git pull/19326/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19326`

View PR using the GUI difftool: \
`$ git pr show -t 19326`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19326.diff">https://git.openjdk.org/jdk/pull/19326.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19326#issuecomment-2122621805)

2024-05-21 14:24 UTC, coleenp requested changes
Please remove that unused variable also in the two places it's defined.  There's a perf counter that does not use this variable so the comment above with TryLock does make sense wrt to that perf counter.  This local variable is unused.

2024-05-21 14:40 UTC, jdksjolen commented
> Please remove that unused variable also in the two places it's defined. There's a perf counter that does not use this variable so the comment above with TryLock does make sense wrt to that perf counter. This local variable is unused.

`nWakeups` deleted!

2024-05-21 15:03 UTC, coleenp approved these changes
Looks great! Thank you for finding this unused code.

2024-05-22 05:09 UTC, dholmes-ora approved these changes
Interestingly this code has been dead since it was introduced. I will assume it was leftover debugging/performance-monitoring code.

2024-05-22 05:11 UTC, dholmes-ora commented on src/hotspot/share/runtime/objectMonitor.cpp
> -    // races during updates for a lower probe effect.
The same comment block needs deleting at line 874 too.

2024-05-22 05:16 UTC, dholmes-ora commented on src/hotspot/share/runtime/objectMonitor.cpp
> -    // races during updates for a lower probe effect.
Actually, I think the comment blocks are referring to the `OM_PERFDATA_OP(FutileWakeups, inc());` calls not the `nWakeups` local variable.

2024-05-22 05:18 UTC, dholmes-ora requested changes
Please restore comment, and possibly move them closer to the code the relate to.

Also nit: please change the bug synopsis to "Remove unused nWakeups in ObjectMonitor"

Thanks

2024-05-22 08:17 UTC, jdksjolen commented
> Please restore comment, and possibly move them closer to the code the relate to.
> 
> Also nit: please change the bug synopsis to "Remove unused nWakeups in ObjectMonitor"
> 
> Thanks

Good catch on both! I've fixed the issues, thanks.

2024-05-22 12:21 UTC, coleenp approved these changes
I would not have missed that comment, but it looks fine.

2024-05-22 13:51 UTC, jdksjolen commented
Errors for maxos-x64 unrelated to this patch. Thanks Coleen, Dan and David.

/integrate

2024-05-22 13:52 UTC, closed without merging

2024-05-22 15:40 UTC, dcubed-ojdk reviewed
I'm fine with the final version also.