8258896: Remove the JVM ForceFloatExceptions option
openjdk/jdk pull request #1932
Opened 2021-01-04 15:54 UTC by hseigel

Please review this change to replace the JVM ForceFloatExceptions flag with #ifdef (_DEBUG).  The change was tested with tiers 1 and 2 on Linux, Windows, and Mac OS, and tiers 3-5 on Windows x64.

Thanks, Harold

2021-01-04 17:56 UTC, lfoltan approved these changes
LGTM.
Lois

2021-01-04 18:29 UTC, iklam commented on src/hotspot/os/windows/os_windows.cpp
> +  fp_control_word |= invalid;
It looks like only `invalid` is used by the code. Are the other consts necessary?

2021-01-04 20:56 UTC, hseigel commented
Thanks Lois and Ioi for reviewing this change.  Please review the updated commit that removes the unneeded consts, as suggested by Ioi.

Thanks, Harold

2021-01-04 21:31 UTC, iklam approved these changes
LGTM

2021-01-05 06:09 UTC, kimbarrett requested changes

2021-01-05 14:54 UTC, coleenp approved these changes
Good find Kim.  LGTM.

2021-01-05 15:09 UTC, hseigel commented on src/hotspot/os/windows/os_windows.cpp
> +#if defined(_DEBUG) && !defined(_WIN64)
Thanks Kim.  I changed it from _DEBUB to ASSERT.

2021-01-05 16:10 UTC, lfoltan approved these changes
LGTM.
Lois

2021-01-05 16:14 UTC, hseigel commented
Thanks for the reviews!

/integrate

2021-01-05 16:15 UTC, closed without merging