8332807
openjdk/jdk pull request #19360
Opened 2024-05-23 10:13 UTC by albertnetymk

Trivial moving methods from public to private.

2024-05-23 15:32 UTC, tschatzl requested changes
Probably more dead code in this class to be cleaned up:

`IterationStatus::complete`; actually the return value of `do_addr()` method returning the other values is never used, so the entire enum can go away.

`is_unmarked(idx_t bit)`
`obj_granularity()`

unused forwards

`class ParCompactionManager;`
`class ParMarkBitMapClosure`

only used in .inline.hpp, so can be made private too:

`HeapWord* bit_to_addr(idx_t bit) const;`
`find_obj_beg(idx_t, idx_t)`
`verify_bit`
`verify_addr`

some other related unused methods

`ParMarkBitMapClosure::bitmap()`

May want to do this separately and more thoroughly.

2024-05-23 19:09 UTC, albertnetymk commented
All suggestions are good. I have resolved some of them. How about addressing the rest in followup PRs, as they touch other files, and can make this trivial PR non-trivial any more?

2024-05-24 07:24 UTC, tschatzl approved these changes
Lgtm and trivial.

2024-05-24 07:24 UTC, tschatzl commented
> All suggestions are good. I have resolved some of them. How about addressing the rest in followup PRs, as they touch other files, and can make this trivial PR non-trivial any more?

Okay.

2024-05-24 07:28 UTC, albertnetymk commented
Thanks for review.

/integrate

2024-05-24 07:29 UTC, closed without merging