Redundant assert(false, "compiler should always document failure: %s" with possible UB
openjdk/jdk pull request #19395
Opened 2024-05-24 14:27 UTC by eastig

[JDK-8303951](https://bugs.openjdk.org/browse/JDK-8303951) added the following code: https://github.com/openjdk/jdk/pull/13038/files#diff-2e74481e557cbe87170a56a6e592eea33bb59019926e1c32bebcfaf5b571bb53R2280

```
     if (!ci_env.failing() && !task->is_success()) {
+ assert(ci_env.failure_reason() != nullptr, "expect failure reason");
+ assert(false, "compiler should always document failure: %s", ci_env.failure_reason());
```

The second assert is redundant because `ci_env.failure_reason() != nullptr` is always `false`. It also has possible UB.

A compiler sees if-statement checking `!ci_env.failing() ` which, if it is true, implies `ci_env.failure_reason()` is `nullptr`.

Based on this information the compiler can optimize `assert(ci_env.failure_reason() != nullptr, "expect failure reason"); ` to
`assert(false, "expect failure reason"); `.
The compiler can optimize `assert(false, "compiler should always document failure: %s", ci_env.failure_reason()); ` to `assert(false, "compiler should always document failure: %s", nullptr); `.

So the original code would be like the following:

```
if (!ci_env.failing() && !task->is_success()) {
  assert(false, "expect failure reason");
  assert(false, "compiler should always document failure: %s", nullptr);
}
```

We have an expression where a format string is used. Format strings usually have undefined behavior if `nullptr` is passed for the character string format specifier. See `std::printf` for example.

Even the second assert is never executed, it makes the IF-block to have UB. The C++ standard says: correct C++ programs are free of undefined behavior. See https://en.cppreference.com/w/cpp/language/ub and https://en.cppreference.com/w/cpp/language/as_if

Choosing between readability and correctness, I choose correctness.

I think the one assert `assert(ci_env.failure_reason() != nullptr, "compiler should always document failure"); ` meets being self-documented and correct.

2024-05-24 18:32 UTC, vnkozlov requested changes
I think it is typo.  This code wants to check and print in these asserts `task->_failure_reason` which should be set when `!task->is_success()`.
We do miss public accessors to `CompileTask::_failure_reason` which have to be added.
And may be we should pass the failure to ciEnv too in this code instead of "compile failed".

2026-04-22 11:56 UTC, eastig commented
/open

2026-04-22 15:33 UTC, eastig commented
> I think it is typo. This code wants to check and print in these asserts `task->_failure_reason` which should be set when `!task->is_success()`. We do miss public accessors to `CompileTask::_failure_reason` which have to be added. And may be we should pass the failure to ciEnv too in this code instead of "compile failed".

Done. Take a look.

2026-04-22 16:09 UTC, vnkozlov approved these changes
Looks good.

2026-04-23 13:01 UTC, sarannat commented on src/hotspot/share/compiler/compileTask.hpp
This file needs copyright fixed.

2026-04-23 13:10 UTC, eastig commented on src/hotspot/share/compiler/compileTask.hpp
Done

2026-04-23 21:45 UTC, eastig commented
@vnkozlov,
Could you please reapprove? The only change is the copyright year.

2026-04-24 22:15 UTC, sarannat commented
Thank you for the fix. It looks good to me.

2026-04-24 22:16 UTC, sarannat approved these changes

2026-04-25 00:00 UTC, vnkozlov approved these changes
Update is good.

2026-04-27 09:43 UTC, eastig commented
@vnkozlov @sarannat Thank you for reviewing.

2026-04-27 09:43 UTC, eastig commented
/integrate

2026-04-27 09:44 UTC, closed without merging