JDK-8332955: ubsan: runningCounters.cpp:48:61: runtime error: member call on null pointer of type 'struct VirtualSpaceList'
openjdk/jdk pull request #19435
Opened 2024-05-28 18:12 UTC by tstuefe

@MBaesken and @dholmes-ora convinced me this needs fixing. Fix is trivial; for details, please see JBS issue.

2024-05-29 06:34 UTC, MBaesken approved these changes

2024-05-29 07:50 UTC, stefank requested changes
It seems unfortunate to have to pollute the code with these checks just because we crash during startup. Could this instead be fixed by not calling into `MemTracker::error_report` if we crash too early?

2024-05-29 09:16 UTC, MBaesken commented
> It seems unfortunate to have to pollute the code with these checks just because we crash during startup. Could this instead be fixed by not calling into `MemTracker::error_report` if we crash too early?

We had those nullptr checks anyway in the getters using VirtualSpaceList::vslist_class(); so it is probably safer to do the same for VirtualSpaceList::vslist_nonclass() .
Even if the callers are adjusted and the ubsan detected issue is gone for the moment, it can always happen that the calling code is reorganized a bit in future and we member-function-call again into a nullptr.

2024-05-29 11:06 UTC, stefank commented
> > It seems unfortunate to have to pollute the code with these checks just because we crash during startup. Could this instead be fixed by not calling into `MemTracker::error_report` if we crash too early?
> 
> We had those nullptr checks anyway in the getters using VirtualSpaceList::vslist_class(); so it is probably safer to do the same for VirtualSpaceList::vslist_nonclass() .

The difference is that the class metaspace is optional whereas the nonclass is not. I don't think that null-checks for the class space is a good argument that we should have them for the nonclass metaspace, which never should be null except in the extreme case when we crash before even having fully started the JVM.

I think I've made my point w.r.t. this, and I'll let Thomas decide if he still thinks that it is nicer to add these null-checks.

2024-05-29 11:07 UTC, stefank reviewed
Removing the "request changes" status.

2024-05-29 12:14 UTC, tstuefe commented
@stefank Yes, that was my original thought too. Non-class is mandatory, Class is optional. See discussion in JBS issue.

But making NMT reporting dependent on Metaspace initialization (different subsystem) is a bit awkward, too. And who knows who else wants to query these counters in the future. Returning 0 seemed the simplest way to make ubsan happy.

2024-05-30 06:31 UTC, dholmes-ora reviewed
By strange coincidence we just encountered an assertion failure during VM initalization (https://bugs.openjdk.org/browse/JDK-8332935) that leads to this secondary failure doing the NMT reporting, so I am glad to see it fixed. 

But I understand @stefank 's position about the code being well-defined except during this initialization phase, and also wonder where is the "best" place to address this? Doing it in the "leaf" methods is more future-proof in a sense but it also means we open up the possibility of even more code interacting with Metaspace stats before metaspace is initialized, which seems to me to be something we would not want and would perhaps like to detect. So I'm slightly in favour of having the NMT code check if metaspace is initialized before trying to report any metaspace stats if that is feasible.

2024-05-30 15:27 UTC, tstuefe commented
> By strange coincidence we just encountered an assertion failure during VM initalization (https://bugs.openjdk.org/browse/JDK-8332935) that leads to this secondary failure doing the NMT reporting, so I am glad to see it fixed.
> 
> But I understand @stefank 's position about the code being well-defined except during this initialization phase, and also wonder where is the "best" place to address this? Doing it in the "leaf" methods is more future-proof in a sense but it also means we open up the possibility of even more code interacting with Metaspace stats before metaspace is initialized, which seems to me to be something we would not want and would perhaps like to detect. So I'm slightly in favour of having the NMT code check if metaspace is initialized before trying to report any metaspace stats if that is feasible.

It is feasible, and likely trivial. We can do both. I opened https://bugs.openjdk.org/browse/JDK-8333290 to track this. 

I still would like this PR go through for now. I think hardening this leaf function makes sense.

2024-05-31 05:25 UTC, dholmes-ora commented
The hardening you propose would mask any incorrect usage of these functions. I would prefer if they assert the fields are non-null.

Thanks for filing the other issue.

2024-05-31 06:51 UTC, tstuefe commented
> The hardening you propose would mask any incorrect usage of these functions. I would prefer if they assert the fields are non-null.
> 
> Thanks for filing the other issue.

Alright, in that case I close this PR as wontfix. The fix for the other issue should shut up ubsan too, hopefully.

2024-05-31 06:51 UTC, closed without merging