8333129: Move ShrinkHeapInSteps flag to Serial GC
openjdk/jdk pull request #19452
Opened 2024-05-29 12:36 UTC by zhengyu123

A trivial change that moves Serial GC specific flag `ShrinkHeapInSteps` to `serial_globals.hpp`

2024-05-29 15:41 UTC, zhengyu123 commented
/add label hotspot-gc

2024-05-29 15:42 UTC, zhengyu123 commented
/label add hotspot-gc

2024-05-30 07:06 UTC, dholmes-ora requested changes
@zhengyu123 I don't think we can do this in quite such a direct way. This flag was added in JDK 9 under [JDK-8146436](https://bugs.openjdk.org/browse/JDK-8146436) and applied to all GC's AFAICS. Over time it seems to have been relegated to only working with SerialGC, but I can still find articles that reference it for GC tuning e.g.

https://docs.oracle.com/en/java/javase/22/gctuning/factors-affecting-garbage-collection-performance.html

So if this is indeed only for SerialGC now then we need to check when it stopped applying elsewhere and whether all the relevant docs have been updated. Then I think we would need to deprecate it for non-Serial (which is tricky because the flag deprecation process isn't intended to be runtime selective like that). I need to flag this directly with our GC team

2024-05-30 07:49 UTC, kimbarrett commented
> @zhengyu123 I don't think we can do this in quite such a direct way. This flag was added in JDK 9 under [JDK-8146436](https://bugs.openjdk.org/browse/JDK-8146436) and applied to all GC's AFAICS. Over time it seems to have been relegated to only working with SerialGC, but I can still find articles that reference it for GC tuning e.g.

It was added in CardGeneration.  I'm not certain, but I think that class was only ever used by Serial and CMS.

2024-05-30 08:04 UTC, kimbarrett approved these changes
Looks good.  Disavowing triviality to give @dholmes-ora a chance to comment further.

2024-05-30 13:05 UTC, zhengyu123 commented
I can confirm that `ShrinkHeapInSteps` flag is only used in `CardGeneration` and `CardGeneration` is only used in Serial and CMS in JDK9u source.

2024-05-31 05:42 UTC, dholmes-ora commented
Apologies, I was mistakenly thinking that moving the flag would cause a runtime error for code not using Serial GC, but it will only cause an error if a VM were built without Serial GC support, which I don't think is possible.

I will file a RFE to get the GC Tuning guide updates (if @kimbarrett doesn't beat me to it :) ).

I also note that component-specific global flags don't advertise the fact they are global-specific.

2024-05-31 05:43 UTC, dholmes-ora approved these changes
Okay. Thanks

2024-05-31 13:00 UTC, closed without merging