JDK-8333522: JFR SwapSpace event might read wrong free swap space size
openjdk/jdk pull request #19574
Opened 2024-06-06 09:23 UTC by MBaesken

In some cgroups v2 based test system , a too large free swap space value has been observed.
The value should not be larger than total swap space.

2024-06-06 09:57 UTC, jerboaa reviewed
I see that if `sysinfo()` fails the return value might be negative. Should be account for that?

2024-06-06 12:45 UTC, jerboaa commented
> > I see that if `sysinfo()` fails the return value might be negative. Should we account for that?
> 
> There are a number of places where sysinfo return value check is omitted. I see 3 places in os_linux.cpp alone. probably it would be better to check this, but I am not sure why it was omitted and how often those failures occur in practise .

We could add an `assert(host_free_swap_val >= 0, "sysinfo failed?");`. That would at least guard for that case in debug builds. And it would show it's been considered.

2024-06-07 07:50 UTC, MBaesken commented
I added the suggested assert .

2024-06-07 09:31 UTC, jerboaa requested changes
Debug builds fail.

2024-06-07 09:31 UTC, jerboaa commented on src/hotspot/os/linux/os_linux.cpp
> +  assert(host_free_swap_val >= 0, "sysinfo failed?")
Missing semicolon.

2024-06-07 09:32 UTC, jerboaa commented
> btw should we check/assert all sysinfo return values (would probably be a separate PR) ?

Feel free to do that. In a separate PR/bug though.

2024-06-07 10:48 UTC, MBaesken commented
added the semicolon .

> Feel free to do that. In a separate PR/bug though.

Thinking more about the potentially  failing sysinfo -  could it be that we get in this case an uninitialized sysinfo struct and just happily use the values from there ?
For example here
https://github.com/openjdk/jdk/blob/master/src/hotspot/os/linux/os_linux.cpp#L287

2024-06-07 11:52 UTC, jerboaa commented
> > Feel free to do that. In a separate PR/bug though.
> 
> Thinking more about the potentially failing sysinfo - could it be that we get in this case an uninitialized sysinfo struct and just happily use the values from there ? For example here https://github.com/openjdk/jdk/blob/master/src/hotspot/os/linux/os_linux.cpp#L287

Yes. Seems so.

2024-06-07 11:56 UTC, jerboaa approved these changes
LGTM. Consider adding the comment.

2024-06-07 11:56 UTC, jerboaa commented on src/hotspot/os/linux/os_linux.cpp
> +  jlong host_free_swap_val = MIN2(os::total_swap_space(), host_free_swap());
Thinking some more about this, it probably warrants a comment. Something like:

```
// os::total_swap_space() might return the containerized limit which might be
// less than host_free_swap(). The upper bound of free swap needs to be the lower of the two.
```

2024-06-07 15:24 UTC, jerboaa approved these changes

2024-06-08 11:24 UTC, tstuefe commented
> > > Feel free to do that. In a separate PR/bug though.
> > 
> > 
> > Thinking more about the potentially failing sysinfo - could it be that we get in this case an uninitialized sysinfo struct and just happily use the values from there ? For example here https://github.com/openjdk/jdk/blob/master/src/hotspot/os/linux/os_linux.cpp#L287
> 
> Yes. Seems so.

sysinfo, as far as I know, relies on /proc. Reading from /proc can theoretically fail. So, error handling would be good.

If you want to know if the observed errors stem from sysinfo failure, init the data structure, then, after the call, assert that the init values are overwritten.

2024-06-10 08:09 UTC, RealLucy approved these changes
<!-- Start of TOU acceptance message header -->
Hi @RealLucy, thanks for making a comment in an OpenJDK project!

All comments and discussions in the OpenJDK Community must be made available under the OpenJDK [Terms of Use](https://openjdk.java.net/legal/tou/). If you already are an OpenJDK [Author](https://openjdk.java.net/bylaws#author), [Committer](https://openjdk.java.net/bylaws#committer) or [Reviewer](https://openjdk.java.net/bylaws#reviewer), please click [here](https://bugs.openjdk.java.net/secure/CreateIssue.jspa?pid=11300&issuetype=1) to open a new issue so that we can record that fact. Please Use "Add GitHub user RealLucy" for the summary.

If you are not an OpenJDK Author, Committer or Reviewer, simply check the box below to accept the OpenJDK Terms of Use for your comments.
<!-- End of TOU acceptance message header -->
 - [ ]  I agree to the [OpenJDK Terms of Use](https://openjdk.java.net/legal/tou/) for all comments I make in a project in the [OpenJDK GitHub organization](https://github.com/openjdk).
<!-- Start of TOU acceptance message footer -->
Your comment will be automatically restored once you have accepted the OpenJDK [Terms of Use](https://openjdk.java.net/legal/tou/).
<!-- End of TOU acceptance message footer -->
<!-- Original message to be restored:
LGTM.
-->

2024-06-10 08:13 UTC, MBaesken commented
Thanks for the reviews !

/integrate

2024-06-10 08:14 UTC, closed without merging

2025-01-29 07:50 UTC, wkia commented
How do you check the assertion passes in the PR? AFAIU PR checks release build only. Or am I wrong?

2025-01-29 09:43 UTC, jerboaa commented
> How do you check the assertion passes in the PR? AFAIU PR checks release build only. Or am I wrong?

You don't. At least not in the PR. It's only been observed when exercising this code and that on a debug build (fastdebug should do). E.g. `containers/docker/TestJFREvents.java` test.

2025-01-30 08:28 UTC, wkia commented
Yes, I've got the assertion failure when running JTREG tests in a container on a fastdebug build. Created https://bugs.openjdk.org/browse/JDK-8349035

Sorry, I believe this change was wrong: since `OSContainer::memory_and_swap_limit_in_bytes()`, and then `os::total_swap_space()`, can return a negative value, `os::total_swap_space()` call shouldn't be used in `MIN2`. The case is actually processed in the code below the changed line, so I guess necessary changes should be made there, under `if (OSContainer::is_containerized()) { ... `