JDK-8334239: Introduce macro for ubsan method/function exclusions
openjdk/jdk pull request #19722
Opened 2024-06-14 13:39 UTC by MBaesken

A number of functions/methods have to be excluded from ubsan detection (e.g. because they do things that ubsan warns about, however it is still valid what is done there).
We can simplify this by introducing a macro (similar to asan-related ATTRIBUTE_NO_ASAN, see sanitizers/address.hpp).
Currently something like this is used :
```
#if defined(__clang__) || defined(__GNUC__)
__attribute__((no_sanitize("undefined")))
#endif
```

2024-06-17 05:34 UTC, dholmes-ora requested changes
In keeping with address.hpp and leak.hpp the header would either be called undefinedbehaviour.hpp or just ub.hpp for short.

I think the actual attribute would read better if placed on the line before the function definition.

Thanks.

2024-06-17 06:13 UTC, tstuefe commented
> In keeping with address.hpp and leak.hpp the header would either be called undefinedbehaviour.hpp or just ub.hpp for short.
> 
> I think the actual attribute would read better if placed on the line before the function definition.
> 
> Thanks.

I vote for ubsan.hpp and asan.hpp, or for a common header sanitizer.hpp.

2024-06-17 06:46 UTC, MBaesken commented
> I think the actual attribute would read better if placed on the line before the function definition.

I placed it on the line before the function.

2024-06-17 08:14 UTC, dholmes-ora commented
> I vote for ubsan.hpp and asan.hpp, or for a common header sanitizer.hpp.

That's a suggestion that should have been made when we added asan and lsan support at the beginning if last year. The "san" in the name is redundant with the "sanitizers" in the path.

2024-06-17 10:54 UTC, tstuefe commented
> Under 'sanitizers' there would be a header for one sanitizer called 'ubsan' - that naming might be a little redundant but would still make sense because that#s the name of the tool ; but I can live with both ub.hpp or ubsan.hpp . Are there any other opinions ?

I'm fine with all proposals so far.

2024-06-19 07:28 UTC, MBaesken commented
I changed the header name from ubsan.hpp to ub.hpp .

2024-06-19 07:49 UTC, stefank reviewed
I've listed some whitespace and punctuation nits.

I have a question/comment about this comment:
```
... special or even 'dangerous', for example causing desired signals/crashes or *overflows*.
```

Do we really intend to use ATTRIBUTE_NO_UBSAN to silence overflow issues? Don't we want to fix all of those?

2024-06-19 07:49 UTC, stefank commented on src/hotspot/share/sanitizers/ub.hpp
> +#ifndef SHARE_SANITIZERS_UB_HPP
```suggestion
 */

#ifndef SHARE_SANITIZERS_UB_HPP
```

2024-06-19 07:49 UTC, stefank commented on src/hotspot/share/sanitizers/ub.hpp
> +
```suggestion

```

2024-06-19 07:49 UTC, stefank commented on src/hotspot/share/sanitizers/ub.hpp
> +// example causing desired signals/crashes or overflows
```suggestion
// example causing desired signals/crashes or overflows.
```

2024-06-19 07:54 UTC, tstuefe approved these changes
good, if you take @stefank's suggestions

2024-06-19 09:05 UTC, MBaesken commented
> Do we really intend to use ATTRIBUTE_NO_UBSAN to silence overflow issues? Don't we want to fix all of those?

Some stuff needs fixing in external libs, that can take some  (maybe a lot) of  time.  Other coding might already handle overflows but only after  the overflow happened; so ubsan is triggered  but the coding is fine.
For now I would be in a first step already happy to be able to *build* with ubsan enabled  (we are close to this but not 100% there, I still have to use some patches on top of OpenJDK).

2024-06-19 09:12 UTC, stefank commented
> > Do we really intend to use ATTRIBUTE_NO_UBSAN to silence overflow issues? Don't we want to fix all of those?
> 
> Some stuff needs fixing in external libs, that can take some (maybe a lot) of time.

Will ATTRIBUTE_NO_UBSAN be used in those case?

> Other coding might already handle overflows but only after the overflow happened; so ubsan is triggered but the coding is fine.

This is the part that I'm questioning. I don't think this is true.

2024-06-19 11:59 UTC, MBaesken commented
I can remove the 2 word 'or overflows' if you want .
(there was at least a 'division by 0' example case here https://github.com/openjdk/jdk/pull/19674
where the case detected by ubsan was already handled; but the coding could be reorganized to avoid it at all ;
comment in that review from the area expert 'This whole ubsan thing is just random findings based on what tests we have.
We'll never be ubsan clean and I'm not sure it is advisable in all cases.' )

2024-06-19 12:30 UTC, stefank commented
> I can remove the 2 word 'or overflows' if you want.

Yes, please. Maybe there are places where overflows are OK, but I would like to get that better explained before we hint people that they can use ATTRIBUTE_NO_UBSAN to "silence" ubsan.

> the case detected by ubsan was already handled

I've seen this argument a number of times in the UBSAN PRs. My concern is that I'm not convinced that you can "handle" real UB issue. You can work around or fix them, but if you have a real UB and and try to silence ubsan, then you still have the UB and the compiler is within rights to throw away the code that "handles" the issue. Over the years we have seen a few issues where this happens: some if statements check for overflows, but the checks were unexpectedly removed by the compiler.

2024-06-19 13:43 UTC, stefank reviewed
Thanks for making the change. I think this looks good, minus one nit in the whitespace change.

2024-06-19 13:43 UTC, stefank commented on src/hotspot/share/sanitizers/ub.hpp
> +#endif // SHARE_SANITIZERS_UB_HPP
You removed one too many blank lines here. It used to be two, now there are none.

2024-06-19 14:41 UTC, stefank approved these changes

2024-06-19 18:56 UTC, kimbarrett approved these changes
Looks good.

2024-06-20 06:14 UTC, MBaesken commented
Thanks for the reviews !

/integrate

2024-06-20 06:15 UTC, closed without merging

2024-06-24 05:21 UTC, dholmes-ora reviewed
Apologies - my review of your updates in response to my comments never got submitted.