8334502: gtest/GTestWrapper.java fails on armhf due to LogDecorations.iso8601_utctime_test
openjdk/jdk pull request #19782
Opened 2024-06-19 02:43 UTC by vpa1977

Due to time_t transition time_t is now 64bit on Ubuntu. zone_hours and zone_min are printed using %02d specifier. This causes random memory to be printed.

2024-07-15 02:31 UTC, dholmes-ora requested changes

2024-07-15 02:31 UTC, dholmes-ora commented on src/hotspot/share/runtime/os.cpp
>      ((abs_local_to_UTC % seconds_per_hour) / seconds_per_minute);
I think you need to cast the expression to `int` to ensure the compiler won't complain, regardless of how `time_t` may actually be declared.

2024-07-16 05:44 UTC, dholmes-ora approved these changes
Looks good. Thanks

2024-07-16 20:46 UTC, vpa1977 commented
/integrate

2024-07-17 04:41 UTC, dholmes-ora commented
@vpa1977 hotspot changes require two reviewers before integration. Thanks

2024-07-17 06:42 UTC, vpa1977 commented
/label remove sponsor

2024-07-17 06:45 UTC, vpa1977 commented
> @vpa1977 hotspot changes require two reviewers before integration. Thanks

Hi, 

@dholmes-ora I apologise for the mistake - the PR header had only 1 reviewer. I have tried to remove sponsor label, but that is not a valid label. Could you please advice how to proceed?

Best Regards, 
 Vladimir.

2024-07-17 08:39 UTC, shipilev approved these changes
I was initially concerned we are narrowing to `int` to please the format specifiers. Normally, I would have expected us to work out a format specifier based on `time_t` size, and put it in `globalDefinitions.hpp`. But this looks okay as the unblocking fix.

2024-07-17 09:42 UTC, shipilev commented
/sponsor

2024-07-17 09:43 UTC, closed without merging

2024-07-17 09:44 UTC, shipilev commented
> @dholmes-ora I apologise for the mistake - the PR header had only 1 reviewer. I have tried to remove sponsor label, but that is not a valid label. Could you please advice how to proceed?

My review is the second one, so we can proceed. Normally, you just wait for more reviewers, even if you have said `/integrate`.

2024-07-17 20:00 UTC, vpa1977 commented
> I was initially concerned we are narrowing to `int` to please the format specifiers. Normally, I would have expected us to work out a format specifier based on `time_t` size, and put it in `globalDefinitions.hpp`. But this looks okay as the unblocking fix.

Hmm, actually [`long        tm_gmtoff;`](https://github.com/vpa1977/jdk/blob/ff97727f9a7141451dcc9a2565d277368c4b5d99/src/hotspot/share/runtime/os.cpp#L183) is getting assigned to time_t and in the alternate branch we are doing a [static cast](https://github.com/vpa1977/jdk/blob/ff97727f9a7141451dcc9a2565d277368c4b5d99/src/hotspot/share/runtime/os.cpp#L187C6-L187C7). I guess the correct fix should've been changing [UTC_to_local](https://github.com/vpa1977/jdk/blob/ff97727f9a7141451dcc9a2565d277368c4b5d99/src/hotspot/share/runtime/os.cpp#L180) to long.

2024-07-18 05:22 UTC, dholmes-ora commented
> I was initially concerned we are narrowing to `int` to please the format specifiers. Normally, I would have expected us to work out a format specifier based on `time_t` size, and put it in `globalDefinitions.hpp`. But this looks okay as the unblocking fix.

Those two variables, like many others in that code are very obviously just small integer values. I think `time_t` use should be minimised as much as possible e.g. `seconds_per_minute` et al. should really just be int values IMO.

> correct fix should've been changing [UTC_to_local](https://github.com/vpa1977/jdk/blob/ff97727f9a7141451dcc9a2565d277368c4b5d99/src/hotspot/share/runtime/os.cpp#L180) to long

If you do that won't it just introduce different conversion issues later in the code. This whole code is really quite a mess with regards to types, but that is partly because the API and structures used are also a mess when it comes to types.

2024-07-18 06:38 UTC, vpa1977 commented
> If you do that won't it just introduce different conversion issues later in the code. This whole code is really quite a mess with regards to types, but that is partly because the API and structures used are also a mess when it comes to types.


We might get something like this https://github.com/openjdk/jdk/commit/63005eaea5ddb5eee5d826433733a57741212af5 - removing both of static casts that I have introduced, and trading a static cast in Windows branch for a static cast in AIX one.
But I am not sure that I should introduce a change that touches the architecture that I can not test.

2024-07-18 07:29 UTC, dholmes-ora commented
Note that in general we do not use `long` in shared code precisely because its size is platform dependent.

2024-07-18 07:35 UTC, shipilev commented
Sorry, I did not mean that a follow-up work would be needed. I agree the cast is fine. It would probably be a bit less confusing to me to cast right in `printf` argument block, so it would be obvious no calculations are affected, and we are really only catering for the format specifiers. But this is a minor thing that does not deserve a follow-up, really.