8334868: Ensure CheckUninstallModalHook is called in WPageDialogPeer._show
openjdk/jdk pull request #19867
Opened 2024-06-24 20:16 UTC by aivanov-jdk

This is somewhat a continuation for [JDK-8307160](https://bugs.openjdk.org/browse/JDK-8307160) and [JDK-8334509](https://bugs.openjdk.org/browse/JDK-8334509).

The former removed the `doIt` flag in #18584, but it introduced a regression.  
The regression is resolved by the latter in #19786, and it added the 'doIt' flag again.

I think using a flag makes the code less clear. When reading the code, one has to keep track of the current value of the `doIt` flag.

I raised my concern in [comments in PR 19786](https://github.com/openjdk/jdk/pull/19786#discussion_r1649191308):

> I'd rather keep `JNI_FALSE` here — it's more explicit and therefore clearer. You don't have to keep track of the value of `doIt` flag while reading the code.
> 
> In fact, I'd prefer no `doIt` flag at all… yet it makes handling the code below `if (ret)` slightly harder.

I came up with a solution which simplifies handling the clean-up. The solution relies on C++ destructors which are called when the declared objects go out of scope.

The C++ object wraps a lambda function to clean up and invokes this function in its destructor. Such C++ class has to be a templated class because there's no defined type to represent a lambda. The class has to be declared at the top of the file because it needs C++ linkage.

There are two `Cleaner` objects declared in the code of `Java_sun_awt_windows_WPageDialogPeer__1show`:

**`refCleaner`** is declared right after all the references to Java objects are initialised. The corresponding `refCleanup` lambda deletes all the references and replaces the `CLEANUP_SHOW` macro. Before JDK-8307160, the code jumped to a go-to label to perform the clean-up.

**`postCleaner`** is declared after `AwtDialog::CheckInstallModalHook` is called. Its lambda `postCleanup` uninstalls the modal hook and handles focus transfer as well as saves the updated printer parameters.

It is `postCleaner` that resolves the bug JDK-8334868 by ensuring `CheckUninstallModalHook` and `ModalActivateNextWindow` are called if `::PageSetupDlg` is called.

As the result of using `refCleaner`, all the `return` statements in the function use an explicit value, which makes the code cleaner. There's no need to use a `go to` statement or insert a macro to delete references to Java objects, about which one had to remember — the destructor of the `refCleaner` handles deleting references when `refCleaner` goes out of scope, that is when the function returns.

2024-06-26 23:42 UTC, alisenchung commented on src/java.desktop/windows/native/libawt/windows/awt_PrintJob.cpp
> +           AwtPrintControl::setPrintHDMode(env, self, setup.hDevMode);
what does setPrintHDMode and setPrintHDName do? do they need to be called as part of cleanup even if there is an exception and we return JNI_FALSE?

2024-06-26 23:42 UTC, alisenchung commented on src/java.desktop/windows/native/libawt/windows/awt_PrintJob.cpp
> +           AwtPrintControl::setPrintHDMode(env, self, setup.hDevMode);
i think this code preserves the printer settings after the dialog closes (and only on success before this fix), so is it possible in the case the printer is removed and causes an exception, we shouldn't preserve these settings?

2024-06-27 11:26 UTC, TheShermanTanker commented
It's been quite a while since I said that, so I don't fully remember what I was talking about, but I believe I was referring to the use of C\+\+'s std::unique\_ptr, which has the functionality for cleanup that we need. That is currently blocked by awt.dll not being allowed to use the C\+\+ Standard Library, but if one looks at the current awt.dll with dumpbin, awt.dll is actually already is linked to msvcp.dll, meaning it already uses C\+\+ Standard Library somehow (I don't know what exactly makes it dependent on msvcp.dll)

2024-06-27 12:54 UTC, aivanov-jdk commented
> …I believe I was referring to the use of C++'s std::unique_ptr, which has the functionality for cleanup that we need.

Yes, `std::unique_ptr` could be useful for handling automatic deallocation of objects created with the `new` operator.

It won't help with releasing references to Java objects though.

> That is currently blocked by awt.dll not being allowed to use the C++ Standard Library, but if one looks at the current awt.dll with dumpbin, awt.dll is actually already is linked to msvcp.dll, meaning it already uses C++ Standard Library somehow (I don't know what exactly makes it dependent on msvcp.dll)

I remember STL has been banned from AWT code, yet I don't know the reasons for it. It could be to keep the size smaller.

I can see that `awt.dll` depends on `msvcp140.dll` and imports one function from it: `?_Xlength_error@std@@YAXPEBD@Z`. It doesn't look like the C++ Standard Library is used. I can't find where it comes from though… It could be worth getting rid of this dependency.

I built a small sample app which uses `std::unique_ptr` and `std::make_unique` and it does not depend on `msvcp140.dll` at all. This makes sense, template libraries are header-only and will become part of the executable (or the dynamic library).

The only references to `std` namespace that I found in client are in `ShellFolder.cpp` which uses `std::bad_alloc`, it uses this type in `catch` blocks and it may throw an object of this class.

So, it looks `awt.dll` doesn't use the C++ Standard Library.

However, using C++ objects with [RAII](https://en.wikipedia.org/wiki/Resource_acquisition_is_initialization) makes the code shorter and frees the programmer from repeating clean-up blocks¹.

Indeed, it's already used by C++ classes in AWT: [`JNILocalFrame`](https://github.com/openjdk/jdk/blob/79a23017fc7154738c375fbb12a997525c3bf9e7/src/java.desktop/windows/native/libawt/windows/awt_Toolkit.h#L64-L77) and [`CriticalSection`](https://github.com/openjdk/jdk/blob/79a23017fc7154738c375fbb12a997525c3bf9e7/src/java.desktop/windows/native/libawt/windows/awt_Toolkit.h#L85-L119) along with its `Lock` class inside.

¹ Repeated clean-up blocks can be seen in #18584 in nearly all the files.

2024-06-27 13:12 UTC, aivanov-jdk commented
> > …I believe I was referring to the use of C++'s std::unique_ptr, which has the functionality for cleanup that we need.
> 
> Yes, `std::unique_ptr` could be useful for handling automatic deallocation of objects created with the `new` operator.
> 
> ~~It won't help with releasing references to Java objects though.~~

Since `std::unique_ptr` accepts a custom deleter, it may be used for deleting any object.

2024-06-27 13:15 UTC, TheShermanTanker commented
std::unique\_ptr has the option for a custom deleter, meaning it can be used to clean up Java objects and other cases where a simple delete call does not suffice, for instance

```c++
std::unique_ptr<jobject, void (*) (jobject*)> self(env->GetObjectField(target, AwtPrintDialog::controlID), [] (jobject* object) -> void { 
 env->DeleteLocalRef(*object); });
```

Admittedly for jobjects this is a lot more cumbersome, since instead of replacing the pointer with a smart pointer, you wrap the pointer inside a smart pointer... Which is unwieldy. It would be helpful if JNI had a jobject unique\_ptr type for C\+\+

2024-06-27 13:16 UTC, TheShermanTanker commented
Oops, you sent your correction about the custom deleter just as I sent my post

2024-06-27 13:30 UTC, aivanov-jdk commented
> It would be helpful if JNI had a jobject unique_ptr type for C++

But `std::unique_ptr` wasn't available when JNI had been conceived…

It could be added…

The declaration in your sample still looks cumbersome… or _unwieldy_ as you said. Writing a custom deleter for each `jobject` doesn't look good either.

Most local references don't require explicit `DeleteLocalRef`, which also helps, I guess.

> Oops, you sent your correction about the custom deleter just as I sent my post

C++ has got many new features… I'm learning these feature on the fly since I don't use C++ as often.

2024-06-28 06:32 UTC, alisenchung approved these changes

2024-07-10 18:16 UTC, prrace requested changes
Sorry, but I  don't see this as better or needed. I was the one who requested the current code  and I don't see the need for all this complexity.
Just do the minimum change to make sure we do CheckUninstallModalHook is called.

2026-02-12 14:52 UTC, aivanov-jdk commented
/open

2026-04-20 16:41 UTC, aivanov-jdk commented
This PR is superseded by https://github.com/openjdk/jdk/pull/30207. I re-worked the approach there.

2026-04-20 16:41 UTC, closed without merging