JDK-8333144: docker tests do not work when ubsan is configured
openjdk/jdk pull request #19907
Opened 2024-06-26 13:32 UTC by MBaesken

Currently when we run with ubsan - enabled binaries (configure option --enable-ubsan, see [JDK-8298448](https://bugs.openjdk.org/browse/JDK-8298448)), the docker tests do not work.

We find this in the test output

[STDOUT]
/jdk/bin/java: error while loading shared libraries: libubsan.so.1: cannot open shared object file: No such file or directory

The container where the test is executed does not contain the ubsan package; we might skip the test in this case.

2024-07-24 14:11 UTC, MBaesken commented
Hello, any input on this ?
Currently the situation with the jtreg tests is not good when running ubsan-enabled binaries .

So we have to check for ubsan (see the PR for an example) or install  ubsan into the docker (or podman or ...) container .

2024-07-25 01:54 UTC, dholmes-ora reviewed
On the one hand this seems like a "Dr Dr it hurts when I do this" kind of problem. On the other hand it only affects the docker testing so I'm inclined to let it in, even though it is a bit of a blunt instrument (what if ubsan is installed in the container and someone wants to run with it enabled there?).

2024-07-26 04:27 UTC, dholmes-ora commented
I think others who have more investment in this area need to weigh in. I don't know the implications for our infra folk if we need to ensure ubsan is installed.

2024-07-26 07:38 UTC, MBaesken commented
> I think others who have more investment in this area need to weigh in. I don't know the implications for our infra folk if we need to ensure ubsan is installed.

I think this would be in the standard container config / BUILDFILE we use for the tests.  So if all works well, no implications.

On the other hand, we could also just run the ubsan - based tests with an own exclude/problem list and exclude the docker test that currently cannot work. That needs a separate list but no other src changes like this PR or the idea with adjusted docker container config.

2024-07-30 09:31 UTC, RealCLanger commented
I would prefer to add the required ubsan libraries to the container used for testing when testing an ubsan enabled build. Can we achieve this?

2024-07-30 13:27 UTC, MBaesken commented
> I would prefer to add the required ubsan libraries to the container used for testing when testing an ubsan enabled build. Can we achieve this?

I added  libubsan1 to the container  (tested it and works nicely, should do no harm if  we test a non-ubsan build).
Should we go this way ?
If so I could remove the WhiteBox related changes (or keep it for other usages).
I also tried to add a WhiteBox based check to  'DockerTestUtils.java' but this seems not to work. But as i said it is probably not necessary.

2024-07-31 07:19 UTC, RealCLanger requested changes
I think adding libubsan1 to the test container is the best way to go. If it cannot be made conditional on ubsan builds then be it so. Then the Whitebox changes should be removed obviously.

2024-07-31 07:19 UTC, RealCLanger commented on test/hotspot/jtreg/containers/docker/DockerBasicTest.java
> - * @run driver DockerBasicTest
you remove @build and @run directives from the test - probably not desired.

2024-07-31 14:05 UTC, MBaesken commented
I removed the WhiteBox stuff.
Maybe David could give the change a try in the Oracle CI if that's possible ?

2024-07-31 20:57 UTC, RealCLanger approved these changes
Fine for me.

2024-08-01 05:49 UTC, tstuefe commented
I have seen this too late.. some questions:

- Are we sure the images the tests use will always be Debian or Debian descendants? What about RHEL or Oracle Linux?
- How close does the libubsan have to be to the compiler used to build the tested JVM? After all, UBSAN is a compiler feature. Does this work for any version of GCC used to build the JVM? Or do we risk weird test errors if libubsan in the image is incompatible with the GCC version used when building the testee JVM?

2024-08-01 07:31 UTC, MBaesken commented
> Are we sure the images the tests use will always be Debian or Debian descendants? What about RHEL or Oracle Linux?

We use Ubuntu for the container test base image as default , see https://github.com/openjdk/jdk/blob/65646b5f81279a7fcef3ea04ef9894cf66f77a5a/test/lib/jdk/test/lib/containers/docker/DockerfileConfig.java#L47
To be more on the safe side (potentially the image can be switched with jdk.test.docker.image.name) we could add a check (and avoid adding the libubsan1 package if it is not ubuntu).

Regarding compatibility, I've seen no issues (and if you compile _without_ ubsan you would not reference the libubsan1 anyway). So it is for some special configuration.

2024-08-01 21:47 UTC, dholmes-ora commented
> Maybe David could give the change a try in the Oracle CI if that's possible ?

Testing ...

2024-08-02 05:50 UTC, dholmes-ora commented
This had no impact on our tier5 testing where we test container related stuff.

2024-08-02 06:15 UTC, MBaesken commented
Hi David, thanks for testing.
Thinking more about it, should I test in ` generateDockerFile ` for  `baseImage`  name containing ubuntu, so that people using a system property to set an own special image do not run into issues with the added `RUN apt-get install libubsan1`     ?

2024-08-02 06:25 UTC, tstuefe commented
> > Are we sure the images the tests use will always be Debian or Debian descendants? What about RHEL or Oracle Linux?
> 
> We use Ubuntu for the container test base image as default , see
> 
> https://github.com/openjdk/jdk/blob/65646b5f81279a7fcef3ea04ef9894cf66f77a5a/test/lib/jdk/test/lib/containers/docker/DockerfileConfig.java#L47
> 
> To be more on the safe side (potentially the image can be switched with jdk.test.docker.image.name) we could add a check (and avoid adding the libubsan1 package if it is not ubuntu).
> 
> Regarding compatibility, I've seen no issues (and if you compile _without_ ubsan you would not reference the libubsan1 anyway). So it is for some special configuration.

Okay, thanks Matthias

2024-08-02 06:59 UTC, dholmes-ora commented
@MBaesken I know nothing about container setup, sorry.

2024-08-02 14:27 UTC, tstuefe approved these changes
Looks reasonable

2024-08-05 05:52 UTC, MBaesken commented
/integrate

2024-08-05 05:57 UTC, closed without merging

2024-08-16 13:26 UTC, jerboaa commented
> If the added apt-get call causes issues for some people running the tests, we can easily add an ubuntu distro check in a follow up.

@MBaesken This breaks container tests on non Debian distros. Please add some form of property that needs to be set to install `libubsan1` on the test containers if you need that. It should have no impact on users not needing/using it. Thanks!

2024-08-16 14:08 UTC, tstuefe commented
> > If the added apt-get call causes issues for some people running the tests, we can easily add an ubuntu distro check in a follow up.
> 
> 
> 
> @MBaesken This breaks container tests on non Debian distros. Please add some form of property that needs to be set to install `libubsan1` on the test containers if you need that. It should have no impact on users not needing/using it. Thanks!

weird that Oracle reported no errors since I assume they test on what essentially is RHEL

2024-08-16 15:00 UTC, jerboaa commented
> > > If the added apt-get call causes issues for some people running the tests, we can easily add an ubuntu distro check in a follow up.
> > 
> > 
> > @MBaesken This breaks container tests on non Debian distros. Please add some form of property that needs to be set to install `libubsan1` on the test containers if you need that. It should have no impact on users not needing/using it. Thanks!
> 
> weird that Oracle reported no errors since I assume they test on what essentially is RHEL

It would depend whether or not skipped tests are flagged or not. The container tests get silently skipped if the container build of the image to test fails. That might be a reason.

2024-08-19 06:54 UTC, MBaesken commented
I created
https://bugs.openjdk.org/browse/JDK-8338550
8338550: Make libubsan1 installation in test container optional

2024-08-19 10:06 UTC, jerboaa commented
Thanks!