c1
openjdk/jdk pull request #19947
Opened 2024-06-28 16:44 UTC by suchismith1993

2024-08-27 17:15 UTC, TheRealMDoerr requested changes
Nice cleanup! I have a couple of small change requests.

2024-08-27 17:15 UTC, TheRealMDoerr commented on src/hotspot/cpu/ppc/macroAssembler_ppc.cpp
> +address MacroAssembler::call_c(address function_entry,relocInfo::relocType) {
Please restore the original line.

2024-08-27 17:15 UTC, TheRealMDoerr commented on src/hotspot/cpu/ppc/macroAssembler_ppc.hpp
> +  address call_c(address function_entry, relocInfo::relocType rt = relocInfo::relocType::none) {
I think `relocInfo::none` should be used like above.

2024-08-27 17:15 UTC, TheRealMDoerr commented on src/hotspot/cpu/ppc/macroAssembler_ppc.hpp
> -
Please don't remove the empty line.

2024-08-27 17:15 UTC, TheRealMDoerr commented on src/hotspot/cpu/ppc/interp_masm_ppc_64.cpp
> +    call_c(CAST_FROM_FN_PTR(address, Interpreter::remove_activation_preserving_args_entry), relocInfo::none);
`relocInfo::none` can be omitted. It's the default.

2024-08-27 17:15 UTC, TheRealMDoerr commented on src/hotspot/cpu/ppc/stubGenerator_ppc.cpp
> +#undef __
I guess this was added unintentionally?

2024-08-27 17:15 UTC, TheRealMDoerr commented on src/hotspot/cpu/ppc/templateInterpreterGenerator_ppc.cpp
> +  __ call_c(CAST_FROM_FN_PTR(address, JavaThread::check_special_condition_for_native_trans), relocInfo::none);
`relocInfo::none` can be omitted. It's the default.

2024-08-28 20:14 UTC, TheRealMDoerr approved these changes
LGTM. Thanks for the update!

2024-08-28 20:16 UTC, TheRealMDoerr requested changes
One more thing: `C1_MacroAssembler::call_c_with_frame_resize` should be removed completely.

2024-08-29 08:06 UTC, TheRealMDoerr approved these changes
This looks good, now! Thank you!

2024-08-29 08:20 UTC, TheRealMDoerr commented
> @TheRealMDoerr i would need another review for this right ?

Yes, please. It's not classified as trivial. Maybe you can ask somebody from your team.

2024-09-02 13:01 UTC, varada1110 commented
LGTM!
tier1 testing done on linux-ppc64le with both release and fastdebug, no related failures.
Thank you

2024-09-02 13:51 UTC, TheRealMDoerr commented
I had already tested on linux-ppc64le. What about AIX?

2024-09-02 20:41 UTC, TheRealMDoerr requested changes

2024-09-02 20:41 UTC, TheRealMDoerr commented on src/hotspot/cpu/ppc/macroAssembler_ppc.hpp
> +    return call_c((FunctionDescriptor*)function_entry, rt);
This breaks ABIv1. Please use a cast to `const FunctionDescriptor*` and move your new function below ` address call_c(const FunctionDescriptor* function_descriptor, relocInfo::relocType rt);`.

2024-09-03 16:01 UTC, TheRealMDoerr commented on src/hotspot/cpu/ppc/macroAssembler_ppc.hpp
> +    // For tail calls: only branch, don't link, so callee returns to caller of this function.
This looks messed up! I requested to move it down, not do duplicate any function declaration. Also, the comment indentation is bad.

2024-09-03 16:03 UTC, TheRealMDoerr commented on src/hotspot/cpu/ppc/macroAssembler_ppc.hpp
> +    // For tail calls: only branch, don't link, so callee returns to caller of this function.
Please still repair the indentation.

2024-09-03 16:14 UTC, TheRealMDoerr approved these changes
LGTM. We should retest it on AIX.

2024-09-03 22:10 UTC, TheRealMDoerr requested changes
You effectively changed the type from `relocInfo::runtime_call_type` to `relocInfo::none` in c1_LIRAssembler_ppc.cpp. This is causing problems with ABIv1.
The VM seems to work when switching off C1 on AIX. So, the other files should be ok.

2024-09-04 08:06 UTC, suchismith1993 commented
> You effectively changed the type from `relocInfo::runtime_call_type` to `relocInfo::none` in c1_LIRAssembler_ppc.cpp. This is causing problems with ABIv1. The VM seems to work when switching off C1 on AIX. So, the other files should be ok.

So do we then call in c1_LIRA using __ call_c(copyfunc_addr, relocInfo::runtime_call_type); ?

2024-09-04 09:23 UTC, TheRealMDoerr commented
> > You effectively changed the type from `relocInfo::runtime_call_type` to `relocInfo::none` in c1_LIRAssembler_ppc.cpp. This is causing problems with ABIv1. The VM seems to work when switching off C1 on AIX. So, the other files should be ok.
> 
> So do we then call in c1_LIRA using __ call_c(copyfunc_addr, relocInfo::runtime_call_type); ?

Yes, for all 4 `call_c` in c1_LIRAssembler_ppc.cpp.

2024-09-04 12:09 UTC, TheRealMDoerr approved these changes
LGTM. Hopefully the tests will pass on AIX.

2024-09-04 20:09 UTC, TheRealMDoerr commented
@varada1110: Can you use "Approve" instead of "Comment", please? Otherwise, your review doesn't get recorded properly.

2024-09-05 09:26 UTC, TheRealMDoerr commented
Test results look good this time. I think it's good to go.

2024-09-05 09:56 UTC, suchismith1993 commented
> Test results look good this time. I think it's good to go.

Hi Martin, you mean the results for AIX ?

2024-09-05 10:37 UTC, varada1110 approved these changes
LGTM! Thank you Martin for testing.

2024-09-05 14:29 UTC, suchismith1993 commented
thank you all for the review and tests.

2024-09-05 14:29 UTC, suchismith1993 commented
/integrate

2024-09-05 15:44 UTC, TheRealMDoerr commented
/sponsor

2024-09-05 15:45 UTC, closed without merging