8335743: jhsdb jstack cannot print some information on the waiting thread
openjdk/jdk pull request #20049
Opened 2024-07-05 09:23 UTC by tkiriyama

This bug was introduced by JDK-8284161. "Object.wait (long timeoutMillis)" was changed to call "Object.wait0 (long timeoutMillis)" in JDK-8284161.

When "jhdsb jstack" is executed, the stack and lock information are printed in "sun.jvm.hotspot.runtime.JavaVFrame.printLockInfo(PrintStream tty, int frameCount)". This method checks whether the method is java.lang.Object.wait (...) and then reports the waitstate only if the check passes.
https://github.com/openjdk/jdk/blob/7bc8f9c150cbf457edf6144adba734ecd5ca5a0f/src/jdk.hotspot.agent/share/classes/sun/jvm/hotspot/runtime/JavaVFrame.java#L103

```
      if (getMethod().getName().asString().equals("wait") &&
          getMethod().getMethodHolder().getName().asString().equals("java/lang/Object")) {
```

However, after JDK-8284161, the waiting thread waits on "java.lang.Object.wait0 (long timeoutMillis)", so it no longer reports the waitstate.

I changed "printLockInfo(PrintStream tty, int frameCount)" to check for "java.lang.Object.wait0 (...)".
I confirmed that the lock information is correctly printed with this fix.
I tested hotspot/jtreg/serviceability/sa/ and jdk/sun/tools/jhsdb/heapconfig/, and there were no regressions by this fix.

Would anyone review this change, please?

2024-07-08 06:53 UTC, dholmes-ora requested changes
Good catch on the underlying issue. I think the test needs an adjustment though.

Thanks

2024-07-08 06:53 UTC, dholmes-ora commented on test/hotspot/jtreg/serviceability/sa/LingeredAppWithLock.java
> +        Thread objectWait = new Thread(() -> waitMethod(new Object()));
Use of `new Object()` could be problematic here as the JIT can recognise that this is a non-escaping object and elide the synchronization.

2024-07-08 17:55 UTC, plummercj approved these changes
Looks good. Thank you for adding the test.

2024-07-09 18:26 UTC, kevinjwalls approved these changes

2024-07-10 06:42 UTC, dholmes-ora approved these changes
Update looks good. Thanks

2024-07-10 08:54 UTC, tkiriyama commented
Thank you all for the reviews. 

/integrate

2024-07-11 02:43 UTC, dholmes-ora commented
/sponsor

2024-07-11 02:44 UTC, closed without merging