JDK-8335778: runtime/ClassInitErrors/TestStackOverflowDuringInit.java fails on ppc64 platforms after JDK-8334545
openjdk/jdk pull request #20053
Opened 2024-07-05 12:26 UTC by MBaesken

stdout shows :
 "The Java thread stack size specified is too small. Specify at least 384k"
Previously the test was done only on x64 platforms (comment said that it only works there 'in desired way') .

2024-07-08 05:57 UTC, dholmes-ora requested changes

2024-07-08 05:57 UTC, dholmes-ora commented on test/hotspot/jtreg/runtime/ClassInitErrors/TestStackOverflowDuringInit.java
> + * @requires vm.simpleArch == "x64" | vm.simpleArch == "aarch64" | vm.simpleArch == "riscv64"
Please just increase the stack size. The test should run okay everywhere now.

2024-07-08 08:15 UTC, MBaesken commented
Hi David, I adjusted to Xss setting.

2024-07-08 21:39 UTC, dholmes-ora reviewed
Sorry for delay, just testing this change in our CI ...

2024-07-10 02:18 UTC, dholmes-ora approved these changes
Seems to work fine here too.

Thanks

2024-07-10 07:10 UTC, MBaesken commented
Hi David, thanks for the review !

2024-07-10 07:52 UTC, MBaesken commented
/integrate

2024-07-10 07:53 UTC, closed without merging