changes for removing power7 and below
openjdk/jdk pull request #20262
Opened 2024-07-19 17:32 UTC by suchismith1993

2025-01-23 07:54 UTC, suchismith1993 commented
/open

2025-04-02 20:36 UTC, TheRealMDoerr commented on make/autoconf/flags-cflags.m4
> +        $1_CFLAGS_CPU="-mcpu=powerpc64 -mtune=power8"
-mcpu=power8 is missing.

2025-04-02 20:36 UTC, TheRealMDoerr commented on src/hotspot/cpu/ppc/macroAssembler_ppc.cpp
> +Register addr_base, Label &retry, Label &failed, bool cmpxchgx_hint, int size) {
Please restore indentation.

2025-04-02 20:36 UTC, TheRealMDoerr commented on src/hotspot/cpu/ppc/macroAssembler_ppc.cpp
> +  const int instruction_type = size;
I think it would be better to remove instruction_type and replace the remaining usages.

2025-04-02 20:36 UTC, TheRealMDoerr commented on src/hotspot/cpu/ppc/macroAssembler_ppc.cpp
> +  const int instruction_type = size;
Same here.

2025-04-02 20:36 UTC, TheRealMDoerr commented on src/hotspot/cpu/ppc/vm_version_ppc.cpp
>        FLAG_SET_ERGO(UsePopCountInstruction, true);
Indentation should be adapted. Or even better set the default in globals_ppc.hpp to true and simplify this logic.

2025-04-02 20:36 UTC, TheRealMDoerr commented on src/hotspot/cpu/ppc/vm_version_ppc.cpp
>        FLAG_SET_ERGO(SuperwordUseVSX, true);
Same here.

2025-04-02 20:36 UTC, TheRealMDoerr commented on src/hotspot/os_cpu/linux_ppc/atomic_linux_ppc.hpp
> +    "   lbarx   %[old_value], 0, %[dest]               \n"
Please adapt the indentation of the modified lines.

2025-04-02 20:36 UTC, TheRealMDoerr commented on src/hotspot/cpu/ppc/vm_version_ppc.hpp
> -  static bool has_lqarx()   { return (_features & lqarx_m) != 0; }
Why are the other Power7 and older instruction checks not removed?

2025-04-07 08:21 UTC, suchismith1993 commented on src/hotspot/cpu/ppc/vm_version_ppc.hpp
> -  static bool has_lqarx()   { return (_features & lqarx_m) != 0; }
Hi @TheRealMDoerr  I removed the instructions mentioned in the issue. How can I determine which instructions were older ? Is there a file where it is mentioned specifically ?

2025-04-07 08:41 UTC, TheRealMDoerr commented on src/hotspot/cpu/ppc/vm_version_ppc.hpp
> -  static bool has_lqarx()   { return (_features & lqarx_m) != 0; }
The Power ISA has a section "Appendix E. Power ISA Instruction Set Sorted by Opcode" at the end. We require Power8 which matches "Power ISA v2.07". All instructions from v2.07 or older are available.

2025-04-08 15:23 UTC, suchismith1993 commented on src/hotspot/cpu/ppc/vm_version_ppc.hpp
> -  static bool has_lqarx()   { return (_features & lqarx_m) != 0; }
Hi @TheRealMDoerr  some instructions have "PPC" written in version..what does this mean ? 
Also I do not see mfdscr in the appendix

2025-04-08 16:04 UTC, suchismith1993 commented on src/hotspot/cpu/ppc/vm_version_ppc.hpp
> -  static bool has_lqarx()   { return (_features & lqarx_m) != 0; }
Also should has_vsx be removed too ?

2025-04-08 16:16 UTC, TheRealMDoerr commented on src/hotspot/cpu/ppc/vm_version_ppc.hpp
> -  static bool has_lqarx()   { return (_features & lqarx_m) != 0; }
"PPC" is older than V2.07. "mfsdcr" is a special version of "mfspr". "has_vsx" is also given on Power8.

2025-04-17 17:01 UTC, TheRealMDoerr reviewed
Very nice that we can get rid of so much code!

2025-04-17 17:01 UTC, TheRealMDoerr commented on src/hotspot/cpu/ppc/vm_version_ppc.cpp
>                 (has_vshasig() ? " sha"     : ""),
The check for `has_vshasig()` is no longer needed (v2.07). I guess that " sha" should still get printed because some tests check for it.

2025-04-21 08:01 UTC, suchismith1993 commented on src/hotspot/cpu/ppc/ppc.ad
>  instruct convF2I_regF_ExEx(iRegIdst dst, regF src) %{
@TheRealMDoerr  There is expand after the instruction..so should it be completely removed ?

2025-04-23 15:48 UTC, TheRealMDoerr commented on src/hotspot/cpu/ppc/ppc.ad
> -  predicate(VM_Version::has_isel());
This makes other instruct with `match(Set dst (MaxI src1 src2));` and higher cost obsolete. `maxI_reg_reg_Ex` should be removed. There are more cases in which you have removed a predicate which makes other instruct blocks obsolete. Please check!

2025-04-29 14:50 UTC, suchismith1993 commented on src/hotspot/cpu/ppc/ppc.ad
>    expand %{
HI @TheRealMDoerr  
I tried removing moveD2L_reg_stack as it is the only usage in ad file. 
But the build fails . Any exception to this rule ?

2025-04-30 21:47 UTC, TheRealMDoerr commented on src/hotspot/cpu/ppc/vm_version_ppc.cpp
> -               (has_vcipher() ? " aes"     : ""),
" aes" seems to be still needed in the feature string. See TestAESIntrinsicsOnSupportedConfig.java and TestAESIntrinsicsOnUnsupportedConfig.java.

2025-04-30 21:48 UTC, TheRealMDoerr commented on src/hotspot/cpu/ppc/assembler_ppc.inline.hpp
> +inline bool Assembler::lxarx_hint_exclusive_access()                                          { return true; }
Should better be removed completely.

2025-04-30 21:49 UTC, TheRealMDoerr commented on src/hotspot/cpu/ppc/c1_LIRAssembler_ppc.cpp
> +      Address       addr = Address();
`addr` is no longer used.

2025-04-30 21:50 UTC, TheRealMDoerr commented on src/hotspot/cpu/ppc/c1_LIRAssembler_ppc.cpp
> +      Address       addr = Address();
`addr` is no longer used.

2025-05-02 12:13 UTC, suchismith1993 commented on src/hotspot/cpu/ppc/assembler_ppc.inline.hpp
> +inline bool Assembler::lxarx_hint_exclusive_access()                                          { return true; }
Hi @TheRealMDoerr hint_exclusive_access flag should be set to true ?

2025-05-02 12:36 UTC, suchismith1993 commented on src/hotspot/cpu/ppc/ppc.ad
>    expand %{
Hi @TheRealMDoerr  could you explain this ?

2025-05-02 15:53 UTC, TheRealMDoerr commented on src/hotspot/cpu/ppc/ppc.ad
>    expand %{
`moveD2L_reg_stack` is the only instruct which matches `Set dst (MoveD2L src)` where `dst` is a `stackSlotL` and `src` is a `regD`. If you remove it, C2 can't match it any more.

2025-05-14 12:57 UTC, TheRealMDoerr commented
Please merge and adapt https://github.com/openjdk/jdk/blob/a989245a2424d136f5d2a828eda666c3867b0f48/src/hotspot/cpu/ppc/vm_version_ppc.cpp#L311

2025-05-15 13:11 UTC, TheRealMDoerr commented on src/hotspot/cpu/ppc/vm_version_ppc.cpp
>        FLAG_SET_ERGO(PowerArchitecturePPC64, 0);
I think we should set it to 8, here.

2025-05-15 13:15 UTC, TheRealMDoerr commented on src/hotspot/cpu/ppc/vm_version_ppc.cpp
> +      FLAG_SET_ERGO(UseVectorByteReverseInstructionsPPC64, true);
I think this part should be reverted. It is still possible to switch off SuperwordUseVSX.

2025-05-15 13:16 UTC, TheRealMDoerr commented on src/hotspot/cpu/ppc/vm_version_ppc.cpp
> +
Please remove the extra newline.

2025-05-15 13:18 UTC, TheRealMDoerr commented on src/hotspot/cpu/ppc/vm_version_ppc.cpp
> +    FLAG_SET_DEFAULT(UseSHA256Intrinsics, true);
I think UseSHA256Intrinsics should only get enabled if UseSHA is enabled.

2025-05-15 13:19 UTC, TheRealMDoerr commented on src/hotspot/cpu/ppc/vm_version_ppc.cpp
> +    FLAG_SET_DEFAULT(UseSHA512Intrinsics, true);
Same here.

2025-05-15 13:22 UTC, TheRealMDoerr commented on src/hotspot/os_cpu/linux_ppc/atomic_linux_ppc.hpp
> +    "   cmpw    %[compare_value], %[old_value] \n"
Please increase indentation before \n.

2025-05-15 13:22 UTC, TheRealMDoerr commented on src/hotspot/os_cpu/linux_ppc/atomic_linux_ppc.hpp
> +      [loaded_value]             "=&r"   (loaded_value),
Indentation.

2025-05-15 15:57 UTC, TheRealMDoerr commented
> > d with -XX:-SuperwordUseVSX.
> 
> Any particular set of tests that rely on Superword optimisation ?

At least the following tests should still work:
`make run-test TEST=jtreg:compiler/c2 JTREG="VM_OPTIONS=-XX:-SuperwordUseVSX"`
We need to support -XX:-SuperwordUseVSX as workaround for vector bugs.

2025-05-16 08:37 UTC, TheRealMDoerr commented
Thanks! Looks good, now. We'll test it, too. A 2nd review will be required.

2025-05-19 09:36 UTC, TheRealMDoerr requested changes
Tests are failing:
TestUseSHA256IntrinsicsOptionOnSupportedCPU.java
TestUseSHA512IntrinsicsOptionOnSupportedCPU.java
TestUseSHAOptionOnSupportedCPU.java
You need to restore the old logic for SHA flag handling (only remove `has_vshasig()`).

2025-05-19 13:05 UTC, suchismith1993 commented on src/hotspot/cpu/ppc/vm_version_ppc.cpp
> -  if (UseSecondarySupersTable && PowerArchitecturePPC64 < 7) {
@TheRealMDoerr  Should the check for UseSecondarySupersTable be present ?

2025-05-19 13:11 UTC, TheRealMDoerr commented on src/hotspot/cpu/ppc/vm_version_ppc.cpp
> -  if (UseSecondarySupersTable && PowerArchitecturePPC64 < 7) {
No. Removal should be fine.

2025-05-19 14:00 UTC, TheRealMDoerr commented
I also got failures in the following IR tests:
compiler/c2/irTests/ModINodeIdealizationTests.java
compiler/c2/irTests/ModLNodeIdealizationTests.java
compiler/c2/irTests/TestFPComparison.java
compiler/c2/irTests/TestIfMinMax.java
Can you reproduce those? I wonder if we have removed too much.

And while talking about removal, `enc_cmove_reg` and `enc_cmove_imm` seem to be unused.

2025-05-19 20:07 UTC, TheRealMDoerr commented on src/hotspot/cpu/ppc/vm_version_ppc.cpp
> +  if (FLAG_IS_DEFAULT(ConditionalMoveLimit)) {
This is incorrectly replaced. Should get removed. (Causes the mentioned test failures.)

2025-05-19 20:14 UTC, TheRealMDoerr commented on src/hotspot/cpu/ppc/vm_version_ppc.cpp
> +               (" aes"),
Maybe change to "ppc64 aes sha" and remove the extra lines?

2025-05-20 15:14 UTC, TheRealMDoerr commented on src/hotspot/cpu/ppc/ppc.ad
> -  %}
Now, you have a lot of empty lines! Also at other places where you removed code.

2025-05-20 15:14 UTC, TheRealMDoerr commented on src/hotspot/cpu/ppc/vm_version_ppc.cpp
> +               (" aes"),
Why did you revert this part?

2025-05-21 08:07 UTC, TheRealMDoerr approved these changes
Looks good. We'll retest it. 2nd review needed.

2025-05-21 08:47 UTC, TheRealMDoerr commented on make/autoconf/flags-cflags.m4
>          # Use ppc64 instructions, but schedule for power5
Would be nice to remove this outdated comment.

2025-05-21 20:11 UTC, TheRealMDoerr requested changes

2025-05-21 20:11 UTC, TheRealMDoerr commented on src/hotspot/cpu/ppc/vm_version_ppc.cpp
> +               "ppc64 sha aes%s%s%s%s",
This is now broken! Too many %s!

2025-05-22 04:21 UTC, suchismith1993 commented on src/hotspot/cpu/ppc/vm_version_ppc.cpp
> +               "ppc64 sha aes%s%s%s%s",
Yeah. Sorry about that. For some reason the files are not getting saved in the machine and older versions were getting pushed. Fixed now.

2025-05-23 09:21 UTC, dbriemann reviewed
Nice cleanup. I have some small suggestions.

2025-05-23 09:21 UTC, dbriemann commented on src/hotspot/cpu/ppc/c1_LIRAssembler_ppc.cpp
>        break;
Would it make sense to split this code into the two separate switch cases `_i2d` and `l2d`, now that the code has fewer lines?

2025-05-23 09:21 UTC, dbriemann commented on src/hotspot/cpu/ppc/c1_LIRAssembler_ppc.cpp
> +      __ fcfids(rdst, rdst);
Same as above. Could be split into separate switch cases.

2025-05-23 09:21 UTC, dbriemann commented on src/hotspot/cpu/ppc/stubGenerator_ppc.cpp
> +    // If supported set DSCR pre-fetch to deepest.
The `If supported` can be removed from the comment.

2025-05-23 14:11 UTC, TheRealMDoerr approved these changes

2025-05-26 08:26 UTC, closed without merging

2025-06-24 11:03 UTC, shqking commented
Hi, I came across VM crash with SIGILL after this patch.

## My local test environment

As I don't hava ppc64 hardware, I built one `ppc64le` Java binary with **cross-compilation** on Ubuntu-24.04 and ran `java -version` with **QEMU**. Here shows a snippet of the error log:

```
$ sudo chroot /sysroot/ppc64el /tmp/build-ppc64el/images/jdk/bin/java --version
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGILL (0x4) at pc=0x00007718c7817380, pid=121270, tid=121272
#
# JRE version:  (26.0) (fastdebug build )
# Java VM: OpenJDK 64-Bit Server VM (fastdebug 26-internal-git-9c3eaa49f7f, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-ppc64le)
# Problematic frame:
# v  ~BufferBlob::config_dscr 0x00007718c7817380
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to //core.121270)
#
# An error report file with more information is saved as:
# //hs_err_pid121270.log
[2.177s][warning][os] Loading hsdis library failed
#
#
qemu: uncaught target signal 6 (Aborted) - core dumped
environment: line 1: 121269 Aborted                 "$@"
```

## The unsupported instruction is `mfdscr`

I checked the instruction at the `pc=0x00007718c7817380`. It is `A6 02 63 7C    mfspr r3, 3`.
Hence I suspected if the following change in this PR might be related, i.e. `src/hotspot/cpu/ppc/vm_version_ppc.cpp`
See https://github.com/openjdk/jdk/pull/20262/files#diff-409e1c95e0846f4dbf17f425616970846bbc5fa105c5fb7e80402dc4663416beL95

```
// Power 8: Configure Data Stream Control Register.
config_dscr();
```

## Check the support of `mfdscr` in my environment

I built another Java binary with the code commit before this PR, i.e. `8357649: IGV: add block index to the supplemental node properties`.

Then I tried the following commands to check the value of `PowerArchitecturePPC64` and the support of `mfdscr` instruction in my environment. As shown below, it seems that `mfdscr` is **NOT** supported by default in my qemu environment.

1.  it's power9 which is >=8. it's as expected.

 
```
$ sudo chroot /sysroot/ppc64el /tmp/build-ppc64el/images/jdk/bin/java -XX:+PrintFlagsFinal --version | grep PowerArchitecturePPC64
    uintx PowerArchitecturePPC64                   = 9                                 {ARCH diagnostic} {ergonomic}
```

2. there is no `mfdscr`

```
$ sudo chroot /sysroot/ppc64el /tmp/build-ppc64el/images/jdk/bin/java -XX:+Verbose -version
Version: ppc64 fsqrt isel lxarxeh cmpb popcntb popcntw fcfids vand lqarx aes vpmsumb vsx ldbrx stdbrx sha darn L1_data_cache_line_size=128

ContendedPaddingWidth 128
openjdk version "25-internal" 2025-09-16
OpenJDK Runtime Environment (fastdebug build 25-internal-git-unknown)
OpenJDK 64-Bit Server VM (fastdebug build 25-internal-git-unknown, mixed mode)
```

3. `VM_Version::determine_features()` also treat `mfdscr` as illegal instructions

Note that `a602 037c` is changed to `0000 0000` after decoding.

```
$ sudo chroot /sysroot/ppc64el /tmp/build-ppc64el/images/jdk/bin/java -XX:+PrintAssembly --version

OpenJDK 64-Bit Server VM warning: PrintAssembly is enabled; turning on DebugNonSafepoints to gain additional output                                                        
Decoding cpu-feature detection stub at 0x00007964b385f380 before execution:     
[0.068s][warning][os] Loading hsdis library failed                              
[MachCode]                                                                      
  0x00007964b385f380: 2c20 60fc | 2c20 60ec | 1e30 e57c | a920 e37c | f833 a77c | f400 a77c | f402 a77c | 9c26 60ec 
  0x00007964b385f3a0: 0404 0010 | 2922 c37c | 0815 0110 | 0814 0110 | a602 037c | 981e 007c | 2824 e37c | 2825 e37c
  0x00007964b385f3c0: 82fe 0110 | e605 e17c | 3601 c57c | 2000 804e | ec1f 007c | 2000 804e
[/MachCode]                                                                     
Decoding cpu-feature detection stub at 0x00007964b385f380 after execution:      
[MachCode]                                                                      
  0x00007964b385f380: 2c20 60fc | 2c20 60ec | 1e30 e57c | a920 e37c | f833 a77c | f400 a77c | f402 a77c | 9c26 60ec
  0x00007964b385f3a0: 0404 0010 | 2922 c37c | 0815 0110 | 0814 0110 | 0000 0000 | 981e 007c | 2824 e37c | 2825 e37c
  0x00007964b385f3c0: 82fe 0110 | e605 e17c | 0000 0000 | 2000 804e | ec1f 007c | 2000 804e
[/MachCode]     
```

## The question

From this PR and the follow-up patch (https://github.com/openjdk/jdk/pull/25495) by @TheRealMDoerr , it seems that `mfdscr` instruction should be **always available for Power>=8**. Unfortunately, it's actually not in my local environment.

I'm not sure if it's an issue of QEMU or an issue of this PR?
Thanks.

2025-06-24 15:21 UTC, TheRealMDoerr commented
@shqking: Thanks for the detailed analysis! Not sure if it is a QEMU bug. If this is the only problem, let's just add the check back. See new PR linked above. Can you verify and review it, please?