8337658: ZGC: Move soft reference handling out of the driver loop function
openjdk/jdk pull request #20418
Opened 2024-08-01 12:19 UTC by stefank

The ZDriver code is written to be neat and have a clear outline. The soft reference handling distracts when reading this code. I propose that we hide it a bit.

I've also clarified in comments and names that the code is dealing with clearing of *all* references.

2024-08-01 12:55 UTC, jsikstro commented
I think this change is good and agree that `ZDriverMajor::run_thread()` becomes easier to read. Since the policy is now read and set in the construction of the `ZDriverScopeMajor`, a new getter is needed from `ZGenerationOld` and in turn `ZReferenceProcessor` to retrieve the policy for the gc request. The naming clarifications seem appropriate.

2024-08-15 08:42 UTC, xmas92 approved these changes
lgtm.

2024-08-15 08:54 UTC, fisk approved these changes
This code sure has moved around a lot! Looks good.

2024-08-20 08:30 UTC, lgxbslgx requested changes
I don't know whether `_uses_clear_all_soft_references_policy` is a good name. I may be confused by the name if I read the code first time.

One nit shown below.

2024-08-20 08:30 UTC, lgxbslgx commented on src/hotspot/share/gc/z/zReferenceProcessor.hpp
> +  bool uses_clear_all_soft_reference_policy() const;
The method name should be `uses_clear_all_soft_references_policy`. Please note the letter `s` after the `reference`.

2024-08-20 08:59 UTC, stefank commented
> I don't know whether _uses_clear_all_soft_references_policy is a good name. I may be confused by the name if I read the code first time.

Could you elaborate on what the problem with the name is?

2024-08-20 09:49 UTC, lgxbslgx commented
> > I don't know whether _uses_clear_all_soft_references_policy is a good name. I may be confused by the name if I read the code first time.
> 
> Could you elaborate on what the problem with the name is?

The two verbs `use` and `clear` are put together, which is curious at first glance. When we dive into the concrete code, we can know the `clear_all` is actually a adjective to describe the `soft_references_policy`. So I don't know whether it would confuse the newbies.

Another problem is whether we should use the third person singular form (use `uses` or `use` in `_uses_clear_all_soft_references_policy` here). I search the code in current HotSpot and both forms are used now. So I am OK with the word `uses`. Maybe we should unify the name rule in the future.

And, my problem may be caused by my poor english, so I will agree with your opinion if you approve this name after reading my comment above.

2024-08-20 10:09 UTC, stefank commented
I fixed the inconsistency between `soft_reference_policy` and `soft_references_policy`.

> The two verbs use and clear are put together, which is curious at first glance. When I dive into the concrete code, I can know the clear_all is actually a adjective to describe the soft_references_policy. So I don't know whether it would confuse the newbies.

Thanks for the explanation. Yes, the intention is to read this as "uses 'clear all' 'soft reference policy'". I'm going to keep that name, unless someone manages to come up with a more spot-on name that is easy to understand.

> Another problem is whether we should use the third person singular form (use uses or use in _uses_clear_all_soft_references_policy here). I search the code in current HotSpot and both forms are used now. So I am OK with the word uses. Maybe we should unify the name rule in the future.

To me "use" sounds like a command to do something, and not a property. An alternative could be to change it to "is_using_clear_all_soft_reference_policy". Would that be better?

2024-08-21 11:18 UTC, lgxbslgx approved these changes
Looks good.

2024-08-21 11:26 UTC, lgxbslgx commented
> To me "use" sounds like a command to do something, and not a property. An alternative could be to change it to "is_using_clear_all_soft_reference_policy". Would that be better?

These names seem similar. I approved the current patch just now.

2024-08-23 07:08 UTC, stefank commented
Thanks for the reviews!
/integrate

2024-08-23 07:09 UTC, closed without merging