8337939: ZGC: Make assertions and checks less convoluted and explicit
openjdk/jdk pull request #20478
Opened 2024-08-06 15:15 UTC by jsikstro

2024-08-07 14:15 UTC, stefank requested changes

2024-08-07 14:15 UTC, stefank commented on src/hotspot/share/gc/z/zVerify.cpp
> +}
I pre-reviewed this part, but I realize now that I'd like to update the parameter name for the zaddress. Would you mind updating the code this?
```suggestion
static void z_verify_root_oop_object(zaddress addr, void* p) {
  const oop obj = cast_to_oop(addr);
  guarantee(oopDesc::is_oop(obj), BAD_OOP_ARG(addr, p));
}
```

2024-08-08 07:14 UTC, stefank approved these changes
Looks good.

2024-08-08 07:40 UTC, albertnetymk approved these changes

2024-08-08 13:27 UTC, fisk approved these changes
Looks good.

2024-08-08 15:10 UTC, stefank approved these changes

2024-08-08 17:40 UTC, jsikstro commented
/integrate

2024-08-09 07:29 UTC, stefank commented
/sponsor

2024-08-09 07:29 UTC, closed without merging