8338425: java.lang.NullPointerException when About MenuItem is selected from SwingSet2DemoTest.java
openjdk/jdk pull request #20589
Opened 2024-08-15 00:58 UTC by lawrence-andrew

Added the missing jpg file & tested and NPE is not seen any more

2024-08-15 16:55 UTC, honkar-jdk requested changes
The image needs to be added to this location too `test/jdk/sanity/client/lib/SwingSet2/src/resources/images`.
The NPE observed here https://github.com/openjdk/jdk/pull/20450#issuecomment-2271904762 was on SwingSet2.

2024-08-23 18:19 UTC, prrace approved these changes

2024-08-24 20:31 UTC, prrace commented
So .. I think you might want to update this PR to use the image I've just posted over in this other PR : https://github.com/openjdk/jdk/pull/20703/files

2024-08-26 18:29 UTC, honkar-jdk commented
Please add the updated image (with correct openjdk urls) as suggested here https://github.com/openjdk/jdk/pull/20589#issuecomment-2308529054 for both locations - SwingSet and SwingSet2.

2024-10-22 00:06 UTC, closed without merging