8337597
openjdk/jdk pull request #20610
Opened 2024-08-16 08:40 UTC by caspernorrbin

Hi everyone,

Metaspace currently contains macros that appear to be scoped within the `metaspace` namespace, but in reality, their scope is global. To avoid confusion, these macros should be moved to the global namespace.

Additionally, there are instances where macros are defined within functions for localized use. Moving these macros outside the functions would introduce unnecessary complexity. Instead, I’ve opted to `#undef` these macros immediately after their use, ensuring they remain accessible only within their respective functions.

Thanks!

2024-08-19 17:22 UTC, kimbarrett commented
> Metaspace currently contains macros that appear to be scoped within the `metaspace` namespace, but in reality, their scope is global. To avoid confusion, these macros should be moved to the global namespace.

I see no confusion; macros are well known to not be namespace scoped. I would
prefer to keep the namespace opening at the top of the file's code.  Looking
at the JBS issue, I see this is driven by a sonarcloud warning that I think is
just bogus.  But I'll defer to @tstuefe (as the primary maintainer of
metaspace) if he prefers this style.

> Additionally, there are instances where macros are defined within functions for localized use. Moving these macros outside the functions would introduce unnecessary complexity. Instead, I’ve opted to `#undef` these macros immediately after their use, ensuring they remain accessible only within their respective functions.

The #undef of local macros is reasonable hygiene, though a bit pedantic in the
cases being changed here.

2024-08-19 17:23 UTC, kimbarrett requested changes
I think the sonarcloud warnings driving some of this are silly.

2024-08-20 06:05 UTC, tstuefe commented
I agree with @kimbarrett, there is nothing to solve here. Macros are not affected by namespaces. And I prefer opening the namespaces at the start of the file, similar to include guards, since otherwise additions can creep in that are placed outside the namespace too.

2024-08-20 08:08 UTC, caspernorrbin commented
Understandable, thank you for your comments.

2024-08-20 08:08 UTC, closed without merging