JDK-8259710: Inlining trace leaks memory
openjdk/jdk pull request #2063
Opened 2021-01-13 14:51 UTC by tstuefe

We see leaks in NMT originating in C2:

```
1434727 [0x00007f58214af461] stringStream::stringStream(unsigned long)+0x55                                                                                                                                                                                                          
1434728 [0x00007f5820c6db3e] Compile::PrintInliningBuffer::PrintInliningBuffer()+0x6c
1434729 [0x00007f5820c724f1] GrowableArrayWithAllocator<Compile::PrintInliningBuffer, GrowableArray<Compile::PrintInliningBuffer> >::grow(int)+0x163
1434730 [0x00007f5820c7160e] GrowableArrayWithAllocator<Compile::PrintInliningBuffer, GrowableArray<Compile::PrintInliningBuffer> >::insert_before(int, Compile::PrintInliningBuffer const&)+0x82
1434731 [0x00007f5820c6aaf2] Compile::print_inlining_push()+0x70
1434732 [0x00007f5820c6ac23] Compile::print_inlining_update(CallGenerator*)+0xd3
1434733 [0x00007f5820b4fef8] VirtualCallGenerator::generate(JVMState*)+0x62
1434734 [0x00007f5820b5792b] LateInlineVirtualCallGenerator::generate(JVMState*)+0x23
1434735                              (malloc=67KB type=Internal #268)

1434777 [0x00007f58214af461] stringStream::stringStream(unsigned long)+0x55
1434778 [0x00007f5820c6db3e] Compile::PrintInliningBuffer::PrintInliningBuffer()+0x6c
1434779 [0x00007f5820c724f1] GrowableArrayWithAllocator<Compile::PrintInliningBuffer, GrowableArray<Compile::PrintInliningBuffer> >::grow(int)+0x163
1434780 [0x00007f5820c7160e] GrowableArrayWithAllocator<Compile::PrintInliningBuffer, GrowableArray<Compile::PrintInliningBuffer> >::insert_before(int, Compile::PrintInliningBuffer const&)+0x82
1434781 [0x00007f5820c6aaf2] Compile::print_inlining_push()+0x70
1434782 [0x00007f5820c6ac79] Compile::print_inlining_update(CallGenerator*)+0x129
1434783 [0x00007f5820b4f9e3] ParseGenerator::generate(JVMState*)+0x3f
1434784 [0x00007f5820b52121] PredictedCallGenerator::generate(JVMState*)+0x419
1434785                              (malloc=48KB type=Internal #190)

```
..etc, accumulating over the course of days to some hundred MB at a customer site (Note NMT stack depth was increased for this analysis).

---------

To build up a comprehensive inlining trace, c2 keeps trace snippets in an internal list (Compile::_print_inlining_list). Its elements are objects of type PrintInliningBuffer, which contain a new'd stringStream living in resource area:

```
GrowableArray<PrintInliningBuffer>* _print_inlining_list;
...
  class PrintInliningBuffer : public ResourceObj {
   private:
    CallGenerator* _cg;
    stringStream* _ss;

   public:
    PrintInliningBuffer()
      : _cg(NULL) {
      _ss = new stringStream();
    }

    void freeStream() {
      _ss->~stringStream(); _ss = NULL; }
...
  };
```

With JDK-8224193, stringStream was changed to use C-heap instead of RA for its internal buffer. This makes a lot of sense but means one cannot just omit stringStream destruction anymore - even where stringStream objects themselves live in RA, their buffers are allocated in C-heap and need to be freed explicitly.

PrintInliningBuffer is kept by value in a GrowableArray, and I assume we did not want to deal with reference counting the contained stringStream, so cleanup is done manually (`PrintInliningBuffer::freeStream`) instead of inside a destructor.

The problem with that is that when GrowableArray grows, it pre-allocates space for future entries and initializes them by calling the default constructor of the item type:

```
template <typename E, typename Derived>
void GrowableArrayWithAllocator<E, Derived>::grow(int j) {

...
  for (     ; i < this->_len; i++) ::new ((void*)&newData[i]) E(this->_data[i]);
>>>  for (     ; i < this->_max; i++) ::new ((void*)&newData[i]) E(); <<<
  for (i = 0; i < old_max; i++) this->_data[i].~E();
...
}
```

which in our case calls PrintInliningStream() and creates a new stringStream. Later, in `Compile::process_print_inlining()`, we clear the array manually, but only the used elements (list->length()) - preallocated but yet unused elements (len >= index < max) stay allocated:

```
    assert(_print_inlining_list != NULL, "process_print_inlining should be called only once.");
    for (int i = 0; i < _print_inlining_list->length(); i++) {
      ss.print("%s", _print_inlining_list->adr_at(i)->ss()->as_string());
      _print_inlining_list->at(i).freeStream();
    }
```

which would not be a problem if the object would implement a destructor - `void GrowableArrayWithAllocator<E, Derived>::clear_and_deallocate()` does call destructors for all preallocated objects - but since PrintInliningBuffer relies on manual cleanup and does not have a contstructor this does not work.

-----------

There are several ways to fix this:

1) implement correct destructor- and copy semantics for PrintInliningBuffer. This would work but is suboptimal since we still pay for unnecessary PrintInliningBuffer objects when the array grows

2) delay construction of `PrintInliningBuffer::_ss` until the stream is actually used for writing into. This would work but now we would need to check for NULL before using that stream.

3) Rewrite the coding such that the GrowableArray contains pointers to dynamically allocated PrintInliningBuffer objects instead of containing them by value. That would solve that problem, take care of unnecessary copy operations. It would not be more complex than the current solution since we currently new the stringStream and need to clean up the streams manually.

2021-01-18 11:25 UTC, TobiHartmann approved these changes
Otherwise, looks good to me.

2021-01-18 11:25 UTC, TobiHartmann commented on src/hotspot/share/opto/compile.cpp
> +  return *(_print_inlining_list->at(_print_inlining_idx));
Maybe just change the return to `Compile::PrintInliningBuffer*` and update callers accordingly (there are only a few).

2021-01-19 06:01 UTC, tstuefe commented
> Otherwise, looks good to me.

Thanks Tobias. I added your suggestion.

Cheers, Thoams

2021-01-19 08:47 UTC, TobiHartmann requested changes
Thanks for updating. Looks good but you accidentally pushed `make/hs_err_pid10680.log`, `make/replay_pid10680.log` :)

Best regards,
Tobias

2021-01-19 09:17 UTC, tstuefe commented
> Thanks for updating. Looks good but you accidentally pushed `make/hs_err_pid10680.log`, `make/replay_pid10680.log` :)
> 
> Best regards,
> Tobias

Oops. Corrected. Not my day today :)

2021-01-20 08:09 UTC, TobiHartmann approved these changes

2021-01-25 09:36 UTC, neliasso approved these changes
Looks good.

2021-01-25 10:48 UTC, tstuefe commented
> Looks good.

Thank you Nils!

2021-01-25 10:50 UTC, tstuefe commented
GA errors seem unrelated, and this patch runs in our SAP internal tests since a week without problems.

/integrate

2021-01-25 10:50 UTC, closed without merging