Optimize ClassFile Utf8EntryImpl inflate
openjdk/jdk pull request #20767
Opened 2024-08-29 11:44 UTC by wenshao

2024-08-29 12:14 UTC, liach requested changes
Java's UTF8 entry cannot use the 4-byte format in regular UTF8. You can check out how DataInputStream read UTF8 strings instead.

2024-08-29 12:36 UTC, wenshao commented
/label remove security

2024-08-29 16:08 UTC, liach commented on src/java.base/share/classes/jdk/internal/classfile/impl/AbstractPoolEntry.java
> +                return JLA.regionMatches(s, chars, UTF16, 0, charLen);
Just looked at `ArraysSupport`; we don't need to ask the VM; we can already duplicate `mismatch(char[], int, char[], int, int)`, make one of its `char[]` parameter `byte[]` and proceed.

2024-08-30 00:25 UTC, ExE-Boss reviewed
Typo (`HCAR` → `CHAR`):

2024-08-30 00:25 UTC, ExE-Boss commented on src/java.base/share/classes/jdk/internal/classfile/impl/AbstractPoolEntry.java
> +                inflateHCAR(singleBytes, hash);
```suggestion
                inflateCHAR(singleBytes, hash);
```

2024-08-30 00:25 UTC, ExE-Boss commented on src/java.base/share/classes/jdk/internal/classfile/impl/AbstractPoolEntry.java
> +        private void inflateHCAR(int singleBytes, int hash) {
```suggestion
        private void inflateCHAR(int singleBytes, int hash) {
```

2024-09-24 16:21 UTC, liach commented on src/java.base/share/classes/jdk/internal/classfile/impl/AbstractPoolEntry.java
> +        private void inflateCHAR(int singleBytes, int hash) {
Can you rename this method to `inflateNonAscii`?

2024-09-25 01:14 UTC, liach commented
Thanks for this rename and cleanup. Is `inflateNonAscii` code size less than 325?

2024-09-27 01:39 UTC, wenshao commented
I don't have a test scenario for inflateNonAscii, and I can't see the codeSize of inflateNonAscii printed in the compiler log.

2024-10-04 16:09 UTC, liach commented on src/java.base/share/classes/jdk/internal/classfile/impl/AbstractPoolEntry.java
> +        private void inflateNonAscii(int singleBytes, int hash) throws ConstantPoolException {
```suggestion
        private void inflateNonAscii(int singleBytes, int hash) {
```

2024-10-09 17:01 UTC, liach approved these changes
We can optimize non-ascii reading here and in DataInputStream together later.

2024-10-09 17:20 UTC, wenshao commented
/integrate

2024-10-09 17:22 UTC, closed without merging