8334165: remove serialVersionUID compatibility logic from JMX
openjdk/jdk pull request #20856
Opened 2024-09-04 16:27 UTC by kevinjwalls

2024-09-05 14:57 UTC, dfuch reviewed
Wow. I hadn't realized so many classes were impacted. I thought there was just a few!

Look good in general. It could be good to write a test that sets the property with 1.0 and 1.1, and that verifies that something (e.g. an ObjectName?) serialized with property=1.0 can be deserialized with property=1.1, and conversely.

That would validate that setting the property no longer has any effect.

2024-09-05 16:59 UTC, kevinjwalls commented
Thanks Daniel @dfuch , we can use a version of what we had before, there was a simple check on ObjectName fields.  I added it, will fail in a JDK that respects jmx.serial.version.

2024-09-06 12:43 UTC, dfuch approved these changes
LGTM  - might be good to have an other pait of eyes looking at it before integrating...

2024-09-10 13:26 UTC, dfuch commented on src/java.management/share/classes/javax/management/modelmbean/InvalidTargetObjectTypeException.java
> +    private static final ObjectStreamField[] serialPersistentFields =
The API doc comment for the serialized fields dhould be preserved.
```suggestion
    /**
     * @serialField exception Exception Encapsulated {@link Exception}
     */
    private static final ObjectStreamField[] serialPersistentFields =
```

2024-09-10 13:30 UTC, dfuch requested changes

2024-09-10 13:30 UTC, dfuch commented on src/java.management/share/classes/javax/management/modelmbean/ModelMBeanAttributeInfo.java
> +        private static final ObjectStreamField[] serialPersistentFields =
API doc coment for serial persistent fields should have been preserved.
```suggestion
        /**
         * @serialField attrDescriptor Descriptor The {@link Descriptor}
         * containing the metadata corresponding to this attribute
         */
        private static final ObjectStreamField[] serialPersistentFields =
```

2024-09-10 13:38 UTC, dfuch requested changes

2024-09-10 13:38 UTC, dfuch commented on src/java.management/share/classes/javax/management/modelmbean/ModelMBeanNotificationInfo.java
> +    private static final ObjectStreamField[] serialPersistentFields =
Same here:
```suggestion
    /**
     * @serialField notificationDescriptor Descriptor The descriptor
     *   containing the appropriate metadata for this instance
     */
    private static final ObjectStreamField[] serialPersistentFields =
```

2024-09-10 13:44 UTC, kevinjwalls commented
thanks yes, updated 4 missing serialField comments

2024-09-10 13:55 UTC, dfuch reviewed
OK - thanks. LGTM now.

2024-09-11 15:06 UTC, dfuch approved these changes

2024-09-12 08:31 UTC, closed without merging