8246112: Remove build-time and run-time checks for clock_gettime and CLOCK_MONOTONIC
openjdk/jdk pull request #2090
Opened 2021-01-15 04:57 UTC by dholmes-ora

We are now confident that we have build-time and runtime support for clock_gettime and CLOCK_MONOTONIC on all our OpenJDK supported POSIX platforms - see bug report for some more details on different OS. Consequently we can simplify a lot of the code in this area and move common code to os_posix.

2021-01-18 13:56 UTC, magicus requested changes
Looks like a good cleanup. But please minimize the use of -lrt to hotspot only as per the comment above.

2021-01-18 13:56 UTC, magicus commented on make/autoconf/flags-ldflags.m4
> +      OS_LDFLAGS="-lrt"
I believe this should be `OS_LDFLAGS_JVM_ONLY`, right?

2021-01-19 14:23 UTC, erikj79 approved these changes
Build changes look good to me.

2021-01-19 18:22 UTC, magicus approved these changes

2021-01-20 21:30 UTC, gerard-ziemski requested changes

2021-01-20 21:30 UTC, gerard-ziemski commented on src/hotspot/os/bsd/os_bsd.inline.hpp
> + * Copyright (c) 1999, 2030, Oracle and/or its affiliates. All rights reserved.
Year 2030 ?

2021-01-20 21:30 UTC, gerard-ziemski commented on src/hotspot/os/bsd/os_bsd.cpp
> +void os::javaTimeNanos_info(jvmtiTimerInfo *info_ptr) {
How come we need `os::javaTimeNanos_info` here if there is already one in `os_posix.cpp`?

2021-01-20 21:30 UTC, gerard-ziemski commented on src/hotspot/os/posix/os_posix.hpp
>    static bool supports_monotonic_clock();
Why do we need this API at all now?

thread.cpp uses it here:

      assert(!os::supports_monotonic_clock(),
             "unexpected time moving backwards detected in JavaThread::sleep()");

so we can just remove this usage?

2021-01-20 21:30 UTC, gerard-ziemski commented on src/hotspot/os/posix/os_posix.cpp
> +  log_info(os)("Use of CLOCK_MONOTONIC is supported");
We are keeping this output to avoid breaking whomever might be looking for this text?

2021-01-21 15:26 UTC, gerard-ziemski approved these changes

2021-01-22 10:10 UTC, tstuefe commented
Builds fine on AIX. I scheduled tests for the coming nights.
About os::javaTimeNanos, not sure if we still need that for AIX, but monotonic clocks gave us a lot of grief in the past on that .. platform and I prefer it to leave that way for now. Investigating if we can use clock_gettime for os::javaTimeNanos like Linux does can be done in a separate RFE.

2021-01-22 16:17 UTC, hseigel approved these changes
Hi David,
The changes look good.  Just a couple of nits.
1. Could you add a comment explaining why AIX and BSD have their own version of javaTimeNanos_info().
2. A few copyrights need to be updated to 2021.
Thanks, Harold

2021-01-25 07:17 UTC, tstuefe commented
I don't see any new issues on AIX in our tests with this patch. Thanks for waiting!

2021-01-25 13:24 UTC, hseigel commented
Hi David,

I think that os_posix.cpp is a good place to put a comment explaining why AIX and BSD have their own javaTimeNanos_info(). Stating something like "AIX and BSD have their own versions because their implementations of monotonic time have worked on those platforms." seems fine.

Thanks for doing this!
Harold

2021-01-26 09:22 UTC, mkraljt commented on src/hotspot/os/posix/os_posix.cpp
> +}
David,
Great to see simplifications like this happening in OpenJdk code.
- Posix letting you delete platform specific code.
- Always nice to see 'if' branching eliminated to simplify test coverage and runtime.

2021-01-27 01:18 UTC, dholmes-ora commented
/integrate

2021-01-27 01:18 UTC, closed without merging