8339668: Parallel: Adopt PartialArrayState to consolidate marking stack in compact GC
openjdk/jdk pull request #21089
Opened 2024-09-19 14:01 UTC by zhengyu123

Please review this patch that adopts `PartialArrayState`introduced by [JDK-8337709](https://bugs.openjdk.org/browse/JDK-8337709) to consolidate `_oop_task_queues` and `_objarray_task_queues` into single `_marking_stacks`.

The change mirrors Kim's [JDK-8311163](https://bugs.openjdk.org/browse/JDK-8311163) work, therefore, there are methods can be consolidated and simplified, but I would like defer to a followup CR.

2024-10-01 14:54 UTC, tschatzl requested changes

2024-10-01 16:40 UTC, kimbarrett commented on src/hotspot/share/gc/parallel/psCompactionManager.hpp
> +
I ran into the same problem for G1 Full GC that @zhengyu123 has run into here.  ScannerTask deals in
_pointers_ to `oop` (and `narrowOop`).  For the separate marking cases we have `oop`s in the tasks.
I added a class just like this one in my work, except I put mine in gc/shared and gave it a different name
(OopScannerTask, which I don't love).  Clearly some coalescing is needed there.

2024-10-02 07:18 UTC, tschatzl commented on src/hotspot/share/gc/parallel/psCompactionManager.hpp
> +
>I ran into the same problem for G1 Full GC that @zhengyu123 has run into here. ScannerTask deals in
pointers to oop (and narrowOop). For the separate marking cases we have oops in the tasks.
I added a class just like this one in my work, except I put mine in gc/shared and gave it a different name
(OopScannerTask, which I don't love). Clearly some coalescing is needed there.

The suggested patch just adds constructor to allow a regular `oop` and the associated getter. Internally `ScannerTask` uses a `void*` anyway.
Probably I am overlooking something trivial here why having an interface to store and retrieve an `oop` is not possible....

2024-10-02 09:25 UTC, tschatzl commented on src/hotspot/share/gc/parallel/psCompactionManager.hpp
> +#endif // TASKQUEUE_STATS
Here's a commit that only touches up the worst issues in this change: https://github.com/openjdk/jdk/commit/ab6e77ed909c13458a24e9663e830cfac9c4f18e

(branch including the other suggestions so far: https://github.com/openjdk/jdk/compare/master...tschatzl:jdk:pull/21089-taskqueue-refactor)

This makes the change a lot more readable imo (and in total reduces LOC count).

The only missing improvement is to have the array statistics in the same log lines as the other statistics; that could be achieved by specializing the queues/queue set, but that requires the unified `ScannerTask` in the other change and more work.

2024-10-02 09:26 UTC, tschatzl commented on src/hotspot/share/gc/parallel/psCompactionManager.hpp
> +
(Fwiw, https://github.com/tschatzl/jdk/tree/submit/pull/21089-recommendations-test with the suggested changes seems to pass GHA....)

2024-10-02 14:21 UTC, zhengyu123 commented on src/hotspot/share/gc/parallel/psCompactionManager.hpp
> +
I missed `ScannerTask` constructor change :-( the suggested changes also passed tier1 with Parallel GC.

2024-10-02 14:27 UTC, zhengyu123 commented
/contributor add @tschatzl

2024-10-02 14:32 UTC, zhengyu123 commented on src/hotspot/share/gc/parallel/psCompactionManager.hpp
> +#endif // TASKQUEUE_STATS
I will take a shot of [JDK-8341332](https://bugs.openjdk.org/browse/JDK-8341332)

2025-01-03 21:43 UTC, zhengyu123 commented
/open

2025-01-20 13:24 UTC, albertnetymk reviewed
Could you also sync the PR with master?

2025-01-20 13:24 UTC, albertnetymk commented on src/hotspot/share/gc/parallel/psCompactionManager.cpp
> +  :_partial_array_splitter(_partial_array_state_manager, ParallelGCThreads),
I feel it's best to avoid using `ParallelGCThreads` directly; instead, pass in `parallel_gc_threads` in `new ParCompactionManager` below. WDYT?

2025-01-20 13:24 UTC, albertnetymk commented on src/hotspot/share/gc/parallel/psCompactionManager.cpp
> +  int end = checked_cast<int>(initial_chunk_size);
I wonder if we can change the callee so that we don't need `checked_cast` here. (Intuitively, [start, end) denotes a range and both number should never be negative.)

2025-01-22 11:23 UTC, albertnetymk commented on src/hotspot/share/gc/parallel/psCompactionManager.cpp
> +#include "utilities/checkedCast.hpp"
Can this be removed now?

2025-01-22 11:23 UTC, albertnetymk commented on src/hotspot/share/gc/parallel/psCompactionManager.cpp
> +    // The destination array is unused when processing states.
This comment is not very helpful; I had to look into the callee to find out it's referring to `nullptr` in the args and why one can use `nullptr` here, but that process is fairly straightforward, so this comment can probably be dropped.

2025-01-22 11:23 UTC, albertnetymk commented on src/hotspot/share/gc/shared/taskqueue.hpp
> +// Oop/oop* are overloaded using the same tag because they can not appear at the
The reason why "they can not appear at the same time" is that one is for young-gc and the other full-gc, right? If so, maybe state that explicitly.

2025-01-22 11:23 UTC, albertnetymk commented on src/hotspot/share/gc/parallel/psCompactionManager.cpp
> +  :_partial_array_splitter(_partial_array_state_manager, ParallelScavengeHeap::heap()->workers().max_workers()),
I would probably pass `parallel_gc_threads` into the constructor of `ParCompactionManager`, instead of calling `max_workers()` directly here, in order to maintain a single source of truth. YMMV.

2025-01-25 21:17 UTC, zhengyu123 commented on src/hotspot/share/gc/shared/taskqueue.hpp
> +// Oop/oop* are overloaded using the same tag because they can not appear at the
As far as Parallel, `PromotionManager` uses `ScannerTask` to wrap around `*oop` and `CompactionManager` to wrap around `oop`, which is true. But I don't think it has such correlation. 

Probably should phase as `ScannerTask` wraps `*oop` or `oop` using the same tag, because they cannot be mixed in the same queue.

2025-01-25 21:20 UTC, zhengyu123 commented on src/hotspot/share/gc/parallel/psCompactionManager.cpp
> +    // The destination array is unused when processing states.
Fixed

2025-01-25 21:20 UTC, zhengyu123 commented on src/hotspot/share/gc/parallel/psCompactionManager.cpp
> +#include "utilities/checkedCast.hpp"
Done.

2025-01-27 12:31 UTC, albertnetymk commented on src/hotspot/share/gc/shared/taskqueue.hpp
> +// Oop/oop* are overloaded using the same tag because they can not appear at the
> But I don't think it has to have such correlation.

I believe this is due to the choice of diff gc-algorithms. Young-gc uses scavenging (copying), while full-gc uses mark-compact (lisp-2). The former performs "pointer remap" in the same phase as forwarding.

(Ofc, this is just for comment/doc. Feel free to keep as is, or revise, or maybe other reviewers have sth to share.)

2025-01-28 09:19 UTC, tschatzl approved these changes

2025-01-28 13:27 UTC, zhengyu123 commented
/integrate

Thanks, @albertnetymk @tschatzl

2025-01-28 13:29 UTC, closed without merging