8341097: GHA: Demote Mac x86 jobs to build only
openjdk/jdk pull request #21257
Opened 2024-09-30 08:36 UTC by shipilev

See the discussion in the bug. I think we can stop testing Mac x86 in GHA, leaving only the build jobs.

Additional testing:
 - [x] GHA passes

2024-09-30 10:39 UTC, kimbarrett requested changes
This change seems premature.  Various companies (Oracle, SAP, others?) are still
supporting macos-x64 on mainline.  Removing this seems to be just asking for more
frequent backouts due to x64-specific changes that aren't compatible with clang.

2024-09-30 11:11 UTC, shipilev commented
> This change seems premature. Various companies (Oracle, SAP, others?) are still supporting macos-x64 on mainline.

Maybe, maybe not. We always run against the runner availability in GHA. AFAIU, MacOS 13 will EOL 3 years after release, so around Oct 2025. I don't mind waiting until next year, but want to point out that the clock is ticking on GHA support for Mac x86, and runner availability will likely get gradually worse.

> Removing this seems to be just asking for more frequent backouts due to x64-specific changes that aren't compatible with clang.

I would assume that clang incompatibilities would be caught as build error/warnings during the build. This PR suggests to only disable the test jobs. Build jobs are still on, and at least some parts of runtime are verified when building the full JDK, e.g. when building jmods/jimages. I cannot remember any recent issue where we successfully passed the build, and something was failing on Mac x86, and not on Mac aarch64.

2024-10-08 13:04 UTC, magicus approved these changes
I think this sounds reasonable. Just as we keep adding to GHA testing, we also need to find any opportunity we can to keep it slim. 

If macos-x64 had been added at this point, I don't think anyone would have suggested that we added running tests for it, so then we should not keep them just out of old habit.

2024-11-06 09:03 UTC, shipilev commented
Not now, bot. I'll probably delay this until the JDK 25 fork.

2024-11-18 12:10 UTC, shipilev commented
As far as I can tell -- and this is very much like reading the tea leaves:
- `macos-11` runners [started brownouts](https://github.blog/changelog/2024-05-20-actions-upcoming-changes-to-github-hosted-macos-runners/#macos-11-deprecation-and-removal) and got completely removed in June 2024
- `macos-12` runners [started brownouts](https://github.com/actions/runner-images/issues/10721) in Nov 2024, and would be removed in Dec 2024.

Pessimistically assuming the same 5-month interval, we may expect the brownouts and removals for `macos-13` image somewhere in Apr 2025. If this happens, it would start affecting July 2025 CPU releases. But it should still be fine for JDK 24 GA. I say we integrate this PR in early "JDK 25" mainline, and let update releases pick it up, as the situation develops.

2024-12-16 14:52 UTC, shipilev commented
Not anecdotally anymore: GHA now publishes richer Actions stats, should be at "Actions" in your personal fork. Here is mine, sorted by queue wait time last month. macos-x86 are the largest waiters, which IMO underlines the reality that macos-x86 workers are not in abundance. macos-aarch64 are also not great, but at least they match the current hardware that we want to test for.

![gha-top-waiters](https://github.com/user-attachments/assets/0dbc1afc-38e1-4e57-820f-e5d86fa72df6)

2025-01-06 09:34 UTC, shipilev commented
Friendly ping :)

2025-01-08 19:24 UTC, prrace commented
I don't have any objection to this, but
(1) I'm surprised Microsoft (github) doesn't have  x64 systems that can run macOS14/15
(2) I expect we'll actually support macOS x64 for as long as Apple do .. and since in 2023 you could still get x64 macs I expect it'll be a number of years before support is dropped.
But since you can no longer get them, if MS missed the last order date, they will soon be struggling to have enough to meet demand, which is why the demotion makes sense.

2025-01-08 19:24 UTC, prrace approved these changes

2025-01-08 23:39 UTC, kimbarrett approved these changes
Looks good.

2025-01-09 10:18 UTC, closed without merging