8340420: ZGC: Should call `vm_shutdown_during_initialization` if initialization fails
openjdk/jdk pull request #21254
Opened 2024-09-30 06:36 UTC by xmas92

ZGC does not call `vm_shutdown_during_initialization` if initialization fails during the setup of the CollectedHeap, in contrast to the other GC.

I propose we add a `ZInitialize::error` which we can use during initialisation to record errors. The first error recored is also stored and used as the error message when shutting down the VM. 

Initially used malloc to allocate the error (ed9ba5dd6805291a6b1b56566c933424230d3b4a) but feels like it is just better to have static storage for the string and not have to care about malloc potentially failing to allocate.

2024-09-30 07:36 UTC, stefank requested changes

2024-09-30 07:36 UTC, stefank commented on src/hotspot/share/gc/z/zInitialize.cpp
> +  const FormatBuffer<ErrorMessageLength> error(FormatBufferDummy(), msg_format, argp);
Maybe consider a name that doesn't clash with the function name.

2024-09-30 07:36 UTC, stefank commented on src/hotspot/share/gc/z/zInitialize.cpp
> +  const FormatBuffer<ErrorMessageLength> error(FormatBufferDummy(), msg_format, argp);
Maybe consider a name that doesn't clash with the function name.

2024-09-30 07:36 UTC, stefank commented on src/hotspot/share/gc/z/zInitialize.cpp
> +  return _error_message;
Maybe invert the conditional?
```suggestion
  if (had_error()) {
    return _error_message;
  }
  return "Unknown error, check error GC logs";
```

2024-09-30 07:36 UTC, stefank commented on src/hotspot/share/gc/z/zInitialize.hpp
> + public:
Indentation doesn't follow the ZGC style.

2024-09-30 07:36 UTC, stefank commented on src/hotspot/share/gc/z/zInitialize.hpp
> +  static char _error_message[ErrorMessageLength];
I would suggest that we separate the constants
```suggestion
  static constexpr size_t ErrorMessageLength = 256;

  static char _error_message[ErrorMessageLength];
```

2024-09-30 08:04 UTC, stefank approved these changes

2024-09-30 08:37 UTC, Hamlin-Li approved these changes

2024-10-01 11:32 UTC, xmas92 commented
Thanks for the reviews.
/integrate

2024-10-01 11:33 UTC, closed without merging