8341664: ReferenceClassDescImpl cache internalName
openjdk/jdk pull request #21373
Opened 2024-10-06 01:22 UTC by wenshao

ReferenceClassDescImpl caches internalName to avoid creating a new String object for each call, which can also simplify the implementation of classfile.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8341664](https://bugs.openjdk.org/browse/JDK-8341664): ReferenceClassDescImpl cache internalName (**Enhancement** - P4)

### Reviewers
 * [Chen Liang](https://openjdk.org/census#liach) (@liach - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/21373/head:pull/21373` \
`$ git checkout pull/21373`

Update a local copy of the PR: \
`$ git checkout pull/21373` \
`$ git pull https://git.openjdk.org/jdk.git pull/21373/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 21373`

View PR using the GUI difftool: \
`$ git pr show -t 21373`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/21373.diff">https://git.openjdk.org/jdk/pull/21373.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/21373#issuecomment-2397426526)

2024-10-06 14:49 UTC, liach requested changes

2024-10-06 14:49 UTC, liach commented on src/java.base/share/classes/jdk/internal/classfile/impl/Util.java
> +        return cd.descriptorString();
```suggestion
        rthrow new IllegalArgumentException(desc);
```

2024-10-06 14:49 UTC, liach commented
The caching of class entry forms in ReferenceClassDescImpl may be controversial; I will consult with other engineers.

2024-10-06 15:39 UTC, wenshao commented
In many scenarios where classfile is used, ClassDesc is cached by statically declaring constants, such as InvokerBytecodeGenerator/StringConcatFactory. However, internalName is generated by subString every time bytecode is built, which means that the purpose of caching ClassDesc is not fully achieved.

2024-10-18 07:56 UTC, liach approved these changes
Good.

2024-10-18 08:04 UTC, wenshao commented
/integrate

2024-10-18 08:06 UTC, closed without merging