8341789: Fix ExceptionOccurred in java.base
openjdk/jdk pull request #21428
Opened 2024-10-09 17:28 UTC by justin-curtis-lu

Please review this PR which fixes incorrect usage of `jthrowable ExceptionOccurred(JNIEnv *env)` within _java.base_.

This corrects instances where the return value is being treated as a boolean. Such occurrences are replaced with `jboolean ExceptionCheck(JNIEnv *env)`.

2024-10-09 20:50 UTC, bplb approved these changes
I think this is correct. `ExceptionOccurred` returns a local reference to a `Throwable` but it is used only in an implicit `!= NULL` check which is better served by the `jboolean` returned by `ExceptionCheck`.

2024-10-10 07:03 UTC, jaikiran approved these changes
Looks OK to me.

2024-10-10 09:29 UTC, dfuch commented
From https://docs.oracle.com/en/java/javase/23/docs/specs/jni/functions.html#exceptioncheck :

> ExceptionCheck
> We introduce a convenience function to check for pending exceptions without creating a local reference to the exception object.
> 
> jboolean ExceptionCheck(JNIEnv *env);
> 
> Returns JNI_TRUE when there is a pending exception; otherwise, returns JNI_FALSE.
> 

So this looks good to me too.

2024-10-10 09:30 UTC, dfuch approved these changes

2024-10-10 11:07 UTC, LanceAndersen requested changes
Hi Justin,

Overall looks fine.  I
t looks like
open/src/java.base/share/native/libzip/Deflater.c
open/src/java.base/share/native/libzip/Inflater.c

also same for line 670 in open.bk/src/java.base/share/native/libjli/java.c

were left out from the commit for the PR but are listed in the JBS issue so it would be great to include the updates as part of this PR or explain why they were excluded if it was intentional

2024-10-10 11:40 UTC, AlanBateman commented
> were left out from the commit for the PR but are listed in the JBS issue so it would be great to include the updates as part of this PR or explain why they were excluded if it was intentional

The original bug report has several false positives, it flagged cases where ExceptionOccurred == NULL, which aren't issues. Some of these could be changed to ExceptionCheck to avoid create the throwable, that would be more about performance for exception cases so not too interesting.

2024-10-10 12:04 UTC, LanceAndersen commented
> > were left out from the commit for the PR but are listed in the JBS issue so it would be great to include the updates as part of this PR or explain why they were excluded if it was intentional
> 
> The original bug report has several false positives, it flagged cases where ExceptionOccurred == NULL, which aren't issues. Some of these could be changed to ExceptionCheck to avoid create the throwable, that would be more about performance for exception cases so not too interesting.

Thanks for the clarification, I missed the comment you added to the bug

2024-10-10 12:05 UTC, LanceAndersen approved these changes

2024-10-10 12:06 UTC, LanceAndersen approved these changes

2024-10-10 13:49 UTC, RogerRiggs approved these changes

2024-10-10 16:11 UTC, naotoj approved these changes

2024-10-10 17:32 UTC, justin-curtis-lu commented
Thank you all for the reviews.
/integrate

2024-10-10 17:33 UTC, closed without merging