8341697: C2: Register allocation inefficiency in tight loop
openjdk/jdk pull request #21472
Opened 2024-10-11 15:50 UTC by merykitty

Hi,

This patch improves the spill placement in the presence of loops. Currently, when trying to spill a live range, we will create a `Phi` at the loop head, this `Phi` will then be spilt inside the loop body, and as the `Phi` is `UP` (lives in register) at the loop head, we need to emit an additional reload at the loop back-edge block. This introduces loop-carried dependencies, greatly reduces loop throughput. My proposal is that if a node is not reassigned inside a loop, and will be spilt there, we spill it eagerly at the loop entry instead. This can lead to more reload inside the loop, but as the loop-carried dependencies are eliminated, a load is negligible.

Please take a look and leave your reviews, thanks a lot.

2024-10-11 15:55 UTC, merykitty commented
The benchmark result:

    Benchmark                          Mode  Cnt    Score     Error  Units
    LoopCounterBench.field_ret         avgt    3  417.865 ±   2.914  ns/op
    LoopCounterBench.localVar_ret      avgt    3  332.657 ± 109.310  ns/op

The inner loop is free of spills because it has been hoisted to the loop entry:

                  │  0x00007fdf9821b546:   mov    r9d,DWORD PTR [r11+0xc]      ;*getfield increment {reexecute=0 rethrow=0 return_oop=0}
                  │                                                            ; - org.openjdk.bench.vm.compiler.LoopCounterBench::localVar_ret@1 (line 56)
                  │                                                            ; - org.openjdk.bench.vm.compiler.jmh_generated.LoopCounterBench_localVar_ret_jmhTest::localVar_ret_avgt_jmhStub@17 (line 190)
       0.03%      │  0x00007fdf9821b54a:   mov    esi,DWORD PTR [r12+r8*8+0xc] ; implicit exception: dispatches to 0x00007fdf9821b6f4
                  │                                                            ;*lastore {reexecute=0 rethrow=0 return_oop=0}
                  │                                                            ; - org.openjdk.bench.vm.compiler.LoopCounterBench::localVar_ret@27 (line 58)
                  │                                                            ; - org.openjdk.bench.vm.compiler.jmh_generated.LoopCounterBench_localVar_ret_jmhTest::localVar_ret_avgt_jmhStub@17 (line 190)
                  │  0x00007fdf9821b54f:   lea    rax,[r12+r14*8]
                  │  0x00007fdf9821b553:   lea    r13,[r12+r8*8]
       0.03%      │  0x00007fdf9821b557:   xor    edi,edi
                  │  0x00007fdf9821b559:   vmovq  xmm0,rbp
                  │  0x00007fdf9821b55e:   xchg   ax,ax                        ;*aload_0 {reexecute=0 rethrow=0 return_oop=0}
                  │                                                            ; - org.openjdk.bench.vm.compiler.LoopCounterBench::localVar_ret@16 (line 58)
                  │                                                            ; - org.openjdk.bench.vm.compiler.jmh_generated.LoopCounterBench_localVar_ret_jmhTest::localVar_ret_avgt_jmhStub@17 (line 190)
                 ↗│  0x00007fdf9821b560:   cmp    edi,r10d
       1.66%    ╭││  0x00007fdf9821b563:   jae    0x00007fdf9821b587
                │││  0x00007fdf9821b565:   mov    rbp,QWORD PTR [rax+rdi*8+0x10];*laload {reexecute=0 rethrow=0 return_oop=0}
                │││                                                            ; - org.openjdk.bench.vm.compiler.LoopCounterBench::localVar_ret@26 (line 58)
                │││                                                            ; - org.openjdk.bench.vm.compiler.jmh_generated.LoopCounterBench_localVar_ret_jmhTest::localVar_ret_avgt_jmhStub@17 (line 190)
       5.43%    │││  0x00007fdf9821b56a:   cmp    edi,esi
       0.17%    │││  0x00007fdf9821b56c:   jae    0x00007fdf9821b5c8
                │││  0x00007fdf9821b56e:   mov    QWORD PTR [r13+rdi*8+0x10],rbp;*goto {reexecute=0 rethrow=0 return_oop=0}
                │││                                                            ; - org.openjdk.bench.vm.compiler.LoopCounterBench::localVar_ret@32 (line 57)
                │││                                                            ; - org.openjdk.bench.vm.compiler.jmh_generated.LoopCounterBench_localVar_ret_jmhTest::localVar_ret_avgt_jmhStub@17 (line 190)
       1.40%    │││  0x00007fdf9821b573:   add    edi,r9d                      ;*iadd {reexecute=0 rethrow=0 return_oop=0}
                │││                                                            ; - org.openjdk.bench.vm.compiler.LoopCounterBench::localVar_ret@30 (line 57)
                │││                                                            ; - org.openjdk.bench.vm.compiler.jmh_generated.LoopCounterBench_localVar_ret_jmhTest::localVar_ret_avgt_jmhStub@17 (line 190)
       3.40%    │││  0x00007fdf9821b576:   mov    rbp,QWORD PTR [r15+0x450]    ; ImmutableOopMap {r11=Oop r8=NarrowOop rcx=Oop rbx=Oop rdx=Oop rax=Oop r13=Oop r14=NarrowOop }
                │││                                                            ;*goto {reexecute=1 rethrow=0 return_oop=0}
                │││                                                            ; - (reexecute) org.openjdk.bench.vm.compiler.LoopCounterBench::localVar_ret@32 (line 57)
                │││                                                            ; - org.openjdk.bench.vm.compiler.jmh_generated.LoopCounterBench_localVar_ret_jmhTest::localVar_ret_avgt_jmhStub@17 (line 190)
       1.80%    │││  0x00007fdf9821b57d:   test   DWORD PTR [rbp+0x0],eax      ;*goto {reexecute=0 rethrow=0 return_oop=0}
                │││                                                            ; - org.openjdk.bench.vm.compiler.LoopCounterBench::localVar_ret@32 (line 57)
                │││                                                            ; - org.openjdk.bench.vm.compiler.jmh_generated.LoopCounterBench_localVar_ret_jmhTest::localVar_ret_avgt_jmhStub@17 (line 190)
                │││                                                            ;   {poll}
      84.42%    │││  0x00007fdf9821b580:   cmp    edi,r10d
       0.30%    │╰│  0x00007fdf9821b583:   jl     0x00007fdf9821b560           ;*if_icmpge {reexecute=0 rethrow=0 return_oop=0}
                │ │                                                            ; - org.openjdk.bench.vm.compiler.LoopCounterBench::localVar_ret@13 (line 57)
                │ │                                                            ; - org.openjdk.bench.vm.compiler.jmh_generated.LoopCounterBench_localVar_ret_jmhTest::localVar_ret_avgt_jmhStub@17 (line 190)

2024-10-11 16:02 UTC, merykitty commented
Thanks to @shipilev for the benchmark, could you verify that this can solve the issue in the original benchmark as I imagine this is a simplified version.

2024-10-12 10:52 UTC, merykitty commented
New benchmark results:

                                                                   Before                 After
    Benchmark                           (prob)  Mode  Cnt       Score      Error      Score     Error  Units
    LoopCounterBench.field_ret             N/A  avgt    5     425.678 ±    5.086    419.819 ±   1.965  ns/op
    LoopCounterBench.localVar_ret          N/A  avgt    5    1126.937 ±    1.078    325.651 ±   5.309  ns/op
    LoopCounterBench.reloadAtEntry_ret     N/A  avgt    5     582.465 ±    2.649    491.421 ±   0.909  ns/op
    LoopCounterBench.spillUncommon_ret     0.0  avgt    5     490.901 ±    5.505    490.981 ±   2.118  ns/op
    LoopCounterBench.spillUncommon_ret    0.01  avgt    5    2491.557 ±    4.837   1912.170 ±  19.208  ns/op
    LoopCounterBench.spillUncommon_ret     0.1  avgt    5   21316.571 ±   88.198  10518.618 ± 183.380  ns/op
    LoopCounterBench.spillUncommon_ret     0.2  avgt    5   42095.064 ±  210.995  19908.240 ± 313.108  ns/op
    LoopCounterBench.spillUncommon_ret     0.5  avgt    5  113825.492 ± 1637.428  48194.341 ± 719.049  ns/op

2024-10-13 08:01 UTC, shipilev commented
This was really found by @rschwietzke, maybe he would like to test it :)

2024-10-13 19:42 UTC, rschwietzke commented
Sure thing, I will give it a try in the coming days. @merykitty 's results look promising.

2024-10-14 08:56 UTC, rschwietzke commented
Fix confirmed. Performance matches the user expectation when pulling data local. I will look into the runtime difference for the plain loop and systemcopy.

### Old - JDK 23.0.0
```
Benchmark                                   (SIZE)  Mode  Cnt     Score     Error  Units
Example8ArrayCopying.manualCopy1              1000  avgt   10    70.222 ±   3.549  ns/op
Example8ArrayCopying.manualCopy2              1000  avgt   10    70.011 ±   0.880  ns/op
Example8ArrayCopying.manualCopyAntiUnroll1    1000  avgt   10   394.275 ±  20.067  ns/op
Example8ArrayCopying.manualCopyAntiUnroll2    1000  avgt   10   636.158 ± 101.505  ns/op
Example8ArrayCopying.manualCopyAntiUnroll3    1000  avgt   10  1646.330 ±  23.042  ns/op
Example8ArrayCopying.systemCopy               1000  avgt   10    74.845 ±   1.535  ns/op
```

### New - JDK 24-internal (merrykitty/improveregalloc, 12d1a2b21fc62145dac04fecf43f267f539b2aa5)
```
Example8ArrayCopying.manualCopy1              1000  avgt   10   80.155 ±  4.504  ns/op
Example8ArrayCopying.manualCopy2              1000  avgt   10   81.122 ±  3.074  ns/op
Example8ArrayCopying.manualCopyAntiUnroll1    1000  avgt   10  394.094 ±  6.809  ns/op
Example8ArrayCopying.manualCopyAntiUnroll2    1000  avgt   10  626.155 ± 13.055  ns/op
Example8ArrayCopying.manualCopyAntiUnroll3    1000  avgt   10  564.199 ± 23.854  ns/op
Example8ArrayCopying.systemCopy               1000  avgt   10   99.393 ±  0.634  ns/op
```

Source code for reference: https://github.com/Xceptance/jmh-training/blob/1dbcc9c38553b0e8b683c6f70475a25150b66635/src/main/java/org/xc/jmh/Example8ArrayCopying.java

2024-10-14 13:42 UTC, merykitty commented
Thanks for the source code. That's really interesting, running the benchmark multiple times may give different results, and even when there is a difference in the observed throughputs, the 2 compiled methods are exactly the same. So I think we are running into different quirks here, probably due to the fact that this benchmark saturates the memory bandwidth.

2024-10-15 17:33 UTC, vnkozlov commented
@merykitty can you run this with regular Java benchmarks (SPECjvm, SPECjbb, Renaissance, DaCapo) to see if they are affected?

2024-10-15 17:52 UTC, vnkozlov commented
> @merykitty can you run this with regular Java benchmarks (SPECjvm, SPECjbb, Renaissance, DaCapo) to see if they are affected?

We will also run our set of benchmarks to make sure there is no regression. If we see significant regression only in some benchmarks and improvement in others we can set `LoopAwareSpilling` to false in these changes and address regression in following PR.

2024-11-13 13:08 UTC, dlunde commented
Keep active. I intend to review this when time allows.

2025-01-07 10:01 UTC, dlunde commented
Keep active.

2025-04-22 05:41 UTC, dlunde commented
Keep alive

2025-05-22 15:00 UTC, dlunde requested changes
Thanks for working on this @merykitty! Here is my long overdue review. I've studied both the existing logic in `PhaseChaitin::Split` (took quite some time) as well as your changes.

First, let me explain my understanding of the problem. Let me know if I've misunderstood something. In pass 1 during splitting, we get to a loop Phi with (at least) one unknown input, and determine from the other known inputs that the Phi is UP. Later on, it turns out one of the unknown inputs actually went DOWN, and additionally in a high frequency block. The Phi prematurely set to UP now forces us to put an expensive reload in the high frequency block.

> A downfall of this algorithm is that we may overspill, which means that after spilling some live ranges, the others do not need to be spilt anymore but are unnecessarily spilt.

I can reproduce the improvements for `LoopCounterBench.java`, so that looks good. Unfortunately, benchmarks (DaCapo, Renaissance, SPECjvm, SPECjbb) indicate more regressions than improvements. I've merged your changes with `master` and will rerun the benchmarks to double check.

Regarding the changeset, I think the code looks good overall. Can you elaborate more regarding the motivation behind the decision table and 10% threshold in `should_spill_before_loop`? What experiments did you run to confirm these are good choices? Perhaps the table and/or the threshold can be tuned to avoid the regressions found during the benchmarking above?

While I do think your suggested changes look reasonable, it seems to me that the fundamental problem is really that we only have partial reaching definitions information available when inserting Phis? I'm guessing it is too expensive to compute complete reaching defitions in the beginning of `PhaseChaitin::Split`, and to then update the reaching definitions continuously during splitting (because we add new definitions while splitting)? Would it perhaps be possible to first perform all the non-Phi splits, and then add required Phis afterwards? Just thinking out loud, there is likely some important interaction that I'm not aware of.

2025-05-28 15:21 UTC, merykitty commented on src/hotspot/share/opto/gcm.cpp
> -  }
It is incorrect, it should be `return this == b_loop`. However, I think it is redundant so I removed it altogether.

2025-05-28 15:22 UTC, merykitty commented on src/hotspot/share/opto/reg_split.cpp
> +      continue;
We are iterating through all the blocks in the loop nest. There is probably a more straight-forward way.

2025-07-23 23:46 UTC, closed without merging