8341927: Remove hardcoded SunJCE provider
openjdk/jdk pull request #21551
Opened 2024-10-16 18:47 UTC by mpdonova

In this PR, I removed hard-coded security providers and replaced them with a system property, test.provider.name. If the property is not specified, the provider originally used in the test is used:

Cipher c = Cipher.getInstance("AES/GCM/NoPadding", System.getProperty("test.provider.name", "SunJCE"));

2024-10-21 08:33 UTC, turbanoff commented on test/jdk/javax/security/auth/login/Configuration/GetInstance.java
> +                System.getProperty("test.provider.name","SUN"));
```suggestion
                System.getProperty("test.provider.name", "SUN"));
```

2024-10-21 08:33 UTC, turbanoff commented on test/jdk/javax/security/auth/login/Configuration/GetInstance.java
> +                    System.getProperty("test.provider.name","SunRsaSign"));
```suggestion
                    System.getProperty("test.provider.name", "SunRsaSign"));
```

2024-10-21 12:42 UTC, seanjmullan commented
You are changing more than SunJCE providers, so the title of this bug should not be specific to SunJCE. Suggest: "Replace hardcoded security providers with new test.provider.name system property".

Are there any cases where a test has more than one hardcoded provider?

2024-10-25 12:16 UTC, mpdonova commented
> You are changing more than SunJCE providers, so the title of this bug should not be specific to SunJCE. Suggest: "Replace hardcoded security providers with new test.provider.name system property".
> 
> Are there any cases where a test has more than one hardcoded provider?

I changed the name of the bug and PR. Yes there are cases where a test has more than one hardcoded provider.

2024-10-25 12:53 UTC, seanjmullan commented
> I changed the name of the bug and PR. Yes there are cases where a test has more than one hardcoded provider.

How would that work then if the property only allows you to specify one provider?

2024-10-25 17:28 UTC, mpdonova commented
> > I changed the name of the bug and PR. Yes there are cases where a test has more than one hardcoded provider.
> 
> How would that work then if the property only allows you to specify one provider?

The tests with multiple, hardcoded providers do that because the SunJCE provider doesn't implement every engine/algorithm. I've seen this mostly with Signatures and KeyPairGenerators. A provider specified via the property would have to implement all of the operations used in the test.

2024-10-29 22:29 UTC, ascarpino approved these changes

2024-10-30 14:15 UTC, seanjmullan requested changes

2024-10-30 14:15 UTC, seanjmullan commented on doc/testing.html
> +security providers</h3>
Avoid the word "external". Change this to "Testing with an alternate security provider".

2024-10-30 14:15 UTC, seanjmullan commented on doc/testing.html
> +specific provider when instantiating the service.</p>
s/specific/different/
No comma needed after "property".
s/service/service(s)/

2024-10-30 14:15 UTC, seanjmullan commented on doc/testing.html
> +<p>Some security tests currently use a hardcoded provider for
Remove "currently".
s/for/when instantiating/
s/or SecretKeyFactory/or SecretKeyFactory objects/

2024-10-30 14:15 UTC, seanjmullan commented on doc/testing.html
> +KeyFactory, Cipher, KeyPairGenerator, KeyGenerator, or SecretKeyFactory.
Put the APIs in code font.

2024-10-30 14:15 UTC, seanjmullan commented on doc/testing.md
> +### Testing with external security providers
Same comments as above apply here.

2024-10-30 14:15 UTC, seanjmullan commented on doc/testing.md
> +### Testing with external security providers
Duplicate entry?

2024-10-30 16:43 UTC, rhalade approved these changes

2024-10-30 16:45 UTC, seanjmullan commented on doc/testing.html
> +<code>SecretKeyFactory</code> objects. Specify the
I see some tests use a hard-coded provider for `Signature` too. Can you double-check all the changes and add any that you missed?

2024-10-30 18:47 UTC, seanjmullan approved these changes
Approving but I recommend a follow-on task be filed to check if some of these hard-coded providers are really necessary.

2024-10-30 18:50 UTC, mpdonova commented
/integrate

2024-10-30 18:51 UTC, closed without merging

2024-11-20 15:50 UTC, RealLucy commented
While reviewing the backport PR to jdk17, I stumbled across a potential functional incompleteness. There are a few tests which use more than one security provider. This works well when only the default providers are used. One example of such a test is `test/jdk/java/security/Signature/TestCloneable.java`. There are three providers by default:
```
        String dsaProviderName = System.getProperty("test.provider.name", "SUN");
        String ecProviderName  = System.getProperty("test.provider.name", "SunEC");
        String rsaProviderName = System.getProperty("test.provider.name", "SunRsaSign");
```
If the `test.provider.name` property is specified for a test run, all three name strings are set to the same provider name. The test will only succeed if the specified provider can handle the combined set of algorithms of all three default providers. 

These are the tests I found to be affected. The list is **not** believed to be complete.
```
test/jdk/java/security/Signature/TestCloneable.java
test/jdk/java/security/SignedObject/Chain.java
test/jdk/java/security/KexGenerator/TestGetInstance.java
test/jdk/java/security/Mac/TestGetInstance.java
test/jdk/java/security/auth/login/Configuration/GetInstance.java
test/jdk/java/security/X509/X509CertImpl/Verify.java
```