8342676: Unsigned Vector Min / Max transforms
openjdk/jdk pull request #21604
Opened 2024-10-21 11:01 UTC by jatin-bhateja

Adding following IR transforms for unsigned vector Min / Max nodes.

=> UMinV (UMinV(a, b), UMaxV(a, b)) => UMinV(a, b)
=> UMinV (UMinV(a, b), UMaxV(b, a)) => UMinV(a, b)
=> UMaxV (UMinV(a, b), UMaxV(a, b)) => UMaxV(a, b)
=> UMaxV (UMinV(a, b), UMaxV(b, a)) => UMaxV(a, b)
=> UMaxV (a, a) => a
=> UMin (a, a) => a

New IR validation test accompanies the patch.

This is a follow-up PR for https://github.com/openjdk/jdk/pull/20507

Best Regards,
Jatin

2025-01-08 09:11 UTC, eme64 requested changes
Generally looks reasonable. Smaller changes like this are much easier to review, thank you for splitting it out :blush: 

I started some testing, so feel free to ping me again for that.

2025-01-08 09:11 UTC, eme64 commented on src/hotspot/share/opto/vectornode.cpp
> +static Node* unsigned_min_max_xform(Node* n) {
```suggestion
static Node* UMinMaxV_Ideal(Node* n) {
```
I think this is how we generally name functions when we share them between nodes of different types.

2025-01-08 09:11 UTC, eme64 commented on src/hotspot/share/opto/vectornode.cpp
> +  if (umin && umax) {
That looks like an implicit null check. Not allowed according to style guide:
`Do not use ints or pointers as (implicit) booleans with &&, ||, if, while. Instead, compare explicitly, i.e. if (x != 0) or if (ptr != nullptr), etc.`
https://github.com/openjdk/jdk/blob/master/doc/hotspot-style.md

2025-01-08 09:11 UTC, eme64 commented on src/hotspot/share/opto/vectornode.cpp
> +  if (umin && umax) {
```suggestion
  if (umin != null && umax) != null {
```

2025-01-08 09:11 UTC, eme64 commented on src/hotspot/share/opto/vectornode.cpp
> +         (umin->in(2) == umax->in(1) && umin->in(1) == umax->in(2))) {
```suggestion
    if ((umin->in(1) == umax->in(1) && umin->in(2) == umax->in(2)) ||
        (umin->in(2) == umax->in(1) && umin->in(1) == umax->in(2))) {
```
Alignment was off

2025-01-08 11:37 UTC, jatin-bhateja commented on src/hotspot/share/opto/vectornode.hpp
> +  }
I think it will be better to schedule this patch after https://github.com/openjdk/jdk/pull/22863
where these nodes are marked at commutative operations.

2025-01-08 12:41 UTC, eme64 commented on src/hotspot/share/opto/vectornode.hpp
> +  }
Ah ok, I will put that one in my review queue! There is lots that have accumulated over the last 2 weeks :see_no_evil:

2025-01-09 22:44 UTC, rose00 commented on src/hotspot/share/opto/vectornode.hpp
> +  }
Suggestion: Align this hash expression and comment with existing ones elsewhere, such as:

https://github.com/openjdk/jdk/blob/931914af76932c9b91fc9affd55d24b2562c72d2/src/hotspot/share/opto/addnode.cpp#L47

2025-01-14 08:08 UTC, XiaohongGong commented on test/hotspot/jtreg/compiler/lib/ir_framework/IRNode.java
> +    static {
```suggestion
    public static final String UMIN_VB = VECTOR_PREFIX + "UMIN_VB" + POSTFIX;
    static {
```

2025-02-12 05:56 UTC, jatin-bhateja commented
/open

2025-03-28 09:46 UTC, jatin-bhateja commented
> @jatin-bhateja Just ping me here if this is ready for another review ;)

@eme64 , please have a look once you have some review cycles.

2025-03-28 11:17 UTC, eme64 requested changes
@jatin-bhateja Thanks for the updates! I have a few more comments :)

2025-03-28 11:17 UTC, eme64 commented on src/hotspot/share/opto/vectornode.cpp
> +bool VectorNode::is_commutative() {
Why did you make this change? It seems unrelated, maybe it slipped in from another change set? Plus, it is not an accurate name, if `if (in(1)->_idx > in(2)->_idx) {` would fail, you would say that it is not commutative ... which is wrong ;)

2025-03-28 11:17 UTC, eme64 commented on src/hotspot/share/opto/vectornode.cpp
> +  else if (lopc == Op_UMaxV && ropc == Op_UMinV) {
```suggestion
  } else if (lopc == Op_UMaxV && ropc == Op_UMinV) {
```

2025-03-28 11:17 UTC, eme64 commented on src/hotspot/share/opto/vectornode.cpp
> +  }
```suggestion
  } else {
    // Either both Min or Max.
    return nullptr;
  }
```
That way, you don't need the check below:
`umin != nullptr && umax != nullptr`.

2025-03-28 11:17 UTC, eme64 commented on src/hotspot/share/opto/vectornode.cpp
> +  return static_cast<VectorNode*>(n)->VectorNode::Ideal(phase, can_reshape);
Hmm. You now have a function `UMinMaxV_Ideal` that promises to do something specific (i.e. work with a MinMax case). But now you actually call into a more general method `VectorNode::Ideal`. I don't think that is a good approach ;)

Our usual approach is something like this:
```
  3871 Node *StoreBNode::Ideal(PhaseGVN *phase, bool can_reshape){
  3872   Node *progress = StoreNode::Ideal_masked_input(phase, 0xFF);                                                                                                                                                                                                                                                                                                                                                                       
  3873   if( progress != nullptr ) return progress;
  3874 
  3875   progress = StoreNode::Ideal_sign_extended_input(phase, 24);
  3876   if( progress != nullptr ) return progress;
  3877                                                                 
  3878   // Finally check the default case
  3879   return StoreNode::Ideal(phase, can_reshape);
  3880 }
```

That way, you don't have to do the whole trick with `static_cast<VectorNode*>(n)->` either.

2025-03-28 11:17 UTC, eme64 commented on src/hotspot/share/opto/vectornode.cpp
> +  return static_cast<VectorNode*>(n)->VectorNode::Ideal(phase, can_reshape);
Ah, and then `UMinMaxV_Ideal` also does not need the argument `can_reshape` any more!

2025-03-28 11:17 UTC, eme64 commented on src/hotspot/share/opto/vectornode.cpp
> +  return static_cast<VectorNode*>(n)->VectorNode::Ideal(phase, can_reshape);
```suggestion
  return nullptr;
```

2025-04-14 13:40 UTC, jatin-bhateja commented on src/hotspot/share/opto/vectornode.cpp
> +  return static_cast<VectorNode*>(n)->VectorNode::Ideal(phase, can_reshape);
It was done in anticipation of receiving a comment about duplicate code :-)

2025-04-14 13:40 UTC, jatin-bhateja commented on src/hotspot/share/opto/vectornode.cpp
> +  }
We still want to execute VectorNode::Ideal if new transforms are not applicable.

2025-04-17 09:05 UTC, eme64 reviewed
The code looks good to me. Let me run some more testing. Please ping me again in 24h+ and I can approve after the Easter weekend :)

2025-04-21 06:28 UTC, jatin-bhateja commented
> The code looks good to me. Let me run some more testing. Please ping me again in 24h+ and I can approve after the Easter weekend :)

Hi @eme64, pinging for approval if validation is green.

2025-04-21 10:22 UTC, eme64 approved these changes
Testing looks good, code too :blush: 

You'll need a second review though :)

2025-04-25 00:10 UTC, sviswa7 commented on test/hotspot/jtreg/compiler/vectorapi/VectorUnsignedMinMaxOperationsTest.java
> +            // UMaxV (UMinV vec2, vec1) (UMaxV vec1, vec2) => UMinV vec1 vec2
The above comment should be:
// UMaxV (UMinV vec2, vec1) (UMaxV vec1, vec2) => UMaxV vec1 vec2

2025-04-25 00:10 UTC, sviswa7 commented on test/hotspot/jtreg/compiler/vectorapi/VectorUnsignedMinMaxOperationsTest.java
> +            // UMaxV (UMinV vec1, vec2) (UMaxV vec2, vec1) => UMinV vec1 vec2
The above comment should be:
// UMaxV (UMinV vec1, vec2) (UMaxV vec2, vec1) => UMaxV vec1 vec2

2025-04-25 19:49 UTC, sviswa7 approved these changes
Looks good to me.

2025-04-26 03:30 UTC, jatin-bhateja commented
Thanks @eme64 and @sviswa7 for your review and approvals.

2025-04-26 03:30 UTC, jatin-bhateja commented
/integrate

2025-04-26 03:31 UTC, closed without merging