8342962
openjdk/jdk pull request #21703
Opened 2024-10-25 06:28 UTC by offamitkumar

We are on thin ice with the `TestOSRLotsOfLocals` test. Before it breaks, I'd like to provide the fix. :-)

2024-10-25 08:18 UTC, RealLucy requested changes
Just some academic improvements...

2024-10-25 08:18 UTC, RealLucy commented on src/hotspot/cpu/s390/c1_LIRAssembler_s390.cpp
> +      __ z_algr(OSR_buf, Z_R0_scratch);
How about using 
`__ z_algfi(OSR_buf, locals_space);`
instead?

2024-10-25 08:18 UTC, RealLucy commented on src/hotspot/cpu/s390/c1_LIRAssembler_s390.cpp
> +      __ z_slgr(OSR_buf, Z_R0_scratch);
How about using 
`__ z_slgfi(OSR_buf, locals_space);`
instead?

2024-10-25 08:28 UTC, offamitkumar commented on src/hotspot/cpu/s390/c1_LIRAssembler_s390.cpp
> +      __ z_slgr(OSR_buf, Z_R0_scratch);
updated :-)

2024-10-25 13:53 UTC, RealLucy approved these changes
Looks good now.
Yet another idea, though.

2024-10-25 13:53 UTC, RealLucy commented on src/hotspot/cpu/s390/c1_LIRAssembler_s390.cpp
> +    bool handled_manually = false;
Sorry, another idea (no need to accept it):
```
  bool large_offset = ! Immediate::is_simm20(monitor_offset + BytesPerWord) && number_of_locks > 0;

  if (large_offset) {
. . .
```

2024-10-25 16:16 UTC, RealLucy approved these changes
Wonderful!

2024-10-28 03:02 UTC, offamitkumar commented
@TheRealMDoerr can I get a review for this fix :-)

2024-10-28 10:36 UTC, TheRealMDoerr approved these changes
Looks correct to me. I suggest testing it by setting `large_offset` to true.

2024-10-29 04:21 UTC, offamitkumar commented
> I suggest testing it by setting large_offset to true.

I ran tier1 test again with suggested settings and didn't see any regression.

2024-10-29 04:22 UTC, offamitkumar commented
Thanks @RealLucy, @TheRealMDoerr for the reviews. 

/integrate

2024-10-29 04:22 UTC, closed without merging