8342808: Javadoc should add whitespace between type parameters
openjdk/jdk pull request #21759
Opened 2024-10-29 11:14 UTC by nizarbenalla

Please review this patch to render javadocs as `<K, V, T>` rather than `<K,V,T>` to match naming conventions and make the rendered output slighly nicer to read.

Passes langtool tests.

The generated docs only includes `java.base/lang`, `java.base/util` and `java.compiler/javax`

2024-10-31 13:50 UTC, hns commented
I'm not sure about this change. For the common case of single uppercase letter parameter names, I actually find the notation without space character more readable, and that also seems to be the convention in most OpenJDK code. 

If we are going to introduce a space character after the comma for type parameters, we also should get rid of the `<wbr>` (line break opportunity) element, as that is not needed anymore with the addes space.

2024-10-31 14:16 UTC, nizarbenalla commented
I don't have a big preference but the default source formatting recommendations seem to use spaces?
https://github.com/openjdk/jdk/blob/3ccd2f757d069c16147b331a90b1590c8ad4ae24/src/java.base/share/classes/java/util/function/Function.java#L41

2024-10-31 15:25 UTC, pavelrappo commented
> I'm not sure about this change.

IIRC, this feature was suggested by @minborg elsewhere. It would be nice if he advocated for it. Per, do you have anything to say here? Maybe other core-libs people have opinions on it?

> For the common case of single uppercase letter parameter names, I actually find the notation without space character more readable, and that also seems to be the convention in most OpenJDK code.

We use a mix of styles in code. However, in javadoc output, we should be uniform similarly to how we are uniform with method and constructor parameters, which we always separate with whitespace.

2024-10-31 16:06 UTC, pavelrappo commented
Not all reviewers might realise it, but javadoc currently outputs generics both ways, with whitespace and without. For example, have a look at [Map.of]. The first occurrence of generic parameters (i.e. declaration), immediately after the `static` keyword, has whitespace. The second occurrence (i.e. use) does not. I think we need to make up our mind on what we should do.

[Map.of]: https://docs.oracle.com/en/java/javase/23/docs/api/java.base/java/util/Map.html#of()

2024-10-31 17:34 UTC, jonathan-gibbons commented
It might be interesting to audit the JDK codebase for prevailing patterns in source code.  While regexes are not great for parsing, they may be good enough for a reasonably good analysis.
For example, as a start, look for
* `<[^> ]+>` -- instances of type parameters or arguments with no space (yes, it doesn't, do nested types, but it's good enough)
* `<[^>]+ [^>]+>` --  instances of type parameters or arguments with at least one space
* `((class|interface) [A-Za-z0-9]+)|public|static) *<[^> ]+>` -- instances of type parameters with no space
* `((class|interface) [A-Za-z0-9]+)|public|static) <[^>]+ [^>]+>` -- instances of type parameters at least one space

The regexes are just a suggestion and may need refinement.  The intent is to catch character sequences between `<` and `>` , and to further filter those that look like generic type or method declarations

2024-10-31 17:43 UTC, minborg commented
Some of the more prominent users of more-than-one-type-parameter declaration are `Map` and `Function` where the upper-case parameters have a space separator.  I think all `java.util.function` constructs with more than one type parameter have spaces after the coma(s).  Ultimately, it is a matter of taste but at least we should be consistent.

2024-10-31 17:52 UTC, jonathan-gibbons commented
I note there is an entity for a "thin space", U+2009. Maybe that could be a compromise here.

https://www.compart.com/en/unicode/U+2009

2024-10-31 17:58 UTC, hns commented
> Not all reviewers might realise it, but javadoc currently outputs generics both ways, with whitespace and without. For example, have a look at [Map.of](https://docs.oracle.com/en/java/javase/23/docs/api/java.base/java/util/Map.html#of()). The first occurrence of generic parameters (i.e. declaration), immediately after the `static` keyword, has whitespace. The second occurrence (i.e. use) does not. I think we need to make up our mind on what we should do.

I just looked into this, and what actually happens is that we have a special `HtmlLinkInfo.addLineBreaksInTypeParameters` flag to insert a newline character after the comma just for this particular case, but the CSS for this particular span of the method signature uses `white-space: normal;`, so the newline character is displayed as space. 

The code to add the newline in this particular position is rather ancient (previously encoded as `HtmlLinkInfo.Kind.MEMBER_TYPE_PARAMS`), and it was certainly never meant to be displayed with preformatted whitespace, so IMO the most likely reason to do this was to add a line break opportunity before we used `<wbr>`. Therefore, regardless of whether we decide to add a space or not, that flag and special case can be safely removed.

2024-10-31 18:09 UTC, RogerRiggs commented
My preference is to keep the compact declarations compact (so no spaces between single character types).
The longer type parameters are more readable with spaces (after ,).

2024-10-31 18:20 UTC, nizarbenalla commented
I'd like to be consistent with source formatting recommendations, and to have a uniform way of displaying output.
But I'm curious how many instances of single letters vs longer type parameters there are in the source code.

2024-11-01 09:29 UTC, hns commented
I have to correct my previous comment, the newline characters in type parameters of generic methods are actually displayed as preformatted text when type parameters are very long, such as [in this method][1].

[1]: https://docs.oracle.com/en/java/javase/23/docs/api/java.net.http/java/net/http/HttpResponse.BodySubscribers.html#fromSubscriber(java.util.concurrent.Flow.Subscriber,java.util.function.Function)

2024-11-05 15:27 UTC, nizarbenalla commented
For now, I will try to have no whitespace when we only have one letter parameters i.e `<K,V,T>` and add whitespace when we have type expressions as in `IntStream flatMapToInt(Function<? super T, ? extends IntStream> mapper)`

In case we have both, I'll still add whitespace.

2024-11-15 17:32 UTC, nizarbenalla commented
I have dialed down this change a bit. Now only affecting uses of parameterized types, in which the type arguments are longer type expressions.

as in (new):
 ![Screenshot 2024-11-15 at 18 28 07](https://github.com/user-attachments/assets/99ebd00b-7ce1-486a-89ef-76bfe8ed43f4)
 
 vs (old)
 
 
![Screenshot 2024-11-15 at 18 29 46](https://github.com/user-attachments/assets/3ca65475-65b1-4715-8836-8611fb9c0854)


Type parameters in class headings will remain with no spaces.

I have updated the PR's body with a new link to the generated documentation.

2024-11-18 13:08 UTC, pavelrappo requested changes

2024-11-18 13:08 UTC, pavelrappo commented on src/jdk.javadoc/share/classes/jdk/javadoc/internal/doclets/formats/html/HtmlLinkFactory.java
> +            boolean hasUsesOfParameterizedTypes =
I think we should name this variable better. Other than that, looks good.

2024-11-18 17:48 UTC, hns commented
To illustrate my previous comment, here are two screenshots of the `Spliterator.OfPrimitive` page heading:

1) in its current form without space

<img width="1237" alt="tp-no-space" src="https://github.com/user-attachments/assets/714454ff-4a95-4cc0-85a3-dd74ff5d1f0d">

2) with space added if bounds are present. 

<img width="1262" alt="tp-bounded-space" src="https://github.com/user-attachments/assets/bcfc7df0-93c8-4c3a-b720-f6f6e698e0d5">

2024-11-22 18:28 UTC, nizarbenalla commented
For visibility, here is the [generated Javadoc](https://cr.openjdk.org/~nbenalla/GeneratedDocs/8342808/docs/api/index.html) after this patch.

2024-11-25 17:19 UTC, hns requested changes
This looks good to me. The threshold of 8 characters is a bit arbitrary, but it seems reasonable. 

A few minor issues:
 - Since we don't really check for bounded type parameters but only for length I suggest renaming the boolean variable to something like `longTypeParams`.
 - The length threshold should be defined as a constant in a way that both `ClassWriter` and `HtmlLinkFactory` can use it.
 - The old `TYPE_PARAMS_MAX_INLINE_LENGTH` constant in `Signatures` isn't used anymore and should be removed.

2024-11-26 12:15 UTC, nizarbenalla commented
I wasn't happy with using a magic number but was unsure on where to define it.
Looking at the source code, most constants are defined in Writers.

2024-11-27 15:36 UTC, closed without merging