8342860: Fix more NULL usage backsliding
openjdk/jdk pull request #21826
Opened 2024-11-01 13:35 UTC by theoweidmannoracle

- Changed several "NULL" in comments to "null"
- Changed several `NULL` in code to `nullptr`

2024-11-01 13:38 UTC, theoweidmannoracle commented
/covered Oracle Employee

2024-11-04 19:11 UTC, SoniaZaldana requested changes
I am not a Reviewer but I left a small comment. 

Cheers!

2024-11-04 19:11 UTC, SoniaZaldana commented on src/hotspot/os/linux/cgroupSubsystem_linux.cpp
Missing copyright update.

2024-11-05 10:30 UTC, theoweidmannoracle commented on src/hotspot/os/linux/cgroupSubsystem_linux.cpp
Thanks for spotting this!

2024-11-05 14:22 UTC, SoniaZaldana commented
Hi @theoweidmannoracle, I think the GHA tests are not running because you haven't enabled GHA on your personal fork. See https://wiki.openjdk.org/display/SKARA/Testing for a bit more info.

2024-11-05 14:49 UTC, theoweidmannoracle commented
Hi @SoniaZaldana, thanks for pointing that out. I enabled the tests now, but it seems there's no way to run them except for pushing new changes. I did run Oracle's internal testing, though.

2024-11-05 15:00 UTC, SoniaZaldana commented
> Hi @SoniaZaldana, thanks for pointing that out. I enabled the tests now, but it seems there's no way to run them except for pushing new changes. I did run Oracle's internal testing, though.

You can try syncing your fork and that should trigger GHA.

2024-11-05 15:03 UTC, theoweidmannoracle commented
@SoniaZaldana Thanks for the tip!

2024-11-05 15:08 UTC, kimbarrett requested changes
Can you use the (updated) regex in the JBS issue description to verify the only
remaining "NULL"s in src/hotspot are jvmti.{xml,xsl} and
globalDefinitons_{gcc,visCPP}.hpp?

There are also some new NULLs in test/hotspot.
./jtreg/serviceability/jvmti/GetMethodDeclaringClass/libTestUnloadedClass.cpp
./jtreg/serviceability/jvmti/vthread/VThreadEventTest/libVThreadEventTest.cpp
There are a couple more (after filtering out java and C source files) that I think
shouldn't be changed.

2024-11-05 15:49 UTC, TheShermanTanker approved these changes

2024-11-05 16:02 UTC, kimbarrett requested changes
Can you use the (updated) regex in the JBS issue description to verify the
only remaining "NULL"s in src/hotspot are the jvmti.{xml,xls} files and the
globalDefinitions_{gcc,visCPP}.hpp files?

There are also some NULLs recently introduced in test/hotspot:
./jtreg/serviceability/jvmti/GetMethodDeclaringClass/libTestUnloadedClass.cpp
./jtreg/serviceability/jvmti/vthread/VThreadEventTest/libVThreadEventTest.cpp

(Found by applying the same regex to test/hotspot, and then removing .java and
.c files.)

There are a few other files in test/hotspot containing NULLs:
./jtreg/vmTestbase/nsk/share/jni/README
./jtreg/vmTestbase/nsk/share/jvmti/README
These are documentation files with examples written in C, so should not be changed.

./jtreg/vmTestbase/nsk/share/native/nsk_tools.hpp
In a comment describing a string to be used for printing.  Uses would need to
be examined to ensure it's okay to change the string used for a null value.
I think I planned to do this as a followup to JDK-8324799, and then forgot.
I'd be okay with doing something about this being separate from the current
PR.  While the necessary textual changes are probably small, there's a lot of
uses to examine to be sure a change is okay.

2024-11-05 16:13 UTC, kimbarrett commented
> Hi @SoniaZaldana, thanks for pointing that out. I enabled the tests now, but it seems there's no way to run them except for pushing new changes. I did run Oracle's internal testing, though.

To manually trigger GHA tests:
1. Go to your personal fork, and click on the "Actions" menu item.
2. Select the "OpenJDK GHA Sanity Checks" Action.
3. Click on the "Run workflow" pulldown.
4. Select the branch you want to test in the "Use workflow from" pulldown.
5. Click on "Run workflow".

2024-11-07 08:28 UTC, theoweidmannoracle commented
> Can you use the (updated) regex in the JBS issue description to verify the only remaining "NULL"s in src/hotspot are the jvmti.{xml,xls} files and the globalDefinitions_{gcc,visCPP}.hpp files?
> 
> There are also some NULLs recently introduced in test/hotspot: ./jtreg/serviceability/jvmti/GetMethodDeclaringClass/libTestUnloadedClass.cpp ./jtreg/serviceability/jvmti/vthread/VThreadEventTest/libVThreadEventTest.cpp
> 
> (Found by applying the same regex to test/hotspot, and then removing .java and .c files.)
> 
> There are a few other files in test/hotspot containing NULLs: ./jtreg/vmTestbase/nsk/share/jni/README ./jtreg/vmTestbase/nsk/share/jvmti/README These are documentation files with examples written in C, so should not be changed.
> 
> ./jtreg/vmTestbase/nsk/share/native/nsk_tools.hpp In a comment describing a string to be used for printing. Uses would need to be examined to ensure it's okay to change the string used for a null value. I think I planned to do this as a followup to JDK-8324799, and then forgot. I'd be okay with doing something about this being separate from the current PR. While the necessary textual changes are probably small, there's a lot of uses to examine to be sure a change is okay.

@kimbarrett I fixed the backslides in the *.cpp files you mentioned. The egrep outputs are now:

```
% find test/hotspot -type f ! -name "*.c" ! -name "*.java" -exec egrep -H "[^[:alnum:]_]NULL([^[:alnum:]_]|$)" {} \;
test/hotspot/jtreg/vmTestbase/nsk/share/native/nsk_tools.hpp: * Returns str or "<NULL>" if str is null; useful for printing strings.
test/hotspot/jtreg/vmTestbase/nsk/share/jvmti/README:    if (!NSK_JVMTI_VERIFY(jvmti->GetVersion(&version) != NULL)) {
test/hotspot/jtreg/vmTestbase/nsk/share/jni/README:            jni->FindClass(class_name) != NULL)) {
test/hotspot/jtreg/vmTestbase/nsk/share/jni/README:            jni->FindClass(class_name)) != NULL)) {
```

and 

```
egrep -R "[^[:alnum:]_]NULL([^[:alnum:]_]|$)" src/hotspot                                                      
src/hotspot/share/prims/jvmti.xml:    or return value. A "null pointer" is C <code>NULL</code> or C++ <code>nullptr</code>.
src/hotspot/share/prims/jvmti.xml:                       &amp;methodName, NULL, NULL);
src/hotspot/share/prims/jvmti.xml:  GetThreadCpuTime(env, NULL, nanos_ptr)
src/hotspot/share/prims/jvmti.xsl:        <xsl:value-of select="@const"/>, NULL)</code>
src/hotspot/share/utilities/globalDefinitions_visCPP.hpp:// When __cplusplus is defined, NULL is defined as 0 (32-bit constant) in
src/hotspot/share/utilities/globalDefinitions_visCPP.hpp:// On 64-bit architectures, defining NULL as a 32-bit constant can cause
src/hotspot/share/utilities/globalDefinitions_visCPP.hpp:// varargs, we pass the argument 0 as an int.  So, if NULL was passed to a
src/hotspot/share/utilities/globalDefinitions_visCPP.hpp:// only 32-bits of the "NULL" pointer may be initialized to zero.  The
src/hotspot/share/utilities/globalDefinitions_visCPP.hpp:// Solution: For 64-bit architectures, redefine NULL as 64-bit constant 0.
src/hotspot/share/utilities/globalDefinitions_visCPP.hpp:#undef NULL
src/hotspot/share/utilities/globalDefinitions_visCPP.hpp:#define NULL 0LL
src/hotspot/share/utilities/globalDefinitions_visCPP.hpp:#ifndef NULL
src/hotspot/share/utilities/globalDefinitions_visCPP.hpp:#define NULL 0
src/hotspot/share/utilities/globalDefinitions_visCPP.hpp:// NULL vs NULL_WORD:
src/hotspot/share/utilities/globalDefinitions_visCPP.hpp:// On Linux NULL is defined as a special type '__null'. Assigning __null to
src/hotspot/share/utilities/globalDefinitions_visCPP.hpp:#define NULL_WORD NULL
src/hotspot/share/utilities/globalDefinitions_gcc.hpp:// NULL vs NULL_WORD:
src/hotspot/share/utilities/globalDefinitions_gcc.hpp:// On Linux NULL is defined as a special type '__null'. Assigning __null to
src/hotspot/share/utilities/globalDefinitions_gcc.hpp:  #define NULL_WORD  NULL
```

2024-11-07 18:31 UTC, kimbarrett approved these changes
Looks good.

The grep results are exactly as expected.  Thanks for checking that.  Now if we can
just get the build to start checking for us, we can stop needing these periodic cleanups.
I forget whether a JBS issue has been filed for that.  If not, I will do so.

2024-11-07 21:46 UTC, kimbarrett commented
> The grep results are exactly as expected. Thanks for checking that. Now if we can just get the build to start checking for us, we can stop needing these periodic cleanups. I forget whether a JBS issue has been filed for that. If not, I will do so.

II've filed these followup issues:
https://bugs.openjdk.org/browse/JDK-8343802 Prevent NULL usage backsliding
https://bugs.openjdk.org/browse/JDK-8343800 Cleanup definition of NULL_WORD
https://bugs.openjdk.org/browse/JDK-8343801 Change string printed by nsk_null_string for null strings

2024-11-08 10:05 UTC, theoweidmannoracle commented
@jdksjolen @TheShermanTanker It would be great if you could also take another look at the latest changes I made. Thanks!

2024-11-08 10:27 UTC, TheShermanTanker approved these changes

2024-11-08 12:43 UTC, tschatzl approved these changes

2024-11-08 12:53 UTC, theoweidmannoracle commented
/integrate

2024-11-08 13:30 UTC, TheShermanTanker commented
/sponsor

2024-11-08 13:31 UTC, closed without merging