8335583: Avoid using pointers in CDS tables
openjdk/jdk pull request #21837
Opened 2024-11-01 16:39 UTC by matias9927

There are several calls to mark_pointer which can be avoided if offsets are used instead, This will help to reduce the archive size and reduce startup time.

This patch introduces some utility functions in the first commit to assist in converting to and from u4 offsets. For ease of review, consider looking at each commit separately as they each address an individual pointer to offset change. Verified with tier 1-5 tests.

2024-11-04 16:53 UTC, iklam requested changes

2024-11-04 16:53 UTC, iklam commented on src/hotspot/share/cds/lambdaFormInvokers.cpp
> +      } else {
The `if (ArchiveBuilder::is_active()` branch doesn't seem necessary, as this function is called in only a single place where this condition is false.

2024-11-04 16:53 UTC, iklam commented on src/hotspot/share/cds/runTimeClassInfo.hpp
> +      return ArchiveBuilder::current()->offset_to_buffered<InstanceKlass*>(_nest_host_offset);
I think this function is never called under this condition. Maybe the `if` should be turned into an assert:

```
assert(!ArchiveBuilder::is_active(), "not called when dumping archive");
```

2024-11-06 16:52 UTC, iklam approved these changes
LGTM

2024-11-06 18:19 UTC, calvinccheung approved these changes
Looks good.

2024-11-06 18:46 UTC, closed without merging