8256298: Shenandoah: Enable concurrent stack processing
openjdk/jdk pull request #2185
Opened 2021-01-21 17:33 UTC by zhengyu123

Please review this patch that enables concurrent stack processing for Shenandoah GC.

After this patch, all root processing are done concurrently for concurrent GC.

2021-01-25 12:48 UTC, rkennke requested changes
Wow that looks very nice and clean! I only have a few minor comments.

2021-01-25 12:48 UTC, rkennke commented on src/hotspot/share/gc/shenandoah/shenandoahHeap.hpp
> +  bool uses_stack_watermark_barrier() const { return true; }
This overrides a CollectedHeap method. I wonder if we should start adding 'override' keywords to overridden methods. However, this requires >=C++11, and might disturb backporting. Not sure about it.

2021-01-25 12:48 UTC, rkennke commented on src/hotspot/share/gc/shenandoah/shenandoahStackWatermark.cpp
> + * Copyright (c) 2020, Red Hat, Inc. All rights reserved.
This is structurally similar to zStackWatermark.cpp, and perhaps 'inspired' by it. Consider adding Oracle copyright there in addition to the Red Hat copyright. We did the same in e.g. shenandoahReferenceProcessor.hpp/cpp. Also, bump the copyright year to 2021 maybe?

2021-01-25 12:48 UTC, rkennke commented on src/hotspot/share/gc/shenandoah/shenandoahStackWatermark.hpp
> + * Copyright (c) 2020, Red Hat, Inc. All rights reserved.
Same comment as in shenandoahStackWatermark.cpp above.

2021-01-25 12:49 UTC, rkennke commented
/reviewers 2

2021-01-25 14:24 UTC, rkennke requested changes
Better, thanks! Found a few more very minor complaints (sorry... ;-) )

2021-01-25 14:24 UTC, rkennke commented on src/hotspot/share/gc/shenandoah/shenandoahStackWatermark.cpp
> + * Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
Small nit: the original copyright in the corresponding z* files is dated 2020. Please preserve that. Leave the Red Hat copyright at 2021. Sorry.

2021-01-25 14:24 UTC, rkennke commented on src/hotspot/share/gc/shenandoah/shenandoahStackWatermark.hpp
> +  virtual void do_code_blob(CodeBlob* cb);
There is no need to mark this virtual, or is there? I see you put override in the other place in that change, so maybe put it here too?

2021-01-25 14:24 UTC, rkennke commented on src/hotspot/share/gc/shenandoah/shenandoahStackWatermark.hpp
> +  virtual void start_processing_impl(void* context);
Also, similar to the other case, we might avoid virtual here, and use override instead?

2021-01-25 15:17 UTC, rkennke approved these changes
Looks good to me! Thank you!

2021-01-25 16:06 UTC, shipilev reviewed
Cursory review.

2021-01-25 16:06 UTC, shipilev commented on src/hotspot/share/gc/shenandoah/shenandoahHeap.hpp
> +  bool uses_stack_watermark_barrier() const override { return true; }
I wonder that this single use of `override` caused CLang to complain about the rest of the file: https://github.com/zhengyu123/jdk/runs/1762873416

2021-01-25 16:06 UTC, shipilev commented on src/hotspot/share/gc/shenandoah/shenandoahStackWatermark.cpp
> +  _epoch_id ++;
Excess space before `++`.

2021-01-25 18:22 UTC, zhengyu123 commented on src/hotspot/share/gc/shenandoah/shenandoahStackWatermark.cpp
> +  _epoch_id ++;
Done

2021-01-26 12:32 UTC, shipilev requested changes
Good job, I have only a few minor comments.

2021-01-26 12:32 UTC, shipilev commented on src/hotspot/share/gc/shenandoah/shenandoahPhaseTimings.hpp
> +  f(conc_mark_roots,                                "Concurrent Mark Roots ")          \
This seems like fixing the regression from JDK-8255765, is it not? Should be a separate issue?

2021-01-26 15:32 UTC, shipilev approved these changes

2021-01-26 16:45 UTC, zhengyu123 commented
/integrate

2021-01-26 16:46 UTC, closed without merging