8342541 :Exclude List/KeyEventsTest/KeyEventsTest.java from running on macOS
openjdk/jdk pull request #21924
Opened 2024-11-06 11:31 UTC by Renjithkannath

Hi Reviewers,

I have added the test tag  **@requires os.family != "mac"** and updated section with new format. 
Removed OSX check condition form the code.

Please review and let me know your suggestions if any.

2024-11-06 15:51 UTC, aivanov-jdk requested changes

2024-11-06 15:51 UTC, aivanov-jdk commented on test/jdk/java/awt/List/KeyEventsTest/KeyEventsTest.java
> +*  @key headful
```suggestion
/*
 *  @test
 *  @key headful
```
Align asterisks to the asterisk on the opening line.

2024-11-06 15:51 UTC, aivanov-jdk commented on test/jdk/java/awt/List/KeyEventsTest/KeyEventsTest.java
>              isWin = true;
Can be simplified to
```suggestion
        boolean isWin = Platform.isWindows();
```

2024-11-12 10:49 UTC, aivanov-jdk approved these changes

2024-11-12 15:08 UTC, Renjithkannath commented
/integrate

2024-11-19 18:18 UTC, prrace approved these changes

2024-11-19 18:18 UTC, prrace commented
/sponsor

2024-11-19 18:19 UTC, closed without merging