JDK-8343535: IGV: Colorize nodes on demand
openjdk/jdk pull request #21925
Opened 2024-11-06 12:19 UTC by tobiasholenstein

<img width="292" alt="color" src="https://github.com/user-attachments/assets/ea050a39-5f1e-456b-adaa-2102d78b0f60">

<img width="697" alt="pick" src="https://github.com/user-attachments/assets/67569b5d-1d74-4a93-8a97-bb37c5bc9f93">

<img width="428" alt="nodes" src="https://github.com/user-attachments/assets/c8a994e3-9946-42ae-8701-34223a000a0c">

Adds new option to IGV to color selected nodes:
1) select some nodes
2) `Ctrl + C` or `View` -> `Color action`
3) pick a color and apply

2024-11-06 12:43 UTC, chhagedorn approved these changes
That's a nice feature! Works as expected on Linux with the short cut.

2024-11-06 18:54 UTC, turbanoff commented on src/utils/IdealGraphVisualizer/View/src/main/java/com/sun/hotspot/igv/view/DiagramScene.java
> +        for (Figure figure :  model.getSelectedFigures()) {
```suggestion
        for (Figure figure : model.getSelectedFigures()) {
```

2024-11-08 08:49 UTC, robcasloz requested changes
Nice improvement, thanks for working on this!

If the user selects a dark color, the node labels might become hard to read. Here's a simple change that addresses that by coloring the labels in white in that case. Please consider merging it into this PR:
```
diff --git a/src/utils/IdealGraphVisualizer/View/src/main/java/com/sun/hotspot/igv/view/widgets/FigureWidget.java b/src/utils/IdealGraphVisualizer/View/src/main/java/com/sun/hotspot/igv/view/widgets/FigureWidget.java
index a469d196a6b..495d844eb34 100644
--- a/src/utils/IdealGraphVisualizer/View/src/main/java/com/sun/hotspot/igv/view/widgets/FigureWidget.java
+++ b/src/utils/IdealGraphVisualizer/View/src/main/java/com/sun/hotspot/igv/view/widgets/FigureWidget.java
@@ -113,7 +113,6 @@ public FigureWidget(final Figure f, DiagramScene scene) {
             LayoutFactory.SerialAlignment.LEFT_TOP :
             LayoutFactory.SerialAlignment.CENTER;
         middleWidget.setLayout(LayoutFactory.createVerticalFlowLayout(textAlign, 0));
-        middleWidget.setBackground(f.getColor());
         middleWidget.setOpaque(true);
         middleWidget.getActions().addAction(new DoubleClickAction(this));
         middleWidget.setCheckClipping(false);
@@ -143,7 +142,6 @@ public FigureWidget(final Figure f, DiagramScene scene) {
             textWidget.addChild(lw);
             lw.setLabel(displayString);
             lw.setFont(Diagram.FONT);
-            lw.setForeground(getTextColor());
             lw.setAlignment(LabelWidget.Alignment.CENTER);
             lw.setVerticalAlignment(LabelWidget.VerticalAlignment.CENTER);
             lw.setBorder(BorderFactory.createEmptyBorder());
@@ -151,6 +149,8 @@ public FigureWidget(final Figure f, DiagramScene scene) {
         }
         formatExtraLabel(false);
 
+        refreshColor();
+
         if (getFigure().getWarning() != null) {
             ImageWidget warningWidget = new ImageWidget(scene, warningSign);
             Point warningLocation = new Point(getFigure().getWidth() - Figure.WARNING_WIDTH - Figure.INSET / 2, 0);
@@ -186,6 +186,9 @@ protected Sheet createSheet() {
 
     public void refreshColor() {
         middleWidget.setBackground(figure.getColor());
+        for (LabelWidget lw : labelWidgets) {
+            lw.setForeground(getTextColor());
+        }
     }
 
     @Override

```

2024-11-08 09:02 UTC, robcasloz commented
In my opinion, the IGV toolbar is already pretty crowded (this hurts most when opening two graphs side-by-side) and I would prefer not adding the color icon there. On the other hand, we could add the action to the pop-up menu that's opened when right-clicking into a node or set of nodes. Here's my suggestion:

```
diff --git a/src/utils/IdealGraphVisualizer/View/src/main/java/com/sun/hotspot/igv/view/EditorTopComponent.java b/src/utils/IdealGraphVisualizer/View/src/main/java/com/sun/hotspot/igv/view/EditorTopComponent.java
index e68abd3297e..c4f2ac670e7 100644
--- a/src/utils/IdealGraphVisualizer/View/src/main/java/com/sun/hotspot/igv/view/EditorTopComponent.java
+++ b/src/utils/IdealGraphVisualizer/View/src/main/java/com/sun/hotspot/igv/view/EditorTopComponent.java
@@ -100,6 +100,7 @@ public EditorTopComponent(DiagramViewModel diagramViewModel) {
         };
 
         Action[] actionsWithSelection = new Action[]{
+                ColorAction.get(ColorAction.class),
                 ExtractAction.get(ExtractAction.class),
                 HideAction.get(HideAction.class),
                 null,
@@ -168,8 +169,6 @@ public void mouseMoved(MouseEvent e) {}
         toolBar.add(ReduceDiffAction.get(ReduceDiffAction.class));
         toolBar.add(ExpandDiffAction.get(ExpandDiffAction.class));
         toolBar.addSeparator();
-        toolBar.add(ColorAction.get(ColorAction.class));
-        toolBar.addSeparator();
         toolBar.add(ExtractAction.get(ExtractAction.class));
         toolBar.add(HideAction.get(HideAction.class));
         toolBar.add(ShowAllAction.get(ShowAllAction.class));
diff --git a/src/utils/IdealGraphVisualizer/View/src/main/java/com/sun/hotspot/igv/view/actions/ColorAction.java b/src/utils/IdealGraphVisualizer/View/src/main/java/com/sun/hotspot/igv/view/actions/ColorAction.java
index a51934a4322..92921c81512 100644
--- a/src/utils/IdealGraphVisualizer/View/src/main/java/com/sun/hotspot/igv/view/actions/ColorAction.java
+++ b/src/utils/IdealGraphVisualizer/View/src/main/java/com/sun/hotspot/igv/view/actions/ColorAction.java
@@ -43,7 +43,7 @@
         @ActionReference(path = "Shortcuts", name = "D-C")
 })
 @Messages({
-        "CTL_ColorAction=Color action",
+        "CTL_ColorAction=Color",
         "HINT_ColorAction=Color current set of selected nodes"
 })
 public final class ColorAction extends ModelAwareAction {
diff --git a/src/utils/IdealGraphVisualizer/View/src/main/java/com/sun/hotspot/igv/view/actions/ExtractAction.java b/src/utils/IdealGraphVisualizer/View/src/main/java/com/sun/hotspot/igv/view/actions/ExtractAction.java
index 24815527a0e..c2329cbb26f 100644
--- a/src/utils/IdealGraphVisualizer/View/src/main/java/com/sun/hotspot/igv/view/actions/ExtractAction.java
+++ b/src/utils/IdealGraphVisualizer/View/src/main/java/com/sun/hotspot/igv/view/actions/ExtractAction.java
@@ -42,7 +42,7 @@
         @ActionReference(path = "Shortcuts", name = "D-X")
 })
 @Messages({
-        "CTL_ExtractAction=Extract action",
+        "CTL_ExtractAction=Extract",
         "HINT_ExtractAction=Extract current set of selected nodes"
 })
 public final class ExtractAction extends ModelAwareAction {
```

@tobiasholenstein @chhagedorn what do you think? If you agree, feel free to merge the patch into this PR.

2024-11-08 09:10 UTC, chhagedorn commented
> If the user selects a dark color, the node labels might become hard to read. Here's a simple change that addresses that by coloring the labels in white in that case. Please consider merging it into this PR:

Great idea!

> In my opinion, the IGV toolbar is already pretty crowded (this hurts most when opening two graphs side-by-side) and I would prefer not adding the color icon there

I agree with this. Maybe we should generally thinking about cleaning the toolbar in general and dropping some of the fewer used icons.
 
> On the other hand, we could add the action to the pop-up menu that's opened when right-clicking into a node or set of nodes. 

I thought about this, too. I think that would be quite handy and an intuitive thing to do when not being aware of the feature and checking if there is an option to do it.

2024-11-08 10:36 UTC, tobiasholenstein commented
@robcasloz I have applied both your patches

2024-11-08 10:46 UTC, robcasloz approved these changes
Looks good, thanks Toby! I see that you also fixed the extra label color, nice! would be good to factor out that code together with that of `FigureWidget::getTextColor()`, but not a must.

2024-11-08 10:49 UTC, tobiasholenstein commented
/contributor add @robcasloz

2024-11-08 11:29 UTC, chhagedorn approved these changes
Looks good! Just tried it out. One more thing I've noticed: When selecting a color for a node and then trying to color another node, the color selection resets back to `#ffffff`. Would be nice if the last selection would have been stored. But I'm not sure how easy this is. Could also be done separately.

2024-11-08 14:29 UTC, tobiasholenstein commented
> Looks good! Just tried it out. One more thing I've noticed: When selecting a color for a node and then trying to color another node, the color selection resets back to `#ffffff`. Would be nice if the last selection would have been stored. But I'm not sure how easy this is. Could also be done separately.

![Screenshot 2024-11-08 at 15 27 06](https://github.com/user-attachments/assets/6dbf0732-f643-4ee2-add9-6adaee380fc0)

right. I have updated it now to save the last colors and provide some default colors

2024-11-08 14:47 UTC, tobiasholenstein commented
> Looks good, thanks Toby! I see that you also fixed the extra label color, nice! would be good to factor out that code together with that of `FigureWidget::getTextColor()`, but not a must.

done

2024-11-08 15:12 UTC, chhagedorn commented
Great idea with the defaults! I've just tried it out on Linux. It does seem to remember my last choice and offers me some defaults. But somehow the window look off:

![image](https://github.com/user-attachments/assets/626f6aef-195a-4b37-9869-16e8ccf26517)

The defaults are hard to see and the rectangle saying "Preview" to the left is strange. It also says "Color Name: #ffffff" even though it chooses the last selected one correctly when pressing "OK".

2024-11-11 12:51 UTC, chhagedorn approved these changes
Now, after many tries, it seems to work! :-) Thanks for investigating further. Looks good!

2024-11-11 13:09 UTC, robcasloz approved these changes

2024-11-11 13:24 UTC, tobiasholenstein commented
thanks for the reviews @robcasloz and @chhagedorn 

/integrate

2024-11-11 13:25 UTC, closed without merging