8277240
openjdk/jdk pull request #21942
Opened 2024-11-06 23:59 UTC by prrace

This test has had reports of failures over the years notably on Linux.
I think the large number of XVisuals may have something to do with it.
I've updated it quite a bit and limited the number of dialogs it creates - we really don't need to test 300 of them
This new version has passed hundreds of iterations.

2024-11-07 12:54 UTC, aivanov-jdk requested changes

2024-11-07 22:05 UTC, prrace commented on test/jdk/java/awt/Graphics2D/ScaledTransform/ScaledTransform.java
> +                             (gcTx.getScaleY() == gTx.getScaleY());
hmm. I don't agree with that convention, it disrupts the indentation. So I prefer to leave it as it always was.

2024-11-07 22:05 UTC, prrace commented on test/jdk/java/awt/Graphics2D/ScaledTransform/ScaledTransform.java
> +                endTime = System.currentTimeMillis();
ok

2024-11-07 22:05 UTC, prrace commented on test/jdk/java/awt/Graphics2D/ScaledTransform/ScaledTransform.java
> +       }
ok

2024-11-07 22:05 UTC, prrace commented on test/jdk/java/awt/Graphics2D/ScaledTransform/ScaledTransform.java
> +
OK .. but I don't think it is a big deal

2024-11-08 15:34 UTC, aivanov-jdk approved these changes

2024-11-08 20:36 UTC, prrace commented
/integrate

2024-11-08 20:37 UTC, closed without merging