8150564: Migrate useful ExtendedRobot methods into awt.Robot
openjdk/jdk pull request #22044
Opened 2024-11-12 17:39 UTC by alisenchung

Some useful methods in ExtendedRobot should be migrated into Robot itself so that ExtendedRobot can be removed in the future. The tests using ExtendedRobot for these migrated methods are changed to use only Robot (removing unnecessary building of ExtendedRobot).

2024-11-13 19:48 UTC, prrace commented
Please resolve the merge conflict.

2024-11-13 19:51 UTC, prrace commented on src/java.desktop/share/classes/java/awt/Robot.java
> +//        throw new RuntimeException("click");
get rid of the comments.
Also you need @since  tags on the new methods

2024-11-13 19:51 UTC, prrace commented on src/java.desktop/share/classes/java/awt/Robot.java
> +//        throw new RuntimeException("click");
same

2024-11-13 19:51 UTC, prrace commented on src/java.desktop/share/classes/java/awt/Robot.java
> +//        throw new RuntimeException("waitForIdle");
same .. I'm not going to point them all out, just fix them

2024-11-13 19:51 UTC, prrace commented
/csr

2024-11-13 19:51 UTC, prrace commented
/reviewers reviewers 2

2024-11-13 20:05 UTC, prrace commented
/reviewers 2 reviewers

2024-11-26 08:30 UTC, kumarabhi006 commented on test/jdk/java/awt/Frame/DecoratedExceptions/DecoratedExceptions.java
Expand wild imports here and in other tests wherever applicable.

2024-11-26 21:07 UTC, alisenchung commented on test/jdk/java/awt/Frame/DecoratedExceptions/DecoratedExceptions.java
out of scope of this change, i won't be changing any tests here outside of stuff relating to ExtendedRobot (also expanding imports of 200+ tests would be insane)

2025-01-28 04:57 UTC, alisenchung commented
/open

2025-02-24 21:26 UTC, azvegint commented on test/jdk/lib/client/ExtendedRobot.java
> -        waitForIdle(syncDelay);
This `waitForIdle(500)` is no longer called by tests(as it uses regular `java.awt.Robot#waitForIdle()`, so I assume you have verified that automated testing looks good. (I haven't gone through all the tests yet)

2025-02-24 21:26 UTC, azvegint commented on src/java.desktop/share/classes/java/awt/Robot.java
> +    public static final int DEFAULT_STEP_LENGTH = 2;
Do we want to make the `DEFAULT_DELAY` and `DEFAULT_STEP_LENGTH` configurable?

2025-02-24 21:26 UTC, azvegint commented on src/java.desktop/share/classes/java/awt/Robot.java
> +            mouseMove((int)x, (int)y);
`mouseMove` can throw an `IllegalThreadStateException` under certain circumstances.

2025-02-24 21:26 UTC, azvegint commented on src/java.desktop/share/classes/java/awt/Robot.java
> +    public void glide(int x, int y) {
I don't see the `public void glide(Point dest)` and `public void glide(Point src, Point dest)` added, it may be convenient in some cases.

2025-02-24 21:26 UTC, azvegint commented on test/jdk/java/awt/Component/PaintAll/PaintAll.java
>    @library /lib/client/
It's not needed anymore, is it?
```suggestion
```

2025-02-24 21:26 UTC, azvegint commented on test/jdk/lib/client/ExtendedRobot.java
> -    public void type(char c) {
Those `type(char...` are not migrated also. 

At least one test uses it:

https://github.com/alisenchung/jdk/blob/8150564/test/jdk/java/awt/Window/ShapedAndTranslucentWindows/ShapedTranslucentWindowClick.java#L178

With your change, it now calls `type(int)` directly, which has a different implementation.

2025-05-07 15:51 UTC, alisenchung commented
/open

2025-05-08 21:26 UTC, prrace commented on src/java.desktop/share/classes/java/awt/Robot.java
> +     * Default 20 milliseconds delay for mouse {@code click} and
Be aware that values of static fields are automatically documented.
eg see
(https://docs.oracle.com/en/java/javase/21/docs/api/constant-values.html#java.awt.Font.BOLD)

And an app really could use knowing what the default is.
And these defaults have been battle-tested in ExtendedRobot

2025-05-08 21:26 UTC, prrace commented on src/java.desktop/share/classes/java/awt/Robot.java
> +    public static final int DEFAULT_STEP_LENGTH = 2;
glide  has over-rides step length

2025-05-08 21:26 UTC, prrace commented on src/java.desktop/share/classes/java/awt/Robot.java
> +     * {@link java.awt.Robot#mousePress(int)}.
I understand the concern but in this case it is more or less explanation of what the method does. Perhaps it can be adjusted or made in to an apiNote or whatever is best.

2025-05-08 21:26 UTC, prrace commented on src/java.desktop/share/classes/java/awt/Robot.java
> +            mouseMove((int)x, (int)y);
yes should be added to all glide API methods

2025-05-12 23:23 UTC, alisenchung commented on src/java.desktop/share/classes/java/awt/Robot.java
> +    public void glide(int x, int y) {
I've taken a look at all the tests running glide and very few of them actually used glide(Point dest) and glide(Point src, Point dest) so I decided to remove them from them from the migration

2025-06-10 21:40 UTC, alisenchung commented on test/jdk/lib/client/ExtendedRobot.java
> -    public void type(char c) {
i've now also migrated type(int)

2025-06-11 17:49 UTC, honkar-jdk reviewed
I see couple of tests that use ExtendedRobot which can be changed to use Robot. Can you double check these tests.

```
java/awt/Frame/DisposeParentGC/DisposeParentGC.java
java/awt/List/SetBackgroundTest/SetBackgroundTest.java
java/awt/Modal/ToBack/ToBackFDFTest.java
```

2025-06-11 17:49 UTC, honkar-jdk commented on test/jdk/lib/client/ExtendedRobot.java
> -    }
Shouldn't `glide(Point src, Point dest)` and `glide(Point dest)` be retained in ExtendedRobot
In a [previous comment](https://github.com/openjdk/jdk/pull/22044/files#r2085671341) it was mentioned that these methods won't be migrated so do they need to be retained in ExtendedRobot ?

I see `MultipleMouseButtonsTest.java` using `glide(Point src, Point dest)`. There are two options here:

1) Either update the test to use Robot's glide()
change the line `robot.glide(origin, center)` to `robot.glide(origin.x, origin.y, center.x, center.y);`  and completely remove ExtendedRobot versions of glide.

2) Or retain these two convenience methods in ExtendedRobot.

2025-06-11 18:12 UTC, honkar-jdk commented on test/jdk/lib/client/ExtendedRobot.java
> -    }
There are few other tests that use ExtendedRobot version of glide() so probably option 2 (retaining the two convenience methods in ExtendedRobot) might be a better option.

2025-06-11 18:33 UTC, honkar-jdk commented on test/jdk/java/awt/TrayIcon/TrayIconPopup/TrayIconPopupTest.java
> +    Robot robot;
This test still builds ExtendedRobot which is no longer needed. Applicable for other tests as well. 

```
@library /lib/client
@build ExtendedRobot
```

2025-06-12 18:04 UTC, alisenchung commented on test/jdk/lib/client/ExtendedRobot.java
> -    }
I think ideally ER will be removed in the future so depending on the number of tests using glide(point), I will either change the tests or readd glide(point) to Robot.

2025-06-17 16:49 UTC, honkar-jdk requested changes
Since there are many test changes it is good to run CI on latest update.

2025-06-17 16:49 UTC, honkar-jdk commented on test/jdk/java/awt/TrayIcon/TrayIconPopup/TrayIconPopupTest.java
> - *          ExtendedRobot
Since ExtendedRobot is removed /lib/client is no longer required in `@library` tag. Applicable for other tests as well.

2025-06-17 17:00 UTC, honkar-jdk commented on test/jdk/java/awt/Modal/ModalBlockingTests/BlockingDDModelessTest.java
>   * @library /test/lib
Same here /lib/client is no longer required.

2025-07-03 22:50 UTC, honkar-jdk reviewed
Latest changes LGTM. 

@alisenchung 
Does CI run look good with the latest changes?

2025-07-03 22:56 UTC, honkar-jdk commented on test/jdk/java/awt/TrayIcon/TrayIconPopup/TrayIconPopupTest.java
> - *          ExtendedRobot
There are couple of tests with /lib/client in `@library` tag which is no longer required. This cleanup can be handled in subsequent PR.

2025-07-08 18:31 UTC, prrace commented on src/java.desktop/share/classes/java/awt/Robot.java
> +     * {@code mousePress} and {@code mouseRelease} calls. For specifics on valid inputs please see
I think in a spec, we can drop "please".

2025-07-08 18:42 UTC, prrace commented on src/java.desktop/share/classes/java/awt/Robot.java
> +     * {@link java.awt.Robot#mousePress(int)}.
If this method doesn't call waitForIdle there's no reason to  document here that you'll get IllegalThreadStateException if called on the EDT, and waitForIdle is the sole source of ITSE.
So since we are obliged to document the IllegalThreadStateException I don't think it does any harm to say it calls waitForIdle.

2025-07-08 18:43 UTC, prrace commented on src/java.desktop/share/classes/java/awt/Robot.java
> +     * Default delay for mouse {@code click} and
Default delay .. in milliseconds ..

2025-07-11 20:10 UTC, prrace commented on src/java.desktop/share/classes/java/awt/Robot.java
> +    public static final int DEFAULT_STEP_LENGTH = 2;
@alisenchung did you see the above ? 
Looks like email for it may not have been generated because I *edited* an old comment rather than adding a new one.

2025-07-14 16:41 UTC, alisenchung commented on src/java.desktop/share/classes/java/awt/Robot.java
> +    public static final int DEFAULT_STEP_LENGTH = 2;
I think setting the default step length with a setter/getter makes sense. I think generally tests don't change the step delays across their glides anyway and it would remove the need for all those extra overrides for glide. I'll make this change now

2025-07-14 19:22 UTC, alisenchung commented
I've decided to remove click/type's usage of the default step-delay and just forced them to use a delay of 20ms since I don't think anyone would need to explicitly set a delay for clicking and typing. I also made the step delay/length to be configurable for glide and added setters/getters for them. Because of that I removed the last glide override that explicitly set the delay and length.

2025-07-22 22:18 UTC, prrace commented on src/java.desktop/share/classes/java/awt/Robot.java
> +    private static int stepLength = DEFAULT_STEP_LENGTH;
These should not be static. They apply to THIS robot instance, not all of them.

2025-07-22 22:19 UTC, prrace commented on src/java.desktop/share/classes/java/awt/Robot.java
> +        Robot.stepLength = stepLength;
Not a static

2025-07-22 22:20 UTC, prrace commented on src/java.desktop/share/classes/java/awt/Robot.java
> +        Robot.stepDelay = stepDelay;
Not a static

2025-07-23 20:33 UTC, alisenchung commented
removed static from step delay and step length fields

2025-07-25 18:11 UTC, prrace commented on test/jdk/lib/client/ExtendedRobot.java
> -     public void glide(int srcX, int srcY, int destX, int destY, int stepLength, int speed) {
I hadn't noticed that this over-ride is both removed here and not added to Robot.
If this were available, then perhaps those setters and getters for the current values aren't needed !
What was the reason for not including it ? No one ever used it or something else ?

2025-07-25 18:11 UTC, prrace commented on src/java.desktop/share/classes/java/awt/Robot.java
> +     * @throws  IllegalArgumentException if {@code stepLength} is greater than the distance
In the CSR Joe asked if glide(int, int) needed to throw IAE and it made me look here and I don't actually see where this code would throw that. 
And the old extended robot never had such a feature, did it ?
Also if you think of glide as a sequence of steps, then even with the default of "2" if the distance to move is say "5" after 2 steps you are one pixel away and then I presume we just step one pixel for the final step.
So how is that different than STARTING one pixel away ?

Perhaps we can just dispense with the IAE and if dist < steplength then there's just one step.

2025-07-28 16:43 UTC, alisenchung commented on test/jdk/lib/client/ExtendedRobot.java
> -     public void glide(int srcX, int srcY, int destX, int destY, int stepLength, int speed) {
I actually removed this when I added the setters/getters since I thought it was redundant. Do you think having this override is better than having the setters/getters? I can revert the change

2025-07-28 17:02 UTC, prrace commented on test/jdk/lib/client/ExtendedRobot.java
> -     public void glide(int srcX, int srcY, int destX, int destY, int stepLength, int speed) {
Sorry for the churn, but yes I do think revert to the override

2025-08-01 22:13 UTC, prrace commented on src/java.desktop/share/classes/java/awt/Robot.java
> +     * steps from its current location to the destination coordinates. Invokes
I think this is the text that caused Joe to write
"From reading the text, it should like the method would benefit from an @implSpec tag describing the behavior."
You can read about implSpec here https://bugs.openjdk.org/browse/JDK-8068562

2025-08-05 02:38 UTC, alisenchung commented on src/java.desktop/share/classes/java/awt/Robot.java
> +     * steps from its current location to the destination coordinates. Invokes
I've moved the description of the implementation into a implSpec tag for both glide(int int) and glide(int int int int). I'm not sure if and how the implSpec should be expanded to include more detail. Do you have any suggestions?

2025-08-07 13:14 UTC, azvegint commented on src/java.desktop/share/classes/java/awt/Robot.java
> +    public void glide(int fromX, int fromY, int toX, int toY) {
```suggestion
    public void glide(int srcX, int srcY, int dstX, int dstY) {
```

* for parameter naming consistency with the `public void glide(int srcX, int srcY, int destX, int destY, int stepLength, int stepDelay)`

2025-08-07 17:22 UTC, azvegint commented on test/jdk/java/awt/datatransfer/Independence/IndependenceSwingTest.java
>   * @library /lib/client
```suggestion
```

Many tests still use `@library /lib/client`.

Not only are they unnecessary in most cases, but they can also hide the use of `ExtendedRobot`.

For example, in this test, the use of `ExtendedRobot` has not been removed, and it is implicitly compiled due to the presence of `@library /lib/client`. After removing `@library`, the test no longer compiles.
```
error: cannot find symbol
    private static ExtendedRobot robot;
```

I suggest removing all unnecessary uses of `@library/lib/client` because there are still plenty of uses of `ExtendedRobot` in other tests as well.

This issue has been [raised](https://github.com/openjdk/jdk/pull/22044#discussion_r2140831788) before, but it has not yet been resolved for all tests.

---

Also, please run a grep search for `ExtendedRobot` in the `test/jdk` directory.  This pull request does not cover many tests that still use the `ExtendedRobot` (which doesn't even use the `dragAndDrop()` and can be safely removed).

2025-08-07 17:22 UTC, azvegint commented on test/jdk/lib/client/ExtendedRobot.java
>      public void dragAndDrop(Point from, Point to){
I missed that earlier. Why didn't we also move the `dragAndDrop` methods to `java.awt.Robot`?
This would allow us to remove the ExtendedRobot class entirely.

2025-08-07 19:05 UTC, alisenchung commented on test/jdk/java/awt/datatransfer/Independence/IndependenceSwingTest.java
>   * @library /lib/client
I planned on removing ExtendedRobot from these tests in a separate followup PR since there are many test changes in this one already.

2025-08-07 19:08 UTC, alisenchung commented on test/jdk/lib/client/ExtendedRobot.java
>      public void dragAndDrop(Point from, Point to){
When I ran tests earlier to see which ExtendedRobot methods were used previously i found that dragAndDrop was never used by any tests, so I decided not to migrate it. It might be better to just remove it all outright and I might do that in a followup PR to remove ExtendedRobot entirely (along with moving the rest of the tests using ER)

2025-08-07 20:55 UTC, azvegint commented on test/jdk/lib/client/ExtendedRobot.java
>      public void dragAndDrop(Point from, Point to){
>  i found that dragAndDrop was never used by any tests

This doesn't seem to be true. I see several tests using it:

```
./java/awt/Window/ShapedAndTranslucentWindows/StaticallyShaped.java:73:        robot.dragAndDrop(location.x + dl, location.y + 5, location.x + dl + random.nextInt(dl), location.y + random.nextInt(dl));
./java/awt/Window/ShapedAndTranslucentWindows/StaticallyShaped.java:79:        robot.dragAndDrop(location.x + 4, location.y + 4, location.x + random.nextInt(2*dl)-dl, location.y + random.nextInt(2*dl)-dl);
./java/awt/Window/ShapedAndTranslucentWindows/ShapedTranslucent.java:75:        robot.dragAndDrop(location.x + dl, location.y + 5, location.x + dl + random.nextInt(dl), location.y + random.nextInt(dl));
./java/awt/Window/ShapedAndTranslucentWindows/ShapedTranslucent.java:81:        robot.dragAndDrop(location.x + 4, location.y + 4, location.x + random.nextInt(2*dl)-dl, location.y + random.nextInt(2*dl)-dl);
./java/awt/Window/ShapedAndTranslucentWindows/Translucent.java:72:        robot.dragAndDrop(location.x + dl, location.y + 5, location.x + dl + random.nextInt(dl), location.y + random.nextInt(dl));
./java/awt/Window/ShapedAndTranslucentWindows/Translucent.java:78:        robot.dragAndDrop(location.x + 4, location.y + 4, location.x + random.nextInt(2*dl)-dl, location.y + random.nextInt(2*dl)-dl);
./java/awt/Window/ShapedAndTranslucentWindows/Shaped.java:75:        robot.dragAndDrop(location.x + dl, location.y + 5, location.x + dl + random.nextInt(dl), location.y + random.nextInt(dl));
./java/awt/Window/ShapedAndTranslucentWindows/Shaped.java:81:        robot.dragAndDrop(location.x + 4, location.y + 4, location.x + random.nextInt(2*dl)-dl, location.y + random.nextInt(2*dl)-dl);
./java/awt/Window/ShapedAndTranslucentWindows/ShapedTranslucentWindowClick.java:174:        robot.dragAndDrop(MouseInfo.getPointerInfo().getLocation(), new Point(x+5, y));
./java/awt/event/MouseEvent/DragToLightweightTest.java:79:        robot.dragAndDrop(
./javax/swing/JWindow/ShapedAndTranslucentWindows/Common.java:369:        robot.dragAndDrop(location.x + 30, location.y + 5, location.x + dl + random.nextInt(dl), location.y + random.nextInt(dl));
./javax/swing/JWindow/ShapedAndTranslucentWindows/Common.java:375:        robot.dragAndDrop(location.x + 4, location.y + 4, location.x + random.nextInt(2*dl)-dl, location.y + random.nextInt(2*dl)-dl);
./javax/swing/JWindow/ShapedAndTranslucentWindows/Common.java:387:        robot.dragAndDrop(location.x + 30, location.y + 5, location.x + dl + random.nextInt(dl), location.y + random.nextInt(dl));
./javax/swing/JWindow/ShapedAndTranslucentWindows/Common.java:393:        robot.dragAndDrop(location.x + 4, location.y + 4, location.x + random.nextInt(2*dl)-dl, location.y + random.nextInt(2*dl)-dl);
```

It seems to be a convenient method because it eliminates the need for all this hassle with a single call.


```java
robot.mouseMove(fromX, fromY);
robot.mousePress(InputEvent.BUTTON1_DOWN_MASK);
robot.waitForIdle();
robot.glide(toX, toY);
robot.mouseRelease(InputEvent.BUTTON1_DOWN_MASK);
robot.waitForIdle();
```

vs

```java
robot.dragAndDrop(fromX, fromY, toX, toY)
```

2025-08-07 22:55 UTC, alisenchung commented on test/jdk/lib/client/ExtendedRobot.java
>      public void dragAndDrop(Point from, Point to){
I've migrated dragAndDrop(int, int, int, int) and updated the csr to include the migration. Can you take a look at the specification to see if it meets the standard?

2025-08-07 22:58 UTC, alisenchung commented on test/jdk/java/awt/datatransfer/Independence/IndependenceSwingTest.java
>   * @library /lib/client
I've updated the current tests in to remove /client/lib from the tests I already removed ER from and I'll remove the remaining tests when I remove ER in a followup PR

2025-08-08 15:04 UTC, azvegint commented on src/java.desktop/share/classes/java/awt/Robot.java
> +     * destination point ({@code toX}, {@code toY}), then releases mouse button 1.
It can probably be omitted because it's essentially the same information that's already stated in the previous sentence and the `@param` tags.

2025-08-08 15:22 UTC, azvegint commented on test/jdk/java/awt/datatransfer/Independence/IndependenceSwingTest.java
>   * @library /lib/client
> I've updated the current tests in to remove /client/lib from the tests I already removed ER from

However, it seems that some of the touch tests are still using the ER, which will result in a compilation failure when run with CI.
For instance, the `IndependenceSwingTest.java` test still fails to compile and run. There are more examples.

> I'll remove the remaining tests when I remove ER in a followup PR

Sure, thank you.

2025-08-13 01:50 UTC, alisenchung commented
I've decided to revert the migration of dragAndDrop. I think not enough tests are using it so I will replace it with mousePress + glide when I remove ExtendedRobot. I am currently fixing the remaining tests that have had ExtendedRobot removed from them.

2025-08-14 18:20 UTC, closed without merging