8344332: (bf) Migrate DirectByteBuffer to use java.lang.ref.Cleaner
openjdk/jdk pull request #22165
Opened 2024-11-15 20:54 UTC by shipilev

When working on [JDK-8343704](https://bugs.openjdk.org/browse/JDK-8343704), I noticed that DirectByteBuffers are still using old `jdk.internal.ref.Cleaner` implementation. That implementation carries a doubly-linked list, and so makes DBB suffer from the same issue fixed for `java.lang.ref.Cleaner`-s with [JDK-8343704](https://bugs.openjdk.org/browse/JDK-8343704).

I think we can migrate DBBs to use `java.lang.ref.Cleaner`.

Additional testing:
 - [ ] Linux x86_64 server fastdebug, `all`

2025-01-20 13:53 UTC, shipilev commented on src/java.base/share/classes/java/nio/Direct-X-Buffer.java.template
> +                    new Error("Cleaner terminated abnormally", x).printStackTrace();
This is verbatim from the old code in removed `Cleaner.java`. This line does not throw, it is there for printing the stack trace, I think :)

2025-01-20 16:39 UTC, shipilev commented
FTR, wider testing shows two tests that install custom system classloader fail with the following circularity:

```
TEST: runtime/cds/appcds/SpecifySysLoaderProp.java
TEST: java/security/SignedJar/SignedJarWithCustomClassLoader.java

Caused by: java.lang.IllegalStateException: getSystemClassLoader cannot be called during the system class loader instantiation
        at java.lang.ClassLoader.getSystemClassLoader(java.base@25-internal/ClassLoader.java:1849)
        at jdk.internal.misc.InnocuousThread.newThread(java.base@25-internal/InnocuousThread.java:68)
        at jdk.internal.ref.CleanerImpl$InnocuousThreadFactory.newThread(java.base@25-internal/CleanerImpl.java:208)
        at jdk.internal.ref.CleanerImpl.start(java.base@25-internal/CleanerImpl.java:110)
        at java.lang.ref.Cleaner.create(java.base@25-internal/Cleaner.java:174)
        at java.nio.DirectByteBuffer.<clinit>(java.base@25-internal/DirectByteBuffer.java:95)
        at jdk.internal.perf.Perf.createLong(java.base@25-internal/Native Method)
        at jdk.internal.perf.PerfCounter.<init>(java.base@25-internal/PerfCounter.java:63)
        at jdk.internal.perf.PerfCounter.newPerfCounter(java.base@25-internal/PerfCounter.java:69)
        at jdk.internal.perf.PerfCounter$CoreCounters.<clinit>(java.base@25-internal/PerfCounter.java:126)
        at jdk.internal.perf.PerfCounter.getZipFileOpenTime(java.base@25-internal/PerfCounter.java:176)
        at java.util.zip.ZipFile.<init>(java.base@25-internal/ZipFile.java:203)
        at java.util.zip.ZipFile.<init>(java.base@25-internal/ZipFile.java:148)
        at java.util.jar.JarFile.<init>(java.base@25-internal/JarFile.java:333)
        at jdk.internal.loader.URLClassPath$JarLoader.getJarFile(java.base@25-internal/URLClassPath.java:682)
        at jdk.internal.loader.URLClassPath$JarLoader.ensureOpen(java.base@25-internal/URLClassPath.java:653)
        at jdk.internal.loader.URLClassPath$JarLoader.<init>(java.base@25-internal/URLClassPath.java:622)
        at jdk.internal.loader.URLClassPath.getLoader(java.base@25-internal/URLClassPath.java:465)
        at jdk.internal.loader.URLClassPath.getLoader(java.base@25-internal/URLClassPath.java:409)
        at jdk.internal.loader.URLClassPath.getResource(java.base@25-internal/URLClassPath.java:331)
        at jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(java.base@25-internal/BuiltinClassLoader.java:688)
        at jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(java.base@25-internal/BuiltinClassLoader.java:620)
        at jdk.internal.loader.BuiltinClassLoader.loadClass(java.base@25-internal/BuiltinClassLoader.java:578)
        at java.lang.ClassLoader.loadClass(java.base@25-internal/ClassLoader.java:490)
        at java.lang.Class.forName0(java.base@25-internal/Native Method)
        at java.lang.Class.forName(java.base@25-internal/Class.java:543)
        at java.lang.ClassLoader.initSystemClassLoader(java.base@25-internal/ClassLoader.java:1887)
        at java.lang.System.initPhase3(java.base@25-internal/System.java:1964)
```

This can be avoided if we use the lazy holder pattern to delay `Cleaner` initialization until the actual use. Done in new commit.

2025-01-20 17:37 UTC, AlanBateman reviewed
No objection to move this to use jl.ref.Cleaner. Note that the long standing recommendation has always been to cache/reuse direct buffers rather than discard like the reproducer does. Now that the FFM API is permanent then we should redirect developers looking for deterministic release to use the new API and they can get a BB view if needed.

I assume you'll update the copyright header before this change is integrated.

2025-01-20 17:37 UTC, AlanBateman commented on src/java.base/share/classes/java/nio/Direct-X-Buffer.java.template
> +                // Old jdk.internal.ref.Cleaner behavior: when it fails, VM exits.
I'd prefer not reference a class that no longer exists, instead just say that it preserves long standing behavior exit the VM. In the case of DBB, I can't think what exceptions/errors are possible here.

2025-01-20 17:37 UTC, AlanBateman commented on src/java.base/share/classes/java/nio/Direct-X-Buffer.java.template
> +        public static Cleanable register(Object buffer, Runnable action) {
Why is this public?

2025-01-20 18:01 UTC, uschindler commented
This looks fine for me. Older Lucene versions won't break, as they use `sun.misc.Unsafe#invokeCleaner()` which behaves as before.

Code that deep reflected and made `setAccessible()` on `DirectByteBuffer#cleaner()` available was broken for long time anyways (since Java 9), so the new names and class types should not affect uptodate code.

I'd remove the `catch (Throwable)` => exit VM code completely. The called methods have no checked exceptions. If the deallocation fails for some (internal) reason it its already broken and a crush will come sooner or later anyways.

2025-01-20 18:04 UTC, uschindler approved these changes

2025-01-20 19:06 UTC, shipilev commented on src/java.base/share/classes/java/nio/Direct-X-Buffer.java.template
> +        public static Cleanable register(Object buffer, Runnable action) {
It is a public method in a private nested class. This method is used from the enclosing class, so private would be weird? I can drop public, though, let it be package-private. Done in new commit.

2025-01-20 19:07 UTC, shipilev commented on src/java.base/share/classes/java/nio/Direct-X-Buffer.java.template
> +                // Old jdk.internal.ref.Cleaner behavior: when it fails, VM exits.
Amended the comment.

2025-01-20 19:09 UTC, shipilev commented
> Note that the long standing recommendation has always been to cache/reuse direct buffers rather than discard like the reproducer does

The reproducer is likely overly simplistic. The performance problem we are solving is non-parallelism in GC when processing backing Cleaner lists.

Actually, this reminds me that I need to add direct churn/GC tests like we did for [JDK-8343704](https://bugs.openjdk.org/browse/JDK-8343704) to verify the DBB-like scenarios also improve. I pushed some benchmarks, going to see how they perform now.

2025-01-21 09:44 UTC, shipilev commented
Benchmark data on new benchmarks:

```
Benchmark                   (count)  (recipFreq)  Mode  Cnt    Score    Error  Units

# Before
DirectByteBufferChurn.test      N/A          128  avgt    9   11.852 ±  0.505  ns/op
DirectByteBufferChurn.test      N/A          256  avgt    9    9.107 ±  0.695  ns/op
DirectByteBufferChurn.test      N/A          512  avgt    9    7.643 ±  0.480  ns/op
DirectByteBufferChurn.test      N/A         1024  avgt    9    7.091 ±  0.183  ns/op
DirectByteBufferChurn.test      N/A         2048  avgt    9    6.734 ±  0.184  ns/op

DirectByteBufferGC.test       16384          N/A  avgt    9    3.122 ±  0.028  ms/op
DirectByteBufferGC.test       65536          N/A  avgt    9    6.079 ±  0.111  ms/op
DirectByteBufferGC.test      262144          N/A  avgt    9   16.892 ±  0.705  ms/op
DirectByteBufferGC.test     1048576          N/A  avgt    9  156.980 ±  9.673  ms/op
DirectByteBufferGC.test     4194304          N/A  avgt    9  725.576 ± 49.363  ms/op

# After
DirectByteBufferChurn.test      N/A          128  avgt    9    8.697 ±  0.742  ns/op ; <---
DirectByteBufferChurn.test      N/A          256  avgt    9    7.557 ±  0.353  ns/op ; <---
DirectByteBufferChurn.test      N/A          512  avgt    9    7.074 ±  0.268  ns/op ; <---
DirectByteBufferChurn.test      N/A         1024  avgt    9    6.853 ±  0.272  ns/op
DirectByteBufferChurn.test      N/A         2048  avgt    9    6.688 ±  0.298  ns/op

DirectByteBufferGC.test       16384          N/A  avgt    9    3.197 ±  0.231  ms/op
DirectByteBufferGC.test       65536          N/A  avgt    9    5.442 ±  0.323  ms/op
DirectByteBufferGC.test      262144          N/A  avgt    9   16.967 ±  0.485  ms/op 
DirectByteBufferGC.test     1048576          N/A  avgt    9   50.613 ±  2.107  ms/op ; <---
DirectByteBufferGC.test     4194304          N/A  avgt    9  343.177 ± 20.655  ms/op ; <---
```

2025-01-21 11:51 UTC, AlanBateman approved these changes
Good, I don't have any other comments.

2025-01-21 12:49 UTC, shipilev commented
Unfortunately, I am seeing intermittent OOME failures in GHA on `DirectBufferAllocTest`. I managed to reproduce some of these locally. This likely hits us hard:

> With the patched version, we now rely on normal Cleaner thread to do cleanups for us. Because of this, there is a new outpacing opportunity window where reference processing might have been over, but cleaner thread has not reacted yet.

So I think we need a feedback loop from a relevant Cleaner back to allocation code. I pushed a hopefully reliable version of it now. It survives the short `DirectBufferAllocTest` stress tests I throw at it, now running it for longer.

2025-01-21 14:31 UTC, shipilev commented
> Okay, there is much more significant change now and will require time to review very closely.

Sure. I was hoping we could avoid changing the feedback path in allocation code, but testing disagreed :)

I remember when we built that feedback path back in JDK 8 days; it is clumsy and hacky and arguably a tech debt, but it worked well on stress tests. Today, migrating DDB to standard Cleaner forces us to figure out that particular part of technical debt: the feedback path from Reference handler to DDB allocation code needs to be replaced with the feedback path from Cleaner. I think current version is less messy than what we had before. No stress test failures so far...

2025-01-22 17:14 UTC, shipilev commented
Some test code removals should disappear once we merge https://github.com/openjdk/jdk/pull/23239.

2025-01-22 17:23 UTC, AlanBateman commented on src/java.base/share/classes/java/nio/Bits.java
> +                    break;
I'm not sure that bailing out to throw OOME when interrupted is the right thing to do here. If ByteBuffer.allocateDIrect is called with the interrupt status set, or someone interrupts a thread while allocating on this slow path, then it would be surprising to have it throw OOME when it might have succeeded (with the interrupt status set).

2025-01-22 17:24 UTC, AlanBateman commented on src/java.base/share/classes/java/nio/BufferCleaner.java
> +    public static class Canary implements Runnable {
Confusing for Canary to be public, it's not accessible outside of this package.

2025-01-22 17:46 UTC, shipilev commented on src/java.base/share/classes/java/nio/Bits.java
> +                    break;
Agreed. I thought I maintained the same interrupt behavior like before, but now I see old code does not bail on interrupt, it just restores the interrupt status on both failing and passing paths. Dropped this `break` in new commit.

2025-01-22 17:46 UTC, shipilev commented on src/java.base/share/classes/java/nio/BufferCleaner.java
> +    public static class Canary implements Runnable {
Right. Can be package-private. Done in new commit.

2025-01-22 20:35 UTC, bchristi-git commented on src/java.base/share/classes/java/lang/ref/Reference.java
> -            if (processPendingActive || hasReferencePendingList()) {
It looks like `hasReferencePendingList()` is no longer used.

2025-01-22 23:44 UTC, bchristi-git commented on src/java.base/share/classes/java/nio/BufferCleaner.java
> +class BufferCleaner {
It looks like `BufferCleaner` is not meant to be instantiated. A private constructor (that throws?) would make that clear.

2025-01-23 08:48 UTC, shipilev commented on src/java.base/share/classes/java/lang/ref/Reference.java
> -            if (processPendingActive || hasReferencePendingList()) {
Right, we can clean this up right here too. Done in new commit.

2025-01-23 08:48 UTC, shipilev commented on src/java.base/share/classes/java/nio/BufferCleaner.java
> +class BufferCleaner {
Correct, added some comments too.

2025-01-23 17:23 UTC, AlanBateman approved these changes
I did another pass over the changes today, including the update that removes JVM_HasReferencePendingList. I'm happy with the changes.

2025-01-24 00:03 UTC, bchristi-git approved these changes
The reference processing and Cleaner stuff all looks fine to me.

2025-01-24 00:09 UTC, bchristi-git commented on src/java.base/share/classes/java/nio/Bits.java
> +                    System.gc();
So the Canary functions only to avoid calling `System.gc()` again if we've not yet seen progress from the previous call to `System.gc()`. Is that right?

2025-01-24 07:07 UTC, shipilev commented on src/java.base/share/classes/java/nio/Bits.java
> +                    System.gc();
Yes. There is no point in flooding the JVM with GC requests if Cleaner have not responded yet. It is, by nature, similar to the waiting for pending reference processing hack we had before.

2025-01-24 11:30 UTC, shipilev commented
Testing is still clean on my side. I would appreciate if folks can run this through their CIs.

I am planning to integrate this on Monday, as long as we discover no new issues.

2025-01-24 22:01 UTC, bchristi-git commented
> Testing is still clean on my side. I would appreciate if folks can run this through their CIs.
> 
> I am planning to integrate this on Monday, as long as we discover no new issues.

Did the change to `test/jdk/sun/security/provider/FileInputStreamPool/FileInputStreamPoolTest.java` get lost?
I'm pretty sure it was updated, but I no longer see that in the changes, and it failed in my automated test run.

2025-01-25 07:09 UTC, shipilev commented
> Did the change to `test/jdk/sun/security/provider/FileInputStreamPool/FileInputStreamPoolTest.java` get lost? I'm pretty sure it was updated, but I no longer see that in the changes, and it failed in my automated test run.

It was a test bug, I fixed it separately: [JDK-8348301](https://bugs.openjdk.org/browse/JDK-8348301). I merged current master to this PR branch now, so it should work well.

2025-01-26 07:30 UTC, AlanBateman commented
> Testing is still clean on my side. I would appreciate if folks can run this through their CIs.
> 
> I am planning to integrate this on Monday, as long as we discover no new issues.

I ran it through our CI and we seem to have a few tests that aren't in the jdk repo but have a dependency on jdk.internal.ref.Cleaner so they will need to be fixed and/or excluded. Would you mind holding off until Tuesday to give time to get that done? Otherwise I didn't see any issues. I see there is a referenced Graal issue as it looks like they have to do an update to align with the changes here.

2025-01-27 09:08 UTC, shipilev commented
> Would you mind holding off until Tuesday to give time to get that done?

Sure, there is no rush with this PR. I'll wait.

2025-01-29 10:58 UTC, shipilev commented
> > Would you mind holding off until Tuesday to give time to get that done?
> 
> Sure, there is no rush with this PR. I'll wait.

How is it going, @AlanBateman? Any progress on closed tests?

2025-01-29 17:16 UTC, bchristi-git commented
> > > Would you mind holding off until Tuesday to give time to get that done?
> > 
> > 
> > Sure, there is no rush with this PR. I'll wait.
> 
> How is it going, @AlanBateman? Any progress on closed tests?

Nearly done - in review now.

2025-01-29 19:28 UTC, kimbarrett commented on src/java.base/share/classes/java/lang/ref/Reference.java
> -    private static boolean waitForReferenceProcessing()
Removing waitForReferenceProcessing is contrary to 
https://bugs.openjdk.org/browse/JDK-8305186
Reference.waitForReferenceProcessing should be more accessible
I've pointed to JDK-8305186 in a number of discussions about problems encountered with various tests.
So I'm doubtful about removing it.

2025-01-29 19:42 UTC, shipilev commented on src/java.base/share/classes/java/lang/ref/Reference.java
> -    private static boolean waitForReferenceProcessing()
No problem, I will revert those removals. I did the removals proactively, thinking none of this infrastructure is needed after we migrate DBB, but since there are apparently plausible use cases for it, I'll leave it in.

2025-01-29 19:51 UTC, shipilev commented on src/java.base/share/classes/java/lang/ref/Reference.java
> -    private static boolean waitForReferenceProcessing()
Done in new commit, thanks for taking a look.

2025-01-29 23:08 UTC, bchristi-git approved these changes
Thanks for restoring `waitForReferenceProcessing()`.
Closed test changes are in, so you should be good to go.

2025-01-29 23:52 UTC, kimbarrett commented on src/java.base/share/classes/java/nio/Bits.java
> +                if (canary == null || canary.isDead()) {
If we're keeping Reference.waitForPendingReferences, why not continue to use it, rather than introducing
the canary as a new, ad hoc, reference processing progress detector?

2025-01-30 06:58 UTC, shipilev commented on src/java.base/share/classes/java/nio/Bits.java
> +                if (canary == null || canary.isDead()) {
Because it is no longer about reference processing _only_, we _also_ need to check if `Cleaner` acted after reference processing was complete. The earlier version of the patch was using old `Reference.waitForPendingReferences` without success.

2025-01-30 08:35 UTC, AlanBateman commented
> How is it going, @AlanBateman? Any progress on closed tests?

Thanks for giving us time to get this sorted out.

2025-01-30 08:36 UTC, AlanBateman commented on src/java.base/share/classes/java/nio/Bits.java
> +                if (canary == null || canary.isDead()) {
@kimbarrett Do you have a change coming to allow waitForPendingReferences be used by WB? I assume this will at least add a comment to the method (or whatever it changes to) to make it clear that it's for testing.

2025-01-30 08:37 UTC, AlanBateman approved these changes

2025-01-30 16:25 UTC, kimbarrett commented on src/java.base/share/classes/java/nio/Bits.java
> +                if (canary == null || canary.isDead()) {
@AlanBateman I've not done any work on JDK-8305186.  There has also been discussion about making
that function non-private or even public (though with concerns about specification difficulty) for use in
places like this.

@shipilev I'm working on a reply, but it might be long-ish.  That outpacing issue for some tests is why this
code wasn't switched away from jdk.internal.ref.Cleaner a long time ago.  I'm still looking at it, but I currently
don't think the canary provides a reliable solution to that.

2025-01-30 16:54 UTC, AlanBateman commented on src/java.base/share/classes/java/nio/Bits.java
> +                if (canary == null || canary.isDead()) {
> @AlanBateman I've not done any work on JDK-8305186. There has also been discussion about making that function non-private or even public (though with concerns about specification difficulty) for use in places like this.

Exposing this in this API might be scary, I think would need a lot of thinking to be confident it doesn't create an attractive nuisance. Keeping it for WB testing is okay of course.

2025-01-30 17:04 UTC, shipilev commented on src/java.base/share/classes/java/nio/Bits.java
> +                if (canary == null || canary.isDead()) {
The asynchronicity of buffer cleanup would IMO always be a headache, so we would need some sort of feedback loop. Cleaner canary is not a perfect vehicle for this, since it does not tell us directly that any buffer cleanup happened, like it used to be with reference handling thread invoking `jdk.internal.ref.Cleaner` directly. We could reinstate the similarly-shaped hack by tracking if buffer-attached cleaners have fired.

That said, I have been in the room when this hack was introduced, we recognized it was not perfect, and I remember we were happy this kind of feedback still worked in practice, seeing no failures on `DirectBufferAllocTest` stress tests. So when introducing the canaries, I planned to arrive to the same happy point: stress`DirectBufferAllocTest` works in all practical configurations.

There could probably be cases where we would throw OOME, when we could have waited a bit more or do a bit more cleanups. But then again, this would not be a correctness issue, but rather a performance pothole, which is, again, does not show up on stress tests, so the probability of it seems fairly low.

So while we are discussing this, I think we should really keep an eye on practical cost-benefit balance here.

2025-02-10 09:28 UTC, shipilev commented on src/java.base/share/classes/java/nio/Bits.java
> +                if (canary == null || canary.isDead()) {
I would like to integrate this PR. How are you doing, @kimbarrett? Have you found any major holes in it?

2025-02-14 06:26 UTC, kimbarrett commented on src/java.base/share/classes/java/nio/Bits.java
> +                if (canary == null || canary.isDead()) {
@shipilev I've been having computer issues.  I'm back to looking at this.

2025-02-18 11:01 UTC, kimbarrett requested changes
There are several changes here that I think are of interest.

(1) Put the cleanables for DirectByteBuffer in a separate j.l.r.Cleaner.  I
don't think that was done in previous experiments with eliminating the use of
j.i.r.Cleaner.  That seems like a good thing to do, to avoid interleaving the
processing of these short and potentially more performance-critical cleanables
with others.

(2) Do a GC for each iteraton of the slow path (i.e. after each exponentially
increasing sleep period).  Neither the existing code (which I had a hand in)
nor its predecessor did that.  I'm currently doubtful of this being a good
idea.  The exponential backoff in the current code was just retained from the
prior code, and I think doesn't actually do much other than delay OOME to
allow other threads to happen to close any direct buffers they might be using.
In the current code (using j.i.r.Cleaner), once waitForReference returns false
all Cleaners discovered by a prior GC will have been processed.  I wonder,
with the current code, under what circumstances do we actually get into those
sleeps, but don't ultimately OOME?

To provide something similar with j.l.r.Cleaner would require an operation
on that class similar to waitForReferenceProcessing.  If there is pending
cleanup work then wait for some and then return true.  If there isn't any
pending cleanup work then return false.  I've spent some time thinking about
how this could be done, and think it's feasible (working on a prototype that
seems like it should work, but hasn't been tested at all yet), though not as
simple as one might wish.

(3) Put the slow path under a lock.  That seems clearly essential with the
change to iterate GCs.  It might be that it's a mistake in the old code to not
do something similar.  The current code allows essentially back to back to
back GCs as multiple threads hit the slow path more or less simultaneously.
You could have several threads come in and all waitForReferenceProcessing, all
finish that loop at the same time and gang-request GCs.  That doesn't seem
good.

(4) Add the canary mechanism.  I think this is a poor replacement for what
waitForReferenceProcessing does currently, since it is not even remotely
reliable.  It might make the path to OOME less likely, but bad luck could make
it do nothing useful at all.

2025-02-18 11:53 UTC, shipilev commented on src/java.base/share/classes/java/nio/Bits.java
> +        synchronized (Bits.class) {
This class is package-private, so I judged the possibility of leaking the lock impractically low. We can do a separate lock, if that reads cleaner, sure. Done in new commit.

2025-02-18 11:53 UTC, shipilev commented on src/java.base/share/classes/java/nio/Bits.java
> +                    Thread.sleep(sleepTime);
Right, that's an overlook. I wanted to make the first non-sleep-ed attempt in the loop, so that it covers the semi-optimistic case where we could have reserved the memory immediately after taking the lock. But we can peel that out from the loop. Done in new commit.

2025-02-18 14:29 UTC, shipilev commented
Thanks for the comment, @kimbarrett!

I started replying, but then figured my reply on current canary mechanics would be better captured in the code comment, so I pushed it right there. Then I ran out of time. I would think about this a bit more and try to reply to the your comments sometime later this week.

So far, I still believe Cleaner canaries are the best way to balance the probability of success for the best effort attempt to allocate when short on memory and the implementation simplicity. Maybe filling the only theoretical gap I see at the moment (see code comments) would be marginally better with waiting for `Cleaner` directly, maybe not. Maybe waiting approaches strike a better balance, maybe not.

What I am sure, though, is that lots of theoretical arguments I made to myself, including re-using waiting infrastructure, failed empirical reliability/performance tests after my attempts at implementing them. Admittedly, I have not tried to go as far as coordinating _both_ reference processing and Cleaner threads, maybe, _maybe_ the answer is there. So I would reserve final judgement on whether GC+RefProc+Cleaner waiting approaches really work until I see them actually work :) In contrast, current PR both fits my theoretical understanding why it works, and passes the empirical tests. Looking forward to your attempt!

2025-02-23 10:20 UTC, kimbarrett requested changes
I've made a prototype that adds Cleaner.waitForCleaning() and changes
Bits.reserveMemory() to use it.

https://github.com/openjdk/jdk/compare/master...kimbarrett:openjdk-jdk:wait-for-cleaning?expand=1

It's based on the shipilev commits 1-19, for ease of comparison and
prototyping. There are also some shortcuts (like making some things public
that likely shouldn't be), again for ease of prototyping.

I ran the DirectBufferAllocTest test a few hundred times without any
problems.  I also ran it directly, configured with a 1/2 hour runtime, again
without problems.  I ran the two new micros against baseline, the shipilev
changes only, and the waitForCleaning changes.  Results below.

DirectByteBufferGC
------------------
baseline
Benchmark                (count)  Mode  Cnt    Score    Error  Units
DirectByteBufferGC.test    16384  avgt    9    4.036 ±  0.244  ms/op
DirectByteBufferGC.test    65536  avgt    9    7.117 ±  0.184  ms/op
DirectByteBufferGC.test   262144  avgt    9   18.482 ±  1.064  ms/op
DirectByteBufferGC.test  1048576  avgt    9  194.590 ± 17.639  ms/op
DirectByteBufferGC.test  4194304  avgt    9  802.354 ± 57.576  ms/op

shipilev
Benchmark                (count)  Mode  Cnt    Score    Error  Units
DirectByteBufferGC.test    16384  avgt    9    4.104 ±  0.045  ms/op
DirectByteBufferGC.test    65536  avgt    9    6.875 ±  0.244  ms/op
DirectByteBufferGC.test   262144  avgt    9   17.943 ±  0.446  ms/op
DirectByteBufferGC.test  1048576  avgt    9   59.002 ±  3.616  ms/op
DirectByteBufferGC.test  4194304  avgt    9  331.328 ± 36.580  ms/op

waitForCleaning
Benchmark                (count)  Mode  Cnt    Score    Error  Units
DirectByteBufferGC.test    16384  avgt    9    4.058 ±  0.167  ms/op
DirectByteBufferGC.test    65536  avgt    9    6.775 ±  0.281  ms/op
DirectByteBufferGC.test   262144  avgt    9   17.724 ±  0.602  ms/op
DirectByteBufferGC.test  1048576  avgt    9   57.284 ±  2.679  ms/op
DirectByteBufferGC.test  4194304  avgt    9  330.002 ± 44.200  ms/op

DirectByteBufferChurn
---------------------
baseline
Benchmark                   (recipFreq)  Mode  Cnt   Score   Error  Units
DirectByteBufferChurn.test          128  avgt    9  15.693 ± 0.991  ns/op
DirectByteBufferChurn.test          256  avgt    9  11.255 ± 0.369  ns/op
DirectByteBufferChurn.test          512  avgt    9   9.422 ± 0.382  ns/op
DirectByteBufferChurn.test         1024  avgt    9   8.529 ± 0.311  ns/op
DirectByteBufferChurn.test         2048  avgt    9   7.833 ± 0.287  ns/op

shipilev
Benchmark                   (recipFreq)  Mode  Cnt   Score   Error  Units
DirectByteBufferChurn.test          128  avgt    9  12.524 ± 0.476  ns/op
DirectByteBufferChurn.test          256  avgt    9   9.248 ± 0.175  ns/op
DirectByteBufferChurn.test          512  avgt    9   8.583 ± 0.197  ns/op
DirectByteBufferChurn.test         1024  avgt    9   8.227 ± 0.274  ns/op
DirectByteBufferChurn.test         2048  avgt    9   7.526 ± 0.394  ns/op

waitForCleaning
Benchmark                   (recipFreq)  Mode  Cnt   Score   Error  Units
DirectByteBufferChurn.test          128  avgt    9  11.235 ± 1.998  ns/op
DirectByteBufferChurn.test          256  avgt    9   9.129 ± 0.324  ns/op
DirectByteBufferChurn.test          512  avgt    9   8.446 ± 0.115  ns/op
DirectByteBufferChurn.test         1024  avgt    9   7.786 ± 0.425  ns/op
DirectByteBufferChurn.test         2048  avgt    9   7.477 ± 0.150  ns/op

The baseline DirectByteBufferGC suffers significantly at higher counts,
probably because of the long doubly-linked list of registered
jdk.internal.ref.Cleaner objects.

By eye the performance of both shipilev and waitForCleaning on the DBBChurn
benchmark seem to be consistently slightly better than baseline, and within
the noise of each other for both benchmarks.

This waitForCleaning approach raises several questions.

(1) Is the improved reliability of this approach worth the additional effort?
My inclination is to say yes.  But note that it should perhaps be different
effort - see item (2).

(2) Should Cleaner be responsible for providing the additional functionality?
An alternative is to have Bits implement it's own cleaning, directly using a
private PhantomReference derivative, ReferenceQueue, and Thread.

If there were multiple (potential) clients for this sort of thing then putting
it in Cleaner may makes sense, so long as their requirements are similar.  But
we're kind of fighting with it, esp. with the canary approach, but even with
the waitForCleaning approach.  I think things could be simpler and easier to
understand with a direct implementation.  And Cleaner was not intended to be
the last word in the area of reference-based cleanup.  Rather, it's a
convenient package for addressing some common patterns (esp. with
finalization).  It provides some useful infrastructure that would need to be
replaced in a bespoke implementation, but I don't think there's anything all
that large or complicated there, and some streamlining is possible.

Note that I haven't done any work in that direction yet.

(3) Do we need the retry stuff, and how should it be done?  I did some
monitoring of the retries, and waitForCleaning DBBA does need the retries
(though rarely more than 1, and I never saw more than 2).  I kind of feel like
the retries are a kludgy workaround for what seems like an unreasonable test,
but oh well.

The point of the retries is to allow other threads to drop some DBBs that can
become reclaimable during the associated wait, giving the waiting thread an
opportunity to make use of that now available memory.

I experimented with a retry-style more similar to the current code, where each
thread on the slow path will do at most one GC and then go into a wait/sleep
loop if reservation continues to fail.  (I added some locking to avoid the
concurrent requests for GC issue with the current code.) That didn't seem to
make any difference compared to something like the proposed serialized GC and
sleep loop.  I can construct theoretical cases that seem to favor either, but
the style in the proposal seems simpler.

Of course, the question of when to do GCs and how many to do is moot if
-XX:+DisableExplicitGC is used.  (The default for that option is false.)

2025-02-24 06:10 UTC, kimbarrett commented
> (2) Should Cleaner be responsible for providing the additional functionality?
> [...]
> If there were multiple (potential) clients for this sort of thing then putting
> it in Cleaner may makes sense [...]

And here is a bug and recently opened PR that would benefit from having
Cleaner.waitForCleaning.
https://bugs.openjdk.org/browse/JDK-8204868
java/util/zip/ZipFile/TestCleaner.java still fails with "cleaner failed to clean zipfile."
https://github.com/openjdk/jdk/pull/23742

2025-02-24 09:30 UTC, kimbarrett commented
> If you are suggesting exposing this as a public API then I don't think we should do this,

Not at this time, quite possibly never.  As mentioned, I made some things public for ease of prototyping.
I even commented it as such.

> I actually think it's time to consider deprecating Cleaner but that is a bigger discussion.

Which "Cleaner" are you referring to?  If jdk.internal.ref.Cleaner, this PR proposes to remove it.
If java.lang.ref.Cleaner, then why?

2025-03-04 23:13 UTC, bchristi-git commented
> I've made a prototype that adds Cleaner.waitForCleaning() and changes Bits.reserveMemory() to use it.
> 
> https://github.com/openjdk/jdk/compare/master...kimbarrett:openjdk-jdk:wait-for-cleaning?expand=1

These caught my eye during my read-through:

- The main `CleanerImpl.run()` loop is changed to call `queue.poll()` in place of (blocking) `queue.remove(timeout)`. Could this make this a busier wait loop? 
- My impression is that it does more locking.

I wonder how these together could affect performance of less specialized Cleaner usage cases (where objects are not being enqueued very often).

I'm therefore inclined for changes along these lines to be limited to a DirectByteBuffer-specific mechanism, as you suggested in your point (2).

2025-04-30 06:12 UTC, shipilev commented
/reopen

2025-05-01 19:34 UTC, kimbarrett commented
FYI, I've been working on some more ideas here.  I hope to have more to report in the next couple of days.

2025-05-23 09:07 UTC, shipilev commented
Closing in favor of https://git.openjdk.org/jdk/pull/25289.

2025-05-23 09:07 UTC, closed without merging