8344199: Problemlist jdk/jfr/jvm/TestVirtualThreadExclusion.java before JDK-8344199 resolved
openjdk/jdk pull request #22178
Opened 2024-11-17 02:03 UTC by sendaoYan

Hi all,
The test `jdk/jfr/jvm/TestVirtualThreadExclusion.java` fails after [JDK-8338383](https://bugs.openjdk.org/browse/JDK-8338383),  before [JDK-8344199](https://bugs.openjdk.org/browse/JDK-8344199) been resolved, should we problemlist this test to make less CI noisy.

2024-11-17 02:23 UTC, sendaoYan commented
/label add hotspot-jfr

2024-11-17 03:04 UTC, lmesnik approved these changes
Looks good and trivial.

2024-11-17 03:06 UTC, lmesnik requested changes
Please update bugid to JDK-8344349

2024-11-17 03:21 UTC, sendaoYan commented
/issue JDK-8344349

2024-11-17 03:22 UTC, sendaoYan commented
Oops, the bugid has been up updated.

2024-11-17 03:59 UTC, lmesnik approved these changes

2024-11-17 14:46 UTC, sendaoYan commented
Thanks for the review.

2024-11-18 02:34 UTC, sendaoYan commented
/integrate

2024-11-18 02:35 UTC, closed without merging