8343893
openjdk/jdk pull request #22204
Opened 2024-11-18 11:44 UTC by jdksjolen

# Background

With the implementation of [JDK-8312132](https://bugs.openjdk.org/browse/JDK-8312132) we added the `MemoryFileTracker` (MFT). Unfortunately, this work failed to implement JFR integration. This, in turn, meant that (generational) ZGC has not correctly reported its heap usage via the NMT JFR events. We (as in Oracle) never saw this issue in testing, as we didn't run this test for all possible GC configurations. With an update of our test configurations this is no longer the case: We run this test for all possible GCs and the test now fails for generational ZGC.

# The fix

I implemented JFR events for the MFT by adding all of its reserved and committed memory into the JFR data, similarly to the `VirtualMemoryTracker`. I also added an explicit `run` using `ZGC` to the failing test, to ensure that any actual regressions are found.

2024-11-18 12:32 UTC, jdksjolen commented
/label hotspot-runtime

2024-11-18 16:15 UTC, lmesnik requested changes

2024-11-18 16:44 UTC, jdksjolen commented on test/jdk/jdk/jfr/event/runtime/TestNativeMemoryUsageEvents.java
> + * @run main/othervm -XX:+UseZGC -XX:NativeMemoryTracking=summary -Xms16m -Xmx128m -XX:-UseLargePages -Xlog:gc jdk.jfr.event.runtime.TestNativeMemoryUsageEvents true
> But if you want to add separate run, please add it as a separate testcase and requires vm.gc.G1.

Sorry Leonid, could you help me out with writing this? I'm not very good at JTReg yet :).

2024-11-18 16:58 UTC, jdksjolen commented
Leonid convinced me that it's unnecessary to have the ZGC case for the test, so I removed it.

2024-11-18 16:58 UTC, lmesnik approved these changes

2024-11-19 16:45 UTC, gerard-ziemski reviewed
Just and observation - you used here the acronym MFT and it just jumped out at me, then I looked at memoryFileTracker and it feels inconsistent to me.

Did we ever consider naming it nativeMemoryFileTracker? Then we would have NMFT, which extends NMT better, IMHO.

Just something to keep in mind if we ever feel like cleaning up the names in NMT area.

2024-11-19 16:48 UTC, gerard-ziemski commented on src/hotspot/share/nmt/nmtUsage.cpp
> +  }
Ah, we actually do use VirtualMemory here to track the memory. Never mind!

2024-11-19 16:48 UTC, gerard-ziemski approved these changes
LGTM

2024-11-20 08:39 UTC, jdksjolen commented on src/hotspot/share/nmt/nmtUsage.cpp
> +  }
Yeah, but it is actually 0 :). I wanted to future proof this code, if we ever do use `reserved` here. I'll assert that `reserved` is 0 with a good message, then we can fix the code if our assumptions change.

2024-11-21 10:27 UTC, jdksjolen commented on src/hotspot/share/nmt/nmtUsage.cpp
> +  }
Sorry, I was pretty confused here. We need to remove the reserved additions, otherwise we double-account reserved memory.

2024-11-21 15:29 UTC, gerard-ziemski approved these changes
That matches the comments from `src/hotspot/share/nmt/memoryFileTracker.hpp`

I've seen the issue of overcounting pop-up couple of times recently - can we write a test that checks and would have caught the issue we ran into just here?

2024-11-22 08:55 UTC, jdksjolen commented
Cheers Gerard. I'm not entirely sure of how to write a test for catching this, if you have any ideas that'd be great.

/integrate

2024-11-22 08:55 UTC, closed without merging