JDK-8260335: [macos] Running app using relative path causes problems
openjdk/jdk pull request #2260
Opened 2021-01-27 12:43 UTC by andyherrick

Fixing FileUtils.dirname() to skip over "/.".

2021-01-27 12:46 UTC, andyherrick commented
/core-libs

2021-01-28 13:58 UTC, andyherrick commented
/label core-libs

2021-01-29 01:03 UTC, sashamatveev approved these changes

2021-02-02 17:10 UTC, alexeysemenyukoracle requested changes

2021-02-02 17:10 UTC, alexeysemenyukoracle commented on src/jdk.jpackage/share/native/common/FileUtils.cpp
> +    if (tstrings::endsWith(path, _T("/."))) {
I'd add `|| tstrings::endsWith(path, _T("\\."))` to cover similar case for Windows paths

2021-02-02 17:35 UTC, azuev-java approved these changes
Aside of small change requested by @alexeysemenyukoracle looks fine.

2021-02-04 14:50 UTC, andyherrick commented
/integrate

2021-02-04 14:51 UTC, closed without merging