8337016: serviceability/jvmti/RedefineClasses/RedefineLeakThrowable.java gets Metaspace OOM
openjdk/jdk pull request #22746
Opened 2024-12-13 22:25 UTC by coleenp

This increases MaxMetaspaceSize for this test so that it can be run with CDS turned off.  This change is upstreamed from the valhalla repo from when it didn't have CDS on.  The test still finds a metaspace leak with this larger MaxMetaspaceSize.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8337016](https://bugs.openjdk.org/browse/JDK-8337016): serviceability/jvmti/RedefineClasses/RedefineLeakThrowable.java gets Metaspace OOM (**Enhancement** - P4)

### Reviewers
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Serguei Spitsyn](https://openjdk.org/census#sspitsyn) (@sspitsyn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/22746/head:pull/22746` \
`$ git checkout pull/22746`

Update a local copy of the PR: \
`$ git checkout pull/22746` \
`$ git pull https://git.openjdk.org/jdk.git pull/22746/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 22746`

View PR using the GUI difftool: \
`$ git pr show -t 22746`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/22746.diff">https://git.openjdk.org/jdk/pull/22746.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/22746#issuecomment-2542484921)
</details>

2024-12-15 21:40 UTC, dholmes-ora requested changes

2024-12-15 21:40 UTC, dholmes-ora commented on test/hotspot/jtreg/serviceability/jvmti/RedefineClasses/RedefineLeakThrowable.java
> +// MaxMetaspaceSize=23m allows InMemoryJavaCompiler to load even if CDS is off.
```suggestion
// MaxMetaspaceSize=25m allows InMemoryJavaCompiler to load even if CDS is off.
```

2024-12-16 20:49 UTC, sspitsyn approved these changes
Looks good.

2024-12-17 01:55 UTC, dholmes-ora approved these changes

2024-12-17 12:58 UTC, coleenp commented
Thank you for reviewing, David and Serguei.
/integrate

2024-12-17 13:00 UTC, closed without merging