8345766: C2 does not remove useless drem runtime calls
openjdk/jdk pull request #22786
Opened 2024-12-17 09:01 UTC by theoweidmannoracle

C2 currently emits runtime calls if the platform rules do not support lowering floating point remainder operations. For example, for float:

https://github.com/openjdk/jdk/blob/fbbc7c35f422294090b8c7a02a19ab2fb67c7070/src/hotspot/share/opto/parse2.cpp#L2305-L2318

https://github.com/openjdk/jdk/blob/fbbc7c35f422294090b8c7a02a19ab2fb67c7070/src/hotspot/share/opto/parse2.cpp#L1099-L1109

The only platform, which currently supports this, however, is x86_32. On all other platforms, runtime calls are generated directly during parsing, which prevent any constant folding or other idealizations.

To fix this, this PR turns ModFNode and ModDNode into macros, which are always created during parsing. They support idealization (constant folding) and are lowered to runtime calls during macro expansion. For simplicity, these operations will now also call into the runtime on x86_32, as this platform is deprecated.

2025-01-07 18:21 UTC, vnkozlov commented on src/hotspot/share/opto/macro.cpp
> +        call->copy_call_debug_info(&_igvn, call);
This is used only for `CallJavaNode`.

2025-01-08 08:23 UTC, eme64 requested changes
Thanks for working on this! Generally looks reasonable to me, though I left a few comments.

2025-01-08 08:23 UTC, eme64 commented on src/hotspot/share/opto/divnode.cpp
> +//------------------------------Idealize---------------------------------------
I would just remove these lines if you are already toughing the code here:
`//------------------------------Idealize---------------------------------------`

2025-01-08 08:23 UTC, eme64 commented on src/hotspot/share/opto/divnode.cpp
> +Node *UModLNode::Ideal(PhaseGVN *phase, bool can_reshape) {
```suggestion
Node* UModLNode::Ideal(PhaseGVN* phase, bool can_reshape) {
```
Ah, maybe you did not mean to touch it, but on GitHub it looks like you did... Maybe you just reordered things.

2025-01-08 08:23 UTC, eme64 commented on src/hotspot/share/opto/divnode.cpp
> +Node *UModLNode::Ideal(PhaseGVN *phase, bool can_reshape) {
Makes it a little trickier to review though.

2025-01-08 08:23 UTC, eme64 commented on src/hotspot/share/opto/divnode.cpp
> +  }
The comment seems to contradict the result. You could return `C->top()`, right?

2025-01-08 08:23 UTC, eme64 commented on src/hotspot/share/opto/divnode.cpp
> +Node* ModFNode::Ideal(PhaseGVN* phase, bool can_reshape) {
Can you quickly say why you congerted this from a `Value` to an `Ideal` method? I guess it is because before it used to be a simple `Node` with a single output, but now it is a `Call` with multiple outputs... Ok makes sense.

2025-01-08 08:23 UTC, eme64 commented on src/hotspot/share/opto/macro.cpp
> +  CallNode *call = make_slow_call(lock, OptoRuntime::complete_monitor_enter_Type(),
```suggestion
  CallNode* call = make_slow_call(lock, OptoRuntime::complete_monitor_enter_Type(),
```

2025-01-08 08:23 UTC, eme64 commented on src/hotspot/share/opto/macro.cpp
> +                                          is_drem ? CAST_FROM_FN_PTR(address, SharedRuntime::drem) : CAST_FROM_FN_PTR(address, SharedRuntime::frem),
```suggestion
                                          is_drem ? CAST_FROM_FN_PTR(address, SharedRuntime::drem)
                                                  : CAST_FROM_FN_PTR(address, SharedRuntime::frem),
```
The line is a little long.

2025-01-08 08:23 UTC, eme64 commented on src/hotspot/share/opto/parse.hpp
> +  Node* floating_point_mod(Node* a, Node* b, bool dbl);
Please use a more descriptive name than `dbl` ;)

2025-01-08 08:23 UTC, eme64 commented on src/hotspot/share/opto/parse2.cpp
> +  CallNode* mod = dbl ? static_cast<CallNode*>(new ModDNode(C, a, b)) : new ModFNode(C, a, b);
He has a call from `Bytecodes::_frem:` and from `Bytecodes::_drem:`.

Why not make it a `BasicType bt` instead of `dbl`, and then switch on that? Might be more readable than true / false.
I read `floating_point_mod(a, b, true)`, and am not sure what the `true` does.

2025-01-08 08:23 UTC, eme64 commented on src/hotspot/share/opto/parse2.cpp
> +  CallNode* mod = dbl ? static_cast<CallNode*>(new ModDNode(C, a, b)) : new ModFNode(C, a, b);
Why do you need the `static_cast<CallNode*>`? I mean why not use the common type `ModFloatingNode*`, which is a subtype of `CallNode*`, right?

2025-01-09 09:59 UTC, theoweidmannoracle commented on src/hotspot/share/opto/parse2.cpp
> +  CallNode* mod = dbl ? static_cast<CallNode*>(new ModDNode(C, a, b)) : new ModFNode(C, a, b);
> Why you need the case for ModDNode?

As @eme64 already explained this function is both for float and double. "floating point" here is supposed to mean both float and double. 

> Why not make it a BasicType bt instead of dbl, and then switch on that? Might be more readable than true / false.
I read floating_point_mod(a, b, true), and am not sure what the true does.

Good point. I will change it.

> Why do you need the static_cast<CallNode*>? I mean why not use the common type ModFloatingNode*, which is a subtype of CallNode*, right?

The cast is necessary because of the ternary operator but you are right that ModFloatingNode could be used as a more concrete subtype here. I will change it.

2025-01-09 10:02 UTC, theoweidmannoracle commented on src/hotspot/share/opto/parse2.cpp
> +  CallNode* mod = dbl ? static_cast<CallNode*>(new ModDNode(C, a, b)) : new ModFNode(C, a, b);
Actually the assignment further down from `as_Call` fails, so I'll leave it with CallNode.

2025-01-09 11:09 UTC, theoweidmannoracle commented on src/hotspot/share/opto/divnode.cpp
> +}
Yes, I wanted to avoid importing the runtime header (OptoRuntime) into the divnode header.

2025-01-09 11:43 UTC, theoweidmannoracle commented on src/hotspot/share/opto/divnode.cpp
> +Node *UModLNode::Ideal(PhaseGVN *phase, bool can_reshape) {
Yes, I think I just re-ordered this without realizing.

2025-01-09 14:36 UTC, theoweidmannoracle commented
@vnkozlov @eme64 Thank you for your reviews. I think I addressed your comments and will run testing again.

2025-01-09 16:57 UTC, vnkozlov commented on src/hotspot/share/opto/parse2.cpp
> +  CallNode* mod = dbl ? static_cast<CallNode*>(new ModDNode(C, a, b)) : new ModFNode(C, a, b);
I have typo in my original question. What I meant to ask is: why you have cast only for ModDNode and not for ModFNode?

2025-01-10 08:03 UTC, theoweidmannoracle commented on src/hotspot/share/opto/parse2.cpp
> +  CallNode* mod = dbl ? static_cast<CallNode*>(new ModDNode(C, a, b)) : new ModFNode(C, a, b);
The cast is there to make the C++ type checker happy. It's fine if the right hand side of the : is a subtype of the left hand side (like my code above with the cast) but the compiler cannot automatically deduce a super type of the lhs and rhs as the type for the lhs and res (which would be required if I remove the cast). I could, of course, add a cast to the rhs too, but it's not necessary, so I left it off.

2025-01-10 22:13 UTC, vnkozlov approved these changes
Good.

2025-01-11 02:29 UTC, merykitty commented
Sorry for being late here. What do you think about using a general-purpose `CallPureNode` that represents a call not reading or writing external modifiable states? Apart from `ModF` and `ModD`, there are several other nodes that may benefit from this such as the trigonometric functions, svml calls, etc. A `CallPureNode` does not have input and output control or memory, which makes it more susceptible to GVN and deadcode elimination, as well as allowing it to be more freely scheduled.

2025-01-16 12:54 UTC, eme64 approved these changes
Looks good! Not sure if copyright year should be updated to 2025 though.

2025-01-16 17:41 UTC, vnkozlov commented
> Looks good! Not sure if copyright year should be updated to 2025 though.

I think it should 2025 - the year changes will be integrated.

2025-01-17 08:11 UTC, theoweidmannoracle commented
@eme64 @vnkozlov I updated the copyright years to 2025. (For the new tests I used "2024, 2025" as I discussed with Tobias yesterday. He said since these files were already available here in 2024, it's fine to keep it.)

2025-01-17 08:25 UTC, eme64 requested changes

2025-01-17 08:25 UTC, eme64 commented on test/hotspot/jtreg/compiler/c2/irTests/ModDNodeTests.java
> + * @bug 8332268
You should probably add the bug id of this issue.
```suggestion
 * @bug 8332268 8345766
```

2025-01-17 08:25 UTC, eme64 commented on test/hotspot/jtreg/compiler/c2/irTests/ModFNodeTests.java
> + * @bug 8332268
```suggestion
 * @bug 8332268 8345766
```

2025-01-17 08:32 UTC, theoweidmannoracle commented on test/hotspot/jtreg/compiler/c2/irTests/ModDNodeTests.java
> + * @bug 8332268
I updated the jtreg comments. (Seems I copied this from another test and never updated it.)

2025-01-17 16:44 UTC, vnkozlov approved these changes
Good.

2025-01-20 06:55 UTC, eme64 approved these changes
Thanks for all the updates @theoweidmannoracle ! Nice work :)

2025-01-21 09:14 UTC, eme64 commented
/sponsor

2025-01-21 09:15 UTC, closed without merging