8260577: Unused code in AbstractCompiler after Shark compiler removal
openjdk/jdk pull request #2281
Opened 2021-01-28 09:41 UTC by TobiHartmann

After removal of the Shark compiler with [JDK-8171853](https://bugs.openjdk.java.net/browse/JDK-8171853) in JDK 10, some methods in AbstractCompiler are unused.

Thanks,
Tobias

2021-01-28 09:51 UTC, shipilev approved these changes
Looks fine. I do wonder if `CICompileOSR` and `CICompileNatives` were also for Shark, and maybe the flags and their relevant blocks could be eliminated as well.

2021-01-28 10:06 UTC, TobiHartmann commented
Thanks for looking at this Aleksey.

> Looks fine. I do wonder if CICompileOSR and CICompileNatives were also for Shark, and maybe the flags and their relevant blocks could be eliminated as well.

Good point, I think these can go as well. I'll update the PR.

2021-01-28 10:19 UTC, shipilev approved these changes
This looks fine, thanks.

2021-01-28 10:33 UTC, chhagedorn approved these changes
Looks good!

2021-01-28 10:39 UTC, TobiHartmann commented
Thanks for the reviews, Aleksey and Christian.

2021-01-28 16:44 UTC, vnkozlov requested changes
Both flags are not related to Shark. I use `CICompileOSR=false` very frequently during debugging to avoid C2 OSR compilations:
http://hg.openjdk.java.net/jdk7u/jdk7u/hotspot/file/062bd42c5e2b/src/share/vm/runtime/globals.hpp#l2403

Revert CICompileOSR back to platform independent and keep both flags.
I agree with removal of functions which always return `true`.

2021-01-29 07:25 UTC, TobiHartmann commented
> I use CICompileOSR=false very frequently during debugging to avoid C2 OSR compilations
Okay but it also disables C1 OSR compilations, right? I've never used that flag and thought it's semantically equivalent to `UseOnStackReplacement`. I'll revert the latest changes then.

2021-01-29 19:28 UTC, vnkozlov approved these changes
Looks good.

2021-02-01 06:32 UTC, TobiHartmann commented
Thanks Vladimir!

2021-02-01 06:32 UTC, TobiHartmann commented
/integrate

2021-02-01 06:33 UTC, closed without merging