8342393: Promote vector IR node sharing
openjdk/jdk pull request #22863
Opened 2024-12-23 11:28 UTC by jatin-bhateja

Extend GVN hashing to promote commutative IR sharing.

Draft version, tests to be added.

2025-01-07 20:59 UTC, iwanowww reviewed
Nice improvement, Jatin.

2025-01-07 20:59 UTC, iwanowww commented on src/hotspot/share/opto/vectornode.hpp
> +      return (uintptr_t)in(1) + (uintptr_t)in(2) + Opcode();
Commutative implies the operation is binary (`req == 3`). Should there be an assert somewhere to ensure it's always the case (ideally, when marking a node as commutative during construction)?

2025-01-07 20:59 UTC, iwanowww commented on src/hotspot/share/opto/phaseX.cpp
> +        if (!((n->in(1) == k->in(1) && n->in(2) == k->in(2)) ||
I find this piece hard to read. What do you think about the following?
```
if (n->is_commutative_operation()) {
  assert(k->is_commutative_operation(), "");
  assert(req == 3, "");
  if (k->in(0) == n->in(0) &&
      (k->in(1) == n->in(1) || k->in(1) == n->in(2)) &&
      (k->in(2) == n->in(1) || k->in(2) == n->in(2))) {
    // nodes are equal
  } else {
    goto collision;
  }
} else {
 ...
```

2025-01-08 10:42 UTC, jatin-bhateja commented on src/hotspot/share/opto/vectornode.hpp
> +      return (uintptr_t)in(1) + (uintptr_t)in(2) + Opcode();
Assertion check added.

2025-01-08 13:02 UTC, eme64 requested changes
Looks promising, thanks for the work!

2025-01-08 13:02 UTC, eme64 commented on test/hotspot/jtreg/compiler/vectorapi/VectorCommutativeOperSharingTest.java
> +}
As mentioned above, it would be good to have all combinations of 2 ops, with inputs x and y:
```
add(x,x)  with add(x,x)
add(y,x)  with add(x,x)
add(x,y)  with add(x,x)
add(y,y)  with add(x,x)
add(x,x)  with add(y,x)
add(y,x)  with add(y,x)
add(x,y)  with add(y,x)
add(y,y)  with add(y,x)
add(x,x)  with add(x,y)
add(y,x)  with add(x,y)
add(x,y)  with add(x,y)
add(y,y)  with add(x,y)
add(x,x)  with add(y,y)
add(y,x)  with add(y,y)
add(x,y)  with add(y,y)
add(y,y)  with add(y,y)
```
At least do this for one operator. All may be a bit much to write... Templates would really be fantastic here... coming soon.

2025-01-09 06:04 UTC, jatin-bhateja commented on test/hotspot/jtreg/compiler/vectorapi/VectorCommutativeOperSharingTest.java
> +}
Done, I think templatization will add value in some cases.

2025-01-13 09:51 UTC, jatin-bhateja commented
Hi @eme64, Your comments have been addressed. Kindly verify.

2025-01-14 08:21 UTC, XiaohongGong commented on src/hotspot/share/opto/vectornode.hpp
> +  }
So does this still work if these vector nodes are predicated which may append another mask input in future?

2025-01-15 04:09 UTC, jatin-bhateja commented on src/hotspot/share/opto/vectornode.hpp
> +  }
Thanks @XiaohongGong , comment addressed.

2025-01-16 06:44 UTC, XiaohongGong commented on test/hotspot/jtreg/compiler/vectorapi/VectorCommutativeOperSharingTest.java
> +            .lanewise(VectorOperators.ADD, vec2.lanewise(VectorOperators.ADD, vec1, vmask))
Thanks for your updating @jatin-bhateja!  

But I don't think it's right here. Do you mean `vec1.lanewise(VectorOperators.ADD, vec2, vmake)` equals to `vec2.lanewise(VectorOperators.ADD, vec1, vmask)` ?  The inactive lane values are not equal, right?  Should it keep the lane value of first input for inactive lanes? Thanks!

2025-01-16 06:54 UTC, XiaohongGong commented on test/hotspot/jtreg/compiler/vectorapi/VectorCommutativeOperSharingTest.java
> +            .lanewise(VectorOperators.ADD, vec2.lanewise(VectorOperators.ADD, vec1, vmask))
Seems the predicated IR can be commutative only if the mask is `alltrue()`. I noticed the mask in this test is `alltrue`, so it maybe correct for this case. Could you please also add other IR tests that the mask is not `alltrue`? Thanks!

2025-01-16 11:56 UTC, jatin-bhateja commented
Hi @iwanowww , @eme64 , @XiaohongGong , your comments have been addressed.

2025-01-16 13:05 UTC, eme64 reviewed
I have a general question about the approach:
For commutative scalar ops (add, mul, etc), we reorder the edges to allow commoning.
```
  // Otherwise, sort inputs (commutativity) to help value numbering.
  if( in1->_idx > in2->_idx ) {
    add->swap_edges(1, 2);
    return true;
  }
```

Have you considered doing the same with vectors?
Or should we rather refactor also the scalars with the `check_for_collision`, and have a `is_commutative_operation` for scalar and vector ops?

I'm just afraid that we have now 2 ways of doing things, making things unnecessarily complicated.

Also the basic hash / hash collision functions now have an extra check. Probably the overhead is negligible, but who knows - they used to have `goto` there for performance... what do you think?

2025-01-16 13:18 UTC, eme64 commented
@jatin-bhateja 

I discussed it quickly with @TobiHartmann . We think it is nicer if we can do a general refactoring:
- Annotate all commutative nodes with `Flag_is_commutative_oper`, both for vector and scalar node.
- Apply your idea with checking commutative cases different in `find_hash`
![image](https://github.com/user-attachments/assets/524b442a-efeb-4978-8de7-cf741534b180)
![image](https://github.com/user-attachments/assets/b2373c57-8312-43f8-a3be-eeb5fd02876f)

For us it is ok if you just apply it basically as is - and file a follow-up RFE so we can refactor away all these:
```
static bool commute(PhaseGVN* phase, Node* add) {
...
  // Otherwise, sort inputs (commutativity) to help value numbering.
  if( in1->_idx > in2->_idx ) {
    add->swap_edges(1, 2);
    return true;
  }
  return false;
}
```
We have such `swap_edges` in a few places, we would have to carefully remove all and test things well.

Alternatively, we first do this refactoring just for the scalar nodes, and then your patch only has to apply it for vector cases.

Since this is touching core `Node::hash` functionality, I think we need to get @iwanowww to agree on this idea as well.

2025-01-16 13:19 UTC, eme64 commented
/reviewers 3 reviewer

Increasing the level so that @TobiHartmann @vnkozlov also sign off on this.

2025-01-16 15:04 UTC, jatin-bhateja commented
> for vector IR we chose a simpler approach to decorate commutative operations with a special node-level flag during IR construction thus
> obviating any dependency on explicit idealization routines.

Hi @eme64 ,  Thanks,  to me marking a node as commutative right at construction time looks more appealing rather than banking on edge swapping during idealization. Patch is important for x86 where we can save bulky backend implementations through commoning, especially for sub-word vector operations where in absence of direct instruction we first upcast to word or double wordl vector, perform operation and then downcast it back to original type,  there is an order of magnitude performance improvement.

2025-01-16 23:40 UTC, vnkozlov commented
I suggest to go first with changes as they are - vector specific.  (We have to submit our testing to make sure they are safe first).
Scalar implementation will have to be investigated more carefully to make sure we will not get performance regression.
We can rename the flag and its accessors to general name, refactor some code as @eme64 suggested later when we do scalar work.

2025-01-17 06:36 UTC, eme64 reviewed
@vnkozlov @jatin-bhateja Ok, then we can leave it at the current `Flag_is_commutative_vector_op`. @jatin-bhateja please file a follow-up RFE and link it with this issue. You can assign it to me if you want - I will try to find someone to take care of the scalar refactoring.

Please add some result verification to the tests, as commented separately.

Once that is done, I can run testing and approve the PR.

2025-01-17 06:36 UTC, eme64 commented on test/hotspot/jtreg/compiler/vectorapi/VectorCommutativeOperSharingTest.java
> +            testVectorIRSharing2(i);
Adding some result verification would be nice. Because now you only check that you get the right number of instructions - but that does not mean that they are connected correctly. Result verification could help here.

See:
https://github.com/openjdk/jdk/blob/master/test/hotspot/jtreg/compiler/lib/verify/Verify.java
https://github.com/openjdk/jdk/blob/master/test/hotspot/jtreg/testlibrary_tests/verify/examples/TestVerifyInCheckMethod.java

Also, for random value generation we hope to use this in the future:
https://github.com/openjdk/jdk/blob/master/test/hotspot/jtreg/compiler/lib/generators/Generators.java

2025-01-17 06:36 UTC, eme64 commented on test/hotspot/jtreg/compiler/vectorapi/VectorCommutativeOperSharingTest.java
> +            testVectorIRSharing2(i);
You don't have to use Generators here, and it is up to you if you want to use `Verify.checkEQ` or do your own comparisons - use what is more convenient for you for now.

2025-01-21 08:11 UTC, jatin-bhateja commented
> Flag_is_commutative_vector_op

Hi @eme64 , 
I have extended IR test points to check functional corretness using Verify.checkEQ.
Created a follow-up JBS entry for scalar IR communing [https://bugs.openjdk.org/browse/JDK-8348134](https://bugs.openjdk.org/browse/JDK-8348134)
For now, I have assigned it to myself. Please feel free to re-assign it; I can help with the reviews. 

Kindly proceed with test runs.

Best Regards,
Jatin

2025-01-22 07:31 UTC, eme64 reviewed
@jatin-bhateja thanks for the test updates!

I have some more comments about the VM changes - I think we can improve the code slightly and make it more understandable :)

And thanks for filing the follow-up RFE for scalar nodes. I did not understand: do you want to work on that or not?

2025-01-22 07:31 UTC, eme64 commented on src/hotspot/share/opto/phaseX.cpp
> +      if (collision == false && n->cmp(*k)) {  // Check for any special bits
```suggestion
      if (!collision && n->cmp(*k)) {  // Check for any special bits
```

2025-01-22 07:31 UTC, eme64 commented on src/hotspot/share/opto/phaseX.cpp
> +    }
```suggestion
    for (uint i = 0; i < req; i++) {
      if (n->in(i) != k->in(i)) { // Different inputs?
        return true;
      }
    }
```
I know you just copied it, but we should fix formatting if we are touching the code anyway ;)

2025-01-22 07:31 UTC, eme64 commented on src/hotspot/share/opto/phaseX.cpp
> +bool NodeHash::check_for_collision(const Node* n, const Node* k) const {
```suggestion
bool NodeHash::have_equivalent_inputs(const Node* n, const Node* k) const {
```
I think that would be a bit more explicit.

2025-01-22 07:31 UTC, eme64 commented on src/hotspot/share/opto/phaseX.cpp
> +      if (collision == false && n->cmp(*k)) {  // Check for any special bits
A renaming of `check_for_collision` -> `have_equivalent_inputs` (with swap of true <-> false) would make this a bit more readable now, right?
```suggestion
      if (have_equivalent_inputs(n, k) && n->cmp(*k)) {  // Check for any special bits
```

2025-01-22 07:31 UTC, eme64 commented on src/hotspot/share/opto/phaseX.cpp
> -  collision:
I would replace this line with a comment like this:
`// k was not a hit. Find another candidate and try again.`

2025-01-22 10:50 UTC, jatin-bhateja commented
> @jatin-bhateja thanks for the test updates!
> 
> I have some more comments about the VM changes - I think we can improve the code slightly and make it more understandable :)
> 
> And thanks for filing the follow-up RFE for scalar nodes. I did not understand: do you want to work on that or not?

![image](https://github.com/user-attachments/assets/3b50ad09-f5b0-4ea9-af13-c0df229fb051)


Hey @eme64 , 

All your comments are addressed.
Kindly verify, on RFE: I have assigned it to myself and plan to address it after integrating my inflight PRs.

Best Regards,
Jatin

2025-01-22 12:03 UTC, eme64 reviewed
@jatin-bhateja The patch looks good now. I'll run testing again just to be sure. Feel free to ping me again in 1-2 days!

2025-01-22 12:12 UTC, eme64 commented
@jatin-bhateja my script is having issues with applying the patch. Can you merge with master, please?

2025-01-22 12:33 UTC, eme64 commented
@jatin-bhateja Thanks for the merge, testing is running...

2025-01-22 13:02 UTC, eme64 commented
Just got a gcc internal compiler error on `linux-x64-ri`:
```
[2025-01-22T12:48:11,911Z] In file included from /opt/mach5/mesos/work_dir/slaves/3fe4557b-066a-4392-9b05-ef874140c35c-S195/frameworks/1735e8a2-a1db-478c-8104-60c8b0af87dd-0196/executors/14e2b4ac-46e5-4d4c-908e-6638025c78bd/runs/0150d400-69b3-4d31-972d-8a79504cd397/workspace/open/src/hotspot/share/precompiled/precompiled.hpp:61:
[2025-01-22T12:48:11,911Z] /opt/mach5/mesos/work_dir/slaves/3fe4557b-066a-4392-9b05-ef874140c35c-S195/frameworks/1735e8a2-a1db-478c-8104-60c8b0af87dd-0196/executors/14e2b4ac-46e5-4d4c-908e-6638025c78bd/runs/0150d400-69b3-4d31-972d-8a79504cd397/workspace/open/src/hotspot/share/utilities/copy.hpp:362:2: internal compiler error: in gt_pch_save, at ggc-common.cc:674
[2025-01-22T12:48:11,911Z]   362 | };
[2025-01-22T12:48:11,911Z]       |  ^
[2025-01-22T12:48:12,841Z] 0x6e0432 gt_pch_save(_IO_FILE*)
[2025-01-22T12:48:12,841Z] 	/home/mikael/src/jdk/jdk/devkit/jdk/open/build/devkit/src/gcc-13.2.0/gcc/ggc-common.cc:674
[2025-01-22T12:48:12,867Z] 0x96b865 c_common_write_pch()
[2025-01-22T12:48:12,867Z] 	/home/mikael/src/jdk/jdk/devkit/jdk/open/build/devkit/src/gcc-13.2.0/gcc/c-family/c-pch.cc:175
[2025-01-22T12:48:12,885Z] 0x7b56e5 c_parse_final_cleanups()
[2025-01-22T12:48:12,885Z] 	/home/mikael/src/jdk/jdk/devkit/jdk/open/build/devkit/src/gcc-13.2.0/gcc/cp/decl2.cc:4940
[2025-01-22T12:48:12,885Z] 0x96b490 c_common_parse_file()
[2025-01-22T12:48:12,885Z] 	/home/mikael/src/jdk/jdk/devkit/jdk/open/build/devkit/src/gcc-13.2.0/gcc/c-family/c-opts.cc:1266
[2025-01-22T12:48:12,925Z] Please submit a full bug report, with preprocessed source (by using -freport-bug).
```
Ah, it was raised as https://bugs.openjdk.org/browse/JDK-8338470

2025-01-23 08:32 UTC, jatin-bhateja commented
Hi @eme64 , Kindly share the result of you test runs.

2025-01-23 08:38 UTC, eme64 commented
@jatin-bhateja I actually see failures in the `assert` code you added:

```
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (.../src/hotspot/share/opto/vectornode.hpp:78), pid=2210207, tid=2210226
#  Error: assert(req() == 3) failed
#
# JRE version: Java(TM) SE Runtime Environment (25.0) (fastdebug build 25-internal-LTS-2025-01-22-1232295.emanuel.peter.jdk-review)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (fastdebug 25-internal-LTS-2025-01-22-1232295.emanuel.peter.jdk-review, mixed mode, sharing, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0x9f7319]  VectorNode::hash() const+0x89
```

I see it with `-XX:UseAVX=3` on these tests:
`jdk/incubator/vector/Float256VectorTests.java`

Let me know if you need more info to reproduce.

2025-01-23 10:09 UTC, jatin-bhateja commented
> @jatin-bhateja I actually see failures in the `assert` code you added:
> 
> ```
> # A fatal error has been detected by the Java Runtime Environment:
> #
> #  Internal Error (.../src/hotspot/share/opto/vectornode.hpp:78), pid=2210207, tid=2210226
> #  Error: assert(req() == 3) failed
> #
> # JRE version: Java(TM) SE Runtime Environment (25.0) (fastdebug build 25-internal-LTS-2025-01-22-1232295.emanuel.peter.jdk-review)
> # Java VM: Java HotSpot(TM) 64-Bit Server VM (fastdebug 25-internal-LTS-2025-01-22-1232295.emanuel.peter.jdk-review, mixed mode, sharing, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
> # Problematic frame:
> # V  [libjvm.so+0x9f7319]  VectorNode::hash() const+0x89
> ```
> 
> I see it with `-XX:UseAVX=3` on these tests: `jdk/incubator/vector/Float256VectorTests.java`
> 
> Let me know if you need more info to reproduce.
> 
> I see it on windows and linux. One machine has these cpu features:
> 
> `fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr.opt pdpe1gb rdtscp lm rep.good nopl cpuid extd.apicid tsc.known.freq pni pclmulqdq ssse3 fma cx16 pcid sse4.1 sse4.2 x2apic movbe popcnt tsc.deadline.timer aes xsave avx f16c rdrand hypervisor lahf.lm cmp.legacy svm cr8.legacy abm sse4a misalignsse 3dnowprefetch osvw topoext perfctr.core invpcid.single ssbd ibrs ibpb stibp vmmcall fsgsbase tsc.adjust bmi1 avx2 smep bmi2 erms invpcid avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha.ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves nt.good avx512.bf16 clzero xsaveerptr wbnoinvd arat npt nrip.save avx512vbmi umip pku ospke avx512.vbmi2 gfni vaes vpclmulqdq avx512.vnni avx512.bitalg avx512.vpopcntdq la57 rdpid fsrm arch.capabilities`

Thanks @eme64 ,
My bad, a check to skip over predicated operation was missing. I have added a test point to cover this scenario.

Kindly verify.

2025-01-23 10:19 UTC, eme64 commented on src/hotspot/share/opto/phaseX.cpp
> +  if (n->is_commutative_vector_operation() && !n->is_predicated_vector()) {
Wait, so any of the commutative operations can also be predicated? Can you tell me what that does?
`VEC1.BLEND(VEC1.lanewise(OPER, VEC2), MASK)`
What does this do? Can you make an example?

And why would it not be ok to check if the `VEC1` and `VEC2` are the same (with swapping), and that the `MASK` is identical?

2025-01-23 10:22 UTC, jatin-bhateja commented on src/hotspot/share/opto/phaseX.cpp
> +  //        RES = VEC1.BLEND(VEC1.lanewise(OPER, VEC2), MASK)
BLEND is operating over VEC1 and result of VEC1.lanewise(OPER, VEC2) under influence of MASK.

2025-01-23 10:23 UTC, eme64 commented on src/hotspot/share/opto/vectornode.hpp
> +    if (is_commutative_vector_operation() && !is_predicated_vector()) {
You should either put the comment here again, or even better move out the condition:
`is_commutative_vector_operation() && !is_predicated_vector()`

2025-01-23 10:24 UTC, eme64 commented on src/hotspot/share/opto/phaseX.cpp
> +  //        RES = VEC1.BLEND(VEC1.lanewise(OPER, VEC2), MASK)
So it should not be `VEC1.BLEND(VEC1.lanewise(OPER, VEC2), MASK)`, but one of these:
```
VEC1.BLEND(VEC1.lanewise(OPER, VEC2), VEC1, MASK)
VEC1.BLEND(VEC1, VEC1.lanewise(OPER, VEC2), MASK)
```

2025-01-23 10:26 UTC, eme64 commented
I'm a little sad that `is_commutative_vector_operation` does not mean that it is actually commutative now. Rather, it means:
"it is commutative if it is not predicated"

I think we need to improve the naming somehow. Because it even slipped by you who work with predicated vector ops all the time - how will someone less familiar understand this and not be misled?

2025-01-23 10:26 UTC, eme64 commented on src/hotspot/share/opto/phaseX.cpp
> +  //        RES = VEC1.BLEND(VEC1.lanewise(OPER, VEC2), MASK)
Blend has 3 arguments, not just 2, right?

2025-01-23 10:38 UTC, jatin-bhateja commented on src/hotspot/share/opto/phaseX.cpp
> +  //        RES = VEC1.BLEND(VEC1.lanewise(OPER, VEC2), MASK)
VEC1 is both destination and first operand. I think we should update the comment accordingly.

2025-01-23 12:37 UTC, eme64 commented
> > I'm a little sad that `is_commutative_vector_operation` does not mean that it is actually commutative now. Rather, it means: "it is commutative if it is not predicated"
> 
> Hey @eme64 , Your comments are addressed.

What was you answer to my concern that `is_commutative_vector_operation` does not mean that it is actually commutative (with the conter example of predicated case)?

I'm still confused about your comment: does `BLEND` not have 3 operands? You closed my thread as resolved without really answering all of my questions - I'm still confused :sweat_smile:

2025-01-23 13:57 UTC, jatin-bhateja commented
> > > I'm a little sad that `is_commutative_vector_operation` does not mean that it is actually commutative now. Rather, it means: "it is commutative if it is not predicated"
> > 
> > 
> > Hey @eme64 , Your comments are addressed.
> 
> What was you answer to my concern that `is_commutative_vector_operation` does not mean that it is actually commutative (with the conter example of predicated case)?
> 
> I'm still confused about your comment: does `BLEND` not have 3 operands? You closed my thread as resolved without really answering all of my questions - I'm still confused 😅

Hi @eme64 , let me think about this solution again. Flags-based solutions are generally troublesome in the long run.  Although we do have a follow-up RFE, but I feel its good to spend a little more time here as it fixes a very important gap.

2025-01-23 18:35 UTC, jatin-bhateja commented
> > > I'm a little sad that `is_commutative_vector_operation` does not mean that it is actually commutative now. Rather, it means: "it is commutative if it is not predicated"
> > 
> > 
> > Hey @eme64 , Your comments are addressed.
> 
> What was you answer to my concern that `is_commutative_vector_operation` does not mean that it is actually commutative (with the conter example of predicated case)?
> 
> I'm still confused about your comment: does `BLEND` not have 3 operands? You closed my thread as resolved without really answering all of my questions - I'm still confused 😅

Hi @eme64 ,
I thought more on this and moving away from a based solution looks appealing.

Let me know if this looks fine to you.

> I'm still confused about your comment: does `BLEND` not have 3 operands? You closed my thread as resolved without really answering all of my questions - I'm still confused 😅

I does, two vectors and a mask under which blending happens, I have updated the comments for clarity. 
Best,
Jatin

2025-01-23 18:38 UTC, jatin-bhateja commented
Hi @vnkozlov , @eme64 , kindly let me know if this looks good to go.

2025-01-23 18:39 UTC, jatin-bhateja commented
Hi @vnkozlov , @eme64 , Please let me know if this looks good to go.

2025-01-24 01:41 UTC, XiaohongGong commented
Hi @jatin-bhateja , the new change is more clear to me. Thanks for updating the predicate IR handling. Looks fine! 

The only concern to me now is the test. I saw a series of IR checks in the added test. It seems some ones check the similar scenario. I'v added the comment in the test file. Could you please check? Thanks!

2025-01-24 10:09 UTC, jatin-bhateja commented
> Hi @jatin-bhateja , the new change is more clear to me. Thanks for updating the predicate IR handling. Looks fine!
> 
> The only concern to me now is the test. I saw a series of IR checks in the added test. It seems some ones check the similar scenario. I'v added the comment in the test file. Could you please check? Thanks!

Hi @XiaohongGong 
The intention here is to exercise all possible input combinations and IR ordering during GVN hashing, so there are explicit test points for (A1 + B1) + (B1 + A1) and (B1 + A1) + (A1 + B1) if that is what you are referring to.

Hi @eme64 , Can you kindly run the current patch through your test framework and share back the results

2025-01-27 07:29 UTC, eme64 commented on src/hotspot/share/opto/vectornode.cpp
> +  // Here, first operand "VEC1" represents both source and destination vector.
Sorry @jatin-bhateja . But this still does not make sense to me. I thought the `RES` was the destination vector for the `BLEND`? Does `BLEND` not have 3 inputs (2 vectors + 1 mask vector), and one output vector?

So I would expect a `BLEND` to have a form like this:
`RES = BLEND(V1, V2, M)`

2025-01-27 07:37 UTC, eme64 requested changes
@jatin-bhateja Yes, I think this is a bit of a simpler solution. Though the flag based one was also very interesting and would solve some other issues, i.e. other optimizations that order the inputs the other way around conflicting with ordering for value numbering. But we can leave that for another day ;)

I have a few suggestions below :)

2025-01-27 07:37 UTC, eme64 commented on src/hotspot/share/opto/vectornode.cpp
> +      }
@jatin-bhateja can you explain this / add a comment to the code?

```suggestion
      if (in(1)->_idx > in(2)->_idx) {
        // Sort the inputs of commutative non-predicated vector operations to help value numbering.
        return true;
      }
```

2025-01-27 07:37 UTC, eme64 commented on src/hotspot/share/opto/vectornode.cpp
> +bool VectorNode::can_swap_inputs() {
```suggestion
bool VectorNode::should_swap_inputs() {
```

I think the method name `can_swap_inputs` should rather be `should_swap_inputs`. Because we `can` swap the edges even when the order is `in(1)->_idx <= in(2)->_idx` already, but we `should` not ;)

2025-01-27 10:54 UTC, jatin-bhateja commented on src/hotspot/share/opto/vectornode.cpp
> +  // Here, first operand "VEC1" represents both source and destination vector.
Reframed for clarity.

2025-01-27 13:56 UTC, eme64 commented
@jatin-bhateja This patch looks good now. Running testing again, feel free to ping me in 1-2 days!

2025-01-28 08:16 UTC, jatin-bhateja commented
> With flags: `-XX:UseAVX=0 -XX:UseSSE=3`. Machine has `AVX2`. I suspect you need to add some CPU feature restrictions on the IR rule.

Hi @eme64, It's the MulVI operation that needs a minimum SSE4 feature set. Please verify, I have updated the PR.

2025-01-28 09:58 UTC, eme64 commented on test/hotspot/jtreg/compiler/vectorapi/VectorCommutativeOperSharingTest.java
> +                  IRNode.AND_VI, IRNode.VECTOR_SIZE_ANY, " 1 "})
And this is not going to fail on any architecture? What about architectures other than x64 and aarch64? Do they all support the vector instructions?

I'd rather not that this fails on their machines and then they have to fix it and we have to review their fix again ;)

2025-01-28 11:47 UTC, jatin-bhateja commented on test/hotspot/jtreg/compiler/vectorapi/VectorCommutativeOperSharingTest.java
> +                  IRNode.AND_VI, IRNode.VECTOR_SIZE_ANY, " 1 "})
Hi @eme64 ,
The attached script shows me that greatest common divisor of targets supporting IR nodes in this test is x86 :-)
  
[get_c2_IR_supported_targets.txt](https://github.com/user-attachments/files/18572758/get_c2_IR_supported_targets.txt)

![image](https://github.com/user-attachments/assets/daedb8aa-23c5-4c67-b7d3-82859155b88d)

2025-01-30 09:53 UTC, eme64 commented on test/hotspot/jtreg/compiler/vectorapi/VectorCommutativeOperSharingTest.java
> + * @requires (os.simpleArch == "x64")
Oh, I see you added it here, rather than at each IR rule. It would be nice to have this test also execute on other machines, for additional coverage.

Can you instead simply restrict it with `avx` features? And if that is not enough, and you do need 64bit restriction, then use this:
`applyIfPlatform = {"64-bit", "true"}`

2025-01-30 13:21 UTC, jatin-bhateja commented on test/hotspot/jtreg/compiler/vectorapi/VectorCommutativeOperSharingTest.java
> + * @requires (os.simpleArch == "x64")
> Oh, I see you added it here, rather than at each IR rule. It would be nice to have this test also execute on other machines, for additional coverage.
> 
These tests are only significant from commoning point of view which is checked through IR rule.

2025-01-30 13:37 UTC, eme64 commented on test/hotspot/jtreg/compiler/vectorapi/VectorCommutativeOperSharingTest.java
> + * @requires (os.simpleArch == "x64")
That would be sad, because we can still profit from all the value verification for other platforms.

And who knows, we may add similar instructions for other platforms as well, and then the value verification would come in really handy.

2025-01-30 13:40 UTC, jatin-bhateja commented on test/hotspot/jtreg/compiler/vectorapi/VectorCommutativeOperSharingTest.java
> + * @requires (os.simpleArch == "x64")
I again iterate a foundational optimizations like GVN its target indipendent and our intent here is to check commoning, hence verifying it for a target which supports all the IR nodes covered by test should suffice for now.

2025-01-30 13:43 UTC, eme64 commented on test/hotspot/jtreg/compiler/vectorapi/VectorCommutativeOperSharingTest.java
> + * @requires (os.simpleArch == "x64")
Things might look target independent now, but we are not just writing tests for the state of now, but for the future too. And that is why increased coverage would be good, as I said above ;)

2025-01-31 07:08 UTC, jatin-bhateja commented
Hi @eme64 , I have lowered the feature check to IR annotation for now.

2025-01-31 07:13 UTC, eme64 commented
@jatin-bhateja Launched testing for Commit 17 / v22.

2025-02-04 17:47 UTC, jatin-bhateja commented
Hi @eme64 , Kindly share the results of your test runs.

2025-02-04 19:20 UTC, eme64 commented
@jatin-bhateja Tests look all good on my side. I'll make another pass in the next few days, and hopefully approve.

2025-02-05 09:48 UTC, eme64 requested changes

2025-02-05 09:48 UTC, eme64 commented on src/hotspot/share/opto/vectornode.cpp
> +  if (should_swap_inputs()) {
```suggestion
  if (should_swap_inputs_to_help_global_value_numbering()) {
```

2025-02-05 09:48 UTC, eme64 commented on src/hotspot/share/opto/vectornode.cpp
> +bool VectorNode::should_swap_inputs() {
```suggestion
// If we have a AddVB(v1, v2) and AddVB(v2, v1), we want to swap the edges of one of them
// so that they become identical, and can common in global value numbering.
bool VectorNode::should_swap_inputs_to_help_global_value_numbering() {
```

2025-02-05 09:48 UTC, eme64 commented on src/hotspot/share/opto/vectornode.hpp
> +  bool should_swap_inputs();
```suggestion
  bool should_swap_inputs_to_help_global_value_numbering();
```

2025-02-05 09:48 UTC, eme64 commented on src/hotspot/share/opto/vectornode.cpp
> +  }
Hmm. Can you give me a concrete example of a masked operation that would be filtered out?

Can it for example be a `AddVI`? But that only has 2 inputs for `VEC1` and `VEC2`. Where would the mask be located - and why does that not get us to `req() > 3`?

Ah, I see it can be added in `VectorNode::try_to_gen_masked_vector`, with `add_req`, but then we should have `req() > 3`.

Ok, this looks a bit complicated, but it looks like we are doing this.
```
  // Generate a vector mask for vector operation whose vector length is lower than the
  // hardware supported max vector length.
```

Ok, fine.

It could be good to add a comment here though, explaining why the operation seemingly has 3 inputs, but we don't exit at `req() != 3` above.

2025-02-07 14:10 UTC, jatin-bhateja commented on src/hotspot/share/opto/vectornode.cpp
> +  }
Hi @eme64, Since we are selectively enabling commoning based on opcodes checks, hence skipping over their predicated counterparts should suffice.

Please find below the code reference adding mask operands it targets supports perdicated instructions.
https://github.com/openjdk/jdk/blob/master/src/hotspot/share/opto/vectorIntrinsics.cpp#L495

2025-02-10 05:33 UTC, jatin-bhateja commented
Hi @eme64 , All comments addressed, looking forward to your approval.

2025-02-12 11:07 UTC, eme64 commented on src/hotspot/share/opto/vectornode.cpp
> +        return true;
Ah, I see you now removed the condition above:
```
  // Must be a binary operation.
  if (req() != 3) {
    return false;
  }
```

That's probably correct. But can we still have an assert somehow that `req() == 3`, please ;)

2025-02-12 12:17 UTC, jatin-bhateja commented
Hi @eme64 , All comments addressed, looking forward to your approval

2025-02-13 09:23 UTC, eme64 commented
@jatin-bhateja Perfect, it looks good now. Let me run testing one more time just to be sure. Please ping me in a day or so for the results!

2025-02-19 11:43 UTC, jatin-bhateja commented
Hi @eme64 , Let us know if its good to land.

2025-02-20 14:17 UTC, eme64 approved these changes
Testing passed. Approved. Thanks for the work @jatin-bhateja :)

2025-02-20 15:52 UTC, jatin-bhateja commented
/integrate

2025-02-21 00:38 UTC, sviswa7 approved these changes
Looks good to me.

2025-02-21 05:31 UTC, jatin-bhateja commented
Hi @iwanowww , Can you kindly review and approve, we need another approval here.

2025-02-24 05:21 UTC, jatin-bhateja commented
Hi @TobiHartmann , @iwanowww , Can you kindly approve the patch.

2025-02-24 06:31 UTC, iwanowww approved these changes
Looks even better!

2025-02-24 07:39 UTC, jatin-bhateja commented on src/hotspot/share/opto/vectornode.cpp
> +  if (should_swap_inputs_to_help_global_value_numbering()) {
It was modified based on @eme64  suggestion,
https://github.com/openjdk/jdk/pull/22863#discussion_r1942531523

I am inclined to go with what we have to save another approval cycle :-)

2025-02-24 07:40 UTC, closed without merging

2025-02-24 07:40 UTC, jatin-bhateja commented
Thanks @eme64 , @iwanowww , @sviswa7  for your approvals.