JDK-8346717: serviceability/dcmd/vm/SystemDumpMapTest.java failing on Windows with "Stack base not yet set for thread id"
openjdk/jdk pull request #22870
Opened 2024-12-23 18:43 UTC by stooke

This test fixes an issue with incomplete Windows threads not yet having a stack.  A test for a null stack_base is added.

2024-12-23 18:47 UTC, stooke commented
/label jcmd

2024-12-23 18:52 UTC, stooke commented
/label hotspot serviceability

2024-12-25 00:26 UTC, lmesnik requested changes

2024-12-25 00:26 UTC, lmesnik commented on test/hotspot/jtreg/serviceability/dcmd/vm/SystemMapTest.java
> + * @run testng/othervm -XX:+UsePerfData -XX:+UseZGC SystemMapTest
No need to add separate testcase for ZGC. It is expected that  hotspot tests are usually executed to ensure that all functionality works with any GC.
If you want to add it to ensure that  regression testcase is always executed even no ZGC is set then please 
1) add
`* @requires vm.gc.Z`
So testcase is not executed if non-ZGC GC (Parallel/Serial etc) is set explicitly.
2) Add 
` * @bug 8346717`
3) Add id like
`* @test id=zgc`
to make testcase name clearer.

2025-01-03 20:07 UTC, stooke commented on test/hotspot/jtreg/serviceability/dcmd/vm/SystemMapTest.java
> + * @run testng/othervm -XX:+UsePerfData -XX:+UseZGC SystemMapTest
@lmesnik thank you for the review!  I have updated the jtreg tags as suggested.  My intent is to ensure this test is run with and without ZGC as the expected results differ.  I believe I can accomplish this with these two test definitions?  I've seen similar test definitions elsewhere in the jdk.

2025-01-06 06:19 UTC, dholmes-ora requested changes

2025-01-06 06:19 UTC, dholmes-ora commented on test/hotspot/jtreg/serviceability/dcmd/vm/SystemMapTest.java
> + * @test id=normal
The normal test should be for non-ZGC otherwise in a test config that runs everything with ZGC you will run them both when only one is needed

2025-01-09 03:06 UTC, dholmes-ora approved these changes

2025-01-09 03:06 UTC, dholmes-ora commented on test/hotspot/jtreg/serviceability/dcmd/vm/SystemMapTest.java
> + * @run testng/othervm -XX:+UsePerfData -XX:-UseZGC SystemMapTest
Technically you don't need to disable ZGC as the requires clause means it is already not the selected GC

2025-01-09 21:13 UTC, stooke commented on test/hotspot/jtreg/serviceability/dcmd/vm/SystemMapTest.java
> + * @run testng/othervm -XX:+UsePerfData -XX:-UseZGC SystemMapTest
Done.

2025-01-09 21:23 UTC, lmesnik approved these changes
Test changes looks good.

2025-01-10 07:24 UTC, dholmes-ora approved these changes
Looks good. Let's get this integrated! :) Thanks

2025-01-10 13:25 UTC, stooke commented
/integrate

2025-01-12 21:38 UTC, dholmes-ora commented
/sponsor

2025-01-12 21:39 UTC, closed without merging