Remove PassFailJFrame constructor with screenshots
openjdk/jdk pull request #22873
Opened 2024-12-24 03:02 UTC by anass-baya

Remove PassFailJFrame constructor with screenshots since no test is using it

2024-12-24 13:06 UTC, anass-baya commented
/covered

2025-01-07 19:59 UTC, aivanov-jdk requested changes

2025-01-07 23:06 UTC, anass-baya commented on test/jdk/java/awt/regtesthelpers/PassFailJFrame.java
> -     */
thank you for your review

2025-01-08 13:16 UTC, aivanov-jdk requested changes
Nearly good.

Please, also update the copyright year at the top of the file: 2024 → 2025.

2025-01-08 13:16 UTC, aivanov-jdk commented on test/jdk/java/awt/regtesthelpers/PassFailJFrame.java
>       * The screenshot feature is not enabled, if you use this constructor.
I think this line about the screenshot should be removed now.

2025-01-08 13:16 UTC, aivanov-jdk commented on test/jdk/java/awt/regtesthelpers/PassFailJFrame.java
> +
This blank line is redundant, follow the code style in the file where there are no blank line between the javadoc and the declaration.

2025-01-08 13:16 UTC, aivanov-jdk commented on test/jdk/java/awt/regtesthelpers/PassFailJFrame.java
> +
No trailing whitespace is allowed. The `jcheck` bot has marked it as an error and blocker.

2025-01-08 18:57 UTC, aivanov-jdk approved these changes
Looks good.

2025-01-23 14:05 UTC, azvegint approved these changes

2025-01-23 15:20 UTC, aivanov-jdk commented
> Remove PassFailJFrame constructor with screenshots since no test is using it

The feature remains available when using the recommended builder pattern to create an instance of `PassFailJFrame`.

This is to discourage using constructors directly. It's easier to remove the constructor when it's not used at all.

2025-01-24 06:59 UTC, azvegint commented
/sponsor

2025-01-24 07:01 UTC, closed without merging