8346836: C2: Introduce a way to verify the correctness of ConstraintCastNodes at runtime
openjdk/jdk pull request #22880
Opened 2024-12-25 14:54 UTC by merykitty

Hi,

This patch adds a develop flag `VerifyConstraintCasts`, which will verify the correctness of `CastIINode`s and `CastLLNode`s at runtime and crash the VM if the dynamic value lies outside the type value range.

Please take a look, thanks a lot.

2024-12-25 15:02 UTC, merykitty commented
Running tier 1 tests with this flag and `-XX:+StressGCM` reveals several failures. One example is `compiler.arraycopy.TestArrayCopyConjoint`. In the method `testByte(int, int, int)`, we have the final graph before matching:

![image](https://github.com/user-attachments/assets/6627c5c9-8408-44cb-849f-76fb4b26fd86)

`228 CastII` is a cast on `P0` has its type being `int[0, 32]`, it depends on 3 dominating ifs:
- `100 If`, which corresponds to `(P0 < 0) == false`
- `223 If`, which corresponds to `(P0 != 0) == true`
- `200 If`, which corresponds to `(ConvI2L(P0) u<= 32L) == true`

As a result, `228 CastII` should have its control flow being the `IfTrueNode` projection of `200 If`. However, it is incorrectly wired to the `IfTrueNode` projection of `223 If`, which leads to the verification failure.

2025-01-08 07:21 UTC, eme64 requested changes
Looks interesting :)

Would we have caught any bug with this, do you have an example?

If I remember correctly, we relax/widen the Cast ranges somewhere later in optimizations, so that different CastII etc can common. Probably happens after loop-opts. So the ranges usually go from `[1..10]` -> `[0, max]` or `[-1 .. 1]` -> `int`. So this verification would then not be super effective, right? Things might have gone wrong much earlier with bad assumptions. I mean it could still catch issues, but I'm not sure how likely that is?

TLDR: I'd like some more context / motivation for this patch ;)

And: you should have at least one plain test where you enable the flag, and it compiles everything required to run an empty `main` function.

2025-01-08 07:24 UTC, eme64 commented
Ah, I actually see that you have some examples. So you plan on introducing this flag first, and only then fixing the issues? But does it fail with a simple `java --version`? Or an empty `main` method, maybe with `-Xcomp`?

2025-01-08 07:47 UTC, merykitty commented
@eme64 Thanks for looking at this

The context is that while reviewing #22666 I came to the conclusion that our handling of `depends_only_on_test` is broken. I have added a comment explaining my understanding and concerns there. In principle, before the execution, a `DivINode` is the same as a `CastIINode` which limits the value range of the divisor to `!= 0`. As a result, there should not be any difference in the way we handle the movements of these nodes. This leads me to the conclusion that `CastIINode`s may also be wired to the wrong control input, the reason we have not caught them is that unlike a division complaining loudly, a `CastIINode` will silently accept incorrect input values. This motivates me to make this patch.

> If I remember correctly, we relax/widen the Cast ranges somewhere later in optimizations, so that different CastII etc can common. Probably happens after loop-opts. So the ranges usually go from `[1..10]` -> `[0, max]` or `[-1 .. 1]` -> `int`.

You are right, it is in `ConstraintCastNode::widen_type` for which I will disable that widening in the presence of `VerifyConstraintCasts`.

> So you plan on introducing this flag first, and only then fixing the issues?

There are several failures in tier 1 alone, and this flag is not enabled by default or in the pipeline, so I think incorporating it first would be preferable, then after fixing all the issues we can add it to the stress options.

> But does it fail with a simple java --version? Or an empty main method, maybe with -Xcomp?

No it does not fail with `--version` or with an empty main method with and without `-Xcomp`.

2025-01-17 07:39 UTC, eme64 reviewed
I like this idea a lot. I'm personally on the fence if it is ok to integrate a flag that does not yet pass in the tests. The risk is that nobody fixes it.

What do you think about that @TobiHartmann @vnkozlov ?

Did you run testing with and without the flag? Cannot see the link posted on JIRA.

2025-01-17 07:39 UTC, eme64 commented on src/hotspot/share/opto/castnode.cpp
> +  if (VerifyConstraintCasts) {
Can we have 2 modes, one where we do the widening, and one where we do not?

2025-01-17 07:39 UTC, eme64 commented on src/hotspot/cpu/x86/c2_MacroAssembler_x86.cpp
> +  stop("Invalid CastII");
Is there any way to print the `[lo,hi]` and `dst`? I suppose one can always get that via the debugger, would just be convenient.

2025-01-17 07:48 UTC, eme64 commented
Talked with @TobiHartmann , he thinks it is ok to integrate the flags, even if it has failures. Let's go ahead with it then.

It would still be nice to have 2 modes: one where we do the widening, and one without. Both may catch different things, right? I imagine it like this: `VerifyConstraintCasts=1` -> do widening. `VerifyConstraintCasts=2` -> disable widening.

Plus, can you do this?
> And: you should have at least one plain test where you enable the flag, and it compiles everything required to run an empty main function.

Or does that already trigger failures? It would be nice just so we have some basic testing, and see that the flag is not completely broken.

2025-01-17 07:48 UTC, eme64 commented
What about implementing the same for aarch64? That would increase our coverage eventually.

2025-01-17 16:41 UTC, vnkozlov commented
We can add this flag to our stress testing sets of flags to make sure we run with it during our regular testing.

2025-01-19 15:04 UTC, merykitty commented on src/hotspot/share/opto/castnode.cpp
> +  if (VerifyConstraintCasts) {
Done

2025-01-19 15:05 UTC, merykitty commented on src/hotspot/cpu/x86/c2_MacroAssembler_x86.cpp
> +  stop("Invalid CastII");
Done, calling into VM somehow results in no stacktrace so I just call `hlt` instead.

2025-01-19 15:11 UTC, merykitty commented
@eme64 Thanks for your reviews, I have added 2 test cases for `TestIterativeGVN` that set `VerifyConstraintCasts`, the name of the test may need to change but I have not been able to come up with anything preferable.

For aarch64, I don't have an aarch64 machine around so it would be not so trivial.

2025-01-22 08:13 UTC, eme64 requested changes
Just a few more comments :)

2025-01-22 08:13 UTC, eme64 commented on src/hotspot/share/opto/c2_globals.hpp
> +                                                                            \
Nit: I think the alignment could be a little improved, maybe also the comments.
Here a quick draft:

```suggestion
  develop(uint, VerifyConstraintCasts, 0,                                   \
          "Perform runtime checks to verify the value of a ConstraintCast " \
          "lies inside its type"                                            \
          "0: No verification."                                             \
          "1: Verify (types are widened, same as without verification)."  \
          "2: Verify, where types are not widened, for better  " \
          "   verification coverage"). \
          range(0, 2)                                                       \
                                                                            \
```
I'm too lazy to fix the alignment of the `\`. This here is just a suggestion, I leave it up to you in the end ;)

2025-01-22 08:13 UTC, eme64 commented on src/hotspot/share/opto/castnode.cpp
> +  // Keep these casts for verification
You could write about `VerifyConstraintCasts` with its 2 modes, and say why they are both useful.

2025-01-22 08:13 UTC, eme64 commented on test/hotspot/jtreg/compiler/c2/TestVerifyConstraintCasts.java
> + * @run main/othervm/timeout=300 -Xbatch -Xcomp -XX:+StressGCM -XX:VerifyConstraintCasts=2 compiler.c2.TestVerifyConstraintCasts
```suggestion
 * @run main/othervm/timeout=300 -Xbatch -Xcomp -XX:VerifyConstraintCasts=2 compiler.c2.TestVerifyConstraintCasts
```
I would have left the `StressGCM` out - we already add that in our CI testing for some runs anyway. But I suppose it does not super hurt to have it in either.

2025-01-22 08:13 UTC, eme64 commented on test/hotspot/jtreg/compiler/c2/TestVerifyConstraintCasts.java
> + * @run main/othervm/timeout=300 -Xbatch -Xcomp -XX:+StressGCM -XX:VerifyConstraintCasts=2 compiler.c2.TestVerifyConstraintCasts
What was your reason to put it in?

2025-01-22 15:15 UTC, merykitty commented on src/hotspot/share/opto/c2_globals.hpp
> +                                                                            \
Done, I believe the common theme in this file is to use `=` to signify the meanings of different values of the same variable while `:` is to signify the meanings of different variables.

E.g:

      develop(uint, VerifyIterativeGVN, 0,                                      \
              "Verify Iterative Global Value Numbering"                         \
              "=XY, with Y: verify Def-Use modifications during IGVN"           \
              "          X: verify that type(n) == n->Value() after IGVN"       \
              "X and Y in 0=off; 1=on")                                         \
              constraint(VerifyIterativeGVNConstraintFunc, AtParse)             \

2025-01-22 15:15 UTC, merykitty commented on src/hotspot/share/opto/castnode.cpp
> +  // Keep these casts for verification
Done

2025-01-22 15:18 UTC, merykitty commented on test/hotspot/jtreg/compiler/c2/TestVerifyConstraintCasts.java
> + * @run main/othervm/timeout=300 -Xbatch -Xcomp -XX:+StressGCM -XX:VerifyConstraintCasts=2 compiler.c2.TestVerifyConstraintCasts
Even if a `ConstraintCastNode` has a wrong control input, it is normally scheduled later than the control input. Using `-XX:+StressGCM` helps lift the node in the dominator tree, increases the chance a wrong value is successfully observed.

2025-02-04 18:58 UTC, eme64 approved these changes
Sorry for the delay.

Looks great, especially with the better comments! :clap:

2025-02-04 19:25 UTC, vnkozlov reviewed
Can we add AArch64 implementation too to cover our platforms?

2025-02-06 19:11 UTC, merykitty commented
@vnkozlov I don't have an AArch64 machine so I feel less confident writing one. We can add an AArch64 implementation later, though. What do you think?

2025-02-07 17:22 UTC, iwanowww reviewed
Very nice!

2025-02-07 17:22 UTC, iwanowww commented on src/hotspot/cpu/x86/c2_MacroAssembler_x86.cpp
> +void C2_MacroAssembler::checked_cast_int(const TypeInt* type, Register dst) {
Naming is a bit confusing here. It is a register which holds the value being range checked, not a register where new value is put.

2025-02-07 17:22 UTC, iwanowww commented on src/hotspot/cpu/x86/c2_MacroAssembler_x86.cpp
> +  cmpl(dst, type->_lo);
Optimization idea: some range checks may be redundant (when `lo`/`hi` hold min/max values).

2025-02-07 17:22 UTC, iwanowww commented on src/hotspot/share/opto/c2_globals.hpp
> +  develop(uint, VerifyConstraintCasts, 0,                                   \
Any downsides in making the flag diagnostic? It'll make it available in product builds.

2025-02-07 17:22 UTC, iwanowww commented on src/hotspot/cpu/x86/c2_MacroAssembler_x86.cpp
> +  hlt(); // hlt so we have the stack trace
That's interesting. Sounds like a problem in `NativeStackPrinter::print_stack()`.

Speaking of debugging output, a call into a local helper function (encapsulating pretty printing logic) followed by a hlt call will do the job. But, considering the usages are in-line and quite common I suggest to make it conditional (guarded by a flag). It is possible to recover all 3 values from generated code if needed and turn on error reporting (specify the diagnostic flag) when reproducing failures.

2025-02-07 17:22 UTC, iwanowww commented on src/hotspot/cpu/x86/x86_64.ad
> +instruct castLL_checked(rRegL dst, rRegL tmp, rFlagsReg cr)
Optimization idea: considering the range is statically known, `tmp` is not needed when range boundaries fit into signed int. Worth adding an extra AD instruction to benefit from that.

2025-02-07 22:06 UTC, vnkozlov commented
> @vnkozlov I don't have an AArch64 machine so I feel less confident writing one. We can add an AArch64 implementation later, though. What do you think?

Okay, later is fine.

2025-04-05 06:33 UTC, merykitty commented
/open

2025-04-05 06:39 UTC, merykitty commented on src/hotspot/cpu/x86/c2_MacroAssembler_x86.cpp
> +void C2_MacroAssembler::checked_cast_int(const TypeInt* type, Register dst) {
I have renamed it to `val`

2025-04-05 06:44 UTC, merykitty commented on src/hotspot/cpu/x86/c2_MacroAssembler_x86.cpp
> +  hlt(); // hlt so we have the stack trace
I have made a helper function that will print the error message together with the parameters, the stack printing is still problematic, though.

2025-04-05 06:48 UTC, merykitty commented on src/hotspot/share/opto/c2_globals.hpp
> +  develop(uint, VerifyConstraintCasts, 0,                                   \
That's a great idea, done it.

2025-04-08 20:08 UTC, merykitty commented on src/hotspot/cpu/x86/c2_MacroAssembler_x86.cpp
> +  call(RuntimeAddress(CAST_FROM_FN_PTR(address, abort_checked_cast_int)));
I believe C2 stacks are 16-byte aligned so we should not need to manually do the alignment?

2025-04-08 20:09 UTC, merykitty commented on src/hotspot/cpu/x86/x86_64.ad
> +            Assembler::is_simm32(static_cast<const CastLLNode*>(n)->type()->is_long()->_lo) &&
Done, I added it to `ad_x86.hpp`

2025-04-08 20:12 UTC, merykitty commented
@iwanowww Thanks for the reviews, I hope I have addressed all of your comments.

2025-04-08 21:26 UTC, iwanowww commented on src/hotspot/cpu/x86/c2_MacroAssembler_x86.hpp
> +  void checked_cast_int(const TypeInt* type, Register val);
> Expanding the Type before passing into the function would be really bad after https://github.com/openjdk/jdk/pull/17508, though.

Can you elaborate, please? Are you saying that after #17508 there'll be more invariants to verify, so better to pass all the data encapsulated in a `Type`?

2025-04-08 21:27 UTC, iwanowww commented on src/hotspot/cpu/x86/c2_MacroAssembler_x86.cpp
> +  call(RuntimeAddress(CAST_FROM_FN_PTR(address, abort_checked_cast_int)));
Indeed. Still puzzled why stack traces are omitted. Do you have a reproducer to try?

2025-04-08 21:31 UTC, iwanowww commented on src/hotspot/cpu/x86/c2_MacroAssembler_x86.cpp
> +  fatal("Invalid CastLL, val: %lld, lo: %lld, hi: %lld", (long long)val, (long long)lo, (long long)hi);
Thanks. Primarily, I had ideal node id in mind, but mach node info is useful as well.

2025-04-08 21:33 UTC, iwanowww commented on src/hotspot/cpu/x86/x86_64.ad
> +bool castLL_is_imm32(const Node* n) {
Please, assert that n is CastLL.

2025-04-08 21:34 UTC, iwanowww approved these changes
Looks good.

2025-04-08 21:37 UTC, iwanowww commented
Speaking of bug synopsis, can you make it a bit more concrete and succinct?

How about "C2: Verify CastII/CastLL bounds at runtime"?

2025-04-09 18:03 UTC, merykitty commented on src/hotspot/cpu/x86/c2_MacroAssembler_x86.cpp
> +  call(RuntimeAddress(CAST_FROM_FN_PTR(address, abort_checked_cast_int)));
You can just run `compiler/arraycopy/TestArrayCopyConjoint.java` with `-XX:+StressGCM -XX:VerifyConstraintCasts=2`.

2025-04-09 18:04 UTC, merykitty commented on src/hotspot/cpu/x86/c2_MacroAssembler_x86.hpp
> +  void checked_cast_int(const TypeInt* type, Register val);
Yes that's what I mean, expanding all of them to feed into this method seems inelegant.

2025-04-09 18:06 UTC, merykitty commented
@iwanowww Thanks a lot for the reviews, I have updated according to your suggestions.

2025-04-09 18:33 UTC, iwanowww commented on src/hotspot/cpu/x86/c2_MacroAssembler_x86.hpp
> +  void checked_cast_int(const TypeInt* type, Register val);
Ok, it makes perfect sense.

2025-04-10 00:37 UTC, iwanowww commented
FTR here's AArch64 support:
  https://github.com/openjdk/jdk/commit/7ed34d09560d9db79183a80df379f3003f79bb1b

Feel free to incorporate it in this PR or I'll upstream it separately..

2025-04-10 00:55 UTC, iwanowww commented on src/hotspot/cpu/x86/c2_MacroAssembler_x86.cpp
> +  call(RuntimeAddress(CAST_FROM_FN_PTR(address, abort_checked_cast_int)));
Mystery solved: it is the consequence of the fact that JVM doesn't preserve frame pointer in generated code. With `-XX:+PreserveFramePointer` everything works fine.

2025-04-10 03:12 UTC, iwanowww commented on src/hotspot/cpu/x86/c2_MacroAssembler_x86.cpp
> +  call(RuntimeAddress(CAST_FROM_FN_PTR(address, abort_checked_cast_int)));
FTR with the following patch I see stack traces both w/ and w/o `-XX:+PreserveFramePointer`:
https://github.com/iwanowww/jdk/commit/bbcd8d4dc7ab24152776a3e937ebd27367cf7331

I'll file a bug to fix the underlying issue.

2025-04-22 17:07 UTC, merykitty commented
@iwanowww Thanks a lot for your help, I have incorporated your patches.

/contributor add vlivanov

2025-04-23 21:38 UTC, iwanowww approved these changes
Looks good. Thanks.

2025-04-24 06:27 UTC, eme64 approved these changes
Wow, this looks even much better with the improved printing on failure now!

Just out of curiosity: Is the whole `reconstruct_frame_pointer` mechanism general enough so that we could use it in other places as well? It is not super important to me any more, but I've wanted to have something like this for `VerifyAlignVector` already :)

2025-04-24 06:27 UTC, eme64 commented on test/hotspot/jtreg/compiler/c2/TestVerifyConstraintCasts.java
> + * @summary Run with -Xcomp to test -XX:+StressGCM -XX:VerifyConstraintCasts=1 in debug builds.
Nit: you are also running it with `-XX:VerifyConstraintCasts=1`. I would just keep the summary more generic.
```suggestion
 * @summary Empty main program to run with flag VerifyConstraintCasts.
```

2025-04-24 16:08 UTC, merykitty commented on test/hotspot/jtreg/compiler/c2/TestVerifyConstraintCasts.java
> + * @summary Run with -Xcomp to test -XX:+StressGCM -XX:VerifyConstraintCasts=1 in debug builds.
Thanks, I have done so

2025-04-24 23:12 UTC, iwanowww commented on src/hotspot/cpu/aarch64/c2_MacroAssembler_aarch64.cpp
> +    subsw(rtmp, rval, lo);
Yes, you are right. Completely forgot that there's only 12 bits available for the immediate (`Assembler::operand_valid_for_add_sub_immediate()`).

2025-04-24 23:14 UTC, iwanowww commented on src/hotspot/cpu/aarch64/c2_MacroAssembler_aarch64.cpp
> +    subsw(rtmp, rval, lo);
Completely forgot what I was thinking about when writing that code :-)

2025-04-24 23:18 UTC, iwanowww approved these changes

2025-04-25 02:09 UTC, merykitty commented
@iwanowww @eme64 Thanks a lot for your reviews!
/integrate

2025-04-25 02:10 UTC, closed without merging

2025-04-25 02:13 UTC, merykitty commented
> IMO it is general enough, but I haven't found a good place to put it. Ideally, all runtime/debug calls should keep frame pointer valid for diagnostic purposes.

Tbh I don't understand ... How does the VM normally walk the stack when we crash in a compiled method? I thought that it has to know the frame size of a compiled method? Why do we need to manually reconstruct the frame pointer?

2025-04-25 05:19 UTC, iwanowww commented
JVM knows how to unwind the stack when crash happens in compiled code (compiled frame on top). When native frame is on top, it relies on platform ABI, so fails to unwind the stack at the border of native and compiled frames because compiled code doesn't follow platform ABI conventions.