8346157
openjdk/jdk pull request #22885
Opened 2024-12-26 09:11 UTC by offamitkumar

Fixes ubsan warning in mallocTracker.cpp

2024-12-26 09:51 UTC, offamitkumar commented
/label hotspot-runtime

2024-12-27 02:55 UTC, offamitkumar commented
/issue 8346157

2025-01-02 16:32 UTC, gerard-ziemski requested changes

2025-01-02 16:32 UTC, gerard-ziemski commented on src/hotspot/share/nmt/mallocTracker.cpp
> +    if (here == 0) {
We should use `nullptr` here not `0`:

if (here == nullptr) {

2025-01-03 06:31 UTC, offamitkumar commented on src/hotspot/share/nmt/mallocTracker.cpp
> +    if (here == 0) {
but `here` is of `uintptr_t` datatype.

2025-01-03 06:34 UTC, offamitkumar commented on src/hotspot/share/nmt/mallocTracker.cpp
> +      if (!os::is_readable_range((uint8_t*)here, (uint8_t*)(here + sizeof(MallocHeader)))) {
> Do we need the casts here?

cast is required is here. because again `here` is `uintptr_t` datatype. 

>so cast it to (void*) instead.

Sure, that was a mistake from my end. Initially I was casting whole thing to `void*` but then `here + sizeof(MallocHeader)` caused issue. So I casted to `uint8_t*` and later forget to update it.

2025-01-03 07:53 UTC, tstuefe reviewed
The overflow is not fixed with a conversion to an integral, right? We just mute UBSAN that way.

The correct way would be to cap `end` at 0.

Instead, or in addition to that, I would bail out right away at the start of the function if the pointer is smaller than a reasonable minimum. Or, even better, at the start of `os::print_location`.

A reasonable minimum would be `os::vm_min_address()`. We should never see mappings lower than that. Since on Linux this is an OS-side setting that can be adjusted theoretically to 0 (I think), I would combine that with a hard minimum, e.g.

```
if (p2u(addr) < MAX2(os::vm_min_address(), 16 * M) {
  return;
}
```

2025-01-06 08:26 UTC, tstuefe commented on src/hotspot/share/nmt/mallocTracker.cpp
> +  if (p2u(addr) < MAX2(os::vm_min_address(), (size_t)16 * 0x100000 /* 16 MB */)) {
Use "M" instead of 0x100000?

2025-01-06 08:30 UTC, tstuefe commented on src/hotspot/share/nmt/mallocTracker.cpp
> +                      : 0;
`here` will always be > 0, overflowed or not. You need to check the decrement amount before decrementing. With "capping end" I meant setting it at or above the decrement amount, e.g.
```
end = MAX2(smallest_possible_alignment, here - (0x1000 + sizeof(MallocHeader))
```
(sorry if I wasn't clear)

2025-01-06 08:49 UTC, offamitkumar commented on src/hotspot/share/nmt/mallocTracker.cpp
> +                      : 0;
oh, I saw 0 and thought that I need to consider that as minimum value possible. Sorry. I have updated code now.

2025-01-14 14:31 UTC, tstuefe approved these changes
ok

2025-01-14 14:31 UTC, tstuefe commented on src/hotspot/share/nmt/mallocTracker.cpp
> +    uintptr_t end = MAX2(smallest_possible_alignment, here - (0x1000 + sizeof(MallocHeader))); // stop searching after 4k
This works since we know that 0x1000 + sizeof(MallocHeader) < 16MB, which is where we bail out above. Otherwise, for here values < 1K+16, we would underflow and end up with a large `end` value.

2025-01-20 12:24 UTC, theRealAph approved these changes

2025-01-21 03:52 UTC, offamitkumar commented
Thanks for the reviews.

/integrate

2025-01-21 03:53 UTC, closed without merging