8260621: Avoid memory leak in ImageBufferCache
openjdk/jdk pull request #2307
Opened 2021-01-29 05:53 UTC by blindpirate

Previously, `ImageBufferCache` contains a ThreadLocal field which holds
strong reference to `ImageBufferCache$BufferReference.class`. When loaded
from `jrt-fs.jar`, this will keep `JrtFileSystemProvider$JrtFsLoader`
in memory forever and never being GCed.

The fix replace the old `ImageBufferCache$BufferReference` class with
`WeakReference<ByteBuffer>`, which is verified by provided test.

2021-01-29 05:58 UTC, blindpirate commented
/signed

2021-02-08 14:58 UTC, JimLaskey approved these changes

2021-05-03 16:34 UTC, JimLaskey requested changes
An alternate approach is pending.

2021-06-28 07:01 UTC, AlanBateman commented
This issue was fixed with PR 3849 so I assume PR 2307 can be closed.

2021-06-28 07:03 UTC, closed without merging