[PPC64] Add support for JDK-8210498 and JDK-8222841
openjdk/jdk pull request #2432
Opened 2021-02-05 18:04 UTC by Quaffel

Introduces support for _nmethod entry barriers_ and _c2i entry barriers_ on the ppc platform. Those are required to enable concurrent class unloading for compatible garbage collectors, such as Shenandoah or zGC.

_This is a preparational change for the Shenandoah GC port to ppc. As such, it introduces features that the current version doesn't make use of, but that are required for the upcoming change. This way, the scope of the upcoming change is limited to Shenandoah-specific functionality; making its review a little easier._

2021-02-05 22:34 UTC, TheRealMDoerr requested changes
Thanks for the contribution. Looks very good. I only have a few minor requests.

2021-02-05 22:34 UTC, TheRealMDoerr commented on src/hotspot/cpu/ppc/gc/shared/barrierSetNMethod_ppc.cpp
> +  // This way, writing frame information on the stack can be avoided.
[optional] I'd replace the last sentence:
// PPC64 always has a valid back chain so the stub can simply pop the frame and there's nothing to do here.

2021-02-05 22:34 UTC, TheRealMDoerr commented on src/hotspot/cpu/ppc/stubGenerator_ppc.cpp
> +    __ bclr(Assembler::bcondCRbiIs1_bhintIsTaken, Assembler::bi0(CCR0, Assembler::equal), Assembler::bhintIsTaken);
Branch hint is provided twice. Not an error, but bcondCRbiIs1 would be cleaner if you keep it at the end.

2021-02-05 22:34 UTC, TheRealMDoerr commented on src/hotspot/cpu/ppc/stubGenerator_ppc.cpp
> +    // its execution after this method's deoptimization.  This method's prologue is aborted.
Unprecise: We're not resuming in the caller after deoptimization, we call handle_wrong_method which finds a better callee (e.g. interpreter) and jumps to it.

2021-02-08 11:24 UTC, TheRealMDoerr requested changes
Thanks for the update. I found an additional Big Endian bug (missing function descriptor).

2021-02-08 11:24 UTC, TheRealMDoerr commented on src/hotspot/cpu/ppc/stubGenerator_ppc.cpp
> +    address stub_address = __ pc();
Please use __ function_entry(); instead of __ pc();
Otherwise it's broken on Big Endian which use ABI v1.

2021-02-08 11:28 UTC, TheRealMDoerr commented on src/hotspot/cpu/ppc/stubGenerator_ppc.cpp
> +    address stub_address = __ pc();
Sorry, __ pc() seems to be correct. It's directly called from nmethod_entry_barrier without using a function descriptor.

2021-02-08 11:29 UTC, TheRealMDoerr approved these changes

2021-02-09 08:28 UTC, GoeLin approved these changes
Hi,
I'm not that deep in this code, but looking at other platforms this looks good.
Thanks for porting this!
Feel free to fix the comment or push as-is ... if this is possible with this tooling :)

2021-02-09 08:28 UTC, GoeLin commented on src/hotspot/cpu/ppc/gc/shared/barrierSetAssembler_ppc.cpp
> +  // Class loader is weak. Determine whether the holder still alive.
'is' in comment missing:   ... wether the holder _is_ still alive.

2021-02-09 13:26 UTC, Quaffel commented
Thank you for your reviews!
/integrate

2021-02-09 14:24 UTC, TheRealMDoerr commented
/sponsor

2021-02-09 14:24 UTC, closed without merging