JDK-8261297: NMT: Final report should use scale 1
openjdk/jdk pull request #2450
Opened 2021-02-08 08:15 UTC by tstuefe

If PrintNMTStatistics is specified, we write a NMT report to stdout before exiting the VM. This is useful for leak analysis.

However, the report uses the standard "K" scale, which is shouldn't, since this omits small leaks < 1K. Hence it should use scale=1. This would provide us with a precise exit report. Note that for this to work JDK-8261238 has to be fixed too, which is a separate issue.

This patch:
- changes the scale of the final report to 1
- does some minor cleanup work in the MemReporter class hierarchy (const-ifying scale and the output stream, and establishing 0 as "default scale" as to avoid having the default scale hard coded in four places.

2021-02-10 13:18 UTC, zhengyu123 requested changes
Sorry for the delay.

2021-02-10 13:18 UTC, zhengyu123 commented on src/hotspot/share/services/memReporter.hpp
> +  MemReporterBase(outputStream* out = NULL, size_t scale = 0) :
Why you want to default scale parameter to 0, instead of default_scale?

2021-02-10 13:18 UTC, zhengyu123 commented on src/hotspot/share/services/memTracker.hpp
> +
Unrelated?

2021-02-10 15:31 UTC, tstuefe commented
> Sorry for the delay.

No problem, I just pinged you in case you had not seen this PR. Since there were so many.

As requested I wired "default_scale" directly and removed the "0" as "default". I also removed the default NULL parameter for outputStream since I found no uses of MemReporter classes without an outputStream specified. 

I also removed the superfluous newline.

2021-02-10 15:41 UTC, zhengyu123 approved these changes
Looks good and trivial

2021-02-10 15:42 UTC, tstuefe commented
> Looks good and trivial

Thanks!

2021-02-11 14:58 UTC, tstuefe commented
/integrate

2021-02-11 14:59 UTC, closed without merging