8252997: Null-proofing for linker_md.c
openjdk/jdk pull request #246
Opened 2020-09-18 11:09 UTC by adamfarley

In the platform-specific implementations of linker_md.c, we see the dll_build_name methods begin with a call to jvmtiAllocate.

We then appear to rush ahead and try to use that variable without checking for a null.

I propose moving the null check to the point *before* we try to use that variable, to avoid any possible SEGV. 

Bug link: https://bugs.openjdk.java.net/browse/JDK-8252997

2020-09-18 20:23 UTC, plummercj reviewed
Both files need copyright updates before pushing. Otherwise the changes look good.

2020-09-18 20:57 UTC, sspitsyn commented
The fix looks okay to me.
But I have a dejavu that I've already reviewed it.

2020-09-18 21:57 UTC, sspitsyn approved these changes

2020-09-18 22:25 UTC, plummercj requested changes
Both files need copyright updates before pushing. Otherwise the changes look good.

2020-10-02 09:29 UTC, adamfarley commented
The copyrights have been updated as advised. Apologies for the delay.

2020-10-02 09:29 UTC, adamfarley commented
/integrate

2020-10-02 16:51 UTC, sspitsyn approved these changes

2020-10-07 08:04 UTC, shipilev commented
/sponsor

2020-10-07 08:05 UTC, closed without merging

2020-10-07 08:49 UTC, adamfarley commented
Thanks @shipilev :)