8261413: Shenandoah: Disable class-unloading in I-U mode
openjdk/jdk pull request #2477
Opened 2021-02-09 11:58 UTC by rkennke

JDK-8261341 describes a serious problem with I-U mode and class-unloading. Let's disable class-unloading in I-U for now as a workaround.

Testing:
 - [ ] hotspot_gc_shenandoah
 - [ ] tier1 (+UseShenandoahGC +IU)
 - [x] runtime/CreateMirror/ArraysNewInstanceBug.java (+UseShenandoahGC +IU +aggressive) many times in a row w/o failure

2021-02-09 12:39 UTC, shipilev requested changes

2021-02-09 12:39 UTC, shipilev commented on src/hotspot/share/gc/shenandoah/mode/shenandoahIUMode.cpp
> +  // See: https://bugs.openjdk.java.net/browse/JDK-8261341
No need for this comment, as the message prints it out.

2021-02-09 12:39 UTC, shipilev commented on src/hotspot/share/gc/shenandoah/mode/shenandoahIUMode.cpp
> +    log_warning(gc)("Shenandoah I-U mode forces -XX:-ClassUnloading, for decails, see https://bugs.openjdk.java.net/browse/JDK-8261341");
"Shenandoah I-U mode sets -XX:-ClassUnloading; see JDK-8261341 for details"

2021-02-09 13:10 UTC, shipilev approved these changes

2021-02-09 13:18 UTC, zhengyu123 approved these changes

2021-02-16 07:23 UTC, shipilev approved these changes

2021-02-16 08:17 UTC, rkennke commented
/integrate

2021-02-16 08:17 UTC, closed without merging