8261938: ASN1Formatter.annotate should not return in the finally block
openjdk/jdk pull request #2620
Opened 2021-02-18 02:28 UTC by DamonFool

Hi all,

ASN1Formatter.annotate should be able to throw an IOException according to this comment [1].
But it fails to do so due to the return [2] in the finally block, which would swallow the IOException.

Generally, it seems not good to put a return statement in a finally block because it would overwrite other return-statements or Exceptions [3].

Thanks.
Best regards,
Jie

[1] https://github.com/openjdk/jdk/blob/master/test/lib/jdk/test/lib/hexdump/ASN1Formatter.java#L113
[2] https://github.com/openjdk/jdk/blob/master/test/lib/jdk/test/lib/hexdump/ASN1Formatter.java#L120
[3] https://stackoverflow.com/questions/17481251/finally-block-does-not-complete-normally-eclipse-warning

2021-02-18 02:28 UTC, DamonFool commented
/issue add JDK-8261938
/test
/label add core-libs
/cc core-libs

2021-02-18 14:53 UTC, RogerRiggs requested changes
An EOFException can occur during the call to annotate() and must return the accumulated contents of the StringBuffer.  Otherwise it is discarded.

2021-02-18 23:41 UTC, DamonFool commented
Thanks @RogerRiggs  for your review.

Just want to make sure:

  1. AFAIK, for a method, it seems impossible to return a value and throw an exception at the same time.
     Did you mean we just need to return a string with the IOException to be catched?

  2. Does it make sense to return a string when an IOException happens?

Thanks.

2021-02-19 01:56 UTC, RogerRiggs commented
The formattters are a test component used both standalone and in the context of the HexPrinter test utilities.
In typical use, the stream is a wrapped byte array, so there are no exceptions other than EOF.
The choice of DataInputStream was chosen for the convenience of the methods to read different types
and (declared) exceptions are an unwelcome artifact.

Formatters are designed to be nested, where one formatter can call another and the valuable output
is the formatted string that has been accumulated from the beginning of the stream.  
If an exception was percolated up and the formatted output discarded it would defeat the purpose.

If an exception was thrown, it would still return useful information about the stream to that point.
The documentation could be improved to be clear on that point.

2021-02-19 03:35 UTC, DamonFool commented
> The formattters are a test component used both standalone and in the context of the HexPrinter test utilities.
> In typical use, the stream is a wrapped byte array, so there are no exceptions other than EOF.
> The choice of DataInputStream was chosen for the convenience of the methods to read different types
> and (declared) exceptions are an unwelcome artifact.
> 
> Formatters are designed to be nested, where one formatter can call another and the valuable output
> is the formatted string that has been accumulated from the beginning of the stream.
> If an exception was percolated up and the formatted output discarded it would defeat the purpose.
> 
> If an exception was thrown, it would still return useful information about the stream to that point.
> The documentation could be improved to be clear on that point.

Got it.
Thanks for your clarification.

Updated.
Thanks.

2021-02-19 15:15 UTC, RogerRiggs approved these changes
Catching and ignoring the exception has the same behavior as handling it with finally.

2021-02-19 23:45 UTC, DamonFool commented
Thanks @RogerRiggs .
/integrate

2021-02-19 23:46 UTC, closed without merging