JDK-8261969: SNIHostName would check if the encoded hostname conform to RFC 3490
openjdk/jdk pull request #2639
Opened 2021-02-19 08:39 UTC by johnshajiang

Similar to the constructor SNIHostName(String hostname), the constructor SNIHostName(byte[] encoded) also needs to check if the encoded hostname conform to RFC 3490.

2021-02-19 09:12 UTC, johnshajiang commented
/label remove net

2021-02-22 16:17 UTC, rhalade requested changes

2021-02-22 16:17 UTC, rhalade commented on test/jdk/javax/net/ssl/ServerName/IllegalSNIName.java
> +            throw new Exception("Expected to get IllegalArgumentException for "
```suggestion
            throw new RuntimeException("Expected to get IllegalArgumentException for "
```

2021-02-22 16:17 UTC, rhalade commented on test/jdk/javax/net/ssl/ServerName/IllegalSNIName.java
> +            throw new Exception("Expected to get IllegalArgumentException for "
```suggestion
            throw new RuntimeException("Expected to get IllegalArgumentException for "
```

2021-02-22 22:38 UTC, johnshajiang commented
I wouldn't merge the master to this branch :-(

2021-02-25 13:35 UTC, johnshajiang commented
Could the latest patch be reviewed?

2021-03-02 21:29 UTC, XueleiFan approved these changes

2021-03-02 21:36 UTC, rhalade approved these changes
Thanks for updating the test.

2021-03-02 22:35 UTC, johnshajiang commented
/integrate

@rhalade @XueleiFan Thanks for your reviews!

2021-03-02 22:36 UTC, closed without merging