8262094: Handshake timeout scaled wrong
openjdk/jdk pull request #2666
Opened 2021-02-21 18:46 UTC by robehn

Parameter HandshakeTimeout is in milliseconds.
Internally we use nanoseconds.
HandshakeTimeout must be scaled to nanoseconds.

2021-02-22 07:46 UTC, dholmes-ora approved these changes
Hi Robbin,

This change seems much clearer, but to be clear the actual result is the same as the "counter" tracks nanoseconds.

This counts as a trivial change IMO.

Thanks,
David

2021-02-22 08:15 UTC, robehn commented
> Hi Robbin,
> 
> This change seems much clearer, but to be clear the actual result is the same as the "counter" tracks nanoseconds.
> 
> This counts as a trivial change IMO.
> 
> Thanks,
> David

Hi David, unfortunately I don't I agree that this is trivial:

`open/src/hotspot/os/windows/os_windows.cpp:jlong os::elapsed_frequency() {
open/src/hotspot/os/windows/os_windows.cpp-  return performance_frequency;
open/src/hotspot/os/windows/os_windows.cpp-}`

This value comes from QueryPerformanceFrequency, which depends on what resolution the Windows thinks is reasonable given what hardware support there are.

In a virtualized env. this causes a 20.000 ms timeout to timeout after 2 s for me due to low resolution (windows only).
(all other platforms hardcoded to NANASECONDS)

We have two more suspective uses here, which I have not investigated (but we have seem wired timeouts with both ZGC and G1, but I have seen non with parGC):
`open/src/hotspot/share/gc/z/zMark.cpp:      _timeout(_start.value() + TimeHelper::micros_to_counter(timeout_in_micros)),
open/src/hotspot/share/gc/g1/g1ServiceThread.cpp:  jlong delay = TimeHelper::millis_to_counter(delay_ms);
`

Thanks

2021-02-22 09:01 UTC, stefank requested changes
Why are we using os::javaTimeNanos instead os::elapsed_counter()? I think we've tried to limit the usage of to places that explicitly interact with the Java side. For example, the reference processor uses os::javaTimeNanos because it interacts with java.lang.ref.SoftReference.clock. Most other places in the JVM uses os::elapsed_counter().

2021-02-22 09:45 UTC, kstefanj commented
`G1ServiceThread` is using `os::elapsed_counter()` but if the `frequency` used in `TimeHelper::millis_to_counter(...)` is wrong I guess we could be in trouble. @robehn, is your theory that the calculated delay in some cases could be extremely long and because of that cause the timeouts we see?

2021-02-22 11:02 UTC, robehn commented
> Why are we using os::javaTimeNanos instead os::elapsed_counter()? I think we've tried to limit the usage of to places that explicitly interact with the Java side. For example, the reference processor uses os::javaTimeNanos because it interacts with java.lang.ref.SoftReference.clock. Most other places in the JVM uses os::elapsed_counter().

Both uses a 'java type', jlong.
For logging and logic for yielding we want a humanly understand unit that is absolute.
Since things goes pretty fast nowadays nanseconds seems reasonable.
Instead of to converting the elapsed_counter to nanos, it's much simpler to just get the nanos.
But yes it would preferably with a os::timeNanos().

2021-02-22 11:07 UTC, robehn commented
> `G1ServiceThread` is using `os::elapsed_counter()` but if the `frequency` used in `TimeHelper::millis_to_counter(...)` is wrong I guess we could be in trouble. @robehn, is your theory that the calculated delay in some cases could be extremely long and because of that cause the timeouts we see?

The logging during handshake timeout doesn't work on windows for some reason, when I locally fixed the logging I notice that timeout was actually 2 seconds instead of 20 seconds. But that only seems to apply to some windows versions/(virtual hardware).

During some tests I have seem results such as:
"Error: time between events 0 ns"
When looking at the code the events are serialized with a mutex, so some time must have passed but the granularity of the system is to coarse. I don't know what else this can cause.

2021-02-22 12:42 UTC, stefank commented
> _Mailing list message from [David Holmes](mailto:david.holmes@oracle.com) on [hotspot-runtime-dev](mailto:hotspot-runtime-dev@openjdk.java.net):_
> 
> On 22/02/2021 7:03 pm, Stefan Karlsson wrote:
> 
> > On Sun, 21 Feb 2021 18:46:46 GMT, Robbin Ehn <rehn at openjdk.org> wrote:
> > > Parameter HandshakeTimeout is in milliseconds.
> > > Internally we use nanoseconds.
> > > HandshakeTimeout must be scaled to nanoseconds.
> > > Passes T1
> > 
> > 
> > Why are we using os::javaTimeNanos instead os::elapsed_counter()? I think we've tried to limit the usage of to places that explicitly interact with the Java side. For example, the reference processor uses os::javaTimeNanos because it interacts with java.lang.ref.SoftReference.clock. Most other places in the JVM uses os::elapsed_counter().
> 
> Runtime code (threading and sync) uses actual time units (ie
> javaTimeNanos) rather than os::elapsed_counter(). And elapsed_counter()
> uses javaTimeNanos() on all platforms but Windows.

I see. In the GC code we've tried to unify towards using one time source (elapsed_counter/elapsedTime/Ticks all use counters), and then convert to nanos/micros/millis when needed. It's a bit unfortunate that we don't use the same time source throughout the JVM.

 It's not really about
> interaction with Java, just about semantics.

From the GC's point-of-view it is. We use os::javaTimeNanos() just were we are forced to use it because interactions with Java. Other use-cases uses the counter based source.

 A timeout/delay in "ticks"
> would scale with CPU speed if "ticks" presented that, but
> os::elapsed_counter() doesn't - so a timeout/delay of N "counts" is
> somewhat arbitrary in duration.

For those cases you wouldn't pass down counter, but use TimeHelper::counter_to_millis (or equivalent).

But OK, given that Runtime already uses os::javaTimeNanos() I'll back off.

2021-02-22 12:54 UTC, robehn commented
I agree with that we should use the same time source.
But here I just want to fixed this bug so the time-out is working as intended on windows.

2021-02-23 07:37 UTC, stefank approved these changes

2021-02-23 08:25 UTC, robehn commented
Thanks David and Stefan!

2021-02-23 12:54 UTC, robehn commented
/integrate

2021-02-23 12:55 UTC, closed without merging