RFR 8252739: Deflater.setDictionary(byte[], int off, int len) ignores the starting offset for the dictionary
openjdk/jdk pull request #269
Opened 2020-09-20 18:03 UTC by LanceAndersen

Hi all,

Please review the fix  for JDK-8252739 which addresses an issue introduced by https://bugs.openjdk.java.net/browse/JDK-8225189, where Deflater.c ignored the offset specified by Deflater.setDictionary.

Mach5 jdk-tier1, jdk-tier2, jdk-tier3 runs cleanly as well as the java/util/zip and java/util/jar JCK tests.

2020-09-20 18:29 UTC, uschindler requested changes
The tests with byte buffers (direct and heap) are not using offsets (arrayOffset=0). The direct buffer test uses just a series of 0-bytes, so incorrect offsets won't change result. There should be real data copied into the direct buffer.

2020-09-20 18:29 UTC, uschindler commented on test/jdk/java/util/zip/DeflaterDictionaryTests.java
> +        ByteBuffer dictDef = ByteBuffer.wrap(DICTIONARY.getBytes(UTF_8));
This should use a slice of the byte buffer, so array offset is not 0. This can be done with offset and size on the wrap() call.

2020-09-20 18:29 UTC, uschindler commented on test/jdk/java/util/zip/DeflaterDictionaryTests.java
> +        ByteBuffer dictDef = ByteBuffer.allocateDirect(DICTIONARY.length());
This creates an empty dictionary with only 0 bytes. Maybe copy some real data into the buffer. Also a slice should be used.

2020-09-20 20:38 UTC, LanceAndersen commented
Minor updates have been made to the tests

2020-09-20 20:42 UTC, uschindler commented
Ok much better for the heap buffers. Many thanks.

The direct buffers have now contents, but I think it should copy the whole heap array into the byte buffer. After that set position and limit and then call slice(). After that you have a slice of the original direct buffer with offset.

2020-09-20 22:19 UTC, LanceAndersen commented
I have made additional updates to testByteBufferDirect to incorporate your suggestions

2020-09-20 22:23 UTC, uschindler approved these changes
Looks fine to me.

2020-09-21 12:18 UTC, AlanBateman reviewed
Update to Deflater.c looks good.

DeflaterDictionaryTests looks like is a shaping up to be a good test for setDictionary. Are there other assertions that should be checked, e.g. setDictionary(ByteBuffer) is specified to consume all bytes and it would be good to check that the position is set to the limit. Also can the 2-arg setDictionary be tests, also corner cases such no bytes remaining or invoked with null.

The naming of the tests is a bit inconsistent, e.g. ByteArrayTest vs. testByteBufferDirect. In the naming then I would use "Heap" instead of "Wrap", as in testHeapByteBuffer.

In passing: The tests can use try-finally to ensure that Deflater::end is invoked even when the test fails. String repeat(int) could be used to avoid duplicating "Welcome to Us Open;". Missing space in several "if(...)" usages.

2020-09-21 19:06 UTC, LanceAndersen commented
> Update to Deflater.c looks good.
> 
> DeflaterDictionaryTests looks like is a shaping up to be a good test for setDictionary. Are there other assertions that should be checked, e.g. setDictionary(ByteBuffer) is specified to consume all bytes and it would be good to check that the position is set to the limit. Also can the 2-arg setDictionary be tests, also corner cases such no bytes remaining or invoked with null.
> 

I have logged JDK-8253444 to add more coverage for setDictionary.  I would prefer to put his change back to address the offset not being used and improve the coverage afterwards.

> The naming of the tests is a bit inconsistent, e.g. ByteArrayTest vs. testByteBufferDirect. In the naming then I would use "Heap" instead of "Wrap", as in testHeapByteBuffer.

I  updated the test name(s).
> 
> In passing: The tests can use try-finally to ensure that Deflater::end is invoked even when the test fails. String repeat(int) could be used to avoid duplicating "Welcome to Us Open;". Missing space in several "if(...)" usages.

Addressed the issues above.

I have pushed the updated changes for review to the PR.

2020-09-22 07:28 UTC, AlanBateman reviewed
Given that the offset handling is buggy then I think the test should at least cover the cases where the offset is 0 or out of bounds. No problem separating out further test coverage for the other setDictionary methods into a separate issue.

2020-09-22 20:54 UTC, LanceAndersen commented
> Given that the offset handling is buggy then I think the test should at least cover the cases where the offset is 0 or out of bounds. No problem separating out further test coverage for the other setDictionary methods into a separate issue.

I updated the test to include an offset test for 0 and to add a test for out of range offsets.  I have updated the PR.

2020-09-23 06:59 UTC, AlanBateman approved these changes
Thanks for update to cover the offset 0 and out of bound cases.

2020-09-23 14:20 UTC, LanceAndersen commented
/integrate

2020-09-23 14:21 UTC, closed without merging