8262185: G1: Prune collection set candidates early
openjdk/jdk pull request #2693
Opened 2021-02-23 14:07 UTC by tschatzl

Hello,

  can I have reviews for this change to the collection candidate selection procedure, moving the G1HeapWastePercent exclusion criteria right after candidate selection instead of at the end of mixed gcs?

This can save lots of memory with negligible other impact.

Long version:
Currently G1 maintains collection set candidates from the marking phase (where it determines those) until the end of the mixed gc phase.

Mixed gc phase ends when the amount of space that can be reclaimed in the java heap with the remaining collection set candidates is smaller than G1HeapWastePercent of the (current) heap capacity.

This means that in some cases a significant amount of memory is used for regions that will never be evacuated. In addition to that, maintaining the remembered sets for these never evacuated regions uses execution time and more memory for the remembered set.

In fact, in some cases, it can happen that in the first few mixed gcs of a mixed gc phase, remembered set memory consumption *increases* even though the remembered sets of recently evacuated old gen regions are freed.

The proposed alternative is to prune the collection set candidates as early as possible, filtering out regions that are never going to be evacuated (or have a very low probability).

In some cases doing this can save half of peak remembered set memory usage. 

There are a few drawbacks here that should be considered during evaluation, also comparing against the old heuristic.

* In the old heuristic, G1 checks *at the end* of gc whether the remaining collection set candidates are worth collecting (remaining collectible space < G1HeapWastePercent means: stop). Which helps with ensuring at least some forward progress in evacuating the heap because (assuming there are candidates) at least some space will be reclaimed.
(I do not know whether this behavior as is is intentional for that reason, but it has been there since initial implementation; then it did not really matter because G1 has been maintaining the old gen remembered sets for all regions all the time anyway).
This is approximated by not removing all of the candidates to have at least one "minimal" mixed collection in this change.

* In some cases in the old heuristic G1 would just evacuate all candidate regions (in the extreme in a single gc) if the pause time permitted, reclaiming a bit more space (i.e. that amount < G1HeapWastePercent of the total heap).
You would expect (given the default value of 5), there will be more mixed cycles because of that with the new heuristic.

2021-02-24 12:56 UTC, walulyai approved these changes
Lgtm!

2021-02-24 13:36 UTC, tschatzl commented
@walulyai and me privately discussed some minor naming changes that the most recent push adds since I think they are good.

Also tried to improve the comment for `G1CollectionSetCandidates::prune()` a bit.

2021-02-24 13:55 UTC, walulyai approved these changes
still good!

2021-02-24 14:07 UTC, kstefanj requested changes
Looks good, just a few small comments.

2021-02-24 16:03 UTC, kstefanj commented on src/hotspot/share/gc/g1/g1CollectionSetCandidates.cpp
> +    if ((at(cur_idx)->reclaimable_bytes() + pruned_bytes) <= prune_total_bytes) {
This check should be the other way around, right?
```suggestion
    if ((at(cur_idx)->reclaimable_bytes() + pruned_bytes) > prune_total_bytes) {
```

2021-02-24 16:08 UTC, kstefanj approved these changes
Looks good =)

2021-02-25 14:23 UTC, albertnetymk approved these changes

2021-02-25 14:40 UTC, tschatzl commented
Albert and me were discussing some further code improvements that this last change implements.

2021-02-26 08:59 UTC, tschatzl commented
... and then @kstefanj also chimed in and we thought of moving the logic completely away from `G1CollectionSetCandidates` which is in spirit of the current implementation.

tier1 tested again, local testing that it works.

2021-02-26 10:27 UTC, kstefanj approved these changes
Looks good, apart from the now unused code.

2021-02-26 10:27 UTC, kstefanj commented on src/hotspot/share/gc/g1/g1CollectionSetCandidates.cpp
> +}
Not used anymore, right?
```suggestion
```

2021-02-26 10:27 UTC, kstefanj commented on src/hotspot/share/gc/g1/g1CollectionSetCandidates.hpp
> +
Same here I guess. 
```suggestion
```

2021-02-26 10:43 UTC, tschatzl commented
Thanks, removed the obsolete code.

2021-03-01 09:24 UTC, kstefanj approved these changes
Still good.

2021-03-01 11:04 UTC, tschatzl commented
Thanks @albertnetymk @kstefanj @walulyai  for your reviews.

/integrate

2021-03-01 11:05 UTC, closed without merging