8250961: Move Universe::update_heap_info_at_gc to CollectedHeap
openjdk/jdk pull request #27
Opened 2020-09-06 07:00 UTC by adityamandaleeka

This is a small refactoring that moves `update_heap_info_at_gc()` and related members to `CollectedHeap`. There should be no behavioral change.

jdk/hotspot tier1 passed

2020-09-06 07:05 UTC, adityamandaleeka commented
/label add "hotspot-gc"

2020-09-06 07:06 UTC, adityamandaleeka commented
/label add hotspot-gc

2020-09-06 07:07 UTC, adityamandaleeka commented
/label remove hotspot

2020-09-07 08:25 UTC, stefank commented on src/hotspot/share/gc/shared/collectedHeap.hpp
> +
These should be initialized in the constructor.

2020-09-07 08:29 UTC, stefank reviewed
Now that the variables and functions have moved to CollectedHeap, I don't think we need the _heap_ infix anymore.

Maybe rename variables to be named:
_capacity_at_last_gc
_used_at_last_gc

Functions:
free_at_last_gc()
used_at_last_gc()
update_capacity_and_used_at_gc()

2020-09-07 08:31 UTC, stefank commented on src/hotspot/share/gc/shared/collectedHeap.hpp
> +
Move these up to the other variables.

2020-09-07 08:32 UTC, stefank commented on src/hotspot/share/gc/shared/collectedHeap.hpp
> +
Maybe move these to after unused(). Alternatively, move it near soft_ref_policy(), since this is currently only used by soft ref handling.

2020-09-07 08:34 UTC, stefank commented
/label remove shenandoah

2020-09-08 23:52 UTC, adityamandaleeka commented
@stefank Thanks for the suggestions. I've updated the PR.

2020-09-09 06:44 UTC, stefank approved these changes
Thanks. Just two small nits below. You still need a second reviewer before this can be integrated.

2020-09-09 06:44 UTC, stefank commented on src/hotspot/share/gc/shared/collectedHeap.hpp
> +  size_t used_at_last_gc()    { return _used_at_last_gc; }
There are some unnecessary spaces between () and {. Could you also make these functions const?

2020-09-09 06:46 UTC, stefank commented
/reviewers 2

2020-09-09 10:58 UTC, kimbarrett commented
Looks good except for Stefan's comments about free/used_at_last_gc().

2020-09-09 11:25 UTC, stefank commented
@kimbarrett you need to use the Review button to make this officially reviewed.
@tschatzl FYI, will not get listed as a Reviewer if you don't review on the GitHub pages.

2020-09-09 11:54 UTC, tschatzl requested changes
@author: Same as @stefank mentioned, please do the requested cleanup.

@stefank : I can't talk about @kimbarrett , but I was simply waiting on the author to do the change and then approve (on github).

Now officially reviewed with a "request changes" result which will hold up integration (?).

2020-09-09 12:57 UTC, kimbarrett commented
/reviewer add kimbarrett

Reviewed on the assumption the requested trivial modification will be made.

2020-09-09 13:01 UTC, kimbarrett approved these changes
I'm assuming the small changes to free/used_at_last_gc will be made.

2020-09-10 00:02 UTC, adityamandaleeka commented
Thanks for the reviews @stefank @tschatzl @kimbarrett . I pushed an update addressing the last comments.

2020-09-10 02:23 UTC, kimbarrett approved these changes

2020-09-10 05:15 UTC, stefank commented
Thanks. Could you merge in master, make sure that this still builds, and run the jtreg tests in test/hotspot/jtreg/gc? After that you can add a comment with /integrate, and I'll sponsor this patch for you.

2020-09-10 06:47 UTC, adityamandaleeka commented
/integrate

2020-09-10 07:00 UTC, stefank commented
@adityamandaleeka Your branch is still 34 commits behind openjdk:master. It doesn't look like you merged the master branch into your 8250961. Or did you only do that locally?

2020-09-10 07:06 UTC, adityamandaleeka commented
@stefank Yes, I did the merge/build/test locally and didn't push anything since I saw the comment from the bot above saying that the change would be auto-rebased when merging since there are no conflicts with my branch.

2020-09-10 07:07 UTC, stefank commented
/integrate

2020-09-10 07:08 UTC, stefank commented
/sponsor

2020-09-10 07:09 UTC, closed without merging

2020-09-10 07:46 UTC, stefank commented
This caused a failure building without precompiled headers. @kimbarrett is handling that with JDK-8252995.