JDK-8157682: @inheritDoc doesn't work with @exception
openjdk/jdk pull request #2818
Opened 2021-03-03 22:22 UTC by jonathan-gibbons

Please review a fix to improve the handling of the legacy `@exception` tag.

A patch for this was [previously submitted](https://mail.openjdk.java.net/pipermail/javadoc-dev/2019-September/001139.html). However, that patch introduced an explicit new `ExceptionTaglet` class, whereas the fix here just reuses the existing `ThrowsTaglet`, registering it under an additional name.

The test in the original patch is enhanced to check all 4 combinations of (throws, exception) in the base class and (throws, exception) in the subclass.

2021-03-04 14:22 UTC, pavelrappo requested changes
This commit changes the order of block tags in the output. The fact that no tests failed when I ran them surprised me. I think we should both fix that order and introduce a test for it.

2021-03-04 15:43 UTC, jonathan-gibbons commented
/contributor add Yano, Masanori <yano-masanori@jp.fujitsu.com>

2021-03-04 15:44 UTC, jonathan-gibbons commented on src/jdk.javadoc/share/classes/jdk/javadoc/internal/doclets/toolkit/taglets/TagletManager.java
> +                    }
yeah, but ... this is just one-off init ... it's the "standard" problem of list vs. sets, and list-y sets vs. set-y lists.

2021-03-04 15:47 UTC, jonathan-gibbons commented
> This commit changes the order of block tags in the output. The fact that no tests failed when I ran them surprised me. I think we should both fix that order and introduce a test for it.

Can you give more details?  Did you observe that anywhere, or are you inferring that from the code somewhere?

2021-03-04 15:57 UTC, jonathan-gibbons commented
/contributor add jonathan-gibbons

2021-03-04 16:10 UTC, pavelrappo commented
> > This commit changes the order of block tags in the output. The fact that no tests failed when I ran them surprised me. I think we should both fix that order and introduce a test for it.
> 
> Can you give more details? Did you observe that anywhere, or are you inferring that from the code somewhere?

I saw that difference in the produced documentation for JDK. I suggest you build documentation for "before" and "after", each time with the `-notimestamp` option, and compare them; you should see what I saw.

2021-03-04 16:14 UTC, jonathan-gibbons commented
/contributor add @jonathan-gibbons

2021-03-04 16:25 UTC, jonathan-gibbons commented
> > > This commit changes the order of block tags in the output. The fact that no tests failed when I ran them surprised me. I think we should both fix that order and introduce a test for it.
> > 
> > 
> > Can you give more details? Did you observe that anywhere, or are you inferring that from the code somewhere?
> 
> I saw that difference in the produced documentation for JDK. I suggest you build documentation for "before" and "after", each time with the `-notimestamp` option, and compare them; you should see what I saw.

Wow. Good catch! That was unexpected! Will investigate!

2021-03-05 10:20 UTC, pavelrappo approved these changes
I can see that you propose to add a test for the output order of block tags separately: https://git.openjdk.java.net/jdk/pull/2835 (JDK-8263043).

Looks good.

2021-03-05 15:24 UTC, jonathan-gibbons commented
/integrate

2021-03-05 15:24 UTC, closed without merging