8263041: Shenandoah: Cleanup C1 keep alive barrier check
openjdk/jdk pull request #2834
Opened 2021-03-04 19:23 UTC by zhengyu123

Please review this cleanup. It appears that JDK-8233339 missed C1 change.

Test:
- [x] hotspot_gc_shenandoah

2021-03-05 12:00 UTC, shipilev requested changes

2021-03-05 12:00 UTC, shipilev commented on src/hotspot/share/gc/shenandoah/c1/shenandoahBarrierSetC1.cpp
> +  if (ShenandoahSATBBarrier && ShenandoahBarrierSet::need_keep_alive_barrier(decorators, type)) {
I wonder if it is actually valid to check for SATB barrier here. `ShenandoahBarrierSetC2::load_at_resolved` only does `need_keep_alive_barrier` check.

2021-03-08 16:00 UTC, shipilev approved these changes
Looks good, minor nit.

2021-03-08 16:00 UTC, shipilev commented on src/hotspot/share/gc/shenandoah/c2/shenandoahBarrierSetC2.cpp
> +  // 3: apply keep-alive barrier for java.lang.ref.Reference if needed
"For java.lang.ref.Reference"?

I think BarrierSetC2 comment if pretty generic, so we might want to match it.

2021-03-08 16:36 UTC, rkennke approved these changes
Looks good!

2021-03-08 18:07 UTC, zhengyu123 commented
/integrate

2021-03-08 18:07 UTC, closed without merging