8263131: reduce unnecessary downwards search when using linear search to find method
openjdk/jdk pull request #2857
Opened 2021-03-06 14:38 UTC by lhtin

Hi,

The `InstanceKlass::find_method_by_name` and `InstanceKlass::find_method_index` use `InstanceKlass::quick_search` to find a method by name. If the method found doesn't match the expected method signature, It has to search downwards and upwards. But if `_disable_method_binary_search` was set to `true`, the `InstanceKlass::quick_search` will use linear search instead of binary search to find the method. So there no needs to search downwards because there no other method with the same name before it since the method found is the first matched method.

Best regards,
Lehua

2021-03-06 14:41 UTC, lhtin commented
/label hotspot-runtime

2021-03-06 14:43 UTC, lhtin commented
/label remove hotspot

2021-03-08 06:21 UTC, iklam reviewed
_disable_method_binary_search is used only when dumping a CDS archive. Have you run all the test cases under test/hotspot/jtreg/runtime/cds?

2021-03-08 10:34 UTC, lhtin commented
@iklam Thank you for your review. `jtreg:hotspot_cds` tests were passed with macosx-x86_64-server-{release, fastdebug, slowdebug} on my machine. Is there other tests or platform I have to run? Or any standard test platform I can use instead of my machine?

2021-03-08 19:29 UTC, iklam approved these changes

2021-03-08 19:29 UTC, iklam commented
> @iklam Thank you for your review. `jtreg:hotspot_cds` tests were passed with macosx-x86_64-server-{release, fastdebug, slowdebug} on my machine. Is there other tests or platform I have to run? Or any standard test platform I can use instead of my machine?

I think this should be enough. Thanks!

2021-03-08 20:41 UTC, iklam commented
> I would like to clarify your statement in the bug description that, "So there no needs to search downwards because there no other method with the same name before it since the method found is the first matched method." Actually there can be more than one entry in the array that contain the same name. Test case "TestConflictingDefaultsAndStaticMethod" in vmTestbase/vm/runtime/StaticMethodsTest.java test demonstrates a situation where an overpass method named "m" and a static method named "m" exist simultaneously in the array. See JDK-8067480 for a full explanation.
> 
> So I am concerned that we should never disable the downwards binary search through overloaded methods. Can you please run the test cases under test/hotspot/jtreg/vmTestbase/vm/runtime/defmeth?
> 
> Thanks,
> Lois

Hmm, I changed my mind about this PR. I think it shouldn't be integrated. The method array is grouped by name. When _disable_method_binary_search is true, quick_search(name) always returns the lowest index of a method with that name, so the caller of quick_search doesn't need to search downwards.

However, as I mentioned in the bug report, _disable_method_binary_search is used only when dumping the CDS archive. The reason is this:

```
inline int InstanceKlass::quick_search(const Array<Method*>* methods, const Symbol* name) {
  if (_disable_method_binary_search) {
    assert(DynamicDumpSharedSpaces, "must be");
    // At the final stage of dynamic dumping, the methods array may not be sorted
    // by ascending addresses of their names, so we can't use binary search anymore.
    // However, methods with the same name are still laid out consecutively inside the
    // methods array, so let's look for the first one that matches.
    return linear_search(methods, name);
  }
```

Performance of InstanceKlass::find_method doesn't really matter during CDS dump, and we are already paying a performance penalty by doing a linear search. And if we go into the download search loop:

```
  const int hit = quick_search(methods, name);
  if (hit != -1) {
    ...
    // search downwards through overloaded methods
    int i;
    for (i = hit - 1; i >= 0; --i) {
        const Method* const m = methods->at(i);
        assert(m->is_method(), "must be method");
        if (m->name() != name) {
          break;   /// <<<<<<< HERE
        }
```

the loop will end on its first iteration. So this PR won't save that much time anyway.

Adding this extra check will slow down our main use case (when CDS is not dumping) where performance is important. It also makes the code harder to understand. So I think we shouldn't do it.

2021-03-08 20:49 UTC, iklam requested changes
As mentioned in my other comment, I withdraw my approval for this PR.

2021-03-09 02:42 UTC, lhtin commented
Thank you @lfoltan for your review and @iklam for more detail about the influence of the changes. I fully accept @iklam's views and decisions. I will close the PR.

2021-03-09 02:42 UTC, closed without merging