8263158: [TESTBUG] FAILED: runtime/cds/appcds/OldClassTest.java
openjdk/jdk pull request #2866
Opened 2021-03-08 06:05 UTC by kelthuzadx

runtime/cds/appcds/OldClassTest.java failed due to the following reason:

```
java.lang.IllegalAccessError: superinterface check failed: class OldClassTest (in unnamed module @0x28115522) cannot access class jdk.internal.org.objectweb.asm.Opcodes (in module java.base) because module java.base does not export jdk.internal.org.objectweb.asm to unnamed module @0x28115522
at java.base/java.lang.ClassLoader.defineClass1(Native Method)
at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1010)
at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:855)
at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:753)
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:676)
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:634)
at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
at java.base/java.lang.Class.forName0(Native Method)
at java.base/java.lang.Class.forName(Class.java:471)
at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:125)
at java.base/java.lang.Thread.run(Thread.java:831)
STATUS:Failed.`main' threw exception: java.lang.IllegalAccessError: superinterface check failed: class OldClassTest (in unnamed module @0x28115522) cannot access class jdk.internal.org.objectweb.asm.Opcodes (in module java.base) because module java.base does not export jdk.internal.org.objectweb.asm to unnamed module @0x28115522
```

This test case has failed on my machine for a long while, I don't see other reports on JBS nor PRs. Please let me know if I missed some stuff.

Thanks!
Yang

2021-03-08 06:23 UTC, dholmes-ora commented
Please see my comment in the bug report. This is really a jtreg execution issue, but it seems you can bypass the issue by using othervm mode explicitly in the test. However we don't want to do that for these tests and explicitly use driver mode to minimise the testing overhead. Running jtreg in agentvm mode, or using "make run-test" should solve the problem (and others).

Thanks,
David

2021-03-08 06:29 UTC, kelthuzadx commented
It confused me a bit. Thank you David to point out this!

2021-03-08 06:57 UTC, iklam approved these changes

2021-03-08 07:30 UTC, iklam commented
The fix is correct. `@run driver` should be used only for those tests that are known to be very simple and can work without any special modules settings. The test should be changed to `@run main/othervm` because it relies on the `@modules java.base/jdk.internal.org.objectweb.asm` setting.

Please see my comments in https://bugs.openjdk.java.net/browse/JDK-8263158 for details.

2021-03-08 07:48 UTC, kelthuzadx commented
Thanks @iklam for the investigation, it makes sense. 

As far as [I know](https://openjdk.java.net/jtreg/faq.html#4.29), `@run driver` is the same as `@run main` with the exception that any VM options specified on the command line will not be used when running the specified class. That's why I did this change. 

AgentVM and OtherVM are how jtreg starts the JVM(a brand new? or retrieve from the pool?), they should not affect this test. i.e. `@run main xxx` should also work for this test case.

2021-03-08 19:38 UTC, iklam commented
I think this qualifies as a "trivial change" under the HotSpot project rules. The changes can be integrated with just one reviewer.

2021-03-08 19:49 UTC, dcubed-ojdk commented
@iklam - It seems that @dholmes-ora has some concerns about this fix. We might
want to hold off on integrating until he has a chance to read your comments in the
bug report.

2021-03-08 21:34 UTC, iklam requested changes
Upon more investigation, we determined that the problem is in jtreg's handling of `@run driver` in `jtreg -othervm` mode. This should be fixed in the upcoming release of jtreg.

Since this issue affects not just OldClassTest.java, I don't recommend fixing this test case individually. Instead, I would recommend using `jtreg -agentvm` as a work around for now.

2021-03-09 06:17 UTC, iklam commented
> According to @iklam's suggestion, I can withdraw this PR. But I'm more confused than before..
> 
> I found the following [JTREG doc](https://openjdk.java.net/jtreg/faq.html#what-are-the-agentvm-and-othervm-modes) which says:
> 
> > In otherVM mode, jtreg will start a new JVM to perform each action (such as @compile, @run main, and so on) in a test. When the action has been completed, the JVM will exit, relying on the system to cleanup any resources that may have been in use by the action.
> 
> > In agentVM mode, jtreg will maintain a pool of available JVMs, grouped according to the VM options specified when the JVM was created. When jtreg needs to execute an action for a test, it will obtain a suitable JVM from the pool, or create a new one if necessary. jtreg will use that JVM, and when it has been completed, it will attempt to restore some well-known global values to a standard state (such as the system properties, standard IO streams, security manager, etc). If that cleanup is successful, depending on the VM options used to create the JVM, jtreg may put the JVM in the pool for later reuse. Otherwise, the JVM is allowed to exit.
> 
> In summary, otherVM starts a new JVM to perform actions such as `@compile` and `@run main` In agentVM mode, jtreg obtains a suitable JVM from the pool. So it looks whether agentVM or otherVM should not affect this test cast since it occurred due to missing `--add-opens` options.
> 
> Another [JTREG doc](https://openjdk.java.net/jtreg/faq.html#what-are-the-agentvm-and-othervm-modes) says:
> 
> > jtreg provides a variant of @run main that can be useful in such situations: @run driver. This is the same as @run main with the exception that any VM options specified on the command line will not be used when running the specified class.
> 
> This is actually what we want, so just using '@run main` looks enough for this test case?

In tiered testing, we run many tests with additional options that will significantly slow down execution. E.g., `jtreg -vmoption:-Xcomp`. 

The OldClassTest class is like a shell script. It builds the "Hello" class using ASM, and then launch a child process to do the real test. So it doesn't make sense to enable -Xcomp when running OldClassTest.

Our policy is to use `@run driver` for classes like OldClassTest. This improves test execution when complicated `-vmoptions` are used.

Changing the test to `@run main` will work around the jtreg bug, but this will slow down test execution. Since a new version of jtreg will be released soon, we shouldn't apply this work around.

2021-03-09 15:27 UTC, kelthuzadx commented
The explanation makes sense. This test case also passed using the latest jtreg without any changes, so I would like to withdraw this PR. Thank you all for taking your time to look at this.

2021-03-09 15:27 UTC, closed without merging