8198317: Enhance JavacTool.getTask for flexibility
openjdk/jdk pull request #2871
Opened 2021-03-08 11:21 UTC by lahodaj

This is a clone of https://github.com/openjdk/jdk/pull/1896, which got closed by Skara.

@lgxbslgx, please let me know if you would prefer to resubmit the PR yourself.

/contributor add lgxbslgx

2021-03-08 11:23 UTC, lahodaj commented
/contributor add @lgxbslgx

2021-03-09 01:24 UTC, liach commented on test/langtools/tools/javac/api/8198317/T8198317.java
> +public class T8198317 extends TestRunner{
formatting

2021-03-09 05:23 UTC, jonathan-gibbons requested changes

2021-03-09 05:23 UTC, jonathan-gibbons commented on test/langtools/tools/javac/api/8198317/T8198317.java
> +public class T8198317 extends TestRunner{
These days, it is considered bad form to base a test name on a bug number. It's better to come up with a meaningful name for the test.  That probably applies to the enclosing directory as well.

2021-03-15 09:22 UTC, lahodaj commented
/contributor add Guoxiong Li <lgxbslgx@gmail.com>

2021-04-06 05:19 UTC, lgxbslgx commented
@lahodaj It is good for me to continue the work in this PR. I will assist you if you need.

2021-04-22 09:48 UTC, lgxbslgx reviewed
The [original patch](https://github.com/openjdk/jdk/pull/1896) began at Dec 2020. About four months passed. Could somebody help me push this patch? Thanks a lot.

2021-04-22 09:48 UTC, lgxbslgx commented on test/langtools/tools/javac/api/TestContextLoggingOutput.java
> + * Copyright (c) 2020, Oracle and/or its affiliates. All rights reserved.
The copyright should be updated to 2021.

2021-04-28 10:38 UTC, jbf commented on src/jdk.compiler/share/classes/com/sun/tools/javac/api/JavacTool.java
> +            else if (out instanceof PrintWriter)
Can use instance of pattern matching

2021-04-28 10:49 UTC, jbf approved these changes
Looks good to me

2021-04-29 09:37 UTC, lahodaj commented
/integrate

2021-04-29 09:38 UTC, closed without merging