8263191: Consolidate ThreadInVMfromJavaNoAsyncException and ThreadBlockInVMWithDeadlockCheck with existing wrappers
openjdk/jdk pull request #2880
Opened 2021-03-08 19:33 UTC by pchilano

Hi,

Please review the following small patch. ThreadInVMfromJavaNoAsyncException is exactly the same as ThreadInVMfromJava except that in the destructor we avoid checking for asynchronous exceptions. Similarly ThreadBlockInVMWithDeadlockCheck is equal to ThreadBlockInVM except that in the destructor we might need to release a Mutex in case we need to stop for a safepoint or handshake.
We can consolidate these two wrappers with the existing ones to avoid code duplication and minimize the number of transition wrappers.

Tested in mach5 tiers 1-3.

Thanks,
Patricio

2021-03-09 01:38 UTC, coleenp approved these changes
Looks good!

2021-03-09 10:37 UTC, dholmes-ora approved these changes
Looks good Patricio!

Thanks,
David

2021-03-09 15:50 UTC, dcubed-ojdk requested changes
I think there are non-trivial differences between the old ThreadBlockInVM
and the new ThreadBlockInVM. Maybe I'm wrong, but they do not look
equivalent to me.

2021-03-09 15:50 UTC, dcubed-ojdk commented on src/hotspot/share/runtime/interfaceSupport.inline.hpp
> +  ThreadInVMfromJava(JavaThread* thread, bool check_async = true) : ThreadStateTransition(thread), _check_asyncs(check_async) {
Field is `_check_asyncs` and parameter is `check_async`.
Either add an `s` to the parameter or delete the `s` from the field.

2021-03-09 15:50 UTC, dcubed-ojdk commented on src/hotspot/share/runtime/interfaceSupport.inline.hpp
> +  ThreadBlockInVM(JavaThread* thread, Mutex** in_flight_mutex_addr = NULL)
The new ThreadBlockInVM is not equivalent to the old one.
The old one used `trans(_thread_in_vm, _thread_blocked)` which
asserted that the "from" state is equal to `_thread_in_vm`. This
new code does not do that. The trans() call also resulted in a
`SafepointMechanism::process_if_requested(thread);` call after
we transitioned the thread to `_thread_in_vm`+1 and before we
set the new thread state to `_thread_blocked`.

2021-03-09 15:50 UTC, dcubed-ojdk commented on src/hotspot/share/runtime/interfaceSupport.inline.hpp
>      thread->set_thread_state(_thread_blocked);
If you're going to set the thread_state directly here, I think you need
to keep the `OrderAccess::storestore()` call. However, this new ThreadBlockInVM
is also missing a `SafepointMechanism::process_if_requested(thread)` call that
happened before setting the `_thread_blocked` state.

2021-03-11 20:52 UTC, dcubed-ojdk commented
I think you're missing my point about the equivalence of the old ThreadBlockInVM()
and the new ThreadBlockInVM(). The old version did this in trans()/transition():

```
    // Change to transition state and ensure it is seen by the VM thread.
    thread->set_thread_state_fence((JavaThreadState)(from + 1));

    SafepointMechanism::process_if_requested(thread);
    thread->set_thread_state(to);
```

which means that when we were in (`_thread_blocked`+1) we did a
`process_if_requested(thread)` call before we changed the thread's
state to `_thread_blocked`. In the new code, we just got straight to
`_thread_blocked` without processing any pending request. I think the
only case that matters is that we won't process a pending handshake
request. As you say, a pending safepoint will be allowed to proceed
once we've reached `_thread_blocked`.

It could be that this change in behavior doesn't make any real difference,
but I want to be sure.

2021-03-11 20:53 UTC, dcubed-ojdk requested changes
Thanks for making the fixes you've done so far, but I still
have one nagging question...

2021-03-11 21:07 UTC, dcubed-ojdk approved these changes
Patricio and I have bounced this change in behavior back and forth
in Slack. I'm now convinced that it is a benign change in behavior.

2021-03-15 14:10 UTC, pchilano commented
Thanks @coleenp, @dholmes-ora and @dcubed-ojdk for the reviews!

2021-03-15 14:11 UTC, pchilano commented
/integrate

2021-03-15 14:12 UTC, closed without merging