8262351: Extra '0' in java.util.Formatter for '%012a' conversion with a sign character
openjdk/jdk pull request #2881
Opened 2021-03-08 21:25 UTC by igraves

This fixes a zero-adding issue observed in the hex float conversion.

2021-03-09 23:32 UTC, bchristi-git requested changes
This all looks fine - just update the copyright year in Formatter.java, please.

In my personal opinion, this behavior change does not rise to the level of needing a CSR, but since it is long-standing behavior, you might double-check with Joe.

2021-03-10 17:51 UTC, naotoj approved these changes
Looks good to me.
BTW apart from this issue, I just noticed that in the chart in the `Formatter` class spec, there are two spaces (two NBSPs) for the `extra space` flag:
```
 * <tr><th scope="row" style="vertical-align:top"> <code>'&nbsp;&nbsp;'</code>
 *     <td style="vertical-align:top"> <code>'&#92;u0020'</code>
 *     <td> Requires the output to include a single extra space
 *     (<code>'&#92;u0020'</code>) for non-negative values.
 *
 *     <p> If both the {@code '+'} and <code>'&nbsp;&nbsp;'</code> flags are given
 *     then an {@link IllegalFormatFlagsException} will be thrown.
 ```
 This might be fixed sometime.

2021-03-10 17:59 UTC, igraves commented
/csr

2021-03-10 18:04 UTC, bchristi-git approved these changes

2021-03-10 21:18 UTC, igraves commented
/integrate

2021-03-10 22:46 UTC, bchristi-git commented
/sponsor

2021-03-10 22:46 UTC, closed without merging