8262880: Add support for the NSS Key Log Format for SSL/TLS keys
openjdk/jdk pull request #2896
Opened 2021-03-09 17:18 UTC by SalusaSecondus

This is my implementation for [JDK-8262880](https://bugs.openjdk.java.net/browse/JDK-8262880) and enables creating of an SSL/TLS key log in the standardized [NSS Key Log Format](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/Key_Log_Format). This is supported by many TLS implementations and also by several parsers such as Wireshark. Supporting this will greatly ease in debugging TLS problems.

(Note: I am covered by the Amazon corporate contribution agreement).

2021-03-09 17:19 UTC, SalusaSecondus commented
/covered

2021-03-09 17:39 UTC, simonis commented
I can confirm that @SalusaSecondus is covered by the Amazon OCA.

2021-03-11 16:33 UTC, XueleiFan requested changes
It is not good practice to leave secret information in debug log. Also, please don't introduce new logger format, including file, into the SSLLogger. Instead please consider to make use of the feature of Java Logger if you want to write the log to files, or use special format.

2021-03-11 16:37 UTC, XueleiFan commented
/csr needed

2021-03-11 18:33 UTC, simonis commented
I'm happy to create a CSR for this issue once the exact details of the option format have been figured out.

2021-03-11 18:39 UTC, SalusaSecondus commented
I am not familiar with either the MSS or XSS log formats and would be interested to see them. The NSS format is a defacto industry standard and already supported by many libraries (both producers and consumers) and thus used widely in the security industry. Most other uses that I can find take this similar pattern of providing a file-name to the TLS logic and then getting key log (in this format) written to that file.

I agree completely that logging secret information is dangerous and should almost never be done. That is why it has to be explicitly enabled (unlike most of the other `javax.net.debug` options) and another reason it is no commingled with the other logging output.

2021-03-18 21:26 UTC, SalusaSecondus commented
@XueleiFan I'd really like to move this forward but I'm uncertain what changes you want me to make. This extra debugging information will be very valuable to those of us debugging Java TLS connections.

2021-03-19 12:45 UTC, seanjmullan commented
I am also not comfortable adding this feature to the JDK, especially since every build of the JDK would by default have this feature enabled. Logging sensitive information to log files is not good security practice (there are many references I could cite). I also think it would be too easy to accidentally leave the system property enabled or forget to remove the file.

2021-03-19 14:46 UTC, SalusaSecondus commented
I think that there might be some confusion around the sensitivity of the data being logged. The security impact of this data is almost identical to passing `-Djavax.net.debug=plaintext,packet` to the JVM. This existing setting logs all plaintext (as well as wire-data) to STDERR. The new feature I'm proposing just lets a second application decrypt the wire-data to access the plaintext, which results in the same level of exposed data. (As an improvement over the existing feature, it outputs the data in a standardized format so that it is easier to analyze rather than being in a Java-specific format and co-mingled with all other STDERR output.)

Similar to the existing feature, the data logged only impacts the exact connections that it is enabled for. (These are ephemeral session-specific secrets).

I hope that this helps to ease some concerns and help explain why this exact feature is present in so many existing applications (including OpenSSL, BoringSSL, WolfSSL, s2n, Mozilla, and Chrome, among others).  If you would like to try it with your current Chrome browser, just add ` --ssl-key-log-file=/path/to/chrome_keys.txt` to the command-line. For Firefox, I believe you need to set the `SSLKEYLOGFILE` environment variable to the name of the log-file.

2021-03-24 21:23 UTC, jnimeh commented
I agree with Bernd, an API gives us some more flexibility.  I like the functionality provided by a key logging feature, but an API-based approach is more appropriate for the platform, and it more closely resembles what OpenSSL and GnuTLS are doing with callback registration.

2021-05-19 23:26 UTC, closed without merging