Improvement: replace all String.equals("") usages with String.isEmpty()
openjdk/jdk pull request #29
Opened 2020-09-06 13:57 UTC by doom369

**isEmpty** is faster + has less byte code + easier to read. Benchmarks could be found [here](https://medium.com/javarevisited/micro-optimizations-in-java-string-equals-22be19fd8416).

2020-09-06 14:02 UTC, doom369 commented
/signed

2020-09-06 18:08 UTC, thatsIch commented
@doom369 jcheck requires an associated issue

2020-09-07 04:39 UTC, mrserb commented on src/demo/share/java2d/J2DBench/src/j2dbench/tests/iio/InputImageTests.java
> -            if (suffix == null || suffix.equals("")) {
This file intentionally maintains compatibility to jdk1.4, so equals("") should be used.

2020-09-07 04:39 UTC, mrserb commented on src/demo/share/java2d/J2DBench/src/j2dbench/tests/iio/OutputImageTests.java
> -            if (suffix == null || suffix.equals("")) {
This file intentionally maintains compatibility to jdk1.4, so equals("") should be used.

2020-09-09 07:57 UTC, doom369 commented
@mrserb hello. Thanks for the review. Any further actions required from me?

2020-09-09 20:21 UTC, kevinrushforth commented
Before this Enhancement can be formally reviewed, you will need a JBS bug ID. If you are already working with a Committer or Reviewer in the `jdk` project who has agreed to sponsor your change, they can file the Enhancement request. Otherwise, you can file it using the web interface at [bugreport.java.com](https://bugreport.java.com/). Once you have a JBS bug ID, you need to edit the PR title to include that bug ID (without the `JDK-`) replacing "Improvement". 

Since this PR cuts across many functional areas (each gray label represents a functional area), you should expect a longer review process, since someone from each functional area will need to look at the changes in their area (like @mrserb started to do for the `2d` area).

2020-09-10 08:47 UTC, doom369 commented
@kevinrushforth thanks. Done.

2020-09-10 10:40 UTC, AlanBateman commented
The code in java.base was updated to use String::isEmpty in JDK 12 (JDK-8215281). There was follow-up in JDK 13 to do the same in the java.desktop module (JDK-8223237). Changing the remaining usages make sense although I see that more more than half are in tests.

It would be good to hear from security-dev on the changes to the Apache Santuario code (in java.xml.crypto module) in case it would be better to contribute those upstream instead. Ditto for the Apache Xalan code (in the java.xml module) but it may be significantly forked already that it doesn't matter.

I assume you can use JDK-8215014 rather than creating a new issue.

2020-09-10 11:21 UTC, dholmes-ora commented
This should be broken up to deal with the files in different functional areas under different bugids and PRs. Otherwise the cross-posting to so many lists is prohibitive. Files in different areas need to be reviewed by different teams. Thank you.

2020-09-10 12:04 UTC, doom369 commented
I have in mind dozens of improvements all over the code like this one. I already did some further review and in most cases, those tiny changes go trough all codebase. I can create PR for every separate module, but in general, it would bring like multiply x5 the number of PRs in total. If you think it's a better way to go, no problem, I can do that.

2020-09-10 12:18 UTC, kevinrushforth commented
@dholmes-ora raises a good point. Hopefully there is a balance point between a dozen different bugs / pull requests each targeting one area and one bug / PR targeting a dozen separate areas. I don't have a good general rule to suggest. Maybe @AlanBateman or @jddarcy can offer some advice?

2020-09-10 13:53 UTC, dholmes-ora commented
14 cc'd mailing lists is unworkable. You need to be subscribed to lists to post, but even if you are a reply-all will be delayed due to all of the mails being held up for moderator approval due to:

" Too many recipients to the message"

I have a longer email coming once it gets through the moderator approval delay. :(

2020-09-10 16:38 UTC, JornVernee commented
Since one of the motivations for this change is micro benchmark performance, please add a benchmark to the JDKs micro benchmark suite as well. (see e.g. https://github.com/openjdk/jdk/tree/master/test/micro/org/openjdk/bench/java/lang).

Also, what testing has been done for these changes?

2020-09-10 23:28 UTC, jonathan-gibbons commented
> I have in mind dozens of improvements all over the code like this one. 

That sounds scary. Broad updates like these cause unnecessary churn in the codebase, and can make merging and back porting harder.  Changes should be discussed ahead of time with the appropriate teams.

2020-09-10 23:57 UTC, prrace requested changes
1) This is un-necessary churn.
2) I can't even be sure I am finding the ones in my area because there's so much here
3) The ones I can find have no need of whatever performance improvement this might bring.
I think this whole PR should be withdrawn, and there may an attempt at measuring the benefits of this for the various cases before submitting in appropriate smaller chunks. But I'll tell you now I don't see a need for the test updates you are making.

2020-09-11 07:15 UTC, doom369 commented
Ok, sorry for the distraction.

2020-09-11 07:15 UTC, closed without merging

2020-09-11 15:17 UTC, bradfordwetmore commented
Our local Santuario maintainer says:

In general, changes to Apache Santuario should also be made at Apache so we stay in sync.

2020-09-18 02:48 UTC, stuart-marks commented
Hi @doom369, I hope we didn't end up wasting too much of your time with this. I wanted to respond to a comment you made earlier in this PR,

> I have in mind dozens of improvements all over the code like this one.

It's hard to see, but as you discovered, the JDK has different groups of people maintaining different areas, and sometimes there are hidden constraints on those different areas, for example, to avoid divergence with upstream source bases. And as you discovered, sometimes those source bases might need to maintain compatibility with an older JDK ... so we don't want to update this code even though it's IN the JDK.

Those kind of constraints generally don't apply to code in the java.base module, since there's nothing upstream of it, and by definition it cannot depend on anything outside the JDK. Generally -- though there are exceptions -- we're more receptive to keeping stuff in java.base (and sometimes related modules close to the core) on the latest and greatest stuff. There are some constraints, however. There are some things we can't use too early during initialization of the JDK, such as lambdas. Also, there is some code lurking around that is sometimes executed by the boot JDK, which is typically one release behind. (This is definitely the case for tools like javac, but I think it might also apply to some things in base.)

Anyway, if you'd like to pursue some of these improvements, drop a note to core-libs-dev@openjdk and we can talk about it.

Thanks.

2020-09-18 11:05 UTC, doom369 commented
@stuart-marks thanks. Sure, I understand that maintaining OpenJDK is not a simple task. I thought as change is super simple without any side effects it can go through. But I was wrong. That's fine. I'll focus on `java.base` when I have some free time.