8252833: Correct "no comment" warnings from javadoc in java.smartcardio module
openjdk/jdk pull request #2930
Opened 2021-03-11 01:13 UTC by bradfordwetmore

Disable the "missing" target for java.smartcardio from doclint.

2021-03-11 01:17 UTC, bradfordwetmore commented
/label security

2021-03-11 01:21 UTC, irisclark approved these changes

2021-03-11 09:25 UTC, magicus approved these changes
Looks good to me.

2021-03-11 11:55 UTC, magicus commented
... however, this fix does not achieve what the bug report is asking for.

The patch here will modify flags to javac. The JBS issue talks about flags for javadoc.

2021-03-11 11:56 UTC, magicus requested changes
Revoking approval.

2021-03-11 14:53 UTC, RogerRiggs requested changes
Please assign a new bug and title to ignore/suppress the warnings.
The original issue 8252833 should be left open.  
Thanks

2021-03-12 00:32 UTC, bradfordwetmore commented
Closing, as it's unclear which approach should be taken.

2021-03-12 00:32 UTC, closed without merging