8263434: Dangling references after MethodComparator::methods_EMCP
openjdk/jdk pull request #2937
Opened 2021-03-11 11:02 UTC by shipilev

SonarCloud reports the following problem in MethodComparator::methods_EMCP:
 "Address of stack memory associated with local variable 's_new' is still referred to by the global variable '_s_new' upon returning to the caller. This will be a dangling reference"

Code inspection reveals the assignment to static variables is only needed to pass them to helper methods. So, while this is not a detectable bug (yet), it is still cleaner not to expose stack variables in globals.

Additional testing:
 - [x] Linux x86_64 fastdebug `tier1`
 - [x] Linux x86_64 fastdebug, `vmTestbase_nsk_jvmti`

2021-03-11 13:35 UTC, coleenp approved these changes
This is much cleaner! Thank you, and thank you SonarCloud.

2021-03-11 13:35 UTC, coleenp commented on src/hotspot/share/prims/methodComparator.cpp
> +bool MethodComparator::pool_constants_same(int cpi_old, int cpi_new, ConstantPool* old_cp, ConstantPool* new_cp) {
Can these be const?

2021-03-11 13:35 UTC, coleenp commented on src/hotspot/share/prims/methodComparator.cpp
> +                                 ConstantPool* old_cp,  ConstantPool* new_cp) {
Can these be const pointers too?

2021-03-11 13:36 UTC, coleenp commented
/label add serviceability-dev

2021-03-11 13:46 UTC, shipilev commented on src/hotspot/share/prims/methodComparator.cpp
> +                                 ConstantPool* old_cp,  ConstantPool* new_cp) {
Yes, they can. Sprinkled.

2021-03-11 13:46 UTC, shipilev commented on src/hotspot/share/prims/methodComparator.cpp
> +bool MethodComparator::pool_constants_same(int cpi_old, int cpi_new, ConstantPool* old_cp, ConstantPool* new_cp) {
Yes, they can. Sprinkled.

2021-03-11 13:46 UTC, shipilev commented
/reviewers 2

2021-03-11 15:21 UTC, dcubed-ojdk commented
Please make sure that you get a review from someone on the Serviceability team.

2021-03-17 01:40 UTC, sspitsyn requested changes
Aleksey,
Sorry for being late to the party.
This looks good to me.
One nit: unneeded extra '()' what came from the original code:
`     if ((old_cp->klass_at_noresolve(cpi_old) != new_cp->klass_at_noresolve(cpi_new)))`

Thanks,
Serguei

2021-03-17 06:32 UTC, shipilev commented
> One nit: unneeded extra '()' what came from the original code:
> ` if ((old_cp->klass_at_noresolve(cpi_old) != new_cp->klass_at_noresolve(cpi_new)))`

Sure, updated. Also updated copyrights.

2021-03-17 07:21 UTC, sspitsyn approved these changes

2021-03-17 10:57 UTC, shipilev commented
/integrate

2021-03-17 10:58 UTC, closed without merging