Fix Sonar warnings for GTestResultParser
openjdk/jdk pull request #2991
Opened 2021-03-13 22:13 UTC by alblue

As noted by https://sonarcloud.io/code?id=shipilev_jdk&selected=shipilev_jdk%3Atest%2Fhotspot%2Fjtreg%2Fgtest%2FGTestResultParser.java there are a few fixes that can be applied for the GTestResultParser:

* Avoiding nested 'try' statements
* Avoiding nested 'switch' statements
* Adding a break for each switch case to prevent accidental/unwanted fall-through
* Disabling ability to load from remote files when parsing XML files

2021-03-13 22:16 UTC, alblue commented
/label hotspot /cc @shipilev

2021-03-13 22:17 UTC, alblue commented
/label hotspot

2021-03-16 09:17 UTC, shipilev requested changes
Please change this PR synopsis to "8263659: Reflow GTestResultParser for better readability" to get this hooked properly. Also, enable testing, see "Pre-submit test status" in "Checks".

2021-03-16 09:17 UTC, shipilev commented on test/hotspot/jtreg/gtest/GTestResultParser.java
> +                    switch (xmlReader.getLocalName()) {
Let's write this as:

```
while (xmlReader.hasNext()) {
    int code = xmlReader.next();
    if (code == XMLStreamConstants.START_ELEMENT) {
        switch (xmlReader.getLocalName()) {
```

2021-03-18 15:46 UTC, alblue commented
One of the test jobs hasn't finished running according to the above, but has if you drill down into the check itself. Is that blocking this PR moving forwards? Should I try to re-run the checks?

2021-03-18 15:49 UTC, shipilev commented
I think all checks have passed: https://github.com/openjdk/jdk/pull/2991/checks.
We just need a test maintainer to ack the patch. @iignatev, want to to take a look?

2021-03-18 15:54 UTC, iignatev approved these changes
LGTM. @alblue, thanks for fixing that.

2021-03-18 15:57 UTC, shipilev approved these changes

2021-03-18 16:40 UTC, alblue commented
/integrate

2021-03-18 16:41 UTC, iignatev commented
/sponsor

2021-03-18 16:41 UTC, closed without merging