JDK-8263559: Add missing initializers to VM_PopulateDumpSharedSpace
openjdk/jdk pull request #2996
Opened 2021-03-14 06:30 UTC by tstuefe

Sonarcloud reports missing initializers in VM_PopulateDumpSharedSpace. I don't see how this could lead to an error, since these members are initialized later, but for cleanliness sake lets initialize them.

2021-03-14 18:53 UTC, kimbarrett reviewed
It seems like the later assignments to NULL should no longer be needed, and maybe just confuse things by making the reader wonder if they got assigned to something else at some point between construction and the assignments.

2021-03-14 23:14 UTC, iklam approved these changes
Looks good and trivial. Thanks for fixing this.

2021-03-14 23:17 UTC, iklam requested changes
Oops,  agree with Kim. The later assignments to NULL should be removed.

2021-03-15 07:20 UTC, tstuefe commented
Kim, Ioi, thanks. I removed the explicit NULL assignments.

Side note, I know VM_op::do_it() is supposed to run only once, and in straight succession from constructing the object, but I wonder if it would make sense to assert this.

2021-03-15 16:51 UTC, iklam approved these changes
LGTM

2021-03-15 20:51 UTC, coleenp approved these changes
LGTM!

2021-03-15 20:51 UTC, coleenp commented on src/hotspot/share/memory/metaspaceShared.cpp
>    { }
The { } should go on line 394, since { is always on the declaration line.

2021-03-15 23:20 UTC, kimbarrett approved these changes
Looks good.

2021-03-16 05:47 UTC, tstuefe commented
Thanks Coleen, Kim and Ioi!

@coleenp I moved the constructor braces up. 

/integrate

2021-03-16 05:48 UTC, closed without merging