Use the blessed modifier order in java.management/naming
openjdk/jdk pull request #3078
Opened 2021-03-18 18:26 UTC by alblue

As with #2993 changing the order of `final static` to `static final` for the `java.management`, `java.management.rmi` and `java.naming` modules.

2021-03-18 19:33 UTC, alblue commented
Would someone mind creating a bug for me? In addition, if it would help, we could create a parent bug for applying cleanups  and associate #2993 and #2991.

2021-03-19 10:20 UTC, alblue commented
@cl4es would you mind creating a parent task of something like "Source code cleanups" and then another sub task for this change please?

2021-03-19 11:01 UTC, cl4es commented
Created the subtask https://bugs.openjdk.java.net/browse/JDK-8263855 for this along with an umbrella RFE.

2021-03-19 13:08 UTC, alblue commented
Thanks @cl4es -- do I need to update the git commit message as well, or is updating the title of the PR sufficient? I recall you suggesting not to do amend/rebases previously.

2021-03-19 13:28 UTC, cl4es commented
No, the git commit messages here doesn't matter, the bots will use the PR name when merging into master. It's good form to use reasonably consistent commit messages as you add commits to a PR, but altering commit history is not necessary and might even be disruptive once a PR has been opened.

There's the /summary command you could use to add additional comments to the final commit, see https://wiki.openjdk.java.net/display/SKARA/Pull+Request+Commands#PullRequestCommands-/summary

2021-03-19 13:31 UTC, alblue commented
Thanks @cl4es will adjust my submissions appropriately in the future.

2021-03-19 14:10 UTC, cl4es requested changes
Overall good - found a few cases where the private modifier is in the wrong place that ought to be fixed as well.

2021-03-19 14:10 UTC, cl4es commented on src/java.naming/share/classes/com/sun/jndi/ldap/EventQueue.java
> +    static final private boolean debug = false;
Move private to the front?

2021-03-19 14:10 UTC, cl4es commented on src/java.naming/share/classes/com/sun/jndi/ldap/EventSupport.java
> +    static final private boolean debug = false;
Move private to the front?

2021-03-19 14:10 UTC, cl4es commented on src/java.naming/share/classes/com/sun/jndi/ldap/LdapSchemaCtx.java
> +    static final private class SchemaInfo {
Move private to the front?

2021-03-19 17:59 UTC, cl4es approved these changes

2021-03-19 20:58 UTC, alblue commented
/integrate

2021-03-22 12:13 UTC, AlekseiEfimov approved these changes
`java.naming` module changes look good to me.

2021-03-22 13:07 UTC, dfuch approved these changes

2021-03-22 13:37 UTC, cl4es commented
/sponsor

2021-03-22 13:38 UTC, closed without merging