8264634: CollectCLDClosure collects duplicated CLDs when dumping dynamic archive
openjdk/jdk pull request #3320
Opened 2021-04-02 08:15 UTC by kelthuzadx

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (/home/qingfeng.yy/openjdk16_so_warning/jdk/src/hotspot/share/classfile/classLoaderData.cpp:316), pid=68929, tid=68930
#  assert(_keep_alive > 0) failed: Invalid keep alive decrement count
#
# JRE version: OpenJDK Runtime Environment (17.0) (slowdebug build 17-internal+0-adhoc.qingfengyy.jdk)
# Java VM: OpenJDK 64-Bit Server VM (slowdebug 17-internal+0-adhoc.qingfengyy.jdk, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0x781087]  ClassLoaderData::dec_keep_alive()+0x31

Stack: [0x00007f1593072000,0x00007f1593173000],  sp=0x00007f1593171c00,  free space=1023k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [libjvm.so+0x781087]  ClassLoaderData::dec_keep_alive()+0x31
V  [libjvm.so+0xef19e7]  MetaspaceShared::link_and_cleanup_shared_classes(Thread*)+0x181
V  [libjvm.so+0x1260834]  JavaThread::invoke_shutdown_hooks()+0x46
V  [libjvm.so+0x12609e5]  Threads::destroy_vm()+0xe7
V  [libjvm.so+0xbb40ec]  jni_DestroyJavaVM_inner+0x91
V  [libjvm.so+0xbb4147]  jni_DestroyJavaVM+0x1f
C  [libjli.so+0x4b4f]  JavaMain+0xc61
C  [libjli.so+0xad93]  ThreadJavaMain+0x27
```
We observed VM crashed when dumping dynamic archive in a simple springboot application(See detailed content on JBS attachment). I did some investigations. In rare case, both of the following paths may be stepped on when dumping dynamic archive:

```
1. SIGINT
at java.lang.Shutdown.beforeHalt(java.base@17-internal/Native Method)
at java.lang.Shutdown.exit(java.base@17-internal/Shutdown.java:172)
- locked <0x00000007fef02040> (a java.lang.Class for java.lang.Shutdown)
at java.lang.Terminator$1.handle(java.base@17-internal/Terminator.java:51)
at jdk.internal.misc.Signal$1.run(java.base@17-internal/Signal.java:219)
at java.lang.Thread.run(java.base@17-internal/Thread.java:831)

2. Normal Exit
JavaThread::invoke_shutdown_hooks()+0x46
Threads::destroy_vm()+0xe7
jni_DestroyJavaVM_inner+0x91
jni_DestroyJavaVM+0x1f
JavaMain+0xc61
ThreadJavaMain+0x27
```

They would call MetaspaceShared::link_and_cleanup_shared_classes, and CollectCLDClosure collects duplicated CLDs into _loaded_cld, _keep_alive is decrementing twice, causing a negative _keep_alive.

Testing(linux_x64):
[+] test/hotspot/jtreg/runtime/cds
[+] test/hotspot/jtreg/gc

2021-04-02 21:55 UTC, yminqi reviewed
Hi, Yi
  The _loaded_cld is a global list, in this case it looks contain duplicated CLD in it. 
   The duplication could from the thread run shutdown hook.
   Could you try 
  if (!cld->is_unloading()) {
      cld->inc_keep_alive();
+     if (!_loaded_cld->contains(cld)) {
      _loaded_cld->append(cld);
+  }
    }
Please let us know if you can avoid the crash.

2021-04-03 01:42 UTC, iklam requested changes
The fix looks reasonable. If MetaspaceShared::link_and_cleanup_shared_classes may be called twice, it's better to isolate the loaded_cld for each invocation. Allocating it locally will also avoid any potential threading issues.

I have some requests for cleaning up the code.

2021-04-03 01:42 UTC, iklam commented on src/hotspot/share/memory/metaspaceShared.cpp
> +  loaded_cld.trunc_to(0);
There's no need for the trucate -- `loaded_cld` is locally allocated and will be freed after this function returns.

Also, to improve modularity, I think we should move the dec_keep_alive loop into the destructor of CollectCLDClosure.

Also, `loaded_cld` can be moved as a field into CollectCLDClosure.

2021-04-03 01:42 UTC, iklam commented on src/hotspot/share/memory/metaspaceShared.cpp
> +  CollectCLDClosure collect_cld(&loaded_cld);
I think we should add a comment to say why it's necessary to first collect the ClassLoaderDatas first:

```
// ClassLoaderDataGraph::loaded_cld_do requires ClassLoaderDataGraph_lock.
// We cannot link the classes while holding this lock (or else we may run into deadlock).
// Therefore, we need to first collect all the CLDs, and then link their classes after
// releasing the lock.
```

2021-04-05 03:45 UTC, kelthuzadx commented
> Hi, Yi
> The _loaded_cld is a global list, in this case it looks contain duplicated CLD in it.
> The duplication could from the thread run shutdown hook.
> Could you try
> if (!cld->is_unloading()) {
> cld->inc_keep_alive();
> `+` if (!_loaded_cld->contains(cld)) {
> _loaded_cld->append(cld);
> `+` }
> }
> Please let us know if you can avoid the crash.

Hi Yumin, this fix still crashes because the CLDs collected at the first invocation of MetaspaceShared::link_and_cleanup_shared_classes are not cleaned, they will decrement their _keep_alives as before at the second invocation of MetaspaceShared::link_and_cleanup_shared_classes.

2021-04-05 04:30 UTC, kelthuzadx commented
Hi Ioi,

> Also, to improve modularity, I think we should move the dec_keep_alive loop into the destructor of CollectCLDClosure.
> Also, loaded_cld can be moved as a field into CollectCLDClosure.

Suggestions make sense, changed. Tests under runtime/cds/ are all passed with slowdebug mode.

2021-04-05 04:43 UTC, iklam approved these changes

2021-04-05 15:35 UTC, yminqi approved these changes
Make the CLD list local is a reasonable solution. LGTM.

2021-04-06 02:09 UTC, kelthuzadx commented
Thanks @yminqi @iklam for the reviews!

/integreate

2021-04-06 02:10 UTC, kelthuzadx commented
/integrate

2021-04-06 02:57 UTC, yminqi commented
/sponsor

2021-04-06 02:58 UTC, closed without merging