8264682: MemProfiling does not own Heap_lock when using G1
openjdk/jdk pull request #3340
Opened 2021-04-05 07:34 UTC by kelthuzadx

Trivial fix for JDK-8264682.

`Universe::heap()->used()` calls G1Allocator::used_in_alloc_regions() when G1 enabled,  it checks whether Heap_lock was owned on this thread's behalf.

/label add hotspot-gc
/label add hotspot-runtime

2021-04-05 07:39 UTC, kelthuzadx commented
/label add hotspot-runtime

2021-04-05 14:29 UTC, kimbarrett commented
> Trivial fix for JDK-8264682.

No, not trivial at all.  Dropping a GC-specific blob like this into shared code is highly questionable.  I'm not sure how this issue should be addressed, but I don't think the proposed change is the right approach.

2021-04-05 22:44 UTC, iklam commented
> > Trivial fix for JDK-8264682.
> 
> No, not trivial at all. Dropping a GC-specific blob like this into shared code is highly questionable. I'm not sure how this issue should be addressed, but I don't think the proposed change is the right approach.

It looks like the following APIs can be reliably called without holding the Heap_lock. However, I am not sure if they would give the same result. I.e., can you get  `Universe::heap()->unused()` by calling `Universe::heap()->capacity() - Universe::heap()->unused()`.

```
JVM_ENTRY_NO_ENV(jlong, JVM_TotalMemory(void))
  size_t n = Universe::heap()->capacity();
  return convert_size_t_to_jlong(n);
JVM_END

JVM_ENTRY_NO_ENV(jlong, JVM_FreeMemory(void))
  size_t n = Universe::heap()->unused();
  return convert_size_t_to_jlong(n);
JVM_END
```

2021-04-06 02:04 UTC, dholmes-ora requested changes
Sorry but I have to agree with Kim that this is the wrong fix for this problem.

And the test needs adjusting.

Thanks,
David

2021-04-06 02:04 UTC, dholmes-ora commented on test/hotspot/jtreg/runtime/MemProfiler/MemProfilingWithGC.java
> +            "UseEpsilonGC",
You have to allow for the fact that these GC's may not have all been built into the JVM under test.

2021-04-06 02:04 UTC, dholmes-ora commented on src/hotspot/share/runtime/memprofiler.cpp
> +    G1GC_ONLY(MutexLocker ml(Heap_lock);)
This seems really out of place - this code should not need to know anything about the specific locking requirements of different GC's. That should be handled inside the appropriate chunk of GC code.

2021-04-06 14:31 UTC, coleenp commented
Unless we can imagine a reason why this code is needed, I think the old memprofiler should be removed.

2021-04-07 09:33 UTC, kelthuzadx commented
I'd like to propose a new PR to remove the memprofiler if there are no strong objections.

2021-04-07 13:01 UTC, coleenp commented
Sure, open a new issue if you want, and link this issue to it.
The "feature" was added here:

^As 00018/00000/00000
^Ad D 1.1 98/04/14 13:18:32 renes 1 0
^Ac date and time created 98/04/14 13:18:32 by renes
^Ae

2021-04-09 07:14 UTC, closed without merging