8253594: Remove CollectedHeap::supports_tlab_allocation
openjdk/jdk pull request #335
Opened 2020-09-24 11:06 UTC by stefank

CollectedHeap::supports_tlab_allocation always returns true, and is only used in an assert. I propose that we remove it.

GenCollectedHeap is the only implementation that didn't trivially return true. Instead it deferred the question to the young gen, which after the CMS removal is only DefNew. I updated the GenCollectedHeap tlab functions to assert that the young gen always supports TLABs. This could be taken even further, and the Generation::supports_tlab_allocation() function could be entierly removed, but that requires that we change GenCollectedHeap to be explicit about the types for _young_gen and _old_gen. So, I left  that part for another day.

2020-09-24 11:06 UTC, stefank commented
/label hotspot-gc

2020-09-24 11:38 UTC, kstefanj requested changes
Nice cleanup, looks good.

2020-09-24 11:55 UTC, pliden approved these changes
Looks good!

2020-09-24 11:59 UTC, kstefanj approved these changes

2020-09-24 12:54 UTC, stefank commented
Thanks @pliden and @kstefanj for reviewing.

2020-09-25 09:10 UTC, stefank commented
/integrate

2020-09-25 09:12 UTC, closed without merging