8264957: Type::dual_type array is not aligned with enum TYPES
openjdk/jdk pull request #3410
Opened 2021-04-09 10:04 UTC by XiaohongGong

This is a bug fix for [1] which adds a new vector mask type. The new added TYPE `"VectorMask"` is inserted into `enum TYPES`, while the array `"Type::dual_type"` is not updated. This makes the array elements are not aligned with TYPES.

I met the following crash due to this issue when I was working on the masking feature support on panama-vector:
```
 Internal Error (/home/xiagon01/code/panama-vector/src/hotspot/share/opto/type.hpp:1727), pid=104432, tid=104449
 # assert(_base >= AnyPtr && _base <= KlassPtr) failed: Not a pointer
```
Adding a value like other vector types for the `"VectorMask"` in the array `"dual_type"` can fix it.

[1] https://bugs.openjdk.java.net/browse/JDK-8262355

Tested with tier1 and jdk:tier3

2021-04-09 11:02 UTC, DamonFool approved these changes
This sounds reasonable to me.
Thanks.

2021-04-09 11:46 UTC, neliasso requested changes
Could you please add an assert so that we don't make this mistake again.

2021-04-12 09:27 UTC, XiaohongGong commented
Thanks for your review @DamonFool @neliasso ! It seems the array `Type::dual_type` is not used anywhere currently. The same definition for `dual_type` is defined in https://github.com/openjdk/jdk/blob/master/src/hotspot/share/opto/type.hpp#L140 and used in type.cpp, which uses `Type::dual_type` before. So I think the whole definition can be totally removed. The issue I met might not be related to it. I will have a test and remove it if everything works well. Thanks!

2021-04-13 06:36 UTC, XiaohongGong commented
Hi, the array `Type:;dual_type` is totally removed. Tested `hotspot:hotspot_all_no_apps, langtools:tier1, jdk:jdk_core and jdk:tier3` internally. Would you mind having a look at it again @DamonFool @neliasso ? Thanks so much!

2021-04-13 06:59 UTC, DamonFool commented
I didn't find the usage of that array either.
So the change looks fine to me.

I'm afraid the JBS needs to be updated as a cleanup issue.
Thanks.

2021-04-13 07:03 UTC, XiaohongGong commented
> I didn't find the usage of that array either.
> So the change looks fine to me.
> 
> I'm afraid the JBS needs to be updated as a cleanup issue.
> Thanks.

Seems reasonable. I will update the JBS and the PR title. Thanks!

2021-04-13 07:28 UTC, DamonFool approved these changes
Thanks for your update.

2021-04-13 07:35 UTC, TobiHartmann approved these changes
Looks good to me.

2021-04-13 07:37 UTC, XiaohongGong commented
Thanks for the review @DamonFool @TobiHartmann !

2021-04-13 07:41 UTC, neliasso approved these changes

2021-04-13 07:42 UTC, XiaohongGong commented
Thanks for the review @neliasso !

2021-04-13 09:44 UTC, XiaohongGong commented
/integrate

2021-04-13 09:57 UTC, nsjian commented
/sponsor

2021-04-13 09:58 UTC, closed without merging