8263006: Add optimization for Max(*)Node and Min(*)Node
openjdk/jdk pull request #3513
Opened 2021-04-15 11:32 UTC by Wanghuang-Huawei

* I optimize `max` and `min` by using these identities 
    - op (max(a,b) , min(a,b))=== op(a,b)
    - if op is commutable
    - example : 
      - max(a,b) + min(a,b))=== a + b // op = add
      - max(a,b) * min(a,b))=== a * b  // op = mul
      -  max( max(a,b) , min(a,b)))=== max(a,b) // op = max()
      - min( max(a,b) , min(a,b)))=== max(a,b) // op = min()
* Test case 
  ```java
  /*
   * Copyright (c) 2021, Huawei Technologies Co. Ltd. All rights reserved.
   * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
   *
   * This code is free software; you can redistribute it and/or modify it
   * under the terms of the GNU General Public License version 2 only, as
   * published by the Free Software Foundation.
   *
   * This code is distributed in the hope that it will be useful, but WITHOUT
   * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
   * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
   * version 2 for more details (a copy is included in the LICENSE file that
   * accompanied this code).
   *
   * You should have received a copy of the GNU General Public License version
   * 2 along with this work; if not, write to the Free Software Foundation,
   * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
   *
   * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
   * or visit www.oracle.com if you need additional information or have any
   * questions.
   */
  package org.sample;
  
  import org.openjdk.jmh.annotations.Benchmark;
  import org.openjdk.jmh.annotations.*;
  
  import java.util.Random;
  import java.util.concurrent.TimeUnit;
  import org.openjdk.jmh.infra.Blackhole;
  
  @BenchmarkMode({Mode.AverageTime})
  @OutputTimeUnit(TimeUnit.MICROSECONDS)
  public class MyBenchmark {
  
      static int length = 100000;
      static double[] data1 = new double[length];
      static double[] data2 = new double[length];
      static Random random = new Random();
  
      static {
          for(int i = 0; i < length; ++i) {
            data1[i] = random.nextDouble();
            data2[i] = random.nextDouble();
          }
      }
  
      @Benchmark
      public void testAdd(Blackhole bh) {
        double sum = 0;
        for (int i = 0; i < length; i++) {
            sum += Math.max(data1[i], data2[i]) + Math.min(data1[i], data2[i]);
        }
        bh.consume(sum);
      }
  
      @Benchmark
      public void testMax(Blackhole bh) {
          double sum = 0;
          for (int i = 0; i < length; i++) {
              sum += Math.max(Math.max(data1[i], data2[i]), Math.min(data1[i], data2[i]));
          }
          bh.consume(sum);
      }
  
      @Benchmark
      public void testMin(Blackhole bh) {
          double sum = 0;
          for (int i = 0; i < length; i++) {
              sum += Math.min(Math.max(data1[i], data2[i]), Math.min(data1[i], data2[i]));
          }
          bh.consume(sum);
      }
  
  }
```
* The result is listed here:
  before:
  Benchmark                  Mode  Samples    Score  Score error  Units
  o.s.MyBenchmark.testAdd    avgt       10  556.048       32.368  us/op
  o.s.MyBenchmark.testMax    avgt       10  543.065       54.221  us/op
  o.s.MyBenchmark.testMin    avgt       10  570.731       37.630  us/op
  o.s.MyBenchmark.testMul    avgt       10  531.906       20.518  us/op
  after:
  Benchmark                  Mode  Samples    Score  Score error  Units
  o.s.MyBenchmark.testAdd    avgt       10  319.350        9.248  us/op
  o.s.MyBenchmark.testMax    avgt       10  356.138       10.736  us/op
  o.s.MyBenchmark.testMin    avgt       10  323.731       16.621  us/op
  o.s.MyBenchmark.testMul    avgt       10  338.458       23.755  us/op

2021-04-15 11:34 UTC, Wanghuang-Huawei commented
/contributor add Wang Huang <whuang@openjdk.org>
/contributor add Wu Yan <wuyan34@huawei.com>

2021-04-17 03:36 UTC, Wanghuang-Huawei commented
@vnkozlov Can you do me a favor to review this optimization? Thank you very much.

2021-04-17 05:55 UTC, vnkozlov commented
Do you have a real example in Java applications which benefit from this optimization?
We should not add and **support** code which would never be used in real world.

Optimization will not work for Integer because of `_min` and `_max` intrinsic which generates `cmove`:
https://github.com/openjdk/jdk/blob/master/src/hotspot/share/opto/library_call.cpp#L1806

I am not sure if this optimization will always work for float/double because of NaN values.

You need to verify results for all edge cases.

2021-04-17 06:38 UTC, Wanghuang-Huawei commented
Thank you for your review.
> Do you have a real example in Java applications which benefit from this optimization?
> We should not add and **support** code which would never be used in real world.
> 
Yes. We refined this optimization from our internal software experience. For instance, the model `min( max(a,b) , min(a,b)))` exists in many source codes in especial some AI project.
> Optimization will not work for Integer because of `_min` and `_max` intrinsic which generates `cmove`:
> https://github.com/openjdk/jdk/blob/master/src/hotspot/share/opto/library_call.cpp#L1806
> 
Yes. Adding `MaxINode`'s `max_opcode`  is just for `max_opcode` method is abstract. Our test cases is for float types only. 
> I am not sure if this optimization will always work for float/double because of NaN values.
> 
> You need to verify results for all edge cases.
I have tested that and showed in my comments. The test cases for NaN values and other special values are listed here 
```java
import java.lang.Math;

public class Test {

    public static void main(String[] args) throws Exception {
      Test m = new Test();
      m.test();
    }

    public void test() throws Exception {
      double[] num = new double[9];
      num[0] = 1; num[1] = 0; num[2] = -0;
      num[3] = Double.POSITIVE_INFINITY; 
      num[4] = Double.NEGATIVE_INFINITY;
      num[5] = Double.NaN;
      num[6] = Double.MAX_VALUE;
      num[7] = Double.MIN_VALUE;
      num[8] = Double.MIN_NORMAL;

      for(int i = 0; i < 9; i++) {
        for(int j = 0; j < 9; j++) {
          check(add_opt(num[i], num[j]), (num[i] + num[j]));
          check(mul_opt(num[i], num[j]), (num[i] * num[j]));
          check(max_opt(num[i], num[j]), Math.max(num[i], num[j]));
          check(min_opt(num[i], num[j]), Math.min(num[i], num[j]));
        } 
      }
    }

    public void check(double a, double b) {
      if (a != b) {
        System.out.println("false");
        System.out.println(a);
        System.out.println(b);
        System.out.println();
      }
    }

    public double add_opt(double a, double b) throws Exception {
      return Math.max(a, b) + Math.min(a, b);
    }

    public double mul_opt(double a, double b) throws Exception {
      return Math.max(a, b) * Math.min(a, b);
    }

    public double max_opt(double a, double b) throws Exception {
      return Math.max(Math.max(a, b), Math.min(a, b));
    }

    public double min_opt(double a, double b) throws Exception {
      return Math.min(Math.max(a, b), Math.min(a, b));
    }
}
```
The `NaN` is a special case. Because `NaN == NaN` is false in Java, so I run the case and check the result. 

Should I add the other test cases for `NaN` ?

2021-04-19 19:55 UTC, vnkozlov commented
Thank you for answers.
The test should be part of changes.

2021-04-21 23:00 UTC, mgkwill reviewed
Running MyBenchmark test listed in the summary on x86_64 Haswell XEON with this patch results in:

```
# Benchmark: org.sample.MyBenchmark.testMax

# Run progress: 25.00% complete, ETA 00:03:57
# Fork: 1 of 1                                                                                                                                                              # Warmup Iteration   1: 112.714 us/op
# Warmup Iteration   2: # To suppress the following error report, specify this argument
# after -XX: or in .hotspotrc:  SuppressErrorAt=/register.hpp:152                                                                                                           #
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (/home/mgkwill/src/git/jdk/src/hotspot/share/asm/register.hpp:152), pid=3450238, tid=3450253
#  assert(a != b && a != c && a != d && a != e && b != c && b != d && b != e && c != d && c != e && d != e) failed: registers must be different: a=0x0000000000000001, b=0x0000000000000001, c=0x0000000000000003, d=0x0000000000000004, e=0x0000000000000005
#
# JRE version: OpenJDK Runtime Environment (17.0) (slowdebug build 17-internal+0-adhoc.mgkwill.jdk) 
```

AND

```
# Benchmark: org.sample.MyBenchmark.testMin

# Run progress: 25.00% complete, ETA 00:03:57
# Fork: 1 of 1
# Warmup Iteration   1: 112.445 us/op
# Warmup Iteration   2: # To suppress the following error report, specify this argument
# after -XX: or in .hotspotrc:  SuppressErrorAt=/register.hpp:152
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (/home/mgkwill/src/git/jdk/src/hotspot/share/asm/register.hpp:152), pid=3450444, tid=3450481
#  assert(a != b && a != c && a != d && a != e && b != c && b != d && b != e && c != d && c != e && d != e) failed: registers must be different: a=0x0000000000000001, b=0x0000000000000001, c=0x0000000000000003, d=0x0000000000000004, e=0x0000000000000005
#
# JRE version: OpenJDK Runtime Environment (17.0) (slowdebug build 17-internal+0-adhoc.mgkwill.jdk)
```

Otherwise the results are below.
```Baseline
Benchmark            Mode  Cnt    Score     Error  Units
MyBenchmark.testAdd  avgt    5  149.581 ?  13.626  us/op
MyBenchmark.testMax  avgt    5  223.362 ? 195.007  us/op
MyBenchmark.testMin  avgt    5  206.096 ?  16.840  us/op
MyBenchmark.testMul  avgt    5  149.366 ?   9.558  us/op
Finished running test 'micro:MyBenchmark'```

```Benchmark            Mode  Cnt    Score   Error  Units
MyBenchmark.testAdd  avgt    5  107.874 ? 0.148  us/op
MyBenchmark.testMul  avgt    5  107.881 ? 0.015  us/op
Finished running test 'micro:MyBenchmark'```

2021-04-22 01:49 UTC, Wanghuang-Huawei commented
> Running MyBenchmark test listed in the summary on x86_64 Haswell XEON with this patch results in:
> 
> ```
> # Benchmark: org.sample.MyBenchmark.testMax
> 
> # Run progress: 25.00% complete, ETA 00:03:57
> # Fork: 1 of 1                                                                                                                                                              # Warmup Iteration   1: 112.714 us/op
> # Warmup Iteration   2: # To suppress the following error report, specify this argument
> # after -XX: or in .hotspotrc:  SuppressErrorAt=/register.hpp:152                                                                                                           #
> # A fatal error has been detected by the Java Runtime Environment:
> #
> #  Internal Error (/home/mgkwill/src/git/jdk/src/hotspot/share/asm/register.hpp:152), pid=3450238, tid=3450253
> #  assert(a != b && a != c && a != d && a != e && b != c && b != d && b != e && c != d && c != e && d != e) failed: registers must be different: a=0x0000000000000001, b=0x0000000000000001, c=0x0000000000000003, d=0x0000000000000004, e=0x0000000000000005
> #
> # JRE version: OpenJDK Runtime Environment (17.0) (slowdebug build 17-internal+0-adhoc.mgkwill.jdk) 
> ```
> 
> AND
> 
> ```
> # Benchmark: org.sample.MyBenchmark.testMin
> 
> # Run progress: 25.00% complete, ETA 00:03:57
> # Fork: 1 of 1
> # Warmup Iteration   1: 112.445 us/op
> # Warmup Iteration   2: # To suppress the following error report, specify this argument
> # after -XX: or in .hotspotrc:  SuppressErrorAt=/register.hpp:152
> #
> # A fatal error has been detected by the Java Runtime Environment:
> #
> #  Internal Error (/home/mgkwill/src/git/jdk/src/hotspot/share/asm/register.hpp:152), pid=3450444, tid=3450481
> #  assert(a != b && a != c && a != d && a != e && b != c && b != d && b != e && c != d && c != e && d != e) failed: registers must be different: a=0x0000000000000001, b=0x0000000000000001, c=0x0000000000000003, d=0x0000000000000004, e=0x0000000000000005
> #
> # JRE version: OpenJDK Runtime Environment (17.0) (slowdebug build 17-internal+0-adhoc.mgkwill.jdk)
> ```
> 
> Otherwise the results are below.
> 
> ```
> Baseline
> Benchmark            Mode  Cnt    Score     Error  Units
> MyBenchmark.testAdd  avgt    5  149.581 ?  13.626  us/op
> MyBenchmark.testMax  avgt    5  223.362 ? 195.007  us/op
> MyBenchmark.testMin  avgt    5  206.096 ?  16.840  us/op
> MyBenchmark.testMul  avgt    5  149.366 ?   9.558  us/op
> Finished running test 'micro:MyBenchmark'
> ```
> 
> ```
> Benchmark            Mode  Cnt    Score   Error  Units
> MyBenchmark.testAdd  avgt    5  107.874 ? 0.148  us/op
> MyBenchmark.testMul  avgt    5  107.881 ? 0.015  us/op
> Finished running test 'micro:MyBenchmark'
> ```



> MyBenchmark.testAdd  avgt    5  149.581 ?  13.626  us/op
> MyBenchmark.testMax  avgt    5  223.362 ? 195.007  us/op
> MyBenchmark.testMin  avgt    5  206.096 ?  16.840  us/op
> MyBenchmark.testMul  avgt    5  149.366 ?   9.558  us/op

I run this test case by `java -jar target/benchmarks.jar -i 10 -wi 10 -f 1 ``on `  Intel(R) Xeon(R) CPU E7-8890 v4 @ 2.20GHz` without crash. Can you give me your jvm options and this crash log? Thank you very much.

2021-04-22 02:15 UTC, mgkwill commented
> > Running MyBenchmark test listed in the summary on x86_64 Haswell XEON with this patch results in:
> > ```
> > # Benchmark: org.sample.MyBenchmark.testMax
> > 
> > # Run progress: 25.00% complete, ETA 00:03:57
> > # Fork: 1 of 1                                                                                                                                                              # Warmup Iteration   1: 112.714 us/op
> > # Warmup Iteration   2: # To suppress the following error report, specify this argument
> > # after -XX: or in .hotspotrc:  SuppressErrorAt=/register.hpp:152                                                                                                           #
> > # A fatal error has been detected by the Java Runtime Environment:
> > #
> > #  Internal Error (/home/mgkwill/src/git/jdk/src/hotspot/share/asm/register.hpp:152), pid=3450238, tid=3450253
> > #  assert(a != b && a != c && a != d && a != e && b != c && b != d && b != e && c != d && c != e && d != e) failed: registers must be different: a=0x0000000000000001, b=0x0000000000000001, c=0x0000000000000003, d=0x0000000000000004, e=0x0000000000000005
> > #
> > # JRE version: OpenJDK Runtime Environment (17.0) (slowdebug build 17-internal+0-adhoc.mgkwill.jdk) 
> > ```
> > 
> > 
> > AND
> > ```
> > # Benchmark: org.sample.MyBenchmark.testMin
> > 
> > # Run progress: 25.00% complete, ETA 00:03:57
> > # Fork: 1 of 1
> > # Warmup Iteration   1: 112.445 us/op
> > # Warmup Iteration   2: # To suppress the following error report, specify this argument
> > # after -XX: or in .hotspotrc:  SuppressErrorAt=/register.hpp:152
> > #
> > # A fatal error has been detected by the Java Runtime Environment:
> > #
> > #  Internal Error (/home/mgkwill/src/git/jdk/src/hotspot/share/asm/register.hpp:152), pid=3450444, tid=3450481
> > #  assert(a != b && a != c && a != d && a != e && b != c && b != d && b != e && c != d && c != e && d != e) failed: registers must be different: a=0x0000000000000001, b=0x0000000000000001, c=0x0000000000000003, d=0x0000000000000004, e=0x0000000000000005
> > #
> > # JRE version: OpenJDK Runtime Environment (17.0) (slowdebug build 17-internal+0-adhoc.mgkwill.jdk)
> > ```
> > 
> > 
> > Otherwise the results are below.
> > ```
> > Baseline
> > Benchmark            Mode  Cnt    Score     Error  Units
> > MyBenchmark.testAdd  avgt    5  149.581 ?  13.626  us/op
> > MyBenchmark.testMax  avgt    5  223.362 ? 195.007  us/op
> > MyBenchmark.testMin  avgt    5  206.096 ?  16.840  us/op
> > MyBenchmark.testMul  avgt    5  149.366 ?   9.558  us/op
> > Finished running test 'micro:MyBenchmark'
> > ```
> > 
> > 
> > ```
> > Benchmark            Mode  Cnt    Score   Error  Units
> > MyBenchmark.testAdd  avgt    5  107.874 ? 0.148  us/op
> > MyBenchmark.testMul  avgt    5  107.881 ? 0.015  us/op
> > Finished running test 'micro:MyBenchmark'
> > ```
> 
> > MyBenchmark.testAdd  avgt    5  149.581 ?  13.626  us/op
> > MyBenchmark.testMax  avgt    5  223.362 ? 195.007  us/op
> > MyBenchmark.testMin  avgt    5  206.096 ?  16.840  us/op
> > MyBenchmark.testMul  avgt    5  149.366 ?   9.558  us/op
> 
> I run this test case by `java -jar target/benchmarks.jar -i 10 -wi 10 -f 1 `on ` Intel(R) Xeon(R) CPU E7-8890 v4 @ 2.20GHz` without crash. Can you give me your jvm options and this crash log? Thank you very much.

Certainly. Tomorrow morning (my time) I will re-run with your command and test on a few other Xeons. I need to re-run to get crash logs (I'm jumping around between patches and cleaned already) but I will post those when I can recreate.

To run I copied MyBenchmark.java from summary to test/micro/org/openjdk/bench/vm/compiler/MyBenchmark.java
Command on running was:
`make test TEST="micro:MyBenchmark" MICRO="FORK=1;WARMUP_ITER=2;" CONF=linux-x86_64-server-slowdebug`

This worked on master, but on checkout of pr/3513 caused the errors above.

2021-04-22 02:35 UTC, Wanghuang-Huawei commented
> > > Running MyBenchmark test listed in the summary on x86_64 Haswell XEON with this patch results in:
> > > ```
> > > # Benchmark: org.sample.MyBenchmark.testMax
> > > 
> > > # Run progress: 25.00% complete, ETA 00:03:57
> > > # Fork: 1 of 1                                                                                                                                                              # Warmup Iteration   1: 112.714 us/op
> > > # Warmup Iteration   2: # To suppress the following error report, specify this argument
> > > # after -XX: or in .hotspotrc:  SuppressErrorAt=/register.hpp:152                                                                                                           #
> > > # A fatal error has been detected by the Java Runtime Environment:
> > > #
> > > #  Internal Error (/home/mgkwill/src/git/jdk/src/hotspot/share/asm/register.hpp:152), pid=3450238, tid=3450253
> > > #  assert(a != b && a != c && a != d && a != e && b != c && b != d && b != e && c != d && c != e && d != e) failed: registers must be different: a=0x0000000000000001, b=0x0000000000000001, c=0x0000000000000003, d=0x0000000000000004, e=0x0000000000000005
> > > #
> > > # JRE version: OpenJDK Runtime Environment (17.0) (slowdebug build 17-internal+0-adhoc.mgkwill.jdk) 
> > > ```
> > > 
> > > 
> > > AND
> > > ```
> > > # Benchmark: org.sample.MyBenchmark.testMin
> > > 
> > > # Run progress: 25.00% complete, ETA 00:03:57
> > > # Fork: 1 of 1
> > > # Warmup Iteration   1: 112.445 us/op
> > > # Warmup Iteration   2: # To suppress the following error report, specify this argument
> > > # after -XX: or in .hotspotrc:  SuppressErrorAt=/register.hpp:152
> > > #
> > > # A fatal error has been detected by the Java Runtime Environment:
> > > #
> > > #  Internal Error (/home/mgkwill/src/git/jdk/src/hotspot/share/asm/register.hpp:152), pid=3450444, tid=3450481
> > > #  assert(a != b && a != c && a != d && a != e && b != c && b != d && b != e && c != d && c != e && d != e) failed: registers must be different: a=0x0000000000000001, b=0x0000000000000001, c=0x0000000000000003, d=0x0000000000000004, e=0x0000000000000005
> > > #
> > > # JRE version: OpenJDK Runtime Environment (17.0) (slowdebug build 17-internal+0-adhoc.mgkwill.jdk)
> > > ```
> > > 
> > > 
> > > Otherwise the results are below.
> > > ```
> > > Baseline
> > > Benchmark            Mode  Cnt    Score     Error  Units
> > > MyBenchmark.testAdd  avgt    5  149.581 ?  13.626  us/op
> > > MyBenchmark.testMax  avgt    5  223.362 ? 195.007  us/op
> > > MyBenchmark.testMin  avgt    5  206.096 ?  16.840  us/op
> > > MyBenchmark.testMul  avgt    5  149.366 ?   9.558  us/op
> > > Finished running test 'micro:MyBenchmark'
> > > ```
> > > 
> > > 
> > > ```
> > > Benchmark            Mode  Cnt    Score   Error  Units
> > > MyBenchmark.testAdd  avgt    5  107.874 ? 0.148  us/op
> > > MyBenchmark.testMul  avgt    5  107.881 ? 0.015  us/op
> > > Finished running test 'micro:MyBenchmark'
> > > ```
> > 
> > 
> > > MyBenchmark.testAdd  avgt    5  149.581 ?  13.626  us/op
> > > MyBenchmark.testMax  avgt    5  223.362 ? 195.007  us/op
> > > MyBenchmark.testMin  avgt    5  206.096 ?  16.840  us/op
> > > MyBenchmark.testMul  avgt    5  149.366 ?   9.558  us/op
> > 
> > 
> > I run this test case by `java -jar target/benchmarks.jar -i 10 -wi 10 -f 1 `on ` Intel(R) Xeon(R) CPU E7-8890 v4 @ 2.20GHz` without crash. Can you give me your jvm options and this crash log? Thank you very much.
> 
> Certainly. Tomorrow morning (my time) I will re-run with your command and test on a few other Xeons. I need to re-run to get crash logs (I'm jumping around between patches and cleaned already) but I will post those when I can recreate.
> 
> To run I copied MyBenchmark.java from summary to test/micro/org/openjdk/bench/vm/compiler/MyBenchmark.java
> Command on running was:
> `make test TEST="micro:MyBenchmark" MICRO="FORK=1;WARMUP_ITER=2;" CONF=linux-x86_64-server-slowdebug`
> 
> This worked on master, but on checkout of pr/3513 caused the errors above.

Thank you very much. I will check this issue.

2021-04-23 03:01 UTC, Wanghuang-Huawei commented
> > > Running MyBenchmark test listed in the summary on x86_64 Haswell XEON with this patch results in:
> > > ```
> > > # Benchmark: org.sample.MyBenchmark.testMax
> > > 
> > > # Run progress: 25.00% complete, ETA 00:03:57
> > > # Fork: 1 of 1                                                                                                                                                              # Warmup Iteration   1: 112.714 us/op
> > > # Warmup Iteration   2: # To suppress the following error report, specify this argument
> > > # after -XX: or in .hotspotrc:  SuppressErrorAt=/register.hpp:152                                                                                                           #
> > > # A fatal error has been detected by the Java Runtime Environment:
> > > #
> > > #  Internal Error (/home/mgkwill/src/git/jdk/src/hotspot/share/asm/register.hpp:152), pid=3450238, tid=3450253
> > > #  assert(a != b && a != c && a != d && a != e && b != c && b != d && b != e && c != d && c != e && d != e) failed: registers must be different: a=0x0000000000000001, b=0x0000000000000001, c=0x0000000000000003, d=0x0000000000000004, e=0x0000000000000005
> > > #
> > > # JRE version: OpenJDK Runtime Environment (17.0) (slowdebug build 17-internal+0-adhoc.mgkwill.jdk) 
> > > ```
> > > 
> > > 
> > > AND
> > > ```
> > > # Benchmark: org.sample.MyBenchmark.testMin
> > > 
> > > # Run progress: 25.00% complete, ETA 00:03:57
> > > # Fork: 1 of 1
> > > # Warmup Iteration   1: 112.445 us/op
> > > # Warmup Iteration   2: # To suppress the following error report, specify this argument
> > > # after -XX: or in .hotspotrc:  SuppressErrorAt=/register.hpp:152
> > > #
> > > # A fatal error has been detected by the Java Runtime Environment:
> > > #
> > > #  Internal Error (/home/mgkwill/src/git/jdk/src/hotspot/share/asm/register.hpp:152), pid=3450444, tid=3450481
> > > #  assert(a != b && a != c && a != d && a != e && b != c && b != d && b != e && c != d && c != e && d != e) failed: registers must be different: a=0x0000000000000001, b=0x0000000000000001, c=0x0000000000000003, d=0x0000000000000004, e=0x0000000000000005
> > > #
> > > # JRE version: OpenJDK Runtime Environment (17.0) (slowdebug build 17-internal+0-adhoc.mgkwill.jdk)
> > > ```
> > > 
> > > 
> > > Otherwise the results are below.
> > > ```
> > > Baseline
> > > Benchmark            Mode  Cnt    Score     Error  Units
> > > MyBenchmark.testAdd  avgt    5  149.581 ?  13.626  us/op
> > > MyBenchmark.testMax  avgt    5  223.362 ? 195.007  us/op
> > > MyBenchmark.testMin  avgt    5  206.096 ?  16.840  us/op
> > > MyBenchmark.testMul  avgt    5  149.366 ?   9.558  us/op
> > > Finished running test 'micro:MyBenchmark'
> > > ```
> > > 
> > > 
> > > ```
> > > Benchmark            Mode  Cnt    Score   Error  Units
> > > MyBenchmark.testAdd  avgt    5  107.874 ? 0.148  us/op
> > > MyBenchmark.testMul  avgt    5  107.881 ? 0.015  us/op
> > > Finished running test 'micro:MyBenchmark'
> > > ```
> > 
> > 
> > > MyBenchmark.testAdd  avgt    5  149.581 ?  13.626  us/op
> > > MyBenchmark.testMax  avgt    5  223.362 ? 195.007  us/op
> > > MyBenchmark.testMin  avgt    5  206.096 ?  16.840  us/op
> > > MyBenchmark.testMul  avgt    5  149.366 ?   9.558  us/op
> > 
> > 
> > I run this test case by `java -jar target/benchmarks.jar -i 10 -wi 10 -f 1 `on ` Intel(R) Xeon(R) CPU E7-8890 v4 @ 2.20GHz` without crash. Can you give me your jvm options and this crash log? Thank you very much.
> 
> Certainly. Tomorrow morning (my time) I will re-run with your command and test on a few other Xeons. I need to re-run to get crash logs (I'm jumping around between patches and cleaned already) but I will post those when I can recreate.
> 
> To run I copied MyBenchmark.java from summary to test/micro/org/openjdk/bench/vm/compiler/MyBenchmark.java
> Command on running was:
> `make test TEST="micro:MyBenchmark" MICRO="FORK=1;WARMUP_ITER=2;" CONF=linux-x86_64-server-slowdebug`
> 
> This worked on master, but on checkout of pr/3513 caused the errors above.

I have tested on my ` Intel(R) Xeon(R) CPU E7-8890 v4 @ 2.20GHz`  on `make test TEST="micro:MyBenchmark" MICRO="FORK=1;WARMUP_ITER=2;" CONF=linux-x86_64-server-slowdebug`. It seems that all things are right?

2021-04-23 09:04 UTC, Wanghuang-Huawei commented
> Running MyBenchmark test listed in the summary on x86_64 Haswell XEON with this patch results in:
> 
> ```
> # Benchmark: org.sample.MyBenchmark.testMax
> 
> # Run progress: 25.00% complete, ETA 00:03:57
> # Fork: 1 of 1                                                                                                                                                              # Warmup Iteration   1: 112.714 us/op
> # Warmup Iteration   2: # To suppress the following error report, specify this argument
> # after -XX: or in .hotspotrc:  SuppressErrorAt=/register.hpp:152                                                                                                           #
> # A fatal error has been detected by the Java Runtime Environment:
> #
> #  Internal Error (/home/mgkwill/src/git/jdk/src/hotspot/share/asm/register.hpp:152), pid=3450238, tid=3450253
> #  assert(a != b && a != c && a != d && a != e && b != c && b != d && b != e && c != d && c != e && d != e) failed: registers must be different: a=0x0000000000000001, b=0x0000000000000001, c=0x0000000000000003, d=0x0000000000000004, e=0x0000000000000005
> #
> # JRE version: OpenJDK Runtime Environment (17.0) (slowdebug build 17-internal+0-adhoc.mgkwill.jdk) 
> ```
> 
> AND
> 
> ```
> # Benchmark: org.sample.MyBenchmark.testMin
> 
> # Run progress: 25.00% complete, ETA 00:03:57
> # Fork: 1 of 1
> # Warmup Iteration   1: 112.445 us/op
> # Warmup Iteration   2: # To suppress the following error report, specify this argument
> # after -XX: or in .hotspotrc:  SuppressErrorAt=/register.hpp:152
> #
> # A fatal error has been detected by the Java Runtime Environment:
> #
> #  Internal Error (/home/mgkwill/src/git/jdk/src/hotspot/share/asm/register.hpp:152), pid=3450444, tid=3450481
> #  assert(a != b && a != c && a != d && a != e && b != c && b != d && b != e && c != d && c != e && d != e) failed: registers must be different: a=0x0000000000000001, b=0x0000000000000001, c=0x0000000000000003, d=0x0000000000000004, e=0x0000000000000005
> #
> # JRE version: OpenJDK Runtime Environment (17.0) (slowdebug build 17-internal+0-adhoc.mgkwill.jdk)
> ```
> 
> Otherwise the results are below.
> 
> ```
> Baseline
> Benchmark            Mode  Cnt    Score     Error  Units
> MyBenchmark.testAdd  avgt    5  149.581 ?  13.626  us/op
> MyBenchmark.testMax  avgt    5  223.362 ? 195.007  us/op
> MyBenchmark.testMin  avgt    5  206.096 ?  16.840  us/op
> MyBenchmark.testMul  avgt    5  149.366 ?   9.558  us/op
> Finished running test 'micro:MyBenchmark'
> ```
> 
> ```
> Benchmark            Mode  Cnt    Score   Error  Units
> MyBenchmark.testAdd  avgt    5  107.874 ? 0.148  us/op
> MyBenchmark.testMul  avgt    5  107.881 ? 0.015  us/op
> Finished running test 'micro:MyBenchmark'
> ```

I fix a bug in my code. I am not sure if it is the reason of your crash. However, you can pull the latest code and test again. Thank you.

2021-04-23 19:42 UTC, mgkwill commented
> I fix a bug in my code. I am not sure if it is the reason of your crash. However, you can pull the latest code and test again. Thank you.

You update fixed the error I was seeing.

Perf numbers on Haswell Intel Xeon CPU E5-1603 v3 @ 2.80GHz:
```
Baseline
Benchmark            Mode  Cnt    Score     Error  Units
MyBenchmark.testAdd  avgt    5  149.581 ?  13.626  us/op
MyBenchmark.testMax  avgt    5  223.362 ? 195.007  us/op
MyBenchmark.testMin  avgt    5  206.096 ?  16.840  us/op
MyBenchmark.testMul  avgt    5  149.366 ?   9.558  us/op
Finished running test 'micro:MyBenchmark'
```
```
Patch
Benchmark            Mode  Cnt    Score   Error  Units
MyBenchmark.testAdd  avgt    5  109.432 ? 0.010  us/op
MyBenchmark.testMax  avgt    5  109.893 ? 0.072  us/op
MyBenchmark.testMin  avgt    5  109.500 ? 0.024  us/op
MyBenchmark.testMul  avgt    5  111.225 ? 0.013  us/op
```

2021-04-23 19:46 UTC, mgkwill requested changes
> Thank you for answers.
> The test should be part of changes.

I agree with @vnkozlov the jmh benchmark should be included in the changes and should be renamed to express what the benchmark is for.

2021-04-26 09:35 UTC, Wanghuang-Huawei commented
> > Thank you for answers.
> > The test should be part of changes.
> 
> I agree with @vnkozlov the jmh benchmark should be included in the changes and should be renamed to express what the benchmark is for.

Thank you for your review. I have added the benchmark. @vnkozlov @mgkwill

2021-05-11 06:23 UTC, Wanghuang-Huawei commented
Could you do me a favor to review the patch? @vnkozlov @mgkwill  Thank you.

2021-05-12 15:18 UTC, vnkozlov reviewed
Looks good. Thank you for adding tests.
I will run some testing before approval.

2021-05-12 23:25 UTC, vnkozlov approved these changes
t1-4 testing passed.

2021-05-13 01:28 UTC, Wanghuang-Huawei commented
/integrate

2021-05-13 01:31 UTC, Wanghuang-Huawei commented
> t1-4 testing passed.

Thank you for your review and approval!

2021-05-14 17:15 UTC, vnkozlov commented
/sponsor

2021-05-14 17:16 UTC, closed without merging

2026-07-20 09:07 UTC, eme64 commented on src/hotspot/share/opto/addnode.cpp
> +  }
I'm 5 years late to the party here: but why was this added to `commute`?
Should this not go into a separate method?

Just randomly spotted this when looking at `commute`, and it seems to me this is rather a separate optimization, not related to the commuting operations below.

2026-07-20 09:43 UTC, eme64 commented on src/hotspot/share/opto/addnode.cpp
> +  }
FYI: there is a similar optimization in `MulNode::Ideal` for mul instead of add.

2026-07-20 10:24 UTC, eme64 commented on src/hotspot/share/opto/addnode.cpp
> +  }
We should probably lift both optimizations into separate methods, maybe called `AddNode::Ideal_max_plus_min` and `MulNode::Ideal_max_times_min` or similar. And they could be executed just before the call to `commute`.

We also already have IR tests for this optimization in `(Add|Mul)(I|L)NodeIdealizationTests.java`.

2026-09-10 18:00 UTC, Wanghuang-Huawei commented on src/hotspot/share/opto/addnode.cpp
> +  }
Sorry for my delayed reply. My 2FA phone was broken, and it took me almost two months to recover access. :-(

I cannot recall why I placed this optimization inside `commute()`. I think your suggestion is spot on; this code should be refactored. I plan to look into this refactor once I wrap up my current work. Thank you for your advice.Do you have any other suggestions regarding this refactoring?

> We should probably lift both optimizations into separate methods, maybe called `AddNode::Ideal_max_plus_min` and `MulNode::Ideal_max_times_min` or similar. And they could be executed just before the call to `commute`.
> 
> We also already have IR tests for this optimization in `(Add|Mul)(I|L)NodeIdealizationTests.java`.

2026-09-21 07:41 UTC, chhagedorn commented on src/hotspot/share/opto/addnode.cpp
> +  }
Just FYI, @eme64 filed this here: [JDK-8389603](https://bugs.openjdk.org/browse/JDK-8389603).