8230664: Fix TestInstanceKlassSize for PowerPC
openjdk/jdk pull request #358
Opened 2020-09-25 13:13 UTC by jrziviani

TestInstanceKlassSize was failing because, for PowerPC, the following code (instanceKlass.cpp) always compiles to `return false;`
```
bool InstanceKlass::has_stored_fingerprint() const {
#if INCLUDE_AOT
  return should_store_fingerprint() || is_shared();
#else
  return false;
#endif
}
```
However, in `hasStoredFingerprint()@InstanceKlass.java` the condition `shouldStoreFingerprint() || isShared();` is always evaluated and may return true (_AFAIK isShared() returns true_). Such condition, adds 8 bytes in the `getSize()@InstanceKlass.java` causing the failure in TestInstanceKlassSize:
```
public long getSize() { // in number of bytes
  ...
  if (hasStoredFingerprint()) {
    size += 8; // uint64_t
  }
  return alignSize(size);
}
```
Considering these tests are failing for PowerPC only (_based on ProblemList.txt_), my solution checks if `hasStoredFingerprint()` is running on a PowerPC platform. I decided to go this way because there is no existing flag informing whether AOT is included or not and creating a new one just to handle the PowerPC case seems too much.

This patch is an attempt to fix https://bugs.openjdk.java.net/browse/JDK-8230664

2020-09-25 13:15 UTC, jrziviani commented
/covered

2020-09-29 20:03 UTC, plummercj requested changes
Can you please update the JBS issue to accurately describe what the underlying cause is. It incorreclty states that it is 8-byte vs 16-byte aligment.

I'd prefer that you added someting like VM.hasAOT(). This will fix the problem for other CPU ports that may be in a similar situation and also ensure correctness when configure a build with `--disable-aot`.

2020-09-29 20:56 UTC, jrziviani commented
@plummercj 
Thank you for your review!

> Can you please update the JBS issue to accurately describe what the underlying cause is. It incorreclty states that it is 8-byte vs 16-byte aligment.
Unfortunately, I don't have write access to the bug system. I'll check if the original reporter would mind to add it for me.

> I'd prefer that you added someting like VM.hasAOT(). This will fix the problem for other CPU ports that may be in a similar situation and also ensure correctness when configure a build with --disable-aot.
Sure, I'll work on it. I'll update this PR as soon as I finish the tests.

Thank you!

2020-09-30 22:12 UTC, jrziviani commented
@plummercj Hello! I implemented `hasAOT()` by using an existing variable in methodCounters that exists only if AOT is enabled.

**ppc64le**
```
==============================
Test summary
==============================
   TEST                                              TOTAL  PASS  FAIL ERROR   
   jtreg:test/hotspot/jtreg/serviceability/sa/TestInstanceKlassSize.java
                                                         1     1     0     0   
==============================
TEST SUCCESS

==============================
Test summary
==============================
   TEST                                              TOTAL  PASS  FAIL ERROR   
   jtreg:test/hotspot/jtreg/serviceability/sa/TestInstanceKlassSizeForInterface.java
                                                         1     1     0     0   
==============================
TEST SUCCESS
```
**x86-64**
```
==============================
Test summary
==============================
   TEST                                              TOTAL  PASS  FAIL ERROR   
   jtreg:test/hotspot/jtreg/serviceability/sa/TestInstanceKlassSize.java
                                                         1     1     0     0   
==============================
TEST SUCCESS

==============================
Test summary
==============================
   TEST                                              TOTAL  PASS  FAIL ERROR   
   jtreg:test/hotspot/jtreg/serviceability/sa/TestInstanceKlassSizeForInterface.java
                                                         1     1     0     0   
==============================
TEST SUCCESS```

2020-09-30 23:37 UTC, plummercj approved these changes
Changes look good.

2020-10-01 00:19 UTC, sspitsyn approved these changes
LGTM

2020-10-01 12:21 UTC, TheRealMDoerr commented
I think this fix deserves a new JBS issue. It doesn't resolve the rounding problem described in JDK-8230664. It fixes an additiona issue.

2020-10-01 14:01 UTC, jrziviani commented
> I think this fix deserves a new JBS issue. It doesn't resolve the rounding problem described in JDK-8230664. It fixes an additional issue. The rounding problem may reoccur when other class layout changes are done.

Totally agreed. But, would you mind to create the ticket for me, please? Then, I change the commit header/message.
Thank you!!

2020-10-01 14:58 UTC, TheRealMDoerr commented
Hi Jose,
here's your new bug: https://bugs.openjdk.java.net/browse/JDK-8253900

2020-10-01 15:02 UTC, plummercj commented
> I think this fix deserves a new JBS issue. It doesn't resolve the rounding problem described in JDK-8230664. It fixes an additional issue. The rounding problem may reoccur when other class layout changes are done.

Does it still need to be problem listed due to this issue? I guess it may or may not be an issue based on the current size InstanceKlass, so probably best to keep in problem listed.

2020-10-01 16:37 UTC, jrziviani commented
> If these tests are currently passing with Jose's fix, I suggest to comment them out in the problem list with a note that we may need to disable them again because of JDK-8230664.
> This way we can test the functionality Jose is fixing until then. And we'll see when the issue comes up again.

Done! Please, check if you're fine with this:
```
+# The solution to bug JDK-8253900 seems to fix tests TestInstanceKlassSize and
+# TestInstanceKlassSizeForInterface. However, while JDK-8230664 is not resolved,
+# these tests may be disabled again if necessary.
+# serviceability/sa/TestInstanceKlassSize.java 8230664 linux-ppc64le,linux-ppc64
+# serviceability/sa/TestInstanceKlassSizeForInterface.java 8230664 linux-ppc64le,linux-ppc64
```
Thank you Martin!

2020-10-01 19:22 UTC, plummercj commented
> > If these tests are currently passing with Jose's fix, I suggest to comment them out in the problem list with a note that we may need to disable them again because of JDK-8230664.
> > This way we can test the functionality Jose is fixing until then. And we'll see when the issue comes up again.
> 
> Done! Please, check if you're fine with this:
> 
> ```
> +# The solution to bug JDK-8253900 seems to fix tests TestInstanceKlassSize and
> +# TestInstanceKlassSizeForInterface. However, while JDK-8230664 is not resolved,
> +# these tests may be disabled again if necessary.
> +# serviceability/sa/TestInstanceKlassSize.java 8230664 linux-ppc64le,linux-ppc64
> +# serviceability/sa/TestInstanceKlassSizeForInterface.java 8230664 linux-ppc64le,linux-ppc64
> ```

I don't believe there are any other cases were we comment out a test in a problem list. I think it would be best just to remove it completely from ProblemList.txt. JDK-8230664 will still be filed. I suggest maybe adding a comment there saying that the test was removed from the problem list when JDK-8253900 was fixed, but should be re-added if JDK-8230664 starts to reproduce again.

2020-10-01 20:35 UTC, jrziviani commented
> ... I suggest maybe adding a comment there saying that the test was removed from the problem list when JDK-8253900 was fixed, but should be re-added if JDK-8230664 starts to reproduce again.

I like this idea because a simple `grep` will be enough to understand. Just pushed my branch, any issue just let me know.

Thank you Chris!

2020-10-01 21:47 UTC, plummercj commented
> > ... I suggest maybe adding a comment there saying that the test was removed from the problem list when JDK-8253900 was fixed, but should be re-added if JDK-8230664 starts to reproduce again.
> 
> I like this idea because a simple `grep` will be enough to understand what happened. Just pushed my branch, any issue just let me know.
> 
Hi Ziviani,

My suggestion was to put the comment in the CR. I really don't think there should be any comment in ProblemList.txt. This is not an uncommon situation. Tests are often removed from the problem list simply because they have not been seen for a while (and we want to determine if the bug is still an issue) or because failures are rare, or possibly even so hard to reproduce that we want to eventually trigger a failure as part of regular testing to help with failure analysis. We have not added comments in the past to document these problem list removals.

2020-10-02 02:10 UTC, jrziviani commented
> My suggestion was to put the comment in the CR. I really don't think there should be any comment in ProblemList.txt. This is not an uncommon situation. Tests are often removed from the problem list simply because they have not been seen for a while (and we want to determine if the bug is still an issue) or because failures are rare, or possibly even so hard to reproduce that we want to eventually trigger a failure as part of regular testing to help with failure analysis. We have not added comments in the past to document these problem list removals.

It's clear now. Sorry for the confusion. :-). I removed the tests from problemlist again and add a comment in my commit message. Any `git blame` will easily found it.

Hope I did it right now :-D

Thanks Chris!

2020-10-02 03:33 UTC, plummercj approved these changes
Looks good.

2020-10-02 04:46 UTC, sspitsyn approved these changes
LGTM

2020-10-02 09:50 UTC, TheRealMDoerr commented
Added comment to JDK-8230664. Test results look good on our side, too.

2020-10-05 21:07 UTC, jrziviani commented
/integrate

2020-10-09 12:55 UTC, TheRealMDoerr commented
/sponsor

2020-10-09 12:56 UTC, closed without merging