8265393: VM crashes if both -XX:+RecordDynamicDumpInfo and -XX:SharedArchiveFile options are specified
openjdk/jdk pull request #3599
Opened 2021-04-21 04:38 UTC by yminqi

Hi, Please review
  1) When the two flags -XX:+RecordDynamicDumpInfo and -XX:SharedArchiveFile used,  in
     Arguments::init_shared_archive_paths() :
          if (DynamicDumpSharedSpaces) {
            if (os::same_files(SharedArchiveFile, ArchiveClassesAtExit)) {
               ...
  ArchiveClassesAtExit is NULL.
  C++ does not have a defined behavior of strcmp with strings of NULL. Posix version of os::same_files(const char* file1, const char* file2) calls strcmp without checking input args. This should be same as it is treated on Windows.
  2) JCmdTest.java is fat and possible to cause test timeout. Split JCmdTest.java into two separate Tests: JCmdTestStaticDump.java and JCmdTestDynamicDump.java.
  3) Add a test to check run with -XX:+RecordDynamicDumpInfo and -XX:SharedArchiveFile in JCmdTestDynamicDump.java
       The test does not use utility to create jvm process  since it will take testing envs into process, but the way in the test using LingeredApp does not take envs.

  Tests: tier1,tier2,tier3,tier4

Thanks
Yumin

2021-04-21 05:19 UTC, iklam requested changes
There's duplicated code between JCmdTestDynamicDump.java and JCmdTestStaticDump.java. I think these should be moved to a common base class.

2021-04-22 16:32 UTC, calvinccheung requested changes
Looks good. I spotted some minor issues in the test code.

Thanks,
Calvin

2021-04-22 16:37 UTC, calvinccheung commented on test/hotspot/jtreg/runtime/cds/appcds/jcmd/JCmdTestDumpBase.java
> +import jdk.test.lib.cds.CDSTestUtils;
Extra import

2021-04-22 16:37 UTC, calvinccheung commented on test/hotspot/jtreg/runtime/cds/appcds/jcmd/JCmdTestDumpBase.java
> +import java.io.BufferedReader;
Extra import.

2021-04-22 16:37 UTC, calvinccheung commented on test/hotspot/jtreg/runtime/cds/appcds/jcmd/JCmdTestDumpBase.java
> +    private static final String BOOT_CLASSES[]    = {"Hello"};
Too many blank spaces before the '='.

2021-04-22 16:37 UTC, calvinccheung commented on test/hotspot/jtreg/runtime/cds/appcds/jcmd/JCmdTestDumpBase.java
> +        allJars = testJar+ File.pathSeparator + bootJar;
Need a blank space after `testJar`.

2021-04-22 16:37 UTC, calvinccheung commented on test/hotspot/jtreg/runtime/cds/appcds/jcmd/JCmdTestDynamicDump.java
> +import java.util.List;
Extra import.

2021-04-22 16:37 UTC, calvinccheung commented on test/hotspot/jtreg/runtime/cds/appcds/jcmd/JCmdTestDynamicDump.java
> +import jdk.test.lib.dcmd.PidJcmdExecutor;
Extra import.

2021-04-22 16:37 UTC, calvinccheung commented on test/hotspot/jtreg/runtime/cds/appcds/jcmd/JCmdTestDynamicDump.java
> +import java.io.BufferedReader;
Extra import.

2021-04-22 16:37 UTC, calvinccheung commented on test/hotspot/jtreg/runtime/cds/appcds/jcmd/JCmdTestStaticDump.java
> +import java.util.List;
Extra import.

2021-04-22 16:37 UTC, calvinccheung commented on test/hotspot/jtreg/runtime/cds/appcds/jcmd/JCmdTestStaticDump.java
> +import java.io.BufferedReader;
Extra import.

2021-04-22 16:38 UTC, calvinccheung commented on test/hotspot/jtreg/runtime/cds/appcds/jcmd/JCmdTestStaticDump.java
> +        final boolean EXPECT_FAIL = !EXPECT_PASS;
These are also used in JCmdTestDynamicDump. Maybe move them to JCmdTestDumpBase?

2021-04-22 18:51 UTC, calvinccheung approved these changes
LGTM.

2021-04-22 18:54 UTC, yminqi commented
> LGTM.

Thanks for review!

2021-04-23 21:20 UTC, iklam approved these changes
The latest code looks good to me.

2021-04-23 21:34 UTC, yminqi commented
@iklam Thanks for review.

2021-04-23 21:50 UTC, yminqi commented
/integrate

2021-04-23 21:51 UTC, closed without merging