8265757: stack-use-after-scope in perfMemory_posix.cpp get_user_name_slow()
openjdk/jdk pull request #3630
Opened 2021-04-22 15:09 UTC by hseigel

Please review this small change to fix JDK-8265757.  The fix was tested with Mach5 tiers 1 and 2 on Linux, MacOS aarch64, and Windows.

Thanks, Harold

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8265757](https://bugs.openjdk.java.net/browse/JDK-8265757): stack-use-after-scope in perfMemory_posix.cpp get_user_name_slow()

### Reviewers
 * [Lois Foltan](https://openjdk.java.net/census#lfoltan) (@lfoltan - **Reviewer**)
 * [Daniel D. Daugherty](https://openjdk.java.net/census#dcubed) (@dcubed-ojdk - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/3630/head:pull/3630` \
`$ git checkout pull/3630`

Update a local copy of the PR: \
`$ git checkout pull/3630` \
`$ git pull https://git.openjdk.java.net/jdk pull/3630/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3630`

View PR using the GUI difftool: \
`$ git pr show -t 3630`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/3630.diff">https://git.openjdk.java.net/jdk/pull/3630.diff</a>

</details>

2021-04-22 15:22 UTC, lfoltan approved these changes
LGTM.
Lois

2021-04-22 15:36 UTC, dcubed-ojdk approved these changes
Thumbs up.

2021-04-22 17:11 UTC, hseigel commented
Thanks Lois and Dan for the reviews.
Harold

2021-04-22 23:32 UTC, dholmes-ora requested changes

2021-04-22 23:32 UTC, dholmes-ora commented on src/hotspot/os/posix/perfMemory_posix.cpp
> +  char buffer[MAXPATHLEN + 1];
If you move this inside the #if defined(LINUX) it would be better. No risk of perturbing other platforms then.

2021-04-27 12:06 UTC, hseigel commented
Thanks Lois and Dan for reviewing this.

/integrate

2021-04-27 12:07 UTC, closed without merging