8234446: Post-CMS workgroup hierarchy cleanup
openjdk/jdk pull request #3663
Opened 2021-04-23 20:06 UTC by albertnetymk

Collapse workgroup hierarchy and some general cleanup.

Tested; hotspot_gc

2021-04-27 14:08 UTC, tschatzl requested changes
Mostly further cleanup suggestions.

2021-04-27 14:08 UTC, tschatzl commented on src/hotspot/share/gc/shared/workgroup.cpp
> +      _workers(NULL),
Pre-existing: the indentation is completely arbitrary here. Please use something like 2 spaces.

2021-04-27 14:08 UTC, tschatzl commented on src/hotspot/share/gc/shared/workgroup.hpp
> + private:
The `private` can be removed.

2021-04-27 14:08 UTC, tschatzl commented on src/hotspot/share/gc/shared/workerManager.hpp
> +  static uint add_workers (WorkGang* holder,
s/holder/workers

2021-04-27 14:08 UTC, tschatzl commented on src/hotspot/share/gc/shared/workerManager.hpp
> +  static void log_worker_creation(WorkGang* holder,
s/holder/workers

2021-04-29 09:11 UTC, albertnetymk commented
There is some preexisting inconsistency regarding the indentation of fields initializers in constructors, e.g. `SubTasksDone` uses 2-space, while `WorkGang` uses 4-space. In order not to make the review process unnecessarily harder, I have kept the original indentation, despite the inconsistency.

2021-04-29 10:41 UTC, tschatzl approved these changes

2021-05-03 10:53 UTC, rkennke approved these changes
Looks good to me. Thank you!

2021-05-03 11:44 UTC, albertnetymk commented
Thanks for the review.

/integrate

2021-05-03 11:45 UTC, closed without merging