8251123: doclint warnings about missing javadoc tags and comments
openjdk/jdk pull request #369
Opened 2020-09-25 21:45 UTC by mrserb

Bug: https://bugs.openjdk.java.net/browse/JDK-8251123
Fix: http://cr.openjdk.java.net/~serb/8251123/webrev.01

We have a number of missing javadoc tags and comments in the desktop module.
Most of the missing comments are related to the serialized form.

The fix:
  - Adds missing comments to the non-static/non-transient fields(even private) of the "serializable" classes
  - Adds comments to the "serializable" classes even if those classes are non-public
  - Fixes references/adds missing tags to the special methods(like readObject/writeObject)
  - Delete the PeerFixer class.

Note that in some cases I added the comments to the "implementation details", so I did not specify it fully.

The old review request:
https://mail.openjdk.java.net/pipermail/beans-dev/2020-August/000423.html

2020-09-25 21:55 UTC, mrserb commented
/csr

2020-09-28 06:30 UTC, jayathirthrao commented
Inputs from https://mail.openjdk.java.net/pipermail/beans-dev/2020-August/000424.html are incorporated or is this fresh git review?

2020-09-28 07:49 UTC, mrserb commented
> Inputs from https://mail.openjdk.java.net/pipermail/beans-dev/2020-August/000424.html are incorporated or is this fresh git review?

It is a fresh update, it changes from the old review request. I made it less "dangerous".

2020-09-30 06:11 UTC, jayathirthrao commented on src/java.desktop/share/classes/java/awt/Window.java
> +     */
More simpler way "Focus transfers should be synchronous for lightweight component requests"

2020-09-30 06:46 UTC, jayathirthrao approved these changes

2020-10-02 18:21 UTC, prrace commented on src/java.desktop/share/classes/javax/imageio/metadata/IIOMetadataNode.java
> + * "exceptional" circumstances.
"A" -> "An"

2020-10-02 18:31 UTC, prrace commented on src/java.desktop/share/classes/java/awt/ScrollPane.java
> - * In JDK 1.1.1, the pkg private class java.awt.PeerFixer was moved to
As I mentioned in the OLD review thread for hg, this definitely needs a CSR
and it needs to be called out.
I think it should be separated out from this fix which is about fixing doclint warnings but here you are making an incompatible change. Let's not mix the two.

2020-10-02 18:33 UTC, prrace commented on src/java.desktop/share/classes/java/awt/CheckboxMenuItem.java
>      private int checkboxMenuItemSerializedDataVersion = 1;
OK. Good this was being discussed in the old review and it should stay.

2020-10-02 18:34 UTC, prrace commented on src/java.desktop/share/classes/java/awt/ContainerOrderFocusTraversalPolicy.java
>      private final int BACKWARD_TRAVERSAL = 1;
I see you also reverted the change of these two to static so that is also good.

2020-10-02 18:35 UTC, prrace requested changes
I think the main thing here is I would separate out removing the duplicate PeerFixer into a new bug.

I also see that the CSR is still just a pure template.

2020-10-02 19:46 UTC, prrace commented
> I need advice about what exact change should be reviewed in the CSR(except PeerFixer removal)

Probably almost all of it.

2020-10-03 03:57 UTC, mrserb commented
The PeerFixer is extracted to the separate CR:
https://bugs.openjdk.java.net/browse/JDK-8253965
https://github.com/openjdk/jdk/pull/493

Other review comments fixed as well, CSR is in progress.

2020-10-03 04:45 UTC, mrserb commented
CSR is updated.

2020-10-03 19:33 UTC, prrace approved these changes

2020-10-06 10:49 UTC, mrserb commented
/integrate

2020-10-06 10:50 UTC, closed without merging