Exception values for AnnotationTypeMismatchException are not always informative
openjdk/jdk pull request #3892
Opened 2021-05-05 21:36 UTC by raphw

This improves the messages that are provided by `AnnotationTypeMismatchException`s. The message provided by AnnotationTypeMismatchExceptions is deliberately undefined such that this should not break any contract.

2021-05-05 22:21 UTC, jddarcy reviewed
Please add 8266598 to the @bug lines of the regression tests.

2021-06-06 21:16 UTC, raphw commented
Commenting on PR to avoid closing it, as it is still under review.

2021-06-09 08:49 UTC, jbf commented
Link to CSR: https://bugs.openjdk.java.net/browse/JDK-8266768

2021-06-09 08:56 UTC, jbf requested changes

2021-06-09 08:56 UTC, jbf commented on test/jdk/java/lang/annotation/AnnotationTypeMismatchException/AnnotationTypeMismatchTest.java
> + * @bug 8266598
\@bug numbers are usually on the same line: "* \@bug 8228988 8266598"

2021-06-09 08:56 UTC, jbf commented on test/jdk/java/lang/annotation/AnnotationTypeMismatchException/EnumTypeMismatchTest.java
> + * @bug 8266598
Same, here, single line

2021-06-09 09:58 UTC, raphw commented
Moved the bug number to the same line on both tests.

2021-06-09 12:54 UTC, jbf approved these changes
LGTM

2021-06-09 12:55 UTC, jbf commented
/csr

2021-06-09 13:07 UTC, raphw commented
/integrate

2021-06-09 13:19 UTC, jbf commented
/sponsor

2021-06-09 13:21 UTC, closed without merging