8267246: -XX:MaxRAMPercentage=0 is unreasonable for jtreg tests on many-core machines
openjdk/jdk pull request #4062
Opened 2021-05-17 13:24 UTC by DamonFool

Hi all,

vmTestbase/vm/mlvm/anonloader/stress/oome/metaspace/Test.java fails on our many-core machines due to `-XX:MaxRAMPercentage=0`.
This is because `MaxRAMPercentage` will be always 0 if JTREG_JOBS > 25 [1].

It can be reproduced by: `make test TEST="vmTestbase/vm/mlvm/anonloader/stress/oome/metaspace/Test.java" JTREG="JOBS=26"` on almost all machines.

Setting `-XX:MaxRAMPercentage=0` on many-core machines seems unreasonable.
It would be better to fix it.

Thanks.
Best regards,
Jie

[1] https://github.com/openjdk/jdk/blob/master/make/RunTests.gmk#L741

2021-05-17 13:24 UTC, DamonFool commented
/test

2021-05-17 13:25 UTC, DamonFool commented
/label add build
/cc build

2021-05-17 16:53 UTC, shipilev commented
Wait, no. That would mean on large core machines, the sum of heap sizes would be more than physical memory size. That is, 1% multiplied over >100 JTREG_JOBS would be >100%. Since `MaxRAMPercentage` is lower priority than `-Xmx`, why not just fix that for the test?

```
diff --git a/test/hotspot/jtreg/vmTestbase/vm/mlvm/anonloader/stress/oome/metaspace/Test.java b/test/hotspot/jtreg/vmTestbase/vm/mlvm/anonloader/stress/oome/metaspace/Test.java
index 0d5f1a1626f..4ee794fb79d 100644
--- a/test/hotspot/jtreg/vmTestbase/vm/mlvm/anonloader/stress/oome/metaspace/Test.java
+++ b/test/hotspot/jtreg/vmTestbase/vm/mlvm/anonloader/stress/oome/metaspace/Test.java
@@ -36,7 +36,7 @@
  * @build vm.mlvm.anonloader.stress.oome.metaspace.Test
  * @run driver vm.mlvm.share.IndifiedClassesBuilder
  *
- * @run main/othervm -XX:-UseGCOverheadLimit -XX:MetaspaceSize=10m -XX:MaxMetaspaceSize=20m vm.mlvm.anonloader.stress.oome.metaspace.Test
+ * @run main/othervm -Xmx1g -XX:-UseGCOverheadLimit -XX:MetaspaceSize=10m -XX:MaxMetaspaceSize=20m vm.mlvm.anonloader.stress.oome.metaspace.Test
  */
 
 package vm.mlvm.anonloader.stress.oome.metaspace;
```

2021-05-17 16:56 UTC, shipilev requested changes
Wait, no. That would mean on large core machines, the sum of heap sizes would be more than physical memory size. That is, 1% multiplied over >100 JTREG_JOBS would be >100%. Since `MaxRAMPercentage` is lower priority than `-Xmx`, and seeing that test does not expect heap OOME, why not just put the explicit heap size in that test?

```
diff --git a/test/hotspot/jtreg/vmTestbase/vm/mlvm/anonloader/stress/oome/metaspace/Test.java b/test/hotspot/jtreg/vmTestbase/vm/mlvm/anonloader/stress/oome/metaspace/Test.java
index 0d5f1a1626f..4ee794fb79d 100644
--- a/test/hotspot/jtreg/vmTestbase/vm/mlvm/anonloader/stress/oome/metaspace/Test.java
+++ b/test/hotspot/jtreg/vmTestbase/vm/mlvm/anonloader/stress/oome/metaspace/Test.java
@@ -36,7 +36,7 @@
  * @build vm.mlvm.anonloader.stress.oome.metaspace.Test
  * @run driver vm.mlvm.share.IndifiedClassesBuilder
  *
- * @run main/othervm -XX:-UseGCOverheadLimit -XX:MetaspaceSize=10m -XX:MaxMetaspaceSize=20m vm.mlvm.anonloader.stress.oome.metaspace.Test
+ * @run main/othervm -Xmx1g -XX:-UseGCOverheadLimit -XX:MetaspaceSize=10m -XX:MaxMetaspaceSize=20m vm.mlvm.anonloader.stress.oome.metaspace.Test
  */
 
 package vm.mlvm.anonloader.stress.oome.metaspace;
```

2021-05-17 17:01 UTC, shipilev commented
...maybe even `-Xmx512m`, you need to see what works.

2021-05-17 17:11 UTC, erikj79 commented
The option -XX:MaxRAMPercentage can't really scale up properly unless it accepts values lower than 1. Not sure what to do about this. Even before hitting 0, we get very clunky behavior due to rounding at lower values.

2021-05-17 17:17 UTC, shipilev commented
`-XX:MaxRAMPercentage` is actually `double`, so it can accept values below 1. The last time I looked into trouble like this, it was a problem with doing floating-point division in the make files -- not sure if something can be done about that. 

But my point is that the failing test -- is that the only test that fails? -- expects some heap size to accommodate Java allocations until the expected Metaspace OOM happens. In that case, the fix should be in the test itself. Because even if we do +1 to `MaxRAMPercentage`, it might still be not enough.

2021-05-17 23:35 UTC, DamonFool commented
Thanks @shipilev and @erikj79 for your review and nice suggestions.

I filed JDK-8267293 to handle the test failure and will fix the unreasonable setting of MaxRAMPercentage in this PR.

2021-05-18 03:32 UTC, DamonFool commented
> _Mailing list message from [Aleksey Shipilev](mailto:shade@redhat.com) on [build-dev](mailto:build-dev@mail.openjdk.java.net):_
> 
> On 5/17/21 7:30 PM, erik.joelsson at oracle.com wrote:
> 
> > Oh, if it's double, we can just switch to using awk to make the
> > calculation, just like we do for TEST_JOBS. I just did a quick check and
> > it produces float values.
> 
> Oh, cool. Having a more precise MaxRAMPercentage would be nice.
> 
> --
> Thanks,
> -Aleksey

Hi @erikj79 and @shipilev ,

Patch has been updated to using awk to make the calculation.
Thanks.

2021-05-18 03:42 UTC, DamonFool commented
/test

2021-05-18 07:54 UTC, shipilev commented
I ran `tier1` and `tier2` on my 3970X, which usually runs with `-XX:MaxRAMPercentage=0` due to having 32 cores, and the tests completed fine. It now runs with `-XX:MaxRAMPercentage=0.78125`.

2021-05-18 07:55 UTC, shipilev approved these changes
I am good with this change, but someone else should take a look as well.

2021-05-18 16:19 UTC, erikj79 approved these changes
Looks good to me, thanks for fixing this!

I took the change for a spin internally running our tier1-3.

2021-05-18 23:53 UTC, DamonFool commented
Thanks @shipilev and @erikj79 for your review.

I'll push it tomorrow since JDK-8267293 and JDK-8267311 are easier to be reproduced with the original code.
Thanks.

2021-05-19 01:45 UTC, DamonFool commented
> I'll push it tomorrow since JDK-8267293 and JDK-8267311 are easier to be reproduced with the original code.

We can still easily reproduce JDK-8267311 as before with this patch.
So push it.

/integrate

2021-05-19 01:46 UTC, closed without merging