8267239: C1: RangeCheckElimination for % operator
openjdk/jdk pull request #4083
Opened 2021-05-18 08:20 UTC by kelthuzadx

% operator follows from this rule that the result of the remainder operation can be negative only if the dividend is negative, and can be positive only if the dividend is positive. Moreover, the magnitude of the result is always less than the magnitude of the divisor(See [LS 15.17.3](https://docs.oracle.com/javase/specs/jls/se8/html/jls-15.html#jls-15.17.3)).
      
So if `y` is a constant integer and not equal to 0, then we can deduce the bound of remainder operation:
-  x % -y  ==> [0, y - 1] RCE
-  x % y   ==> [0, y - 1] RCE
-  -x % y  ==> [-y + 1, 0]
-  -x % -y ==> [-y + 1, 0]

Based on above rationale, we can apply RCE for the remainder operations whose dividend is constant integer and >= 0,  e.g.:

```java
for(int i=0;i<1000;i++){
  int top5 = arr[i%5];  // Apply RCE if arr is a loop invariant
  ....
}
```

For more detailed RCE results, please check out the attachment on JBS, it was generated by ArithmeticRemRCE with additional flags -XX:+TraceRangeCheckElimination -XX:+PrintIR.

Testing:
- test/hotspot/jtreg/compiler/c1/(slowdebug)

2021-05-18 08:28 UTC, kelthuzadx commented
/label add hotspot

The inference is not documented in JLS, so add hotspot-dev for more logical checking ;)

2021-05-18 13:22 UTC, neliasso commented
Have you checked how C2 handles this case?

2021-05-18 15:08 UTC, TobiHartmann requested changes
Looks like C2 does not implement this optimization (should be in `ModINode::Value`). We should add it.

2021-05-19 02:39 UTC, kelthuzadx commented on src/hotspot/share/c1/c1_RangeCheckElimination.cpp
> +    }else {
> Looks like C2 does not implement this optimization (should be in ModINode::Value). We should add it.

Thanks for confirming the C2 part, I will double-check it and file an issue for that~

> Missing whitespace }else

Fixed.

2021-05-19 08:14 UTC, TobiHartmann approved these changes
Looks good to me.

2021-05-19 08:25 UTC, neliasso approved these changes
Looks good.

2021-05-19 08:53 UTC, kelthuzadx commented
Thank you Nils and Tobias for taking the time to review this patch! I've filed https://bugs.openjdk.java.net/browse/JDK-8267376 for investigating if it's possible to apply C2 RCE for % operator when divisor != 0.

/integrate

2021-05-19 09:03 UTC, TobiHartmann commented
/sponsor

2021-05-19 09:05 UTC, closed without merging

2021-05-24 11:12 UTC, kelthuzadx commented
I think it is not easy/trivial to implement this for C2 since it idealize ModINode to other nodes if divisor is constant integer:

https://github.com/openjdk/jdk/blob/31139108c1ca9d355bd484d692830dfbc8317477/src/hotspot/share/opto/divnode.cpp#L946-L948

https://github.com/openjdk/jdk/blob/31139108c1ca9d355bd484d692830dfbc8317477/src/hotspot/share/opto/divnode.cpp#L166-L192