Jdk 8266748
openjdk/jdk pull request #4142
Opened 2021-05-21 08:46 UTC by hns

This change consolidates the code to generate type signature modifiers into `Signatures.TypeSignature`. 

Although this mostly consists of moving the code from `ClassWriterImpl` and `Utils` to `Signatures`, I also avoided the need to split the modifiers string when processing preview modifiers by returning a `List<String>` instead of a `String` in what used to be `Utils.modifiersToString` and is now `TypeSignature.getModifiers`.

2021-05-28 15:51 UTC, jonathan-gibbons reviewed
General comments; not a final review.

* Moving code out of `Utils` is generally always good but it's a bit of a shame to move it down into `formats.html`. That being said, `Signatures` is a good abstraction to be building.

* The medium amount of use of `HtmlDocletWriter` in `Signatures` is a code-smell, although arguably, we're just exposing an existing code-smell. We should (generally) continue our efforts to move code out of `HtmlDocletWriter` into other more-focussed abstractions.

2021-06-03 17:22 UTC, jonathan-gibbons requested changes
Minor changes suggestion, to access items from the configuration where possible.

As a followup, it would be good to look at the remaining uses of `HtmlDocletWriter` in `Signatures`. There is at least a theme of "methods to create links", and if those methods are just used in the `Signatures` class, they would be candidates to move into that class as well.

2021-06-03 17:22 UTC, jonathan-gibbons commented on src/jdk.javadoc/share/classes/jdk/javadoc/internal/doclets/formats/html/Signatures.java
> +            if (writer.options.linkSource()) {
better to use configuration.getOptions()

2021-06-03 17:22 UTC, jonathan-gibbons commented on src/jdk.javadoc/share/classes/jdk/javadoc/internal/doclets/formats/html/Signatures.java
> +                    Content c = Text.of(writer.resources.getText("doclet.not.exhaustive"));
Better to use `configuration.getDocResources()`

2021-06-03 17:22 UTC, jonathan-gibbons commented on src/jdk.javadoc/share/classes/jdk/javadoc/internal/doclets/formats/html/Signatures.java
> +                             writer.contents.previewMark)));
use the configuration for these two values

2021-06-07 13:27 UTC, hns commented
> Minor changes suggestion, to access items from the configuration where possible.
> 
> As a followup, it would be good to look at the remaining uses of `HtmlDocletWriter` in `Signatures`. There is at least a theme of "methods to create links", and if those methods are just used in the `Signatures` class, they would be candidates to move into that class as well.

I changed the mentioned accesses to  use configuration instead of writer. 

Most of the link methods in `HtmlDocletWriter` are used all over the place. `addSrcLink` is only used in `TypeSignature` and `MemberSignature`, but there's various circumstances that makes a move to Signatures unattractive (it accesses fields in HtmlDocletWriter, to which static nested classes TypeSignature and MemberSignature don't share a common reference).

2021-06-08 16:25 UTC, jonathan-gibbons approved these changes
Generally good, and as with many cleanups, it's a great step in the right direction. As I indicated in a previous round of review, I think that further cleanup is possible (later) by moving more code out of `HtmlDocletWriter` into more specific abstractions, possibly including this one.

2021-06-08 19:19 UTC, hns commented
/integrate

2021-06-08 19:21 UTC, closed without merging