8267578: Remove unnecessary preview checks
openjdk/jdk pull request #4157
Opened 2021-05-23 11:04 UTC by lgxbslgx

Hi all,

The following preview checks are unnecessary because they are standard features now.

Attr.java
```
        allowReifiableTypesInInstanceof =
                Feature.REIFIABLE_TYPES_INSTANCEOF.allowedInSource(source) &&
                (!preview.isPreview(Feature.REIFIABLE_TYPES_INSTANCEOF) || preview.isEnabled());
```

JavacParser.java
```
        this.allowYieldStatement = (!preview.isPreview(Feature.SWITCH_EXPRESSION) || preview.isEnabled()) &&
                Feature.SWITCH_EXPRESSION.allowedInSource(source);
```

Resolve.java
```
        allowYieldStatement = (!preview.isPreview(Feature.SWITCH_EXPRESSION) || preview.isEnabled()) &&
                Feature.SWITCH_EXPRESSION.allowedInSource(source);
```

It is good to remove them.
Thanks for review.

Best Regards,
-- Guoxiong

2021-05-23 17:43 UTC, JimLaskey commented
These checks need to remain to allow the Javac compiler to generate code for earlier releases. Please close.

2021-05-23 17:44 UTC, JimLaskey requested changes
These checks need to remain to allow the Javac compiler to generate code for earlier releases. Please close.

2021-05-24 06:34 UTC, lahodaj approved these changes
Looks good to me.

@JimLaskey - please note that javac does not support preview features from previous versions (as per JEP 12). So once a feature is made final, it is safe to remove the preview checks, AFAIK, it just was not done for these few cases.

2021-05-24 07:22 UTC, lgxbslgx commented
@JimLaskey @jonathan-gibbons @lahodaj Thanks for your comments and reviews.

This patch only cleans up the preview checks instead of something about releases.

The similar cleanup codes are common when we implement the standard feature. Please see the following two cases.

1. [8260517: implement Sealed Classes as a standard feature in Java](https://github.com/openjdk/jdk/commit/0fa9223)

```
-        this.allowSealedTypes = (!preview.isPreview(Feature.SEALED_CLASSES) || preview.isEnabled()) &&
-                Feature.SEALED_CLASSES.allowedInSource(source);
+        this.allowSealedTypes = Feature.SEALED_CLASSES.allowedInSource(source);
```

2. [8255013: implement Record Classes as a standard feature in Java, follow-up](https://github.com/openjdk/jdk/commit/8bde2f4)

```
-        this.allowRecords = (!preview.isPreview(Feature.RECORDS) || preview.isEnabled()) &&
-                Feature.RECORDS.allowedInSource(source);
+        this.allowRecords = Feature.RECORDS.allowedInSource(source);
```

We can consider that the codes of this patch were forgotten to cleanup during previous standard features.

2021-05-24 08:50 UTC, JimLaskey commented
Apologies. I misread the nature of the change.

2021-05-24 08:58 UTC, lgxbslgx commented
/integrate

2021-05-24 12:28 UTC, lahodaj commented
/sponsor

2021-05-24 12:31 UTC, closed without merging