8267611: Print more info when pointer_delta assert fails
openjdk/jdk pull request #4163
Opened 2021-05-24 11:11 UTC by stefank

We've seen a few new failures with the new pointer_delta assert. It would be nice if the assert printed the 'left' and 'right' pointer values.

2021-05-24 12:48 UTC, dholmes-ora approved these changes
LGTM!

Thanks,
David

2021-05-24 22:55 UTC, DamonFool approved these changes

2021-05-25 06:15 UTC, stefank commented
Thanks for reviewing!

2021-05-26 08:10 UTC, tschatzl approved these changes

2021-05-26 08:32 UTC, kimbarrett requested changes

2021-05-26 08:32 UTC, kimbarrett commented on src/hotspot/share/utilities/globalDefinitions.hpp
> +inline intptr_t p2i(const void* p) {
I don't think the `const void*` overload is needed, given the presence of the `const volatile void*` overload.

2021-05-26 13:40 UTC, kimbarrett approved these changes
Looks good.

2021-05-26 17:56 UTC, stefank commented
Thanks for the reviews!
/integrate

2021-05-26 17:57 UTC, closed without merging