JDK-8267916: Make as_CompilerThread consistent with other as_*_thread methods
openjdk/jdk pull request #4240
Opened 2021-05-28 08:09 UTC by albertnetymk

Simple refactoring around `as_CompilerThread`. A new file, `compilerThread.inline.hpp`, is created to get around the circular dependency.

2021-05-28 13:03 UTC, dholmes-ora commented
Sorry I'm not seeing the need for a new compilerThread.inline.hpp. That isn't making things consistent AFAICS - if we haven't factored out CompilerThread into its own header we shouldn't have compilerThread.inline.hpp.

David

2021-05-28 19:24 UTC, albertnetymk commented
> That isn't making things consistent

It's the renaming and move to `thread.inline.hpp` (two points covered in the ticket description) that is supposed to make it more consistent. The creation of `compilerThread.inline.hpp` is just to work around the circular dependency, `CompilerThread::current()` in `compilerThread.hpp` calls `JavaThread::as_CompilerThread` (in `thread.inline.hpp` after the move).

2021-05-28 22:34 UTC, dholmes-ora commented
Sorry I looked at this too late at night:

>  if we haven't factored out CompilerThread into its own header

but we do of course have that.

2021-05-28 23:26 UTC, kimbarrett requested changes

2021-05-28 23:26 UTC, kimbarrett commented on src/hotspot/share/ci/ciEnv.hpp
> +#include "compiler/compilerThread.inline.hpp"
Including .inline.hpp by a .hpp is not allowed.

2021-05-28 23:26 UTC, kimbarrett commented on src/hotspot/share/compiler/compilerThread.inline.hpp
> +#include "compiler/compilerThread.hpp"
This include order is inconsistent with JDK-8267464.

2021-06-02 14:26 UTC, albertnetymk commented
I encountered some circular dependencies after moving the definition to `thread.inline.hpp`, so I replaced it with a static `cast` method, as Kim instructed from an offline discussion. Note now there's a discrepancy: `CompilerThread::cast(t)` vs `t->as_Worker_thread()` (or `t->as_Java_thread()`). I can do the same for other `as_*_thread` methods as well (in this PR or another one) if people feel like this approach.

2021-06-02 14:43 UTC, kimbarrett approved these changes
Looks good.

2021-06-02 14:50 UTC, kimbarrett commented
> I encountered some circular dependencies after moving the definition to `thread.inline.hpp`, so I replaced it with a static `cast` method, as Kim instructed from an offline discussion. Note now there's a discrepancy: `CompilerThread::cast(t)` vs `t->as_Worker_thread()` (or `t->as_Java_thread()`). I can do the same for other `as_*_thread` methods as well (in this PR or another one) if people feel like this approach.

as_Worker_thread => WorkerThread::cast could pretty easily be added to this change.  There's only one call.

There are lots of as_Java_thread calls.  Maybe check with runtime team how they feel about the inconsistency vs code churn.

2021-06-02 17:19 UTC, iklam commented
> > I encountered some circular dependencies after moving the definition to `thread.inline.hpp`, so I replaced it with a static `cast` method, as Kim instructed from an offline discussion. Note now there's a discrepancy: `CompilerThread::cast(t)` vs `t->as_Worker_thread()` (or `t->as_Java_thread()`). I can do the same for other `as_*_thread` methods as well (in this PR or another one) if people feel like this approach.
> 
> as_Worker_thread => WorkerThread::cast could pretty easily be added to this change. There's only one call.
> 
> There are lots of as_Java_thread calls. Maybe check with runtime team how they feel about the inconsistency vs code churn.

I prefer `JavaThread::cast()` over `Thread::as_Java_thread()`. The former style is consistent with other functions such as `InstanceKlass:cast()`.

As far as code churn, [JDK-8252685](https://bugs.openjdk.java.net/browse/JDK-8252685) already removed a bunch of `as_Java_thread()` calls (we have about 110 of them now, vs about 180 in JDK 16), so we may as well fix the rest for a more consistent style, which is also better with header dependencies. @dholmes-ora what do you think? In any case, we should do that in a different PR.

2021-06-02 17:29 UTC, iklam approved these changes
This looks good to me. If we decide to use Compiler::cast, the RFE title should be updated before integration.

2021-06-02 21:49 UTC, dholmes-ora approved these changes
The change to CompilerThread::cast doesn't seem necessary to address any circular header dependencies - what am I missing?

I personally prefer the as_X() style for thread casts (though X is spelt incorrectly in most places), but `cast` is a more traditional name and used for other type hierarchies in the VM. So we can change this for other thread types in a separate RFE.

As Ioi notes, this RFE needs a new synopsis: "Adopt cast notation for CompilerThread conversions" or something like that.

Thanks,
David

2021-06-02 22:38 UTC, dholmes-ora commented
> The change to CompilerThread::cast doesn't seem necessary to address any circular header dependencies - what am I missing?

Doh! I was missing the fact the cast method goes in compilerThread.hpp not thread.hpp.

2021-06-03 08:20 UTC, albertnetymk commented
> as_Worker_thread => WorkerThread::cast could pretty easily be added to this change. There's only one call.

I will do that in another PR to keep this one more focused.

> As Ioi notes, this RFE needs a new synopsis: "Adopt cast notation for CompilerThread conversions" or something like that.

Updated.

Thank you all for the suggestions and reviews.

/integrate

2021-06-03 08:21 UTC, closed without merging