JDK-8259806: Clean up terminology on the "All Classes" page
openjdk/jdk pull request #4270
Opened 2021-05-31 10:06 UTC by hns

This is a simple change to replace the "All Classes" with "All Classes and Interfaces" in the heading of and references to the page of the same name.

2021-06-03 17:09 UTC, jonathan-gibbons requested changes
Maybe I'm fighting a losing battle on this one, but the current policy is to generate the correct new terminology for recent releases and the older terminology for older releases, to try and stay consist within the release.

The mapping is handled semi-automatically in `HtmlDoclet.getResourceKeyMapper`, line 130.  As a general rule, if you're changing terminology, you should at least be updating the mapping as well.

2021-06-05 06:55 UTC, hns commented
> Maybe I'm fighting a losing battle on this one, but the current policy is to generate the correct new terminology for recent releases and the older terminology for older releases, to try and stay consist within the release.
> 
> The mapping is handled semi-automatically in `HtmlDoclet.getResourceKeyMapper`, line 130. As a general rule, if you're changing terminology, you should at least be updating the mapping as well.

Is "Classes and Interfaces" part of the "new terminology"? I thought "classes and interfaces" would be the correct term for anything living in a .class file, regardless of release.

2021-06-08 16:21 UTC, jonathan-gibbons approved these changes

2021-06-08 18:48 UTC, hns commented
/integrate

2021-06-08 18:49 UTC, closed without merging