8266631: StandardJavaFileManager: getJavaFileObjects() impl violates the spec
openjdk/jdk pull request #4360
Opened 2021-06-04 12:42 UTC by lahodaj

This improves javadoc/specification of several StandardJavaFileManager methods, as requested in these bugs:
https://bugs.openjdk.java.net/browse/JDK-8266631
https://bugs.openjdk.java.net/browse/JDK-8266596
https://bugs.openjdk.java.net/browse/JDK-8266591
https://bugs.openjdk.java.net/browse/JDK-8266590

The CSR is here:
https://bugs.openjdk.java.net/browse/JDK-8268260

2021-06-04 12:43 UTC, lahodaj commented
/issue add JDK-8266631,JDK-8266596,JDK-8266591,JDK-8266590

2021-06-04 15:31 UTC, vicente-romero-oracle approved these changes
the patch and the CSR look good to me. I would just inline the spec changes in the specification section of the CSR

2021-06-04 16:13 UTC, jonathan-gibbons commented
/csr

2021-06-04 16:29 UTC, jonathan-gibbons requested changes

2021-06-04 16:29 UTC, jonathan-gibbons commented on src/java.compiler/share/classes/javax/tools/StandardJavaFileManager.java
>       * IllegalArgumentException will be thrown if any of the paths
since we're editing lines in this region ... use {@code} or {@link} around IllegalArgumentException.

2021-06-04 16:29 UTC, jonathan-gibbons commented on src/java.compiler/share/classes/javax/tools/StandardJavaFileManager.java
>       * IllegalArgumentException will be thrown if any of the paths
since we're editing lines in this region ... use {@code} or {@link} around IllegalArgumentException.

2021-06-04 16:29 UTC, jonathan-gibbons commented on src/java.compiler/share/classes/javax/tools/StandardJavaFileManager.java
>       * @return a list of file objects
In the following @throws, remove the trailing "."

2021-06-04 16:29 UTC, jonathan-gibbons commented on src/java.compiler/share/classes/javax/tools/StandardJavaFileManager.java
>       * a directory
consider adding ` or if this file manager does not support any of the
     * given paths` in line with similar methods

2021-06-04 16:29 UTC, jonathan-gibbons commented on src/java.compiler/share/classes/javax/tools/StandardJavaFileManager.java
> +     * {@linkplain #getJavaFileObjectsFromPaths(Collection)}.
The new condition should be in an `@implSpec`.

The package declaration contains a general specification for nulls and NPE, so it's not clear that we need the `@throws NPE` at all, but it's not wrong to leave it as was.

2021-06-15 14:27 UTC, lahodaj commented
Transferred to JDK 17 as:
https://github.com/openjdk/jdk17/pull/56

Thanks for the comments!

2021-06-15 14:27 UTC, closed without merging