8263461: jdk/jfr/event/gc/detailed/TestEvacuationFailedEvent.java uses wrong mechanism to cause evacuation failure
openjdk/jdk pull request #4541
Opened 2021-06-21 14:32 UTC by tschatzl

Hi all,

  can I have reviews for this change to the jdk/jfr/event/gc/detailed/TestEvacuationFailedEvent.java test to use the only "officially sanctioned" way to cause evacuation failures via the respective debug-level options.

Testing: checking failing test case to cause evacuation failures

Thanks,
  Thomas

2021-06-21 14:32 UTC, tschatzl commented
/label add hotspot-gc

2021-06-22 00:53 UTC, kimbarrett requested changes

2021-06-22 00:53 UTC, kimbarrett commented on test/jdk/jdk/jfr/event/gc/detailed/TestEvacuationFailedEvent.java
> +        System.out.println(data);
`Reference.reachabilityFence` seems like a better choice for keep-alive.  Other than that, looks good.

2021-06-22 16:23 UTC, kimbarrett approved these changes
Looks good.

2021-06-30 07:59 UTC, walulyai approved these changes
lgtm!

2021-06-30 07:59 UTC, albertnetymk approved these changes

2021-06-30 08:04 UTC, tschatzl commented
Thanks @kimbarrett @walulyai @albertnetymk for your reviews.

/integrate

2021-06-30 08:05 UTC, closed without merging