8269135: TestDifferentProtectionDomains runs into timeout in client VM
openjdk/jdk pull request #4558
Opened 2021-06-22 13:34 UTC by mychris

The test tries to compile a method using the WhiteBox with optimization level 4, which is not available in client VMs. The WhiteBox only prints out a warning, and the call to enqueueMethodForCompilation succeeds. After that, the test case goes into an endless loop to wait for the compilation to finish, which never happens, because the method is not enqueued for compilation.

I fixed this by choosing a different compilation level, if C2 is not included in the JVM. I think this test should be enough, since there is already an `@requires` which checks, that we are in mixed mode and that C2 should be used.

In addition, I bound the loop in order to fail with a timeout more early, if the compilation does not happen (or takes too long because of platform restrictions).

2021-06-22 14:13 UTC, dcubed-ojdk commented
@dholmes-ora - This one might interest you since it is a Nestmates test...

2021-06-22 16:46 UTC, eastig commented on test/hotspot/jtreg/runtime/Nestmates/protectionDomain/TestDifferentProtectionDomains.java
> +        wb.enqueueMethodForCompilation(cons,  optimizationLevel);
It might be worth to check the value `enqueueMethodForCompilation` returns.

2021-06-22 17:01 UTC, eastig commented on test/hotspot/jtreg/runtime/Nestmates/protectionDomain/TestDifferentProtectionDomains.java
> +        }
I think it is better to check whether COMP_LEVEL_FULL_OPTIMIZATION is supported:
```
if (!wb.isMethodCompilable(optimizationLevel)) {
  optimizationLevel = CompilerWhiteBoxTest.COMP_LEVEL_ANY;
}
```

2021-06-22 17:19 UTC, eastig commented on test/hotspot/jtreg/runtime/Nestmates/protectionDomain/TestDifferentProtectionDomains.java
> +        }
try {
  CompilerWhiteBoxTest.waitBackgroundCompilation(cons);
} catch (InterruptedException e) {
  throw new RuntimeException("Timeout");
}

2021-06-23 06:51 UTC, dholmes-ora requested changes
Hi Christoph,

I think, given the failure scenario the test is trying to test, that the best, and simplest, fix is to update the:

* @requires vm.compMode=="Xmixed" &
*           (vm.opt.TieredStopAtLevel == null | vm.opt.TieredStopAtLevel == 4)
 
so that it requires C2 to be present and so is skipped on a client-only VM.

Thanks,
David

2021-06-23 10:41 UTC, mychris commented
Thanks for your reviews.

I initially didn't want to limit the test case to tiered VMs, since the bug said "C1", but if that's OK I am fine with it as well. I also picked up one of the suggestion @eastig gave me, which is check the return value of `enqueueMethodForCompilation` since I think this is a reasonable addition and makes the test more robust.

I am not using `CompilerWhiteBoxTest.waitBackgroundCompilation`, since it had some issues with the enabled security manager and I didn't want to complicate the test case more. I think with the new `@requires` and the check of the return value from `enqueueMethodForCompilation`, we should be save here and the loop should always terminate.

2021-06-24 13:07 UTC, dholmes-ora approved these changes
This seems fine to me.

Thanks,
David

2021-06-24 13:40 UTC, mychris commented
Thanks David.
Are you fine with this version as well, @eastig?

2021-07-02 08:44 UTC, mychris commented
Hearing no objections, I guess we can integrate it then?
/integrate

2021-07-02 15:12 UTC, dcubed-ojdk approved these changes
HotSpot changes require two reviewers and it doesn't look
like @eastig has marked this PR as reviewed.

I've gone ahead and reviewed your changes.

2021-07-02 15:14 UTC, dcubed-ojdk commented
/sponsor

2021-07-02 15:16 UTC, closed without merging

2021-07-02 20:09 UTC, eastig reviewed
Sorry for missing this.

LGTM.