8269596: Snapshot soft ref policy before marking/copying
openjdk/jdk pull request #4624
Opened 2021-06-29 14:58 UTC by albertnetymk

Set up soft ref policy before marking/copying for Serial, Parallel and G1. With this change, all collectors do soft-ref policy setup in the beginning of a GC cycle.

2021-07-01 10:03 UTC, tschatzl requested changes
Would it be useful to only call the soft ref policy setup via `setup_policy()` when it is (potentially) set to `true`? I.e. only during full gc, and call `setup_policy(false)` afterwards, maybe with a scope object?
This would remove the unnecessary calls with `false` as argument completely in the places where we never actually change it (e.g. for the G1 concurrent mark ref processor), and emphasize for the stw full gc collectors that they are the only ones eventually change it to "always clearing".

Also the sequence
```
reference_processor()->enable_discovery();
reference_processor()->setup_policy(<some value>);
```
should be merged into a single call as there are like five places now where both are called one after another.

In `psParallelCompact.cpp`, the `marked_for_unloading` local right after these calls could be removed too, it's unused.

2021-07-01 12:42 UTC, albertnetymk commented
Merged `enable_discovery` and `setup_policy` into one call, and made `setup_policy` private.

2021-07-01 15:32 UTC, tschatzl approved these changes
Lgtm.

2021-07-01 16:33 UTC, albertnetymk commented
I accidentally removed a call to `disable_discovery();` in `genCollectedHeap.cpp`. Restored in the latest commit.

2021-07-02 08:20 UTC, kimbarrett approved these changes
Looks good.

2021-07-02 09:18 UTC, albertnetymk commented
Thanks for the review.

/integrate

2021-07-02 09:20 UTC, closed without merging