8269592: [JVMCI] Optimize c2v_iterateFrames.
openjdk/jdk pull request #4625
Opened 2021-06-29 17:26 UTC by woess

2021-07-08 18:26 UTC, vnkozlov requested changes
Someone from Graal group have to review it.

I have concern about relaxing guarantees in `asJavaVFrame()`. It is shared code and the only case when we can see native frame is call from JVMCI's method `iterateFrames()` as I understand. Then relaxation should be JVMCI specific.

2021-07-08 19:15 UTC, tkrodriguez approved these changes
Looks good.

2021-07-08 19:19 UTC, tkrodriguez commented
We went through a bunch of review and tests cycles on this in our JDK repos so this is the result of that, so I've approved it.  @dean-long saw some of this progress as well.
So you want an ifdef JVMCI around the is_native part of the guarantees?  Why are those guarantees anyway?  Seems like they should just be asserts to me.

2021-07-08 19:41 UTC, woess commented
> I have concern about relaxing guarantees in `asJavaVFrame()`. It is shared code and the only case when we can see native frame is call from JVMCI's method `iterateFrames()` as I understand. Then relaxation should be JVMCI specific.

@vnkozlov The changes to `asJavaVFrame()` seemed like a good idea since `vframeStream` iterates all javaVFrames including native frames but, without these changes, fails the `_frame.is_compiled_frame()` guarantee for native frames. This is ok if you filter the frames by method first, as is the case with current usages, but you won't be able to use `asJavaVFrame()` on all vframes in the stream.
But, if the change is considered problematic/too risky, we can work around it.

2021-07-08 20:49 UTC, dean-long commented
@tkrodriguez I think I introduced those guarantees, and now I agree they should probably be asserts.

2021-07-08 21:38 UTC, vnkozlov commented
Please link Graal's PR to this RFE so I can see your reviews. 
I am fine with converting guarantees to asserts.

2021-07-08 22:56 UTC, vnkozlov commented
My concern comes from fact that we don't treat `native` frame as as `java` frame: [frame.cpp#L183](https://github.com/openjdk/jdk/blob/master/src/hotspot/share/runtime/frame.cpp#L183). And `frame::is_compiled_frame()` specifically checks that compiled method is Java method.

On other hand we create `compiledVFrame` for native calls wrappers - we check only that it is compiled code: [vframe.cpp#L81](https://github.com/openjdk/jdk/blob/master/src/hotspot/share/runtime/vframe.cpp#L81). And `compiledVFrame` is subclass of `javaVFrame`. Which is conflicting for me but it is not related to these changes.

Okay, if Tom and Dean think it is safe change for `asJavaVFrame()` code I will approve changes.

2021-07-09 03:48 UTC, dean-long commented
I agree, it's confusing that different APIs can't agree on the exact status of compiled native frames.  But as Vladimir pointed out, we support them in vframe::new_vframe, and we also support them in vframeStreamCommon::fill_from_compiled_native_frame(), so it seems OK for asJavaVFrame() to support them as well.

2021-07-09 03:49 UTC, dean-long approved these changes

2021-07-09 11:25 UTC, woess commented
> My concern comes from fact that we don't treat native frame as as java frame: frame.cpp#L183. And frame::is_compiled_frame() specifically checks that compiled method is Java method.

Indeed, there's an inconsistency between `frame` and `vframe` w.r.t. native frames:
* `frame`: `is_java_frame()` and `is_compiled_frame()` return false
* `vframe`: `is_java_frame()` and `is_compiled_frame()` return true (since they're represented as `compiledVFrame`)

I can change the guarantees to asserts.

2021-07-09 12:11 UTC, woess commented
I converted the guarantees in asJavaVFrame() to asserts. Let me know if any of the asserts should remain guarantees.

2021-07-09 15:46 UTC, vnkozlov commented
Thank you, Tom, for Graal's PR link.

2021-07-09 15:47 UTC, vnkozlov approved these changes
Approved.
Please, run mach5 testing before push. Tom or Dean can help.

2021-07-14 17:22 UTC, woess commented
/covered

2021-07-14 17:28 UTC, woess commented
/integrate

2021-07-14 17:31 UTC, tkrodriguez commented
/sponsor

2021-07-14 17:33 UTC, closed without merging