JDK-8269651: ZGC: Optimize away gc locker in mark start
openjdk/jdk pull request #4638
Opened 2021-06-30 11:58 UTC by Hamlin-Li

Currently, ZGC involves gc locker in mark-start and relocate-start.
It seems gc locker in mark-start is not necessary anymore.
This is to remove this uncessary(??) gc locker before further optimization is discussed.

2021-06-30 12:42 UTC, pliden requested changes
Sorry, but we can't do this. The GC locker needs to be honored any time the good/bad mask is changed, so both MarkStart and RelocateStart still needs it.

2021-07-01 01:38 UTC, Hamlin-Li commented
Thanks for clarification.
When I invesitgated JDK-8269423, I also thought good/bad mask changing might be the reason to keep gc locker at MarkStart.

But after further investigation, it seems to me that for GetXxxCritical it's OK to remove gc locker at MarkStart.
The reasons are:
1. GetXxxCritical returns the native address, and whether good or bad these addresses are valid address for native code (am I right here?), unless it's relocated later at Relocate.
2. The gc locker in RelocateStart will block until ReleaseXxxCritical, so gc locker in RelocateStart ensures the native address retrieved from GetXxxCritical to be valid.

Please kindly correct my comments above.

2021-07-01 08:19 UTC, pliden commented
> GetXxxCritical returns the native address, and whether good or bad these addresses are valid address for native code (am I right here?), unless it's relocated later at Relocate.

We currently have the invariant that all accesses must go through the currently good heap view. While you can "cheat" and access objects through a bad heap view that will only work as long as you don't enable -XX:+ZVerifyViews, which will enforce this invariant. ZVerifyViews unmaps memory that isn't currently in the good heap view. It's a valuable debugging option to catch bad accesses, like when a load barrier is missing.

2021-07-01 08:51 UTC, Hamlin-Li commented
I see, Thanks for clarification!

2021-07-02 01:43 UTC, closed without merging