8269803: G1: remove unnecessary NoRefDiscovery
openjdk/jdk pull request #4664
Opened 2021-07-02 11:00 UTC by albertnetymk

Simple change of removing the unnecessary disable of ref-discovery for CM during young-gc pause.

Test: hotspot_gc

2021-07-05 09:31 UTC, tschatzl requested changes
I think the comment beginning `g1CollectedHeap.hpp:929` should be adapted too.

Looks good otherwise.

2021-07-06 07:58 UTC, kimbarrett commented
> I think the comment beginning `g1CollectedHeap.hpp:929` should be adapted too.
> 
> Looks good otherwise.

Other than the mentioned need for a comment update, I also thing this looks good.

2021-07-07 07:26 UTC, albertnetymk commented
Updated the comments.

2021-07-07 07:33 UTC, tschatzl approved these changes

2021-07-07 22:56 UTC, kimbarrett approved these changes
Looks good.

2021-07-08 06:14 UTC, albertnetymk commented
Thanks for the review.

/integrate

2021-07-08 06:15 UTC, closed without merging