8051680: (ref) unnecessary process_soft_ref_reconsider
openjdk/jdk pull request #4667
Opened 2021-07-02 12:59 UTC by albertnetymk

This PR consists of 3 commits:

1. Removes the soft-ref reconsideration phase because the soft-ref policy is set before marking (JDK-8269596) and stays the same across the GC cycle. Reconsideration phase should not find anything interesting. That being said, there might be some benefit of using more precise heap usage after marking for soft-ref processing, created JDK-8269798 for exploring that.

2. Removes reloading of `_soft_ref_timestamp_clock` from `java_lang_ref_SoftReference::clock();` because the master clock should only be changed by GC.

3. Rename phase{2,3,4} to phase{1,2,3}.

Test: hotspot_gc

2021-07-06 08:18 UTC, kimbarrett requested changes
The first two commits look good.

As for the 3rd (phase renumbering) commit, if we're going to do all this
renaming, I'd prefer the new names were semantically meaningful, rather than
just Phase1,2,3,4.  Unfortunately that didn't happen either in or as a
followup to JDK-8202845.

2021-07-07 08:03 UTC, albertnetymk commented
Names and responsibility of various phases:

```
  enum RefProcSubPhases {
    SoftRefSubPhase1,
    WeakRefSubPhase1,
    FinalRefSubPhase1,
    FinalRefSubPhase2,
    PhantomRefSubPhase3,
    RefSubPhaseMax
  };

  enum RefProcPhases {
    RefPhase1,
    RefPhase2,
    RefPhase3,
    RefPhaseMax
  };
  
  // Phase 1: Drop Soft/Weak/Final references with a NULL or live referent, and clear
  // and enqueue non-Final references.
  void process_soft_weak_final_refs(RefProcProxyTask& proxy_task,
                                    ReferenceProcessorPhaseTimes& phase_times);

  // Phase 2: Keep alive followers of Final references, and enqueue.
  void process_final_keep_alive(RefProcProxyTask& proxy_task,
                                ReferenceProcessorPhaseTimes& phase_times);

  // Phase 3: Drop and keep alive live Phantom references, or clear and enqueue if dead.
  void process_phantom_refs(RefProcProxyTask& proxy_task,
                            ReferenceProcessorPhaseTimes& phase_times);
```

Kim's suggestion:

```
Process{Soft,Weak,Final}RefsSubPhase, KeepAliveFinalRefsSubPhase, ProcessPhantomRefsSubPhase

SoftWeakFinalRefsPhase, KeepAliveFinalRefsPhase, PhantomRefsPhase
```

Given such renaming is quite invasive, maybe it can be done in a separate PR. So which option do reviewers think is the best to take?

1. create a revert for the third commit, leaving renaming to another PR. (The phases will start from "2" in the logs.)
2. make semantic renaming in this PR. (Mixing real changes with large renaming.)

2021-07-09 05:41 UTC, kimbarrett commented
I would prefer to have the renaming done in a separate PR.

2021-07-09 08:04 UTC, albertnetymk commented
I have reverted the renaming commit; this PR effectively contains only the first two commits.

2021-07-09 20:25 UTC, kimbarrett approved these changes
Looks good.

2021-07-12 07:31 UTC, tschatzl approved these changes

2021-07-12 07:52 UTC, albertnetymk commented
Thanks for the review.

/integrate

2021-07-12 07:53 UTC, closed without merging