8269886: Inaccurate error message for compressed hprof test
openjdk/jdk pull request #4685
Opened 2021-07-06 02:55 UTC by linzang

The current implementation of hprof Reader for testing always prompts "Can not decompress the compressed hprof file" when there is error for testing gzipped heap dump. This is inaccurate if the gzipped file was decompressed successfully but the hprof file format is incorrect. So the inaccurate error message could be misleading for issue analysis.

This trivial PR refine the error message by simply print "Can not get stack of the compressed hprof file", the underlying exception from GZIPInputStream() or HprofReader() would give accurate error info.

2021-07-06 03:14 UTC, dholmes-ora commented
The existing message is a generic message covering the general operation of the whole try block. It seems far more appropriate than your new message, which only seems to apply to the final step. ???

David

2021-07-06 03:30 UTC, linzang commented
Hi David,
    Thanks for review and comments.

> The existing message is a generic message covering the general operation of the whole try block. It seems far more appropriate than your new message, which only seems to apply to the final step. ???

IMO, the whole method named getStack() is used to get the stack trace for the hprof file.  And the try block could throw exceptions by serveral reasons as decribed, so IMHO printing "Can not decompress the compressed hprof file" is not accurate. The proposed change is to print a generic error message that the getStack() fail when processing compressed hprof.  And the extra 'e' argument in the changed line would give detailed reason.  

So may be change error message to "Can not process the compressed hprof file" is better? what do you think? 

BRs,
Lin

2021-07-06 06:29 UTC, linzang commented
Hi @dholmes-ora， 
     Thanks for your suggestion! I have update the PR which split the try block into two seperate ones to process different exceptions.

BRs,
Lin

2021-07-06 06:48 UTC, dholmes-ora approved these changes
These changes are fine in themselves.

This code is not very well written though - the file streams do not get closed and the decompressed output file doesn't seem to get deleted when I would expect.

Thanks,
David

2021-07-06 06:58 UTC, linzang commented
Hi David，
Thanks for reviewing!
 
> This code is not very well written though - the file streams do not get closed and the decompressed output file doesn't seem to get deleted when I would expect.

Agree. I will create a seperate issue to fix it.

BRs,
Lin

2021-07-06 06:58 UTC, linzang commented
/integrate

2021-07-06 17:46 UTC, plummercj commented
You need 2 reviews. Please don't integrate yet. I'll provide more comments shortly.

2021-07-06 18:12 UTC, plummercj commented
After decompressing, no error or exception is thrown if MAGIC_NUMBER is not found. It just silently fails to print the stack trace.

Please use "cannot" instead of "can not". Both are grammatically correct, but "cannot" is what is normally used.

2021-07-07 00:41 UTC, linzang commented
Hi @plummercj , 

Thanks for reviewing,  I have updated the PR based on your comments, and remove unreachable code introduced by the updated code.

BRs,
Lin

2021-07-07 01:14 UTC, dholmes-ora requested changes
Either deleting the out file needs to be handled correctly in all cases or it should left as-is and fixed in a different RFE that also handles stream closing *try-with-resources?) etc. to clean up the code.

Otherwise the actual try/catch changes seem okay.

Thanks,
David

2021-07-07 01:14 UTC, dholmes-ora commented on test/lib/jdk/test/lib/hprof/parser/Reader.java
> +                        out.delete();
I thought this was going to handled by the separate RFE to fix the general logic? And you don't delete before throwing below. There should be a finally clause to handle deletion consistently.

2021-07-07 02:01 UTC, linzang commented
Hi @dholmes-ora 

> Either deleting the out file needs to be handled correctly in all cases or it should left as-is and fixed in a different RFE that also handles stream closing *try-with-resources?) etc. to clean up the code.

I have created an issue in JBS (https://bugs.openjdk.java.net/browse/JDK-8269909) to use the try-with-resource for stream closing, and will submit a PR shortly. 

For out.delete(), I prefer to fix it in this PR as the introduction of throwing exception in my last update makes the original out.delete() unreachable, so I have to add logic to handle it.  I will update this PR with a finally block in a minute. 

Thanks,
Lin

2021-07-07 02:52 UTC, dholmes-ora approved these changes
I would have added a single try/finally block that encompasses all the code after:

File out = new File(deCompressedFile);

but what you have also does the job.

Thanks,
David

2021-07-07 17:45 UTC, plummercj commented
There is still an inconsistency exception handling. For the outer bad MAGIC_NUMBER handling you have:

186                 throw new IOException("Unrecognized magic number: " + i);

But the decompressed handling results in:

178                         throw new IOException("Unrecognized magic number of decompressed data: " + i);

Which is caught and wrapped by:

181                     throw new IOException("Cannot get stack trace from the compressed hprof file", e);

Also, nothing is wrapping exceptions thrown by the following code:

143                 HprofReader r
144                     = new HprofReader(heapFile, in, dumpNumber,
145                                       true, debugLevel);
146                 r.read();
147                 return r.printStackTraces();

But any exception thrown by the following code is wrapped and rethrown at line 181:

172                         HprofReader r
173                             = new HprofReader(deCompressedFile, in2, dumpNumber,
174                                               true, debugLevel);
175                         r.read();
176                         return r.printStackTraces();

2021-07-07 22:37 UTC, linzang commented
Hi @plummercj,
    Thanks for point it out! I think the throw at line 181 could be removed and the `new = HprofReader(); r.read()` code should be in try block consistently in both situation (compressed/uncompressed). I will make the change.
-Lin

2021-07-07 22:49 UTC, linzang commented
Hi @plummercj,
    I just found that maybe there is no need to catch exception from `HprofReader` in this method, just keep it as what it originally did -  throw any exception from HprofReader directly. The information from HprofReader's exception is enough for root cause analysis in this case.
    I will test it and make the change.

BRs,
Lin

2021-07-08 03:40 UTC, plummercj requested changes
Looks good other than cleaning up the exception message.

2021-07-08 03:40 UTC, plummercj commented on test/lib/jdk/test/lib/hprof/parser/Reader.java
> +                        throw new IOException("Unrecognized magic number of decompressed data: " + i);
"of decompressed data" just doesn't sound right. I'd suggest either removing it, or maybe instead say "...found in decompressed data".

2021-07-08 03:56 UTC, linzang commented
I will mark this PR with integrate. 
Thanks Chris and David for your reviewing!

BRs,
Lin

2021-07-08 03:56 UTC, linzang commented
/integrate

2021-07-08 03:57 UTC, dholmes-ora approved these changes
LGTM.

2021-07-08 05:56 UTC, plummercj approved these changes

2021-07-08 06:28 UTC, dholmes-ora commented
/sponsor

2021-07-08 06:30 UTC, closed without merging