8269851: OperatingSystemMXBean getProcessCpuLoad reports incorrect pr…
openjdk/jdk pull request #4702
Opened 2021-07-07 04:03 UTC by xpbob

…ocess cpu usage in containers

2021-07-07 04:05 UTC, xpbob commented
/issue add JDK-8269851

2021-07-07 04:07 UTC, xpbob commented
getProcessCpuLoad return jvm cpu load。
8 core in machine, set 1 core for container。
Run same program, the getProcessCpuLoad return the same value。

expected
same program run in machine,value 0.12
run in 1 core container,value 0.99
ProcessCpuLoad is associative container setting

2021-07-07 04:29 UTC, dholmes-ora commented
Why did you create a new PR ??

2021-07-07 04:34 UTC, xpbob commented
> Why did you create a new PR ??

bug description changed。
update the commit info.

2021-07-07 06:30 UTC, linzang commented on src/jdk.management/unix/classes/com/sun/management/internal/OperatingSystemImpl.java
> +
I think this empty line could be removed

2021-07-07 06:32 UTC, linzang commented
Hi Bob,
     I am not a reviewer, just a tiny comments that you may need to remove the unnecessary empty line. Thanks.
-Lin

2021-07-07 07:50 UTC, YaSuenag reviewed
In HotSpot, CPU usage for JVM would be calculated at `get_jvm_tickes()` in os_perf_linux.cpp . It refers `/proc/self/stat` - should we refer it in same way?

I discussed about similar issue in #4299 , then we came to an agreement that we should refactor that HotSpot and JMX should share the code. Of course you can fix JMX only in this PR, but it still uses different implementation from HotSpot. I prefer to fix it in code consolidation between HotSpot and JMX.

2021-07-07 08:31 UTC, jerboaa requested changes
This patch seems fine in principle, but I don't like the duplication. Right now, `getProcessUsageDividesTotal()` and `getUsageDividesTotal()` look almost the same, but use different fields to set. Perhaps pass a parameter whether or not it's a system/process load request and use the different setters accordingly. Same duplication between `getCpuLoad()` and `getProcessCpuLoad()`. The main difference seems to be how `usageNanos` are being retrieved.

2021-07-07 10:31 UTC, jerboaa commented
> In HotSpot, CPU usage for JVM would be calculated at `get_jvm_tickes()` in os_perf_linux.cpp . It refers `/proc/self/stat` - should we refer it in same way?
> 
> I discussed about similar issue in #4299 , then we came to an agreement that we should refactor that HotSpot and JMX should share the code. Of course you can fix JMX only in this PR, but it still uses different implementation from HotSpot. I prefer to fix it in code consolidation between HotSpot and JMX.

Yes, we need a bug to track this work (or at least decide on a plan of action - if any). I wouldn't conflate this into this bug, though as it's not clear whether or not JFR/thread dumps should report container values. I'll try to create a bug for this consolidation effort today.

2021-07-07 10:34 UTC, jerboaa commented
> This patch seems fine in principle [...]

Let me revise this. It looks like imposing CPU limits via cpuset-cpus would go down a path which won't have this fixed with the current patch.

2021-07-08 03:47 UTC, xpbob commented
> > This patch seems fine in principle [...]
> 
> Let me revise this. It looks like imposing CPU limits via cpuset-cpus would go down a path which won't have this fixed with the current patch.

use (getProcessCpuLoad0() * totalCPUs / containerCPUs) for CPU limits via cpuset-cpus

2021-07-09 14:19 UTC, jerboaa requested changes
Thanks for the update. `getProcessCpuLoad()` and `getCpuLoad()` looks way too similar to me. Is there a way to make them more generic and do the process vs. system paths as needed? I think there is.

2021-07-12 03:46 UTC, xpbob commented
> Thanks for the update. `getProcessCpuLoad()` and `getCpuLoad()` looks way too similar to me. Is there a way to make them more generic and do the process vs. system paths as needed? I think there is.

use getCpuLoadWithTarget for process and system

2021-07-12 13:19 UTC, jerboaa commented
> > Thanks for the update. `getProcessCpuLoad()` and `getCpuLoad()` looks way too similar to me. Is there a way to make them more generic and do the process vs. system paths as needed? I think there is.
> 
> use getCpuLoadWithTarget for process and system

Thanks. We are getting there. I've proposed a PR to your branch which makes this a bit easier to read:
https://github.com/xpbob/jdk/pull/1

If you merge that it'll show up in this PR.

2021-07-13 06:01 UTC, xpbob commented
> > > Thanks for the update. `getProcessCpuLoad()` and `getCpuLoad()` looks way too similar to me. Is there a way to make them more generic and do the process vs. system paths as needed? I think there is.
> > 
> > 
> > use getCpuLoadWithTarget for process and system
> 
> Thanks. We are getting there. I've proposed a PR to your branch which makes this a bit easier to read:
> [xpbob#1](https://github.com/xpbob/jdk/pull/1)
> 
> If you merge that it'll show up in this PR.

Thank you so much @jerboaa .

Code has been merged.
I tested the following cgroup scenario on Linux/x64 and all passed.
```
  cpu-quota=50000 cpu-period=50000 
  cpuset-cpus=0-2
  cpu.shares=2048
  cpuset-cpus=3
```

2021-07-13 06:01 UTC, xpbob commented
/Contributor add @jerboaa

2021-07-13 06:03 UTC, xpbob commented
/test

2021-07-13 13:07 UTC, jerboaa commented
https://github.com/jerboaa/jdk/actions/runs/1026610314 is a pre-integration run of this.

2021-07-13 15:09 UTC, jerboaa approved these changes
Except for the missing comments in the new code blocks this looks good to me.

2021-07-13 15:09 UTC, jerboaa commented on src/jdk.management/unix/classes/com/sun/management/internal/OperatingSystemImpl.java
> +            } else {
The old code had these comments here. We should add them as they're still relevant:

```
                // If CPU quotas and shares are not active then find the average system load for
                // all online CPUs that are allowed to run this container.

                // If the cpuset is the same as the host's one there is no need to iterate over each CPU
```

2021-07-13 15:09 UTC, jerboaa commented on src/jdk.management/unix/classes/com/sun/management/internal/OperatingSystemImpl.java
> +                    if (cpuSet == null) {
Please add the comment as it was in the original code:

```
                        // cgroups is mounted, but CPU resource is not limited.
                        // We can assume the VM is run on the host CPUs.
```

2021-07-14 07:38 UTC, jerboaa approved these changes
Still looks good.

2021-07-16 02:12 UTC, xpbob commented
May I get a second review for this change?  Thanks.

2021-07-28 02:26 UTC, xpbob commented
/integrate

2021-07-28 02:35 UTC, DamonFool commented
Will sponsor it tomorrow if there is no objection.
Thanks.

2021-07-28 23:10 UTC, DamonFool commented
/sponsor

2021-07-28 23:12 UTC, closed without merging