8269598: Regressions up to 5% on aarch64 seems due to JDK-8268858
openjdk/jdk pull request #4766
Opened 2021-07-13 12:55 UTC by JoshuaZhuwj

Hi,

Please review this change.
It fixes the SPECjvm2008 regression on aarch64 caused by JDK-8268858.

Compressor::compress() in case "compress" of SPECjvm2008 performed
degraded by 5% due to extra spillings. There existed an LRG that covered
almost the entire function, hence it interfered with more live ranges.
These interferences caused the LRG no freedom and lastly RA had to spill
it to stack. After the fix, the LRG is split into two shorter live
ranges. Both LRGs are assigned to registers due to fewer interferences.

See details at: http://cr.openjdk.java.net/~jzhu/8269598/analysis.pdf
OptoAssembly: http://cr.openjdk.java.net/~jzhu/8269598/

The root cause is:
When PreserveFramePointer is off, frame pointer is allocatable, but
different from other SOC registers, it is excluded from fatproj's mask
because its save type is No-Save. Therefore fatproj was not treated as
high-pressure transition point in the previous int_pressure_limit()
computation. This fix ensures high pressure at fatproj when
PreserveFramePointer is off. See check_pressure_at_fatproj() [1].

After this fix, the regression disappeared.
The result of regression cases in SPECjvm2008:
    http://cr.openjdk.java.net/~jzhu/8269598/Book1.pdf

[1] https://github.com/openjdk/jdk/blob/375fc2a2b29c454b36d3ae068a080b28f6ec04e9/src/hotspot/share/opto/chaitin.hpp#L620

Best Regards,
Joshua

2021-07-13 16:08 UTC, vnkozlov approved these changes
Good.

2021-07-13 21:51 UTC, dean-long requested changes
I don't understand why aarcht64 needs these adjustments but x86 does not.  Both are doing the same tricks with PreserveFramePointer, right?

2021-07-14 09:11 UTC, JoshuaZhuwj commented
> I don't understand why aarcht64 needs these adjustments but x86 does not. Both are doing the same tricks with PreserveFramePointer, right?

Yes. If make the same adjustment on x86, the same wide LRG in
Compressor::compress() will also be split and be assigned to register
just like aarch64.

But this adjustment is a trade-off in my opinion. Lowering pressure
threshold would also bring unnecessary spillings in some scenarios,
result in performance degradation especially on x86 platform that has
a small quantity of GPRs. On aarch64 that has more GPRs, the benefits
of lowering pressure threshold by 1 or 2 outweigh the disadvantages.

I also performed the same SPECjvm2018 "compress" test on x86_64.
Compared to 5% performance improvement on aarch64, the same adjustment
degraded performance by 1.28% nevertheless.

2021-07-14 20:11 UTC, dean-long approved these changes

2021-07-15 01:49 UTC, JoshuaZhuwj commented
Thanks @vnkozlov @dean-long for your review.

2021-07-15 01:49 UTC, JoshuaZhuwj commented
/integrate

2021-07-15 01:55 UTC, kelthuzadx commented
/sponsor

2021-07-15 01:57 UTC, closed without merging

2021-07-15 20:39 UTC, dean-long commented
@JoshuaZhuwj Please try SPECjvm2008 compress on x86/x64 with -XX:+PreserveFramePointer.  We are seeing a regression after JDK-8268858.

2021-07-16 02:27 UTC, JoshuaZhuwj commented
@dean-long Thanks for your information. Previously I already found performance degradation with -XX:+PreserveFramePointer in Alibaba Flink Nexmark benchmark. It's caused by inefficient codes generated by RA. That's why I begin working on register pressure. I already created JDK-8270808 [1] to track it. Meanwhile I will also track your mentioned regression issue together with it. Hope they're caused by the same reason.

[1] https://bugs.openjdk.java.net/browse/JDK-8270808

2021-07-16 12:20 UTC, JoshuaZhuwj commented
> @JoshuaZhuwj Please try SPECjvm2008 compress on x86/x64 with -XX:+PreserveFramePointer. We are seeing a regression after JDK-8268858.

Just now I ran six rounds of "compress" on x64 machine with "-XX:+PreserveFramePointer".
Thread number of "compress" test is configured as 1 in my testing environment.
See result at http://cr.openjdk.java.net/~jzhu/8269598/Book2_x86.pdf
There is no regression in my testing. How about yours?