8270446: Remove the MemBarNode that has been optimized from the current block
openjdk/jdk pull request #4774
Opened 2021-07-14 07:35 UTC by sunny868

Hi all,
aarch64 and mips64 also had an optimization to merge two memory barrier instructions. But when I use the args -XX:+UnlockDiagnosticVMOptions -XX:+PrintOptoAssembly, I see some information like the following 

1a0 membar_release 
            dmb ish 
1a4 membar_release 
            dmb ish 
1a4 spill R19 -> R0 # spill size = 64 

Here, "1a4 membar_release" is actually optimized out . so I think it should be better to display it like this 

1a0 membar_release 
            dmb ish 
1a4 spill R19 -> R0 # spill size = 64

Please review this trivial change.

Thanks,
Sun Guoyun

2021-07-14 15:49 UTC, vnkozlov requested changes
Modifying block during emit phase could be dangerous. These empty membars still used for instructions ordering.

And your case should be handled already:
https://github.com/openjdk/jdk/blob/master/src/hotspot/cpu/aarch64/aarch64.ad#L8517

`-XX:+PrintOptoAssembly` output should be `"membar_release (elided)"`
Please, look why it is not the case.

2021-07-15 08:03 UTC, sunny868 commented
-XX:+PrintOptoAssembly output really has many "membar_release (elided)"，but also have some continuous  and same type "membar_release "，and they've actually been optimized in this patch http://hg.openjdk.java.net/jdk/hs/rev/8f1bc5a0d16d

2021-07-15 08:13 UTC, sunny868 commented
For continuous and same type membar, like"membar_release "，maybe http://hg.openjdk.java.net/jdk/hs/rev/8f1bc5a0d16d was also only a workround. I`ll try to fix it in share/opto.

2021-07-15 12:16 UTC, theRealAph commented
> For continuous and same type membar, like"membar_release membar_release"，maybe http://hg.openjdk.java.net/jdk9/jdk9/hotspot/rev/93ae449c9b52 was also only a workround. I`ll try to fix it in share/opto.

It was actually fixed by this:
http://hg.openjdk.java.net/jdk/hs/rev/8f1bc5a0d16d

And no, I agree with Vladimir. There's nothing to fix. OptoAssembly isn't supposed to be the exact instructions we generate: PrintAssembly does that.

2021-07-15 20:03 UTC, vnkozlov commented
Yes, if you want to see exact generated assembler you should use `-XX:+PrintAssembly`.
If you really want to fix OptoAssembly output for this case I would suggest to adjust `unnecessary_release()` method for this case if possible. But I don't see big benefit from this because you can see from addresses in output that code is empty.

2021-07-16 02:33 UTC, sunny868 commented
Thank you very much for your explanation.
But  I know that ` -XX:+PrintAssembly` can see that continuous barrier instructions have been removed, while `-XX:+PrintOptoAssembly` does not see this change. Maybe you don't think it's a problem, so I should close this PR ?

2021-09-10 04:30 UTC, closed without merging