JDK-8270308: Amalloc aligns size but not return value
openjdk/jdk pull request #4784
Opened 2021-07-14 17:26 UTC by tstuefe

2021-07-19 13:31 UTC, coleenp requested changes
I think you made this too general and too complicated and I don't see the benefit.
Thank you for writing the gtests though.  It was an area where they were missing.

2021-07-19 13:31 UTC, coleenp commented on test/hotspot/gtest/memory/test_arena.cpp
> +  void* p1 = ar.Amalloc(1);   // just one byte, leaves _hwm unaligned at offset 1
No I don't want this.  Amalloc should still round up the allocation size to 64 bits, then return the pointer aligned to 64 bits.
The test that I was going to write is 
p1  = AmallocWords(4)
p2 = Amalloc(some size that gets aligned to 64 bits)
verify p2 is 64 bit aligned.

I don't want _hwm to ever be unaligned.

2021-07-19 16:35 UTC, tstuefe commented on src/hotspot/share/memory/arena.hpp
> +  //  necessary. In debug builds, those paddings will be zapped with a pattern ('GGGG..').
No, `_hwm` is not aligned. It points to the address beyond the last allocation (like it did before). 

`_hwm` is X + y, with X being the last allocation start address, aligned as the last caller wanted, and y being the length of the allocation, which does not have to be aligned to anything.

If the last allocation was "allocate 5 bytes at a 64byte boundary" (e.g. for a 5-char string in the resource area),  the resulting _hwm would be X+5. It is unaligned. Any follow-up allocation requiring an alignment > 1 needs padding, and at that moment the pad is added before the next allocation.

2021-07-19 16:55 UTC, tstuefe commented
> I think you made this too general and too complicated and I don't see the benefit.
> Thank you for writing the gtests though. It was an area where they were missing.

Hi Coleen,

thank you for looking at this. Honestly, I think this is simpler than it looks. 

Bear with me:

The benefit of having the caller choose the alignment would be to allow the caller to allocate with tighter alignments than 64bit, wasting less space. Currently, the vast majority of allocations use NEW_RESOURCE_ARRAY in allocation.hpp, which just allocates with 64bit alignment. For many allocations, this alignment is unnecessary. For example, strings need no alignment at all. If you repeatedly put strings into RA, you may waste a lot of memory due to this alignment. And we put a lot of strings into RAs. I should probably measure how much space we really waste this way.

(Side note, due to the fact that Arenas use C-heap, and the fact that the glibc caches way too aggressively, the JVM never really recovers from spikes in arena usage. See also https://github.com/openjdk/jdk/pull/4510. We even have a proprietary patch at SAP where we switched to mmap() forCompilerarenas for that very reason. So, reducing the Arena footprint is actually worthwhile).

ATM we allow two alignments, pointer size and 64bit. But you cannot actually mix those since you may end up with unaligned allocations - the original bug. So the fix for that would be to correctly align at allocation time. I thought allowing just any alignment would be even simpler, and might make it possible later on have something like, say, a NEW_RESOURCE_ARRAY_1 to allocate unaligned space for strings which need no alignment at all.

----

However, if you don't like this, here is a different proposal. We could make the alignment a property of an arena: every arena has a fixed allocation alignment, that's what you get when allocating. Things like HandleAreas would have pointer-sized alignments, since allocating with a different alignment makes no sense there and introduces errors (alignment gaps would be misinterpreted as oops). Thread ResourceAreas could be 64bit aligned. That way, we even could reduce the number of Amalloc.. functions to just one: Amalloc(). Which would allocate with whatever default alignment the arena has.

That way we don't benefit from tighter packing, but the code would be simpler and more correct and safer. Since you cannot mix different alignments, _hwm would never be unaligned.

Cheers, Thomas

2021-07-20 04:01 UTC, tstuefe commented
I decided to withdraw this patch and to provide a minimal version in a separate PR.

2021-07-20 04:01 UTC, closed without merging