8269753: Misplaced caret in PatternSyntaxException's detail message
openjdk/jdk pull request #4906
Opened 2021-07-26 18:10 UTC by igraves

Fixes a bug where carets aren't indented correctly in PatternSyntaxException messages because tab characters are converted to spaces in their indentation.

2021-07-26 18:10 UTC, igraves commented
@pavelrappo

2021-07-26 19:46 UTC, pavelrappo requested changes

2021-07-26 19:46 UTC, pavelrappo commented on src/java.base/share/classes/java/util/regex/PatternSyntaxException.java
> +                sb.append((pattern.charAt(i) == '\t') ? '\t' : ' ');
In contrast with https://github.com/igraves/jdk/blob/2609dd9618dd43ea0de9abe3e3100262d09c079c/src/jdk.compiler/share/classes/com/sun/tools/javac/util/AbstractDiagnosticFormatter.java#L324, this code uses `StringBuilder.append(char)`, which might be even cleaner; good.

2021-07-26 19:46 UTC, pavelrappo commented on test/jdk/java/util/regex/RegExTest.java
> +        report("Correct caret indentation for patterns with tabs");
`report` will not be reached on success; this is different from how `report` is used in the rest of the file. Also: `report` seems to be stateful in that it resets the `failCount`.

2021-07-26 19:46 UTC, pavelrappo commented on test/jdk/java/util/regex/RegExTest.java
> +            if(message.contains(sep + "\t ^")){
```suggestion
            if (message.contains(sep + "\t ^")) {
```

2021-07-26 22:09 UTC, pavelrappo approved these changes

2021-07-27 02:23 UTC, igraves commented
/integrate

2021-07-27 02:25 UTC, closed without merging