8272231 G1: Refactor G1CardSet::get_card_set to return G1CardSetHashTableValue*
openjdk/jdk pull request #5072
Opened 2021-08-10 15:11 UTC by walulyai

Hi all,

Please review this change to return G1CardSetHashTableValue* from G1CardSet::get_card_set. Consequently, we do not have to use G1CardSet::get_or_add_card_set in instances where we only need to get the table entry (such as in G1CardSet::transfer_cards_in_howl).

Testing: Tier 1-5.

2021-08-10 19:56 UTC, tschatzl approved these changes
Lgtm.

2021-08-16 09:16 UTC, kimbarrett requested changes

2021-08-16 09:16 UTC, kimbarrett commented on src/hotspot/share/gc/g1/g1CardSet.cpp
> +    G1CardSetHashTableValue* _value = nullptr;
Non-static data member initializers (http://www.open-std.org/JTC1/SC22/WG21/docs/papers/2008/n2756.htm) have not (yet) been approved for use in HotSpot.  Needs to be initialized in a constructor.

2021-08-16 09:16 UTC, kimbarrett commented on src/hotspot/share/gc/g1/g1CardSet.cpp
> +    G1CardSetHashTableValue* table_entry = get_card_set(card_region);
Maybe there should be an assert here that `table_entry` is non-null.

2021-08-16 11:06 UTC, kimbarrett approved these changes

2021-08-16 13:08 UTC, walulyai commented
Thanks @kimbarrett and @tschatzl for the reviews!

/integrate

2021-08-16 13:09 UTC, closed without merging