8272342: [TEST_BUG] java/awt/print/PrinterJob/PageDialogMarginTest.java catches all exceptions
openjdk/jdk pull request #5115
Opened 2021-08-13 19:23 UTC by rajamah

Removed try catch block so the test can function as expected and fail
when it ought to, rather than passing all the time because of catch
block catching all exceptions and Passing test even there is a failure.

2021-08-13 19:44 UTC, aivanov-jdk requested changes
Please add
```java
    Locale.setDefault(Locale.US);
```
as the first line in `main()`, otherwise the Page Format dialog uses millimetres instead of inches for non-US locales.

Please resolve IDE warnings:
1. Use Java style array declaration in main: `String[] args`.
2. Line 51: Casting 'null' to 'Component' is redundant.
3. Line 50: Statement lambda can be replaced with expression lambda.

Please update the copyright year.

2021-08-13 19:44 UTC, aivanov-jdk commented on test/jdk/java/awt/print/PrinterJob/PageDialogMarginTest.java
> +        pf = pj.pageDialog(aset);
I suggest merging these two lines:
```suggestion
        PageFormat pf = pj.pageDialog(aset);
```

2021-08-14 01:12 UTC, rajamah commented on test/jdk/java/awt/print/PrinterJob/PageDialogMarginTest.java
> +        pf = pj.pageDialog(aset);
Made the changes you asked.

2021-08-14 18:33 UTC, pankaj-bansal approved these changes

2021-08-15 10:27 UTC, aivanov-jdk requested changes

2021-08-15 10:27 UTC, aivanov-jdk commented on test/jdk/java/awt/print/PrinterJob/PageDialogMarginTest.java
> + * Copyright (c) 2016, 2021,  Oracle and/or its affiliates. All rights reserved.
```suggestion
 * Copyright (c) 2016, 2021, Oracle and/or its affiliates. All rights reserved.
```
Two many spaces, there should be one space after the comma.

2021-08-15 10:27 UTC, aivanov-jdk commented on test/jdk/java/awt/print/PrinterJob/PageDialogMarginTest.java
> +import java.text.MessageFormat;
I wonder where do DialogTypeSelection and MessageFormat come from?

The imports should be sorted by default, usually your IDE handles it perfectly on its own.

2021-08-16 20:49 UTC, aivanov-jdk approved these changes

2021-08-16 21:24 UTC, rajamah commented
/integrate

2021-08-16 22:22 UTC, aivanov-jdk commented
/sponsor

2021-08-16 22:24 UTC, closed without merging