8272563: Possible assertion failure in CardTableBarrierSetC1
openjdk/jdk pull request #5164
Opened 2021-08-18 12:37 UTC by fmatte1

This patch is proposed by the submitter of the bug - ugawa@ci.i.u-tokyo.ac.jp

The method CardTableBarrierSetC1::post_barrier generates a move LIR when TwoOperandLIRForm flag is true to move the address to be marked in the card table to a temporary register.
> __ move(addr, tmp);
However, this code only guarantees that `addr` is a valid register for LIR, which can be a virtual register. If the virtual register for `addr` is spilled to the stack by chance, the `move(addr, tmp)` is compiled to a memory-to-register which causes an assertion failure because a memory-to-register move requires their arguments to have the same size. 
The fix is to check if it is is_oop() and call the mov appropriately.

No issues found in local testing and Mach5 tier1-3

2021-08-18 12:40 UTC, fmatte1 commented
/label hotspot-gc hotspot-compiler

2021-08-20 06:25 UTC, TobiHartmann requested changes
Using an additional register + move does not seem right to fix this.

The problem is that `addr->type()` is `T_OBJECT` and the type of the virtual register `tmp` is `T_LONG`, right?

What about this?
```
LIR_Opr tmp = gen->new_register(addr->type());
```
Could the reporter provide a reproducer?

2021-08-30 08:30 UTC, fmatte1 commented
Hi Igor, 

Thanks for looking into this and thanks for the pointers to handle the spills in logic involved in T_OBJECT to T_LONG mov's and Also to check the src and dst must have the registers.
These conditions can be handled using asserts/guarantee's (as the function doesn't return). 
But as original patch suggests we can have solution by copying over extra temp register. 

In https://github.com/openjdk/jdk/blob/d732c3091fea0a7c6d6767227de89002564504e5/src/hotspot/share/c1/c1_LinearScan.cpp#L1135 It was not handled and enfornced we must have both registers. So I am not sure if we also can handle this scenario or it can be prevented as done in c1_LinearScan.cpp file.

Thanks,

2021-08-30 15:47 UTC, veresov commented
Well, an extra temp register won't solve it, right? You're just getting lucky that tmp2 is not getting spilled. If that happens you get exactly the same situation as before, don't you?

2021-08-31 03:27 UTC, fmatte1 commented
yes that's being the case. 
I got your point, will try to add guarantees to handle this scenario and propose the solution after testing

2021-08-31 04:36 UTC, veresov commented
Oh, hey! Another much easier idea. Do it with a `lea`.

```
LIR_Address* addr_addr = new LIR_Address(addr, addr->type());
__ leal(addr_addr, tmp);
```
It will force `addr` into a register. And no need to mess  with the register allocator.

2021-08-31 14:56 UTC, fmatte1 commented
Hi Igor, 

Possibly you mean this,
`      LIR_Opr addr_opr = LIR_OprFact::address(new LIR_Address(addr, addr->type()));
      __ leal(addr_opr, tmp);`
I have updated the patch with this fix and there is no issue in hs-tier1 to hs-tier3

2021-08-31 16:57 UTC, veresov commented
Good. You don't actually need to check if it's an oop or not. You can just do `leal` for all the types.

2021-09-01 05:52 UTC, fmatte1 commented
Thanks, updated the patch.

2021-09-01 06:49 UTC, veresov commented on src/hotspot/share/gc/shared/c1/cardTableBarrierSetC1.cpp
>      __ move(addr, tmp);
You don't need the move anymore.

2021-09-01 06:52 UTC, fmatte1 commented on src/hotspot/share/gc/shared/c1/cardTableBarrierSetC1.cpp
>      __ move(addr, tmp);
ok, will remove that.

2021-09-01 07:03 UTC, veresov commented
Looks good!

2021-09-01 07:03 UTC, veresov approved these changes

2021-09-01 08:53 UTC, fmatte1 commented
/integrate

2021-09-01 10:10 UTC, TobiHartmann approved these changes
Looks good to me too!

2021-09-01 10:10 UTC, TobiHartmann commented
/sponsor

2021-09-01 10:12 UTC, closed without merging