8265489: RunThese24H.java times out because of long ObjectSynchronizer::monitors_iterate(...) operation
openjdk/jdk pull request #5194
Opened 2021-08-19 21:18 UTC by lmesnik

monitors_iterate make several checks which often are true before filter monitor by a thread. It might take a lot of time when there are a lot of threads. So it makes sense to first check thread and only then other conditions.

2021-09-03 02:32 UTC, dcubed-ojdk requested changes

2021-09-08 03:33 UTC, dcubed-ojdk commented on src/hotspot/share/runtime/synchronizer.cpp
> +    }
Thanks for resolving the above comment.

2021-09-08 03:38 UTC, dcubed-ojdk approved these changes
Moving the thread check from the closure's do_monitor() call
into monitors_iterate() as early as possible is a good idea.

Do you have any measurements to show how much this helps?
I'm okay if you don't and I'd be happy waiting to see if it makes
a difference with some of those Tier8 timeouts...

2021-09-08 19:30 UTC, lmesnik commented
I run stress tests several times on linux-x64 with ParallelGC and haven't seen timeout anymore.

2021-09-08 19:30 UTC, lmesnik commented
/integrate

2021-09-08 19:31 UTC, closed without merging