JDK-8273142 : Remove dependancy of TestHttpServer, HttpTransaction, HttpCallback
openjdk/jdk pull request #5352
Opened 2021-09-02 17:30 UTC by mahendrachhipa

Dependencies of TestHttpServre, HttpTransaction, HttpCallback are removed from following tests:
open/test/jdk/sun/net/www/protocol/http/ResponseCacheStream.java
open/test/jdk/sun/net/www/protocol/http/SetChunkedStreamingMode.java
open/test/jdk/sun/net/www/protocol/http/RelativeRedirect.java
open/test/jdk/sun/net/www/protocol/http/B6296310.java

2021-09-29 11:02 UTC, Michael-Mc-Mahon requested changes

2021-09-29 13:45 UTC, mahendrachhipa commented on test/jdk/sun/net/www/protocol/http/B6296310.java
> +         }
Hi @Michael-Mc-Mahon , In my understanding purpose of this block is to return a file with no contents.(Empty file).

2021-09-29 19:24 UTC, Michael-Mc-Mahon commented on test/jdk/sun/net/www/protocol/http/B6296310.java
> +         }
I think it would be simpler to replace lines 101-103 just with `trans.close()`

2021-09-30 09:05 UTC, dfuch commented on test/jdk/sun/net/www/protocol/http/B6296310.java
> +         }
Strictly speaking to preserve the current behavior - that would be `trans.getResponseBody().close();` isn't it?

2021-09-30 10:49 UTC, Michael-Mc-Mahon commented on test/jdk/sun/net/www/protocol/http/B6296310.java
> +         }
HttpExchange.close() calls the close method on both streams and closing the output stream implicitly closes the input stream. So, they are equivalent.

2021-09-30 11:02 UTC, Michael-Mc-Mahon approved these changes

2021-09-30 11:05 UTC, mahendrachhipa commented
/integrate

2021-09-30 11:26 UTC, mahendrachhipa commented
/sponsor

2021-09-30 11:27 UTC, Michael-Mc-Mahon commented
/sponsor

2021-09-30 11:29 UTC, closed without merging