8273450: Fix the copyright header of SVML file
openjdk/jdk pull request #5399
Opened 2021-09-07 20:25 UTC by sviswa7

Fix the copyright header of SVML files to match others.

2021-09-07 20:30 UTC, sviswa7 commented
/label core-libs

2021-09-07 23:08 UTC, dholmes-ora requested changes
Hi Sandhya,

You must not change another company's copyright line, so "All rights reserved" needs to be removed again.

Thanks,
David

2021-09-07 23:08 UTC, dholmes-ora commented on src/jdk.incubator.vector/linux/native/libsvml/svml_d_acos_linux_x86.S
> + * Copyright (c) 2018, 2021, Intel Corporation. All rights reserved.
You must not change another company's copyright line.

2021-09-07 23:19 UTC, sviswa7 commented
@dholmes-ora I am from Intel so editing the Intel copyright line should be ok?

2021-09-07 23:39 UTC, dholmes-ora commented
@sviswa7 My apologies, I hadn't realized you worked for Intel. But note that other Intel files i.e. ./hotspot/cpu/x86/macroAssembler_x86_*.cpp also do not have "All rights reserved".

David

2021-09-08 00:43 UTC, sviswa7 commented
Thanks a lot @dholmes-ora for the review.

2021-09-08 02:03 UTC, PaulSandoz approved these changes

2021-09-08 16:06 UTC, sviswa7 commented
Thanks a lot @PaulSandoz for the review.

2021-09-08 16:07 UTC, sviswa7 commented
/integrate

2021-09-08 16:07 UTC, closed without merging