JDK-8273979: move some os time related functions to os_posix for POSIX platforms
openjdk/jdk pull request #5582
Opened 2021-09-20 13:16 UTC by MBaesken

There are a couple of time related functions in os_<platform> for Linux, BSD+Mac and AIX that are pretty similar (or identical) across the platforms and can be centralized in os_posix .
While doing so, I noticed that  os::supports_vtime()   returns always true , on Posix and also on Windows, so we might remove it completely if this prefered ? 

Best regards , Matthias

2021-09-21 06:15 UTC, dholmes-ora requested changes
Hi Matthias,

Generally this refactoring looks good, though I have a request to restore some of the code - see comments below. Also could you clarify where functions were only "pretty similar" rather than identical as we don't want to introduce subtle incompatibilities.

I think supports_vtime() could probably be removed in a separate RFE.

Thanks,
David

2021-09-21 06:15 UTC, dholmes-ora commented on src/hotspot/os/bsd/os_bsd.cpp
> -void os::javaTimeNanos_info(jvmtiTimerInfo *info_ptr) {
Please restore as per previous comment.

2021-09-21 06:15 UTC, dholmes-ora commented on src/hotspot/os/posix/os_posix.cpp
> +#endif
Can't we just defer the conditional initialization to the init() function where we already have to conditionally initialise.

2021-09-21 07:14 UTC, dholmes-ora approved these changes
Thanks Matthias - updates look good.

David

2021-09-21 07:42 UTC, MBaesken commented
Hi David, I brought back os::javaTimeNanos_info  following your suggestion and adjusted the initialization of  'clock_tics_per_sec ' in os_posix.

>Also could you clarify where functions were only "pretty similar" rather than identical as we don't want to introduce subtle incompatibilities
Sure, went through them and this is what I found
os::elapsedTime()      identical except comment
os::elapsed_counter()   identical
os::elapsed_frequency() identical
os::supports_vtime()          identical
os::getTimesSecs         identical
os::local_time_string  identical
os::localtime_pd   identical

>I think supports_vtime() could probably be removed in a separate RFE.

OK, I opened https://bugs.openjdk.java.net/browse/JDK-8274051  .

2021-09-22 07:55 UTC, RealLucy requested changes

2021-09-22 08:13 UTC, RealLucy approved these changes
My previous comment about clock_ticks_per_sec is obsolete. Just saw the initialisation in os::Posix::init(void) now is the same as in os::init(). The static init value is in effect only for the short time until os::init() is invoked. 
Looks good to me.

2021-09-22 08:17 UTC, MBaesken commented
> My previous comment about clock_ticks_per_sec is obsolete. Just saw the initialisation in os::Posix::init(void) now is the same as in os::init(). The static init value is in effect only for the short time until os::init() is invoked.
> Looks good to me.

Hi Lutz, thanks for the review .
In case of worries about  the short time frame between  posix and linux init functions, we could introduce 'os::clock_ticks_per_sec()'  and  move this to os_linux, os_aix os_bsd  etc. to have the initialization at one single point.
Not sure if this is worth the effort?

Best regards, Matthias

2021-09-22 08:21 UTC, RealLucy commented
I would not add this complexity. Just leave it as it is.

2021-09-23 05:33 UTC, MBaesken commented
/integrate

2021-09-23 05:34 UTC, closed without merging

2024-08-28 15:26 UTC, rvansa commented
/backport jdk17u-dev