8274069: Clean up g1ParScanThreadState a bit
openjdk/jdk pull request #5607
Opened 2021-09-21 11:39 UTC by tschatzl

Hi all,

  can I have reviews for this change that does some minor refactoring for issues found in JDK-8271880/PR#5037:

- remove declaration without definition
- move inlined code into hpp file
- factor out some code

Testing: gha, local compilation, local gc/g1

Thanks,
  Thomas

2021-09-21 12:02 UTC, kstefanj approved these changes
👍

2021-09-21 14:23 UTC, albertnetymk approved these changes
The old name, `enqueue_card_after_barrier_filters`, is still referenced in the comments.

(I also wonder if it makes sense to unify all callers of `enqueue_card_if_tracked` to use `write_ref_field_post` with template non-type arguments. Not in *this* PR ofc.)

2021-09-21 15:22 UTC, kimbarrett requested changes
Does this change allow this inclusion of an .inline.hpp to be moved out of the .hpp?
33 #include "gc/g1/heapRegionRemSet.inline.hpp"

2021-09-21 15:22 UTC, kimbarrett commented on src/hotspot/share/gc/g1/g1ParScanThreadState.hpp
> +  // if the barrier (same region, not from survivor) does not filter out not find
I don't understand this comment; seems like there's a grammar or wording problem.

2021-09-21 16:11 UTC, tschatzl commented
> Does this change allow this inclusion of an .inline.hpp to be moved out of the .hpp?
> 33 #include "gc/g1/heapRegionRemSet.inline.hpp"

In the latest change I also touched up includes in that file a bit. Nothing about heapRegionRemSet has been used in that file...

2021-09-21 22:08 UTC, kimbarrett approved these changes
Looks good.

2021-09-22 11:40 UTC, tschatzl commented
Thanks @albertnetymk @kstefanj @kimbarrett for your reviews.

/integrate

2021-09-22 11:43 UTC, closed without merging