8254265: s390 and linux 32 bit builds broken
openjdk/jdk pull request #568
Opened 2020-10-08 19:29 UTC by TheRealMDoerr

JDK-8253717 missed 2 ocurrances of JavaThread::stack_guard_zone_size() which was moved to class StackOverflow.

I just verified s390 build. Can anybody check linux 32 bit?

2020-10-08 20:59 UTC, coleenp commented
I'm sorry, I really thought I'd built all the platforms.  Trying to figure out what happened.  This change looks good.  I'm trying to verify linux-32 bit now.

2020-10-08 21:00 UTC, coleenp approved these changes

2020-10-08 22:19 UTC, dholmes-ora approved these changes

2020-10-08 22:49 UTC, coleenp requested changes

2020-10-08 22:49 UTC, coleenp commented on src/hotspot/os_cpu/linux_x86/os_linux_x86.cpp
> +                       (StackOverflow::stack_guard_zone_size() + page_size));
Lines 841 and 842 also need to be fixed.  Still testing.

2020-10-08 22:57 UTC, coleenp commented
Also could you change this too?
diff --git a/src/hotspot/os/linux/os_linux.cpp b/src/hotspot/os/linux/os_linux.cpp
index 85560cc..cf20034 100644
--- a/src/hotspot/os/linux/os_linux.cpp
+++ b/src/hotspot/os/linux/os_linux.cpp
@@ -1935,7 +1935,7 @@ void * os::Linux::dll_load_in_vmthread(const char *filename, char *ebuf,
       StackOverflow* overflow_state = jt->stack_overflow_state();
       if (!overflow_state->stack_guard_zone_unused() &&     // Stack not yet fully initialized
           overflow_state->stack_guards_enabled()) {         // No pending stack overflow exceptions
-        if (!os::guard_memory((char *)jt->stack_end(), overflow_state->stack_guard_zone_size())) {
+        if (!os::guard_memory((char *)jt->stack_end(), StackOverflow::stack_guard_zone_size())) {
           warning("Attempt to reguard stack yellow zone failed.");
         }
       }

2020-10-09 07:39 UTC, RealLucy requested changes
Change looks good, but is complete only when you adapt the two lines mentioned by coleenp as well.
src/hotspot/os_cpu/linux_x86/os_linux_x86.cpp:
      limit += JavaThread::stack_red_zone_size() +
        JavaThread::stack_yellow_zone_size();

2020-10-09 09:52 UTC, TheRealMDoerr commented
Thanks for reviewing and checking linux 32 bit. x86_32 is not among the supported dev kit targets (https://openjdk.java.net/groups/build/doc/building.html) and I don't have a machine which is configured for that build, but maybe devkit does work.

2020-10-09 11:08 UTC, coleenp approved these changes
Thank you for fixing this!

2020-10-09 11:10 UTC, coleenp commented
Actually the linux-x86 build is broken because of something in the libdwp native code right now but this code compiles.
https://bugs.openjdk.java.net/browse/JDK-8254270

2020-10-09 11:51 UTC, TheRealMDoerr commented
/integrate

2020-10-09 11:51 UTC, closed without merging