Use new APIs on Windows for monitoring available clipboard formats
openjdk/jdk pull request #594
Opened 2020-10-11 19:58 UTC by xavery

This change replaces the usage of SetClipboardViewer with Add/RemoveClipboardFormatListener, introduced in Windows Vista. This makes OpenJDK immune to external applications failing to process clipboard messages properly.
I have put this proposal forward in the [mailing list](https://mail.openjdk.java.net/pipermail/awt-dev/2020-July/015990.html), which was tentatively accepted by Mr. Sergey Bylokhov.

The deficiencies of the old APIs are well known and might result in some subscribed applications not receiving notifications from the operating system, as they rely on all the applications in the current clipboard chain processing clipboard messages properly. Porting the code to use the new APIs not only makes OpenJDK immune to these issues, but also results in slightly less code needed to support clipboard-related functionality.

As this is a change that's very platform-specific, I don't think providing a unit test is practical, as it would also require providing a native application that runs alongside the test and deliberately breaks the keyboard chain, resulting in OpenJDK not being able to receive clipboard format change notifications. This is a bug/limitation of the old Windows API, not OpenJDK itself. Anyhow, the already existing ClipboardInterVMTest passes, which shows that already existing functionality is not impacted by this change.

I have prepared a proof-of-concept test which illustrates the deficiencies of the old API, however it is not integrated with the test suite, as it requires compiling a native WinAPI application. I will gladly share the source if needed.

2020-10-11 19:59 UTC, xavery commented
/signed

2020-10-15 09:52 UTC, xavery commented
/issue JDK-8254825

2020-10-25 02:51 UTC, mrserb commented
Description of possible ways to interact with a clipboard:
https://docs.microsoft.com/en-us/windows/win32/dataxchg/using-the-clipboard

> There are three ways of monitoring changes to the clipboard. The oldest method is to create a clipboard viewer window. Windows 2000 added the ability to query the clipboard sequence number, and Windows Vista added support for clipboard format listeners. Clipboard viewer windows are supported for backward compatibility with earlier versions of Windows. New programs should use clipboard format listeners or the clipboard sequence number.

The current fix proposes to change the old "clipboard viewer window" approach:
https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setclipboardviewer
https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-changeclipboardchain
To the new approach:
https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-addclipboardformatlistener

2020-10-25 02:52 UTC, mrserb commented
I have run the tests and waiting for the results, will sponsor it if the results will be good.

2020-10-25 02:55 UTC, mrserb requested changes
Please update the second date in the header of the changed files to 2020.

2020-10-25 18:38 UTC, xavery commented
> Please update the second date in the header of the changed files to 2020.

Done.

2020-10-25 22:16 UTC, mrserb approved these changes
Looks fine

2020-10-26 07:20 UTC, xavery commented
/integrate

2020-10-26 19:11 UTC, mrserb commented
/sponsor

2020-10-26 19:13 UTC, closed without merging