8276721: G1: Refine G1EvacFailureObjectsSet::iterate
openjdk/jdk pull request #6303
Opened 2021-11-09 03:49 UTC by Hamlin-Li

Currently, G1EvacFailureObjectsSet::iterate(ObjectClosure* closure) is not a const method, but it looks like a const method. It will be a surprise for reader, i.e. you would not expect that an iteration method is destructive, clearing out the set it just iterated over.
We should refine it in some way.

2021-11-09 09:13 UTC, tschatzl requested changes
I do not think this change solves what it was intended to do: `G1EvacFailureObjectsSet:handle_iteration()` is still destructive, and the rest of the changes seem to just be moving around code, and making more stuff visible in the header file, overall complicating the code imho.

What about renaming `G1EvacFailureObjectsSet:iterate` to `G1EvacFailureObjectsSet:iterate_and_drop/empty/remove`? Or, as mentioned earlier, have an explicit `drop/remove/emtpy` method in `G1EvacFailureObjectsSet` and call it appropriately?
The former would be my preferred solution because it is then called distinctively enough from a normal `iterate` method, and does not completely mess up current code.

The cause of all this may have been the decision to put `G1EvacFailureObjectsSet`, a data structure only interesting during (young) gc that needs some per-gc handling, into the permanently valid `HeapRegion` data structure - I'll handle this refactoring though as mentioned. 

Let's sync with @albertnetymk about this before continuing.

2021-11-09 09:21 UTC, albertnetymk commented
> The former would be my preferred solution

Agree; I prefer not having `iterate` in the name, sth like `process_and_drop/empty/remove`, but either is fine to me.

2021-11-09 09:23 UTC, Hamlin-Li commented
I was thinking handle_iteration() will be not that surprising for users as iterate(), but seems it's not.
Sure, let me just rename it as process_and_drop.

2021-11-09 09:31 UTC, tschatzl commented
> I was thinking handle_iteration() will be not that surprising for users as iterate(), but seems it's not. Sure, let me just rename it as process_and_drop.

The main issue I have with the current change is that this is a changeset with 160 changed lines for the purpose of renaming two methods which are each called once. That seems completely off.

2021-11-09 10:07 UTC, Hamlin-Li commented
Agree, seems it's too much code for such a trivial issue. :)

2021-11-09 10:21 UTC, tschatzl approved these changes
Lgtm apart from the one comment about the comment.

2021-11-09 10:21 UTC, tschatzl commented on src/hotspot/share/gc/g1/g1EvacFailureObjectsSet.hpp
> +  void process_and_drop(ObjectClosure* closure);
The comment needs some update, something like: "Apply the given ObjectClosure to all objects that failed evacuation and empties the list after processing. Objects are passed in increasing address order."

2021-11-09 11:11 UTC, albertnetymk approved these changes

2021-11-10 01:25 UTC, Hamlin-Li commented
Thanks @tschatzl @albertnetymk for your reviews.

/integrate

2021-11-10 01:26 UTC, closed without merging