JDK-8277382 make c1 BlockMerger use IR::verify only when necessary
openjdk/jdk pull request #6456
Opened 2021-11-18 13:30 UTC by LudwikJaniuk

This PR removes two calls to `IR::verify` which were unnecessary. The reason they are unnecessary is that `try_merge` does not always take any action. There is not need to verify if nothing has changed. In the cases that `try_merge` does do anything, it already calls `IR::verify` afterwards.

This PR also switches some deeply nested if statements in `try_merge` to early returns.

2021-11-18 13:30 UTC, LudwikJaniuk commented
Passes both tier1 and tier2 in debug build.

2021-11-22 14:22 UTC, TobiHartmann requested changes

2021-11-22 14:22 UTC, TobiHartmann commented on src/hotspot/share/c1/c1_Optimizer.cpp
> +    assert(sux_state->caller_state() == end_state->caller_state(), "caller not equal");
The indentation is wrong.

2021-11-24 12:47 UTC, LudwikJaniuk commented on src/hotspot/share/c1/c1_Optimizer.cpp
> +    assert(sux_state->caller_state() == end_state->caller_state(), "caller not equal");
done

2021-11-24 13:20 UTC, neliasso approved these changes
Looks good!

2021-11-24 16:09 UTC, LudwikJaniuk commented
/integrate

2021-11-29 06:39 UTC, TobiHartmann approved these changes
Looks good.

2021-11-29 06:39 UTC, TobiHartmann commented
/integrate

2021-11-29 06:39 UTC, TobiHartmann commented
/sponsor

2021-11-29 06:42 UTC, closed without merging