8247973: Javadoc incorrect for IdentityArrayList, IdentityLinkedList
openjdk/jdk pull request #6710
Opened 2021-12-04 03:07 UTC by anupamdev20

The documentation for following methods used object equality mentioning 'equals()'. I have replaced the equals() with == operator where necessary with some formattings.

sun.awt.util.IdentityLinkedList#contains
sun.awt.util.IdentityArrayList#contains
sun.awt.util.IdentityArrayList#indexOf
sun.awt.util.IdentityArrayList#lastIndexOf
sun.awt.util.IdentityArrayList#remove(java.lang.Object) 

Kindly review the change.

2021-12-04 17:42 UTC, aivanov-jdk commented
Was the previous PR #6694 not good enough?  
The previous PR has comments to the changes thus you should've referenced it when you created the new one.

2021-12-05 03:55 UTC, anupamdev20 commented
@aivanov-jdk The PR #6694 included HttpURLConnection too. I therefore closed that PR (https://github.com/openjdk/jdk/pull/6694#pullrequestreview-823124988) and initiated new requested with correct files and changes. As I am slightly new to git I did not know how to update the PR, so I filed a new one.

2021-12-06 16:50 UTC, aivanov-jdk commented
> @aivanov-jdk The PR #6694 included HttpURLConnection too. I therefore closed that PR ([#6694 (review)](https://github.com/openjdk/jdk/pull/6694#pullrequestreview-823124988)) and initiated new requested with correct files and changes. As I am slightly new to git I did not know how to update the PR, so I filed a new one.

You could've just reverted the changes to `HttpURLConnection` in your branch and pushed. Effectively, it would've removed the change from the PR.

2021-12-06 16:58 UTC, aivanov-jdk requested changes

2021-12-06 16:58 UTC, aivanov-jdk commented on src/java.desktop/share/classes/sun/awt/util/IdentityLinkedList.java
> + * Copyright (c) 2007, 2021 Oracle and/or its affiliates. All rights reserved.
```suggestion
 * Copyright (c) 2007, 2021, Oracle and/or its affiliates. All rights reserved.
```
There should be another comma.

2021-12-06 17:07 UTC, aivanov-jdk commented on src/java.desktop/share/classes/sun/awt/util/IdentityLinkedList.java
> + * Copyright (c) 2007, 2021 Oracle and/or its affiliates. All rights reserved.
Other than that, the changes look good.

2021-12-06 17:40 UTC, prrace approved these changes

2021-12-06 18:21 UTC, anupamdev20 commented
/integrate

2021-12-06 18:42 UTC, aivanov-jdk approved these changes

2021-12-06 18:45 UTC, aivanov-jdk commented
/sponsor

2021-12-06 18:46 UTC, closed without merging