8278289: Drop G1BlockOffsetTablePart::_object_can_span
openjdk/jdk pull request #6718
Opened 2021-12-06 10:24 UTC by albertnetymk

Simple change of dropping a debug-only field. Instead, the assert logic queries for the region type directly.

Test: tier1-5

2021-12-06 11:52 UTC, tschatzl requested changes

2021-12-06 11:52 UTC, tschatzl commented on src/hotspot/share/gc/g1/g1BlockOffsetTable.inline.hpp
> +    // For non ContinuesHumongous regions, the first obj always starts from bottom.
```suggestion
    // For non-ContinuesHumongous regions, the first obj always starts from bottom.
```

2021-12-06 11:52 UTC, tschatzl commented on src/hotspot/share/gc/g1/g1BlockOffsetTable.inline.hpp
> +    assert(offset == 0, "Found offset %u instead of 0", offset);
Please add region# too here, maybe even the region's short type string (that can be gained from the `hs_err` file though).

2021-12-07 09:12 UTC, tschatzl approved these changes
Lgtm.

2021-12-07 11:17 UTC, kstefanj approved these changes

2021-12-07 13:09 UTC, Hamlin-Li approved these changes

2021-12-07 13:33 UTC, albertnetymk commented
Thanks for the review.

/integrate

2021-12-07 13:34 UTC, closed without merging