8278548: G1: Remove unnecessary check in forward_to_block_containing_addr
openjdk/jdk pull request #6797
Opened 2021-12-10 11:36 UTC by albertnetymk

Simple change of removing an always-false `if`.

Test: I added `assert(false)` inside the `if`, and no failure in tier1-6.

2021-12-10 12:29 UTC, Hamlin-Li commented
Not sure if I'm overreact, but IMHO it might be more safe to replace it with an assert. How do you think about it?

2021-12-11 11:19 UTC, tschatzl requested changes
I would also prefer to keep an assert here.

2021-12-11 14:53 UTC, albertnetymk commented
I added an assert. However, it's quite odd to mention the klass pointer in this context: it's unclear why the klass is not null and why a non-null klass pointer is useful or required here.

2021-12-13 04:41 UTC, Hamlin-Li approved these changes
looks good.

2021-12-13 09:37 UTC, tschatzl commented
> I added an assert. However, it's quite odd to mention the klass pointer in this context: it's unclear why the klass is not null and why a non-null klass pointer is useful or required here.

Looking at `block_start`, you are right that this is not absolutely necessary, it can handle arbitrary locations (at least below TAMS) to start from. It will fail above TAMS though as the code directly accesses these objects' `size()` in that area.

Having slightly stronger assumptions, that all block starts are valid objects, does not seem to hurt.

The error message could mention something like "start of block must be an initialized object" instead?

2021-12-13 09:37 UTC, tschatzl approved these changes
Lgtm.

2021-12-13 10:17 UTC, tschatzl approved these changes
Still good.

2021-12-15 15:00 UTC, kstefanj approved these changes
Looks good.

2021-12-15 15:03 UTC, closed without merging