8261404: Class.getReflectionFactory() is not thread-safe
openjdk/jdk pull request #6870
Opened 2021-12-16 21:04 UTC by liach

Simply changes this to only read the static field once to prevent `null` on second read.

2021-12-16 21:21 UTC, RogerRiggs requested changes
It would be easier to read and clearer if the local was not named the same as the static.

2021-12-16 21:31 UTC, RogerRiggs commented on src/java.base/share/classes/java/lang/Class.java
>          }
p.s.  If using an early return, I'd have it return early in the case reflectionFactory was not-null.
then fall through to compute and assign the factory and return it.
```
        var factory = reflectionFactory;
        if (factory != null) {
            return factory;
        }
        return reflectionFactory =
            java.security.AccessController.doPrivileged
                (new ReflectionFactory.GetReflectionFactoryAction());
```

2021-12-16 22:52 UTC, mlchung approved these changes

2021-12-17 15:23 UTC, RogerRiggs approved these changes

2021-12-17 21:11 UTC, liach commented
Should've been 24 hours for people in different time zones to review.

/integrate

2021-12-17 22:22 UTC, mlchung commented
/sponsor

2021-12-17 22:23 UTC, closed without merging