8254863: Delete code leftover from old fixes
openjdk/jdk pull request #691
Opened 2020-10-16 02:31 UTC by mrserb

The fix for JDK-4893408 adds a special code to handle the "PYCC.pf" color profile for the "kernel java":
https://bugs.openjdk.java.net/browse/JDK-4893408?focusedCommentId=12284308&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-12284308
The "kernel java" support was removed in jdk7 in JDK-7016724 but the special code in the ICC_Profile.java still exists.

After the fix for JDK-8175984 a few methods became unused:
 - CMSManager#freeProfile()
 - ProfileDeferralMgr#unregisterDeferral()

2020-10-21 02:42 UTC, azuev-java approved these changes

2020-11-08 21:56 UTC, prrace requested changes
I don't think it was really for kernel. The Windows on-line jRE installer made it
an optional component.

2020-11-08 21:56 UTC, prrace approved these changes

2020-11-10 06:16 UTC, mrserb commented
/integrate

2020-11-10 06:17 UTC, closed without merging