8279008: G1: Calculate BOT threshold on-the-fly during Object Copy phase
openjdk/jdk pull request #6916
Opened 2021-12-22 12:48 UTC by albertnetymk

Simple change of unifying BOT logic for PLAB and direct allocation during GC.

Test: tier1-6; no difference observed while running BigRamTester, SPECjbb2015

2022-01-10 10:30 UTC, tschatzl approved these changes

2022-01-10 10:30 UTC, tschatzl commented on src/hotspot/share/gc/g1/g1BlockOffsetTable.inline.hpp
> +inline HeapWord* G1BlockOffsetTablePart::align_up_by_card_size(HeapWord* const addr) const{
```suggestion
inline HeapWord* G1BlockOffsetTablePart::align_up_by_card_size(HeapWord* const addr) const {
```

2022-01-19 08:41 UTC, kstefanj requested changes
Nice cleanup, not sure if I agree that it's that simple though 😉  At least it requires a lot of testing to make sure there is no regression. 

In general it looks good, I basically just have a few naming suggestions/comments. I think it would be nice to keep the terminology to use threshold rather than boundary since this is what the BOT is currently calling it.

2022-01-19 08:41 UTC, kstefanj commented on src/hotspot/share/gc/g1/g1BlockOffsetTable.inline.hpp
> +inline HeapWord* G1BlockOffsetTablePart::align_up_by_card_size(HeapWord* const addr) const {
What do you think about calling this `align_up_to_threshold()`.

2022-01-19 08:41 UTC, kstefanj commented on src/hotspot/share/gc/g1/heapRegion.hpp
> +  inline void update_bot_if_crossing_boundary(HeapWord* obj_start, size_t obj_size);
I would prefer using threshold instead of boundary here since threshold is the term used in the BOT.

2022-01-19 08:41 UTC, kstefanj commented on src/hotspot/share/gc/g1/heapRegion.inline.hpp
> +  HeapWord* cur_card_boundary = _bot_part.align_up_by_card_size(obj_start);
I think something like `next_bot_threshold` would be even more descriptive.

2022-01-20 16:05 UTC, albertnetymk commented on src/hotspot/share/gc/g1/heapRegion.inline.hpp
> +  bool cross_card_boundary = (obj_end > cur_card_boundary);
Just wanna highlight it's "strictly greater-than" and give it a meaningful name to match the method name, "XXX_if_crossing_boundary".

2022-01-20 16:47 UTC, kstefanj approved these changes

2022-01-20 17:18 UTC, albertnetymk commented
As discussed with Stefan, I will keep the term "card boundary" in this PR and remove `G1BlockOffsetTablePart::_next_offset_threshold` in a new PR, since "threshold" is too abstract and less precise.

Thanks for the review.

/integrate

2022-01-20 17:19 UTC, closed without merging