8254913: Increase InlineSmallCode default from 2000 to 2500 for x64
openjdk/jdk pull request #705
Opened 2020-10-16 17:31 UTC by ericcaspole

We have seen some specific benefits to increasing InlineSmallCode to 2500 from 2000, and across the whole promo build perf test collection the change is neutral to slightly positive, where the tests are run on modern OCI systems.

Passed tier1 testing, some ad-hoc perf testing and more compiler related parts of the weekly promo performance set.

JBS: https://bugs.openjdk.java.net/browse/JDK-8254913
Thanks,
Eric

2020-10-16 17:33 UTC, cl4es approved these changes
LGTM!

2020-10-16 20:47 UTC, AzeemJiva commented
Do you have any results?  Changing defaults without published results makes the process opaque.

2020-10-17 16:32 UTC, voitylov commented
It would be interesting to understand the impact on code cache size as well and see a definition of OCI system so that the other members of the community could check some other HW.

2020-10-19 06:43 UTC, shipilev requested changes
Changing the global inlining defaults without providing the justifying performance data is not acceptable. @cl4es, please rescind your review if you can, so that change is not integrated by accident.

2020-10-19 11:55 UTC, cl4es commented
What constitutes a full promotion is proprietary, but I can verify no regressions across at least:

- SPECjvm2008*
- SPECjbb2005
- SPECjbb2015**
- Dacapo
- Renaissance

Notable improvements on Renaissance-DecTree (6%), Renaissance-Reactors (5%), Dacapo-lusearch (2%)
Various micros in the OpenJDK corpus improve significantly, e.g., AES_ECB_NoPadding 10% ChaCha20Poly1305 7%. No detected regressions.

I agree that some more info about code cache utilization across a more complete range of workloads is a reasonable request, but we've detected no regressions in our sample of footprint tests. I'm sure @ericcaspole won't integrate this without first coming back with more data on this.

* not running the broken compiler sub-benchmarks
** interestingly most SPECjbb2015 publications in recent years have included -XX:InlineSmallCode=10k or more, see https://www.spec.org/jbb2015/results/

2020-10-20 06:56 UTC, shipilev approved these changes
That is OK, looks good then.

2020-10-21 19:31 UTC, ericcaspole commented
The motivation for this change is, among other things, that we discovered a big regression in this micro in 11 vs 8:

https://github.com/openjdk/jdk/blob/master/test/micro/org/openjdk/bench/java/lang/NewInstance.java

jdk1.8.0_271:

Benchmark                                 Mode  Cnt   Score   Error  Units
NewInstance.threeDifferentProtected       avgt    5  61.413 ± 0.078  ns/op
NewInstance.threeDifferentPublic          avgt    5  56.705 ± 0.096  ns/op
NewInstance.threeDifferentPublicConstant  avgt    5  43.316 ± 0.094  ns/op
NewInstance.threeDifferentPublicFinal     avgt    5  56.586 ± 0.140  ns/op
NewInstance.threeSameProtected            avgt    5  46.714 ± 0.045  ns/op
NewInstance.threeSamePublic               avgt    5  44.565 ± 0.058  ns/op

jdk-11.0.9:

Benchmark                                 Mode  Cnt    Score    Error  Units
NewInstance.threeDifferentProtected       avgt    5  851.560 ± 44.299  ns/op
NewInstance.threeDifferentPublic          avgt    5  854.080 ±  7.619  ns/op
NewInstance.threeDifferentPublicConstant  avgt    5  911.749 ± 33.695  ns/op
NewInstance.threeDifferentPublicFinal     avgt    5  830.804 ± 21.219  ns/op
NewInstance.threeSameProtected            avgt    5  785.063 ±  2.580  ns/op
NewInstance.threeSamePublic               avgt    5  792.167 ±  0.538  ns/op

jdk-11.0.9 w/ -XX:InlineSmallCode=2500:

Benchmark                                 Mode  Cnt   Score   Error  Units
NewInstance.threeDifferentProtected       avgt    5  58.091 ± 0.012  ns/op
NewInstance.threeDifferentPublic          avgt    5  55.514 ± 0.062  ns/op
NewInstance.threeDifferentPublicConstant  avgt    5  43.233 ± 0.079  ns/op
NewInstance.threeDifferentPublicFinal     avgt    5  54.955 ± 0.103  ns/op
NewInstance.threeSameProtected            avgt    5  44.216 ± 0.013  ns/op
NewInstance.threeSamePublic               avgt    5  44.214 ± 0.009  ns/op

This carries on into 14, then other fixes in 15 make it go bi-modal where it may or may not get inlined run to run.

Also, increasing InlineSmallCode for x64 to 2500 makes it now equal to ARM64, which we think is sensible.

Here are some results on a recent internal testing build of jdk-16 default vs -XX:InlineSmallCode=2500.
All these results were statistically insignificant.

Name  Pct-Diff
==============
"SPECjvm2008-Compress-G1", 0.889,
"SPECjvm2008-Crypto.aes-G1", 2.884,
"SPECjvm2008-Crypto.rsa-G1", 0.230,
"SPECjvm2008-Crypto.signverify-G1", 0.824,
"SPECjvm2008-Derby-ParGC", 0.878,
"SPECjvm2008-FFT.large-G1", 1.626,
"SPECjvm2008-FFT.small-G1", 2.023,
"SPECjvm2008-LU.large-ParGC", -14.624,
"SPECjvm2008-LU.small-ParGC", -0.633,
"SPECjvm2008-MPEG-ParGC", 0.326,
"SPECjvm2008-MonteCarlo-G1", 3.054,
"SPECjvm2008-MonteCarlo-ZGC", -2.247,
"SPECjvm2008-SOR.large-ParGC", 10.729,
"SPECjvm2008-SOR.small-ParGC", 0.127,
"SPECjvm2008-Serial-ParGC", 0.909,
"SPECjvm2008-Sparse.large-G1", 0.204,
"SPECjvm2008-Sparse.small-G1", 0.594,
"SPECjvm2008-XML.transform-G1", 0.349,
"SPECjvm2008-XML.validation-G1", 0.378,

These tests are run on the generally available OCI BM2.52 platform. See https://docs.cloud.oracle.com/en-us/iaas/Content/Compute/References/computeshapes.htm

2020-10-21 19:41 UTC, AzeemJiva commented
Should this be backported to 11 then?

2020-10-21 19:42 UTC, AzeemJiva approved these changes

2020-10-21 20:32 UTC, ericcaspole commented
/integrate

2020-10-21 20:35 UTC, closed without merging

2020-10-21 20:49 UTC, vnkozlov reviewed
Good.

2020-10-22 08:02 UTC, plokhotnyuk commented
I'm got ~10% regression after adding `-XX:InlineSmallCode=2500` in some JSON parsing benchmarks where huge methods were generated for some data structures with big number of fields.

Steps to reproduce:
1. Clone the jsoniter-scala repo:
```
git clone --depth 1 git@github.com:plokhotnyuk/jsoniter-scala.git
```
2. Run benchmarks with default options:
```
sbt -java-home /usr/lib/jvm/openjdk-16 'jsoniter-scala-benchmarkJVM/jmh:run -wi 10 -i 10 TwitterAPIReading.jsoniterScala'
```
3. Run benchmarks with an additional `-XX:InlineSmallCode=2500` option:
```
sbt -java-home /usr/lib/jvm/openjdk-16 'jsoniter-scala-benchmarkJVM/jmh:run -wi 10 -i 10 -jvmArgsAppend "-XX:InlineSmallCode=2500" TwitterAPIReading.jsoniterScala'
```