JDK-8253936 Replace <code>...</code> with {@code ...} for java.sql
openjdk/jdk pull request #707
Opened 2020-10-16 19:38 UTC by Vipin-Sharma

<code>...</code> is replaced with {@code ...} in java.sql classes.
Please review and sponsor this change.

2020-10-17 07:26 UTC, Vipin-Sharma commented
Hi @LanceAndersen,

I have generated javadoc before and after change. Following are 3 differences showing side by side comparison here.

DriverManager.java - line 417 (Change: CODE replaced with code)
<CODE>d.getClass().getName()</CODE></div>		      |	 <code>d.getClass().getName()</code></div>

ResultSet.java - line 3085 (Change: CODE replaced with code)
the result set concurrency is <CODE>CONCUR_READ_ONLY</code>  |	 the result set concurrency is <code>CONCUR_READ_ONLY</code>

SQLClientInfoException.java - line 60 (Change: removed space before null)
 <code> null</code> and the vendor code is initialized to 0.  |	 <code>null</code> and the vendor code is initialized to 0.
 
All the above three changes doesn't change the effective view.

2020-10-20 23:47 UTC, LanceAndersen requested changes
Hi Vipin

Thank you for tackling this update.  There are a few required changes below.  I will also be going through the generated javadoc to see if anything jumps out as well.

Best
Lance

2020-10-20 23:47 UTC, LanceAndersen commented on src/java.sql/share/classes/java/sql/RowId.java
> + * Copyright (c) 2005, 2006, 2020, Oracle and/or its affiliates. All rights reserved.
Please fix the copyright

2020-10-20 23:47 UTC, LanceAndersen commented on src/java.sql/share/classes/java/sql/SQLClientInfoException.java
> + * method threw an exception.  An application can use the {@code getFailedProperties }
Please remove the extra space after getFailedProperties

2020-10-20 23:47 UTC, LanceAndersen commented on src/java.sql/share/classes/java/sql/SQLDataException.java
> + * Copyright (c) 2005, 2010, 2020, Oracle and/or its affiliates. All rights reserved.
Please fix the copyright

2020-10-20 23:47 UTC, LanceAndersen commented on src/java.sql/share/classes/java/sql/SQLException.java
> + * Copyright (c) 1996, 2014, 2020, Oracle and/or its affiliates. All rights reserved.
please fix the copyright

2020-10-20 23:47 UTC, LanceAndersen commented on src/java.sql/share/classes/java/sql/SQLFeatureNotSupportedException.java
> + * Copyright (c) 2005, 2013, 2020, Oracle and/or its affiliates. All rights reserved.
please fix the copyright

2020-10-20 23:47 UTC, LanceAndersen commented on src/java.sql/share/classes/java/sql/SQLIntegrityConstraintViolationException.java
> + * Copyright (c) 2005, 2013, 2020, Oracle and/or its affiliates. All rights reserved.
please fix the copyright

2020-10-20 23:47 UTC, LanceAndersen commented on src/java.sql/share/classes/java/sql/SQLInvalidAuthorizationSpecException.java
> + * Copyright (c) 2005, 2013, 2020, Oracle and/or its affiliates. All rights reserved.
please fix the copyright

2020-10-20 23:47 UTC, LanceAndersen commented on src/java.sql/share/classes/java/sql/SQLNonTransientConnectionException.java
> + * Copyright (c) 2005, 2013, 2020, Oracle and/or its affiliates. All rights reserved.
please fix the copyright

2020-10-20 23:47 UTC, LanceAndersen commented on src/java.sql/share/classes/java/sql/SQLNonTransientConnectionException.java
> +     * Constructs a {@code SQLTransientException} object
This should be SQLNonTransientConnectionException

2020-10-20 23:47 UTC, LanceAndersen commented on src/java.sql/share/classes/java/sql/SQLNonTransientException.java
> + * Copyright (c) 2005, 2013, 2020, Oracle and/or its affiliates. All rights reserved.
please fix the copyright

2020-10-20 23:47 UTC, LanceAndersen commented on src/java.sql/share/classes/java/sql/SQLNonTransientException.java
> +     * Constructs a {@code SQLTransientException} object
Should be SQLNonTransiientException

2020-10-20 23:47 UTC, LanceAndersen commented on src/java.sql/share/classes/java/sql/SQLPermission.java
> + * Copyright (c) 1999, 2017, 2020, Oracle and/or its affiliates. All rights reserved.
please fix the copyright

2020-10-20 23:47 UTC, LanceAndersen commented on src/java.sql/share/classes/java/sql/SQLRecoverableException.java
> + * Copyright (c) 2006, 2013, 2020, Oracle and/or its affiliates. All rights reserved.
please fix the copyright

2020-10-20 23:47 UTC, LanceAndersen commented on src/java.sql/share/classes/java/sql/SQLSyntaxErrorException.java
> + * Copyright (c) 2005, 2013, 2020, Oracle and/or its affiliates. All rights reserved.
please fix the copyright

2020-10-20 23:47 UTC, LanceAndersen commented on src/java.sql/share/classes/java/sql/SQLTimeoutException.java
> + * Copyright (c) 1996, 2013, 2020, Oracle and/or its affiliates. All rights reserved.
please fix the copyright

2020-10-20 23:47 UTC, LanceAndersen commented on src/java.sql/share/classes/java/sql/SQLTransactionRollbackException.java
> + * Copyright (c) 2005, 2013, 2020, Oracle and/or its affiliates. All rights reserved.
please fix the copyright

2020-10-20 23:47 UTC, LanceAndersen commented on src/java.sql/share/classes/java/sql/SQLTransientConnectionException.java
> + * Copyright (c) 2005, 2013, 2020, Oracle and/or its affiliates. All rights reserved.
please fix the copyright

2020-10-20 23:47 UTC, LanceAndersen commented on src/java.sql/share/classes/java/sql/SQLTransientException.java
> + * Copyright (c) 2005, 2013, 2020, Oracle and/or its affiliates. All rights reserved.
please fix the copyright

2020-10-20 23:47 UTC, LanceAndersen commented on src/java.sql/share/classes/java/sql/SQLWarning.java
> + * Copyright (c) 1996, 2013, 2020, Oracle and/or its affiliates. All rights reserved.
please fix the copyright

2020-10-20 23:47 UTC, LanceAndersen commented on src/java.sql/share/classes/java/sql/Types.java
> + * Copyright (c) 1996, 2014, 2020, Oracle and/or its affiliates. All rights reserved.
please fix the copyright

2020-10-20 23:47 UTC, LanceAndersen commented on src/java.sql/share/classes/java/sql/Wrapper.java
> + * Copyright (c) 2005, 2013, 2020, Oracle and/or its affiliates. All rights reserved.
please fix the copyright

2020-10-20 23:47 UTC, LanceAndersen commented on src/java.sql/share/classes/javax/sql/ConnectionEvent.java
> + * Copyright (c) 2000, 2006, 2020, Oracle and/or its affiliates. All rights reserved.
please fix the copyright

2020-10-20 23:47 UTC, LanceAndersen commented on src/java.sql/share/classes/javax/sql/ConnectionEventListener.java
> + * Copyright (c) 2000, 2001, 2020, Oracle and/or its affiliates. All rights reserved.
please fix the copyright

2020-10-20 23:47 UTC, LanceAndersen commented on src/java.sql/share/classes/javax/sql/RowSetEvent.java
> + * Copyright (c) 2000, 2006, 2020, Oracle and/or its affiliates. All rights reserved.
please fix the copyright

2020-10-20 23:47 UTC, LanceAndersen commented on src/java.sql/share/classes/javax/sql/RowSetListener.java
> + * Copyright (c) 2000, 2001, 2020, Oracle and/or its affiliates. All rights reserved.
please fix the copyright

2020-10-20 23:47 UTC, LanceAndersen commented on src/java.sql/share/classes/javax/sql/StatementEventListener.java
> + * Copyright (c) 2005, 2014, 2020, Oracle and/or its affiliates. All rights reserved.
please fix the copyright

2020-11-04 19:29 UTC, LanceAndersen approved these changes

2020-11-04 23:20 UTC, Vipin-Sharma commented
/integrate

2020-11-25 14:31 UTC, Vipin-Sharma commented
I think all steps are completed for this PR, please help sponsoring this.

2020-11-25 16:00 UTC, LanceAndersen commented
/sponsor

2020-11-25 16:01 UTC, closed without merging