8280136: Serial: Remove unnecessary use of ExpandHeap_lock
openjdk/jdk pull request #7124
Opened 2022-01-18 12:03 UTC by albertnetymk

This PR consists of two commits:

1. remove `ExpandHeap_lock` in Serial GC code.
2. rename it to `ParallelExpandHeap_lock` to indicate it's Parallel-GC only.

Test: tier1-6

2022-02-09 19:06 UTC, walulyai approved these changes
lgtm!

2022-02-10 03:10 UTC, kimbarrett reviewed
I'm not keen on the suggested new name. I want to read ParallelExpandHeap_lock
as a lock for parallel expansion of the heap, which doesn't really have the
right flavor of subsystem ownership. I think (with this change) its uses are
limited to ParallelGC oldgen expansion, suggesting a name like
PSOldGenExpand_lock (or PSOldGen::Expand_lock, which could be private were it
not for the assert in MutableSpace and the "usual" practice of defining locks
in mutexLocker.[ch]pp).

Other than that naming issue, nice cleanup.

2022-02-10 13:28 UTC, albertnetymk commented
I have moved the mutex inside `PSOldGen` to reduce its scope.

2022-02-10 17:10 UTC, coleenp commented on src/hotspot/share/gc/parallel/psOldGen.cpp
> +#endif
As per our coding convention, this should be _expand_lock.

2022-02-11 10:38 UTC, kstefanj approved these changes
Looks good, even if I preferred the old use of `needs_expand()`.

2022-02-11 10:38 UTC, kstefanj commented on src/hotspot/share/gc/parallel/psOldGen.cpp
> +    if (needs_expand) {
To me the old code reads better, but I guess it's a matter of taste. The predicate could be moved to PSOldGen to allow asserting that the lock is held.

2022-02-15 08:01 UTC, kimbarrett requested changes

2022-02-15 10:05 UTC, albertnetymk commented
I have moved the lock back to `mutexLocker` and used the name `PSOldGenExpand_lock`.

2022-02-15 10:34 UTC, kimbarrett approved these changes
Looks good.

2022-02-15 10:58 UTC, kstefanj approved these changes

2022-02-15 12:22 UTC, albertnetymk commented
Thanks for the review.

/integrate

2022-02-15 12:24 UTC, closed without merging