8198400: Test javax/swing/SwingUtilities/6797139/bug6797139.java fails in mach5
openjdk/jdk pull request #719
Opened 2020-10-17 13:26 UTC by prsadhuk

Please review a test fix for an issue seen failing in mach5 testing although it is not reproducible locally.
The issue seems to stem from the fact that the test was been run as headless test although it requires to create UI class like ComponentUI which is needed for painting, layout calculations etc and therefore it fails citing
===========
no ComponentUI class for: javax.swing.JButton[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=0,maximumSize=,minimumSize=,preferredSize=,defaultIcon=,disabledIcon=,disabledSelectedIcon=,margin=null,paintBorder=true,paintFocus=true,pressedIcon=,rolloverEnabled=false,rolloverIcon=,rolloverSelectedIcon=,selectedIcon=,text=Probably,defaultCapable=true] 
=================
Modified the test to mark it as headful.
Mach5 job was run for several iteration on all 3 platforms. Link in JBS

2020-10-18 03:36 UTC, mrserb commented
It does not look like the test uses any API which required the headful system, none of them throw a headless exception.

2020-10-18 04:31 UTC, prrace commented
if you run it locally with -Djava.awt.headless=true what happens ?
And in the bug report I see
Caused by: java.lang.NullPointerException 
at java.desktop/javax.swing.plaf.basic.LazyActionMap.installLazyActionMap(LazyActionMap.java:64) 

So installUI failed which is why there's no componentUI but why did we get this NPE that started it ?

2020-10-18 15:55 UTC, prsadhuk commented
Running -Djava.awt.headless=true passes locally.
I tried running on mach5 in headless configuration also and it passes even on running several iterations. Link in JBS.
It seems last time it gets NPE when executing UIManager.getLookAndFeelDefaults().put(defaultsKey, map); which indicate getLookAndFeelDefaults() returns null. But there are many instances in jdk swing code where no null check is done for this getLookAndFeelDefaults() call and it is working fine.

2020-10-19 01:53 UTC, mrserb commented
I think is that the root cause is in the stack trace "SameVMRunnable". It means that the test was run in the samevm mode and was affected by the other tests. I suggest finding such traces in the JBS and de-problem list all of them. Similar issue: https://github.com/openjdk/jdk/pull/715/files. The bug was fixed by the adding client tests to the "othervm.dirs" in the TEST.ROOT

2020-10-19 04:34 UTC, prsadhuk commented
I am not sure how to find such traces in JBS. THe mach5 log in  https://github.com/openjdk/jdk/pull/715/files doesn't seem to be accessible anymore. At least for this 2 PRs 719 and 715, we can deproblemlist this swing PL issues for now which is done in this 2 PRs.

2020-10-19 05:04 UTC, mrserb commented
> I am not sure how to find such traces in JBS. 

It is something like this:
https://bugs.openjdk.java.net/issues/?jql=text%20~%20%22SameVMRunnable%22%20and%20status%3DOpen%20and%20component%20%3D%20client-libs%20

I guess most of the bugs filed during that test sprint. I can take a look at them if you wish.

2020-10-19 05:10 UTC, prsadhuk commented
OK. Thanks for the query. So, how do you propose to go about this? 
I can take look at the swing issues. 
I have already de PLed 2 of these swing issues which I guess should not be an issue now.

2020-10-19 05:37 UTC, mrserb commented
> OK. Thanks for the query. So, how do you propose to go about this?
Create a new issue, something like "Re-enable tests which were broken due to samevm mode" and close all that bugs that currently passed as duplicates.
BTW I currently completed the same task in jdk8, and we will have only 6(six) headless tests in the problem list(after the samevm mode was changed to othervm).

2020-10-19 05:51 UTC, prsadhuk commented
"close all that bugs that currently passed as duplicates"
So, did you run all PL-ed bug several times to consider it as passed or just run client-tier3 job with these PL tests from this query deproblemlisted?

2020-10-19 06:38 UTC, shipilev requested changes
> Modified the test to mark it as headful.

I don't see that in the changeset. There are only removals of newline and `@author` tag.

2020-10-21 06:06 UTC, closed without merging