8280541: remove self-recursion of ConnectionGraph::find_inst_mem()
openjdk/jdk pull request #7204
Opened 2022-01-24 22:57 UTC by navyxliu

This is a follow-up task of JDK-8276219.

ConnectionGraph::find_inst_mem() contains a self-recursion for MergeMemNode.
It drills into one input of mergenode and tries to locate the memory node
which has the exact alias_idx. Once it returns, the result will be same from
recursion. Therefore, it's not necessary to use recursion in this case. We can
reset the initial state of this function and respin.

We can use a collection to remember all MergeMem Nodes and update them after then. 

This patch also makes a cleanup in MergeMemNode::memory_at(). C is not in use in
that function.

2022-01-31 19:27 UTC, navyxliu commented
May I ping this?  It's really a simple change.

2022-01-31 23:52 UTC, dean-long requested changes
I don't think it makes sense to remove only self-recursion here.  I think it makes the code less readable (see JDK-8276219).  It's not obvious to me that the code gives the same result.  Normally when converting recursive to iterative, I would expect to see both push and pop operations, but I only see push operations here.  Also, to test the new algorithm, I would suggest to run it in parallel with the old algorithm and compare the results.

2022-02-02 18:07 UTC, navyxliu commented
>  Normally when converting recursive to iterative, I would expect to see both push and pop operations, but I only see push operations here.

For the self-recursion case, the invariant of find_inst_mem is "the the result is either MemNode, PhiNode, InitializeNode" and "the mem of result is alias_idx ".  As a result, the result won't change.  we can leverage this property to backpatch all MergeMem nodes.  It's similar to tail recursion optimization. we reset the stackframe and arguments. 
 
> I don't think it makes sense to remove only self-recursion here.I think it makes the code less readable (see JDK-8276219). 
I agree.  I just feel this code change is easy. Please check the 2nd revision that I bring back the assertion code.  now we have iterative EA. It may give us more compilation-time pressure than before.

2022-02-08 01:16 UTC, dean-long commented
/reviewers 2

2022-02-08 01:27 UTC, dean-long commented
If the result won't change, then perhaps the self-recursion case should return instead of falling through.  Then it really is tail-recursion elimination.  However, knowing that falling through won't change the value makes several assumptions based on the current code, and those assumptions could break if the code changes.  To follow the original algorithm, the new version should fall through, which means having the loop pop elements off a stack.  Either way, this is not a trivial change to me.

I also noticed that moving the C->failing() check could also cause different behavior, but maybe it's harmless.

2022-02-09 18:18 UTC, navyxliu commented
@

2022-02-09 18:18 UTC, closed without merging