8281263: virtual space leakage if large page commit fails.
openjdk/jdk pull request #7350
Opened 2022-02-04 13:27 UTC by swati-sha

Hi Team,

In this patch I have fixed the virtual space leakage issue. While attempting commit over larger pages we first try to reserve requested bytes over the virtual address space, in case commit to large page fails we should be un reserving entire reservation to avoid leaving any leaks in virtual address space.

Please review and provide your valuable comments.

Thanks,
Swati Sharma
Runtime Software Development Engineer 
Intel

2022-02-04 13:29 UTC, swati-sha commented
/add label hotspot-runtime-dev

2022-02-04 13:30 UTC, swati-sha commented
/add label hotspot-gc-dev

2022-02-04 13:31 UTC, swati-sha commented
/contributor add @jatin-bhateja

2022-02-04 15:32 UTC, stefank requested changes
I'm not convinced that this is needed or even safe. My understanding is that you have already lost the reservation [aligned_start, aligned_start + large_bytes) when the large page commit failed. If that is the case, then it is unsafe to unmap it again, since another thread could race and reserve that memory, and then this thread would potentially unmap the other thread's memory.

Could you provide some data help me understand the problem you are seeing?

I'd like to see the values of aligned_start, large_bytes and bytes and a preferably a dump of /proc/<pid>/maps when  the coded enters the if statement:
```
if (!large_committed) {
    // Failed to commit large pages, so we need to unmap the
```

2022-02-04 15:53 UTC, tstuefe commented
> I'm not convinced that this is needed or even safe. My understanding is that you have already lost the reservation [aligned_start, aligned_start + large_bytes) when the large page commit failed. If that is the case, then it is unsafe to unmap it again, since another thread could race and reserve that memory, and then this thread would potentially unmap the other thread's memory.

I thought so too. See also https://bugs.openjdk.java.net/browse/JDK-8007074, which was caused by a failing commit leaving the address range in question unmapped and available for concurrent reservations.

> 
> Could you provide some data help me understand the problem you are seeing?
> 
> I'd like to see the values of aligned_start, large_bytes and bytes and a preferably a dump of `/proc/<pid>/maps` when the coded enters the if statement:
> 
> ```
> if (!large_committed) {
>     // Failed to commit large pages, so we need to unmap the
> ```

Note that an easy way to get this would be to just assert at that point, the hs-err file should contain a copy of the maps file.

2022-02-04 16:18 UTC, stefank commented
> > I'm not convinced that this is needed or even safe. My understanding is that you have already lost the reservation [aligned_start, aligned_start + large_bytes) when the large page commit failed. If that is the case, then it is unsafe to unmap it again, since another thread could race and reserve that memory, and then this thread would potentially unmap the other thread's memory.
> 
> I thought so too. See also https://bugs.openjdk.java.net/browse/JDK-8007074, which was caused by a failing commit leaving the address range in question unmapped and available for concurrent reservations.
> 
> > Could you provide some data help me understand the problem you are seeing?
> > I'd like to see the values of aligned_start, large_bytes and bytes and a preferably a dump of `/proc/<pid>/maps` when the coded enters the if statement:
> > ```
> > if (!large_committed) {
> >     // Failed to commit large pages, so we need to unmap the
> > ```
> 
> Note that an easy way to get this would be to just assert at that point, the hs-err file should contain a copy of the maps file.

Great suggestion. I think something like would give us enough information:
```
assert(false, "Large pages commit failed " PTR_FORMAT " " PTR_FORMAT " " PTR_FORMAT, p2i(aligned_start), p2i(aligned_start + large_bytes), p2i(aligned_start + bytes));
```

2022-02-07 12:51 UTC, jatin-bhateja commented
MAP_FIXED flag is clear on the semantics here, it will override the earlier mapping and which will unreserve the memory in case of commit failure.

Closing this PR which was spun out of discussion on [PR 7326](https://github.com/openjdk/jdk/pull/7326)

2022-02-07 12:54 UTC, closed without merging