8281296: Create a regression test for JDK-4515999
openjdk/jdk pull request #7363
Opened 2022-02-07 08:18 UTC by manukumarvs

Create a regression test for [JDK-4515999](https://bugs.openjdk.java.net/browse/JDK-4515999)
Create a test which checks whether incrementing dates via the keyboard (up/down) gives the same results as when using mouse press on the arrow buttons in a JSpinner.

2022-02-07 08:24 UTC, manukumarvs commented
@aivanov-jdk Can you please review this?

2022-02-07 13:37 UTC, aivanov-jdk requested changes
Does this new test reproduce the original problem reported in JDK-4515999?

2022-02-07 13:37 UTC, aivanov-jdk commented on test/jdk/javax/swing/JSpinner/4515999/JSpinnerMouseAndKeyPressTest.java
> +    private static JFrame frame;
I suggest adding a blank line between the constant and the frame to separate them.

2022-02-07 13:37 UTC, aivanov-jdk commented on test/jdk/javax/swing/JSpinner/4515999/JSpinnerMouseAndKeyPressTest.java
> +    //2 days in milliseconds
Please add a space after `//` according to [the guidelines](http://cr.openjdk.java.net/~alundblad/styleguide/index-v6.html#toc-whitespace). In other places too.

2022-02-07 13:37 UTC, aivanov-jdk commented on test/jdk/javax/swing/JSpinner/4515999/JSpinnerMouseAndKeyPressTest.java
> +                                  .collect(Collectors.toList());
This is probably a bit too much for just mapping `LookAndFeelInfo` to `lafClassName`… If you like it though, I don't mind.

2022-02-07 13:37 UTC, aivanov-jdk commented on test/jdk/javax/swing/JSpinner/4515999/JSpinnerMouseAndKeyPressTest.java
> +                final int spinnerQuarterHeight = spinner.getHeight() / 4;
The `spinner` component must be accessed from EDT only.

2022-02-07 13:37 UTC, aivanov-jdk commented on test/jdk/javax/swing/JSpinner/4515999/JSpinnerMouseAndKeyPressTest.java
> +                long upValue = ((Date) spinner.getValue()).getTime();
The `spinner` component must be accessed from EDT only.

2022-02-07 13:37 UTC, aivanov-jdk commented on test/jdk/javax/swing/JSpinner/4515999/JSpinnerMouseAndKeyPressTest.java
> +                robot.mouseRelease(InputEvent.BUTTON1_MASK);
`BUTTON1_MASK` is deprecated in favour of `BUTTON1_DOWN_MASK`

2022-02-07 13:47 UTC, aivanov-jdk commented on test/jdk/javax/swing/JSpinner/4515999/JSpinnerMouseAndKeyPressTest.java
> +                        spinnerQuarterHeight;
The [Java Style Guidelines](http://cr.openjdk.java.net/~alundblad/styleguide/index-v6.html#toc-wrapping-lines) suggests breaking before the operators.

2022-02-07 16:20 UTC, manukumarvs commented
> Does this new test reproduce the original problem reported in JDK-4515999?

Yes it's reproducible in JDK 1.4.

2022-02-08 12:09 UTC, aivanov-jdk approved these changes

2022-02-08 12:12 UTC, manukumarvs commented
/integrate

2022-02-08 12:37 UTC, aivanov-jdk commented
/sponsor

2022-02-08 12:40 UTC, closed without merging