8281505: Add CompileCommand PrintIdealPhase
openjdk/jdk pull request #7392
Opened 2022-02-08 22:34 UTC by neliasso

This patch adds the CompileCommand PrintIdealPhase. It allows to specify a list of compiler phases that will print the ideal IR.

The motivation for this is that during work with the IR framework I have found the need for printing specific phases, and the previously added PrintIdealLevel is forced to use levels that just prints to much.

Usage:
-XX:CompileCommand=PrintIdealPhase,*::indexOf,"AFTER_EA,FINAL_CODE"

I have chosen not to add this as a separate VM flag. Debug flags like this usually only applied to specific methods.

Please review,
Nils Eliasson

2022-02-11 04:19 UTC, vnkozlov approved these changes
Good.

2022-02-11 10:13 UTC, TobiHartmann approved these changes
Looks good to me.

2022-02-11 10:13 UTC, TobiHartmann commented on test/hotspot/jtreg/compiler/oracle/PrintIdealPhaseTest.java
> + * Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
```suggestion
 * Copyright (c) 2022, Oracle and/or its affiliates. All rights reserved.
```

2022-02-11 10:47 UTC, neliasso commented
@vnkozlov @TobiHartmann Thanks for having a look!

I updated the copyright year.

I also found that sometimes the test method can be compiled multiple times, so I changed the List to a HashSet. Also removed redundant command line parameters.

Best regards,
Nils

2022-02-11 10:59 UTC, TobiHartmann approved these changes
Looks good.

2022-02-11 16:15 UTC, chhagedorn approved these changes
Nice work! That will make things easier (and better in terms of performance) for [JDK-8280378](https://bugs.openjdk.java.net/browse/JDK-8280378). Looks good to me, too.

2022-02-11 18:17 UTC, vnkozlov approved these changes
Update is good.

2022-02-11 18:19 UTC, vnkozlov requested changes
Looks like `zero` and `minimal` builds failed with this change:
```
src/hotspot/share/compiler/compilerDirectives.cpp:388:20: error: 'PrintIdealPhaseIndex' was not declared in this scope
[19](https://github.com/neliasso/jdk/runs/5155280503?check_suite_focus=true#step:19:19)
  388 |     if (!_modified[PrintIdealPhaseIndex]) {
[20](https://github.com/neliasso/jdk/runs/5155280503?check_suite_focus=true#step:19:20)
      |                    ^~~~~~~~~~~~~~~~~~~~
 ```

2022-02-11 18:53 UTC, vnkozlov approved these changes
Good.

Wait result of GIT testing.

2022-02-14 06:55 UTC, chhagedorn approved these changes

2022-02-14 08:25 UTC, neliasso commented
Thanks for the reviews and feedback! @vnkozlov @TobiHartmann @chhagedorn

2022-02-14 08:26 UTC, neliasso commented
/integrate

2022-02-14 08:27 UTC, closed without merging