PPC64 part of JDK-8281146
openjdk/jdk pull request #7430
Opened 2022-02-10 17:40 UTC by TheRealMDoerr

It can get implemented similarly on PPC64.

2022-02-11 15:05 UTC, TheRealMDoerr commented
Hi Richard,
thanks for reviewing it!
The match rules are optional. (`Matcher::match_rule_supported(Op_HasNegatives)` checks if ALDC has created one.) Note that the same replacement was done for x86 and some other platforms don't have it at all (arm32).
Yes, I have used our nightly tests to test Claes' change together with my PPC64 implementation.
I guess it will be better to let Claes handle Copyright year updates when all changes are complete. Otherwise, merge conflicts may arise.

2022-02-11 15:19 UTC, reinrich commented
> Hi Richard, thanks for reviewing it! The match rules are optional. (`Matcher::match_rule_supported(Op_HasNegatives)` checks if ALDC has created one.)

Thanks for the indication. I expected that but couldn't find it.

> Note that the same replacement was done for x86 and some other platforms don't have it at all (arm32). Yes, I have used our nightly tests to test Claes' change together with my PPC64 implementation.

Good.

> I guess it will be better to let Claes handle Copyright year updates when all changes are complete. Otherwise, merge conflicts may arise.

Ok.

Cheers, Richard.

2022-02-14 13:04 UTC, cl4es commented
Thanks so much for doing this, Martin!

I aim to wait for aarch64 and s390 variants to be implemented as well and remove all the code for supporting the `_hasNegatives` intrinsic in the hotspot code.

2022-02-14 23:07 UTC, backwaterred commented
I am taking a look at this PR to better understand how intrinsics function in Hotspot, and I noticed that the old intrinsic name is mentioned [here](https://github.com/openjdk/jdk/pull/7430/files#diff-d21a64a4949f298476bf91083d3b956face9a6393a08a706b071068898533082R12788).

Nice changes! They are clean and easy to understand.

2022-02-16 10:58 UTC, RealLucy requested changes

2022-02-16 10:58 UTC, RealLucy commented on src/hotspot/cpu/ppc/ppc.ad
>    ins_encode %{
How about adapting the cleartext name in the format? I would suggest to use the same name as on x86 (countPositives).

2022-02-21 10:43 UTC, cl4es commented
Pre-existing, but I note that the ppc (and s390) impl don't have an explicit effect on the `len` register. x86 and aarch64 does a `USE_KILL len`. Not exactly sure what this means exactly, or whether it's intentional or not. What do you think?

2022-02-21 10:52 UTC, RealLucy commented
USE_KILL reg means the reg contents on entry to the code is relevant (in contrast to TEMP), and the reg contents is altered on exit from the code. 

ppc and s390 don't alter the len reg. There is no reason to prevent the compiler from re-using the reg contents afterwards.

2022-03-04 09:01 UTC, RealLucy approved these changes
Changes look good to me.

2022-03-07 10:18 UTC, TheRealMDoerr commented
Integrated by https://github.com/openjdk/jdk/pull/7231/commits/b826ef8102cddf0afc22d9d56111d5fba9d1e091

2022-03-07 10:18 UTC, closed without merging