8281569: Create tests for Frame.setMinimumSize() method
openjdk/jdk pull request #7444
Opened 2022-02-11 17:28 UTC by srmandal

Create tests for setMinimumSize functionality
Create a test which verifies that on increasing the Frame's minimumSize, it gets reflected in the subsequent getSize call
Create a test which verifies that on frame resizes back to minimumSize on calling pack.

2022-02-14 15:54 UTC, srmandal commented
Can someone review this PR?

2022-02-18 22:23 UTC, aivanov-jdk commented on test/jdk/java/awt/Frame/SetMinimumSizeTest/SetMinimumSizeTest1.java
> +        frame.setSize(140,140);
```suggestion
        frame.setSize(140, 140);
```

2022-02-18 22:23 UTC, aivanov-jdk commented on test/jdk/java/awt/Frame/SetMinimumSizeTest/SetMinimumSizeTest1.java
> +        SetMinimumSizeTest1.doTest();
```suggestion
        doTest();
```

2022-02-18 22:23 UTC, aivanov-jdk commented on test/jdk/java/awt/Frame/SetMinimumSizeTest/SetMinimumSizeTest2.java
> +    }
```suggestion
    public static void main(String[] args) throws Exception {
        doTest();
    }
```

2022-02-18 22:23 UTC, aivanov-jdk commented on test/jdk/java/awt/Frame/SetMinimumSizeTest/SetMinimumSizeTest1.java
> +    private static Dimension dimension;
The `dimension` field should be volatile as it's accessed from different threads.

2022-02-21 20:46 UTC, aivanov-jdk requested changes

2022-02-21 20:46 UTC, aivanov-jdk commented on test/jdk/java/awt/Frame/SetMinimumSizeTest/SetMinimumSizeTest1.java
> +            Dimension actualDimension = frame.getSize();
Let's be consistent: this should also be called on EDT.

2022-02-21 20:46 UTC, aivanov-jdk commented on test/jdk/java/awt/Frame/SetMinimumSizeTest/SetMinimumSizeTest1.java
> +            robot.setAutoDelay(100);
And add
```
robot.waitForIdle();
```

2022-02-21 20:46 UTC, aivanov-jdk commented on test/jdk/java/awt/Frame/SetMinimumSizeTest/SetMinimumSizeTest2.java
> +            robot.setAutoDelay(100);
Also add
```
robot.waitForIdle();
```

2022-02-21 20:46 UTC, aivanov-jdk commented on test/jdk/java/awt/Frame/SetMinimumSizeTest/SetMinimumSizeTest2.java
> +            Dimension actualDimension = frame.getSize();
Let's be consistent and access `frame` on EDT only.

2022-03-01 16:11 UTC, aivanov-jdk requested changes

2022-03-01 16:11 UTC, aivanov-jdk commented on test/jdk/java/awt/Frame/SetMinimumSizeTest/SetMinimumSizeTest1.java
> +    private static volatile Dimension dimension, actualDimension;
In Java, each field should be declared on its own line.

2022-03-01 16:11 UTC, aivanov-jdk commented on test/jdk/java/awt/Frame/SetMinimumSizeTest/SetMinimumSizeTest1.java
> +    public static void createGUI(Frame _frame) {
The `_frame` parameter is never used, please remove it.

2022-03-01 16:11 UTC, aivanov-jdk commented on test/jdk/java/awt/Frame/SetMinimumSizeTest/SetMinimumSizeTest1.java
> +                dimension.height = dimension.height + 20;
```suggestion
                dimension.width += 20;
                dimension.height += 20;
```

2022-03-01 16:11 UTC, aivanov-jdk commented on test/jdk/java/awt/Frame/SetMinimumSizeTest/SetMinimumSizeTest1.java
> +        finally {
```suggestion
        } finally {
```

The finally-block as well as catch- and else-blocks should be at the same line as the closing brace from the previous block.

2022-03-02 09:52 UTC, aivanov-jdk approved these changes

2022-03-02 13:08 UTC, srmandal commented
/integrate

2022-03-02 13:08 UTC, srmandal commented
@aivanov-jdk Can you please sponsor my changes?.

2022-03-03 03:24 UTC, akolarkunnu commented
/sponsor

2022-03-03 03:26 UTC, closed without merging