8282172: CompileBroker::log_metaspace_failure is called from non-compiler threads
openjdk/jdk pull request #7555
Opened 2022-02-21 11:22 UTC by shipilev

In several places in hotspot, we call CompileBroker::log_metaspace_failure(). I believe the intent is to call it from compiler threads only, because it ends up calling:

  void log_metaspace_failure(const char* reason) {
    ResourceMark rm;
    StringLogMessage lm;
    lm.print("%4d COMPILE PROFILING SKIPPED: %s", -1, reason);
    lm.print("\n");
    log(JavaThread::current(), "%s", (const char*)lm);
  }

...which would fail the cast in `JavaThread::current()` if current thread is not Java thread (compiler threads are Java threads too).

It clearly manifests on [JDK-8282170](https://bugs.openjdk.java.net/browse/JDK-8282170) test:

```
12700 breakpoints set
12800 breakpoints set
12900 breakpoints set
13000 breakpoints set
# To suppress the following error report, specify this argument
# after -XX: or in .hotspotrc: SuppressErrorAt=/thread.hpp:1458
#
# A fatal error has been detected by the Java Runtime Environment:
#
# Internal Error (/home/shade/trunks/jdk/src/hotspot/share/runtime/thread.hpp:1458), pid=889379, tid=889389
# assert(t->is_Java_thread()) failed: incorrect cast to JavaThread
V [libjvm.so+0xacfad4] CompilationLog::log_metaspace_failure(char const*)+0x494
V [libjvm.so+0xac84b0] CompileBroker::log_metaspace_failure()+0x20
V [libjvm.so+0x15069e9] Method::build_method_counters(Thread*, Method*)+0x119
V [libjvm.so+0x150851b] BreakpointInfo::set(Method*)+0xfb
V [libjvm.so+0x127d5ea] JvmtiBreakpoint::each_method_version_do(void (Method::*)(int))+0x5a
V [libjvm.so+0x1b342ae] VM_Operation::evaluate()+0x18e 
```

Additional testing:
 - [x] Linux x86_64 fastdebug does not fail JDK-8282170 test anymore

2022-02-22 16:59 UTC, vnkozlov requested changes
No, it could be called from Java execution thread too when profiling is triggered. But yes it was assumed that only Java thread can ask for creation `MethodData`.
On other hand `log()` methods accepts `Thread*` parameter and just record it:
https://github.com/openjdk/jdk/blob/master/src/hotspot/share/utilities/events.hpp#L183
May be we don't need to cast it to `JavaThread` in this case.

2022-02-23 07:36 UTC, shipilev commented
> No, it could be called from Java execution thread too when profiling is triggered. But yes it was assumed that only Java thread can ask for creation `MethodData`. On other hand `log()` methods accepts `Thread*` parameter and just record it: https://github.com/openjdk/jdk/blob/master/src/hotspot/share/utilities/events.hpp#L183 May be we don't need to cast it to `JavaThread` in this case.

Yes, this would also work:

```
diff --git a/src/hotspot/share/compiler/compileBroker.cpp b/src/hotspot/share/compiler/compileBroker.cpp
index 1c8656044b5..62c45e6adca 100644
--- a/src/hotspot/share/compiler/compileBroker.cpp
+++ b/src/hotspot/share/compiler/compileBroker.cpp
@@ -227,11 +227,11 @@ class CompilationLog : public StringEventLog {
   void log_metaspace_failure(const char* reason) {
     ResourceMark rm;
     StringLogMessage lm;
     lm.print("%4d   COMPILE PROFILING SKIPPED: %s", -1, reason);
     lm.print("\n");
-    log(JavaThread::current(), "%s", (const char*)lm);
+    log(Thread::current(), "%s", (const char*)lm);
   }
 };
 
 static CompilationLog* _compilation_log = NULL;
```

...but it is odd to: a) have the rest of `CompilationLog` accept `JavaThread` only; b) having `COMPILE SKIPPED` printed when we are not dealing with any compiler/Java thread.

```
void CompileBroker::log_metaspace_failure() {
  const char* message = "some methods may not be compiled because metaspace "
                        "is out of memory";
  if (_compilation_log != NULL) {
    _compilation_log->log_metaspace_failure(message);
  }
  if (PrintCompilation) {
    tty->print_cr("COMPILE PROFILING SKIPPED: %s", message); // <--- from here
  }
}
```

So I still believe filtering non-Java/compiler threads at `CompileBroker::log_metaspace_failure()` is the proper fix.

2022-02-23 16:55 UTC, vnkozlov commented on src/hotspot/share/compiler/compileBroker.cpp
>    if (_compilation_log != NULL) {
Okay. But  can you add the thread check here so that at least we get message with `PrintCompilation`?

2022-02-23 17:10 UTC, vnkozlov approved these changes
Good.

2022-02-25 07:56 UTC, TobiHartmann approved these changes
Looks good to me too.

2022-02-25 09:26 UTC, tstuefe commented
AFAICS FormatStringEventLog::log() - which is only used from the compiler btw - is always called with the current thread. Maybe it should just use Thread::current instead?

2022-02-28 13:12 UTC, shipilev commented
> AFAICS FormatStringEventLog::log() - which is only used from the compiler btw - is always called with the current thread. Maybe it should just use Thread::current instead?

Maybe. Let's do that separately?

2022-02-28 13:23 UTC, tstuefe commented
> > AFAICS FormatStringEventLog::log() - which is only used from the compiler btw - is always called with the current thread. Maybe it should just use Thread::current instead?
> 
> Maybe. Let's do that separately?

Oh, sure.

2022-02-28 13:28 UTC, shipilev commented
Good. Thanks for reviews!

/integrate

2022-02-28 13:29 UTC, closed without merging