8282208: Reduce MachNode size
openjdk/jdk pull request #7562
Opened 2022-02-21 16:19 UTC by neliasso

Hi,

This patch reduces the size of MachNodes from 72  to 64 bytes.

The motivation for this patch is that I needed more bits for the _barrier_data field. (This will happen in another patch.) I noticed that the bool _remove field caused a lot of padding. It's only used by peephole and can as well be modeled as a Node::flag.

Fixes in this patch:
1) Change MachNode::_remove to a Node::flag

2) Changing MachNode::operands to a 16 bit unsigned (Allowing room for 16 bits _barrier_data) 

3) Moving Node::_debug_idx below Node::_debug_orig saving 8-12 bytes in debug builds. Nodes in debug builds are about twice as large as in product builds making this change have a relatively small impact. 

Please review,
Nils Eliasson

2022-02-22 17:37 UTC, vnkozlov approved these changes
Good.

2022-02-22 19:05 UTC, neliasso commented
Thank you @vnkozlov !

I can add that I have listed the node layouts in the bug report for reference.

2022-02-23 01:22 UTC, DamonFool commented
There are several failures in the github tests.
Did you test the failing cases with your patch?

Also, we'd better update the copyright year.
Thanks.

2022-02-23 08:07 UTC, TobiHartmann requested changes
The value of `Node::_last_flag` needs to be updated.

2022-02-23 08:07 UTC, TobiHartmann commented on src/hotspot/share/opto/node.hpp
>      _last_flag                       = Flag_for_post_loop_opts_igvn
```suggestion
    Flag_is_removed_by_peephole      = 1 << 17,
    _last_flag                       = Flag_is_removed_by_peephole
```

2022-02-23 08:49 UTC, neliasso commented on src/hotspot/share/opto/node.hpp
>      _last_flag                       = Flag_for_post_loop_opts_igvn
Good catch! Thanks!

2022-02-23 08:54 UTC, neliasso commented
> There are several failures in the github tests. Did you test the failing cases with your patch?
> 
> Also, we'd better update the copyright year. Thanks.

I looked at the test failures, and they look unrelated. I've also run separate testing that didn't show these failures.

The github tests will run again now.

Updated copyright year.

2022-02-23 09:01 UTC, TobiHartmann approved these changes
Looks good to me.

2022-02-23 11:20 UTC, DamonFool approved these changes
LGTM

2022-02-23 12:46 UTC, neliasso commented
/integrate

2022-02-23 12:48 UTC, closed without merging