6742362: JComponent.setFont() font comparison is not correct
openjdk/jdk pull request #7571
Opened 2022-02-22 08:59 UTC by prsadhuk

Font comparison in JComponent.setFont() uses `font != oldFont` check which is not correct as per Object equality essence. The correct way of checking font equality is to use "equals" as is done in [GlyphLayout](https://github.com/openjdk/jdk/blob/master/src/java.desktop/share/classes/sun/font/GlyphLayout.java#L144) , [StandardGlyphVector](https://github.com/openjdk/jdk/blob/master/src/java.desktop/share/classes/sun/font/StandardGlyphVector.java#L657) etc

Existing jtreg, jck test are green.

2022-02-22 14:21 UTC, dmarkov20 requested changes
I have concern regarding the case once null-value is passed to `setFont() `method. In particular when `font` is null but `oldFont` is not null. Now `revalidate()` and `repaint()` are not called but they used to be called before.
Shouldn't we have here something similar to https://github.com/openjdk/jdk/blob/b48e71f16a01992500851e3eb56c90b0ba0668e4/src/java.desktop/share/classes/java/awt/Container.java#L1782

2022-02-22 16:13 UTC, prsadhuk commented
I am not sure if what used to be done before was correct..I guess we should ignore null font and don't do expensive repaint. Even [Graphics.setFont](https://docs.oracle.com/en/java/javase/17/docs/api/java.desktop/java/awt/Graphics.html#setFont(java.awt.Font)) spec says " A null argument is silently ignored"

2022-02-22 17:23 UTC, prrace commented
What Graphics.setFont() says is irrelevant to this.
Looking at Component.java and Container.java which you need to since super.setFont(f) is called by both JComponent.setFont() and Container.setFont() "==" and "!=" are used there so this would be inconsistent.
You'd need to take a holistic look at all of these together and make risky changes
So I'm not sure we should change this. It might just cause unexpected regressions.
And see for example : https://github.com/openjdk/jdk/pull/7313 so we know Font.equals() isn't perfect.

2022-02-23 04:07 UTC, prsadhuk commented
Thanks for the feedback @prrace on this. I see in some places `==` is used and some places `.equals` and since a JBS issue existed on this so wanted to initiate a discusssion by raising PR..Since there is no proof of `.equals `benefit, I will close this JBS as Won't Fix

2022-02-23 21:55 UTC, aivanov-jdk commented
I agree it's safer to leave it unchanged. If a new font instance is set, it's likely different, it's safer to repaint the component. If you want to avoid expensive repaint, don't change the component font. In the majority of cases, font is set when the component is configured before it's made visible.

2022-02-25 04:13 UTC, closed without merging