8281181: Do not use CPU Shares to compute active processor count
openjdk/jdk pull request #7666
Opened 2022-03-02 20:01 UTC by iklam

This is a simple change (Linux-only) that removes the consideration of Cgroups CPU Shares from the active process count calculation. Of note, this fixes CPU underutilization when Java is executed by Kubernetes without CPU resources limits. 

Please see the CSR [JDK-8281571](https://bugs.openjdk.java.net/browse/JDK-8281571) for a detailed discussion of the reasons to make this change.

To err on the side of caution, we added a temporary (and deprecated) VM flag `-XX:+UseContainerCpuShares` to enable the old behavior. We believe the old behavior is wrong and unnecessary. The plan is to remove the old behavior in JDK 20.

The associated flag, `PreferContainerQuotaForCPUCount` is also deprecated. Both flags will be obsoleted in JDK 20.

Testing with tiers 1-4, as well as container tests in tier5.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed
- [x] Change requires a CSR request to be approved

### Issues
 * [JDK-8281181](https://bugs.openjdk.java.net/browse/JDK-8281181): Do not use CPU Shares to compute active processor count
 * [JDK-8281571](https://bugs.openjdk.java.net/browse/JDK-8281571): Do not use CPU Shares to compute active processor count (**CSR**)

### Reviewers
 * [David Holmes](https://openjdk.java.net/census#dholmes) (@dholmes-ora - **Reviewer**)
 * [Severin Gehwolf](https://openjdk.java.net/census#sgehwolf) (@jerboaa - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/7666/head:pull/7666` \
`$ git checkout pull/7666`

Update a local copy of the PR: \
`$ git checkout pull/7666` \
`$ git pull https://git.openjdk.java.net/jdk pull/7666/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7666`

View PR using the GUI difftool: \
`$ git pr show -t 7666`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/7666.diff">https://git.openjdk.java.net/jdk/pull/7666.diff</a>

</details>

2022-03-02 20:14 UTC, iklam commented
/label remove hotspot-runtime
/label add hotspot

2022-03-03 02:33 UTC, dholmes-ora requested changes
Hi Ioi,

Generally looks good. A couple of nits below.

The deprecated flags should be added to the VMDeprecatedOptions test.

Thanks,
David

2022-03-03 02:33 UTC, dholmes-ora commented on src/hotspot/os/linux/cgroupSubsystem_linux.cpp
> +  // of CPUs used by the JVM. See JDK-8281571.
I suggest using JDK-8281181 rather than the CSR issue.

2022-03-03 02:33 UTC, dholmes-ora commented on test/hotspot/jtreg/containers/docker/TestCPUAwareness.java
> +        // will be removed in the next JDK release. See JDK-8281571.
I suggest using JDK-8281181 rather than the CSR issue.

2022-03-03 07:05 UTC, iklam commented
> Hi Ioi,
> 
> Generally looks good. A couple of nits below.
> 
> The deprecated flags should be added to the VMDeprecatedOptions test.
> 
> Thanks, David

Hi David, thanks for the review. I've updated the patch as you suggested.

2022-03-03 09:27 UTC, jerboaa approved these changes
LGTM

2022-03-03 12:50 UTC, dholmes-ora approved these changes
Updates look good.

Please file an issue to obsolete these flags in JDK 20 (they will be expired en-masse in JDK 21).

Thanks,
David

2022-03-04 20:10 UTC, iklam commented
> Updates look good.
> 
> Please file an issue to obsolete these flags in JDK 20 (they will be expired en-masse in JDK 21).
> 
> Thanks, David

I filed https://bugs.openjdk.java.net/browse/JDK-8282684

Thanks

2022-03-04 20:12 UTC, iklam commented
Thanks to @dholmes-ora and @jerboaa for the review.
/integrate

2022-03-04 20:14 UTC, closed without merging