8282548: Create a regression test for JDK-4330998
openjdk/jdk pull request #7740
Opened 2022-03-08 10:06 UTC by manukumarvs

Create a regression test for [JDK-4330998](https://bugs.openjdk.java.net/browse/JDK-4330998)

Issue tested:
When calling JEditorPane.setText(null), the following exception is thrown:

java.lang.NullPointerException:
        at java.io.StringReader.<init>(StringReader.java:38)

Testing:
Java 1.4.0 -> Test Failed.
$ ./j2sdk1.4.0/bin/java bug4330998Win
java.lang.RuntimeException: Test failed, caught Exception java.lang.NullPointerException when calling text.setText(null)
        at bug4330998Win.runTest(bug4330998Win.java:45)
        at bug4330998Win.main(bug4330998Win.java:51)
Exception in thread "main"

Java 1.4.1 -> Test Passed.
$ ./j2sdk1.4.1/bin/java bug4330998Win
Test passed

2022-03-08 10:53 UTC, manukumarvs commented
@aivanov-jdk Can you please review this.

2022-03-15 09:37 UTC, manukumarvs commented
Any volunteers?

2022-03-16 16:28 UTC, aivanov-jdk requested changes

2022-03-16 16:28 UTC, aivanov-jdk commented on test/jdk/javax/swing/JEditorPane/4330998/JEditorPaneSetTextNullTest.java
> +             SwingUtilities.invokeAndWait(() -> editorPane.setText(null));
I believe the test could be simplified to
```suggestion
             SwingUtilities.invokeAndWait(() -> new JEditorPane().setText(null));
```
And `createUI()` can be removed.

2022-03-16 16:36 UTC, aivanov-jdk commented on test/jdk/javax/swing/JEditorPane/4330998/JEditorPaneSetTextNullTest.java
> +             SwingUtilities.invokeAndWait(() -> editorPane.setText(null));
If you like to make sure the test expects `NullPointerException` only, you can use try-catch inside the lambda expression and propagate the exception thrown from `invokeAndWait`. Yet it's not required: we don't expect any exceptions thrown. Therefore try-catch can be dropped too.

2022-03-16 16:47 UTC, aivanov-jdk commented on test/jdk/javax/swing/JEditorPane/4330998/JEditorPaneSetTextNullTest.java
> +             SwingUtilities.invokeAndWait(() -> editorPane.setText(null));
> But if we want to throw the RuntimeException with a failure message, I think we need to catch it, right?

Yes, if you want to provide a more specific error message.

2022-03-17 16:39 UTC, manukumarvs commented
/integrate

2022-03-21 07:32 UTC, aivanov-jdk commented
/sponsor

2022-03-21 07:33 UTC, closed without merging