Added missing comments in java.rmi
openjdk/jdk pull request #79
Opened 2020-09-08 15:19 UTC by RogerRiggs

2020-09-08 15:22 UTC, RogerRiggs commented
Add the missing comments where required by javadoc -Xdoclint to document public and serializable classes, methods, and fields.

2020-09-08 15:27 UTC, RogerRiggs commented
/csr

2020-09-08 16:26 UTC, dfuch requested changes

2020-09-08 16:26 UTC, dfuch commented on src/java.rmi/share/classes/java/rmi/activation/ActivationGroupDesc.java
>          private void readObject(ObjectInputStream in)
Hi Roger, you could take this opportunity to add the @serial annotation to this method (here and in the other files you modified as well.

2020-09-08 16:26 UTC, dfuch commented on src/java.rmi/share/classes/java/rmi/activation/ActivationID.java
>      private void writeObject(ObjectOutputStream out)
Same comment as above...

2020-09-08 19:01 UTC, LanceAndersen approved these changes
Hi Roger,

The combined changes to both commits look good

2020-09-08 19:37 UTC, dfuch approved these changes
Otherwise looks good.

2020-09-08 19:37 UTC, dfuch commented on src/java.rmi/share/classes/java/rmi/activation/ActivationID.java
>      private void writeObject(ObjectOutputStream out)
one `@Serial` still missing here?

2020-09-08 19:44 UTC, LanceAndersen approved these changes

2020-09-08 19:45 UTC, dfuch approved these changes

2020-09-08 21:38 UTC, stuart-marks commented on src/java.rmi/share/classes/java/rmi/server/RemoteObject.java
>          throws java.io.IOException
It's a little odd to see an import of java.io.IOException (which is used by the `@throws` tag) but not to have it used here. There's another occurrence down below. These files have a mixture of imports and fully qualified names, which I find irritating, which might be nice to clean up. But you might find beyond the scope of this change. So, clean up as much of this as you like, or none if you prefer, no big deal.

2020-09-08 21:38 UTC, stuart-marks approved these changes

2020-09-09 07:24 UTC, ChrisHegarty approved these changes

2020-09-09 13:16 UTC, RogerRiggs commented
Hi Stuart,

I'm going to leave this for later, its a bit out of scope and every change
prompts the people who have already reviewed it to need to review it again.

Thanks, Roger


On 9/8/20 5:38 PM, Stuart Marks wrote:
>
> *@stuart-marks* commented on this pull request.
>
> ------------------------------------------------------------------------
>
> In src/java.rmi/share/classes/java/rmi/server/RemoteObject.java 
> <https://urldefense.com/v3/__https://github.com/openjdk/jdk/pull/79*discussion_r485210638__;Iw!!GqivPVa7Brio!OBTG2nlJMZowBn3gf_R72ZdA_MzJASDpLUuJFDC4fTAxUL_AnJ9Pfvctp470Fa4a$>:
>
> >       */
> +    @java.io.Serial
>       private void writeObject(java.io.ObjectOutputStream out)
>           throws java.io.IOException
>
> It's a little odd to see an import of java.io.IOException (which is 
> used by the |@throws| tag) but not to have it used here. There's 
> another occurrence down below. These files have a mixture of imports 
> and fully qualified names, which I find irritating, which might be 
> nice to clean up. But you might find beyond the scope of this change. 
> So, clean up as much of this as you like, or none if you prefer, no 
> big deal.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://urldefense.com/v3/__https://github.com/openjdk/jdk/pull/79*pullrequestreview-484510521__;Iw!!GqivPVa7Brio!OBTG2nlJMZowBn3gf_R72ZdA_MzJASDpLUuJFDC4fTAxUL_AnJ9Pfvctp0HjkJMk$>, 
> or unsubscribe 
> <https://urldefense.com/v3/__https://github.com/notifications/unsubscribe-auth/AAIRSVBO6NWK7WC75GOJRETSE2P67ANCNFSM4RAD5TXQ__;!!GqivPVa7Brio!OBTG2nlJMZowBn3gf_R72ZdA_MzJASDpLUuJFDC4fTAxUL_AnJ9Pfvctp5LhysgN$>.
>

2020-09-10 14:38 UTC, closed without merging