JDK-6251738: Want a top-level summary page that itemizes all spec documents referenced from javadocs (OEM spec)
openjdk/jdk pull request #790
Opened 2020-10-22 02:40 UTC by jonathan-gibbons

This introduces support for a new `@spec` tag that can be used as either an inline tag or as a block tag. It is used to identify references to external specifications, in such a way that the references can be collected together on a new summary page, called "Other Specifications", available from either the static INDEX page or the interactive search box.

As an inline tag, the format is `{@spec url label}`, which is roughly translated to `<a href="url">label</a>` in the generated docs.

As a block tag, the format is simply

    @spec url label

which is handled in a manner analogous to

    @see <a href="url">label</a>

The tag is notable for being the first standard/supported tag that can be used as either an inline or block tag. (We have had support for bimodal non-standard/custom tags for a while, such as `{@jls}` and `{@jvms}`. To support a bimodal standard tag, some changes to `DocCommentParser` are incorporated here.

This change is only the _support_ for the new tag;  it does _not_ include any changes to API docs to _use_ the new tag.

2020-10-23 01:00 UTC, jonathan-gibbons commented
/issue add JDK-8226279

2020-10-23 15:43 UTC, jonathan-gibbons commented
/csr

2020-10-23 16:37 UTC, erikj79 approved these changes
Build changes look good.

2020-11-04 15:51 UTC, hns approved these changes
It's very instructive to see a new tag introduced from scratch with all the accompanying infrastructure and tests. The changes looks good to me, but I need to stress than I'm not an expert on some of the affected areas such as the jdk.compiler parts.

2020-11-05 13:13 UTC, pavelrappo commented on src/jdk.compiler/share/classes/com/sun/source/util/DocTreeFactory.java
> +     * @param inline whether this is instance is an inline tag
Should be: 
`* @param inline whether this instance is an inline tag`

2020-11-05 16:16 UTC, pavelrappo requested changes
1. Thanks for incorporating my previous offline feedback.
2. Since Hannes and Erik seem to have looked at everything else, I looked mostly at changes in `src/jdk.compiler/share/classes/com/sun/source/**`, which are good!
3. There should be a corresponding but separate change to "Documentation Comment Specification for the Standard Doclet".
4. Can we use this new `@since` tag to refer to the spec at `com/sun/tools/javac/parser/DocCommentParser.java:1116`?
5. Should we specify in `com.sun.source.doctree.SpecTree` that both `url` and `label` parts are mandatory?
6. `DCSpec extends DCEndPosTree`, sigh... Although that is not a public API, this design suggests we could improve that abstraction sometime later.

2020-11-05 16:16 UTC, pavelrappo commented on src/jdk.javadoc/share/classes/jdk/javadoc/internal/doclets/toolkit/taglets/TagletManager.java
> +            String name = t.isBlockTag() ? "@" + t.getName() : "{@" + t.getName() + "}";
Out of curiosity, why did you flip that?

2020-12-16 18:26 UTC, jonathan-gibbons commented
Closing pull request, until we better decide the contents of the spec page

2020-12-16 18:26 UTC, closed without merging