JDK-8284389
openjdk/jdk pull request #8113
Opened 2022-04-05 20:57 UTC by RealCLanger

Make cygwin usage in GHA more reliable

With this change we now attempt to retrieve the cygwin installer from cache every time we need it.
We would also only try to download it once per build job, in the beginning.
During testing we rely on it being cached which will make potential errors more obvious
(e.g. in the download step in the beginning of the build).

I also replaced actions/cache@v2 with v3. Didn't see issues.

2022-04-06 07:40 UTC, shipilev requested changes
Let's not switch `v2` -> `v3` in this PR.

So `windows_aarch64_build`, `windows_x64_build` checks the cache and adds recovery step. But `windows_x64_test` does not do it? Why? If the cygwin installer was cached, it would work fine, but if it does not -- for example if `windows_x64_test` job is restarted in isolation after cache flush -- it would break? I think we should be consistent in this: if installer is not in cache, we always do the recovery.

2022-04-06 10:32 UTC, RealCLanger commented
> Let's not switch `v2` -> `v3` in this PR.
You're right. I'll do another PR to update the actions versions. There are also updates possible for upload and donwload actions.

> So `windows_aarch64_build`, `windows_x64_build` checks the cache and adds recovery step. But `windows_x64_test` does not do it? Why? If the cygwin installer was cached, it would work fine, but if it does not -- for example if `windows_x64_test` job is restarted in isolation after cache flush -- it would break? I think we should be consistent in this: if installer is not in cache, we always do the recovery.

Yeah, I wasn't happy with this, too. I, however, thought that we could maybe assume that the build step was run successfully before the test step and therefore the cygwin installer should be in the cache and we would never fail. But, I guess you're right, the cache could be evicted in between due to whatever reason and we're unnecessarily abstaining from a safety net.

What I want to accomplish is that if it fails due to an issue with downloading the cygwin installer, it should fail in the build job, not later. But this should be the case in 99.99% now anyway, due to the added caching.

I will implement your suggestions.

2022-04-06 11:42 UTC, shipilev approved these changes
This looks fine, assuming GHA workflows are green.

2022-04-07 06:01 UTC, RealCLanger commented
Thanks for the review.
/integrate

2022-04-07 06:01 UTC, RealCLanger commented
Thanks for the review.
/integrate

2022-04-07 06:03 UTC, closed without merging