8284532: Memory leak in BitSet::BitMapFragmentTable in JFR leak profiler
openjdk/jdk pull request #8148
Opened 2022-04-07 17:41 UTC by zhengyu123

BitSet::BitMapFragmentTable needs a destructor to cleanup its contents to avoid leaking hashtable entries and bucket array.

2022-04-07 18:17 UTC, tstuefe requested changes
Hi Zhengyu,

small remark inline, otherwise this looks okay. This should really be a utility function in BasicHashMap. 

What tests did you run?

Cheers, Thomas

Note that there is https://github.com/openjdk/jdk/pull/7964 open too, but it may be easier to get this one in first to keep it easy to backport.

2022-04-07 18:17 UTC, tstuefe commented on src/hotspot/share/jfr/leakprofiler/chains/bitset.cpp
> +    free_buckets();
Doesn't ~BasicHashtable do free_buckets already?

2022-04-07 18:44 UTC, zhengyu123 commented on src/hotspot/share/jfr/leakprofiler/chains/bitset.cpp
> +    free_buckets();
Right. FIxed.

2022-04-07 18:50 UTC, zhengyu123 commented
> Hi Zhengyu,
> 
> small remark inline, otherwise this looks okay. This should really be a utility function in BasicHashMap.

Probably, I would like to defer it to separate CR, which it may touch quite a few places.

> 
> What tests did you run?
> 
Manual test with JFR recording `path-to-gc-roots=true`, then run `jcmd  JFR.dump`

> Cheers, Thomas
> 
> Note that there is #7964 open too, but it may be easier to get this one in first to keep it easy to backport.

2022-04-08 03:42 UTC, tstuefe commented
> > Hi Zhengyu,
> > small remark inline, otherwise this looks okay. This should really be a utility function in BasicHashMap.
> 
> Probably, I would like to defer it to separate CR, which it may touch quite a few places.
> 

Sure. You just follow established patterns here.

> > What tests did you run?
> 
> Manual test with JFR recording `path-to-gc-roots=true`, then run `jcmd JFR.dump`

How did you notice the memory leak? In NMT dumps?

2022-04-08 03:42 UTC, tstuefe approved these changes
Looks good!

2022-04-08 09:31 UTC, mgronlun approved these changes
Looks good, thanks.

2022-04-08 11:24 UTC, shipilev approved these changes
Looks fine, modulo a bit of indenting.

2022-04-08 11:24 UTC, shipilev commented on src/hotspot/share/jfr/leakprofiler/chains/bitset.cpp
> +    }
I think indenting is a bit off here: should be 2 spaces at all columns. Probably a copy-paste--from-destructor error.

2022-04-08 14:56 UTC, zhengyu123 commented
Thanks, @tstuefe @mgronlun @shipilev

2022-04-08 14:56 UTC, zhengyu123 commented
/integrate

2022-04-08 14:58 UTC, closed without merging

2022-04-26 19:40 UTC, zhengyu123 commented
> > > Hi Zhengyu,
> > > small remark inline, otherwise this looks okay. This should really be a utility function in BasicHashMap.
> > 
> > 
> > Probably, I would like to defer it to separate CR, which it may touch quite a few places.
> 
> Sure. You just follow established patterns here.
> 
> > > What tests did you run?
> > 
> > 
> > Manual test with JFR recording `path-to-gc-roots=true`, then run `jcmd JFR.dump`
> 
> How did you notice the memory leak? In NMT dumps?

Sorry, missed this comment earlier. No, I found it with `valgrind`