8284734
openjdk/jdk pull request #8196
Opened 2022-04-12 08:18 UTC by albertnetymk

Small change of fixing a crash if using `ReferentBasedDiscovery`.

Test: hotspot_gc

2022-04-18 10:15 UTC, kimbarrett requested changes
There really needs to be some testing with ReferentBasedDiscovery.

2022-04-18 10:15 UTC, kimbarrett commented on src/hotspot/share/gc/shared/referenceProcessor.cpp
> +    return true;
Can the UseG1GC test instead be discovery_is_concurrent()?  The old comments talk about concurrent discovery.  But can a G1 young-only collection during a concurrent cycle attempt to discover a reference that is already in the CM reference processor?  I'm not sure, and the discovery policy might be relevant to the answer.

2022-04-18 10:39 UTC, albertnetymk commented on src/hotspot/share/gc/shared/referenceProcessor.cpp
> +    //     mark stack.
True, but due to the use of `_finger` (bounded mark-stack), duplicate oops can still exist. The comment in that method covers that.

2022-04-18 10:39 UTC, albertnetymk commented on src/hotspot/share/gc/shared/referenceProcessor.cpp
>    HeapWord* const discovered_addr = java_lang_ref_Reference::discovered_addr_raw(obj);
I will do a clean-up PR afterwards. Thank you for the suggestion.

2022-04-18 10:52 UTC, albertnetymk commented on src/hotspot/share/gc/shared/referenceProcessor.cpp
> +    return true;
> It would be better to entirely avoid the fetch of discovered here for other collectors in non-debug builds.

Agree; since this is a bugfix, I went for the less intrusive approach.

> Can the UseG1GC test instead be discovery_is_concurrent()?

Rediscovery is caused by a peculiar impl detail (`_finger`) in CM not CM being concurrent. Testing `discovery_is_concurrent()` can be a bit misleading. (Both are correct though, because G1 is the only concurrent collector using ref-processor.)

>  But can a G1 young-only collection during a concurrent cycle attempt to discover a reference that is already in the CM reference processor?

No, it cannot, because at the start of young-gc, all refs in CM discovered list are treated as roots, as shown in `G1RootProcessor::evacuate_roots`. IOW, the discovered lists of young-gc and CM share no refs.

2022-04-19 08:47 UTC, albertnetymk commented
> There really needs to be some testing with ReferentBasedDiscovery.

Tier1-6 pass with `-XX:RefDiscoveryPolicy=1`.

2022-04-19 10:17 UTC, kimbarrett commented
> > There really needs to be some testing with ReferentBasedDiscovery.
> 
> Tier1-6 pass with `-XX:RefDiscoveryPolicy=1`.

I meant repeated / CI testing.  Otherwise will just bit-rot.

2022-04-22 08:02 UTC, albertnetymk commented
> I meant repeated / CI testing. Otherwise will just bit-rot.

My plan is to remove `RefDiscoveryPolicy`, having only one policy. I am leaned towards keeping `ReferentBasedDiscovery`, the non-default one, but we can cross that bridge when we get there.

2022-06-17 22:54 UTC, closed without merging