8284642: Unexpected behavior of -XX:MaxDirectMemorySize=0
openjdk/jdk pull request #8222
Opened 2022-04-13 12:24 UTC by hseigel

Please review this small fix for JDK-8284642.  The fix was tested by running Mach5 tiers 1-2 on Linux, Mac OS, and Windows, and Mach5 tiers 3-5 on Linux x64.  Additionally, the modified test and the test in the bug report were run locally.

Thanks, Harold

2022-04-13 12:29 UTC, hseigel commented
/label add hotspot_runtime

2022-04-13 14:11 UTC, AlanBateman commented
If nothing else, I think the man page could be improved to say that JVM chooses the size for NIO direct-buffer allocations automatically when MaxDirectMemorySize is not set.

2022-04-13 14:22 UTC, tstuefe commented
I looked a little, and found no example on GH or Google which relied on MaxDirectMemorySize=0 to disable. I found some examples of the opposite, e.g. https://github.com/cloudfoundry/java-buildpack/issues/591. So this is fine I think.

2022-04-13 14:23 UTC, tstuefe approved these changes

2022-04-16 12:20 UTC, dholmes-ora commented
I don't this is the right "fix". There is a bit of a disconnect between the VM option and the system property. Although the default value of the VM flag is zero, that is ignored and the JDK side, not being directed otherwise, determines the max size. If you set the flag explicitly to zero that is passed through to the JDK and the max memory is actually set to zero.

I think this is more a documentation issue - MaxDirectMemory has no affect unless explicitly set on the command-line. The default value of the flag is actually irrelevant.

2022-04-19 01:41 UTC, dholmes-ora requested changes
See main comment

2022-04-21 18:22 UTC, hseigel commented
Should no changes be made to the code, instead just remove "the size is set to 0, meaning that" from the description of LargePageSizeInBytes?

-XX:LargePageSizeInBytes=size
Sets the maximum large page size (in bytes) used by the JVM. The size argument must be a valid page size supported by the environment to have any effect. Append the letter k or K to indicate kilobytes, m or M to indicate megabytes, or g or G to indicate gigabytes. By default, **the size is set to 0, meaning that** the JVM will use the default large page size for the environment as the maximum size for large pages.

2022-04-22 00:22 UTC, dholmes-ora commented
I would delete the last sentence:

> By default, the size is set to 0, meaning that the JVM chooses the size for NIO direct-buffer allocations automatically.

and replace with:

> If not set, the flag is ignored and the JVM chooses the size for NIO direct-buffer allocations automatically.

2022-04-22 18:09 UTC, hseigel commented
Please review the updated man page change.
Thanks, Harold

2022-04-23 05:42 UTC, dholmes-ora commented
I didn't realize that text was from the manpage. It is fine but I think we also need something in globals.hpp:

```
 product(uint64_t, MaxDirectMemorySize, 0,                                 \
          "Maximum total size of NIO direct-buffer allocations. "        \
          "Ignored if not explicitly set.")
          range(0, max_jlong)                                               \

```

2022-04-25 14:22 UTC, hseigel commented
Hi David,  Thanks for looking at this and for the suggested text.  Please review this latest commit to fix the text in globals.hpp.
Thanks, Harold

2022-04-25 22:50 UTC, dholmes-ora approved these changes
That all looks good to me.

Thanks,
David

2022-04-26 19:01 UTC, closed without merging