8253734: Optimize Move nodes
openjdk/jdk pull request #826
Opened 2020-10-23 08:27 UTC by iwanowww

Introduce the following transformations for Move nodes: 
1. `MoveI2F (MoveF2I x) => x`

1. `MoveI2F (LoadI mem) => LoadF mem` 

1. `StoreI mem (MoveF2I x) => StoreF mem x` 

(The same applies to MoveL2D/MoveD2L.)

№1 eliminates redundant operations and №2/№3 avoid reg-to-reg moves in generated code:
```
0x000000010d09964c:   vmovss 0x20(%rsi),%xmm1
0x000000010d099651:   vmovd  %xmm1,%eax                   ;*invokestatic floatToRawIntBits
```
vs
```
0x0000000110c5a6cc:   mov    0x20(%rsi),%eax              ;*invokestatic floatToRawIntBits
``` 

(№2 and №3 are performed late (after loop opts are over) to avoid high-level optimizations passes to handle newly introduced mismatched accesses.)

Testing: tier1-5.

2020-10-23 08:28 UTC, iwanowww commented
/label add hotspot-compiler

2020-10-23 09:20 UTC, TobiHartmann requested changes
Maybe add some comments with examples to the reinterpret methods.

2020-10-23 09:20 UTC, TobiHartmann commented on src/hotspot/share/opto/movenode.hpp
> +    init_class_id(Class_Move);
Shouldn't `init_class_id` be moved to the `MoveNode` constructor?

2020-10-23 09:20 UTC, TobiHartmann commented on src/hotspot/share/opto/movenode.hpp
> +//  virtual const Type* Value(PhaseGVN* phase) const;
Can be removed.

2020-10-23 11:08 UTC, iwanowww commented
Thanks for the quick feedback, Tobias!

Please, take a look at the updated version.

2020-10-23 12:06 UTC, TobiHartmann approved these changes
Looks good to me. Thanks for making these changes!

2020-10-23 12:39 UTC, neliasso approved these changes
Looks good!

2020-10-23 16:56 UTC, vnkozlov approved these changes
Proposed optimization looks fine. In what cases you see the issues?

2020-10-23 21:28 UTC, blaquez approved these changes

2020-10-23 21:29 UTC, blaquez commented
Would love to merge

2020-10-23 21:29 UTC, blaquez approved these changes

2020-10-24 04:41 UTC, blaquez approved these changes

2020-10-24 04:42 UTC, blaquez commented
Thanks

2020-10-24 04:43 UTC, blaquez approved these changes

2020-10-26 17:22 UTC, iwanowww commented
/integrate

2020-10-26 17:23 UTC, iwanowww commented
Thanks for the reviews, Vladimir, Tobias, and Nils.

2020-10-26 17:24 UTC, closed without merging