8284903: Fix typos in hotspot
openjdk/jdk pull request #8260
Opened 2022-04-15 07:40 UTC by magicus

I ran `codespell` on hotspot, and accepted those changes where it indeed discovered real typos. 

You'd be surprised over the many implementions of instrinsics and other intructions accross all archtectures I've encounted, so for the preceding reason it's neccesery to sucessfully seach for exisiting typos...

2022-04-15 19:27 UTC, plummercj approved these changes
I tried to cover all serviceability files, but didn't want to pick and choose individual files within any given directory, so I reviewed all files in any directory that contained a serviceability related file. So the following were covered by my review:

src/os
src/os_cpu
src/share/prims
src/share/services

2022-04-15 19:27 UTC, plummercj commented on src/hotspot/share/prims/jvmtiThreadState.hpp
> +  // is event_type enabled and usable for this thread in any environments?
Should it be "environment"?

2022-04-15 19:27 UTC, plummercj commented on src/hotspot/share/services/memTracker.hpp
> +  // chunks that backing up the arena.
This doesn't read correctly (not due to your change). Perhaps "that back up" or "that are backing up" is what was intended.

2022-04-18 17:55 UTC, coleenp approved these changes
I checked all directories except gc, jfr, metaspace, opto and jvmti.

2022-04-18 18:37 UTC, vnkozlov approved these changes
Nice work!

I reviewed compiler related code:
`cpu`, `os`, `os_cpu`, `share/adlc`, `share/c1`, `share/ci`, `share/code`, `share/compiler`, `share/jvmci`, `share/opto`.

2022-04-19 00:23 UTC, dholmes-ora requested changes
Hi Magnus,

Generally looks good. Thanks for doing this extremely tedious cleanup.

A few comments/suggestions/corrections below.

And of course copyright dates need updating for Oracle copyrights.

Thanks,
David

2022-04-19 00:23 UTC, dholmes-ora commented on src/hotspot/share/runtime/os.cpp
> +  // On malloc(0), implementers of malloc(3) have the choice to return either
I suggest "implementations of malloc..."

2022-04-19 00:23 UTC, dholmes-ora commented on src/hotspot/share/runtime/task.hpp
> +  // Make the task deactivate
Should be "inactive"

2022-04-19 00:23 UTC, dholmes-ora commented on src/hotspot/share/services/threadIdTable.cpp
>        // There is no obvious benefits in allowing the thread table
s/benefits/benefit/

2022-04-19 00:23 UTC, dholmes-ora commented on src/hotspot/share/services/threadIdTable.cpp
> +      // to be concurrently populated during the initialization.
delete "the"

2022-04-19 08:49 UTC, dougxc commented
Are there plans to add `codespell` to the make system to somehow catch/prevent spelling regressions in future? I understand this may not be feasible.

2022-04-19 08:58 UTC, XenoAmess commented
> Are there plans to add `codespell` to the make system to somehow catch/prevent spelling regressions in future? I understand this may not be feasible.

IMO all spell checking mechanisms suffers from false positive and need human manual job to filter them...
So maybe we can only arrange a scan per year or per months...

2022-04-19 14:00 UTC, magicus commented
Thank you for all your input! I will update the PR according to all suggestions. But let me answer a few more general comments first.

The spelling corrections in this PR was generated by codespell. I manually removed all false positives (that was the most tedious part of this fix). Codespell works by checking a list of commonly misspelled words, not by verifying that all words are present in a list of accepted spellings. The latter approach might work for normal prose, but is utterly worthless for source code. In practice, codespell does automatically what several users have been doing manually lately -- discover a common misspelling, searching the code base for more instances of that misspelling. So, there are certainly lots of typos left. But this should reasonably cut down on the number of PRs of the type "Fix typos for supercalifragilisticexpialidocious" that updates a lot of files for just a single misspelled word.

For some cases where I were not sure (like mismatch or re-enable), I googled, read spelling recommendations and/or checked how common alternative spellings where. When the ratio exceeded 10:1 or so, I deemed one alternative as "correct"; in less common cases I let the original authors choice of spelling remain.

I have not read the complete sentences, just verified that the actual word fixes seemed to make sense. Hence the odd results in some places. 

Ideally, I would like to find some way of keeping the code "codespell clean" using tooling. Due to the amount of false positives, this is not a trivial task. I don't think we'll ever be able to have it as part of jcheck, but we might have a script that someone runs once per release or so. I'm not yet sure how to achieve this, but my two main ideas is to either just run codespell on added or modified code (think "+" lines in git diff), or to have a list of acknowledged false positives that should be skipped.

Before I can even start on this, the huge number of *true* positives needs to be addressed, though! Hotspot is by no means worst, it's just a huge chunk of code which I addressed all at once.

2022-04-19 17:29 UTC, RealLucy approved these changes
This is a partial approval for 
 - cpu/ppc
 - cpu/s390
 - os/aix
 - os_cpu/aix_ppc
 - os_cpu/linux_ppc
 - os_cpu/linux_s390

Thank you for completing this tedious job!

2022-04-19 18:02 UTC, stefank approved these changes
Reviewed:
gc/
oops/
utilities/

2022-04-19 19:09 UTC, magicus commented
/integrate

2022-04-19 19:11 UTC, closed without merging

2022-04-20 06:18 UTC, dholmes-ora commented on src/hotspot/share/runtime/task.hpp
> +  // Make the task inactivate
That should have been "inactive".