8196465: javax/swing/JComboBox/8182031/ComboPopupTest.java fails on Linux
openjdk/jdk pull request #829
Opened 2020-10-23 09:50 UTC by prsadhuk

Please review a test fix for an issue seen to be failing in mach5 testing on linux whereby the combo popup is not opening.
The issue is not reproducible locally in ubuntu18.04 but mach5 testing on ubuntu18.04 was able to see the issue. 
Combo popup was opened by clicking at right edge of combo box, which sometimes is not set properly at mach5 system, so mouse click is clicked at wrong location of frame, thereby not opening the combo popup.
 Modified the test to open the combo popup by clicking on middle of combobox which now works for all. Also, made robot autodelay consistent with other test to be 100ms. Also, changed deprecated constant to appropriate constants.
Mach5 job was run for several iteration on all 3 platforms. Link in JBS

2020-10-24 06:26 UTC, mrserb commented
This test was created for this bug:
https://bugs.openjdk.java.net/browse/JDK-8182031

> A DESCRIPTION OF THE PROBLEM :
> When clicking the right-most pixel of a JComboBox the related Popup opens and closes immediately. Happens on any tested Look & Feel (Metal, Windows, Nimbus, BizLookAndFeel). 

So it looks like the usage of the right-most pixel to open the popup is intentional,

2020-10-24 23:14 UTC, prrace approved these changes

2020-10-25 00:49 UTC, mrserb requested changes
I think this is a product bug.

2020-10-25 07:31 UTC, prsadhuk commented
I also thought initially it's a product bug but it is passing in my local ubuntu18.04

2020-10-25 08:15 UTC, mrserb commented
> I also thought initially it's a product bug but it is passing in my local ubuntu18.04

But it fails in CI, something in the configuration difference cause that.

2020-11-01 17:36 UTC, closed without merging