8255305: Add Linux x86_32 tier1 to submit workflow
openjdk/jdk pull request #830
Opened 2020-10-23 10:04 UTC by shipilev

Following JDK-8254282, it seems useful to also run tier1 tests on 32-bit platform, because that finds problems with runtime tests and internal asserts. Those problems do not show up during the plain build. Again, while x86_32 might not be widely deployed by itself, but 32/64 bit cleanliness detects bugs that manifest on ARM32 early.

2020-10-26 22:16 UTC, magicus commented
See my comments in https://github.com/openjdk/jdk/pull/869

2020-10-27 05:54 UTC, shipilev commented
> See my comments in #869

See my comments in #869 as well. Let's integrate this to get the testing going, and then do cosmetic improvements.

2020-10-27 10:36 UTC, magicus requested changes
Please incorporate the additional fixes in https://github.com/openjdk/jdk/pull/869 into this PR. That also means that the new code here that mentions "linux-x32" needs to be renamed. After that, you can close #869.

2020-10-27 10:39 UTC, shipilev commented
While I am still not sure folding these two together is perfect, did so! Please re-review, @magicus. (Now to wait and see that testing is still fine).

2020-10-27 10:49 UTC, magicus approved these changes
Looks good to me now. Thank you!

2020-10-27 13:22 UTC, shipilev commented
Testing is still clean apart for missing #833 change. Okay to push then?

2020-10-27 13:32 UTC, magicus commented
I think you should wait for the problem list. Otherwise you'll introduce intentional test breakage in GH actions.

2020-10-27 13:55 UTC, shipilev commented
#833 is now merged, I am pushing this to get other PRs retested with x86_32.

/integrate

2020-10-27 13:57 UTC, closed without merging