8285305: Create an automated test for JDK-4495286
openjdk/jdk pull request #8333
Opened 2022-04-21 10:51 UTC by srmandal

Create an automated test for [JDK-4495286](https://bugs.openjdk.java.net/browse/JDK-4495286)

AccessibleJTable.setAccessibleSelction should select rows/cols when cell selection.
When cell selection is not enabled, there is no way, using
accessibility, to select rows or columns. It seems logical that selecting a cell
using accessibility should have the same effect as clicking on a cell with the
mouse. That is, if row or column selection is enabled, then selecting a cell
should instead cause the row or column to be selected.
 The proposed test verifies that the above behavior is fixed.

This review is for migrating tests from a closed test suite to open.

Testing:
The test ran successfully on Mach5 with multiple runs (40) on windows-x64, linux-x64 and macos-x64.

2022-04-25 13:23 UTC, srmandal commented
Hi! Can someone please take a look at this PR and provide their valuable feedback ?

2022-04-27 07:15 UTC, mrserb commented on test/jdk/javax/accessibility/4495286/AccessibleJTableSelectionTest.java
> + * published by the Free Software Foundation.
typo

2022-04-27 08:46 UTC, srmandal commented on test/jdk/javax/accessibility/4495286/AccessibleJTableSelectionTest.java
> + * published by the Free Software Foundation.
Fixed.

2022-05-05 23:58 UTC, prrace requested changes
Get rid of the useless extra directory level

2022-05-18 08:15 UTC, srmandal commented
> Get rid of the useless extra directory level

Done.

2022-05-18 08:16 UTC, srmandal commented
Hi! Can someone please take a look at this PR and provide their valuable feedback & approval?

2022-06-03 06:10 UTC, srmandal commented
/integrate

2022-06-03 21:25 UTC, mrserb commented
/sponsor

2022-06-03 21:28 UTC, closed without merging