8255298: Remove SurvivorAlignmentInBytes functionality
openjdk/jdk pull request #838
Opened 2020-10-23 15:16 UTC by tschatzl

Hi all,

  can I have reviews to remove the SurvivorAlignmentInBytes functionality? It has not been in use for a long time if ever, and can be removed. Searching the web also indicates that apart from the usual lists of all options and CRs it is never mentioned.

SurvivorAlignmentInBytes is an experimental option so no further process is required.

Testing: tier1-5

Thanks,
  Thomas

2020-10-23 15:51 UTC, shipilev requested changes
Nifty cleanup! One nit I see:

2020-10-23 15:51 UTC, shipilev commented on src/hotspot/share/gc/parallel/psPromotionLAB.inline.hpp
>    if (obj == NULL) {
`obj` cannot be `NULL` now?

2020-10-23 17:20 UTC, tschatzl commented
Done, thanks for catching this.

2020-10-23 17:22 UTC, shipilev approved these changes
These look fine to me.

2020-10-26 07:42 UTC, albertnetymk approved these changes

2020-10-26 08:24 UTC, kimbarrett commented on src/hotspot/share/gc/parallel/psPromotionLAB.inline.hpp
>      set_top(obj);
I think we don't need this set_top anymore.

2020-10-27 09:45 UTC, tschatzl commented
@kimbarrett : fixed in new revision. Thanks!

2020-10-27 21:56 UTC, kimbarrett approved these changes

2020-10-29 08:46 UTC, tschatzl commented
Thanks @kstefanj @kimbarrett @shipilev for your reviews.

/integrate

2020-10-29 08:49 UTC, closed without merging