8285279: ArgumentsTest.set_numeric_flag_double_vm fails on some locales (again)
openjdk/jdk pull request #8386
Opened 2022-04-25 19:04 UTC by iklam

Please review this trivial fix for ArgumentsTest.set_numeric_flag_double_vm. If an input string is only partially accepted by `strtod()` under the current locale , `end` will point to a non-empty character. In this case, the test should treat the input as invalid.

Thanks to @tstuefe for providing the test scenario.

2022-04-25 23:03 UTC, dholmes-ora requested changes

2022-04-25 23:53 UTC, iklam commented on test/hotspot/gtest/runtime/test_arguments.cpp
> +    if (errno == 0 && end != NULL && *end == '\0') {
Yes, that check is on line 609 below.

2022-04-26 00:09 UTC, dholmes-ora commented on test/hotspot/gtest/runtime/test_arguments.cpp
> +    if (errno == 0 && end != NULL && *end == '\0') {
Sorry missed that.

2022-04-26 00:09 UTC, dholmes-ora approved these changes

2022-04-27 04:57 UTC, iklam commented
Thanks @dholmes-ora for the review.
/integrate

2022-04-27 04:58 UTC, closed without merging