8285687 : Remove jtreg tag manual=yesno for ava/awt/print/PrinterJob/PageRangesDlgTest.java
openjdk/jdk pull request #8412
Opened 2022-04-27 00:06 UTC by lawrence-andrew

1) Fixed Parser error by removing  yesno from @run main/manual=yesno 
2) Used PassFaileJFrame to show the test instruction to the user instead of printing the test instruction on the console or jtreg log file. 
3) If printer is not configured then mark the test as passed.

@shurymury 
@aivanov-jdk

2022-04-27 07:08 UTC, mrserb commented
The question about this and other tests is, should the test pass if the printer is not installed? I guess the printer is one of the pre-requirements for such tests and it should be configured properly.

2022-04-27 07:19 UTC, GoeLin commented
Hi,  if this needs a printer, you might want to add @key printer? Best regards, Goetz

2022-04-27 18:04 UTC, prrace approved these changes

2022-04-28 05:29 UTC, lawrence-andrew commented
/integrate

2022-04-29 00:41 UTC, mrserb commented
Since the test now uses the printer keyword I doubt that it should pass silently if the printer is not installed.

2022-04-29 05:58 UTC, mrserb commented
> @mrserb, run the test on Ubuntu 20.04 where printer is not configured and test passes as shown in the jtreg jtr file

That's my point, why does the manual test for the printer silently pass if the printer is not installed.

2022-04-29 16:51 UTC, prrace commented
One thing we could start to do is use jtreg.SkippedException - which you define yourself.
It is a "special" in that jtreg recognises it as meaning a test was skipped due to some reason
that could not/was not determined before running. 
The test passes but with a special message so you know it didn't really run the test.
https://openjdk.java.net/jtreg/faq.html#what-if-a-test-does-not-apply-in-a-given-situation

For manual tests it might be good to change PassFailJFrame to be able to put up a  special message to the user in such a case and  disable "fail" ..

2022-05-17 19:16 UTC, aivanov-jdk commented
Can't we use existing `jtreg.SkippedException` in `test/lib`?

Modify PageRangesDlgTest:

```diff
diff --git a/test/jdk/java/awt/print/PrinterJob/PageRangesDlgTest.java b/test/jdk/java/awt/print/Pri
nterJob/PageRangesDlgTest.java
index 77be99107d1..0d8ce30057a 100644
--- a/test/jdk/java/awt/print/PrinterJob/PageRangesDlgTest.java
+++ b/test/jdk/java/awt/print/PrinterJob/PageRangesDlgTest.java
@@ -37,9 +37,9 @@ import jtreg.SkippedException;
  * @bug 8061267
  * @key printer
  * @library /java/awt/regtesthelpers
- * @library /java/awt/jtreg
+ * @library /test/lib
  * @build PassFailJFrame
- * @build SkippedException
+ * @build jtreg.SkippedException
  * @summary The specified page range should be displayed in the dialog
  * @run main/manual PageRangesDlgTest
  */
```

The test can't pass when the native Print dialog is displayed: `aset` should be passed to it:
```diff
@@ -58,7 +58,7 @@ public class PageRangesDlgTest implements Printable {
         job = PrinterJob.getPrinterJob();
         job.setPrintable(new PageRangesDlgTest());
         aset.add(DialogTypeSelection.NATIVE);
-        if (job.printDialog()) {
+        if (job.printDialog(aset)) {
             job.print();
         }
     }
```

2022-05-17 19:20 UTC, aivanov-jdk requested changes

2022-05-17 19:20 UTC, aivanov-jdk commented on test/jdk/java/awt/print/PrinterJob/PageRangesDlgTest.java
> +        if (PrinterJob.lookupPrintServices().length > 0) {
The inverted condition produces cleaner code with less indentation:

```java
        if (PrinterJob.lookupPrintServices().length == 0) {
            throw new SkippedException("Printer not configured or available."
                                       + " Test cannot continue.");
        }

        // Rest of the test code
```

2022-05-18 16:58 UTC, lawrence-andrew commented
/integrate

2022-05-18 17:48 UTC, aivanov-jdk approved these changes

2022-05-19 08:03 UTC, aivanov-jdk commented
/sponsor

2022-05-19 08:04 UTC, closed without merging