8255342: Remove non-specified JVM checks on Classes with Record attributes
openjdk/jdk pull request #845
Opened 2020-10-23 20:30 UTC by hseigel

Please review this fix to remove the checks for non-final and abstract classes containing Record attributes and checks for classes containing Record attributes whose supers are not java.lang.Record.  These checks are not specified in the JVM Spec and so should not be done by the JVM.

The change removes the checks and updates Record tests as needed.

The fix was tested with mach5 tiers 1 and 2 on Linux, Windows, and Mac, and tiers 3-5 on Linux x64 and with JCK lang, vm, and api/java_lang tests.

Thanks, Harold

2020-10-26 03:54 UTC, dholmes-ora requested changes
Hi Harold,
Generally looks good, but you need a new test case - see below.
Thanks,
David

2020-10-26 03:54 UTC, dholmes-ora commented on test/hotspot/jtreg/runtime/records/recordAttributeTest.java
> +        runTest("superNotJLRecord", "Truncated class file");
This simple "inversion" of the test is not sufficient. The original test was that a bad record attribute is ignored when not a subclass of j.l.Record. The modified test should be that a bad record attribute is never ignored. But in addition there should be a new test that a good record attribute in a class that does not subclass j.l.Record, is also okay.

2020-10-26 15:21 UTC, hseigel commented
Hi David,
Thanks for looking at this change.  Please review the updated commit that adds the missing test case.
Thanks, Haorld

2020-10-26 22:47 UTC, dholmes-ora approved these changes
Thanks for adding the additional test.

David

2020-10-27 11:56 UTC, coleenp approved these changes
Looks good, Harold!

2020-10-27 12:21 UTC, hseigel commented
Thanks David and Coleen for the reviews!

2020-10-27 12:22 UTC, hseigel commented
/integrate

2020-10-27 12:23 UTC, closed without merging

2020-10-27 16:45 UTC, rose00 commented
This was a good example of a VM anti-pattern that's easy to fall into, which I call "The Gratuitous Restriction".  There's a wide range of correctness checks the VM *could* do, but deciding which ones it *should* do is surprisingly subtle.  When designing a new feature, there's a certain impulse to reject every suspicious input, and even to fish around in the design asking "what can we reject, that doesn't appear to have a meaning?"  This impulse is (often) rooted in a legitimate desire to reduce implementation work by constraining inputs (rejecting a class file before trying to interpret something that smells funny).  But there are four downsides:

1. The rejected thing might turn out to have a meaning after all, but now we are blocked from discovering what it might be.  (This is my favorite.  When once we said "value types can't extend abstract classes", I thought, "yeah, that's what we're saying now; just wait a while.")

2. The rejection we threw into the code to save ourselves work has to be rigorously specified in the JVMS and kept there forever.  (We may get tired of looking at it, and it may obscure more important material in the JVMS.)

3. The rejection we threw into the code to save ourselves work has to be maintained forever, and if we ever disturb it our own VM will be non-compliant with the JVMS.  (We may get tired of maintaining it.)

4. Maybe, if you get into the habit of making them, they can build up as performance debt.  Enough extra checks will start to slow down the JVM.