8286172: Create an automated test for JDK-4516019
openjdk/jdk pull request #8546
Opened 2022-05-05 06:58 UTC by srmandal

Create an automated test for [JDK-4516019](https://bugs.openjdk.java.net/browse/JDK-4516019)

Clicking on the increment/decrement buttons of the spinner does not install focus on the spinner or one of its focusable children.

The test validates the same.

This review is for migrating tests from a closed test suite to open.

Testing:
The test ran successfully on Mach5 with multiple runs (30) on windows-x64, linux-x64 and macos-x64.

2022-05-05 19:00 UTC, prrace requested changes

2022-05-05 19:00 UTC, prrace commented on test/jdk/javax/swing/4516019/JSpinnerFocusTest.java
> +            e.printStackTrace();
Shouldn't the test fail if we get an exception ?

2022-05-05 23:55 UTC, prrace requested changes
Also you are doing the same thing I've told others not to - look at the path name

test/jdk/javax/swing/4516019/JSpinnerFocusTest.java

what is the point of 4516019 ? Do NOT create an extra directory for no reason.
especially one just numbered for a bugid
and in this case this test should go in the pre-existing JSpinner directory !

2022-05-17 12:25 UTC, srmandal commented on test/jdk/javax/swing/4516019/JSpinnerFocusTest.java
> + * does not get focus onto the spinner.
Changed appropriately.

2022-05-17 12:25 UTC, srmandal commented on test/jdk/javax/swing/4516019/JSpinnerFocusTest.java
> +            robot.delay(300);
Done

2022-05-17 12:26 UTC, srmandal commented on test/jdk/javax/swing/4516019/JSpinnerFocusTest.java
> +            }
Done

2022-05-17 12:27 UTC, srmandal commented
> Also you are doing the same thing I've told others not to - look at the path name
> 
> test/jdk/javax/swing/4516019/JSpinnerFocusTest.java
> 
> what is the point of 4516019 ? Do NOT create an extra directory for no reason. especially one just numbered for a bugid and in this case this test should go in the pre-existing JSpinner directory !

As suggested:
Test removed from the original location. 
Test added under pre-existing JSpinner directory.

2022-05-23 17:23 UTC, alisenchung requested changes

2022-05-23 17:23 UTC, alisenchung commented on test/jdk/javax/swing/JSpinner/JSpinnerFocusTest.java
> +            Thread.sleep(1000);
Would it be better to make robot a global variable and use Robot.waitForIdle() here? Sleeping might slow down the test unnecessarily

2022-05-23 17:23 UTC, alisenchung commented on test/jdk/javax/swing/JSpinner/JSpinnerFocusTest.java
> +            Thread.sleep(1000);
same here

2022-06-09 08:33 UTC, srmandal commented on test/jdk/javax/swing/JSpinner/JSpinnerFocusTest.java
> +            Thread.sleep(1000);
Fixed as suggested.

2022-06-09 19:08 UTC, alisenchung approved these changes

2022-06-10 05:37 UTC, srmandal commented
/integrate

2022-06-15 05:10 UTC, srmandal commented
Hi! Can someone please take a look at this PR and provide their valuable feedback and approval?

2022-07-02 03:52 UTC, srmandal commented
Hi! Can someone please take a look at this PR and provide their valuable feedback and approval?

2022-07-14 05:03 UTC, srmandal commented
Hi! Can someone please sponsor this PR?

2022-07-15 20:41 UTC, prrace approved these changes

2022-07-16 00:47 UTC, srmandal commented
/integrate

2022-07-16 00:48 UTC, srmandal commented
Can someone sponsor this PR?

2022-07-18 17:19 UTC, closed without merging