8276549: Improve documentation about ContainerPtr encoding
openjdk/jdk pull request #8811
Opened 2022-05-20 13:28 UTC by tschatzl

Hi all,

  can I have reviews for this trivial? change to add some more documentation to `G1CardSet::ContainerPtr`?

Testing: local compilation

Thanks,
  Thomas

2022-05-21 03:54 UTC, kimbarrett requested changes
Looks good, and trivial.

2022-05-21 11:10 UTC, tschatzl commented on src/hotspot/share/gc/g1/g1CardSet.hpp
> +  // 0...00000 free               (Empty, should never happen on a top-level ContainerPtr)
```suggestion
  // 0...00000 free               (Empty, should never happen on a top-level ContainerPtr)
```

2022-05-23 08:09 UTC, tschatzl commented
@kimbarrett : I am unable to find any suggested changes, and the comment also seems to read that everything is fine. Can you confirm?

2022-05-23 08:14 UTC, walulyai approved these changes

2022-05-23 08:46 UTC, kimbarrett approved these changes

2022-05-23 08:50 UTC, closed without merging