8287312
openjdk/jdk pull request #8882
Opened 2022-05-25 11:18 UTC by albertnetymk

Simple restructuring to match the intent of the comment.

Test: hotspot_gc

2022-05-30 09:19 UTC, tschatzl requested changes

2022-05-30 09:19 UTC, tschatzl commented on src/hotspot/share/gc/g1/g1HeapVerifier.cpp
> +      r->object_iterate(&verify_oop_pointers);
This should also set `_failures` if there are any; the previous code early exited via `return true`.

2022-05-30 09:19 UTC, tschatzl commented on src/hotspot/share/gc/g1/g1HeapVerifier.cpp
> +      r->object_iterate(&verify_open_archive_oop);
This should also set `_failures` if there are any; the previous code early exited via `return true`.

2022-05-30 12:22 UTC, albertnetymk commented
Open/Closed-region verifiers use `guarantee` -- it crashes on failure. There is indeed some inconsistency: other regions verifers report the status back to the caller. Such inconsistency also exists at the top-level caller `G1HeapVerifier::verify`.

For unification, I believe using `guarantee` and discarding the "out parameter" would be cleaner, with the potential drawback of printing too little info on failure. However, when failure does occur during verification, some domain-specific knowledge is required to resolve it, so blindly printing all info is not always necessarily helpful.

2022-05-30 12:56 UTC, tschatzl commented
> Open/Closed-region verifiers use `guarantee` -- it crashes on failure. There is indeed some inconsistency: other regions verifers report the status back to the caller. Such inconsistency also exists at the top-level caller `G1HeapVerifier::verify`.
> 
> For unification, I believe using `guarantee` and discarding the "out parameter" would be cleaner, with the potential drawback of printing too little info on failure. However, when failure does occur during verification, some domain-specific knowledge is required to resolve it, so blindly printing all info is not always necessarily helpful.

Note that there is some use of printing some erroneous objects - a dev might glean some information on whether a particular class of objects is affected; there is not much point in printing all errors for all regions though. Also for  reasons it's sometimes easier to look at failures for some classes than others.

There is `G1MaxVerifyFailures` after all, but it's not implemented consistently.

So I'm not really convinced that a `guarantee` is best, but of course it depends. Since the guarantees are pre-existing I'll mark this as reviewed.

2022-05-30 12:56 UTC, tschatzl approved these changes

2022-07-04 08:35 UTC, walulyai approved these changes

2022-07-04 12:04 UTC, closed without merging