8286707: JFR: Don't commit JFR internal jdk.JavaMonitorWait events
openjdk/jdk pull request #8883
Opened 2022-05-25 12:24 UTC by jaokim

Changed the JFR chunk rotation lock object to specific internal class. This allows that specific Object.wait() event to be skipped, thus not adding JFR internal noise to recordings. 

# Testing
- jdk_jfr

2022-05-25 12:44 UTC, jaokim commented on src/jdk.jfr/share/classes/jdk/jfr/internal/FileDeltaChangeLockObject.java
> +class FileDeltaChangeLockObject {}
Or would a more general lock object be preferred? I couldn't find any more explicitly JFR related monitors in use.

2022-05-26 02:27 UTC, dholmes-ora commented
/label add hotsppot-jfr-dev

2022-05-26 02:27 UTC, dholmes-ora commented
/label add hotspot-jfr-dev

2022-05-26 02:27 UTC, dholmes-ora commented
/label add hotspot-jfr

2022-05-26 02:28 UTC, dholmes-ora requested changes
I think any filtering should be handled internally to JFR not in the ObjectMonitor code.

2022-10-14 08:47 UTC, jaokim commented
/open

2022-10-14 13:12 UTC, egahlin approved these changes

2022-10-17 02:13 UTC, dholmes-ora reviewed
I am still not happy about this approach. JFR is written in Java and so triggers numerous events that are defined for Java code - that is a simple consequence of implementing it in Java. If there is to be filtering of events that originate from JFR Java code then there should be a general purpose filtering mechanism available to say "exclude JFR code" or "include JFR code" as desired. And to me the filtering mechanism should reside in the event commit code inside the JFR code not in the event-posting code in the shared components of the VM.

2022-10-17 12:08 UTC, mgronlun commented
There exist a general exclusion/inclusion mechanism already. But it is an all-or-nothing proposition. This particular case is a thread that we can't exclude because it runs the periodic events, upon being notified. It is the notification mechanism to run the periodic events that trigger this large amount of unnecessary MonitorWait events. Even should we change it to some util.concurrent construct, we are only pushing the problem, because we might be instrumenting them later too. To work with the existing exclusion mechanism, the system would have to introduce an additional thread, which will be excluded, which only handles the notification, and then by some other means triggers another periodic thread (included) to run the periodic events.

2022-10-18 00:50 UTC, dholmes-ora commented
@mgronlun my request is that this filtering be done inside the commit logic by the JFR code, not at the site where the event is generated - ie this internal-jfr-event filtering is internalized into the JFR code.

2022-10-19 06:50 UTC, jaokim commented
I'm realizing that the monitor class isn't available elsewhere; it is in objectMonitor.cpp, and passed to private members in the `JavaObjectMonitorEvent`, which in turn is generated. The only possibility I see to moving the logic away from objectMonitor.cpp is to change how the event's classes are generated. Either by adding getter to certain members (in this case something like `get_monitorClass `to `JavaObjectMonitorEvent`), or trying to shoehorn the `is_excluded` method into the generated `JavaObjectMonitorEvent`. Neither of these approaches would I say are even worth considering, and they'd also still introduce overhead.

2022-10-19 07:53 UTC, dholmes-ora approved these changes
Thank you for making the effort to investigate alternatives, it is appreciated.

2022-10-19 10:10 UTC, jaokim commented
/integrate

2022-10-19 10:33 UTC, mgronlun commented
/sponsor

2022-10-19 10:34 UTC, closed without merging