8286850: [macos] Add support for signing user provided app image
openjdk/jdk pull request #8987
Opened 2022-06-02 05:17 UTC by sashamatveev

- Added support for signing predefined application image.
 - Following command can be used to sign predefined application images: jpackage --type app-image --app-image Test.app --mac-sign [additional signing options]
 - Main class and if --mac-app-store was specified will be saved in .jpackage.xml. Both values are required for signing. Main class is to generate default identity and --mac-app-store to do correct signing for App Store.
 - Signing is done exactly same as when generating app bundle. Unsigned, signed or partially signed app images are supported. App image will be completely unsigned before signing.

2022-06-02 17:44 UTC, alexeysemenyukoracle commented on test/jdk/tools/jpackage/macosx/SigningAppImageTwoStepsTest.java
> +        Path appimageOutput = TKit.workDir().resolve("appimage");
This should be `TKit.createTempDirectory("appimage")` to allow subsequent invocations of the test to create a new "appimage" directory if the test work directory already contains "appimage" directory from the previous test run.

2022-06-02 18:09 UTC, alexeysemenyukoracle requested changes

2022-06-02 18:09 UTC, alexeysemenyukoracle commented on test/jdk/tools/jpackage/share/jdk/jpackage/tests/PredefinedAppImageErrorTest.java
> + */
There is no  need to duplicate the whole jtreg test declaration, it supports multiple @run comments:
```
/*
 * @test
 * @summary Test jpackage output for erroneous input with --type "app-image" and --app-image
 * @library ../../../../helpers
 * @build jdk.jpackage.test.*
 * @modules jdk.jpackage/jdk.jpackage.internal
 * @compile PredefinedAppImageErrorTest.java
 * 
 * @run main/othervm/timeout=360 -Xmx512m jdk.jpackage.test.Main
 *  --jpt-run=jdk.jpackage.tests.PredefinedAppImageErrorTest
 *  --jpt-before-run=jdk.jpackage.test.JPackageCommand.useToolProviderByDefault
 * 
 * @run main/othervm/timeout=360 -Xmx512m jdk.jpackage.test.Main
 *  --jpt-run=jdk.jpackage.tests.PredefinedAppImageErrorTest
 *  --jpt-before-run=jdk.jpackage.test.JPackageCommand.useExecutableByDefault
 */
```

2022-06-02 18:09 UTC, alexeysemenyukoracle commented on test/jdk/tools/jpackage/macosx/SigningAppImageTwoStepsTest.java
> +                .removeArgumentWithValue("--main-class")
There is no point in calling `JPackageCommand.helloAppImage()` if later all arguments added by this call get deleted. Simply call JPackageCommand ctor instead.

2022-06-03 01:58 UTC, sashamatveev commented
8286850: [macos] Add support for signing user provided app image [v2]
 - Fixed all comments from Alexey.
8286850: [macos] Add support for signing user provided app image [v3]
 - Fixed whitespace issues.

2022-06-03 15:50 UTC, alexeysemenyukoracle approved these changes

2022-06-03 20:26 UTC, sashamatveev commented
/integrate

2022-06-03 20:28 UTC, closed without merging