8287493: 32-bit Windows build failure in codeBlob.cpp after JDK-8283689
openjdk/jdk pull request #9088
Opened 2022-06-08 16:50 UTC by shipilev

See the bug report for example build failure. This breakage is widely seen on many build servers. The fix follows what [https://bugs.openjdk.org/browse/JDK-8210803](JDK-8210803) did for other blobs.

Additional testing:
 - [x] Windows x86_32 fastdebug build
 - [x] Linux x86_64 fastdebug `java/foreign`
 - [x] Windows x86_32 fastdebug `java/foreign`

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.java.net/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8287493](https://bugs.openjdk.org/browse/JDK-8287493): 32-bit Windows build failure in codeBlob.cpp after JDK-8283689

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)
 * [Zhengyu Gu](https://openjdk.java.net/census#zgu) (@zhengyu123 - **Reviewer**)
 * [Alan Bateman](https://openjdk.java.net/census#alanb) (@AlanBateman - **Reviewer**)
 * [Jorn Vernee](https://openjdk.java.net/census#jvernee) (@JornVernee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/9088/head:pull/9088` \
`$ git checkout pull/9088`

Update a local copy of the PR: \
`$ git checkout pull/9088` \
`$ git pull https://git.openjdk.java.net/jdk pull/9088/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 9088`

View PR using the GUI difftool: \
`$ git pr show -t 9088`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/9088.diff">https://git.openjdk.java.net/jdk/pull/9088.diff</a>

</details>

2022-06-08 17:20 UTC, vnkozlov approved these changes
I would say it is trivial.

2022-06-08 18:19 UTC, zhengyu123 requested changes

2022-06-08 18:20 UTC, shipilev commented on src/hotspot/share/code/codeBlob.hpp
> +  void operator delete(void* p);
Not sure how well that works with non-virtual operators. We can consider that as the follow-up cleanup. Meanwhile, I'd like to push this one trivial build fix, OK?

2022-06-08 18:21 UTC, zhengyu123 commented on src/hotspot/share/code/codeBlob.hpp
> +  void operator delete(void* p);
Okay then.

2022-06-08 18:27 UTC, AlanBateman approved these changes

2022-06-08 18:54 UTC, JornVernee approved these changes
LGTM.

I thought this wasn't needed since the comment talks about a two-argument operator delete, which we don't have in this class. When I tried removing it everything seemed fine so I went with that.

Maybe good to update the comment here as well... (and maybe even in other places in codeBlob.hpp as well).

2022-06-09 05:47 UTC, shipilev commented
Thank you for reviews!

/integrate

2022-06-09 05:49 UTC, closed without merging