8286962: java/net/httpclient/ServerCloseTest.java failed once with ConnectException
openjdk/jdk pull request #9155
Opened 2022-06-14 15:20 UTC by c-cleary

**Issue**
A failure in this test was observed whereby an unexpected connection from a client that was not created by the test caused the test to unsucessfully complete. 

**Solution**
When a connection is accepted by the ServerSocket, some verification of the Request URI and of the Request Path is conducted. If the client connection is found to be invalid or external to the test, the connection is closed. The ServerSocket will continue to accept new connections until the correct parameters are met. Once a valid connection is accepted, the test behaves exactly as it previously did.

2022-06-14 16:39 UTC, dfuch requested changes
Thanks for the fix Conor! I have suggested some changes that should make the fix easier to review and keep it closer to the original.

2022-06-14 16:42 UTC, dfuch commented on test/jdk/java/net/httpclient/ServerCloseTest.java
> +                    if (validURI && path.contains("/dummy/x")) {
Since we will have already checked `path`, `method` and `uri`  here just unconditionally add the clientConnection to the list and proceed as before.

2022-06-15 11:38 UTC, dfuch approved these changes
LGTM. Please make sure the test is stable before integrating, and then drop me a note, and I will sponsor.

2022-06-15 15:09 UTC, c-cleary commented
Test appears stable after multiple runs and tier runs. Issuing integration command

2022-06-15 15:10 UTC, c-cleary commented
/integrate

2022-06-15 15:41 UTC, closed without merging