8288528: broken links in java.desktop
openjdk/jdk pull request #9195
Opened 2022-06-17 03:45 UTC by prsadhuk

doccheck reports some broken links which are rectified

2022-06-17 14:34 UTC, aivanov-jdk approved these changes

2022-06-17 14:34 UTC, aivanov-jdk commented on src/java.desktop/share/classes/java/awt/doc-files/AWTThreadIssues.html
> +<a href="https://bugs.openjdk.org/browse/JDK-4030718">
The old URL has changed to https://bugs.java.com/bugdatabase/view_bug.do?bug_id=4030718

I am for using JBS links though.

2022-06-17 14:34 UTC, aivanov-jdk commented on src/java.desktop/share/classes/javax/swing/plaf/metal/MetalLookAndFeel.java
> +     * design guidelines.
```suggestion
     * Returns a {@code LayoutStyle} implementing the Java look and feel
     * design guidelines.
```

2022-06-17 14:45 UTC, prrace requested changes

2022-06-17 14:45 UTC, prrace commented on src/java.desktop/share/classes/javax/swing/plaf/multi/doc-files/multi_tsc.html
> +<a href="https://www.comp.nus.edu.sg/~cs3283/ftp/Java/swingConnect/archive/plaf_papers_arch/multi_update/multi_update.html"
Well I am 100% sure this article wasn't originally published by the national university of singapore.
And we definitely should NOT be linking there. 
I actually think for most of these we'd be better off getting rid of the link entirely.

2022-06-17 17:43 UTC, kristylee88 approved these changes

2022-06-17 18:48 UTC, aivanov-jdk approved these changes

2022-06-17 20:45 UTC, prrace requested changes

2022-06-17 20:45 UTC, prrace commented on src/java.desktop/share/classes/java/awt/doc-files/AWTThreadIssues.html
> +<a href="https://bugs.openjdk.org/browse/JDK-4515058">
This is about Solaris IMF .. I think we don't need to worry about it any more.

2022-06-17 20:45 UTC, prrace commented on src/java.desktop/share/classes/java/awt/doc-files/AWTThreadIssues.html
> +<a href="https://bugs.openjdk.org/browse/JDK-4671025">
And even better it was resolved in 1.5 under this bug id which I guess was still open when this doc was written

2022-06-17 20:45 UTC, prrace commented on src/java.desktop/share/classes/java/awt/doc-files/AWTThreadIssues.html
> +<a href="https://bugs.openjdk.org/browse/JDK-4465537">
This bug was about some off-screen image problem with JScrollBar
It was closed as a dup of 4417287 which was fixed in 1.4

So in summary it is wrong to keep these linked bugs in here.
Remove the lot of them

2022-06-20 07:24 UTC, prsadhuk commented
will be done in jdk19 forked repo

2022-06-20 07:24 UTC, closed without merging