JDK-8288904: Incorrect memory ordering in UL
openjdk/jdk pull request #9225
Opened 2022-06-21 19:12 UTC by jdksjolen

Please review this fix for JDK-8288904, thank you.

Currently running tier1-3 tests.

2022-06-22 05:17 UTC, fisk requested changes
Might want to add a comment explaining the reason for the fence to be there.

2022-06-22 07:41 UTC, jdksjolen commented
@fisk , sure, something like this?

2022-06-22 07:45 UTC, robehn approved these changes
Thanks, looks good.

2022-06-22 12:31 UTC, dholmes-ora approved these changes
This fix in itself looks good.

But it raises a lot of questions for me about how concurrent access is actual controlled here. I can't see what stops a new reader from becoming active after we see _active_readers go to zero?

Thanks.

2022-06-22 13:54 UTC, jdksjolen commented
@dholmes-ora,

The implementation is lock-free and uses RCU.

This is approximately how it works in pseudo-code:

```
class LogOutputList {
  LogOutputNode* entry; // All threads gain entry to the linked list through this pointer
}

void LogOutputList::mutate_output_list() {
  // Save the entry pointer
  LogOutputNode* cur = entry;
  // Remove the entry pointer, now no new readers can access this list
  entry = NULL;
  // OK, we can now wait for all readers to exit
  wait_until_no_readers();
  // ... Do things we need to do to cur ...
  // Restore pointer, new readers can occur.
  entry = cur;
} 
```

There are some details here which I have omitted, but this is the gist of it.

2022-06-22 13:54 UTC, jdksjolen commented
Please sponsor this :-).

2022-06-22 18:58 UTC, pchilano commented on src/hotspot/share/logging/logOutputList.cpp
> +  OrderAccess::loadstore();
Just got curious about this memory ordering problem. How can a write after the while loop be executed(and be seen by other threads) without even knowing if we can bail out of the while loop. So I'm thinking that otherwise this program would crash:

```
volatile int never_touched_variable = 0;
int* address = (int*)0xBADC0FEE;

int main() {
	while(never_touched_variable == 0) {}
	*address = 1;
	return 0; 
}
```

2022-06-22 19:51 UTC, jdksjolen commented on src/hotspot/share/logging/logOutputList.cpp
> +  OrderAccess::loadstore();
I'm going by ARM's memory model, which is understood by me as something like: "Any nondependent loads and stores may be observed in a different order than program order". Dependency here means register or address dependency.

I think your program is allowed to crash, because I think you're invoking UB by making and dereferencing a pointer to random memory.

2022-06-22 20:17 UTC, fisk commented on src/hotspot/share/logging/logOutputList.cpp
> +  OrderAccess::loadstore();
I suppose the memory state change due to calling free on a node can reorder to before the load checking there are no readers. The. The memory can appear to be free memory and get allocated to random other memory that changes state arbitrarily, while there is still a concurrent reader.

2022-06-22 20:36 UTC, pchilano commented on src/hotspot/share/logging/logOutputList.cpp
> +  OrderAccess::loadstore();
Right but isn't there a control dependency that the hardware will still obey? Or can the hardware write to memory even if that path is never taken?
Regarding UB, I could paste the assembly of that instead (maybe I should have done that). My question was whether the cpu can execute that write instruction before even knowing if that branch will be taken.
Note: I found this interesting article about control dependencies (https://lwn.net/Articles/860037/). It mentions that the hardware will respect that dependency but there could be some aggressive compiler optimizations on some cases. I don't think that applies here though.
@fisk sorry, not sure I understood the example.

2022-06-22 20:39 UTC, fisk commented
Talked to Johan and StefanK earlier today. In general this data structure is very poorly synchronized. Nodes are injected without release store even though there are concurrent readers, there is no fencing or atomics around basically any of the heads or next pointer accesses, despite reading and writing to them concurrently. Not sure how much of it we want to rewrite in this particular patch, but it does need major reworking I think. Maybe the most reasonable option is writing a new data structure entirely. Or maybe this is one of those times where having any form of readers writer lock would make this code way easier to reason about. We already mark where the reader vs writer sections are, but with unnecessarily relaxed and fragile synchronization for what it is.
We have other places where we really want a readers writer lock and end up inventing the wheel again.
Not sure if fixing this properly should be done in this patch or a follow up patch.

2022-06-22 21:28 UTC, jdksjolen commented on src/hotspot/share/logging/logOutputList.cpp
> +  OrderAccess::loadstore();
@pchilano, it seems that it is true that a control dependency establishes that writes are not moved above the read of a control branch (as we do not know which, if any, branch is taken before the read is done). read-on-read allows for moving it up however.

For example:

```
// OK
x = true;
while(x == true) { }
y = a[0];
~>
x = true;
y = a[0];
while(x == true) {}
// NOT OK
x = true;
while(x == true) { }
a[0] = 5;
~>
x = true;
a[0] = 5;
while(x == true) {}
```

Source:

https://www.cl.cam.ac.uk/~pes20/ppc-supplemental/test7.pdf

I believe that that means that this barrier is unnecessary, but it's good manners to do the `Atomic::load`.

2022-06-22 21:57 UTC, dholmes-ora commented
> There are some details here which I have omitted, but this is the gist of it.

@jdksjolen  - it is the actual details I have concerns about. More seems to be done than just a pointer switch to unlink, and the unlink itself is not an atomic operation - are we guaranteed only a single writer is possible? And even so, as others have noted, without atomics or barriers there is no guarantee readers will see the unlink has happened. I'm a bit surprised as this code has been extensively examined in the past.

2022-06-22 22:20 UTC, fisk commented on src/hotspot/share/logging/logOutputList.cpp
> +  OrderAccess::loadstore();
Hold your horses guys. I think the logic in the cited paper is flawed. It essentially says that surely the hardware couldn't perform stores before knowing what control flow is taken, at which point the value of the load must be known. Therefore the hardware can't reorder the load and store.

Well, the hardware can speculate one branch is taken, defer the load, buffer the stores without committing them to caches, and then commit them once the load is executed, and the speculation is proven right, committing the branch. Then the already buffered stores will be published. This will yield a result equivalent to the load and store appearing to have reordered across the control dependency. It would never break a sequential program, but would reorder a LoadStore pairbseparated by a control dependency, requiring barriers.

In fact, the official ARMv8 memory model document linked here https://documentation-service.arm.com/static/6048f1aaee937942ba302655 (end of section 6.2) says explicitly that the control dependency is *not* enough to prevent ordering between a load and a store, and that you need explicit barriers if you don't want reordering.

So basically I would rather trust the official ARM documentation that explicitly says it may reorder, than an academic paper saying it isn't possible because building such hardware would be tricky. It's essentially proof by lack of imagination IMO.

It would be interesting I guess, to run the "S" litmus test on the failing machine. Although I wouldn't want to rely on control dependency tricks for ordering regardless of the outcome. I would follow the spec and assume reordering can happen, as it clearly states.

2022-06-23 00:25 UTC, pchilano commented on src/hotspot/share/logging/logOutputList.cpp
> +  OrderAccess::loadstore();
@jdksjolen, @fisk thanks for the investigation and linked documents! Mmm there seems to be contradictory definitions then. I also found [1] which as I understand it defines there should be an order between those instructions (sections B2.3.2 and B2.3.3; there is even an intent Note about that). But the fact that we have to look this up and check the fine print is already surprising for me. I thought any cpu would provide that guarantee.
 
[1] Arm Architecture Reference Manual: https://documentation-service.arm.com/static/623b2de33b9f553dde8fd3b0

2022-06-23 06:41 UTC, fisk commented on src/hotspot/share/logging/logOutputList.cpp
> +  OrderAccess::loadstore();
Interesting find! So we have 2 ARMv8 memory model documents from ARM, one explicitly saying it may reorder and one explicitly saying it may not.
Since the document saying it won't reorder is more recent, I guess they might have completely changed their minds about this. Has happened before, and seems fine.

While similarly to how we don't exploit data dependency without language level guarantees (we are writing C++, not assembly), I would not exploit control dependencies either, without a C++ level contract saying that's fine, defined in a C++ context. So we should have fences anyway.

However, I would have to assume that ARM would only really be able to update the spec to say this won't reorder, if they knew there are no implementations where it does. So that might at least provide a clue that maybe the reason this code crashed, is due to something different, like maybe the lack of release when allocating new list entries that are injected into the list. So while we might want some fence here anyway, it seems likely it won't stop this code from crashing.

Is it time to wrap the whole thing in a readers writer lock? We already increment and decrement a global variable on the reader side, and writes barely ever happen, but are marked with a lock for writers. It would seemingly fix the problems.

2022-06-23 07:03 UTC, robehn commented
> Talked to Johan and StefanK earlier today. In general this data structure is very poorly synchronized. Nodes are injected without release store even though there are concurrent readers, there is no fencing or atomics around basically any of the heads or next pointer accesses, despite reading and writing to them concurrently. Not sure how much of it we want to rewrite in this particular patch, but it does need major reworking I think. Maybe the most reasonable option is writing a new data structure entirely. Or maybe this is one of those times where having any form of readers writer lock would make this code way easier to reason about. We already mark where the reader vs writer sections are, but with unnecessarily relaxed and fragile synchronization for what it is. We have other places where we really want a readers writer lock and end up inventing the wheel again. Not sure if fixing this properly should be done in this patch or a follow up patch.

If I remember correctly I suggested this code should use the global counter instead.

On control flow dependencies, even compiler can change the control flow so this is an issue on x86 also. (in this case the variable is volatile, so it eliminates must issue).

According to "Who's afraid of a big bad optimizing compiler?" even this is buggy:
```
// Writer, stores are ordered
y = 1;
OrderAccess::storestore();
Atomic::store(&x, 1);

// Reader
int xr = Atomic::load(&x);
OrderAccess::loadstore();
if (xr == 1)
  y = 0;
 
// Compiler can re-write the reader as:
int xr = Atomic::load(&x);
OrderAccess::loadstore();
if (xr == 1)
   if (y != 0) // <--- can be reordered with load of x
     y = 0;
```
This particular compiler re-write seems to be very, very uncommon, but legal.

2022-07-27 13:00 UTC, jdksjolen commented
I've now re-run tier1-3 tests and they are fully passing (excluding an issue fixed in 8291289). I propose that this patch is merged as is and a new ticket is added to evaluate and perhaps rewrite this implementation.

@dholmes-ora , I believe that it is meant to be multiple reader, single writer. It seems that this is only altered through `LogConfiguration`, which holds the `ConfigurationLock` during reading and writing. I assume that people have accepted this code as correct as empirically it works.

2022-07-29 08:11 UTC, jdksjolen commented
This PR is still looking for a sponsor. @dholmes-ora, would you mind sponsoring this?

2022-07-30 07:33 UTC, dholmes-ora commented
/sponsor

2022-07-30 07:34 UTC, closed without merging