JDK-8290020 Deadlock in leakprofiler::emit_events during shutdown
openjdk/jdk pull request #9465
Opened 2022-07-12 10:39 UTC by LudwikJaniuk

Add a boolean parameter to Jfr::on_vm_shutdown to differentiate the "called from java" case, and in that case to not call JfrEmergencyDump::on_vm_shutdown.

2022-07-12 11:44 UTC, LudwikJaniuk commented
trying to trigger jcheck...

2022-07-12 13:11 UTC, mgronlun requested changes
Good work Ludvig, thanks for fixing this.

2022-07-12 13:18 UTC, LudwikJaniuk commented on test/jdk/jdk/jfr/jvm/TestDumpOnCrash.java
> +        test(CrasherHalt.class, "", true, dumppath.toString(), false);
Fine by me

2022-07-12 13:23 UTC, dholmes-ora commented
What exactly is the constraint on calling `JfrEmergencyDump::on_vm_shutdown`? Is it that there must not be any Java frames on the stack? While it would be very unlikely in theory there is nothing to stop a daemon Java thread from calling a native method which calls JNI DestroyJavaVM, and so we get to `before_exit` in a "non-halt" case but the thread is no different to one that would call Runtime.halt().

2022-07-12 13:27 UTC, dholmes-ora commented
> What exactly is the constraint on calling `JfrEmergencyDump::on_vm_shutdown`? Is it that there must not be any Java frames on the stack? While it would be very unlikely in theory there is nothing to stop a daemon Java thread from calling a native method which calls JNI DestroyJavaVM, and so we get to `before_exit` in a "non-halt" case but the thread is no different to one that would call Runtime.halt().

But if that happens we have worse problems anyway as there is no concurrency control for shutting down the VM that way.

2022-07-12 13:30 UTC, dholmes-ora approved these changes
It would be nicer if `JfrEmergencyDump::on_vm_shutdown` could detect whatever condition actually causes it a problem in the `halt()` case and do nothing; but I don't know how hard that is to detect.

The proposed workaround is okay.

Thanks.

2022-07-12 15:27 UTC, LudwikJaniuk commented
/integrate

2022-07-12 15:46 UTC, egahlin approved these changes

2022-07-12 15:52 UTC, egahlin commented
/sponsor

2022-07-12 15:54 UTC, closed without merging

2022-07-14 05:53 UTC, dholmes-ora commented
@mgronlun  or @egahlin do you have any feedback on my query above?

2022-07-14 09:14 UTC, egahlin commented
> @mgronlun or @egahlin do you have any feedback on my query above?

The emergency dump was added because we could not execute Java code during JVM crash and the code to extract a recording file from a core dump was hard to maintain. 

The functionality was never meant to be triggered from Java.

One could argue the emergency dump should happen if somebody calls Runtime::halt(int), but I don't think that's what users want. Most likely they want a fast exit. If they call System.exit(int), JFR will do an ordinary dump in the shutdown hook, assuming JFR has been setup to dump on exit.

2022-07-14 10:18 UTC, mgronlun commented
Runtime.halt() is tricky in that this method does not cause shutdown hooks to be started. If the shutdown sequence has already been initiated then this method does not wait for any running shutdown hooks to finish their work. This means it could deadlock with the normal Leakprofiler dump logic, issued either by the thread that stops a recording or if the shutdown hooks have already started, with the shutdown hook. It was an oversight to not exclude Runtime.halt() from calling into the emergency dump logic. One could argue that it could be distinguished in that it does not pass the exception handler, so we are not crashing. Unfortunately, that is only one part of the problem because we also attempt to emit the emergency dump in cases of out-of-memory, which is very hard to coordinate correctly.