8290376
openjdk/jdk pull request #9517
Opened 2022-07-15 14:14 UTC by albertnetymk

Introducing a more intuitive implementation.

This PR consists of two commits: the first adds the new algorithm and verifies the result is same as before. The second commit removes the old implementation.

Test: tier1-6 for the first commit.

2022-08-22 08:58 UTC, tschatzl requested changes

2022-08-22 08:58 UTC, tschatzl commented on src/hotspot/share/gc/g1/g1MMUTracker.cpp
> +  // Clamp it by max
```suggestion
    // If the pause is over the maximum, just assume that it's the maximum.
```
I would prefer the original comment as it explicitly states that this is a conscious decision.

2022-08-22 08:58 UTC, tschatzl commented on src/hotspot/share/gc/g1/g1MMUTracker.cpp
> +// time inside [deficit, current_timestamp], is equal to gc_budget. Next,
`gc_budget` is not defined anywhere in this comment or the diagram. This is confusing.

2022-08-22 08:58 UTC, tschatzl commented on src/hotspot/share/gc/g1/g1MMUTracker.cpp
> +  // Iterate from newest to oldest
```suggestion
  // Iterate from newest to oldest.
```

2022-08-22 08:58 UTC, tschatzl commented on src/hotspot/share/gc/g1/g1MMUTracker.cpp
> +    // Outside the window
```suggestion
    // Outside the window.
```

2022-08-22 08:58 UTC, tschatzl commented on src/hotspot/share/gc/g1/g1MMUTracker.cpp
> +    // Would exceed the budget; strictly greater than
```suggestion
    // This duration would exceed the budget. Check for strictly greater than.
```
Not sure what the "[Check for ]strictly greater than" adds, but it's okay.

2022-08-22 08:58 UTC, tschatzl commented on src/hotspot/share/gc/g1/g1MMUTracker.cpp
> +      // The timestamp where a budget deficit occurs.
```suggestion
      // This GC event contains the timestamp where the budget deficit occurs.
```

2022-08-22 08:58 UTC, tschatzl commented on src/hotspot/share/gc/g1/g1MMUTracker.cpp
> +  // No enough gc time inside the window; a budget surplus
```suggestion
  // Not enough gc time spent inside the window, we have a budget surplus.
```

2022-08-24 09:14 UTC, tschatzl approved these changes
Lgtm.

2022-08-25 07:27 UTC, walulyai approved these changes

2022-08-25 09:13 UTC, albertnetymk commented
Thanks for the review.

/integrate

2022-08-25 09:15 UTC, closed without merging