8255691: Shenandoah: Invoke native-LRB only on non-strong refs
openjdk/jdk pull request #961
Opened 2020-10-30 18:12 UTC by rkennke

The way that current native LRB is implemented is wrong (but non-fatal) and misleading. It's purpose is to prevent resurrection of unreachable non-strong references, and it should only be invoked on non-strong references, not all native references. This distinction will become even more important once we get concurrent reference processing: then we also want to invoke this barrier on referent-loads.

This changes the runtime-part of native-LRB so that it is only invoked when it's invoked with non-strong reference decorator. Otherwise it acts as regular LRB.

Testing: hotspot_gc_shenandoah

2020-10-30 18:38 UTC, zhengyu123 reviewed
Just a quick scan. 
We probably should also rename ShenandoahRuntime::load_reference_barrier_native() to something like load_reference_barrier_on_weak()(?)  also BS::use_load_reference_barrier_native()

2020-11-02 13:44 UTC, zhengyu123 approved these changes

2020-11-02 13:44 UTC, zhengyu123 commented on src/hotspot/share/gc/shenandoah/c2/shenandoahSupport.cpp
> +  address calladdr = is_native ? CAST_FROM_FN_PTR(address, ShenandoahRuntime::load_reference_barrier_weak)
Please rename is_native -> is_weak.

2020-11-02 14:08 UTC, rkennke commented
/integrate

2020-11-02 14:11 UTC, closed without merging

2020-11-02 14:11 UTC, shipilev requested changes
Generally looks good, some minor nits.

2020-11-02 14:11 UTC, shipilev commented on src/hotspot/share/gc/shenandoah/c2/shenandoahBarrierSetC2.cpp
>      // If one input is NULL, then step over the barriers (except LRB native) on the other input
Should be `weak LRB`, not `LRB native` now? Probably text search for `native` elsewhere?

2020-11-02 14:11 UTC, shipilev commented on src/hotspot/share/gc/shenandoah/shenandoahBarrierSet.cpp
> +  return ((decorators & IN_NATIVE) != 0) && ((decorators & ON_STRONG_OOP_REF) == 0);
This would change with conc ref processing, right? Currently this only accepts "native" + "weak" LRBs.

2020-11-02 14:11 UTC, shipilev commented on src/hotspot/share/gc/shenandoah/shenandoahBarrierSet.inline.hpp
> +  // Prevent resurrection of unreachable non-strorg references.
Typo: "non-strorg"