8282651: ZGC: vmTestbase/gc/ArrayJuggle/ tests fails intermittently with exit code 97
openjdk/jdk pull request #9645
Opened 2022-07-26 16:18 UTC by rsunderbabu

Fixing JuggleTests for OOME.
The JuggleTests continuously allocate memory and juggle them in various array positions. Over the course of allocation, heap might be fully filled, esp in high memory strategy. The test doesn't take into account OOME and run under the assumption that any freed memory would be immediately GCed. Immediate GC under memory stress is not guaranteed. Hence it is better to explicitly call WhiteBox API to do the job.

2022-07-26 18:20 UTC, lmesnik requested changes

2022-08-24 16:18 UTC, rsunderbabu commented
The test is multi-threaded. The calculation for memory doesn't take into account that the allocation is done in parallel by many threads. Hence, added the number of memory allocating threads in the object size calculation.

2022-08-28 04:19 UTC, rsunderbabu commented
@lmesnik I have simply reduced the number of threads that juggle. Tested against all GCs.

2022-08-31 16:13 UTC, lmesnik commented on test/hotspot/jtreg/vmTestbase/gc/ArrayJuggle/Juggle01/Juggle01.java
> +        private static int NUM_JUGGLE_THREADS = 4;
Could you please make number of threads depend on the CPU?

2022-10-27 05:09 UTC, closed without merging