8282729: Serial: Move BOT implementation to collector specific directory
openjdk/jdk pull request #9662
Opened 2022-07-27 18:04 UTC by xmas92

Moves serial code from `share/gc/shared/blockOffsetTable.*` to `share/gc/serial/serialBlockOffsetTable.*`
Move required fixing up some missing header files.
Refactoring tries to respect `INCLUDE_SERIALGC` without changing any behaviour. 

Given that `--disable-jvm-feature-serialgc` will not build before this change, it will not build afterwards either. However it does now compile, but will fail to link. 

The diff below is enough to for `make hotspot` to run (on `macosx-aarch64`), but it will not build the complete JDK as the build system will use the compiled binaries with `-XX:+UseSerialGC` which obviously won't work as that GC is missing.
```diff
diff --git a/src/hotspot/share/gc/shared/genCollectedHeap.cpp b/src/hotspot/share/gc/shared/genCollectedHeap.cpp
index 5558f1a4a32..79b465b3e0a 100644
--- a/src/hotspot/share/gc/shared/genCollectedHeap.cpp
+++ b/src/hotspot/share/gc/shared/genCollectedHeap.cpp
@@ -31,7 +31,6 @@
 #include "code/icBuffer.hpp"
 #include "compiler/oopMap.hpp"
 #include "gc/serial/defNewGeneration.hpp"
-#include "gc/serial/markSweep.hpp"
 #include "gc/shared/adaptiveSizePolicy.hpp"
 #include "gc/shared/cardTableBarrierSet.hpp"
 #include "gc/shared/cardTableRS.hpp"
@@ -80,6 +79,9 @@
 #if INCLUDE_JVMCI
 #include "jvmci/jvmci.hpp"
 #endif
+#if INCLUDE_SERIALGC
+#include "gc/serial/markSweep.hpp"
+#endif
 
 GenCollectedHeap::GenCollectedHeap(Generation::Name young,
                                    Generation::Name old,
@@ -204,9 +206,9 @@ void GenCollectedHeap::post_initialize() {
   initialize_size_policy(def_new_gen->eden()->capacity(),
                          _old_gen->capacity(),
                          def_new_gen->from()->capacity());
-
+#if INCLUDE_SERIALGC
   MarkSweep::initialize();
-
+#endif
   ScavengableNMethods::initialize(&_is_scavengable);
 }
 
diff --git a/test/hotspot/gtest/gc/shared/test_collectorPolicy.cpp b/test/hotspot/gtest/gc/shared/test_collect
orPolicy.cpp
index dfe096248c7..30a24fd9232 100644
--- a/test/hotspot/gtest/gc/shared/test_collectorPolicy.cpp
+++ b/test/hotspot/gtest/gc/shared/test_collectorPolicy.cpp
@@ -31,6 +31,7 @@
 #include "utilities/macros.hpp"
 #include "unittest.hpp"
 
+#if INCLUDE_SERIALGC
 class TestGenCollectorPolicy {
  public:
 
@@ -279,3 +280,4 @@ TEST_OTHER_VM(CollectorPolicy, old_cmd) {
 
   TestGenCollectorPolicy::TestWrapper::test(&setter_old_size, &setter_max_new_size, &checker_large);
 }
+#endif
```

There is still a lot of Serial only code in the shared code base. The `share/gc/shared/space.*` is a clear next candidate for refactoring as this change required a bunch of code in there to depend on `INCLUDE_SERIALGC` to build. 

Testing: Tier 1

2022-07-28 09:57 UTC, tschatzl requested changes
Can you check tier4/tier5, which includes the serviceability tests after these changes (just do tier1-5 to be safe).

Looks good apart from this request to rerun testing.

2022-07-29 07:19 UTC, xmas92 commented
Passed: tier 2-5
`java/lang/ProcessBuilder/PipelineLeaksFD.java` failed in tier 1. But it succeeded in the previous run (same source) and succeeded when I reran tier 1. Given that the test is working with os pipes it seems unrelated to this PR.

2022-07-29 15:40 UTC, tschatzl approved these changes
Thanks.

2022-08-15 12:18 UTC, albertnetymk commented
It's a bit surprising to see changes to other collectors in a commit titled "Serial: ...". I guess that's what you meant by "Move required fixing up some missing header files." I wonder if you can extract those fixes in another PR(s), which, IMO, would also make reviewing this PR slightly easier. Basically keeping each PR more focused.

2022-08-15 13:50 UTC, xmas92 commented
> It's a bit surprising to see changes to other collectors in a commit titled "Serial: ...". I guess that's what you meant by "Move required fixing up some missing header files." I wonder if you can extract those fixes in another PR(s), which, IMO, would also make reviewing this PR slightly easier. Basically keeping each PR more focused.

It seems a bit ugly to leave the repository in an intermediate state where some headers are included only because there is something, somewhere else, that need that include. But if it makes the review easier I'll move 
```diff
-#include "gc/shared/gc_globals.hpp"
-#include "memory/virtualspace.hpp"
```
into a different issue, so G1 and Epsilons still have all their required (indirect) includes.

2022-08-18 13:56 UTC, albertnetymk approved these changes
Thank you for the update. Now I can use `git diff --color-moved=dimmed_zebra` to ignore pure "moves".

I actually think `BlockOffsetTable.hpp` is better than `serialBlockOffsetTable.hpp`, as it matches the type name. The counterpart would be `ObjectStartArray` in the `Parallel` collector, which also has a relatively long name, unlike G1.

Either way, this PR is good to go.

2022-08-18 15:20 UTC, xmas92 commented
I agree, used that name because of the `All source files must have a globally unique basename. The build system depends on this uniqueness.` rule. 
But it will be cleaner if the `BlockOffsetTable.hpp` still in shared would be named something like `BOTConstants.hpp` or `BlockOffsetTableConstants.hpp`. However that change would change the header includes in a lot of files, but as it is only a rename maybe it is ok? From a review perspecive.

Regardless want to integrate #9921 / [JDK-8292606](https://bugs.openjdk.org/browse/JDK-8292606) before this so the header files in whatever `shared/BlockOffsetTable.hpp` will be called can be cleaned up.

2022-08-23 07:58 UTC, tschatzl approved these changes
Still good.

2022-08-23 08:12 UTC, xmas92 commented
/integrate

2022-08-24 09:48 UTC, albertnetymk commented
/sponsor

2022-08-24 09:50 UTC, closed without merging