8051627: Invariants about java.net.URI resolve and relativize are wrong
openjdk/jdk pull request #9671
Opened 2022-07-28 06:48 UTC by tkiriyama

The current documentation of URI class describes relationship between resolve and relativize methods as follows.

```
For any two normalized URIs u and v,
    u.relativize(u.resolve(v)).equals(v) and
    u.resolve(u.relativize(v)).equals(v) .
```

However, there are some cases where this relationship is not true. For example, when u and v are "http://a/b" and "c/d", respectively, both u.relativize(u.resolve(v)) and u.resolve(u.relativize(v)) equal to "http://a/c/d" not "c/d". The documentation should be updated to avoid confusion by describing the relationship between resolve nd relativize methods under certain conditions of the URI. Note that these conditions are sufficient but not necessary for the statement.

2022-07-28 06:49 UTC, tkiriyama commented
/csr

2022-08-07 23:56 UTC, tkiriyama commented
Could anyone please reviwe this fix?

2022-08-11 14:33 UTC, dfuch requested changes
I believe you are correct. Could you update the UriTest with some examples and counter-examples to validate this claim?

2022-08-11 14:33 UTC, dfuch commented on src/java.base/share/classes/java/net/URI.java
> + * or slash character ({@code '/'}). Then, the following statement is true.
A colon ':' may be more appropriate than a period '.' at the end of this sentence:
I'd suggest:
> Then, the following statement is true:

2022-08-11 14:33 UTC, dfuch commented on src/java.base/share/classes/java/net/URI.java
> + * and <i>v</i> be any normalized absolute URI. Then, the following statement is true.
Same remark here.

2022-08-11 14:34 UTC, dfuch commented
/csr needed

2022-09-16 07:20 UTC, tkiriyama commented
@dfuch 
Thank you for your review and suggestions.

> A colon ':' may be more appropriate than a period '.' at the end of this sentence:
> I'd suggest:

You’re right. I changed to use a colon.

> Could you update the UriTest with some examples and counter-examples to validate this claim?

I added tests in URI/Test.java.  
The tests include testing if the resolve-relativize relationship stand when the two URIs meet the condition of the modified javadoc.  
The tests also include testing if the relationship does not stand when the two specific URIs which meets the condition of the original javadoc are given. These URIs are excluded by the condition of the modiied javadoc.

2022-09-28 11:11 UTC, dfuch commented
Hi @tkiriyama sorry for taking so long to get back to you. I had a look at the CSR - and fixed a few missing fields, and added myself as reviewer. Please move its state to "Proposed" to get this moving further.

2022-09-29 07:17 UTC, tkiriyama commented
@dfuch 
Thank you for your reply.
I moved CSR's status to "PROPOSED". Please review it.

2022-11-01 04:10 UTC, tkiriyama commented
This pull request is waiting for the CSR.

2022-11-24 04:05 UTC, tkiriyama commented
@dfuch 
The CSR of this pull request was moved to "CLOSED".   
Could you review this pull request again?

2022-11-24 11:52 UTC, dfuch approved these changes

2022-11-24 11:55 UTC, dfuch commented
Done! Thanks for reminding me.

2022-11-24 11:56 UTC, dfuch commented
If you need a sponsor please drop a note here after integrating.

2022-11-24 12:07 UTC, tkiriyama commented
/integrate

2022-11-24 12:11 UTC, tkiriyama commented
Thank you for your review. Could you sponsor this pull request, please?

2022-11-24 16:15 UTC, dfuch commented
/sponsor

2022-11-24 16:17 UTC, closed without merging