JDK-8292071: NMT: move MallocHeader to its own header and inline header checks
openjdk/jdk pull request #9801
Opened 2022-08-09 05:40 UTC by tstuefe

MallocHeader should be moved into its own header in preparation for further NMT changes.

Also, malloc header check routines - that are called on every free and realloc - should be inlined.

2022-08-10 06:52 UTC, MBaesken approved these changes
LGTM

2022-08-10 11:00 UTC, RealLucy requested changes
Changes are duplicated by #9802. Why this? Isn't this one obsolete then?

2022-08-10 15:41 UTC, tstuefe commented
> Changes are duplicated by #9802. Why this? Isn't this one obsolete then?

#9802 builds atop of this PR. I experimented with PR sequences to speed up work while keeping changes fine granular and easy to review.

2022-08-10 22:13 UTC, RealLucy commented
I experimented with PR sequences to speed up work while keeping changes fine granular and easy to review.

I understand the motivation but don't really like the approach. It's basically mixing changes.

2022-08-10 22:13 UTC, RealLucy approved these changes
With the explanation given: LGTM.

2022-08-11 00:34 UTC, iklam approved these changes
LGTM.

2022-08-11 05:25 UTC, tstuefe commented
Thanks @MBaesken , @RealLucy and @iklam !

/integrate

2022-08-11 05:27 UTC, closed without merging