8285405: add test and check for negative argument to HashMap::newHashMap et al
openjdk/jdk pull request #9806
Opened 2022-08-09 09:36 UTC by jaikiran

(This is a recreation of a previous pull request which had received some reviews https://github.com/openjdk/jdk/pull/9036. I had to delete that personal branch and recreate it due to some git issues)

Can I please get a review of this change which addresses https://bugs.openjdk.java.net/browse/JDK-8285405?

2022-08-09 09:38 UTC, jaikiran commented
Hello Stuart (@stuart-marks), as suggested by you in the pull request that you previously reviewed, I've now moved the tests to `HashMap/WhiteBoxResizeTest` and it now tests the new APIs using (only) `-1` as the negative input.

2022-08-09 10:07 UTC, ChrisHegarty approved these changes
LGTM

2022-08-09 17:03 UTC, naotoj approved these changes
Looks good as it stands.

2022-08-09 17:03 UTC, naotoj commented on test/jdk/java/util/HashMap/WhiteBoxResizeTest.java
> +    }
Could utilize `assertThrows`, instead of try-catch.

2022-08-09 18:05 UTC, LanceAndersen requested changes

2022-08-10 02:49 UTC, jaikiran commented
Thank you Chris, Lance and Naoto for the reviews.

I've now updated the PR to use `assertThrows` as suggested by Naoto and Lance.

2022-08-10 10:03 UTC, LanceAndersen approved these changes

2022-08-10 23:56 UTC, stuart-marks approved these changes
Thanks for following up on this. Looks good.

2022-08-11 02:15 UTC, jaikiran commented
Thank you everyone for the reviews.

2022-08-11 02:15 UTC, jaikiran commented
/integrate

2022-08-11 02:17 UTC, closed without merging