JDK-8289510 : Improve test coverage for XPath Axes: namespace
openjdk/jdk pull request #9906
Opened 2022-08-17 15:32 UTC by mahendrachhipa

Added tests for namespace Axis. Tests incluse namspace expressions, namespace node counts and namespace node scope.

2022-08-17 15:33 UTC, mahendrachhipa commented
Hi @JoeWang-Java , Could you please review this PR.

2022-08-18 16:05 UTC, JoeWang-Java reviewed
Thanks Mahendra! 

In general, it would be good to add javadoc/notes to each test and data provider.

The test cases themselves look okay, although they are a bit repetitive in that they are all in the form of a forward axis starting from the root. In practical use cases, it's most useful to perform node test with various namespace-related functions in order to locate a node or nodeset. Namespace changes the way how a node or nodeset is located, e.g. /a/b/c finds c, but as soon as namespace(s) are added, that same xpath expression no longer finds it. I remember sub-task JDK-8289948 (https://github.com/openjdk/jdk/pull/9633) had some of that. It would be good to discuss with Bill @bwhuang-us  or have Bill review this PR, as we talked about more comprehensive test coverage for namespaces in this sub-task.

2022-08-18 16:05 UTC, JoeWang-Java commented on test/jaxp/javax/xml/jaxp/unittest/xpath/XPathExpNamespaceTest.java
> +                {"/Customers/Customer/Address/namespace::*", 2},
Duplicate test cases.

2022-08-26 00:02 UTC, bwhuang-us commented
One last thing I'd like to add is the default namespace, notated as xmlns="". Since this will impact most of the existing test cases, I am fine with adding it to one of the grandchildren and testing from there.

2022-08-31 21:37 UTC, bwhuang-us requested changes

2022-09-01 14:40 UTC, bwhuang-us approved these changes

2022-09-01 17:41 UTC, mahendrachhipa commented
/integrate

2022-09-01 17:42 UTC, closed without merging