JDK-8292586: simplify cleanups in NTLMAuthSequence getCredentialsHandle
openjdk/jdk pull request #9914
Opened 2022-08-18 10:03 UTC by MBaesken

NTLMAuthSequence getCredentialsHandle has a number of cleanup paths doing various JNU_ReleaseStringPlatformChars calls; those could be placed at one place in the function.

2022-08-18 10:59 UTC, Michael-Mc-Mahon requested changes
Looks good. Minor suggestion that the check in line 144 be changed to:

if (ss == SEC_E_OK) {

which complements the change to the initialization of variable ss.

2022-08-18 11:40 UTC, MBaesken commented
> Looks good. Minor suggestion that the check in line 144 be changed to:
> 
> if (ss == SEC_E_OK) {
> 
> which complements the change to the initialization of variable ss.

Hi Michael, I adjusted the check.

2022-08-18 13:52 UTC, Michael-Mc-Mahon approved these changes
looks good to me.

2022-08-23 07:29 UTC, MBaesken commented
/integrate

2022-08-23 07:31 UTC, closed without merging